### ISSUE TITLE
Problem with ODataResourceDeserializer's ReadInline method

### ISSUE THREAD

**Issue by ysmoradi** [OData/WebApi#1005]
In following codes:

https://github.com/OData/WebApi/blob/326d9a497f9de8f48b9fe483846dc7387c789532/src/System.Web.OData/OData/Formatter/Deserialization/ODataResourceDeserializer.cs#L78-L93

You've developed:

`if (edmType.IsComplexType() && item == null) return;`

Later you've developed:

```
if (edmType == null) 
{ 
     throw Error.ArgumentNull("edmType"); 
} 

```

This has no meaning at all.

**Comment by xuzhg** [comment]
Merge at https://github.com/OData/WebApi/commit/b62968f8cbc6d4c4da26e5bd7ec9161fa1b1e823
