### ISSUE TITLE
method removed from DeltaOfTStructuralType

### ISSUE THREAD

**Issue by figuerres** [OData/WebApi#1006]
https://github.com/OData/WebApi/blob/master/src/System.Web.OData/OData/DeltaOfTStructuralType.cs

what happened to   GetEntity() method ??
I am updating some code that was calling Validate()   with Delta<T>  patch
where T is an entity from an EF model and i am in an Odata 4 Controller.

code that was valid was  Validate(patch.GetEntity());

now the method is gone.  is there any documentation on how to update an Odata Controller to validate the model before trying to update the EF model ??

**Comment by chester29** [comment]
I am having the same issue. 
I want to update from OData V3 to V4 but this problem has halted my progress in the all my Patch action methods of my controllers.
I notice the method is included in the Microsoft documentation for System.Web.Odata at [https://msdn.microsoft.com/en-us/library/mt153356(v=vs.118).aspx#M:System.Web.OData.Delta`1.GetEntity](url)
Can we get some clarification on this please?

**Comment by xuzhg** [comment]
@figuerres @chester29 

I think it is changed to "https://github.com/OData/WebApi/blob/master/src/System.Web.OData/OData/DeltaOfTStructuralType.cs#L237"

**Comment by S1r-Lanzelot** [comment]
Updated url: https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs#L237
