### ISSUE TITLE
Add support to WebApi for $compute

### ISSUE THREAD

**Issue by mtroth-microsoft** [OData/WebApi#1008]
Once the ODL parsers support $compute, it would be great to see WebApi extend to this query option as well.

**Comment by xuzhg** [comment]
@mtroth-microsoft Would you please some links or material about the $compute $compute supported in ODL in this issue?

**Comment by mtroth-microsoft** [comment]
@xuzhg 
$compute is supported in the parser for both query option based queries and for options nested inside of an $expand. as far as I know, $compute support in the parser is equal in scope to the spec for $compute.
http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html

**Comment by markdreyer** [comment]
Any idea on the priority of this request? I would be willing to contribute if nobody else is working on this.

**Comment by xuzhg** [comment]
@markdreyer Any contribution is welcome.

**Comment by evilB** [comment]
Was there any progress made? Does compute or $compute work in any way?

**Comment by markdreyer** [comment]
I attempted, but was not able to get the project to build in vscode. I ended up using a work-around that did not require a code change.

**Comment by gathogojr** [comment]
Support for $compute and $search implemented in [AspNet Core OData](https://github.com/OData/AspNetCoreOData)
Blog https://devblogs.microsoft.com/odata/compute-and-search-in-asp-net-core-odata-8/
