### ISSUE TITLE
Support CRUD on single dynamic property of open type

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#103]
Do we want to support CRUD on single dynamic property of the open type?  
  
for example:  
  
Get ~/Customers(1)/MyDynamicPropertName  
  
Post ~/Customers(1)/MyDynamicPropertName  
  
Put ~/Customers(1)/MyDynamicPropertName  
  
Patch ~/Customers(1)/MyDynamicPropertName  
  
Delete ~/Customers(1)/MyDynamicPropertName  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1942](http://aspnetwebstack.codeplex.com/workitem/1942)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	May 14, 2014 at 7:25 AM
**Reported by:**	xuzhg
**Updated on:**	Nov 17, 2014 at 8:56 PM
**Updated by:**	ificator

**Comment by LianwMS** [comment]
On *2014-11-18 03:40:57 UTC*, **ificator** commented:

We'd definitely like this capability added in the not too distance future. Please make sure it supports nesting:

Get ~/Customers(1)/MyDynamicPropertyName/AnotherProperty

Since MyDynamicPropertyName is dynamic AnotherProperty will also have to be parsed as a dynamic property. That's fine - the controller make determine whether it's actually dynamic or not depending on the type of MyDynamicPropertyName.

**Comment by LianwMS** [comment]
On *2014-11-18 04:56:17 UTC*, **ificator** commented:

Also, it would be nice if the AttributeRoutingConvention provided a mechanism for matching dynamic properties generically. E.g.

[ODataRoute("/MyEntitySet/{key}/{propertyName}]
public IHttpActionResult GetProperty([FromODataUrl] string key, string propertyName)
{
...
}

**Comment by ificator** [comment]
I've done part of this work - it's been sitting as a pull request for over a week. Can someone look at it?

https://github.com/OData/WebApi/pull/222

**Comment by xuzhg** [comment]
@ificator Thanks your contribution. @LiangwMS will follow up your pull request.

**Comment by xuzhg** [comment]
Liang is working on similar issue. Re-assign it to him. Thanks.

**Comment by VikingsFan** [comment]
Checked in ac72f756dcdedc967e5a37c388281d357f7ff980
