### ISSUE TITLE
Support dynamic property on query option

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#104]
for example:  
  
Get ~/Customers?$filter=MyDynamicProperty eq 'xxx'  
  
or  
  
Get ~/Customers$orderby=MyDynamicProperty  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1943](http://aspnetwebstack.codeplex.com/workitem/1943)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	May 14, 2014 at 7:26 AM
**Reported by:**	xuzhg
**Updated on:**	Nov 17, 2014 at 7:12 PM
**Updated by:**	ificator

**Comment by LianwMS** [comment]
On *2014-11-18 03:11:54 UTC*, **ificator** commented:

Please also include $select

Get ~/Customers?$select=MyDynamicProperty

Get ~/Singleton?$expand=ContainedNav($select=MyDynamicProperty)

**Comment by connected-web-development** [comment]
I've just commited a changeset which partially does this. See:
https://github.com/connected-web-development/WebApi/commit/2ece3903cc8e5b0b51cb2120ca34dd86e6b51ba3

However it does not yet work with the EnableQuery attribute as the custom properties are gone before the writing starts in that case.

**Comment by connected-web-development** [comment]
My latest commit:
https://github.com/connected-web-development/WebApi/commit/5148c6ecb64715c15df5a685dbee40b307303479

also supports the EnableQuery attribute.

**Comment by connected-web-development** [comment]
I've made a pull request for it:
https://github.com/OData/WebApi/pull/250

**Comment by VikingsFan** [comment]
checked in 3f43633

**Comment by VikingsFan** [comment]
The Doc is http://odata.github.io/WebApi/#04-09-query-by-dynamic-properties
