### ISSUE TITLE
Is Odata-HttpGet‘s Parameter class ？

### ISSUE THREAD

**Issue by a764578566** [OData/WebApi#1047]
asp.net-HttpGet‘s Parameter allows is class
`public IActionResult Get([FromUri]PersonInfo person)
{
}`

**Comment by xuzhg** [comment]
@a764578566 you should use "[FromODataUri]"

Example you can find [here](http://odata.github.io/WebApi/#04-06-function-parameter-support)

**Comment by a764578566** [comment]
Sorry ，I use Asp.net Core , Asp.net core hasn't FromODataUriAttribute .
I hope OData/WebApi suppets Asp.net core 2.0

**Comment by xuzhg** [comment]
@a764578566 So far, we are still working on the ASP.NET Core support. 

You can refer to for example: https://github.com/OData/WebApi/issues/975 for the detail information about the ASP.NET Core support.
