### ISSUE TITLE
Converting TimeSpan into TimeOfDay throws exception

### ISSUE THREAD

**Issue by RiseeeAgainst** [OData/WebApi#1049]
class ODataPrimitiveSerializer

internal static object ConvertPrimitiveValue(object value, IEdmPrimitiveTypeReference primitiveType)
        {
            if (value == null)
            {
                return null;
            }

            Type type = value.GetType();
            if (primitiveType != null && primitiveType.IsDate() && TypeHelper.IsDateTime(type))
            {
                Date dt = (DateTime)value;
                return dt;
            }

            if (primitiveType != null && primitiveType.IsTimeOfDay() && TypeHelper.IsTimeSpan(type))
            {
                TimeOfDay tod = (TimeSpan)value;  //<----this line
                return tod;
            }

            return ConvertUnsupportedPrimitives(value);
        }

Value that comes equal new TimeSpan(1, 00, 00, 00)
Is it an issue or there is another way to avoid this, except writing own serializer?

**Comment by xuzhg** [comment]
@RiseeeAgainst 

Do you get the exception from https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Edm/Schema/TimeOfDay.cs#L242-L254

**Comment by RiseeeAgainst** [comment]
@xuzhg 

Exception trown in line, that I marked. 
"Exception thrown: 'System.FormatException' in Microsoft.OData.Edm.dll"
Can't convert TimeSpan with value 1.00.00.00 into TimeOfDay

**Comment by xuzhg** [comment]
@RiseeeAgainst Yes. 

`TimeOfDay tod = (TimeSpan)value;  //<----this line`

will call "https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Edm/Schema/TimeOfDay.cs#L242-L254" function. 

For example: I have the follow xunit test:

![image](https://user-images.githubusercontent.com/9426627/29934842-81b52e2e-8e31-11e7-8c2f-283afddd2bcc.png)

Run it, I will get the error message:
```json
System.FormatException : The TimeSpan value '1.00:00:00' is out of representable TimeOfDay range.
```
Debug it, you can find the following:

![image](https://user-images.githubusercontent.com/9426627/29935025-3a260a3c-8e32-11e7-9481-66580337097c.png)

I don't know where to get the following `MaxTickValue `

![image](https://user-images.githubusercontent.com/9426627/29935333-3c6dab32-8e33-11e7-99f3-c21d1eb917a8.png)

Maybe it should be set to:

`MaxTickValue = 9223372036854775807 (== TimeSpan.MaxValue.Ticks)`

Any thoughts?

**Comment by fenixil** [comment]
I believe `TimeOfDay` represents 'intraday' time only. 
So, if anyone asks you: "What time is it now?", your answer should be of `TimeOfDay` type and you cannot answer:
> \- It's 1 day o'clock.

Range for TimeOfDay is set to [00:00:00,24:00:00) and you could get it by following code:
```
TimeSpan.FromDays(1).Ticks - 1
```

**Comment by xuzhg** [comment]
@fenixil 

It looks `TimeSpan.FromDays(1).Ticks == 864000000000".`

That's the below value from `TimeSpan.FromDays(1).Ticks - 1`:
```C#
public const long MaxTickValue = 863999999999;
```

@RiseeeAgainst What's your thought?

**Comment by RiseeeAgainst** [comment]
@xuzhg 
I think, that @fenixil is right and that's my fault, that I try to put wrong value into TimeOfDay.

**Comment by xuzhg** [comment]
Thanks @RiseeeAgainst your input. Please let us know if you have further problems. We'd love to help.

@fenixil Thanks your comments. It does help us a lot.
