### ISSUE TITLE
Support Key As Segment

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#105]
Now we have to override whole DefaultODataPatchHandler and copy internal class
ODataPathSegmentTranslator to support key as segment.  
Add extensive way in DefaultODataPathHandler and MapODataServiceRoute to
enable key as segment.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1955](http://aspnetwebstack.codeplex.com/workitem/1955)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	May 20, 2014 at 2:56 AM
**Reported by:**	fenzhao
**Updated on:**	Dec 10, 2014 at 12:31 AM
**Updated by:**	yishaigalatzer

**Comment by LianwMS** [comment]
On *2014-06-18 16:20:12 UTC*, **azhou** commented:

It will be done together with URL parser extension in vNext.

**Comment by congysu** [comment]
Related issue: https://github.com/OData/WebApi/issues/366

**Comment by VikingsFan** [comment]
Merged 8e3845b2ca9438dbc65279547afdfdf1d07e92fe
