### ISSUE TITLE
AutoExpand not working after upgrade to System.Web.OData 5.9.1

### ISSUE THREAD

**Issue by FerRrari** [OData/WebApi#1057]
I’m trying to update from version 5.8 to 5.9.1. We have an entity with a navigation property (an array of values) which is decorated with the AutoExpand property. After updating the System.Web.OData version to 5.9.1 the property stopped auto-expanding. I can see in the source code that GetExtraQueryParameters was removed and this function was the one adding the AutoExpand properties to the expand clause

**Comment by santhudr** [comment]
I have the same issue.

**Comment by gathogojr** [comment]
Fixed in current version
