### ISSUE TITLE
v5.6: Enum on un-type support

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#106]
Currently, enum on un-type doesn't work. While, the collection of enum on un-
type doesn't work too.  
  
As ODL spec says:  
  
Structural property can be :  
1) primitive type  
2) complex type  
3) enum type  
4) the collection of the above.  
  
So. Please add the support enum on un-type.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1956](http://aspnetwebstack.codeplex.com/workitem/1956)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	May 20, 2014 at 9:36 AM
**Reported by:**	xuzhg
**Updated on:**	Tue at 7:29 AM
**Updated by:**	cysu

**Comment by LianwMS** [comment]
On *2014-11-20 11:28:47 UTC*, **xuzhg** commented:

Similar to: 
https://aspnetwebstack.codeplex.com/workitem/2186

**Comment by LianwMS** [comment]
On *2015-01-06 15:29:29 UTC*, **cysu** commented:

Consolidate with other untyped asks.

**Comment by VikingsFan** [comment]
Checked in 07ae38d4cc1184285a826c72735d2df2c47c6354
