### ISSUE TITLE
Method not implemented when filtering by child count

### ISSUE THREAD

**Issue by mark--stephenson** [OData/WebApi#1062]
I'm lead to believe the following query is valid as per the spec for oData v4` http://localhost:4839/odata/v1/people?$filter=addresses/$count gt 0`, however an exception 'The method or operation is not implemented' is thrown. 

Can anyone advise? Should this query work? Or am I misinformed?

I'm using Microsoft.AspNet.OData v6.0.0

**Comment by xuzhg** [comment]
@mark--stephenson 

We merged a PR related to the issue.

Please refer to https://github.com/OData/WebApi/issues/194 for more information.

I think it will be shipped in next release. You can try our nightly build.
