### ISSUE TITLE
Move direct annotations in webapi.odata to use v4 vocabulary

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#107]
Shall move to use v4 vocabulary / capability etc. for the work done last year
(etag, query limitations, etc.)  
  
Query limitations:  

    
    
          - Filterability ($filter)
          - Sortability ($orderby)
          - Queryability of top level entity sets
          - Query functions
    

Etag:  

    
    
      <Term Name="OptimisticConcurrency" Type="Collection(Edm.PropertyPath)" AppliesTo="EntitySet">
        <Annotation Term="Core.Description"
          String="Data modification requires the use of Etags. A non-empty collection contains the set of properties that are used to compute the ETag" />
      </Term>
    

Probably shall also evaluate other existing usages of direct annotation in
webapi.odata, see if they can be moved to use Capabilities / Core Vocabulary.  
  
Link:  
[ 1451 : metadata is not exposed correctly for properties with query
limitations ](https://aspnetwebstack.codeplex.com/workitem/1451)  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1961](http://aspnetwebstack.codeplex.com/workitem/1961)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	May 21, 2014 at 5:48 AM
**Reported by:**	cysu
**Updated on:**	May 21, 2014 at 5:58 AM
**Updated by:**	azhou

**Comment by xuzhg** [comment]
Checked in for capabilities vocabulary.

**Comment by congysu** [comment]
@xuzhg Is ETag done?  Related issue: https://github.com/OData/WebApi/issues/459

**Comment by xuzhg** [comment]
@congysu See a9f309886fece9dd7fe7229e7b7bf87f355a8c2c for ETag. Thanks.
