### ISSUE TITLE
Document how to configure for .NET Core Web application?

### ISSUE THREAD

**Issue by sarchibald-mdsol** [OData/WebApi#1072]
Hi,
I'm trying to use OData for a .NET Core (2.0) Web application. .NET Core apps are configured in a different way from  ASP.NET Framework web applications are configured.
Typically, in .NET Core, you configure your routes with "app.UseMvc(route => ....). I'm doing something similar
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
	loggerFactory.AddConsole(Configuration.GetSection("Logging"));
	loggerFactory.AddDebug();
	app.UseDefaultFiles();
	app.UseStaticFiles();
	var modelBuilder = new ODataConventionModelBuilder();
	app.UseMvc(route =>
		{
			route.MapRoute("odata", "odata/{controller}/{id}");
			BuildODataModels(modelBuilder);
		});
}
 
private void BuildODataModels(ODataConventionModelBuilder modelBuilder)
{
	modelBuilder.EntitySet<RaveCdcEstimations>("RaveCDCEstimations");
}
```
I've tried using app.UseMvc(route => route.MapODataServiceRoute(....), but that method is not found.

How do I configure OData v4 to work correctly in .NET Core (2.0)?

Note, I can successfully retrieve an entire collection from EntityFramework using the above code. However, adding a $filter or a $top causes me to get a 500 error.

**Comment by robward-ms** [comment]
OData WebApi is not supported on .Net Core. See here for more info: #975

**Comment by sarchibald-mdsol** [comment]
Sigh ...

Thanks for the info.
