### ISSUE TITLE
EnableEnumPrefixFree - where is it?

### ISSUE THREAD

**Issue by ianlar** [OData/WebApi#1080]
Prior to 6.0.0, we used config.EnableEnumPrefixFree to allow prefix-free enums as function parameters. This configuration settings seems to be missing in 6.0.0 and above.

Is there another way to accomplish this, or should we downgrade to 5.x?

### Assemblies affected

>= 6.0.0

**Comment by xuzhg** [comment]
@ianlar 

Please check https://github.com/OData/WebApi/blob/master/test/UnitTest/System.Web.OData.Test/OData/ODataUriResolverExtensionTest.cs#L235-L266
for the usage of the EnumPrefixFree.

Thanks!

**Comment by ianlar** [comment]
Thank you! For anyone trying to do this in the future, I got this working with the OData versioning library as follows:

      config.MapVersionedODataRoutes(
                "odata",
                "odata",
                ODataModels,
                builder =>
                {
                    builder.AddService<ODataUriResolver>(ServiceLifetime.Singleton, sp => new StringAsEnumResolver());
                });
