### ISSUE TITLE
 Dynamic property  and Quarry and update in database side 

### ISSUE THREAD

**Issue by a-elnajjar** [OData/WebApi#1086]
OData team,
just I want to ask if you can support the Dynamic property  Filed can be mapped to JSON filed because database like SQL Server 2016 and PostgreSQL are adding a feature to Quarry and update data in JSON Field.

**Comment by biaol-odata** [comment]
@a-elnajjar: I believe here is ODL's support for dynamic property: https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/use-open-types-in-odata-v4

Let's know if that helps.

**Comment by biaol-odata** [comment]
@a-elnajjar Any other questions, please re-open or submit new issues. I am closing this issue since the last update was in last October.
