### ISSUE TITLE
Hypermedia links for navigation properties wrong

### ISSUE THREAD

**Issue by bdebaere** [OData/WebApi#1088]
Using OData 4 controllers I am able to get the hyper media information via adding the following to my resource: "$format=application/json;odata.metadata=full". The links added to the navigation properties however are wrong. They are still in the old format with slashes, which means when I click on them I get: "No HTTP resource was found that matches the request URI http://localhost:port/odata/Class(6)/Class2".

Unless of course I'm doing something wrong, which is entirely possible as this is my first time working with OData.
### Assemblies affected

Latest NuGet package: OData WebApi lib 6.1.0.

### Reproduce steps
Use "$format=application/json;odata.metadata=full" on a resource and notice you cannot click any links for the navigation properties.

### Expected result
Hypermedia links should be clickable for the navigation properties.

### Actual result
Hypermedia links for the navigation properties take you to the wrong page.

**Comment by bdebaere** [comment]
@biaol-odata Expanding uses $expand=Class2 since OData 4 as I've understood it. The hypermedia links do not reflect this yet and instead use the older notation with slashes.

**Comment by biaol-odata** [comment]
@bdebaere Is this related? https://github.com/OData/WebApi/issues/157

**Comment by xuzhg** [comment]
@bdebaere In Web API OData convention, 

`http://localhost:port/odata/Class(6)?$expand=Class2 ` will route to "Get(...)" method in the controller.

Meanwhile, `http://localhost:port/odata/Class(6)/Class2` will route to "GetClass2(...)" method in the controller.

The error message "No HTTP resource was found that matches the request URI http://localhost:port/odata/Class(6)/Class2" seems to me that you didn't implement the right method in your controller. Would you please take a look or share us your more detail information?

Thanks!

**Comment by xuzhg** [comment]
I closed it. Thanks your feedback. Please re-open it or file new issue if you have further concerns.

**Comment by bdebaere** [comment]
@xuzhg I think we misunderstand each other. The question I'm asking is why is http://localhost:port/odata/Class(6)/Class2 even included in the response when there is no HTTP resource matching that request in my controller. This is not about not implementing the right method, this is about OData giving links which don't exist. What if I choose not to implement this method.

**Comment by bdebaere** [comment]
@xuzhg By the way, there is no reopen button when a collaborator closes the issue.

**Comment by xuzhg** [comment]
@bdebaere 

OData is based on a powerful set of concepts and **conventions** which allow rich interaction with OData services. Such interactions are handled by the functionalities implemented in the really OData service.

So, the link in the error message is generated based the OData **conventions**. You can use this link to interaction with service if the service implements the corresponding functionality.

I don't agree that OData gives links which doesn't exist. Based on the "http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part2-url-conventions.html", ODL can construct many links. However, whether you can use link to interaction with the OData services or not depends on the really OData service implementation.

**Comment by biaol-odata** [comment]
Re-opening per the submitter's request.

**Comment by bdebaere** [comment]
@xuzhg Then we will agree to disagree here.
