### ISSUE TITLE
Support OData Uri Parse extension of ODL 6.7 release

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#11]
#  1\. Problem:

ODL 6.7 supports  
  
overriding default Uri parsing behavior, including:  

    
    
    -  Resolving property name 
    -  Resolving type name 
    -  Resolving navigation source name 
    -  Resolving operation import name 
    -  Resolving bound operation name 
    -  Resolving function parameters 
    -  Resolving entity set key 
    -  Resolving binary operator node elements 
    

for detail: [ http://blogs.msdn.com/b/odatateam/archive/2014/09/05
/announcement-odatalib-6-7-0-release.aspx
](http://blogs.msdn.com/b/odatateam/archive/2014/09/05/announcement-odatalib-6-7-0-release.aspx)  

#  2\. Secanio - case insensitive

For OData $filter/$sort queries, our output could potentially different
casings vs. the model. In this scenario the query parsing will fail.  
  
For example, if my model has a "Name" property but my JSON outputs the
property as "name" I cannot use $filter=startswith(name,'Joe') which consumers
would expect.  
  
Discussion reference: [ http://aspnetwebstack.codeplex.com/discussions/391903
](http://aspnetwebstack.codeplex.com/discussions/391903)  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 366](http://aspnetwebstack.codeplex.com/workitem/366)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Aug 24, 2012 at 5:41 PM
**Reported by:**	jberd126
**Updated on:**	Dec 24, 2014 at 6:10 AM
**Updated by:**	xuzhg

**Comment by LianwMS** [comment]
On *2012-08-26 01:07:40 UTC*, **JackW** commented:

This problem applies to more than mere casing differences. Would it be possible use attributes on the model, so when requesting XML or JSON the names declared using [XmlElement] or [JsonProperty] attributes are used in place of the underlying property
 names?

Obviously more heavily customised serialisation scenarios may require a more sophisticated extension point for mapping OData queries to the underlying properties, but it seems the change suggested above would cover most cases.

**Comment by LianwMS** [comment]
On *2012-08-28 05:36:12 UTC*, **aggieben** commented:

I seem to be observing a familiar problem with the $orderby query; I have a [Queryable] action in which '$orderby [PropertyName] DESC' causes a "syntax error" positioned right after the 'C' character and winds up responding with a 400 Bad Response.
 However, if the query is written '$orderby [PropertyName] desc', the action responds as expected.

**Comment by LianwMS** [comment]
On *2012-09-14 21:16:05 UTC*, **Grokys** commented:

This would be very useful for me too - I use javascript casing on the client side and C# casing on the server side, as I'm sure many people do.

**Comment by LianwMS** [comment]
On *2012-09-15 10:52:08 UTC*, **jberd126** commented:

@JackW,
Ideally I would like to have a query property name provider (or something) that would be more flexible and support scenarios that are content negotiated. I felt that the case insensitive support would be simpler to implement and go a long way to supporting
 many scenarios. However it's going to go so far.

Is there any plans for something like JackW mentions?

**Comment by LianwMS** [comment]
On *2012-10-05 07:45:06 UTC*, **HongmeiG** commented:

We are locking down the preview release. This requires some changes in the OData Uri Parser.

**Comment by LianwMS** [comment]
On *2013-03-30 06:17:57 UTC*, **HongmeiG** commented:

This requires changes not in this product. Will contact the owner for making this change.

**Comment by LianwMS** [comment]
On *2013-09-13 21:39:36 UTC*, **Hellmax** commented:

Are there any updates on this?

**Comment by LianwMS** [comment]
On *2013-10-24 07:52:39 UTC*, **danroth27** commented:

Requires ODataLib support. We will handle this in our next release.

**Comment by LianwMS** [comment]
On *2014-07-10 07:02:34 UTC*, **kirkpabk** commented:

Understanding that the ODATA protocol specifies case-sensitivity... it doesn't mean that this protocol design choice is the "right" one... Why should we--a consumer of a product--be forced to perform yet another time consuming (and expensive)
 mapping exercise that could be difficult to troubleshoot in a crunch... So--it's not the aspnetwebstack that really needs to be changed (they're adhering to a standard--although I'd love to see an "override" switch at webapi.config or something)--this
 should be ALSO addressed with the ODATA board. In lieu of this "defense"--I didn't see anything new in the ODataLib, pretty please--someone make it happen... ;-) We have many data models with an INSANE amount of non-sense casing (mostly from legacy
 mainframe) that makes documenting (let alone using) ODATA very tough for our consumers. Not to repeat, but the JavaScript standards casing issue is yet another reason why we need consumer-driven flexibility here. An organization should be free to CHOOSE is
 they want case sensitivity, but not FORCED... Just a thought...

**Comment by LianwMS** [comment]
On *2014-09-09 21:32:10 UTC*, **eivindbjarte** commented:

Agree complety with kirkpabk, this is yet another example of making something complicated out of something that should be simple .

**Comment by xuzhg** [comment]
Resolved:
7b3367371b1632cf33161cc090e67994c0b6067a
