### ISSUE TITLE
ODataUriParser cannot parse Enum function parameter when its EdmType is nullable

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#110]
ODataUriParser cannot parse Enum function parameter when its EdmType is
nullable.  
such as ~/FunctionAtRoot(Parameter=NS.SimpleEnum'0')  
The Parameter is defined as Nullable=true  
The ODataUriParser will throw NullReferenceException "Object reference not set
to an instance of an object."  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1975](http://aspnetwebstack.codeplex.com/workitem/1975)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	May 27, 2014 at 4:40 PM
**Reported by:**	fenzhao
**Updated on:**	May 28, 2014 at 10:10 PM
**Updated by:**	danroth27

**Comment by xuzhg** [comment]
@VikingsFan  please check this. As I know, it works now.

**Comment by VikingsFan** [comment]
Fixed in v5.5

**Comment by congysu** [comment]
2dfbbfa66b62e9350097d269ec06f55df2414c00
