### ISSUE TITLE
The "LiteralText" property of ConstantNode in parsed result of ODataUriParser should never be null

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#111]
The "LiteralText" property of ConstantNode in parsed result of ODataUriParser
should never be null  
  
For example: parsing "~/FunctionAtRoot(NullableInt32Parameter=1)"  
The parsed parameter value in ODL path segment is a ConstantNode.  
The "Value" property of this ConstantNode is 1.  
But the "LiteralText" property of this ConstantNode is null which is expected
to be "1"  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1978](http://aspnetwebstack.codeplex.com/workitem/1978)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	May 28, 2014 at 2:35 AM
**Reported by:**	fenzhao
**Updated on:**	May 28, 2014 at 10:10 PM
**Updated by:**	danroth27

**Comment by xuzhg** [comment]
ODL already fix it. Close it.
