### ISSUE TITLE
"&" is not the correct logic symbol used in conditional statement

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#112]
in ** AddProcedures ** function of ** EdmModelHelperMethods.cs **  
  
there is a conditional statement as follows:  

    
    
    if (procedure.IsBindable && procedure.Title != null & procedure.Title != procedure.Name)

Where, "&" is not correct. It should be "&&".  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1979](http://aspnetwebstack.codeplex.com/workitem/1979)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	May 28, 2014 at 3:27 AM
**Reported by:**	xuzhg
**Updated on:**	May 28, 2014 at 10:10 PM
**Updated by:**	danroth27

**Comment by LianwMS** [comment]
On *2014-05-28 13:18:44 UTC*, **dougbu** commented:

very minor bug which has zero impact. the '&' is just not going to short-circuit (avoid) the last check when
IsBindable is false or Title is null.

**Comment by VikingsFan** [comment]
Fixed with 1225ef1
