### ISSUE TITLE
UnqualifiedNameCall setting seems to be missing

### ISSUE THREAD

**Issue by bdebaere** [OData/WebApi#1125]
With the latest OData v7.3.1.10814 I cannot find the setting for UnqualifiedNameCall. I have searched the entire repository at https://github.com/OData/WebApi and it seems to have vanished.

The UnqualifiedNameCall is still in the documentation: http://odata.github.io/WebApi/#06-01-custom-url-parsing

Can you tell me how I can enable this setting?

Currently I'm using the UnqualifiedODataUriResolver implementation found in the samples for OData with versioning. But this does not contain a setting for UnqualifiedNameCall.

```
    public class CaseInsensitiveODataUriResolver : UnqualifiedODataUriResolver
    {
        public override bool EnableCaseInsensitive {
            get { return true; }
            set { }
        }
    }
```

**Comment by xuzhg** [comment]
See the test codes about how to config/enable it.

https://github.com/OData/WebApi/blob/88c5f01f2ee2d685d873b2ab075909b7da6651f1/test/UnitTest/System.Web.OData.Test/OData/ODataUriResolverExtensionTest.cs#L106-L113

https://github.com/OData/WebApi/blob/88c5f01f2ee2d685d873b2ab075909b7da6651f1/test/UnitTest/System.Web.OData.Test/OData/ODataUriResolverExtensionTest.cs#L123-L128

**Comment by bdebaere** [comment]
@xuzhg Thank you, I see now the UnqualifiedNameCall is changed to the UnqualifiedODataUriResolver.
