### ISSUE TITLE
Consuming Put/Patch method with Delta<T> parameter from a c# console App

### ISSUE THREAD

**Issue by gpm12gpm** [OData/WebApi#1126]
Consuming a Odata Put mehod from c# console App,
Receiving null value in the input parameter Delta<T>. But working fine when consuming the service from Advance Rest Client. Below is my console app code

`using (HttpClient client = new HttpClient())
            {
                Brand brand = new Brand();
                brand.BrandKeyID = brandkeyid;
                brand.MasterBrandKeyID = masterbrandkeyid;
                brand.ApprovalStatusKeyID = status;
                brand.ModifiedBy = "DQ tbc";
                string brandJson = Newtonsoft.Json.JsonConvert.SerializeObject(brand);

                //var method = new HttpMethod("PATCH");

                //var request = new HttpRequestMessage(method, new Uri(url))
                //{
                //   Content= new StringContent(brandJson, Encoding.UTF8, "")
                //};

                HttpResponseMessage response = new HttpResponseMessage();
                // In case you want to set a timeout
                //CancellationToken cancellationToken = new CancellationTokenSource(60).Token;

                try
                {
                    var request = new StringContent(brandJson, Encoding.UTF8, "application/json");
                    request.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                    
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", bearerToken);
                    client.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", ocp);
                    client.DefaultRequestHeaders.Add("RelatesTo", "Platform.FacialCoding.Product1");
                    response = client.PutAsync(new Uri(url), request).Result;
                 
                }
                catch (TaskCanceledException e)
                {
                    return BadRequest(e.ToString());
                }
            }`

**Comment by gpm12gpm** [comment]
Fixed this issue

**Comment by evanypark** [comment]
@gpm12gpm How did you fix this issue? I'm experiencing the same
