### ISSUE TITLE
Build action/function and actionimport/functionimport are not correct.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#113]
In ** EdmModelHelperMethods ** .cs, there are some errors while building the
action/function and actionimport/functionimport.  

  1. For bound action/function, no need to create the actionimport/functionimport.   

  2. For actionimport/functionimport, only the entity set name is valid. The EntitysetPath is not used for actionimport/functionimport.   

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1980](http://aspnetwebstack.codeplex.com/workitem/1980)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	May 28, 2014 at 3:58 AM
**Reported by:**	xuzhg
**Updated on:**	May 29, 2014 at 5:58 AM
**Updated by:**	xuzhg

**Comment by LianwMS** [comment]
On *2014-05-28 13:19:35 UTC*, **dougbu** commented:

What user-visible symptoms result from the "errors" described in this bug? What improves for users if this bug is fixed?

**Comment by LianwMS** [comment]
On *2014-05-29 12:58:42 UTC*, **xuzhg** commented:

Yes. It is mostly related to performance:

for bound action/function, we should not new actionimport/functionimport". But, the code in EdmModelHelperMethods always create both.
EntitySetPath is used in bound action/function.
For unbound action/function, we should build (new) actionimport/functionimport.

**Comment by xuzhg** [comment]
The codes are ok now.
