### ISSUE TITLE
Odata filter is not working when altering the filter

### ISSUE THREAD

**Issue by manojmore** [OData/WebApi#1133]
Requirement -> change the request url to alter the filter value. 

Example - 
If Input URL is-
https://localhost/DemoService/api/v2.0/Employees?$filter=Addresses/any(a: **a/City eq 'New York'**)

Altered URL should be-
https://localhost/DemoService/api/v2.0/Employees?$filter=Addresses/any(a: **a/Pincode eq 10038**)

here filter is changed from a/City to a/Pincode

I have followed one solution from stackoverflow site (see below url) by creating custom attribute.
[https://stackoverflow.com/questions/33660648/odata-v4-modify-filter-on-server-side](url)

```
public class CustomEnableQueryAttribute : EnableQueryAttribute
{
    public override void OnActionExecuting(HttpActionContext actionContext)
    {
        var url = actionContext.Request.RequestUri.OriginalString;

        //change something in original url, 
        //for example change all A charaters to B charaters,
        //consider decoding url using WebUtility.UrlDecode() if necessary
        var newUrl = ModifyUrl(url); 

        actionContext.Request.RequestUri = new Uri(newUrl);
        base.OnActionExecuting(actionContext);
    }
}
```

I have modified the url inside OnActionExecuting. When I debug inside controller, queryOptions.Filter.RawValue shows old filter value. ie. **Addresses/any(a: a/City eq 'New York')**

But the queryOptions.Request.RequestUri shows the newly modified url. ie. https://localhost/DemoService/api/v2.0/Employees?$filter=Addresses/any(a: **a/Pincode eq 10038**)

Is there any solution to this issue. Or is there any alternative to achieve the requirement.

In my project I have used following libraries;

Microsoft.Data.OData.dll  v4.0.30319
Microsoft.OData.Core.dll  v4.0.30319
Microsoft.OData.Edm.dll  v4.0.30319

**Comment by madansr7** [comment]
@manojmore , Do you still need assistance with this issue? Can we close it?
