### ISSUE TITLE
EnableLowerCamelCase broken when grouping and sorting on a sub-property

### ISSUE THREAD

**Issue by PietheinHeemskerk** [OData/WebApi#1136]
We use ODataConventionModelBuilderExtensions.EnableLowerCamelCase() so that our C# model, which has Pascal-casing, presents itsself in JSON with camel-casing.
We we're trying to upgrade from Microsoft.AspNet.OData version 6.0.0 to the latest release. But the following query does not parse anymore:

http://localhost:8080/PrognoseAPI/odata/Forecast(545)?$apply=groupby((dimDateMonth/yearNumber))&$orderby=dimDateMonth/yearNumber%20desc

It throws the ODataException "The query specified in the URI is not valid. Property or path DimDateMonth isn't available in the current context. It was removed in earlier transformation."
If we do not do the EnableLowerCamelCase() then query the following works as expected.

http://localhost:8080/PrognoseAPI/odata/Forecast(545)?$apply=groupby((DimDateMonth/YearNumber))&$orderby=DimDateMonth/YearNumber%20desc

### Assemblies affected

Microsoft.AspNet.OData version 6.1.0

### Reproduce steps

With ODataConventionModelBuilderExtensions.EnableLowerCamelCase() enabled perform a query with grouping on a field of a field and subsequently orderby on that same field.

### Expected result

The query returns the expected results.

### Actual result

ODataException "The query specified in the URI is not valid. Property or path DimDateMonth isn't available in the current context. It was removed in earlier transformation."

### Additional detail

I did some investigation and source level debugging in the 6.1.0 version. According to me the issue is introduced by https://github.com/OData/WebApi/pull/875/files
I added a comment to the pullrequest that fixes the issue for me. It basically makes the dictionary lookup case insensitive.

**Comment by jcannata** [comment]
I have just upgrade to 6.1.0 and ran into this too, @PietheinHeemskerk 
All of my aggregate calls have now broken. Ugh.
Was there any further action planned on this @robward-ms ?

**Comment by robward-ms** [comment]
@xuzhg - Thoughts?

**Comment by xuzhg** [comment]
@PietheinHeemskerk @jcannata Do you try the latest 7.0 version?

I can't repro your problem in the 7.0 version. I had a test like:

1. Create EdmModel by enable lower camel case.
2. Build and run the service.
3. File a request at: 
![image](https://user-images.githubusercontent.com/9426627/40325550-0e619aea-5cf1-11e8-841a-58eb16c27b58.png)
4. Debug it, it can show as below
![image](https://user-images.githubusercontent.com/9426627/40325521-ebffaabe-5cf0-11e8-8a28-f0fd55dc409d.png)

5. Continue to run, it can give me the result.

![image](https://user-images.githubusercontent.com/9426627/40325594-3c3260ee-5cf1-11e8-88f4-e392c1b758f3.png)
