### ISSUE TITLE
@odata.type dont work on post .net core 2

### ISSUE THREAD

**Issue by lboss75** [OData/WebApi#1140]
Post method don't deserialize derived object.

### Assemblies affected

maintenance-aspnetcore branch

### Reproduce steps

If I have the following classes:
`abstract class A {};`
`class B : A {};`
`class C : A {}`

and model:
`            builder.EntityType<A>();`
`            builder.EntityType<B>();`
`            builder.EntityType<C>();`

`            builder.EntitySet<A>("As");`

and controller:
`        [HttpPost]`
`        public IActionResult Post([FromBody]A value) { ...`

So when I post the json:
`{ "@odata.type" : "#B", ...`

### Expected result

OData have to process tag @odata.type and create derived value;

### Actual result

I got the exception because Newtonsoft.Json can't create abstract class A.

### Additional detail

.net core 2

**Comment by xuzhg** [comment]
@lboss75 

Asp.net Core for OData is in development under branch https://github.com/OData/webapi/tree/feature/netcore.  Please check the development history through https://github.com/OData/WebApi/issues/939. 

And the alpha version is available at : https://www.myget.org/F/webapinetcore/ . You are to welcome download and give a try. Any feedback is welcome.

maintenance-aspnetcore is in its maintenance status. There's no plan to accept PR or bug fix for this branch. Sorry for that.
