### ISSUE TITLE
Microsoft.Owin.Testing not registering OData v4 routes

### ISSUE THREAD

**Issue by javiercn** [OData/WebApi#1146]
Hey OData team, this sounds like a question better suited for you guys, so I'm leaving it here. See https://github.com/aspnet/AspNetKatana/issues/146#issuecomment-349012793 for the original.

From @furier

> Hi
> 
> I am trying to spin up an in-memory owin test server to integration test my OData API, however all attempts at calling any routes routes return **404 not found**. Everything works fine for WebApi but OData nothing...
> 
> Here are the "important" parts of my code, have tried to strip out less important parts, however if I missed something or stripped out to much just call out.
> 
> _I also want to point out that it works wonders using IIS or IIS Express, Im able to use the OData endpoints as intended, however not with the OwinTestServer._
> 
> ### ASP.NET.WebApi Project
> 
> Here is the `OwinConfig` class in the ASP.NET.WebApi Project.
> ```cs
> public class OwinConfig
> {
>     public void Configuration(IAppBuilder app)
>     {
>         var config = new HttpConfiguration
>         {
>             IncludeErrorDetailPolicy = IncludeErrorDetailPolicy.Always
>         };
>         WebApiConfig.Register(config);
>         config.DependencyResolver = DependencyResolver;
>         app.UseWebApi(config);
>     }
> 
>     protected virtual IDependencyResolver DependencyResolver => new UnityHierarchicalDependencyResolver(UnityConfig.GetConfiguredContainer());
> }
> ```
> 
> Here is the traditional `WebApiConfig`
> ```cs
> public static class WebApiConfig
> {
>     public static void Register(HttpConfiguration config)
>     {
>         config.MapHttpAttributeRoutes();
>         config.Routes.MapHttpRoute(
>             "DefaultApi",
>             "api/{controller}/{id}",
>             new { id = RouteParameter.Optional });
> 
>         var builder = new ODataConventionModelBuilder();
>         builder.EntitySet<Application>("Applications");
>         config.Count().Filter().OrderBy().Expand().Select().MaxTop(1000);
>         config.MapODataServiceRoute("odata", "odata", builder.GetEdmModel());
>     }
> }
> ```
> 
> ### ASP.NET.WebApi.Tests.Integration Project
> 
> Here is my `TestOwinConfig` to override the way i get the dependency resolver.
> ```cs
> public class TestOwinConfig : OwinConfig
> {
>     private readonly Func<IUnityContainer> container;
> 
>     public TestOwinConfig(Func<IUnityContainer> container)
>     {
>         this.container = container;
>     }
> 
>     protected override IDependencyResolver DependencyResolver => new UnityHierarchicalDependencyResolver(container());
> }
> ```
> 
> I have an integration test base class to tuck away the repetitive setup / teardown stuff off the Owin Test Server.
> ```cs
> public abstract class IntegrationTestBase : UnitTestBase
> {
>     protected TestServer Server;
> 
>     private IUnityContainer ChildContainer { get; } = UnityConfig.GetConfiguredContainer().CreateChildContainer();
> 
>     [OneTimeSetUp]
>     public override void OneTimeSetUp()
>     {
>         Server = TestServer.Create(builder => new TestOwinConfig(() => ChildContainer).Configuration(builder));
>         Server.HttpClient.Timeout = TimeSpan.FromDays(1);
>         Container = new UnitTestUnityContainer(ChildContainer);
>     }
> 
>     [OneTimeTearDown]
>     public override void OneTimeTearDown()
>     {
>         base.OneTimeTearDown();
>         Server.Dispose();
>     }
> }
> ```
> 
> I have stripped this class a bit, but here is the base stuff meant to be used for all OData controller tests.
> ```cs
> public abstract class ODataControllerTestBase<TEntity, TClientEntity, TClientCreatedODataResult, TClientUpdatedODataResult> : IntegrationTestBase where TEntity : EntityBase
> {
>     private readonly string baseUrl;
> 
>     public ODataControllerTestBase(string baseUrl)
>     {
>         this.baseUrl = baseUrl;
>     }
> 
>     protected TEntity Entity;
> 
>     [OneTimeSetUp]
>     public new async Task OneTimeSetUp()
>     {
>         base.OneTimeSetUp();
> 
>         Entity = BuildEntity();
>         await CreateEntity(Entity);
>     }
> 
>     protected abstract TEntity BuildEntity();
> 
>     protected async Task<TClientCreatedODataResult> CreateEntity(TEntity entity)
>     {
>         var response = await Server.HttpClient.PostAsJsonAsync(baseUrl, entity);
>         await PrintErrors(response);
>         response.EnsureSuccessStatusCode();
>         return await response.Content.ReadAsAsync<TClientCreatedODataResult>();
>     }
> 
>     ...
> }
> ```
> 
> This is the test class for the ApplicationController, this may be confusing to read as the base class is calling the `CreateEntity` method which should call the correct action in the ODataController. All the test does is assert that behind the scenes something else I expect to happen ocurred, but thats beside the issue here as I dont get past calling the `CreateEntity` method. 
> `await Server.HttpClient.PostAsJsonAsync(baseUrl, entity);` just return 404 Not Found.
> ```cs
> public class ApplicationControllerTests : ODataControllerTestBase<Application, Client.Models.Application, CreatedODataResultApplication, UpdatedODataResultApplication>
> {
>     public override void SetUp()
>     {
>         base.SetUp();
> 
>         crmClient = Container.Resolve<ICrmClient>();
>     }
> 
>     private ICrmClient crmClient;
> 
>     public ApplicationControllerTests() : base("odata/applications") { }
> 
>     protected override Application BuildEntity()
>     {
>         return new Fixture()
>             .Build<Application>()
>             .Without(x => x.ApplicationContent)
>             .Create();
>     }
> 
>     [Test]
>     public async Task CreateApplicationTest()
>     {
>         var entity = await crmClient.Applications.GetApplicationV5Async(Entity.Id);
>         entity.Should().NotBeNull();
>         entity.ProjectName.Should().Be(Entity.ProjectName);
>     }
> }
> ```
> 
> Here is a sample of the ApplicationsController, all methods except POST has been stripped, the class is scaffolded with the Visual Studio ODataController Wizard, all Iv done is change the way the context is initialized, by dependency injection.
> ```cs
> public class ApplicationsController : ODataController
> {
>     private IApplicationDataBaseContext db;
> 
>     public ApplicationsController(IApplicationDataBaseContext db)
>     {
>         this.db = db;
>     }
> 
>     ...
> 
>     // POST: odata/Applications
>     public async Task<IHttpActionResult> Post(Application application)
>     {
>         if (!ModelState.IsValid)
>             return BadRequest(ModelState);
> 
>         db.Applications.Add(application);
> 
>         try
>         {
>             await db.SaveChangesAsync();
>         }
>         catch (DbUpdateException)
>         {
>             if (ApplicationExists(application.Id))
>                 return Conflict();
>             throw;
>         }
> 
>         return Created(application);
>     }
> 
>     ...
> }
> 
> ```
> 
> 
> *Short summary (3-5 sentences) describing the issue.*
> 
> ### Assemblies affected
> 
> *Which assemblies and versions are known to be affected e.g. OData WebApi lib 6.1.0
> 
> ### Reproduce steps
> 
> *The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*
> 
> ### Expected result
> 
> *What would happen if there wasn't a bug.*
> 
> ### Actual result
> 
> *What is actually happening.*
> 
> ### Additional detail
> 
> *Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by xuzhg** [comment]
@furier 

Would you please give us a repo? 

Because, I wrote a sample test, it can work at my side:

```C#
public class Startup1
    {
        public void Configuration(IAppBuilder app)
        {
            // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=316888
            var config = new HttpConfiguration
            {
                IncludeErrorDetailPolicy = IncludeErrorDetailPolicy.Always
            };

            WebApiConfig.Register(config);
         //   config.DependencyResolver = DependencyResolver;
            app.UseWebApi(config);

        }

       // protected virtual IDependencyResolver DependencyResolver => new UnityHierarchicalDependencyResolver(UnityConfig.GetConfiguredContainer());
    }

public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            config.MapHttpAttributeRoutes();
            config.Routes.MapHttpRoute(
                "DefaultApi",
                "api/{controller}/{id}",
                new { id = RouteParameter.Optional });

            var builder = new ODataConventionModelBuilder();
            builder.EntitySet<Application>("Applications");
            config.Count().Filter().OrderBy().Expand().Select().MaxTop(1000);
            config.MapODataServiceRoute("odata", "odata", builder.GetEdmModel());

        }
    }

    public class Application
    {
        public int Id { get; set; }
    }

class Program
    {
        static void Main(string[] args)
        {
            using (WebApp.Start<Startup1>("http://localhost:12345"))
            {
                Console.WriteLine("Press [enter] to quit ...");
                Console.ReadLine();
            }
        }
    }
```
If I send a request as " http://localhost:12345/odata/$metadata"
I can get 
```json
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="ODataOWin" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityType Name="Application">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int32" Nullable="false" />
            </EntityType>
        </Schema>
        <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityContainer Name="Container">
                <EntitySet Name="Applications" EntityType="ODataOWin.Application" />
            </EntityContainer>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>
```

**Comment by furier** [comment]
Hi @xuzhg will try the metadata route on Monday and see what I get. Don't have a repo and cant really upload it wither as it is private code developed for a customer who owns it etc.

**Comment by furier** [comment]
@xuzhg I can confirm that I get the same as output when I send a request to the  `.../odata/$metadata` endpoint, all looks to be well and good with the EDM model. However 404 is still returned when I send a 
POST request to the `.../odata/applications` endpoint.

**Comment by furier** [comment]
Ahhhhh I remember reading somewhere that odata routes are case sensitive, and I tested with the route `.../odata/Applications` and everything worked, sigh sorry for wasting your time...

**Comment by xuzhg** [comment]
Never mind. 
Be glad to hear it worked. Please let us know any further questions or concerns. Thanks!
