### ISSUE TITLE
Remove useless parameters in BuildEditLink() & BuildReadLink()

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#115]
In NavigationSourceLinkBuilderAnnotation.cs, public function BuildEditLink()
and BuildReadLink() have useless parameters. Please verify and remove them.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2000](http://aspnetwebstack.codeplex.com/workitem/2000)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jun 4, 2014 at 12:58 PM
**Reported by:**	xuzhg
**Updated on:**	Jun 5, 2014 at 7:58 AM
**Updated by:**	azhou

**Comment by xuzhg** [comment]
@VikingsFan please clean it up.

**Comment by xuzhg** [comment]
Currently, BuildEditLink()  and BuildReadLink() are public virtual function. Customers can overload these function to use `Uri idLink` or `Uri editLink`. So, let's keep them unmodified. Thanks.
