### ISSUE TITLE
[feature/netcore] Support "/$count" and "?$count=true"

### ISSUE THREAD

**Issue by smlynch** [OData/WebApi#1153]
It appears neither counting all entities (`/SomeEntity/$count`) nor  adding counts inline (`/SomeEntity?$count=true`) are supported with the alpha release of Microsoft.AspNetCore.OData

### Assemblies affected

Microsoft.AspNetCore.OData.dll, 7.0.0-Nightly201712061320

### Reproduce steps

- go to `SomeEntity/$count`
- go to `SomeEntity?$count=true`

### Expected result

- number response
- `@odata.count` added as metadata to response

### Actual result

- returns 404
- does not include `@odata.count`

**Comment by robward-ms** [comment]
Fixed by #1152

**Comment by techniq** [comment]
I was just trying to pull this down and build, but currently getting the following error (project built fine before this change).

![image](https://user-images.githubusercontent.com/177476/33863454-c72325d6-deb5-11e7-9b26-0db1f8ed5349.png)

I'm using Visual Studio for Mac with .NET Core 2.0.  It could still be on my side.

**Comment by techniq** [comment]
actually getting a few errors during a build:

![image](https://user-images.githubusercontent.com/177476/33863521-2bb322ee-deb6-11e7-9f98-defa5ba15a04.png)

**Comment by techniq** [comment]
Sorry, disregard.  I had to force VS to refresh the solution to see the changes.

**Comment by techniq** [comment]
@robward-ms Sorry for all the noise, but I just checked, and while inline counts (`?$count=true`) are now working, `/$count` is still returning a 406 (not acceptable).  Is there possibly something else I need to add to Startup to enable this endpoint?

**Comment by robward-ms** [comment]
The /$count is likely an issue with formatting, #1157 has the latest formatting code. I'm seeing a good pass rate in the latest code on my working branch (NetCore-Latest). I'll leave the issue open until we can verify it's fixed.

**Comment by techniq** [comment]
@robward-ms Thanks.  I've been collecting a list of items I've found that currently do not work.  Should I log them as individual issues, or create 1 issue with a bulleted/checklist?  Some are fairly specific (ex. nested $expands) and some might become fixed on your latest changes.

Unrelated, but I just logged this (https://github.com/OData/lab/issues/79) that you might have some feedback on.

Thanks for all your hard work.

**Comment by robward-ms** [comment]
@techniq - Yes, please do files issues. I think an issue per bug is cleaner but if they are related, i.e. $expand problems, feel free to lump those together.

**Comment by techniq** [comment]
@robward-ms Sounds good.  I'll look to pull down your NetCore-Latest and test there before submitting new issues (that might already been resolved by unmerged PRs).  Is that branch your "develop" branch that you keep in sync with your pending PRs?

**Comment by robward-ms** [comment]
@techniq - Yes, NetCore-Latest is where I keep the latest dev code. At this point, they are really close product code-wise (NetCore-Latest has unit tests though). The main difference now is the formatter PR #1157. They will converge in the next week or so.

**Comment by techniq** [comment]
@robward-ms I just pulled down your NetCore-Latest branch and `/$count` was working.  I'll leave this issue open until I see #1157 resolved (feel free to make this issue as resolved via that PR if you want as well)

**Comment by techniq** [comment]
This is fixed and can be closed (using 7.0.0-Nightly201712181325).  I don't seem to have the ability to close this myself now.

**Comment by robward-ms** [comment]
@techniq - Thanks for the feedback!

**Comment by engenb** [comment]
I think this needs to be reopened.  I am encountering this exact issue with Microsoft.AspNetCore.Odata / Microsoft.AspNetCore.OData.Versioning.ApiExplorer

**Comment by Echarnus** [comment]
> I think this needs to be reopened. I am encountering this issue with Microsoft.AspNetCore.Odata 7.2.1 / Microsoft.AspNetCore.OData.Versioning.ApiExplorer 3.2.3
> 
> `/resource$count=true` works
> `/resource/$count` does not work (404)

Can confirm. Having the same issue over here.
