### ISSUE TITLE
[feature/netcore] Exception when attempting to consume ODataQueryOptions function parameter

### ISSUE THREAD

**Issue by techniq** [OData/WebApi#1161]
### Assemblies affected

Latest MyGet 7.0.0 release and @robward-ms's NetCore-Latest branch as of [now](https://github.com/robward-ms/WebApi/commit/58a731dc1b8ea2668f80dc8739f0324fa9aa33ac)

### Reproduce steps

Create a function that consumes an `ODataQueryOptions` parameter:
```c#
[HttpGet]
public IActionResult Export(ODataQueryOptions<Employee> queryOptions)
{
    throw new NotImplementedException();

    // Typically would apply the queryOptions to a context and then modifying the IQueryable further
    /*
    var query = queryOptions.ApplyTo(DbContext.Set<Employee>()) as IQueryable<Employee>;
    var exportQuery = query.Select(r => new EmployeeExport { ... });
    return Ok(exportQuery);
    */
}
```
and expose it within `Startup`
```c#
private static IEdmModel GetEdmModel(IServiceProvider serviceProvider)
{
    var builder = new ODataConventionModelBuilder(serviceProvider);
           
    builder.EntityType<Employee>()
        .Collection
        .Function("Export")
        .ReturnsFromEntitySet<Employee>("Employees");

    return builder.GetEdmModel();
}
```

and then call it, for example `http://localhost:5000/odata/Employees/Default.Export`

### Expected result

Populated `queryOptions` based on the OData query filter (`$select`, `$expand`, ...)

### Actual result
`SocketException: Operation not supported`

![image](https://user-images.githubusercontent.com/177476/33907914-c263a044-df54-11e7-86d4-a2f66eb24d20.png)

**Comment by robward-ms** [comment]
Fixed in the Nightly build that is newer than 201712151325 (2017-12-15 13:25)
