### ISSUE TITLE
[feature/netcore] SocketException when attempting basic example

### ISSUE THREAD

**Issue by gordon-matt** [OData/WebApi#1167]
Issue #1165 was closed, but the problem persists. Perhaps the fix somehow wasn't pushed to myget? Otherwise, I don't know. Please reopen that issue and you can delete this one then.

**Comment by robward-ms** [comment]
Yep, you need the Nightly build that is **newer** than 201712151325 (2017-12-15 13:25). I wrote the comment before the build had dropped not knowing it's final name. That build failed but one just finished, you need 201712180820.

**Comment by robward-ms** [comment]
Dup of 1165. I re-opened #1165 , I'll let you confirm, the fix on that issue.
