### ISSUE TITLE
Model from ODataConventionModelBuilder different from ReadMetadataDocument

### ISSUE THREAD

**Issue by johnhzhu** [OData/WebApi#1169]
Followed code http://odata.github.io/odata.net/v7/ to re-build a model as below. But the new model is a CsdlSemanticsModel instead of an EdmModel, and the ODataPath object will consist of CSDL segments instead of EntitySet segments. How to convert CsdlSemanticsModel  to EdmModel?

IEdmModel edmModel = (new ODataConventionModelBuilder()).GetEdmModel();
MemoryStream stream = new MemoryStream();
InMemoryMessage message = new InMemoryMessage { Stream = stream };
ODataMessageWriterSettings writerSettings = new ODataMessageWriterSettings();
ODataMessageWriter writer = new ODataMessageWriter((IODataResponseMessage)message, writerSettings, model);
writer.WriteMetadataDocument();
stream.Position = 0;
ODataMessageReaderSettings settings = new ODataMessageReaderSettings();
ODataMessageReader reader = new ODataMessageReader((IODataResponseMessage)message, settings);
IEdmModel modelFromReader = reader.ReadMetadataDocument();

**Comment by AlanWong-MS** [comment]
Closing this issue in favor of [OData #1021](https://github.com/OData/odata.net/issues/1021).
