### ISSUE TITLE
Support of adding instance annotations to complex types

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#117]
It's to add the ability of adding instance annotations to complex types  
## Work Item Details

**Original CodePlex Issue:**    [Issue 2013](http://aspnetwebstack.codeplex.com/workitem/2013)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Jun 13, 2014 at 4:08 AM
**Reported by:**    azhou
**Updated on:** Jun 13, 2014 at 4:08 AM
**Updated by:** azhou

**Comment by mikepizzo** [comment]
I think this is now supported.
