### ISSUE TITLE
ASP .NET Core error on start [feature / netcore]

### ISSUE THREAD

**Issue by ErliSoares** [OData/WebApi#1176]
On start Odata show this erros:

InvalidOperationException: No media types found in 'Microsoft.AspNet.OData.Formatter.ODataInputFormatter.SupportedMediaTypes'. Add at least one media type to the list of supported media types.

**Comment by ErliSoares** [comment]
[It does not work
](https://q-a-assistant.info/computer-internet-technology/exception-connecting-excel-to-net-core-v1-1-odata-v4-add-at-least-one-media-type/3883239)

**Comment by robward-ms** [comment]
@ErliSoares - Can you provide some information about your startup, controller and the request url?

**Comment by ErliSoares** [comment]
Duplicate sorry #1177
