### ISSUE TITLE
Support Edm.Date

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#118]
Currently OData support extends to Edm.DateTime for System.DateTime and
Edm.Time for System.TimeSpan.  
  
Can we please have the ability to set the Edm as Date? I am storing it as Date
in the database, and would like this to extend all the way to the OData level.  
  
Either:  

    
    
    entityType.Property(p => p.AgreementDate).EdmType = EdmType.Date;
    

Or:  

    
    
    [DataType(DataType.Date)]
    public DateTime AgreementDate { get; set; }
    

Would be great!  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2015](http://aspnetwebstack.codeplex.com/workitem/2015)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jun 13, 2014 at 9:44 AM
**Reported by:**	Apathy
**Updated on:**	Sep 17, 2014 at 11:44 PM
**Updated by:**	j_thorn

**Comment by congysu** [comment]
The ask is for Edm.Date with EF support.
