### ISSUE TITLE
filtering string type on dynamic properties not supported and causes misleading error message.

### ISSUE THREAD

**Issue by ozanmut** [OData/WebApi#1180]
Filtering on dynamic properties with non-string types works, but when filtering on string values, it gives this exception:
`Microsoft.OData.Core.ODataException: 'The 'tolower' function cannot be applied to an enumeration-typed argument.'`

### Assemblies affected

****OData WebApi 5.10.0, 
OData WebApi 5.11.0****

### Reproduce steps
       Write an odata action which has an odata mapping similar to this: 
   `conf.ReturnsCollection<CmInfo>();`
           
        [DataContract]
        public class CmInfo
	    {
          [DataMember]
          public string Name { get; set; }
          [DataMember]
 	      public IDictionary<string, Object> CmValues { get; set; }
	    }
then make a request like this:
http://localhost:9993/Service/OData/GetDynamicCmInfo?$filter=contains(tolower(BTS)%2C%20tolower(%27KK%27))%20eq%20true

BTS is the dynamic property being filtered on. 'KK' is the filter value.

### Expected result

Filter should work, and there should not be an exception.

### Actual result

Exception is thrown, filtering doesn't work.

### Additional detail

Error occurs in System.Web.OData.Query.Expressions.FilterBinder.cs where it checks  
`if (arguments.Any(arg => arg.Type != typeof(string)))
            {
                throw new ODataException(Error.Format(SRResources.FunctionNotSupportedOnEnum, functionName));
            }`
in which arg.Type is an object type.

**Comment by Compufreak345** [comment]
FYI: This is still an issue for the current nightly release for feature/netcore (Odata 7.0.0). It can easily be reproduced if you set the setter for a property to private.

Working:
`public string Title { get;set; }`
Not working:
`public string Title { get;private set; }`

The Title-column is calculated server-side thus a private setter would be correct to prevent setting of the property.
```
 // Add calculated title
            modelBuilder.Entity<UserProfile>()
                .Property(p => p.Title)
                .HasComputedColumnSql("[FirstName] + ' ' + [LastName]");
           
```

**Comment by sandeepagrawal921** [comment]
Hi Team,
This is still an issue in Microsoft.AspNetCore.Odata -7.4.0. Do we have any solution for this yet? this is kind of urgent for client implementation.

**Comment by gathogojr** [comment]
Fixed in [Microsoft.AspNetCore.OData 8.0.11](https://www.nuget.org/packages/Microsoft.AspNetCore.OData/8.0.11) via update of [Microsoft.OData.Core 7.12.2](https://www.nuget.org/packages/Microsoft.OData.Core/7.12.2) dependency - PR https://github.com/OData/odata.net/pull/2257
