### ISSUE TITLE
[feature/netcore] EdmModels not equals

### ISSUE THREAD

**Issue by genusP** [OData/WebApi#1184]
Models from HttpContext.Request.ODataFeature().Model and HttpContext.Request.GetModel() not equals.

**Comment by robward-ms** [comment]
Looks like the ODataFeature()'s model is not populated: https://github.com/OData/WebApi/blob/f140814fa7a300a88dad259124ddf45de6682bc0/src/Microsoft.AspNetCore.OData/Routing/ODataPathRouteConstraint.cs#L63-L66

I'm inclined to delete model from ODataFeature(), thoughts?

**Comment by genusP** [comment]
Delete model from ODataFeature(), broke backward compatibility.

**Comment by robward-ms** [comment]
@genusP - Broke backwards compatibility with the vNext code? Since that was never released in binary form, do we need to be concerned with back-compat?

**Comment by genusP** [comment]
Ups. I through that this API equals between Core and non-Core versions.  No objections.
