### ISSUE TITLE
Method Not Found: Void Microsoft.OData.ODataObjectModelExtensions.SetSerializationInfo(Microsoft.OData.ODataResource, Microsoft.OData.ODataResourceSerializationInfo)

### ISSUE THREAD

**Issue by TonyValenti** [OData/WebApi#1193]
It seems like an overload is missing when using:
Microsoft.OData.Core v. 7.4.0.11218
instead of 
v 7.3.1

**Comment by mprigge** [comment]
Just stumbled across this same issue. Had to update to 7.4.0-beta2 versions of ODL due to a tangle of other dependencies and this caused this exception. One step earlier at ODL 7.4.0-beta (11102) does not.

**Comment by mikepizzo** [comment]
Thanks for the report. I think this is due to some of the refactoring we did for delta, but our E2E tests should have caught any issues. Will investigate...

**Comment by mikepizzo** [comment]
Introduced a base class and bound the extension method to the base class instead of the derived class. Apparently the method resolver doesn't find the method on the base class. Recompiling would fix, but since this is a breaking change we should restore the extension method on the derived class.

**Comment by mikepizzo** [comment]
Please confirm fixed in [7.4 Beta 3](https://www.nuget.org/packages/Microsoft.OData.Core/7.4.0-beta3).  RTM should go out later today.

Thanks for catching this!

**Comment by mprigge** [comment]
Fixed! Thank you!
