### ISSUE TITLE
add model validation pass in odata model builder

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#12]
we should validate things like when users build edm models explicitly (not for
the implicit model we build in query composition)  
1) an entity type has key(s).  
2) an entity type has a corresponding entity set.  
3) all navigation properties are bound to an entity set.  
4) a non-abstract entity type is bound to a non-abstract clr type.  
5) all properties in an edm type have public setters and public getters in the
backing clr type.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 437](http://aspnetwebstack.codeplex.com/workitem/437)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Sep 20, 2012 at 7:34 PM
**Reported by:**	raghuramn
**Updated on:**	Oct 3, 2013 at 11:49 PM
**Updated by:**	danroth27

**Comment by LianwMS** [comment]
On *2012-09-21 06:18:29 UTC*, **HongmeiG** commented:

We can validate the model when someone calls builder.GetEdmModel().

**Comment by LianwMS** [comment]
On *2013-10-04 06:49:23 UTC*, **danroth27** commented:

We should do this by default (with option to disable) as part of our OData v4.0 work.

**Comment by xuzhg** [comment]
Already added a validation function at https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Builder/ODataModelBuilder.cs#L599-L623
