### ISSUE TITLE
Entity relation with extra key parameter

### ISSUE THREAD

**Issue by bdebaere** [OData/WebApi#1200]
My employer asks me to create a resource like Customers(id)/Orders(id), is this even possible?

**Comment by xuzhg** [comment]
What do you mean? 
The Uri is valid in OData. The convention routing has the logic to handle this Uri. Its template is "EntitySet/Key/NavigationProperty/Key".

**Comment by bdebaere** [comment]
@xuzhg Do you have an example on how to create this? I have the code below for a simple entity relation on a collection. But receive the error when trying http://localhost:/Customers(6)/Orders(2) for example. What am I missing?

```
{
    "error": {
        "code": "",
        "message": "No HTTP resource was found that matches the request URI 'http://localhost:/Customers(6)/Orders(2)'.",
        "innererror": {
            "message": "No routing convention was found to select an action for the OData path with template '~/entityset/key/navigation/key'.",
            "type": "",
            "stacktrace": ""
        }
    }
}
```

```csharp
        [HttpGet]
        [EnableQuery]
        public IQueryable<Order> GetOrders([FromODataUri] int key)
        {
            RepositoryOrder repositoryOrder = ;

            IQueryable<Order> orders = repositoryOrder
                .Select(key)
                .Include(i => i.Orders)
                .SelectMany(sm => sm.Orders);

            return orders;
        }
```

**Comment by xuzhg** [comment]
@bdebaere 

Sorry, what I mentioned in the previous "The convention routing has the logic to handle this Uri." is not correct. 

You can use attribute routing or You can refer to the below example:

https://github.com/xuzhg/WebApiSample/commit/671ed7f2de4d1a20874fa2cc8688b9a2ff4a755c

**Comment by bdebaere** [comment]
@xuzhg The sample you linked appears to no longer be valid with System.Web.OData, Version=6.1.0.10907. `KeyValuePathSegment` for example is no longer found in the assembly, as is `NavigationPathSegment`. Is it possible to provide an example working on the latest Microsoft.OData.Core, Version=7.3.1.10814?

**Comment by xuzhg** [comment]
@bdebaere 
For the Web API OData v6.x and ODL 7.x example, you can refer to: https://github.com/xuzhg/WebApiSample/commit/6a2dfc679f2b935cf9fd89faa682ee894f727e02

**Comment by bdebaere** [comment]
@xuzhg I see now, this is a truly custom implementation. You cannot automatically have it know what to look for. If for example the Order entity has a list of Supplier entities then you would have to write a custom implementation again for `http://localhost/odata/NavCustomers(1)/Orders(2)/Suppliers(3)`. Is that correct?

**Comment by xuzhg** [comment]
For the convention routing, I think yes. 
But, you can use the attribute routing. For attribute routing, you can refer to: http://odata.github.io/WebApi/#03-03-attrribute-routing
