### ISSUE TITLE
[feature/netcore] Nested `$expand` not working

### ISSUE THREAD

**Issue by techniq** [OData/WebApi#1205]
When attempting to expand more than 1 level deep the property is added to the model but set to null.  I also do not see any mention of it in the EFCore sql query.  Other operators seem to work (at least `$select`)

### Assemblies affected
- 7.0.0-Nightly201801081323

### Reproduce steps

Attempt to expand more than 1 level deep.  For example:
  - `http://localhost:5000/odata/Employees?$expand=Supervisor($expand=Position)`

### Expected result
```js
{
  "@odata.context": "http://localhost:5000/odata/$metadata#Employees",
  "value": [
    {
      ...
      "Supervisor": {
        ...
        "Position": { ... } // Populated with Position properties
      }
    },
    ...
  ]
}
```

### Actual result

```js
{
  "@odata.context": "http://localhost:5000/odata/$metadata#Employees",
  "value": [
    {
      ...
      "Supervisor": {
        ...
        "Position": null
      }
    },
    ...
  ]
}
```

### Additional detail
I've attempted to set `[EnableQuery(MaxExpansionDepth = 3)]` on the endpoint but resulted in no change.

**Comment by robward-ms** [comment]
@techniq - Can you provide the code that builds the model?

**Comment by robward-ms** [comment]
@techniq - Can you provide the code that builds the model?

**Comment by techniq** [comment]
@robward-ms Actually, I think I have more details that can help (after some more testing).

Currently, this still returns the `null` Position as indicated above:

```c#
[EnableQuery()]
public IQueryable<Employee> Get()
{
    return DbContext.Employees;
}
```

but using the following fixes this problem

```c#
[HttpGet]
public IActionResult Get(ODataQueryOptions<Employee> queryOptions)
{
    var querySettings = new ODataQuerySettings()
    {
        // Workaround for: https://github.com/aspnet/EntityFrameworkCore/issues/10721
        HandleNullPropagation = HandleNullPropagationOption.False
    };

    var query = queryOptions.ApplyTo(DbContext.Set<Employee>(), querySettings);
    return Ok(query);
}
```

Removing `HandleNullPropagation = HandleNullPropagationOption.False` shows the same issues as `[EnableQuery]`, but adding it fixes this issue (and aspnet/EntityFrameworkCore/issues/10721).  I also thought it fixed https://github.com/aspnet/EntityFrameworkCore/issues/10721, but after more testing, that looks to be fixed even using `[EnableQuery()]` now (I'm using `7.0.0-Nightly201802211312`)

**Comment by robward-ms** [comment]
@techniq - On EFCore? 

There is some code missing to set NullPropgation for EFCore, I have it in the EFCore investigation branch: https://github.com/robward-ms/WebApi/blob/0ba1ddca056555a1aef556e6493c57b29dcef2ed/src/Microsoft.AspNet.OData.Shared/Query/HandleNullPropagationOptionHelper.cs

**Comment by techniq** [comment]
@robward-ms yes, `2.0.1`

**Comment by techniq** [comment]
Resolved, thanks @robward-ms

**Comment by elefantelimpio** [comment]
Does anyone knows why I have to explicitly add NavigationParameters when I try to query my API with $Expand. In Framework 4.6 API with OData V4 I only had to add the reserved word "Virtual" to each navigation property.

Those images are from my AspNetCore.OData API
![image](https://user-images.githubusercontent.com/11888892/38821768-ca79d348-41a1-11e8-9a75-7a1e01d0a813.png)
![image](https://user-images.githubusercontent.com/11888892/38821815-e8929d2e-41a1-11e8-827b-66342337a1ba.png)
![image](https://user-images.githubusercontent.com/11888892/38821844-f52a048c-41a1-11e8-9c27-75d3321c083e.png)
