### ISSUE TITLE
.net core 2.0.0  - get single item by guid

### ISSUE THREAD

**Issue by suadev** [OData/WebApi#1209]
Hi,

I am trying to get single item by primary key, and the pk is a guid. The odata request url ;

http://localhost:5021/v1/OutboxDespatch(55208e81-0363-471a-bb67-2be2045ec522) 

The get request reach my action, it is ok. But it returns entire list, not the single item. 

And idea?

![image](https://user-images.githubusercontent.com/5918811/34893017-76d7e1c0-f7ec-11e7-94d7-8a8336f2e3a1.png)

**Comment by suadev** [comment]
Is anybody there?

**Comment by voltage220** [comment]
> Is anybody there?

Hi. 
Please show me your controller. I probably know the solution.

**Comment by suadev** [comment]
@voltage220 

```cs
    public class OutboxDespatchController : BaseController
    {
        [EnableQuery]
        [HttpGet]
        public  IActionResult Get()
        {
            var list = _despatchAdviceService.GetList(); //returns IQueryable<T>
            return Ok(list);
        }
    }
```

**Comment by voltage220** [comment]
@suadev 
Maybe action must take argument Id for getting element by Id...
Please [look](https://github.com/voltage220/AspNetCore_OData_v7b1/blob/981e006964c4777522b10673c29d81f05a6596b0/ODataService/ODataService/Controllers/ProductsController.cs#L35) my simple project. There is example you request.

**Comment by suadev** [comment]
@voltage220 no buddy, you can get single result with;

http://localhost:5021/v1/OutboxDespatch**(55208e81-0363-471a-bb67-2be2045ec522)** 

No need to create another Get(string id) action in your controller. I think this is a lack of .net core api.

**Comment by genusP** [comment]
return ObjectResult from action

**Comment by robward-ms** [comment]
@suadev - The default [routing conventions](http://odata.github.io/WebApi/#03-02-built-in-routing-conventions) provide an example of how to achieve this scenario. @voltage220 is correct in that we would expect to route http://.../object(key) to a Get(keyType key) method.

WebApi OData for ASP.NET Core does not leverage the internal routing mechanisms of ASP.NET Core; a route that works in ASP.NET Core will not necessarily work in OData.

**Comment by suadev** [comment]
@robward-ms, so http://.../object(key) should not hit the action below, right? But it does. 

I am gonna try an action like Get(keyType key), asap. 

Thanks.


```cs 
        [EnableQuery]
        [HttpGet]
        public  IActionResult Get()
        {
            var list = _despatchAdviceService.GetList(); //returns IQueryable<T>
            return Ok(list);
        }    
```

**Comment by robward-ms** [comment]
Well, the HttpGet() may get it caught up ion Asp.Net Core routing (as opposed to OData routing). OData will not route it to this method. Can you try removing [HttpGet] and see how that change things?

**Comment by AlanWong-MS** [comment]
@suadev, are you still seeing the issue? To reiterate, the current advice is to try writing a separate method to handle GUIDs themselves, e.g. Get(Guid id). I may be missing something but according the sample code you've provided
```
        public  IActionResult Get()
        {
            var list = _despatchAdviceService.GetList(); //returns IQueryable<T>
            return Ok(list);
        }
```
it seems like you may be returning a list each time (where the list could be a single item at times). Is that intended?

@andrew-laughlin, thanks for the report. It sounds like it will require a separate investigation into the ApplyTo call. It could be the case of a missing functionality. Can you please open a separate issue for that? Thanks.

**Comment by mikepizzo** [comment]
If I understand the issue correctly, this is by design.

ApplyTo applies the filter, select, expand, top, skip, etc. *query options* to controller methods that return a collection.  Similarly, the [EnableQuery] attribute applies the same query options to a controller method that handles a path that represents a collection.

Neither were designed to support an individual key-lookup expression which, as Rob says, has different odata routing (i.e., to a method that takes the key value and is typed to return a single instance of the entity).

**Comment by DennisInSky** [comment]
Even though I have those 2 methods in my controller, querying an item by its key does not get routed to the second method. The whole list of items is returned instead without hitting the first method.

`[HttpGet]
[EnableQuery]
public ActionResult<IEnumerable<Product>> Get()
{
    return new ProductService().GetProducts();
}

public SingleResult<Product> Get([FromODataUri] int id)
{
    throw new NotImplementedException();
}`

{"@odata.context":"https://localhost:44316/odata/$metadata#Products","value":[{"Id":1,"Name":"Milk","Price":10},{"Id":2,"Name":"Chocolate","Price":5}]}
