### ISSUE TITLE
Should support Action/Function returns contained entities.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#121]
Now no API is exposed on ActionConfiguration to set the return type of an
Action/Function to Contained Entity Type.  
And these 2 are only for primitive/complex/enum types:  

```
    public ActionConfiguration Returns<TReturnType>();
    public ActionConfiguration ReturnsCollection<TReturnElementType>();
```
## Work Item Details

**Original CodePlex Issue:**    [Issue 2021](http://aspnetwebstack.codeplex.com/workitem/2021)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Jun 18, 2014 at 7:14 AM
**Reported by:**    jinfutan
**Updated on:** Aug 6, 2014 at 7:02 AM
**Updated by:** royoung

**Comment by vojtechvit** [comment]
+1 !!

**Comment by chuanboz** [comment]
+1
