### ISSUE TITLE
String Equals should have a StringComparison

### ISSUE THREAD

**Issue by grahamehorner** [OData/WebApi#1215]
when building using VS 2017 code analysis shows a number of errors/warnings with regards to {string].Equals not using a StringComparison type which results in 👎 

Error	CA1307 The behavior of 'string.Equals(string)' could vary based on the current user's locale settings. Replace this call in ... with a call to 'string.Equals(string, System.StringComparison)'.

**Comment by xuzhg** [comment]
@grahamehorner Would you please let us know which C# project (or branch) are you mentioning? Thanks!

**Comment by xuzhg** [comment]
close it. please let us know any further question and problem. Thanks.
