### ISSUE TITLE
[feature/netcore] OData classes replacements

### ISSUE THREAD

**Issue by raffaeler** [OData/WebApi#1218]
I am trying to build the simplest possible edm model for a bunch of clr types.

### Assemblies affected

Using Microsoft.OData.Core 7.3.1 and Microsoft.AspNetCore.OData 7.0.0-beta1

### Reproduce steps

I am trying to port a library to the new set of classes and can't find the replacements.

1. which is the replacement for EntitySetPathSegment ?
The goal is retrieving a valid ODataQueryContext
```
var mymodel = GetModelBuilder(null, rootType).GetEdmModel();
var segment = new System.Web.OData.Routing.EntitySetPathSegment("anything");
var path = new System.Web.OData.Routing.ODataPath(segment);
var context = new System.Web.OData.ODataQueryContext(mymodel, entityType, path);
```

2. The first ODataConventionModelBuilder parameter is IServiceProvider
Since I am working outside aspnet/aspnetcore, is this implementation sufficient to satisfy OData needs?
```
private class ServiceProvider : IServiceProvider
{
    public object GetService(Type serviceType)
    {
        return Activator.CreateInstance(serviceType);
    }
}
```

Thanks

**Comment by robward-ms** [comment]
@raffaeler - some answer below:

1.) I think you are looking for [Microsoft.OData.UriParser.EntitySetSegment](https://github.com/OData/odata.net/blob/dece13339942dd5ef7405e38720991063ec8ee39/src/Microsoft.OData.Core/UriParser/SemanticAst/EntitySetSegment.cs)

2.) The relevant code is [here](https://github.com/OData/WebApi/blob/ba37702e8371a3f361e6075f8c20dbb343620e03/src/Microsoft.AspNetCore.OData/Builder/ODataConventionModelBuilder.cs#L49-L52). What you need to provide is an ApplicationPartManager which is an Asp.Net Core class. You would need a service provide that contains an ApplicationPartManager. We have an article explaining dependency injection [here](http://odata.github.io/odata.net/v7/#01-05-di-support).

**Comment by robward-ms** [comment]
@raffaeler - For question 2, let's use #1219 track the issue that you may not be able to use an ApplicationPartManager in your scenario. WebApiAssemblyResolver wraps ApplicationPartManager  with now way for you to inject one of your own. The fix for #1219 will address that and then you can create a service container with an AssemblyResolver that does not require Asp.Net or Asp.Net core classes.

**Comment by raffaeler** [comment]
Got it @robward-ms 
I already injected ApplicationPartManager as well as ODataQuerySettings, IEdmModel (manually build from me), ODataUriResolver, ODataSimplifiedOptions and ODataUriParserSettings, but it didn't work and I am stuck.
I discovered the need to register all those instances after getting exceptions after exceptions, but it looks definitely not a good way to proceed.

If you believe this thread should be closed in favor of #1219 feel free to do it. After all my target is described there.

**Comment by robward-ms** [comment]
@raffaeler - Stuck on the assembly resolver thing? I have a CR, #1236, which fixes the assembly resolver issue. I was planning to provide a static class that allows you to inject any assemblies you like (no need to implement a resolver itself or the container). However, I found out that .Net Core supports AppDomain.CurrentDomain so I plan to use this for the default assembly resolver, meaning you have to do nothing w.r.t. assembly resolution.

If you are only stuck on assembly resolution, please close this issue.

**Comment by raffaeler** [comment]
ok, let's continue on #1219.
Hopefully your #1236 will close that too.
Thanks
