### ISSUE TITLE
[feature/netcore] FilterBinder requires an internal interface

### ISSUE THREAD

**Issue by raffaeler** [OData/WebApi#1219]
I am trying to extract a Linq Expression from an odata query filter without using asp.net.
This was possible with odata 6.

### Assemblies affected

Using Microsoft.OData.Core 7.3.1 and Microsoft.AspNetCore.OData 7.0.0-beta1

### Reproduce steps

The class `Microsoft.AspNet.OData.Query.Expressions.FilterBinder` is public but when I use it, it requires to the service provider an instance of IWebApiAssembliesResolver which is `internal`.

**Comment by robward-ms** [comment]
@raffaeler - Yep, that sure is a problem. Can you provide a small code snippet so I can understand the scenario and see what we can do to fix it?

One option I can think of, which you touch on in #1218, if to provide a non-internal version of an AssemblyResolver so you can implement one yourself to decouple from AspNetCore's ApplicationPartManager. Essentially, the IWebApiAssembliesResolver would become public and you could create one youself and return whatever assemblies you want searched.

**Comment by raffaeler** [comment]
@robward-ms I am building from scratch the code that would allow a, let's say, netcore console application to extract an Expression<Func<T, bool>> for a predicate expressed with the "$filter" clause syntax.
I built several years ago for OData6 but it was definitely a mess because of the heavy dependencies on asp.net.
With the current beta, it is definitely not possible anymore with OData7, but my wish is:
- to be able to extract predicates but also projections, orderby and other clauses
- to be totally decoupled from asp.net core
- for each clause obtain a Linq Expression so that I can visit, modify or merge it with other Expressions.

The basic steps that I had in my code are:
- build the simplest possible edm model automagically (for certain clauses defining an id is not even of interes)
- create the ODataQueryContext and a ODataQueryOptionParser with the required clauses
- define the ODataQuerySettings so that I can choose to whether support null propagation generation or not
- apply the filter to my IQueryable (this last step is not really needed, it would be even better to just create the expression.

Any code solving this transformation would be good, so there is no really need to give you some intricate code that could potentially be simplified drastically.

TIA

**Comment by robward-ms** [comment]
@raffaeler - Got it. My current PR, #1236, decouples ODataQueryContext and it's downstream classes from the request container. It also decouples ODataConventionModelBuilder from the request container as well. I think with #1236, you'll be able to accomplish all that. If not, let's fix it. 

Can you try out the nightly build with the code from #1236 when it is available?

**Comment by xuzhg** [comment]
Close it. Please re-open it or file new issue if you have further concern. Thanks.
