### ISSUE TITLE
Should support NavigationPropertyBinding which contains a Navigation Property to a contained entity.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#122]
Say there is such Edm Model as below, now we don't have an API to set the
NavigationPropertyBinging:  

```
      <EntitySet Name="Accounts" EntityType="WebStack.QA.Test.OData.Containment.Account">
         <NavigationPropertyBinding Path="PayoutPI/Statement" Target="Statements" />
      </EntitySet>
```

where PayoutPI is a containment navigation property.  

```
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
 <edmx:DataServices>
  <Schema Namespace="WebStack.QA.Test.OData.Containment" xmlns="http://docs.oasis-open.org/odata/ns/edm">
    <EntityType Name="PaymentInstrument">
      <Key>
        <PropertyRef Name="PaymentInstrumentID" />
      </Key>
      <Property Name="PaymentInstrumentID" Type="Edm.Int32" Nullable="false" />
      <Property Name="FriendlyName" Type="Edm.String" />
      <NavigationProperty Name="Statement" Type="WebStack.QA.Test.OData.Containment.Statement" ContainsTarget="true" />
    </EntityType>
    <EntityType Name="Account">
      <Key>
        <PropertyRef Name="AccountID" />
      </Key>
      <Property Name="AccountID" Type="Edm.Int32" Nullable="false" />
      <Property Name="Name" Type="Edm.String" />
      <NavigationProperty Name="PayinPIs" Type="Collection(WebStack.QA.Test.OData.Containment.PaymentInstrument)" ContainsTarget="true" />
      <NavigationProperty Name="PayoutPI" Type="WebStack.QA.Test.OData.Containment.PaymentInstrument" ContainsTarget="true" />
    </EntityType>
    <EntityType Name="Statement">
      <Key>
        <PropertyRef Name="StatementID" />
      </Key>
      <Property Name="StatementID" Type="Edm.Int32" Nullable="false" />
      <Property Name="TransactionDescription" Type="Edm.String" />
      <Property Name="Amount" Type="Edm.Double" Nullable="false" />
    </EntityType>
    <EntityContainer Name="Container">
      <EntitySet Name="Accounts" EntityType="WebStack.QA.Test.OData.Containment.Account" />
      <EntitySet Name="Statements" EntityType="WebStack.QA.Test.OData.Containment.Statement" />
    </EntityContainer>
  </Schema>
 </edmx:DataServices>
</edmx:Edmx>
```
## Work Item Details

**Original CodePlex Issue:**    [Issue 2022](http://aspnetwebstack.codeplex.com/workitem/2022)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Jun 18, 2014 at 8:45 AM
**Reported by:**    jinfutan
**Updated on:** Jul 3, 2014 at 4:49 AM
**Updated by:** azhou

**Comment by LianwMS** [comment]
On *2014-07-03 11:49:11 UTC*, **azhou** commented:

It's for containment deep path.

**Comment by sab39** [comment]
If I were to work on this for the non-vNext branch, would a pull request be considered?

**Comment by xuzhg** [comment]
@sab39 Would you please try our breaking change version？ see [branch OData60](https://github.com/OData/WebApi/commits/OData60)

This branch adds the support to add navigation property binding path for complex/containment. Detail information that you can find in [this](https://github.com/OData/WebApi/commit/f1471617e332b34a686786db522b53986ea7afab) commit. 

If you want to help us the same funcationality on the master branch. It will be great.

**Comment by sab39** [comment]
Wow, that's pretty complex! The approach I was going to try probably doesn't cover nearly as many scenarios (in particular, it doesn't cover complex types at all), but it's an awful lot simpler and would be a non-breaking change.

I had in mind something like [this](https://github.com/sab39/odata.net/compare/ODataV4-6.x...sab39:sab39-contained-entitysets) (note: I threw that together quickly by editing directly on github, so it's not tested even to the point of making sure it compiles - it's just to show the general concept).

This works because it's already possible to add a navigation binding to a contained entity set by doing something like:

``` C#
var containedEntitySet = (EdmNavigationSource)rootEntitySet.FindNavigationTarget(containedNavigationProperty);
containedEntitySet.AddNavigationTarget(subNavigationProperty, targetEntitySet);
```

If I'm understanding the code right, my changes to EdmModelCsdlSchemaWriter and EdmModelCsdlSerializationVisitor would be sufficient for those bindings to get emitted to the CSDL correctly.

**Comment by xuzhg** [comment]
@sab39 It looks like you want to change the OData Lib to support this feature. If so, It'll be great for you to file an issue at https://github.com/OData/odata.net/issues. And I am looking forward your Pull request.

**Comment by sab39** [comment]
Ah, I guess so, yes. Seems I'm not quite clear yet on the separation of concerns between ODataLib and OData WebApi. Sorry. I posted to an existing issue [here](https://github.com/OData/odata.net/issues/312#issuecomment-242410626).

My project is built on WebApi (although I've overridden a lot of the default RoutingConventions and suchlike), so maybe it will need some changes on the WebApi side as well to make it work, and I just don't know what they are yet. If there's something obvious that you'd like to point out, I'll take a look and see if it applies to my use case. Regardless, I'll follow up if I find anything.

Thanks very much for your responses and guidance!

**Comment by xuzhg** [comment]
Any help and contribution from you are appreciated. If you have further questions and concerns, please let us know. Thanks.
