### ISSUE TITLE
Route with parameters

### ISSUE THREAD

**Issue by neothoms** [OData/WebApi#1222]
I am really sorry but I have been looking everywhere without solutions.

With Classic .net core MVC I would be using for my controller :
[Route("api/[controller]")]
public class ProductsController : Controller

And for my actions :
```
[HttpGet]
public IQueryable<DonneeReference> Get()

```
and then another get with another name 
```
[HttpGet]
[Route("Details")]
public IQueryable<DonneeReference> GetWithDetails()

```
I can get  localhost:xxx/Products/ 
and localhost:xxx/Products/Details

Why is it not possible to do that in a ODataController without having this error :  
The path template 'Products/Details' on the action 'GetWithDetails' in controller 'Products' is not a valid OData path template. The request URI is not valid. Since the segment 'Products' refers to a collection, this must be the last segment in the request URI or it must be followed by an function or action that can be bound to it otherwise all intermediate segments must refer to a single resource.|url: http://localhost/api/Products|action: 

Also I have another controller on which I want two levels of Ids : 
```
[HttpGet]
[Route("{trigramme}")]
public IQueryable<DonneeReference> Get(string trigramme)

```
and I can have another action on the same controller
```
[HttpGet]
[Route("{trigramme}/{id}")]
public IQueryable<DonneeReference> Get(string trigramme, string Id)
```

I can get  localhost:xxx/Products/spp/
and localhost:xxx/Products/spp/1234567/

If I use a ODataRoute I get this error
The path template '{trigramme}' on the action 'Get' in controller 'DonneesReference' is not a valid OData path template. Resource not found for the segment '{trigramme}'.|url: http://localhost/v1/api/Supports|action

And if I use Route like I used to do I don't have any anotations in the results  
"@odata.context": "http://localhost:29860/v1/api/$metadata#Products",
"@odata.count": 4,

**Comment by robward-ms** [comment]
You want to use ODataRoute and you will need to define an EdmModel which contains the entities returned by your controller. The model needs to be used in a call to MapODataServiceRoute().

The exception you are seeing occurs when the routing convention handling ODataRoute tries to parse the path using the EdmModel supplied to MapODataServiceRoute; when it cannot match the entity names in the route to entity names in the model, it throws this exception.

**Comment by neothoms** [comment]
Thank you for your answer.
I don't have time right now to test your again.

I already tried  ODataRoute without success, and another problem I am thinking about is when I Don't have the Route Attributes the Swagger documentation is not generated.

If you have good tutorials (up to date) I would love to test it. I am actually facing the problem that every article / tutorials or even documentation are for version 2 or 4 and not the actual versions.

**Comment by shawndewet** [comment]
@neothoms did you ever resolve this?  I'm running into the same error.

**Comment by neothoms** [comment]
@shawndewet Sorry. I am no longer on this project anymore and I never had time to try the ODataRoute solution suggested by robward-ms

**Comment by gathogojr** [comment]
Issue from 2018. Issue reporter advised on a solution but were not in a position to try it out after they moved off from the project
