### ISSUE TITLE
OData doesn't see QueryString when EnableQuery + AWS Lambda

### ISSUE THREAD

**Issue by CrazyBaran** [OData/WebApi#1227]
I have problem with get working OData Query on AWS Lambda. When I try locally everything works fine, but when deploy into AWS something goes wrong. It is only wrong with` EnableQueryAttribute`, when I change it into `ODataQueryOptions` and care about `ApplyTo` myself it works fine.

### Assemblies affected

Microsoft.AspNetCore.OData 7.0.0-beta1
Microsft.AspNetCore.All
Amazon.Lambda.AspNetCoreServer

### Reproduce steps

1.Made Get method with `[EnableQuery]` and allow filtering.
2. Deploy to AWS Lambda.
3. Try to request with `?$filter=startswith(Name,'K')`.

### Expected result

Should return a filtered query.

### Actual result

Return full list with odata metadata, like it will any QueryString.

### Additional detail

Walkaround for it is to use `ODataQueryOptions` as parameter in Get method.
I made additional investigation and there is QueryString in Request. Maybe something wrong with pipeline?

**Comment by biaol-odata** [comment]
@CrazyBaran Can you provide details of the additional investigation from your side, so that we can have more context? Thanks.

**Comment by CrazyBaran** [comment]
I made additional investigation and made customenablequery as:

```
 public class CustomEnableQueryAttribute : EnableQueryAttribute
    {
        public override void OnActionExecuted(ActionExecutedContext actionExecutedContext)
        {
            HttpResponse response = actionExecutedContext.HttpContext.Response;
            LambdaLogger.Log("Test "+ response.StatusCode+ " "+ (response != null).ToString() +" " + 
                response.IsSuccessStatusCode().ToString()+ " " + (actionExecutedContext.Result != null).ToString());
            
            base.OnActionExecuted(actionExecutedContext);
        }
    }
```
and result is: `Test 0 True False True`. very weird. I return in this method Ok().

**Comment by robward-ms** [comment]
@CrazyBaran - Is there a difference between your development config and AWS config. i.e. a different web server?

Can you try the following experiment?  In you OnActionExecuted:

1.) get a Uri from the HttpRequest using Microsoft.AspNetCore.Http.Extensions.UriHelper.GetEncodedUrl()
2.) See what's in the Query property of that Uri.
3.) See that's in the Query of the HttpRequest itself.

The HttpRequest is available via actionExecutedContext.HttpContext.Request.

The HttpRequest object itself, supplied by the server implementation, is a bit odd in that it only provides the parts of the Uri, not the Uri itself. The HttpRequest has a Query and QueryString property. The code path which applies the query uses an abstracted version of the request and checks the Query property of a Uri obtained from GetEncodedUrl().  See [here ](https://github.com/OData/WebApi/blob/ba37702e8371a3f361e6075f8c20dbb343620e03/src/Microsoft.AspNetCore.OData/Adapters/WebApiRequestMessage.cs#L113-L116) and [here](https://github.com/OData/WebApi/blob/ba37702e8371a3f361e6075f8c20dbb343620e03/src/Microsoft.AspNet.OData.Shared/EnableQueryAttribute.cs#L380-L389).

**Comment by CrazyBaran** [comment]
@robward-ms I wrongly investigate a problem in first time, in my opinion there is no problem with queryString, it pass correctly. Problem is with WebServer I think, when EnableQueryAttribute is executed there is no Http Code yet. As i write in previous post when i set Http Code manually odata start work.

There was some differences between local web server and AWS implementation.

**Comment by robward-ms** [comment]
@CrazyBaran - Can you post the controller Get method that is decorated with [EnableQuery]?

**Comment by CrazyBaran** [comment]
@robward-ms If you want to there is nothing fancy :)
```
        [EnableQuery(AllowedQueryOptions = AllowedQueryOptions.Filter, AllowedFunctions = AllowedFunctions.StartsWith)]
        public IQueryable<ProductDto> Get()
        {
            return _productService.GetByQuery();
        }
```

**Comment by robward-ms** [comment]
@CrazyBaran - You could try an [OKObjectResult()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.okobjectresult?view=aspnetcore-2.0) as a return type, which would explicitly set the status code as part of your response. Otherwise, an action filter is handling this for you and it guess it's possible that the order of action filters is causing an issue.

**Comment by vickityvik** [comment]
@CrazyBaran - I am seeing the same thing. Did you find any workaround for this?

**Comment by vickityvik** [comment]
@robward-ms - I tried your suggestion, but I ams still getting the whole object back.

**Comment by vickityvik** [comment]
@robward-ms - FYI I added the following to my controller to see if the query parameters were making their way from API Gateway -> Lambda -> Controller:

```csharp
            foreach (var query in HttpContext.Request.Query)
            {
                _logger.Warning(new LoggingEvent
                {
                    EventId = 5000,
                    Message = "KEY:" + query.Key + " VALUE:" + query.Value
                });
            }
```
In the logs, I am able to see the parameter and its value:
```csharp
[WARNING] 06cba715-1b7a-11e8-a692-c520719655d9 KEY:$select VALUE:code...
```

I also noticed this in the logs:
```csharp
[INFORMATION] 0HLBTJM7TS8H9 Request starting GET https://someapi/api/AddressTypes('MAIL')?%24select=code SourceContext:Microsoft.AspNetCore.Hosting.Internal.WebHost RequestPath:/api/AddressTypes('MAIL') ActionName: ActionId: [{Protocol=null, Method="GET", ContentType=null, ContentLength=null, Scheme="https", Host="someapi", PathBase="", Path="/api/AddressTypes('MAIL')", QueryString="?%24select=code", EventId={Id=1}}] 
```
Noticed that the "QueryString" is encoded.

**Comment by CrazyBaran** [comment]
@vickityvik As I write in previous post, I made custom Enable Query Attribute and set StatusCode explicitly.
```
 public class CustomEnableQueryAttribute : EnableQueryAttribute
    {
        public override void OnActionExecuted(ActionExecutedContext actionExecutedContext)
        {
            actionExecutedContext.HttpContext.Response.StatusCode = 200;
            base.OnActionExecuted(actionExecutedContext);
        }
    }
```
This is little ugly, but it work. I think the problem is with AWS implementation not with OData.

**Comment by vickityvik** [comment]
@CrazyBaran - I did see your comment, after I posted mine. :) 

I did give it a go, and it work! Thanks!

**Comment by jeremymcgee73** [comment]
Thanks for this! Helped me as well! @CrazyBaran

**Comment by grascioni** [comment]
> Thanks for this! Helped me as well! @CrazyBaran

I have no idea why but CustomEnableQueryAttribute did work for me as well. BTW, opened a related issue in the aws-lambda-dotnet repo: https://github.com/aws/aws-lambda-dotnet/issues/694

**Comment by erezgreenberg** [comment]
Thanks @CrazyBaran! You are a lifesaver

**Comment by Sayan751** [comment]
This issue should be reopened, as the suggested patch always sets the status code to 200, which always results in HTTP OK even if there is any internal error. For example, in my case, there is a null in one of column in the database, but on model-side that property is non-nullable. Naturally the conversion failed, but due to the application of the patch I still get HTTP 200 from the calling side.

**Comment by nathanvj** [comment]
This is still an issue, I have some custom role validation in my `CustomEnableQueryAttribute` and it's giving me the same response for all my OData endpoints:
```
{
  "message": null
}
```
