### ISSUE TITLE
WebAPI support for optional_$_prefix for OData system query

### ISSUE THREAD

**Issue by biaol-odata** [OData/WebApi#1230]
*WebAPI needs to support OData system query with the optional "$" prefix. For example, "GET ~/Users?filter=id eq 33" should be be acceptable and equivalent to "GET ~/Users?$filter=id eq 33".*

### Assemblies affected

*OData WebAPI master branch and next release 6.2*

### Reproduce steps

*NA -- this is a feature request.*

### Expected result

*NA -- this is a feature request.*

### Actual result

*NA -- this is a feature request.*

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by xuzhg** [comment]
@biaol-odata Is it ready to close?

**Comment by biaol-odata** [comment]
This is also ported to current WebApi/master as well: https://github.com/OData/WebApi/pull/1425
Closed. Thanks.
