### ISSUE TITLE
[feature/netcore] Document case insentive configuration for WebApi 6.x and up

### ISSUE THREAD

**Issue by robward-ms** [OData/WebApi#1231]
*Short summary (3-5 sentences) describing the issue.*

### Assemblies affected

OData WebApi lib 6.0.0 and up.

### Issue

The case insensitivity, unqualified function/action and prefix-free enums are not documented for 6.x and up, the documentation for 5.x no longer works: http://odata.github.io/WebApi/#06-01-custom-url-parsing

**Comment by alexdresko** [comment]
Can you provide a short explanation of what needs to change to support case insensitivity?

**Comment by xuzhg** [comment]
@robward-ms are you still willing to work on this?

**Comment by robward-ms** [comment]
@xuzhg - Actually, I never started. Can you handle this?

**Comment by mikepizzo** [comment]
Fixed by PR #1426.
