### ISSUE TITLE
[feature/netcore] No results when "count=true" is set

### ISSUE THREAD

**Issue by gordon-matt** [OData/WebApi#1235]
When I have "**&$count=true**" in the query, the server code (the controller action) is called 10 times and then nothing is returned. If I remove that, it works fine. Has something changed in the way we need to return the count?

**UPDATE**: It may also be worth mentioning that when I try the URL directly (instead of AJAX), the browser tells me the connection was reset. As soon as I remove the **$count** param, then everything works fine.

**Comment by robward-ms** [comment]
Can you provide the routing configuration section and the full URL? We've seen a couple of issues where $count is not working for non-OData routes, wondering if that is what you are seeing here.

**Comment by gordon-matt** [comment]
As follows:

```
app.UseMvc(routes =>
{
	// Enable all OData functions
	routes.Select().Expand().Filter().OrderBy().MaxTop(null).Count();

	foreach (var registrar in registrars)
	{
		registrar.Register(routes, app.ApplicationServices);
	}
	//etc

```

These registrars you see above are instances of an interface of mine called, `IODataRegistrar`, which is defined as follows:

```
public interface IODataRegistrar
{
	void Register(IRouteBuilder routes, IServiceProvider services);
}
```

So far I only have instance one of these and it is defined as follows:

```
public void Register(IRouteBuilder routes, IServiceProvider services)
{
	ODataModelBuilder builder = new ODataConventionModelBuilder(services);

	builder.EntitySet<Page>("PageApi");
	builder.EntitySet<PageType>("PageTypeApi");
	builder.EntitySet<PageVersion>("PageVersionApi");
	// etc

	routes.MapODataServiceRoute("OData_Mantle_CMS", "odata/mantle/cms", builder.GetEdmModel());
}
```

And the URL I have been testing is as follows:

`http://localhost:13010/odata/mantle/cms/PageTypeApi?$format=json&$top=10&$orderby=Name&$count=true`

As previously mentioned, removing the $count param works fine. Also I noticed that sending $count=false works fine as well. It only fails when it's set to true.

**Comment by robward-ms** [comment]
@gordon-matt - I used the MapODataServiceRoute() line from your repo as well as the Url in a simple controller scenario and it works as expected. I suspect we're seeing an issue with the backend.

What's backing up your controller, i.e. where are the PageType objects stored an how many are there?

**Comment by gordon-matt** [comment]
The controller in question looks like this:

```
public class PageTypeApiController : GenericODataController<PageType, Guid>
{
    public PageTypeApiController(IPageTypeService service)
        : base(service)
    {
    }
    // etc
```

It inherits from the following:

```
public abstract class GenericODataController<TEntity, TKey> : ODataController
    where TEntity : class
{
    // etc
    
    public virtual async Task<IEnumerable<TEntity>> Get(ODataQueryOptions<TEntity> options)
    {
        if (!CheckPermission(ReadPermission))
        {
            return Enumerable.Empty<TEntity>().AsQueryable();
        }

        options.Validate(new ODataValidationSettings()
        {
            AllowedQueryOptions = AllowedQueryOptions.All
        });

        using (var connection = Service.OpenConnection())
        {
            var query = connection.Query();
            query = ApplyMandatoryFilter(query);
            var results = options.ApplyTo(query);
            return await (results as IQueryable<TEntity>).ToHashSetAsync();
        }
    }
    
    // etc
}
```

This is the **exact** same code that works perfectly well in an older (MVC5) version of my framework.

There's only 1 record in the Page Types table at the moment.

If the above doesn't help, let me know and I will see if I can make a small demo project with the issue and upload it here to GitHub.

**Comment by gordon-matt** [comment]
Okay I have created a demo of the problem for you, which you can find here: [OData_Test](https://github.com/gordon-matt/OData_Test)

Just run `Update-Database` to create the DB and run this **SQL INSERT** script:

```
INSERT INTO [OData_Test].[dbo].[Mantle_PageTypes] ([Id], [LayoutPath], [Name])
VALUES('0BEDC229-2280-46FA-B157-BCE4F1CDDEAA', NULL, 'Standard Page')
```

Then simply run the demo and try the following (with and without **$count**):
http://localhost:14718/odata/PageTypeApi?$format=json&$top=10&$orderby=Name&$count=true

Perhaps I have done something stupid somewhere, but like I said: the code in the `Get()` method is exactly the same as working code in my MVC5 version which doesn't cause any issues at all.

**Comment by robward-ms** [comment]
Thanks, I'll take a look. Seems like the backend should be a non-issue in this case.

**Comment by robward-ms** [comment]
@gordon-matt - Thanks for such a comprehensive repro. It was indeed need since you were not providing this portion of the controller"
            using (var connection = Service.OpenConnection())
            {
                var query = connection.Query();
                query = ApplyMandatoryFilter(query);
                var results = options.ApplyTo(query);
                return await (results as IQueryable<TEntity>).ToHashSetAsync();
            }

The error is that the connection object has been disposed when the $count is computed. Since the $count will have to go hit the DB, it needs the connection. If I remove the using, the URL works as you expect.

I'm not entirely clear on the dispose pattern for controller in Core; I know there was a Request.RegisterForDispose() in ASP.NET. I'll see if I can find an answer tomorrow; without a good answer for dispose, $count is a bit messed up.

**Comment by robward-ms** [comment]
I chatted with the ASP.NET Core folks and currently it seems like out $count implementation is the part that is not ideal. While you would work-around the problem by creating the DB connection as a scoped object in the DI container, which would keep it around for the lifetime of the request, and then accept the connection in the constructor of the controller (this is a recommended pattern for services), it would be better if the $count query occurred in the context of ApplyTo(), which it does not today.

I'm going to see what I can do about fixing that.

**Comment by robward-ms** [comment]
Totally trivial fix except that is was purposely changed due to RESTier, see #1 and [this ](https://github.com/OData/WebApi/commit/533213984a8f80802d31ceb1e0542b8d38be6ce8) commit.

**Comment by gordon-matt** [comment]
@robward-ms Thanks. Just got back from a holiday and saw your messages and noticed that while you mentioned it is due to a change made on purpose, you've left the issue open. Are you still working on a fix or what is your recommendation then?

**Comment by robward-ms** [comment]
@gordon-matt - Still deciding how to fix it, if at all. I have a "fix" for it which really just reverts the change from [this ](https://github.com/OData/WebApi/commit/533213984a8f80802d31ceb1e0542b8d38be6ce8)commit. Still deciding if this is what we want to do. Until then, I'll leave the issue open.

In short, the ASP.NET folks are not crazy about the query executing during the formatting stage but that is what we intended to happen.

The best work-around I've been able to come up with is to put the DB connection in the services container as scoped, which means it will last as long as the request does. The container will dispose of the connection properly but leave it around until after the count query is executed.

**Comment by gordon-matt** [comment]
@robward-ms Thanks. As the change was made for **RESTier**, perhaps there might be a change one can make there instead of from **OData Web API**? I don't know anything about **RESTier**, but reading that issue you mentioned, it looks like there was an [alternative fix](https://github.com/OData/WebApi/issues/1#issuecomment-156894412) for it. Also, it's been a couple of years since then, so perhaps it won't be as much of an issue now. Can someone investigate the issue from **RESTier** again and see if anything can be done there so we can have the **$count** query occur in the context of `ApplyTo()`, as you mentioned would fix this issue I am seeing and that you and the ASP.NET folks would also seem  to prefer?

In the meantime, I will see if I can apply the workaround you mentioned.

**Comment by robward-ms** [comment]
@gordon-matt - We've considered the issue and decided not to change the code for this case. There are a couple reasons for it but in short, it's the WebApi design pattern to allow Linq execution to occur after the controller method to fulfill the OData request so we thing the right design is to make the disposable resource in the controller live beyond the controller method, i.e. put it in the service container.

You've pointed out a case where you were not able to work-around ther WebApi expectation but you included one where you did: ToHashSetAsync(). The call to ToHashSetAsync() forces the query to be evaluated by the underlying Linq provider and transferred to memory. This would solve any problem you were seeing with that query and a disposed resource but we believe this is not ideal; the query should be returned from the controller without ToHashSetAsync(), allowing WebApi to extend and execute the most efficient query. In order to achieve that, the disposably resource would need to be stashed into the request container.

If we were to change the $count query execution, which is possible, it would not fix the larger issue which ToHashSetAsync() worked around.

FYI, we didn't consider RESTier as part of this, i.e. avoiding churn that affects RESTier is not something we considered.

**Comment by gordon-matt** [comment]
I appreciate the proper look at this issue and the explanation of it. Thanks very much indeed.

I just wanted to note that the reason I have new DbContexts being created for each query rather than sharing one is due to 2 reasons:

1. I had various errors in the past when sharing a DbContext. It's been years now, so I don't remember the exact reasons, but I think it had something to do with data becoming stale.

2. I recall it being suggested as best practice because **"The DbContext is not thread-safe and since the DbContext caches data, it gets stale pretty soon"**, which I think was causing the issues I mentioned above. More info: https://stackoverflow.com/questions/10585478/one-dbcontext-per-web-request-why

Anyway, so instead of using the service container to share a DbContext, I decided to do something else instead. Would you be so kind as to take a look at my own workaround to this issue (using IDisposable on my ODataControllers). Basically I have opted to do the following:

```
public virtual async Task<IEnumerable<TEntity>> Get(ODataQueryOptions<TEntity> options)
{
    options.Validate(new ODataValidationSettings()
    {
        AllowedQueryOptions = AllowedQueryOptions.All
    });

    var connection = GetDisposableConnection(); // <-- See here... Creates a new connection (if it doesn't exist already) and the class inherits IDisposable and disposes the DbContext when it itself is disposed
    var query = connection.Query();
    query = ApplyMandatoryFilter(query);
    var results = options.ApplyTo(query);
    return await (results as IQueryable<TEntity>).ToHashSetAsync();
}
```

The code can be found in the same repo as before: [OData_Test](https://github.com/gordon-matt/OData_Test)

All seems to be working well for now. Do you see any issues with this?

**Comment by robward-ms** [comment]
@gordon-matt - Seems like a good compromise. I'm not sure the lifetime of the controller is the same as the request but the approach is certainly reasonable. You might also try removing ToHashSetAsync() to avoid converting the results to memory immediately.

**Comment by gordon-matt** [comment]
Thank you very much. All seems to be working well and hopefully it stays that way. I'll close this issue.
