### ISSUE TITLE
Support collection of primitive value as function parameter

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#124]
Support collection of primitive value as function parameter  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2032](http://aspnetwebstack.codeplex.com/workitem/2032)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Jun 25, 2014 at 4:32 AM
**Reported by:**	fenzhao
**Updated on:**	Aug 5, 2014 at 11:57 PM
**Updated by:**	goroth

**Comment by LianwMS** [comment]
On *2014-06-25 11:34:12 UTC*, **michaelkira** commented:

that's exactly what we need

**Comment by xuzhg** [comment]
Resolved as Duplicate #7. Thanks.
