### ISSUE TITLE
Odata 7.xx spatial IConvertible  problem

### ISSUE THREAD

**Issue by premiaware** [OData/WebApi#1247]
GeographyPoint throws Object must implement IConvertible inside the Patch Method of controller.

### Assemblies affected

OData WebApi lib 7.xxx

### Reproduce steps

After upgrade my project from OData 6.xx to OData 7.xx. in the controller Patch method:

public async Task Patch([FromODataUri] long key, Delta delta)

delta always is null when the DbGeography have valid value.

How can is resolve the problem? using OData 6.x all working well.
Reading data working well

the problem is similar to old thread 

https://github.com/OData/WebApi/issues/718

but in my project the problem is only using OData 7.

**Comment by xuzhg** [comment]
@premiaware are you using ASP.NET Core for OData?

**Comment by premiaware** [comment]
No, I using target framework .net framework 4.6.1

**Comment by xuzhg** [comment]
@premiaware sorry, I mean the Web API OData version. Is it 5.x, 6.x or 7.x?

**Comment by premiaware** [comment]
Microsoft.OData.Core 7.4.1.20214
Microsoft.OData.Edm 7.4.1.20214
System.Web.OData 6.0.0.0

**Comment by premiaware** [comment]
Today i have try to update to 
Microsoft.AspNet.OData 7.0.0-beta2
Microsoft.OData.Core 7.4.3
Microsoft.OData.Edm 7.4.3
Microsoft.Spatial 7.4.3

but the problem is the same, when using Spatial Data the Delta is null in Patch controller method.
how i can fix the problem?

**Comment by premiaware** [comment]
I have update spatial to 7.4.4 but the problem is the same, how can fix this?

**Comment by xuzhg** [comment]
Merged the PR. Please re-open it or file new issue if you have further concern. Thanks.
