### ISSUE TITLE
[feature/netcore] ODataActionParameters is not binding parameters

### ISSUE THREAD

**Issue by gordon-matt** [OData/WebApi#1249]
I am migrating some code from **MVC5** to **.NET Core** and I can see that `ODataActionParameters` is not binding parameters.

```
public virtual async Task<IEnumerable<ContentBlock>> GetByPageId(ODataQueryOptions<ContentBlock> options, ODataActionParameters parameters)
{
    // 'parameters' is empty when I debug here...
}
```

I am definitely registering the **OData Action** in the same way as before:

```
var getByPageIdAction = builder.EntityType<ContentBlock>().Collection.Action("GetByPageId");
getByPageIdAction.Parameter<Guid>("pageId");
getByPageIdAction.ReturnsCollectionFromEntitySet<ContentBlock>("ContentBlocks");
```

And I can see that the **pageId** param is definitely being sent in the request.

Anything else you need from me in order to investigate further? Thanks in advance.

**Comment by gordon-matt** [comment]
Any progress?

**Comment by Domitnator** [comment]
I am running into the same issue!

**Comment by gordon-matt** [comment]
I see a problem with that. Although adding `[FromBody]` fixes the issue with `ODataActionParameters`, that leaves me with a small problem in 2 of my actions... 1 of them being this one. If you look at my method, you will see it takes both an `ODataQueryOptions` and an `ODataActionParameters`. Now `ODataQueryOptions` is not being bound because `[FromBody]` is only applied to the `ODataActionParameters`. This was not a problem in MVC5, but obviously in .NET Core we need `[FromBody]` and it can only be applied to one parameter... so what do you suggest here? Is there something you can do to automatically bind the `ODataQueryOptions`?

**Comment by gordon-matt** [comment]
@robward-ms OK yes, I solved this by doing the following:

- Removed the `[HttpPost]` attribute from my method and

- Changed the method signature to the following:
`public virtual async Task<IEnumerable<ContentBlock>> GetByPageId([FromODataUri] Guid pageId, ODataQueryOptions<ContentBlock> options)`

- Finally: changed the registration from action to function as follows:
```
var getByPageIdFunction = builder.EntityType<ContentBlock>().Collection.Function("GetByPageId");
getByPageIdFunction.Parameter<Guid>("pageId");
getByPageIdFunction.ReturnsCollectionFromEntitySet<ContentBlock>("ContentBlockApi");
```

Seems to be working fine now. So for **OData actions**, we can only have 1 param and decorate it with `[FromBody]`. Else, use an **OData function** instead, which in my case actually makes more sense anyway.

@Domitnator Hope this helps you too...
