### ISSUE TITLE
[netcore] $inlinecount fails

### ISSUE THREAD

**Issue by NQuirmbach** [OData/WebApi#1255]
The query option for $inlinecount fails on every queryable.

`{
    "@odata.context": "http://localhost:53721/odata/$metadata#Edm.String",
    "value": "The query parameter 'Specified argument was out of the range of valid values.\r\nParameter name: $inlinecount' is not supported."
}
`

**Assemblies affected**
7.0.0-Beta

**Reproduce steps**

- Clone repository: https://github.com/NQuirmbach/odata-inlinecount
- Start application
- Navigate to http://localhost:_[port]_/odata/Person?$inlinecount=allpages

Am I missing something?

**Comment by xuzhg** [comment]
$inlinecount is in OData spec v3. In the OData sepc v4, it's $count. 7.0.0-beta is the implementation of OData spec v4. Hope it can help.

**Comment by NQuirmbach** [comment]
Oh, my bad. Should have had a look at specs :)

Thx for your help.

**Comment by xuzhg** [comment]
You are welcome. Please share us more feedbacks about the usage of OData and its implementation. Thanks!
