### ISSUE TITLE
Creating new object duplicates existing collection member

### ISSUE THREAD

**Issue by mdufrasne** [OData/WebApi#1256]
I am POSTING the following payload to create an object of my test definition class to my WebApi' odata Test Definition controller.

My payload is simple:

```
{
    "name": "test for test definition",
    "description": "some description",
    "active": true,
    "features": [{
            "id": 1,
            "name": "classic",
            "createdOn": "2017-07-11T23:29:39.987Z",
            "createdBy": "bobw",
            "description": "classic feature"
        }
    ]
}
```
This gets to the server fine - it's seemingly de-serialized correctly.

The problem I am facing is that it is creating a new Feature with the same properties as those specified instead of simply assigning the the existing one.

Interestingly, when I do an update of an existing test definition and assign different features, the payload is structured the exact same way (just a patch instead of post) - however, there it handles the members of features correctly, assigning the existing ones.

**Comment by xuzhg** [comment]
Would you please share more information? for example, which version do you use? and your edm model. Those can help us to investigate.

**Comment by xuzhg** [comment]
Similar issue with : https://github.com/OData/WebApi/issues/1299

**Comment by biaol-odata** [comment]
@mdufrasne Isn't POST supposed to create a top level entity object (including a new Feature nested object)? I believe the method handling this POST request in your controller is handling it correctly.
What you have observed on PATCH about in-place update (vs creating new object) is expected as well.

Looks like it is all related to controller method, not WebApi/OData. And your controller is doing the right thing. Therefore I believe this one can be closed. Please re-open or submit new issue if needed.
