### ISSUE TITLE
[feature/netcore] Ability to modify query after applying queryOptions

### ISSUE THREAD

**Issue by techniq** [OData/WebApi#1257]
### Assemblies affected

- `7.0.0-Nightly201803011314`

### Reproduce steps

In OData 6.x, it used to be possible to cast the result of `queryOptions.ApplyTo(...)` as an `IQueryable<T>` where `T` is the type of the `DbContext.Set<T>()` and make further changes.

For example, I would use this to add additional fields, apply additional filtering, etc before returning a result.  A use case would be to provide an `Export` capability, such as this trivial example.

```c#
[HttpGet]
public IActionResult Export(ODataQueryOptions<Employee> queryOptions)
{
    var query = queryOptions.ApplyTo(DbContext.Set<Employee>()) as IQueryable<Employee>;
    var exportQuery = query.Select(e => new EmployeeExport
    {
        Name = e.Name,
        // ...
    });
    return Ok(exportQuery);
}
```

### Expected result

Ability to continue to modify query after calling `queryOptions.ApplyTo(...)`

### Actual result

If the odata query contains anything except for `$filter` (for example, `$top`, `$select`, or `$expand`), the result is not castable to `IQueryable<T>` (returns null)

**Comment by techniq** [comment]
@robward-ms Any thoughts on this one?

I'm currently using `beta-2`(as I can no longer install recent [nightlies](https://github.com/OData/WebApi/issues/1321)).  There are some [E2E](https://github.com/OData/WebApi/blob/feature/netcore/test/E2ETest/Microsoft.Test.E2E.AspNet.OData/QueryComposition/ODataQueryOptionsTests.cs#L59-L75) tests that appear to cast to `IQueryable<T>` but they are not using `$select` or `$expand`.

This is currently a big blocker for my project and was hoping to find some solution (and is a regression from 6.x).

**Comment by robward-ms** [comment]
@techniq - What is the backend you are using? I think it's EFCore but I want to verify.

**Comment by techniq** [comment]
Correct, EFCore (SQL Server)

**Comment by techniq** [comment]
@robward-ms any thoughts on this one?

**Comment by robward-ms** [comment]
@techniq - My thoughts are the query expression building in OData does not play well with EFCore in general :).

I put some [test ](https://github.com/robward-ms/WebApi/blob/d153c8807b9bcf2c9756a53d916eafbae78325a1/test/E2ETest/Microsoft.Test.E2E.AspNet.OData/QueryComposition/CompoundQueryTests.cs#L55-L84) together for this in a [personal branch](https://github.com/robward-ms/WebApi/tree/NetCore-1257). All tests pass on EF6.

Can you take a look and see if you think I got the repo right? If so, I think this is likely an EFCore-specific issue.

**Comment by techniq** [comment]
@robward-ms From what I can tell, this test doesn't appear to test the issue (unless I'm looking at the wrong one or not following)

![image](https://user-images.githubusercontent.com/177476/38948003-600ce592-430c-11e8-8e56-96e85f1ffcd6.png)


An example of the problem.  If I take in `queryOptions` and apply it directly...
```c#
[HttpGet]
public IActionResult Export(ODataQueryOptions<Employee> queryOptions)
{
    var query = queryOptions.ApplyTo(DbContext.Set<Employee>()) as IQueryable<Employee>;
    // query will be null here if `queryOptions` contains `$top`, `$select`, or `$expand`
    var exportQuery = query.Select(e => new EmployeeExport
    {
        Name = e.Name,
        // ...
    });
    return Ok(exportQuery);
}
```
`query` will be null if `queryOptions` contains `$top`, `$select`, or `$expand` as it is no longer castable to `IQueryable<Employee>`.  You can cast it to `IQueryable<IEdmStructuredObject>`, but then you no longer have the underlying entity type to in the additional query calls
```c#
query.Select(e => /* no longer Employee */)
```

**Comment by techniq** [comment]
@robward-ms I just looked at the test closer and missed how the underlying `/compoundquery/Transform` route was setup

![image](https://user-images.githubusercontent.com/177476/38948422-93844d56-430d-11e8-85e3-88f602ae0b5a.png)

This should catch it as I'm 90% sure the problem was present with `$top`.  It would be nice if another `InlineData` or two were added that included `$select` and `$expand` cases.

Does this fail for you on EFCore?

**Comment by techniq** [comment]
@robward-ms thanks for all the hard work 

I'm somewhat expecting it to be an issue on the OData side (instead of EFCore) since the type coming back is `IEdmStructuredObject` but I could be wrong.

**Comment by dozer75** [comment]
@techniq What is your query string? I have a similar issue that it creates an `IQueryable` of `IEdmStructuredObject` and with that a very ineffective expression to handle for SQL server, I have not investigated this enough yet, but I have a suspicion that my issue relates to filtering navigational entities using `$expand`, I am thinking about reporting this issue, but just want to see if it is similar to yours. I get this using EF6.

**Comment by FordSoft** [comment]
A similar case (but .net 46). But at the same time I get a full result without formatting ODATA (e.g. "@odata.metadata", "value:". Only array of JSON format), apparently the serializer does not understand how to resolve just IQueryable.  

How to get the formatting with (e.g. "@odata.metadata", "value:") used for IQueryable<SomeType> ?

**Comment by NetTecture** [comment]
TOTALLY not closed and a showstopper.

Somehow this works for me when I materialize the whole result.

i.e. if I have this:

            var data = query.ToList();
            return data.AsQueryable();

it works nicely, but if I use this:

            var q2 = options.ApplyTo(query);
            return ((IQueryable<D>) q2);

I get 'Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Microsoft.AspNet.OData.Query.Expressions.SelectExpandBinder+SelectAllAndExpand`1[Api.Odata.Account]]' to type 'System.Linq.IQueryable`1[Api.Odata.Account]'.'

There is something missing and none seems to actually want to fix it. Amazing. How hard is it to put up a navigation property and then expand with it? In my case the URL is /Account?$expand=Documents

This is one of he main showstoppers - for small data my workaround works perfectly, but once you pull in larger data... bad. Really bad.

**Comment by dozer75** [comment]
@NetTecture 

What you are experiencing is not a bug, it is by design, if you see in your exception the result of ApplyTo encapsulates your `Api.Odata.Account` into a generic `SelectAndExpand` object, and you can't just cast this. The reason why `ApplyTo` does this is because of the internal handling after OData has called your get action which needs this `SelectAndExpand` for further handling to serialize the data into a OData JSON result. 

Due to the limitation of your code example it's difficult to see why you need to cast it to an `IQueryable` in this situation. 

If you just do this because your action are returning an `IQueryable`, let it return an `IActionResult` instead and let Odata handle the rest (Let your action return an `IActionResult` type and return your data as `Ok(q2)`) and it will probably work for you. 

If you need an `IQueryable` because of something else, please post why and maybe someone can give you an another approach (e.g. if you want to do additional filter, do that on query before calling `ApplyTo`).


@techniq 

After seeing this last post I realized I never answered you, but your problem is the same. Which isn't quite the same I experienced there, I let it go because I solved it in another way.

**Comment by NetTecture** [comment]
@dozer75  You know, returning IActionResult NEARLY worked. Now I get N+x round trips as every relationship is a separate request.

Funny.

The following code:

            IEnumerable<string> includes = EmptyIncludes;
            if (options != null) {
                includes = GetIncludesFromExpandClause(options.SelectExpand);
            }

            var query = Repository.Set<E>()
                .ProjectTo<D>(new Dictionary<string, object>(), includes.ToArray())
            ;

            var data = query.ToList();
            return Ok(query);

executes the query first into data, then returns it. I get the proper results, but slow. Oh, and data.... that is ONE sql statement. And then, the next execution - goes on and on with individual statements.

Yes, I already "include" them. I actually parse the ODataQueryOptions to extract every single expand to get them.

**Comment by techniq** [comment]
@xuzhg @biaol-odata any plans to enable this use case again with ASP.NET Core?

**Comment by GeorgePetri** [comment]
Can you guys please take a look at it?
