### ISSUE TITLE
PATCH of nested complex properties not per OData spec

### ISSUE THREAD

**Issue by catalinis** [OData/WebApi#1263]
*Short summary (3-5 sentences) describing the issue.*

Per OData Spec:
11.4.3 Update an Entity
Services SHOULD support PATCH as the preferred means of updating an entity. PATCH provides more resiliency between clients and services by directly modifying only those values specified by the client.
The semantics of PATCH, as defined in [RFC5789], is to merge the content in the request payload with the [entity’s] current state, applying the update only to those components specified in the request body. Collection properties and primitive properties provided in the payload corresponding to updatable properties MUST replace the value of the corresponding property in the entity or complex type. Missing properties of the containing entity or complex property, including dynamic properties, MUST NOT be directly altered unless as a side effect of changes resulting from the provided properties.

What we are observing is that PATCH for complex properties does not follow the spec above.

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData WebApi lib 6.1.0

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*
Assume the Contact schema:
<EntityType Name="Contact" ">
      <Key>
            <PropertyRef Name="Id"/>
      </Key>
      <Property Name="Id" Type="Edm.String"/>
      <Property Name="Name" Type="Edm.String"/>
      <Property Name="HomeAddress" Type=" PhysicalAddress"/>
</EntityType>
< ComplexType Name="PhysicalAddress">
      <Property Name="Street" Type="Edm.String"/>
      <Property Name="City" Type="Edm.String"/>
</ComplexType>

and an entity instance:
{
                Id: “1”,
                Name: “Joe”
                HomeAddress:{
                                Street : “Main street”,
                                City : “Some City”
                }
}
and we want to update the Name and City using
PATCH /Contacts(‘1’)
{
                Name: “Joey”,
                HomeAddress:{
                                City : “Some other city”
                }
}

### Expected result

*What would happen if there wasn't a bug.*

Contacts(1) would be:
{
                Id: “1”,
                Name: “Joey”
                HomeAddress:{
                                Street : “Main street”,
                                City : “Some other city”
                }
}

### Actual result

*What is actually happening.*
Contacts(1) would be:
{
                Id: “1”,
                Name: “Joey”
                HomeAddress:{
                                Street : null,
                                City : “Some other city”
                }
}

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by bdebaere** [comment]
@catalinis Can you share how you managed to patch a nested complex entity please? What does your controller method look like?

**Comment by biaol-odata** [comment]
@catalinis Do you have any code that you might be able to share for repo? That way we can understand the exact scenario.

**Comment by CatalinStafieTest** [comment]
It looks like we agree, the current code does not implement the section 11.4.3 of the spec.
What is the plan for a fix?

**Comment by biaol-odata** [comment]
Adding one related issue: https://github.com/OData/WebApi/issues/135

**Comment by biaol-odata** [comment]
Merged. This issue can be closed now.

**Comment by ricksearcy** [comment]
What is the status of this? I am still seeing the behavior and not able to use a PATCH for our complex types in 7.1.0.
