### ISSUE TITLE
OData expand filter

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#127]
The feature in the OData 4 spec where you can filter expanded properties is
missing. Will this be added in?  
  
Example 90: all categories and for each category all related products with a
discontinued date equal to null  
http://host/service/Categories?$expand=Products($filter=DiscontinuedDate eq
null)  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2046](http://aspnetwebstack.codeplex.com/workitem/2046)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jul 4, 2014 at 11:45 AM
**Reported by:**	jrote1
**Updated on:**	Wed at 3:51 AM
**Updated by:**	hmcafee

**Comment by LianwMS** [comment]
On *2014-07-11 17:03:56 UTC*, **jrote1** commented:

So this will not be in OData for mvc5 as vnext is a very big migration

**Comment by LianwMS** [comment]
On *2014-07-13 09:37:34 UTC*, **azhou** commented:

This issue is raised at 
https://github.com/aspnet/Mvc/issues/783#issuecomment-48811756. 

It won't be in next Web API OData Release in August (5.3 or 2.3 or another version number). We will see how it can be fit into a Release after August.

**Comment by LianwMS** [comment]
On *2014-09-23 21:52:51 UTC*, **jrote1** commented:

Any update on this feature?

**Comment by LianwMS** [comment]
On *2015-01-07 11:51:10 UTC*, **hmcafee** commented:

Just ran into this - kind of a bummer!

**Comment by dotnetwise** [comment]
so any predictions one year later?

**Comment by codesocket** [comment]
We have a an upgrade planned from odata v3 to v4. However without this support, we cannot move forward. Any update?

**Comment by congysu** [comment]
Checked in 97b1ba0eaeb551fb21c5718245bbcc6f28cad886

**Comment by dotnetwise** [comment]
So how can we use it? Is there any docs?

In what version will it be released?

**Comment by congysu** [comment]
@dotnetwise A doc - GitHub page: [Nested $filter in $expand](http://odata.github.io/WebApi/#filter-in-expand).  It is included in [OData v4 Web API nuget package]( https://www.nuget.org/packages/Microsoft.AspNet.OData/) 5.5-beta and afterwards.
