### ISSUE TITLE
Improve the error message when failing to serialize null collection values

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#128]
Currently when a user returns an object that includes a collection property
and that collection property is null, we throw a 500 error (which is the right
kind of error, as it's a programming error, not a client error) but we don't
include the name of the null property.  
  
Improve the error message by including the name of the property if possible.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2049](http://aspnetwebstack.codeplex.com/workitem/2049)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Jul 7, 2014 at 7:00 PM
**Reported by:**	jacalvar
**Updated on:**	Aug 6, 2014 at 3:47 AM
**Updated by:**	xuzhg

**Comment by LianwMS** [comment]
On *2014-07-10 05:27:09 UTC*, **yishaigalatzer** commented:

This was a customer input

**Comment by LianwMS** [comment]
On *2014-08-06 10:47:45 UTC*, **xuzhg** commented:

It is not easily to get the property name without changing the signature of CreateODataValue(...) function. So, Postpone it to vNext.

**Comment by taspeotis** [comment]
> (which is the right kind of error, as it's a programming error, not a client error)

I have an entity with an `IEnumerable<byte>` full of binary data. It's not a collection in the navigation property sense, it's either `null` or `byte[16]`. I don't know why a `null` value here is a programming error, that's the value that Entity Framework puts there.

**Comment by xuzhg** [comment]
@taspeotis Form OData spec, if a property that specifies a collection, the property MUST always exist, but the collection MAY be empty. 

Moreover, the nullable attribute of the collection property applies to the members of the collection, not the collection itself, because the collection property MUST always exist.

So, from developer aspect, the collection property must be set as empty collection not null if it's actual null.

**Comment by taspeotis** [comment]
For what it's worth: if I change the property type to `byte[]` (not `IEnumerable<byte>`) then the `$metadata` changes the type to `Edm.Binary` and it serialises `null` fine. So now in C# I have a "collection" that's `null`.

**Comment by xuzhg** [comment]
@taspeotis  

In Web API OData, `byte[]` and `IEnumerable<byte>` are treated different. Even that It looks a little bit strange.

You can find the type mapping for `byte[]` [here](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Formatter/EdmLibHelpers.cs#L57)

So, `byte[]` is treated as Edm.Binary primitive type, while `IEnumerable<byte>` is treated as collection of Edm.Byte. There are totally different.

Owing that Edm.Binary is a primitive type, it can be nullable or not bases on its nullable attribute. As a result, you can serializes as `null` for `byte[]` if it's nullable. 

Owing that `IEnumerable<byte>` is a collection of Edm.Byte. it should follow up the collection strategy.

Thanks.

**Comment by xuzhg** [comment]
Let me have an example, if I use the following model to build the Edm Model:
```C#
public class Customer
{
     public int Id { get; set; }

     public byte[] Content { get; set; }

     public IEnumerable<byte> Bytes { get; set; }

     public ICollection<byte?> Contents { get; set; }
}
```

I can get the following type mapping. (Please pay attention to the different sample values for different properties)

|Property	|CLR type	|Edm Type|	Type kind|	Nullable|	Sample Value|
--------------|-----------------------|------------|-----------------|----------------------|----------------------|
Content|	byte[]	|Edm.Binary|	Primitive type|	true|	"Content":"AQs="  or "Content":null
Bytes	|IEnumerable<byte>|	Collection(Edm.Byte)|	Collection|	false|	"Bytes":[ 1,2,3,4,5]
Contents|	ICollection<byte?>	|Collection(Edm.Byte)	|Collection|	true|	"Contents":[1,null,3]

**Comment by taspeotis** [comment]
I appreciate the persistence. I am just surprised `IEnumerable<byte>` is treated as a collection rather than `Edm.Binary`. To me collections have individual items that can be added/edited/removed (analogous to what `ICollection` can do) but I see from [here](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398347) that OData doesn't permit updating items within a collection so it's a meaningless distinction:

> Since collection members have no individual identity, PATCH is not supported for collection properties.

**Comment by VikingsFan** [comment]
@taspeotis can you try 5.7rc, we provide two configuration for null collection serialize: 

    config.SetDoNotSerializeNullCollections(true)
    config.SetSerializeNullCollectionsAsEmpty(true)

**Comment by shaneconnolly** [comment]
@VikingsFan  can you give me an example of setting the config in this way as I haven't been able to figure out how to apply this. What exactly is the config object in this scenario?

**Comment by shaneconnolly** [comment]
Disregard previous question, I was using OData V3 (System.Web.Http.OData) instead of V4 (System.Web.OData)
