### ISSUE TITLE
What happened to EntitySetPathSegment in the current version of Odata?

### ISSUE THREAD

**Issue by rbmanian75** [OData/WebApi#1282]
We are using EntitySetPathSegment  to set the location of the response. But with this version of odata we are not able to locate EntitySetPathSegment  type. Is there any alternative for this available?

Thanks

**Comment by xuzhg** [comment]
Sorry about that, however, the `EntitySetPathSegment` is removed in the 6.x version. See the detail information from: http://odata.github.io/WebApi/#13-05-PathSegmentChange

So, you can use `EntitySetSegment` class from the OData.Core lib.

**Comment by rbmanian75** [comment]
However entitysetsegment missing the constructor
`public EntitySetPathSegment(
	string entitySetName
)`
so we cant use it. it would be nice we entitysetsegment accepts entitysetname as a string.

**Comment by xuzhg** [comment]
Yes. However, It's easy to retrieve the `IEdmEntitySet` object from Edm Model using the `EntitySetName`, then use the `IEdmEntitySet` object to create `EntitySetSegment`.
Thanks for your feedback. Please let us know any help you want.

**Comment by rbmanian75** [comment]
Thank you for the reply. However with this version it is not possible to get the edmmodel from Request.ODataProperties()...Is there any alternate way we can get the edmmodel from Request properties?

**Comment by xuzhg** [comment]
I think just to call `Request.GetModel()`

**Comment by DaleyKD** [comment]
This is now an issue when trying to use https://github.com/OData/WebApi/issues/31 for MVC. How are we to get the Model from an MVC Request?

**Comment by xuzhg** [comment]
@DaleyKD What do you mean? `Request.GetModel()` can not work for you?

**Comment by DaleyKD** [comment]
@xuzhg  - I can't find that Extension Method off of System.Web.HttpRequestBase, System.Web.Routing.RequestContext, or System.Web.HttpContextBase.

I'm trying to get the route to an OData Controller in a Razor cshtml page.

This is an MVC (NOT Core) 5.2.7 web app with Web API 5.2.2 and Microsoft.AspNet.OData 7.1.0.

**Comment by jonjanelle** [comment]
@DaleyKD 
It should be in Microsoft.AspNet.OData.Extensions
