### ISSUE TITLE
I am looking for the branch where Microsoft.AspNet.OData 6.0 nuget package is built from. I can only find 5.9 and 6.1 so far.

### ISSUE THREAD

**Issue by lixindou** [OData/WebApi#1284]
I am looking for the branch where Microsoft.AspNet.OData 6.0 nuget package is built from. I can only find 5.9 and 6.1 so far. I need to debug to the source code to find why ApplyQuery cause database N+1 query issue.
Nuget package:
Microsoft.AspNet.OData 6.0 -> System.Web.OData 6.0

**Comment by robward-ms** [comment]
In general, [master](https://github.com/OData/WebApi/tree/master)
Specific versions of the code are tagged, you want the [6.0.0 tag](https://github.com/OData/WebApi/tree/v6.0.0)
