### ISSUE TITLE
Error when using multiple calls to MapODataServiceRoute

### ISSUE THREAD

**Issue by smasherprog** [OData/WebApi#1286]
I have multiple odata services that I want to keep seperate on the same website because they are totally unrelated things. When navigating to one of the odata endpoints, an error is generated

### Assemblies affected

net core beta 2

### Reproduce steps

add multiple calls to MapODataServiceRoute with different names, prefix, ect  in  the UseMvc service 

### Expected result
I expect to be able to have multiple odata services on the same website

### Actual result

Obviously, the names below are my controller and action names

InvalidOperationException: The path template 'AdminA102_1' on the action 'CreateEvent' in controller 'AdminA102_1' is not a valid OData path template. Resource not found for the segment 'AdminA102_1'.
Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.GetODataPathTemplate(string prefix, string pathTemplate, IServiceProvider requestContainer, string controllerName, string actionName)

### Additional detail

It looks like the odata services overlap eachother because in the above error, the controller/path   'AdminA102_1' is in the OTHER odata service.  One works, the other does not

**Comment by CrazyBaran** [comment]
I get this case too. OData wrong route into bad controller, so if in one controller we have rich Product entity and in second route we have some poor Product entity, it get error cause it try parse poor model into rich controller.

**Comment by robward-ms** [comment]
Yep, sounds like a bug. FYI, the cause will have to do with using ODataRoute attributes. 

I think what is happening is that there are two instances of AttributeRoutingConvention each with visibility to all controllers but only one model. When processing the ODataRoute attributes, the parser fails to find the entities listed in ODataRoute in the EdmModel because it's looking at the controller for another route.

Not saying it's not a bug, but without the ODataRoute attributes, you won't see it, but that may not be possible given your desired urls.

**Comment by robward-ms** [comment]
AttributeRoutingConvention's AttributeMappings property uses the IActionDescriptorCollectionProvider to get call ControllerActionDescriptor in the server, which may not be limited to a certain route. As a result, it may find actions for which the referenced entities are not in the model since they may reference another model. However, the model is route-specific.

One option is to ignore errors, maybe log them, but then discovering why an ODataRouteAttribute does not work get's a bit tougher.

**Comment by CrazyBaran** [comment]
@robward-ms So what is a walkaround? Or there isn't?

**Comment by robward-ms** [comment]
No work-around at this point except to use fewer ODataRoute attributes.

**Comment by CrazyBaran** [comment]
@robward-ms I made additional test. I remove all of ODataRoute attributes from my controllers and use only name convention and still it looks like it is issue with multiple calls of OData Route. I get route only to first of prefix.

**Comment by robward-ms** [comment]
@CrazyBaran - The controllers are not route-specific so there is now way to associated a set of controllers with a particular route. I think this is true for AspNetCore in general.

I added a "RouteName" parameter to the ODataRouteAttribute to allow you to specify which route you want to apply the attribute to. If you want to support multiple routes, use multiple ODataRouteAttribute's one with each route or leave RouteName off, in which case it will be used in all routes.

Can you try the nightly (sometime after today) to see if the fix works for your scenario?

**Comment by CrazyBaran** [comment]
@robward-ms I check my case today with new nightly and it looks like it made a work for me, thank you. 
I have also additional question, in case of this change, ODataRoutePrefix shouldnt have also this parameter?

**Comment by robward-ms** [comment]
@CrazyBaran - I didn't think it was necessary as the prefix is always applied to an ODataRouteAttribute anyway.

**Comment by jahknow** [comment]
@CrazyBaran I am using .net core 2.2 and I am having the same problem. I have two controllers with the same name and the same Get method, but they are in 2 separate namespaces and they both return two separate datatype

```C#
namespace A
{
    public class OdataPatientsController : ODataController
    {
        [ODataRoute("patients", RouteName = "routeA")]
        [EnableQuery(EnableCorrelatedSubqueryBuffering = true)]
        public ActionResult<IEnumerable<Patient>> GetPatients()
        {
            var result = Gets list of patient from repository here;

            return Ok(result);
        }
    }
}
```

```C#
namespace B
{
    public class OdataPatientsController : ODataController
    {
        [ODataRoute("patients", RouteName = "routeB")]
        [EnableQuery(EnableCorrelatedSubqueryBuffering = true)]
        public ActionResult<IEnumerable<PatientWithTerminalDesease>> GetPatients()
        {
            var result = Gets list of patient with terminal disease from repository here;

            return Ok(result);
        }
    }
}
```
inside my startup.cs file
```C#
 app.UseMvc(routeBuilder => {

                routeBuilder.MapODataServiceRoute("routeA", "odata/api-patient", GetDefaultEdmModel(app.ApplicationServices));
            });
```

```C#
private static IEdmModel GetDefaultEdmModel(IServiceProvider serviceProvider)
        {
            var builder = new ODataConventionModelBuilder(serviceProvider);

            builder.EntitySet<Models.Patient>("patients");

            builder.EnableLowerCamelCase();

            return builder.GetEdmModel();
        }
```

Whenever i call **odata/api-patient/patients** it always navigates to **GetPatients** method in **B.OdataPatientsController .GetPatients()** but as you can see i did not even define a route that would cause this method to get invoked. what am i doing wrong?

I need some urgent help, please.
