### ISSUE TITLE
Make ODataPathSegmentTranslator public so that developers can write their own odata path handler.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#129]
Now if a developer write his own odata path handler, he has to duplicate the
ODataPathSegmentTranslator to translate the ODL odata path to webapi odata
path as it is an internal class.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2052](http://aspnetwebstack.codeplex.com/workitem/2052)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Jul 8, 2014 at 3:18 AM
**Reported by:**	jinfutan
**Updated on:**	Sep 30, 2014 at 2:55 AM
**Updated by:**	joeloughton

**Comment by congysu** [comment]
Key as segment is a scenario for this issue.

**Comment by xuzhg** [comment]
Changed. Thanks.
