### ISSUE TITLE
batch request return  201 code, on creating entities but the response is not v4 response on $batch protocol

### ISSUE THREAD

**Issue by jlteranr** [OData/WebApi#1290]
Response is missing on sending  when sending batch request creating entities. status code 201.Created is right but not the body section for the entity created. Http Post alone is doing right.

### Assemblies affected
Beta 2 7.0.0

### Reproduce steps
1. Send and http post request $batch with the  create request entities.

### Expected result

Response 201 Created and response body with a serialize JSON object representing the entity created.

### Actual result
201.Created and NO Response body

### Initial  Request

POST http://localhost:44393/PRSLOdata/$batch HTTP/1.1
Accept: multipart/mixed
Accept-Encoding: gzip, deflate, br
Accept-Language: en
Cache-Control: no-cache
Connection: keep-alive
Content-Type: multipart/mixed; boundary=batch_id-1521217824534-20
Host: localhost:44393
MIME-Version: 1.0
OData-MaxVersion: 4.0
OData-Version: 4.0
Origin: http://localhost:44393
Pragma: no-cache
Referer: http://localhost:44393/webapp/index.html
Content-Length: 501

--batch_id-1521217824534-20
Content-Type:application/http
Content-Transfer-Encoding:binary

POST SiteCatalog HTTP/1.1
Accept:application/json;odata.metadata=minimal;IEEE754Compatible=true
Accept-Language:en
Content-Type:application/json;odata.metadata=minimal;charset=UTF-8;IEEE754Compatible=true

{"Id":"sMRAad","Description":" CENTRAL SITE ","Blocked":"SI","EntityId":"eMRA","DateCreated":"2018-03-16T16:30:05.276Z","DateUpdated":"2018-03-16T16:30:05.276Z"}
--batch_id-1521217824534-20--

### Response result

HTTP/1.1 200 OK
Date: Tue, 20 Mar 2018 22:49:44 GMT
Content-Type: multipart/mixed;boundary=batchresponse_e4297286-1a83-4583-8076-a978e2d5fd67
Server: Kestrel
Transfer-Encoding: chunked
OData-Version: 4.0

146
--batchresponse_e4297286-1a83-4583-8076-a978e2d5fd67
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 201 Created
Location: http://localhost:44393/PRSLOdata/SiteCatalog('sMRAad')
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
OData-Version: 4.0

3a

--batchresponse_e4297286-1a83-4583-8076-a978e2d5fd67--

0

### Response must be include on batch segment

JSON formated according OData v4.protocol.

HTTP/1.1 201 Created
Date: Tue, 20 Mar 2018 23:14:19 GMT
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked
Location: http://localhost:44393/PRSLOdata/SiteCatalog('sMRAtf')
OData-Version: 4.0

e9
{"@odata.context":"http://localhost:44393/PRSLOdata/$metadata#SiteCatalog/$entity","Id":"sMRAtf","EntityId":"eMRA","Description":"TC","DateCreated":"2018-03-20T11:14:19-06:00","DateUpdated":"2018-03-20T11:14:19-06:00","Blocked":"SI"}
0

**Comment by jacqueskang** [comment]
I think this is fixed by #1304

**Comment by jlteranr** [comment]
Thanks Jacques
