### ISSUE TITLE
top, orderby asc desc default in .net core

### ISSUE THREAD

**Issue by andrew-laughlin** [OData/WebApi#1296]
Apologies if this has been answered somewhere, and I've just missed it. 

I'm using the latest beta 2 .net core release. When running a top query, an `order by <key> asc` clause is appending to the query. This makes sense in terms of stable ordering. In my case the key field is a time stamp and I'd like to default ordering to descending (e.g. `order by <key> desc`. Is there a way to accomplish this?

**Comment by granthoff1107** [comment]
You can manually override the order by nodes.  I haven't tested this in the .Net Core Version
Here is the gyst of how to https://stackoverflow.com/a/23453383/1938988

**Comment by robward-ms** [comment]
@andrew-laughlin - Did this resolve your issue?

**Comment by andrew-laughlin** [comment]
@robward-ms yes, thanks.
