### ISSUE TITLE
How Do I Enable Filtering For a specific entity set

### ISSUE THREAD

**Issue by granthoff1107** [OData/WebApi#1299]
I'm trying to only enable certain features of odata depending on the Entity Set.  My startup looks like so:

    services.AddOData();
    
    //...
    
    app.UseMvc(routeBuilder =>
    {
        //If I enable this it enables filtering etc for all of my entities
        //routeBuilder.Count().Filter().OrderBy().Expand().Select().MaxTop(null);
        routeBuilder.MapODataServiceRoute("odata", null, GetModel());
        routeBuilder.EnableDependencyInjection();
    });

    public static IEdmModel GetModel()
    {
        var builder = new ODataConventionModelBuilder();
        var skillSet = builder.EntitySet<Skill>(nameof(Skill));
        //When I try to enable things this way nothing is enabled on my controller
        skillSet.EntityType.Count().Filter().OrderBy().Expand().Select();
        builder.Namespace = "ODataTest.Models";
        builder.ContainerName = "DefaultContainer";

        return builder.GetEdmModel();
    }

When I globally enable odata everything works fine, but I cannot expose all of my entities

    routeBuilder.Count().Filter().OrderBy().Expand().Select().MaxTop(null);

but when, I try to enable odata for a specific entity set my I get an error when I attempt to filter

    skillSet.EntityType.Count().Filter().OrderBy().Expand().Select();

>The query specified in the URI is not valid. The property 'Name' cannot be used in the $filter query option.

For the sake of completeness here is my controller:

    [HttpGet]
    [EnableQuery]
    public async Task<Skill[]> GetFilteredODataList(ODataQueryOptions<Skill> q)
    {
        var skillsQuery = this._context.Skills.AsQueryable();
        if (q?.Filter != null)
        {
            skillsQuery = q.Filter.ApplyTo(skillsQuery, new ODataQuerySettings()) as IQueryable<Skill>;
        }

        return await skillsQuery.ToArrayAsync();
    }

**Comment by robward-ms** [comment]
@granthoff1107 - Have you looked at the [E2E tests](https://github.com/OData/WebApi/tree/feature/netcore/test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ModelBoundQuerySettings) for model bound query settings?

Als,o  [EnableQueryAttribute](https://github.com/OData/WebApi/blob/feature/netcore/src/Microsoft.AspNet.OData.Shared/EnableQueryAttribute.cs) has many options to limit the queries that can be applied to a given entity/controller.

There is also an example in the [docs](http://odata.github.io/WebApi/#04-16-ignore-query-option) for using a custom attribute.

**Comment by xuzhg** [comment]
Close it and please re-open it or file new issue if you have further concern. Thanks.
