### ISSUE TITLE
Queries to blocked resources still execute on the DB

### ISSUE THREAD

**Issue by granthoff1107** [OData/WebApi#1302]
I'm running the Beta 2 of OData on .Net Core.  OData is consuming and wasting resources on queries that should be blocked

    services.AddOData();   
    //...
    
    app.UseMvc(routeBuilder =>
    {
        routeBuilder.MapODataServiceRoute("odata", null, GetModel());
        routeBuilder.EnableDependencyInjection();
    });

    public static IEdmModel GetModel()
    {
        var builder = new ODataConventionModelBuilder();
        var skillSet = builder.EntitySet<Skill>(nameof(Skill));
        builder.Namespace = "ODataTest.Models";
        builder.ContainerName = "DefaultContainer";

        return builder.GetEdmModel();
    }

As you can See I've intentionally ommited permission to any function of odata (Filter, Count, Expand, Select Etc) 

    [HttpGet]
    [EnableQuery]
    public async Task<Skill[]> GetFilteredODataList(ODataQueryOptions<Skill> q)
    {
        var skillsQuery = this._context.Skills.AsQueryable();
        if (q?.Filter != null)
        {
            skillsQuery = q.Filter.ApplyTo(skillsQuery, new ODataQuerySettings()) as IQueryable<Skill>;
        }

        return await skillsQuery.ToArrayAsync();
    }

When I Navigate to my controller I can see that my controller executes and retrieves the data from the DBContext, Despite Being return with the error 

>The query specified in the URI is not valid. The property 'Name' cannot be used in the $filter query option.

I'm not sure if this is expected behavior, but I would expect a 403 to be thrown instead

**Comment by robward-ms** [comment]
@granthoff1107 - You can call [Validate](https://github.com/OData/WebApi/blob/e5034f9c2a99b343eabe710d25573b54d72f495c/src/Microsoft.AspNet.OData.Shared/Query/ODataQueryOptions.cs#L503-L514) on the query options first to avoid the overhead.

**Comment by granthoff1107** [comment]
Thanks I think that solves this issue

**Comment by robward-ms** [comment]
@granthoff1107 - I don't think I understand the question. If you use [EnableQuery], validation will occur automatically. If you want to use ODataQueryOptions<Skill>, you would need to call Validate yourself.

**Comment by granthoff1107** [comment]
@robward-ms.  

The validation method takes in an odataquerysettings.  If I declare my settings globally in the routebuilder I would like to be able to reuse them when I validate manually.

I was just wondering if there is a built in way to get them, or if I have to put them in a container and inject them into my controller?

**Comment by robward-ms** [comment]
@granthoff1107 - There are [default query options we attach to the route builder](https://github.com/OData/WebApi/blob/f9d10191efcb13fee7f995fa4ec2188860d8c6fd/src/Microsoft.AspNetCore.OData/Extensions/ODataRouteBuilderExtensions.cs#L29-L79), is that what you are looking for?

**Comment by granthoff1107** [comment]
Yes, how can I grab them from the controller?

**Comment by xuzhg** [comment]
Close it and please re-open or file new issue if you have further concern. Thanks.
