### ISSUE TITLE
Batch response does not contain individual requests' response bodies

### ISSUE THREAD

**Issue by jacqueskang** [OData/WebApi#1304]
I'm trying to create an ASP.NET Core OData API supporting batching and I'm using Microsoft.AspNetCore.OData v7.0.0-beta2

I noticed that batch response doesn't contain sub-responses' body.
After investigation it seems that in ODataBatchResponseItem.WriteMessageAsync()
[(ODataBatchResponseItem.cs)](https://github.com/OData/WebApi/blob/feature/netcore/src/Microsoft.AspNetCore.OData/Batch/ODataBatchResponseItem.cs)
There is:
```
        using (Stream stream = batchResponse.GetStream())
        {
            context.RequestAborted.ThrowIfCancellationRequested();
            await context.Response.Body.CopyToAsync(stream);
        }
```
The problem is that when CopyToAsync() got executed, the position of context.Response.Body (whose type is System.IO.MemoryStream) is actually at the end of the stream. So nothing get copied in batch stream.

If I add the following line before calling CopyToAsync(), the issue is fixed
```
context.Response.Body.Seek(0, SeekOrigin.Begin);
```

### Assemblies affected

Microsoft.AspNetCore.OData.dll 7.0.0

### Reproduce steps

1. Create an empty ASP.NET Core application, add an OData controller
```
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class ProductController : ODataController
    {
        [HttpGet]
        [EnableQuery]
        public IEnumerable<Product> Get()
        {
            return new[] {
                new Product
                {
                    Id = 0,
                    Name = "PC"
                },
                new Product
                {
                    Id = 1,
                    Name = "Bread"
                }
            };
        }
    }
```

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOData();
            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseODataBatching();
            app.UseMvc(routeBuilder =>
            {
                var builder = new ODataConventionModelBuilder();
                builder.EntitySet<Product>(nameof(Product));
                IEdmModel model = builder.GetEdmModel();
                routeBuilder.MapODataServiceRoute("ODataRoute", "odata", model, new DefaultODataBatchHandler());
                routeBuilder.EnableDependencyInjection();
            });
        }
```

Then send a batch request:
```
POST http://localhost:11546/odata/$batch HTTP/1.1
Content-Type: multipart/mixed; boundary=batch_1237acc2-bef9-435f-a0ca-3c8ba817079e

--batch_1237acc2-bef9-435f-a0ca-3c8ba817079e
Content-Type: application/http
Content-Transfer-Encoding: binary
Accept: application/json

GET /odata/Product HTTP/1.1
Accept: application/json

--batch_1237acc2-bef9-435f-a0ca-3c8ba817079e--
```

### Expected result

--batchresponse_e5c36a5c-8108-483c-a0ea-0a89b4187e0e
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 200 OK
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
OData-Version: 4.0

**{"@odata.context":"http://localhost:11546/odata/$metadata#Product","value":[{"Id":0,"Name":"PC"},{"Id":1,"Name":"Bread"}]}**
--batchresponse_e5c36a5c-8108-483c-a0ea-0a89b4187e0e--

### Actual result

--batchresponse_2b2ab216-261f-4dcd-a9b8-81496a3c2ec6
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 200 OK
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
OData-Version: 4.0

--batchresponse_2b2ab216-261f-4dcd-a9b8-81496a3c2ec6--

**Comment by xuzhg** [comment]
Merged. Thanks.
