### ISSUE TITLE
EtagMessageHandler does not add Etags

### ISSUE THREAD

**Issue by robward-ms** [OData/WebApi#1306]
When adding an EtagMessageHandler to the configuration, Etags are not added.

### Assemblies affected

7.0.0-Beta2

### Reproduce steps

Create a controller with a method to put or post a resource from the model.
Add an ETagMessageHandler to the configuration.

### Expected result

The put/post works as expected and Etag is returned.

### Actual result

The Etag is not returned.

**Comment by xuzhg** [comment]
@robward-ms I helped to merged your PR. Please let me know any problem.
