### ISSUE TITLE
[feature/netcore] Applying Delta<TEntity> patch does nothing

### ISSUE THREAD

**Issue by gordon-matt** [OData/WebApi#1316]
Not sure if it's a bug or if the way to do this has changed, but applying a `Delta<TEntity>` patch does nothing.

Here's my generic Patch method:

```
[AcceptVerbs("PATCH", "MERGE")]
public virtual async Task<IActionResult> Patch([FromODataUri] TKey key, Delta<TEntity> patch)
{
    if (!ModelState.IsValid)
    {
        return BadRequest(ModelState);
    }

    TEntity entity = await Service.FindOneAsync(key);

    if (entity == null)
    {
        return NotFound();
    }

    if (!CanModifyEntity(entity))
    {
        return Unauthorized();
    }

    patch.Patch(entity); // <-- No change here. I assume there is a problem binding to the Delta<TEntity>

    try
    {
        await Service.UpdateAsync(entity);
    }
    catch (DbUpdateConcurrencyException x)
    {
        Logger.LogError(new EventId(), x, x.Message);

        if (!EntityExists(key))
        {
            return NotFound();
        }
        else { throw; }
    }

    return Updated(entity);
}
```

I don't know for certain, but my bet is there is a problem binding to the `Delta<TEntity>`

**Comment by gordon-matt** [comment]
I just noticed this is actually a duplicate of #1292. I will grab the latest nightly and see if it's fixed for me, then close this

**Comment by gordon-matt** [comment]
Latest version makes no difference - it's still not binding. I see the fix is in #1300, which was only 20 hours ago.. so perhaps the fix isn't in the latest nightly yet?

**Comment by xuzhg** [comment]
@gordon-matt You're right. The fix is not in the latest successful nightly build (version 7.0.0-Nightly201803261244) yet.  The latest successful Nightly build was queued before #1300. I queued a new nightly build. Once it finishes, I will update you. Thanks!

**Comment by xuzhg** [comment]
@gordon-matt The latest nightly package (Microsoft.AspNet.OData 7.0.0-Nightly201803272349) is out. Would you please try it out and let us know the result? Appreciate your feedback!

**Comment by gordon-matt** [comment]
@xuzhg Thanks, I can confirm it is working now.
