### ISSUE TITLE
[feature/netcore] Recent nightly NuGet packages unable to build due to Microsoft.OData.Core dependency

### ISSUE THREAD

**Issue by techniq** [OData/WebApi#1321]
Using the nightlies from [MyGet](https://www.myget.org/F/webapinetcore/api/v3/index.json), it appears the upgrade of Microsoft.OData.Core from 7.4.1 to 7.4.3 (https://github.com/OData/WebApi/commit/bbf848059b18119321b081322225771ed398d5d5) is not represented in the NuGet dependencies and is thus not able to build.

<img width="823" alt="screen shot 2018-03-28 at 1 50 30 pm" src="https://user-images.githubusercontent.com/177476/38047384-53c8777e-3290-11e8-9c67-59a81d63e437.png">

### Assemblies affected

Nightlies generated in the last week or so

### Reproduce steps

Attempt to build a project with a recent nightly

### Expected result

Build successfully

### Actual result

![image](https://user-images.githubusercontent.com/177476/38047448-976343e2-3290-11e8-95e0-a1faefb1abf5.png)

**Comment by xuzhg** [comment]
The latest nightly build is [Microsoft.AspNetCore.OData 7.0.0-Nightly201803281948](https://www.myget.org/feed/webapinetcore/package/nuget/Microsoft.AspNetCore.OData)

![image](https://user-images.githubusercontent.com/9426627/38052873-5639daa6-3287-11e8-9317-b5db57ffb960.png)

**Comment by techniq** [comment]
@xuzhg I would of thought I was crazy if I hadn't captured the screenshot showing `7.0.0-Nightly201803272349` requiring Microsoft.OData.Core 7.3.1 as well as my VSTS build was failing for the same issue.  When I check now in Visual Studio Mac, I see 7.4.3 for the `7.0.0-Nightly201803272349` (as well as the latest `7.0.0-Nightly201803281948` which wasn't out yet when I submitted this)

![image](https://user-images.githubusercontent.com/177476/38053778-fb1f2c36-32a2-11e8-8414-9d1add21332f.png)

After submitting this issue I decided to downgrade to [beta2](https://www.nuget.org/packages/Microsoft.AspNetCore.OData/) on NuGet official as I needed to get around the build problem and wasn't needing any recent changes.  I'll switch back to Nightlies next time I need an unreleased commit, but for now it looks like it should work if I do, so I'll close the issue.

**Comment by xuzhg** [comment]
Glad to know this and welcome any further questions.

**Comment by techniq** [comment]
@xuzhg Well, I tried to install the nightlies again and still getting the same error regarding only having `Microsoft.OData.Core` version `7.3.1` on NuGet when it needs `7.4.3`.   I then tried to install `Microsoft.OData.Core` into a brand new web project and it still gets `7.3.1`

![image](https://user-images.githubusercontent.com/177476/38319120-07c4d3d0-37ff-11e8-87f4-1d5bd187b632.png)

I can clearly see [7.4.3](https://www.nuget.org/packages/Microsoft.OData.Core/7.4.3) is available on NuGet (including in the Visual Studio for Mac UI)...

![image](https://user-images.githubusercontent.com/177476/38319275-715df89e-37ff-11e8-9bf1-c713992f2c00.png)

...but no matter what I try, it seems to only see `7.3.1`

![image](https://user-images.githubusercontent.com/177476/38319337-95e5c304-37ff-11e8-8734-ecc69741c93c.png)

This is happening on mine another another developers Mac, as well as on VSTS.  I can't seem to tell on NuGet.org if maybe 7.4.3 is not a .netstandard package, and 7.3.1 was, and maybe that's why I can't install 7.4.3, but I'm drawing at straws at this point.

**Comment by robward-ms** [comment]
ODL 7.4.3. sill ships a NetStandard 1.1 Dll so that should not be it.

Any thoughts on this @xuzhg?

**Comment by techniq** [comment]
@robward-ms I am.  I just created a new web project and installed Microsoft.OData.Core and still pull 7.3.1

![image](https://user-images.githubusercontent.com/177476/38831892-d0a2bc84-418e-11e8-9853-ba14faf82339.png)

although I just had my coworker perform the same steps and his pulled 7.4.4 (which should mean the nightlies would work).

![image](https://user-images.githubusercontent.com/177476/38832267-054a6b48-4190-11e8-988d-293189df56ca.png)

We're both running `dotnet 2.1.4` on Mac.  I run zsh but tried bash as well (to try to rule out other environment things) and still get 7.3.1 on my machine.

I then tried to clear my local nuget package:
- `rm -rf ~/.nuget/packages/*`

and try again, but still pulled `7.3.1`

![image](https://user-images.githubusercontent.com/177476/38832723-70f07dc8-4191-11e8-8ce3-7b3bba35c31e.png)

**Comment by techniq** [comment]
@robward-ms good call.

I had this page open earlier but only manually cleared out my `~/.nuget/packages` which after reading is just the global packages cache.  Issuing `dotnet nuget locals all --clear` cleared out the HTTP cache, global packages cache, and temp cache, and now I grab 7.4.4.  

![image](https://user-images.githubusercontent.com/177476/38833661-2b39a31a-4194-11e8-827e-f1420a36074b.png)

I'm not in a position to pull in nightlies into my current project that was having an issue, but I'll try again soonish (and reopen the issue).  I was also having this problem on my VSTS build.. so curious if it's still an issue there.  I'll script in a nuget cache clear there if needed.

Thanks for your help.
