### ISSUE TITLE
Support collection of complex type value as function parameter

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#133]
We need to support this feature so that below request can be fulfilled.  

    
    
    PUT ~/Windows(1)/OptionalShapes

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2064](http://aspnetwebstack.codeplex.com/workitem/2064)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jul 16, 2014 at 3:56 AM
**Reported by:**	jinfutan
**Updated on:**	Sep 27, 2014 at 8:23 AM
**Updated by:**	okazuki

**Comment by xuzhg** [comment]
Duplicated as #7.
