### ISSUE TITLE
[feature/netcore] Overload for ODataQueryOptions<T>.ApplyTo does NOT apply ODataQueryOptions

### ISSUE THREAD

**Issue by gordon-matt** [OData/WebApi#1357]
`ODataQueryOptions<T>.ApplyTo(IQueryable query, AllowedQueryOptions ignoreQueryOptions)` doesn't apply the query options.

**This works fine:**
`var results = options.ApplyTo(query);`

**This does NOT work:**
`var results = options.ApplyTo(query, AllowedQueryOptions);`

Here, `AllowedQueryOptions` is a property and the value of it is: `AllowedQueryOptions.All`

Basically, it just returns everything and doesn't filter, order, skip, etc.

**Comment by gordon-matt** [comment]
Note: This bug also prevents `@odata.count` from being returned as well.

**Comment by gordon-matt** [comment]
My mistake - it would appear that the second parameter in `ApplyTo` does not behave the same as the `AllowedQueryOptions` property in the `[EnableQuery]` attribute. Instead, it's the opposite. I just noticed the name of the parameter in question is **ignoreQueryOptions**, so instead of passing `AllowedQueryOptions.All`, I either don't pass anything or where I am using my generic controller, I now have the following property:

`protected virtual AllowedQueryOptions IgnoreQueryOptions => AllowedQueryOptions.None;`

and use as follows:
`var results = options.ApplyTo(query, IgnoreQueryOptions);`

**Comment by rossbuggins** [comment]
I've just had the same moment of madness. If you want the same behaviour as EnableQuery, pass the QueryOptions you want to allow into an new instance ODataValidationSettings and pass this to the ApplyTo method.
