### ISSUE TITLE
Could not load file or assembly System.Web.Http, Version=5.2.2.0 error when deploy my WebApi service to Azure.

### ISSUE THREAD

**Issue by JeffreyZZ** [OData/WebApi#1368]
I’m using nuget Microsoft.AspNet.OData 6.1.0 (System.Web.OData.dll) and Microsoft.AspNet.WebApi.Core 5.2.3 ('System.Web.Http.dll) in my Azure Web Api project. I added the following bindingRedirect in the web.config file, which works well in Azure emulator on my local deployment machine. 

      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http.Formatting" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>

However as I deployed this web api service to my Azure subscription, it always failed to start with the following error captured in Event Viewer. I find another bug (https://github.com/OData/WebApi/issues/275) ever reported about this issue before, but I didn't see any solution mentioned. After revert Microsoft.AspNet.WebApi.Core to 5.2.2 in project, it works well.  Could any one from the team help take a look?

Role entrypoint could not be created: System.TypeLoadException: Unable to load the role entry point due to the following exceptions:
-- System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Web.Http, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
 
=== Pre-bind state information ===
LOG: DisplayName = System.Web.Http, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
(Fully-specified)
LOG: Appbase = file:///F:/approot/bin
LOG: Initial PrivatePath = F:\approot\bin
Calling assembly : System.Web.OData, Version=6.1.0.10907, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: F:\base\x64\WaIISHost.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from D:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Web.Http, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Attempting download of new URL file:///F:/approot/bin/System.Web.Http.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

Hare are the steps to repro it by building a solution from scratch, and I also attached my test solution : 
[ODataTestService.zip](https://github.com/OData/WebApi/files/1886793/ODataTestService.zip)

1.	Open Visual Studio 2015, Visual C# -> Cloud -> Azure Cloud Service
2.	Add ASP.NET Web Role
3.	ASP.NET 4.5.2 Template -> Empty -> Add folders and core references for Web API
4.	Install Microsoft.AspNet.OData nuget package 6.1.0 via Manage Nuget Packages..
5.	Update WebApiConfig.cs file with the sample code from http://odata.github.io/WebApi/#01-02-getting-started. I attached my solution codes. 
6.	Run it in local Azur Emulator, it works well. 
7.	Deploy it to Azure, it failed in initialization with the above error.

**Comment by nstubi** [comment]
Hello,

I've the same issue with Microsoft.AspNet.OData 6.1.0

Having to downgrade is a shame.

But I am considering to do it now ...

Best Regards,
Nicolas Stübi

**Comment by vinniep79** [comment]
Any updates on this issue?

**Comment by looptr00p** [comment]
Hi! i have the same problem, but with the Microsoft.AspNet.WebApi.Cors. Anyone solved this problem??

**Comment by etehadi** [comment]
This dll is loading as a dependency of a nuget package. So you should reinstall it. For me this command worked:
Update-Package Microsoft.AspNet.WebApi -reinstall

**Comment by ryanharding** [comment]
Solved it myside. So for me, was 2 issues. 

1) the nuget package was not creating the lib folder in my projects packages folder for Microsoft.AspNet.WebApi
2) A search of the package folder for the dll's showed them in other nuget packages, and the version number of these were different to what my web.config was saying.

Fix:
1. Remove System.Web.Http from under References 
2. Manuel browse and add it from folder in project packages (for me it was Microsoft.AspNet.WebApi.Core.5.2.7\lib\net45 )
3. Right click - properties - details on System.Web.Http.dll, check version and update in web.config

**Comment by lavahasif** [comment]
i face this problem with unity nuget package .it resolved by updating latest http plugin from nuget
