### ISSUE TITLE
Delta<T> should avoid static properties

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#137]
When initializing the _allProperties field in Delta<T> GetProperties() gets
called, which includes static properties.  
  
Instead GetProperties(BindingFlags.Instance | BindingFlags.Public) should be
used.  
  
We need to evaluate the impact on existing scenarios before making this
change.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2079](http://aspnetwebstack.codeplex.com/workitem/2079)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jul 29, 2014 at 4:29 AM
**Reported by:**	jacalvar
**Updated on:**	Aug 14, 2014 at 9:17 AM
**Updated by:**	azhou

**Comment by xuzhg** [comment]
Close it. Thanks.
