### ISSUE TITLE
OData Core Throws null reference exception when trying to execute

### ISSUE THREAD

**Issue by granthoff1107** [OData/WebApi#1370]
I'm working .Net Core using on the 7.0.0 Beta-2
http://localhost:59943/Api/Values/OData?$filter=substring(LastName, 1) eq 'u'
When trying to execute a simple filter on a query some functions throw a null reference exception

```        
        CustomContext _context;
   
        public ValuesController(CustomContext context)
        {
            this._context = context;
        }

        [HttpGet("OData")]
        public async Task<User[]> ODataFailingTestings(ODataQueryOptions<User> queryOptions)
        {
            var baseQuery = this._context.Users.AsQueryable();
            if (queryOptions != null)
            {
                baseQuery = queryOptions.ApplyTo(baseQuery, new ODataQuerySettings()) as IQueryable<User>;
            }

            var values = await baseQuery.ToArrayAsync();
            return values;
        }
```

**Comment by robward-ms** [comment]
@granthoff1107 - Can you provide any more details regarding the null reference exception, maybe a call stack?

**Comment by granthoff1107** [comment]
> 

   at lambda_method(Closure , User )
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Astoot.Controllers.ValuesController.ODataFailingTestings(ODataQueryOptions`1 queryOptions) in C:\source\Astoot\src\Astoot\Controllers\ValuesController.cs:line 39

**Comment by robward-ms** [comment]
Looks like you are using EFCore. Are you using 2.1.0 or better? OData for AspNetCore is not fully compatible with EFCore yet, it is tracked in #669.

**Comment by granthoff1107** [comment]
I have not upgraded to 2.1.0. Yet.  I’m still using 2.0.3.  Will upgrading be more beneficial or less?

**Comment by robward-ms** [comment]
The AsQueryable() function is not supported in EfCore until 2.1.0:

`this._context.Users.AsQueryable();`

I suspect you are seeing a delay execution exception from that line. That said, OData WebApi is still not fully compatible with EFCore, see #669.

**Comment by robward-ms** [comment]
See #1154 for links to the EFCore GitHub issues associated with AsQueryable().   #669 is the OData bug tracking EFCore and OData WebApi.

**Comment by granthoff1107** [comment]
Thanks, I’ll check this out after I upgrade, and if it works I’ll close the issue.

**Comment by xuzhg** [comment]
@granthoff1107 Have you been checked the latest?

**Comment by biaol-odata** [comment]
@granthoff1107 Both [beta4](https://www.nuget.org/packages/Microsoft.AspNetCore.OData/7.0.0-beta4) and [EFCore 2.1](https://www.nuget.org/packages/Microsoft.AspNetCore/2.1.0) have been available since end of May. Can you please try and let's know any updates.

**Comment by granthoff1107** [comment]
Yeah upgrading is the next task on my list,  I’m just working on a production  issue I’ll post an update as soon as I upgrade

**Comment by granthoff1107** [comment]
Okay, let me know if there's any I can do to help
