### ISSUE TITLE
DefaultODataPathHandler does not correctly handle long queries with lambda operators

### ISSUE THREAD

**Issue by StanislawSwierc** [OData/WebApi#1375]
I observed strange behavior when working with OData queries which used `any` lambda filters. Apparently `DefaultODataPathHandler` fails to handle such query because it treats whole path and query as one long scheme part. I debugged this problem and found that the root cause it probably in the framework. I've opened an issue against the framework https://github.com/dotnet/corefx/issues/29011. Most likely it will take long time to make a fix in such a base class. Maybe we can fix it in the WebApi project earlier. I expect that this problem affects all the endpoints including the one used for tutorials at odata.org.

http://services.odata.org/V4/(S(l0iq2naomzp2p3vvm2c2tmrl))/TripPinServiceRW/People?$filter=%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Emails/any(s:endswith(s,%20%27contoso.com%27))

    static void Main(string[] args)
    {
        var baseUri = new Uri("https://stansw.analytics.visualstudio.com/_odata/v2.0-preview/");
        var relativeUri =
              "WorkItems?$filter=                                                                                                              " // 128
            + "                                                                                                                                " // 256
            + "                                                                                                                                " // 384
            + "                                                                                                                                " // 512
            + "                                                                                                                                " // 640
            + "                                                                                                                                " // 768
            + "                                                                                                                                " // 896
            + "Processes/any(b:b/BacklogName eq 'Features')";

        var uri = new Uri(baseUri, relativeUri);
        Console.WriteLine(uri.ToString());

        relativeUri =
              "WorkItems?$filter=                                                                                                              " // 128
            + "                                                                                                                                " // 256
            + "                                                                                                                                " // 384
            + "                                                                                                                                " // 512
            + "                                                                                                                                " // 640
            + "                                                                                                                                " // 768
            + "                                                                                                                                " // 896
            + "                                                                                                                                " // 1024
            + "Processes/any(b:b/BacklogName eq 'Features')";

        uri = new Uri(baseUri, relativeUri);
        Console.WriteLine(uri.ToString());
    }

**Comment by StanislawSwierc** [comment]
This is example of how you can reproduce it with existing tests:

```
public static TheoryDataSet<string, string> AnyAndAllFunctionsTestData
{
    get
    {
        return new TheoryDataSet<string, string>
        {
            // Primitive collection property
            {"?$filter=Points/any()", "any"},
            {"?$filter=Points/any(p: p eq 1)", "any"},
            {"?$filter=Points/all(p: p eq 1)", "all"},

            // Complex type collection property
            {"?$filter=Addresses/any()", "any"},
            {"?$filter=Addresses/any(a: a/ZipCode eq 1)", "any"},
            {"?$filter=Addresses/all(a: a/ZipCode eq 1)", "all"},

            // Collection navigation property
            {"?$filter=Orders/any()", "any"},
            {"?$filter=Orders/any(o: o/Id eq 1)", "any"},
            {"?$filter=Orders/all(o: o/Id eq 1)", "all"},

            // Collection navigation property with casts
            {"?$filter=Orders/any(o: o/System.Web.OData.Test.DiscountedEnableQueryOrder/Discount eq 1)", "any"},
            {"?$filter=Orders/all(o: o/System.Web.OData.Test.DiscountedEnableQueryOrder/Discount eq 1)", "all"},
            {"?$filter=Orders/System.Web.OData.Test.DiscountedEnableQueryOrder/any()", "any"},
            {"?$filter=Orders/System.Web.OData.Test.DiscountedEnableQueryOrder/any(o: o/Discount eq 1)", "any"},
            {"?$filter=Orders/System.Web.OData.Test.DiscountedEnableQueryOrder/all(o: o/Discount eq 1)", "all"},

            // Long queries
            { "?$filter="
                + "                                                                                                                                " // 128
                + "                                                                                                                                " // 256
                + "                                                                                                                                " // 384
                + "                                                                                                                                " // 512
                + "                                                                                                                                " // 640
                + "                                                                                                                                " // 768
                + "                                                                                                                                " // 896
                + "                                                                                                                                " // 1024
                + "Points/any(p: p eq 1)", "any"},
        };

    }
}
```

**Comment by robward-ms** [comment]
@StanislawSwierc - Looks like you coded a fix and added a test. Have you considered contributing it to this WebApi repo?

**Comment by StanislawSwierc** [comment]
I've already contributed it to the fork maintained by my product group. I'll check if we've got plans to reverse-integrate our fixes.

https://github.com/kosinsky/WebApi/pull/26
