### ISSUE TITLE
Allow enum properties to be keys

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#138]
With OData 4 support for enums, composite keys, containing an enum are no
longer possible. If the property is explicitly declared as enum before the
explicit ` .HasKey ` call, an exception is thrown in `
StructuralTypeConfiguration.AddProperty ` . If the ` .HasKey ` is called
first, then an exception is thrown in `
StructuralTypeConfiguration.AddEnumProperty ` .  
  
For example, the following model is not working with OData 4:  

    
    
    public class MyEntity
    {
        [Key]
        [Column(Order = 0)]
        public long Key1 { get; set; }
    
        [Key]
        [Column(Order = 1)]
        public MyEnum Key2 { get; set; }
    }
    
    public enum MyEnum
    {
        FirstValue,
        SecondValue
    }

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2080](http://aspnetwebstack.codeplex.com/workitem/2080)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jul 29, 2014 at 10:37 AM
**Reported by:**	nirinchev
**Updated on:**	Nov 21, 2014 at 9:02 PM
**Updated by:**	afutrell

**Comment by LianwMS** [comment]
On *2014-07-30 21:49:41 UTC*, **rcollette** commented:

Related to:
https://aspnetwebstack.codeplex.com/workitem/2082

**Comment by LianwMS** [comment]
On *2014-11-22 04:32:36 UTC*, **packman76** commented:

This issue is especially problematic when the Enum key property is part of a composite key because you get no indication from the ODataConventionModelBuilder that it has dropped one of your keys from the resulting model.

You don't even know you have a problem until you start getting weird, hard-to-track-down behavior on the client due to the missing keys.

**Comment by xuzhg** [comment]
Checked-in. Thanks.
