### ISSUE TITLE
[feature/netcore] UseODataBatching() should return IApplicationBuilder

### ISSUE THREAD

**Issue by maximpashuk** [OData/WebApi#1381]
now signature of UseODataBatching is
```public static void UseODataBatching(this IApplicationBuilder app)```
I think it should be
```public static IApplicationBuilder UseODataBatching(this IApplicationBuilder app)```

Method UseMiddleware returns IApplicationBuilder, so you just should also return IApplicationBuilder.

This will allow to construct method chains like app.UseODataBatching().UseMvc()

**Comment by xuzhg** [comment]
Thanks, I think so. Will update.

**Comment by xuzhg** [comment]
Merged. Thanks.
