### ISSUE TITLE
[feature/netcore] ODataBatchMiddleware should use TemplateMatcher

### ISSUE THREAD

**Issue by maximpashuk** [OData/WebApi#1386]
TemplateMatcher = Microsoft.AspNetCore.Routing.Template.TemplateMatcher

If I map OData route on route that contain template parameters like
``` builder.MapODataServiceRoute("odata", "v{api-version:apiVersion}/odata", ...)```
Then regular ODATA calls works fine, but **$batch calls not work**.

I investigate this and I found that ODataBatchMiddleware not using TemplateMatcher then trying to match request path to Odata route.
Only constant route templates is supported.

So please support $batch endpoint with mapping to route templates with parameters.

**Comment by xuzhg** [comment]
@maximpashuk Would you please take a look about #1436. Thanks

**Comment by maximpashuk** [comment]
@xuzhg approved, this is exactly a was talking about

**Comment by xuzhg** [comment]
Merged the PR #1436. Thanks your contribution!
