### ISSUE TITLE
[feature/netcore] ODataPathRouteConstraint is not extensible

### ISSUE THREAD

**Issue by commonsensesoftware** [OData/WebApi#1388]
The type **ODataPathRouteConstraint** is not properly extensible in ASP.NET Core because the [Match](../blob/feature/netcore/src/Microsoft.AspNetCore.OData/Routing/ODataPathRouteConstraint.cs#L32) method is not `virtual`. While this type can be _decorated_ or _adapted_, the lack of extensibility breaks other functionality such as [ODataRoute](../blob/feature/netcore/src/Microsoft.AspNet.OData.Shared/Routing/ODataRoute.cs), which has a hard dependency on this concrete, base type.

### Assemblies affected

* Microsoft.AspNetCore.OData Version=7.0.0-beta2
* Microsoft.AspNetCore.OData Version=7.0.0-Nightly*

### Reproduce steps

Try to extent the platform.

### Expected result

**ODataPathRouteConstraint.Match** should be `virtual`.

### Actual result

**ODataPathRouteConstraint.Match** is not `virtual`.

### Additional detail

The [Match](../blob/feature/netcore/src/Microsoft.AspNet.OData/Routing/ODataPathRouteConstraint.cs#L31) method implementation in **ODataPathRouteConstraint** for Web API is `virtual`.

**Comment by robward-ms** [comment]
@commonsensesoftware - Sounds like a great feature, any interest in making a contribution to fix the scenario?

**Comment by xuzhg** [comment]
Merged. Thanks.
