### ISSUE TITLE
OData: Enum keys not recognized by ODataConventionModelBuilder

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#139]
Given a class which contains properties:  

    
    
            [Key,
            Range(1, int.MaxValue)]
            public int? Id { get; set; }
    
            /// <summary>
            /// The type of client
            /// </summary>
            [Key]
            public BusinessType ClientType { get; set; }

Where BusinessType is  

    
    
        public enum BusinessType
        {
            Broker,
            Agent
        }

With configuration like:  

    
    
                ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
                EntitySetConfiguration<Client> clients = builder.EntitySet<Client>("Clients");           
                var conventions = ODataRoutingConventions.CreateDefault();
                conventions.Insert(0, new CompositeKeyRoutingConvention());
                config.MapODataServiceRoute(
                    routeName: "odata",
                    routePrefix: "odata",
                    model: builder.GetEdmModel(),
                    pathHandler: new DefaultODataPathHandler(),
                    routingConventions: conventions);

The generaeted $metadata does not include the enum type ClientType property  

    
    
    <EntityType Name="Client">
    <Key>
    <PropertyRef Name="Id" />
    </Key>

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2082](http://aspnetwebstack.codeplex.com/workitem/2082)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Jul 29, 2014 at 11:27 PM
**Reported by:**	rcollette
**Updated on:**	Dec 3, 2014 at 4:02 PM
**Updated by:**	troydalldorf

**Comment by LianwMS** [comment]
On *2014-07-30 16:12:52 UTC*, **nirinchev** commented:

I believe this is related to 
Allow enum properties to be keys. It appears this is a scenario that was not foreseen by the team.

**Comment by LianwMS** [comment]
On *2014-07-30 21:37:51 UTC*, **rcollette** commented:

Thank you for the cross link nirinchev. It's interesting that we posted this same issue on the same day. Yours was first but for some reason my search didn't find it and I also browsed recent issues manually and didn't see it.

Is there a way we can combine these issues? I don't see any options on my to delete or close it.

What I find surprising about the ODataConventionModelBuilder is that it seems to be a completely free standing model builder, not based on any other common base classes from EF/EDM. Therefore, it's not surprising that features are going to be out of sync, missing,
 or behaving differently. I wish MS would refactor the code a bit to separate the data access and data model portions of EF/EDM so that it can be reused in cases like ODataConventionModelBuilder.

Sadly there is still no foreign key support as well.

**Comment by LianwMS** [comment]
On *2014-08-05 03:37:13 UTC*, **rcollette** commented:

I trace the issue down to System.Web.OData.Builder.EntityTypeConfiguration

The method: 

public virtual EntityTypeConfiguration HasKey(PropertyInfo keyProperty)

Creates only a PrimitivePropertyConfiguration and does not create a EnumPropertyConfiguration if the property being added as a Key is an enum.

**Comment by LianwMS** [comment]
On *2014-11-22 04:28:25 UTC*, **adamcaviness** commented:

I would consider this more than a low impact issue.

**Comment by LianwMS** [comment]
On *2014-11-22 04:33:08 UTC*, **packman76** commented:

This issue is especially problematic when the Enum key property is part of a composite key because you get no indication from the ODataConventionModelBuilder that it has dropped one of your keys from the resulting model.

You don't even know you have a problem until you start getting weird, hard-to-track-down behavior on the client due to the missing keys.

**Comment by xuzhg** [comment]
Resolved as duplicated:
https://github.com/OData/WebApi/issues/138
