### ISSUE TITLE
[feature/netcore] Expose underlying semantic OData path

### ISSUE THREAD

**Issue by atykhyy** [OData/WebApi#1398]
The so-called semantic OData path - `Microsoft.OData.UriParser.ODataPath` - is more useful than `Microsoft.AspNet.OData.Routing.ODataPath`, and the latter is constructed from the former, but it does not expose the underlying semantic path object publicly. 

### Expected result

The semantic OData path underlying the `AspNet.OData.Routing.ODataPath` is accessible.

### Actual result

The semantic OData path is not accessible.

### Additional detail

There is an old TODO in ODataOutputFormatterHelper.cs:
```
// TODO: 1604 Convert webapi.odata's ODataPath to ODL's ODataPath, or use ODL's ODataPath.
```
However, it doesn't look like a high priority item. In the meantime, it would be helpful to have the semantic path available and not have to fish out (or squirrel away) the original URL components and re-parse the path with the semantic parser, or to read the internal property with reflection. The required change is just one line:
```
diff --git a/src/Microsoft.AspNet.OData.Shared/Routing/ODataPath.cs b/src/Microsoft.AspNet.OData.Shared/Routing/ODataPath.cs
index 8298dfc..db3112f 100644
--- a/src/Microsoft.AspNet.OData.Shared/Routing/ODataPath.cs
+++ b/src/Microsoft.AspNet.OData.Shared/Routing/ODataPath.cs
@@ -106,6 +106,6 @@ public override string ToString()
             return _pathLiteral;
         }

-        internal Semantic.ODataPath ODLPath { get; set; }
+        public Semantic.ODataPath ODLPath { get; internal set; }
     }
 }
```

**Comment by madansr7** [comment]
closing because the fix is merged.
