### ISSUE TITLE
Provide api to make Action parameters Nullable

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#14]
For the following action, I would like to make the parameter 'p3' nullable.
Currently, there is no api on the ActionConfiguration which can make it
Optional or Nullable.  
  
var actionConfig = vehicle.Action("TestAction1");  
actionConfig.Parameter<string>("p1");  
actionConfig.Parameter<string>("p2");  
actionConfig.Parameter<string>("p3");  
  
Also, from the schema, there seem to be other attributes like "MaxLength",
"Precision", "Scale" etc. that can be provided for FunctionImport's
parameters:  
  
<xs:attributeGroup name="TFunctionImportParameterAttributes">  

    
    
    <xs:attribute name="Name" type="edm:TSimpleIdentifier" use="required" />
    <xs:attribute name="Type" type="edm:TFunctionImportParameterAndReturnType" use="required" />
    <xs:attribute name="Mode" type="edm:TParameterMode" use="optional" />
    <xs:attribute name="Nullable" type="xs:boolean" use="optional" />
    <xs:attribute name="MaxLength" type="edm:TMaxLengthFacet" use="optional" />
    <xs:attribute name="Precision" type="edm:TPrecisionFacet" use="optional" />
    <xs:attribute name="Scale" type="edm:TScaleFacet" use="optional" />
    <xs:attribute name="SRID" type="edm:TSridFacet" use="optional" />
    <xs:anyAttribute namespace="##other" processContents="lax" />

</xs:attributeGroup>  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 461](http://aspnetwebstack.codeplex.com/workitem/461)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Sep 26, 2012 at 3:19 AM
**Reported by:**	kichalla
**Updated on:**	Sep 23, 2013 at 7:15 PM
**Updated by:**	danroth27

**Comment by xuzhg** [comment]
I separated this feature into two parts and created the corresponding issues.

1. __Make function/action parameter and return type as Nullable__ [#210](
https://github.com/OData/WebApi/issues/210)

2. __Support MaxLength,Precision,Scale .. for parameter__ [#211](https://github.com/OData/WebApi/issues/211)

**Comment by xuzhg** [comment]
So, I resolved it as duplicated.
