### ISSUE TITLE
OData V4: Support creation of Microsoft.OData.Edm.IEdmModel from DbContext

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#140]
I really is hard to fathom why there are separately namespaced IEdmModel for
EF and OData. There needs to be a common interface assembly that both use. As
it stands, the work of one group is never going to be in sync with the other.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2084](http://aspnetwebstack.codeplex.com/workitem/2084)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jul 30, 2014 at 5:38 PM
**Reported by:**	rcollette
**Updated on:**	Aug 14, 2014 at 9:15 AM
**Updated by:**	azhou

**Comment by tschettler** [comment]
+1 The conversion from DBContext to IEdmModel works for OData 3, it seems reasonable to also have a method to do it for OData 4, hopefully sooner than later.

**Comment by xuzhg** [comment]
You can refer to http://github.com/OData/Restier. Thanks.
