### ISSUE TITLE
[feature/netcore] When is this commit getting released to Nuget.org?

### ISSUE THREAD

**Issue by akorchev** [OData/WebApi#1401]
Hi guys,

When do you think [this commit](https://github.com/OData/WebApi/commit/51ce3d6ab70e3ef92f8015c6e397118e6b225d11#diff-3f42c9656a7ac14ed1050a774e681c6c) will get released to Nuget? We are facing a problem which the RouteName property solves (verified against the master branch).

**Comment by robward-ms** [comment]
I think Sam commented on #939 the other day with some more release details which answers the "When on Nuget" questions.

If it really more of a "when can I get a Nuget package with the fix", we publish a nightly build so the fix is available on MyGet. Details are in our [readme.md](https://github.com/OData/WebApi/blob/master/README.md):

```
Nightly builds
The nightly build process will upload a NuGet packages for WebApi to the [MyGet.org webapinightly feed](https://www.myget.org/gallery/webapinightly).

To connect to webapinightly feed, use this feed URL: [webapinightly MyGet feed URL](https://www.myget.org/F/webapinightly).

You can query the latest nightly NuGet packages using this query: [MAGIC WebApi query
](https://www.myget.org/F/webapinightly/Packages?$select=Id,Version&$orderby=Version%20desc&$top=4&$format=application/json)```

**Comment by robward-ms** [comment]
Ah, sorry about that. I thought the readme was up-to-date but apparently not.  The link you want is: https://www.myget.org/F/webapinetcore/

**Comment by NetTecture** [comment]
Ah, no?

That link returns an XML document with the content...

<service xmlns="http://www.w3.org/2007/app" xmlns:atom="http://www.w3.org/2005/Atom" xml:base="https://www.myget.org/F/webapinetcore/">
<workspace>
<atom:title>Default</atom:title>
<collection href="Packages">
<atom:title>Packages</atom:title>
</collection>
<collection href="Screenshots">
<atom:title>Screenshots</atom:title>
</collection>
</workspace>
</service>

Not exactly anything to download.

**Comment by robward-ms** [comment]
@NetTecture:

It's a Nuget feed, as in:

> To connect to webapinightly feed, use this feed URL: [webapinightly MyGet feed URL.](https://www.myget.org/F/webapinetcore/)

**Comment by NetTecture** [comment]
I stand corrected - yeah, empty xml, but once you point nuget at it, something shows up ;)
