### ISSUE TITLE
[feature/netcore] Exception on Get/Post when using EnableLowerCamelCase with optional keys.

### ISSUE THREAD

**Issue by offbeatful** [OData/WebApi#1402]
Encountered exception during standard usage (GET/POST) operations when Key is marked as optional and EnableLowerCamelCase was invoked.

### Assemblies affected

Microsoft.AspNetCore.OData 7.0.0-beta2

### Reproduce steps

1. Use EnableLowerCamelCase();
2. Configure your model:
            var entityType = ODataModelBuilder.EntitySet<T>(route).EntityType;
            entityType.HasKey(_ => _.Id);
            entityType.Property(_ => _.Id).IsOptional();
3. Run and Try to POST/GET

Note: without EnableLowerCamelCase() - everything works fine

### Expected result

Works properly for GET/POST operations.

### Actual result

Received the following exception:
`System.InvalidOperationException: The EDM instance of type '[WebApp.User Nullable=True]' is missing the property 'id'.
`

### Additional detail

The issue appears only with EnableLowerCamelCase. Everything works fine without it.
Id is Uppercase. Its type is 'Guid?'

**Comment by robward-ms** [comment]
@offbeatful - Can you include your Startup.cs code and the model class just to make sure we look at the right issue?

**Comment by AlanWong-MS** [comment]
@offbeatful, per Rob's comment, would you be able to share details of the Startup.cs code and model class for more info?

**Comment by mikepizzo** [comment]
Note that I'm surprised WebAPI OData lets you define a key property as nullable; by OData protocol, key properties must be non-nullable.  see http://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/cs01/odata-csdl-xml-v4.01-cs01.html#sec_Key:

"An entity type’s key refers to the set of properties that uniquely identify an instance of the entity type within an entity set. The key MUST consist of at least one property.
Key properties MUST NOT be nullable..."

**Comment by xuzhg** [comment]
@offbeatful I can't seem your error message at my side. And I tested it, it can work at my side. See my repro: https://github.com/xuzhg/WebApi/tree/issue1402

@mikepizzo To define a key property as nullable is not prohibited in Web API OData model builder. However, if you run the model validation, you will get the error message as below:

![image](https://user-images.githubusercontent.com/9426627/41071042-db77d0ba-69aa-11e8-967e-a89dffb9983d.png)

**Comment by xuzhg** [comment]
Close it and please file new issue or re-open it if you have further concerns. Thanks.
