### ISSUE TITLE
Expect 400 for NotNavigable usage in path

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#141]
We check the NotNavigable restriction in DefaultODataPathHandler:  
[ https://aspnetwebstack.codeplex.com/SourceControl/latest#OData/src/System.We
b.OData/OData/Routing/DefaultODataPathHandler.cs ](https://aspnetwebstack.code
plex.com/SourceControl/latest#OData/src/System.Web.OData/OData/Routing/Default
ODataPathHandler.cs)  

ODataException is thrown for invalid usages.  
But 400 bad request is expected.  
So this exception should be HttpResponseException or convert to
HttpResponseException  
## Work Item Details

**Original CodePlex Issue:**    [Issue 2088](http://aspnetwebstack.codeplex.com/workitem/2088)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Aug 2, 2014 at 2:53 AM
**Reported by:**    fenzhao
**Updated on:** Aug 14, 2014 at 9:10 AM
**Updated by:** azhou

**Comment by xuzhg** [comment]
Similar to #147.
