### ISSUE TITLE
Complex type list not serialized

### ISSUE THREAD

**Issue by andrew-laughlin** [OData/WebApi#1412]
When requesting a complex type that contains a list of complex types, the list is not serialized to a JSON array.

### Assemblies affected

Microsoft.AspNetCore.OData 7.0.0-beta2

### Reproduce steps

```
public class ConnectedDevice 
{
	[Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
	public System.Guid Id { get; set; }
}

public class Device : ConnectedDevice
{
	[Newtonsoft.Json.JsonProperty("tenantId", Required = Newtonsoft.Json.Required.Always)]
	public System.Guid TenantId { get; set; }

        // ConnectedDevices is not serialized
	[Newtonsoft.Json.JsonProperty("connectedDevices", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
	public System.Collections.ObjectModel.ObservableCollection<ConnectedDevice> ConnectedDevices { get; set; } = new System.Collections.ObjectModel.ObservableCollection<ConnectedDevice>();
}
```

```
var builder = new ODataConventionModelBuilder(serviceProvider);
builder.EnableLowerCamelCase();

builder.EntitySet<Device>("Devices")
                .EntityType
                .HasKey(e => e.Id)
```
Request to:
http://localhost:57787/odata/Devices

Produces the below JSON, which doesn't contain a connectedDevices array.

```
{
	"@odata.context": "http://localhost:57787/odata/$metadata#Devices",
	"value": [{
			"id": "55b519f4-ca2a-4a11-bc75-b3791ffdbd13",
			"tenantId": "fffc0a03-a950-438c-843b-9aa3f2e85892"
		}, {
			"id": "a44534ad-c56f-4974-b51f-8b8462a8b2e1",
			"tenantId": "fffc0a03-a950-438c-843b-9aa3f2e85892"
		}
	]
}
```

### Expected result

Lists of complex properties is serialized to a JSON array in the response.

### Actual result

Complex property list is not serialized in resulting JSON output.

**Comment by xuzhg** [comment]
@andrew-laughlin 

First,  `ConnectedDevice` will be treated as an entity type by convention model builder. So, the `ConnectedDevices ` must be a navigation property.

You should use `?$expand=NAVIGATIONPROPERTY` to serialize the navigation property value in the entity payload. 

Second, The query will be converted to Linq expression. For your exception, would you please to check the corresponding linq method is supported? We'd love to get your feedback. Thanks.

**Comment by andrew-laughlin** [comment]
@xuzhg thanks for your response. How can I use ODataConventionModelBuilder to define ConnectedDevices as a navigation property?

**Comment by andrew-laughlin** [comment]
I have a pretty vanilla setup for device entity config, but connected devices still won't show up in the serialized result. What am I missing?

```
builder.EntitySet<Device>("Devices")
                .EntityType
                .HasKey(e => e.Id)
```

**Comment by andrew-laughlin** [comment]
@xuzhg 
It appears the Cosmos IQueryable provider does not support `Select( ... )`. I think the exception makes sense if `ApplyQuery( ... )` is attempting to add `Select` to the expression tree, when applying expand to the IQueryable. I'm not clear on the details of how this is done, but it's not necessary in my case, as the entire entity (including nested types) is returned from Cosmos and is available to OData.

**Comment by xuzhg** [comment]
@andrew-laughlin Ok. Do you have any chance to file an issue for Cosmos?

**Comment by andrew-laughlin** [comment]
@xuzhg  
again I'm not clear on the details, but if OData is attempting a projection via `Select`, I don't understand how this makes sense? How would it translate into SQL? If Cosmos is returning the entire entity, nested types and all, wouldn't `expand `be applied after the results are returned from Cosmos?

**Comment by xuzhg** [comment]
@andrew-laughlin is your problem resolved?

**Comment by andrew-laughlin** [comment]
@xuzhg We've worked around the issue by separating the entities.
