### ISSUE TITLE
Always get parameter alias from ParameterAliasNodes by odl parser

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#143]
In DefaultODataPathHandler, if unresolved path segment is encountered, we
can't get parameter alias from odl parser.  
So we get the parameter alias info from the query string in this case.  
The bug is fixed in ODL 6.5.  
We can always get the parameter alias from odl parser after migration to ODL
6.5 or later,  
and we don't need query string in DefaultODataPathHandler and
ODataPathSegmentTranslator any more.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2093](http://aspnetwebstack.codeplex.com/workitem/2093)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Aug 5, 2014 at 6:13 AM
**Reported by:**	fenzhao
**Updated on:**	Dec 10, 2014 at 12:31 AM
**Updated by:**	yishaigalatzer

**Comment by LianwMS** [comment]
On *2014-08-05 13:19:06 UTC*, **jinfutan** commented:

The fix can start from change:
        return ODataPathSegmentTranslator.TranslateODLPathToWebAPIPath(
            path,
            model,
            unresolvedPathSegment,
            id,
            enableUriTemplateParsing,
            unresolvedPathSegment == null ?
                uriParser.ParameterAliasNodes :
            // We can't get parameter alias if ODataUnrecognizedPathException was thrown.
                new Dictionary<string, Semantic.SingleValueNode>(),
            unresolvedPathSegment == null ? null : queryString);

To 
        return ODataPathSegmentTranslator.TranslateODLPathToWebAPIPath(
            path,
            model,
            unresolvedPathSegment,
            id,
            enableUriTemplateParsing,
            uriParser.ParameterAliasNodes ,
            null);

And then check if there is other related change.

**Comment by LianwMS** [comment]
On *2014-08-05 14:04:48 UTC*, **fenzhao** commented:

The last parameter "queryString" is also useless after the change. Please remove

**Comment by challenh** [comment]
fixed by https://github.com/OData/WebApi/commit/13608a082ebf3ea70c43b988b897880a612f283c
