### ISSUE TITLE
Unbound function do not work with asp.net core

### ISSUE THREAD

**Issue by Metaphis** [OData/WebApi#1439]
Unbound functions cannot be called using asp.net core and OData. When calling a function I'm getting a 404 back.

### Assemblies affected
using the following nugets: 
    Microsoft.AspNetCore.All 2.0.6
    Microsoft.AspNetCore.OData 7.0.0-beta2

### Reproduce steps
Create a blank asp.net core project. The startup should look like this:

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddOData();
        }
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            var builder = new ODataConventionModelBuilder(app.ApplicationServices);

            builder.Function("Test").Returns<int>();

            app.UseMvc(routes =>
            {
                routes.MapODataServiceRoute("ODataRoute", "odata", builder.GetEdmModel());
            });
        }
    }

Create a matching controller:

    [Produces("application/json")]
    public class TestUnboundController : Controller
    {
        [HttpGet]
        [ODataRoute("Test")]
        public int TestFunction()
        {
            return 1;
        }
    }

run the application locally and call
`http://localhost:<port>/odata/Test`

### Expected result

The TestUnboundController method TestFunction should be called

### Actual result

an http response of 404 is returned

**Comment by Asido** [comment]
I won't go much into the problem, but I'll tell you that I implemented an unbound action yesterday and had no problems. Except I use .NET Core 2.1 RC1 and OData 7.0.0-beta2.

```csharp
public class FileController : ODataController
{
    [HttpPost]
    [ODataRoute("UploadFile")]
    public async Task<IActionResult> UploadFile(IFormFile file)
    {
        // ...
    }
}
```

```csharp
app.UseMvc(routeBuilder =>
{
    var odataBuilder = new ODataConventionModelBuilder(app.ApplicationServices);
    odataBuilder.EnableLowerCamelCase();

    var uploadHistory = builder.EntitySet<UploadHistory>(nameof(UploadHistory));
    uploadHistory.EntityType.Namespace = "File";
    uploadHistory.EntityType.HasKey(e => e.Key);

    var uploadFile = odataBuilder.Action("UploadFile");
    uploadFile.Namespace = "File";
    uploadFile.Parameter<Stream>("file");
    uploadFile.ReturnsFromEntitySet<UploadHistory>(nameof(UploadHistory));

    routeBuilder.Select().Expand().Filter().OrderBy().MaxTop(1000).Count();
    routeBuilder.MapODataServiceRoute("ODataRoute", "odata", odataBuilder.GetEdmModel());
});
```

![unbound-odata](https://user-images.githubusercontent.com/678800/40160956-91f66dbc-59af-11e8-9895-a7e21a5a0ee1.png)

**Comment by AlanWong-MS** [comment]
Can you try deriving from ODataController?

**Comment by Metaphis** [comment]
@AlanWong-MS that actually works, should I be using ODataController for all OData routes? using the asp.net core Controller class as a base works for other odata requests.

**Comment by AlanWong-MS** [comment]
If you have OData endpoints, you should stick with the ODataController for better interoperability.

**Comment by xuzhg** [comment]
@Metaphis It seems the issue resolved. Close it and please file new issue for us if you have further questions or concerns. Thank for your input.

**Comment by binuedwin** [comment]
Hi,

I am trying to create odata action for file upload , but it is not working. Can u send me the full code.
