### ISSUE TITLE
Microsoft.AspNetCore.OData 7.0.0-beta2 with ASP.NET Core 2.0.6 - Plain JSON Response

### ISSUE THREAD

**Issue by adeelsheikh** [OData/WebApi#1442]
*I have an ASP.NET Core 2 (version 2.0.6) project and I am trying to expose OData endpoint using Microsoft.AspNetCore.OData library. I am facing a weird issue that the response I am getting is plain JSON. It does not include either `@odata.context` property or `value` property. I simply returns me object / collection like ASP.NET Web API.*

### ASP.NET Core Configuration

        
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddOData();
            services.AddODataQueryFilter();

            services.AddDbContext<AppDbContext>(options =>
            {
                options.UseSqlServer("ConnectionString");
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            var modelBuilder = new ODataConventionModelBuilder(app.ApplicationServices);
            modelBuilder.EntitySet<Employee>(nameof(AppDbContext.Employees));

            app.UseMvc(routeBuilder =>
            {
                routeBuilder.MapODataServiceRoute("ODataRoute", "odata", modelBuilder.GetEdmModel());
                routeBuilder.Count().Filter().OrderBy().Expand().Select().MaxTop(null);
                routeBuilder.EnableDependencyInjection();
            });
        }

### OData Controller

   
 [Route("odata/[controller]")]
    public class EmployeesController : ODataController
    {
        private readonly AppDbContext _context;

        public EmployeesController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        [EnableQuery]
        public IActionResult Get()
        {
            return Ok(_context.Employees.AsQueryable());
        }
    }

### DB Context

    
public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {
        }

        public DbSet<Employee> Employees { get; set; }
    }

### Entity Class

    
[Table("Employee", Schema = "common")]
    public class Employee
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Email { get; set; }

        public string Department { get; set; }

        public string BusinessUnit { get; set; }
    }

### Expected result

*I am expecting to receive collection in `value` property along with `@odata.context` property.*

### Actual result

*I am receiving plain JSON collection.*

**Comment by xuzhg** [comment]
@adeelsheikh 

Please:
1. remove `routeBuilder.EnableDependencyInjection();` 
2. remove `[Route("odata/[controller]")]` 

you will get the odata payload. 

Reason is that: `[Route(...)]` is web api routing attribute. OData uses convention routing or attribute routing decorated by `[ODataRoute(...)]`.

**Comment by xuzhg** [comment]
close it and please re-open it or file new issue if you have further concern or question. Thanks your input.

**Comment by adeelsheikh** [comment]
Thanks @xuzhg. That was it 👍
