### ISSUE TITLE
[feature/netcore] Broken with .NET Core 2.1

### ISSUE THREAD

**Issue by gordon-matt** [OData/WebApi#1447]
When using .NET Core 2.1, OData does not return the expected response. For instance, when making a standard Get request to pass `ODataQueryOptions<TEntity>` for querying against an `IQueryable<T>`, it simply returns a JSON array instead of the expected response with `@odata.count`, the `value` property and metadata. Will this be an easy fix? When can we expect it to be working? Thanks.

**Comment by AlanWong-MS** [comment]
@gordon-matt, can you please provide more info regarding what your metadata looks like and a code sample of your controller?

**Comment by gordon-matt** [comment]
@AlanWong-MS OK I've updated my [OData_Test](https://github.com/gordon-matt/OData_Test) project for you. Checkout branch **feature/SDK2_1** and go to this URL: https://localhost:44367/odata/RegionApi. You should see the metadata for OData, but instead all you get is an array of the records.

>NOTE: Before running it, change the connection string in **appsettings.json** and run the **Update-Database** command in Package Manager Console to create the db.

**Comment by gordon-matt** [comment]
Any idea when this can be fixed? There are features in 2.1 that I'd like to make use of, but I can't upgrade until this issue with OData is fixed.

**Comment by AlanWong-MS** [comment]
We don't have a fix estimate at this moment but we're currently reviewing bugs to determine whether we'll be able to fix them for the GA release of WebAPI 7.0. Please stay tuned.

**Comment by xuzhg** [comment]
@gordon-matt I tested your code.

If I change the `Get` method in your `GenericODataController.cs` as:

```C#public virtual IActionResult Get(ODataQueryOptions<TEntity> options)
        {
            options.Validate(new ODataValidationSettings()
            {
                AllowedQueryOptions = AllowedQueryOptions.All
            });

            var connection = GetDisposableConnection();
            var query = connection.Query();
            query = ApplyMandatoryFilter(query);
            var results = options.ApplyTo(query);
            return Ok(results);
        }
```
I will get the following result for the uri: https://localhost:44367/odata/RegionApi

![image](https://user-images.githubusercontent.com/9426627/41438913-bbdf5fb4-6fdd-11e8-9026-4b88313e2312.png)

**Comment by gordon-matt** [comment]
Thanks, @xuzhg , but it seems it's nothing to do with `ToHashSet`. After all, that was working perfectly fine in .NET Core 2.0. It seems the following works just as well:

```
return Ok((results as IQueryable<TEntity>).ToHashSet());
```

So, we have to return an `OkObjectResult` now - where before we could just return any `IEnumerable` directly. It's a breaking change, but it should be easy to fix in all my code - especially since most of it uses the generic controller. If this breaking change is intentional, please feel free to go ahead and close this issue... but it may be a good idea to announce this change somewhere.

**Comment by gordon-matt** [comment]
Another breaking change seems to be with returning `SingleResult` as well. Example from my **GenericODataController**:

```
public virtual async Task<SingleResult<TEntity>> Get([FromODataUri] TKey key)
{
	if (!await AuthorizeAsync(ReadPermission))
	{
		return SingleResult.Create(Enumerable.Empty<TEntity>().AsQueryable());
	}

	var entity = await Repository.FindOneAsync(key);

	// TODO: CheckPermission(ReadPermission) is getting done twice.. once above, and once in CanViewEntity(). Unnecessary... see if this can be modified
	if (!await CanViewEntity(entity))
	{
		return SingleResult.Create(Enumerable.Empty<TEntity>().AsQueryable());
	}

	return SingleResult.Create(new[] { entity }.AsQueryable());
}
```

The JSON is now serialized with camel casing. This is probably a good thing actually, but it's going to be a nuisance to fix, because I will need to fix 100s of lines of code in my JavaScript (huge project). SO it's quite a big breaking change there. 2 questions:

1. Is there some option I can set somewhere to change the json serializer settings for OData to not use camel case?
2. Any more surprising changes like this?

**Comment by gordon-matt** [comment]
One more broken thing: `PUT` is not longer working. `POST` still binds the model fine, but with `PUT`, the update comes through as null (not binding the model for some reason). You can see this in my other project here: https://github.com/gordon-matt/Extenso/tree/develop. Checkout the develop branch and run the following demo project: **Demo.Extenso.AspNetCore.Mvc.OData**. Just click the OData page in the nav bar and you will see a Kendo Grid. Try update one of the records and see what happens.

**Comment by xuzhg** [comment]
@gordon-matt OData doesn't use camel case by default except you enable camel case supporting. I tested it that OData formatter can't be selected again for your `Get(TKey key)`. 

If I change it to:
```C#
[EnableQuery]
        public virtual async Task<IActionResult> Get([FromODataUri] TKey key)
        {
            var entity = await Service.FindOneAsync(key);

            // TODO: CheckPermission(ReadPermission) is getting done twice.. once above, and once in CanViewEntity(). Unnecessary... see if this can be modified
            if (!CanViewEntity(entity))
            {
                return NotFound();
        //        return SingleResult.Create(Enumerable.Empty<TEntity>().AsQueryable());
            }

         //   return SingleResult.Create(new[] { entity }.AsQueryable());
            return Ok(entity);
        }
```

it can give me 
![image](https://user-images.githubusercontent.com/9426627/41445447-73b34248-6ffe-11e8-93be-ff72e901bc3a.png)

**Comment by xuzhg** [comment]
@gordon-matt Close it. Please file new issue or reopen it if you have any other further concerns.

**Comment by gordon-matt** [comment]
@xuzhg You haven't yet addressed [this comment](https://github.com/OData/WebApi/issues/1447#issuecomment-397483456) about PUT not working anymore. It's still related to this same issue - because it was working fine in 2.0 and now it's not working in 2.1

**Comment by gordon-matt** [comment]
Nevermind - PUT seems to be working now. Maybe because I updated to the latest nightly version. Not sure. Anyway, no longer a problem. Thanks.

**Comment by xuzhg** [comment]
@gordon-matt Never mind. Please feel free to file new issue for us if you have further concerns. Thanks.

**Comment by davidmorissette** [comment]
I noticed that returning a "async Task<IQueryable<xyz>>" instead of a "IQueryable<xyz>" produces that behavior.
