### ISSUE TITLE
Error in DbTransaction.Commit when using $select and/or $expand on a Single Entity

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#145]
I would consistently get an exception being thrown on the commit of a database
transaction when using OData version 4 with WebApi and when querying a single
entity by primary key but only when using the $select and/or $expand query
parameters.  
  
Note, after debugging the source code in the project System.Web.Http.OData for
a good 1/2 day I found the problem. Will do a pull request with the fix.  
  
To ensure every WebAPI call was contained within a database transaction, I
created my own WebApi ActionFilter called "UnitOfWorkActionFilter". On
"OnActionExecuting" would open a database connection and begin a database
transaction. On "OnActionExecuted" would commit or rollback depending if any
exception was thrown during the call. This has been working great for a long
time to ensure data consistency with my REST API WebApi services by ensuring
every WebApi call was withing a database transaction and I did not have to add
the database transactions manually in every API call.  
  
Recently I added OData version 4 to the services for a test drive. Worked
great except for the case of a GET call to get a single entity with the
[EnableQuery] attribute applied but only when $select and/or $expand were used
as query parameters. There in the database commit as described above I would
get the following error:  

    
    
    http://local.proxcontent.com/odata/Users(1)?$expand=devices&$select=userId,userName

Controller Snippet  

    
    
            [EnableQuery]
            [ODataRoute("({key})")]
            public Task<IHttpActionResult> GetUser([FromODataUri]long key)
            {
                return Task.Factory.StartNew<IHttpActionResult>(() =>
                    {
                        var exists = this.UnitOfWork.ExistsByKey<User, long>(key);
                        if (exists == false)
                        {
                            var error = new ODataError
                            {
                                ErrorCode = "EntityNotFound",
                                Message = String.Format("User [key={0}] not found.", key)
                            };
                            return this.Content(HttpStatusCode.NotFound, error);
                        }
    
                        var singleResult = SingleResult.Create(this.UnitOfWork.AsQueryable<User>().Where(x => x.UserId == key));
                        return this.Content(HttpStatusCode.OK, singleResult);
                    });
            }
    

Summary  
_ Outer Exception Message: The underlying provider failed on Commit.  
Outer Exception Type: System.Data.Entity.Core.EntityException  
  
Inner Exception Message: There is already an open DataReader associated with
this Command which must be closed first.  
Inner Exception Type: System.InvalidOperationException  _  
  
Details  

    
    
    {
      "error":{
        "code":"","message":"An error has occurred.","innererror":{
          "message":"The underlying provider failed on Commit.","type":"System.Data.Entity.Core.EntityException","stacktrace":"   at System.Data.Entity.Core.EntityClient.EntityTransaction.Commit()\r\n   at Acme.Data.EntityFramework.UnitOfWork.CommitTransaction() in c:\\Examples\\Acme\\Source\\Acme.Data.EntityFramework\\UnitOfWork.cs:line 138\r\n   at Acme.ProxContent.ApiServer.UnitOfWorkActionFilter.OnActionExecuted(HttpActionExecutedContext actionExecutedContext) in c:\\Examples\\Acme\\Source\\Acme.ProxContent.ApiServer\\App_Start\\UnitOfWorkActionFilter.cs:line 45\r\n   at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutedAsync(HttpActionExecutedContext actionExecutedContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.Tracers.ActionFilterAttributeTracer.<>c__DisplayClass4.<<OnActionExecutedAsyncCore>b__1>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.Tracers.HttpControllerTracer.<ExecuteAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()","internalexception":{
            "message":"There is already an open DataReader associated with this Command which must be closed first.","type":"System.InvalidOperationException","stacktrace":"   at System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)\r\n   at System.Data.SqlClient.SqlInternalTransaction.Commit()\r\n   at System.Data.SqlClient.SqlTransaction.Commit()\r\n   at System.Data.Entity.Infrastructure.Interception.DbTransactionDispatcher.<Commit>b__c(DbTransaction t, DbTransactionInterceptionContext c)\r\n   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)\r\n   at System.Data.Entity.Infrastructure.Interception.DbTransactionDispatcher.Commit(DbTransaction transaction, DbInterceptionContext interceptionContext)\r\n   at System.Data.Entity.Core.EntityClient.EntityTransaction.Commit()"
          }
        }
      }
    }

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2097](http://aspnetwebstack.codeplex.com/workitem/2097)
**Status:**	Resolved
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Aug 7, 2014 at 2:45 AM
**Reported by:**	smcdonald68
**Updated on:**	Dec 10, 2014 at 12:31 AM
**Updated by:**	yishaigalatzer

**Comment by LianwMS** [comment]
On *2014-08-07 11:15:54 UTC*, **yishaigalatzer** commented:

PR - 
https://aspnetwebstack.codeplex.com/SourceControl/network/forks/smcdonald68/2097/contribution/7253

**Comment by LianwMS** [comment]
On *2014-08-21 14:41:24 UTC*, **azhou** commented:

We will get it into 5.4 once CLA is approved.

**Comment by LianwMS** [comment]
On *2014-09-25 07:51:05 UTC*, **dougbu** commented:

Taking this one as I track reviewing this contribution, adding tests, and getting both into 5.4.

**Comment by LianwMS** [comment]
On *2014-10-01 02:43:07 UTC*, **dougbu** commented:

Fixed with commits 7ef360ea619ff4dd437096cab7e980c2b9d2c023 and d24a9b00c9b7c28fec1796755259cacac5b7d8f4

**Comment by LianwMS** [comment]
On *2014-10-01 02:45:25 UTC*, **dougbu** commented:

Andrew, please have someone on your team confirm this fix.

**Comment by congysu** [comment]
This fix seemed already in v5.3.1
