### ISSUE TITLE
Add IEEE754Compatible to input\output ODataFormatters supported media types

### ISSUE THREAD

**Issue by maximpashuk** [OData/WebApi#1460]
I using Microsoft.AspNetCore.OData 7.0.0-beta4

If you take a look at 
[ODataInputFormatterFactory.cs](https://github.com/OData/WebApi/blob/f9d10191efcb13fee7f995fa4ec2188860d8c6fd/src/Microsoft.AspNetCore.OData/Formatter/ODataInputFormatterFactory.cs#L59)
[ODataOutputFormatterFactory.cs](https://github.com/OData/WebApi/blob/f9d10191efcb13fee7f995fa4ec2188860d8c6fd/src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatterFactory.cs#L71)

You will see that header media type parameter "IEEE754Compatible" not described at all.

But I know that this parameter exist and works fine, allowing me to format int64 as json string.
I tested it using postman.

Can you please add media types also with parameter IEEE754Compatible, so this parameter will be documented in swagger, (it using IApiRequestFormatMetadataProvider.GetSupportedContentTypes)

P.S. My issue has some indirect relation with issue #1177.
Workaround described in that issue suggest to add at least one SupportedMediaType in ODataInputFormatterFactory.CreateRawValue\ODataOutputFormatterFactory.CreateRawValue formatters.
Possible these two can be done in one shot.

**Comment by biaol-odata** [comment]
@maximpashuk The convention in WebApi and ODL has been providing the permutation of parameter values for content-type header, including the  parameter. ODL implementation includes the odata.streaming and odata.IEEE754Compatible as parameter same way as here.  
This is what is done in #1495. We need to have  further discuss whether we should make the list more concise in WebApi. See discussion [here](https://github.com/OData/WebApi/pull/1495).

**Comment by biaol-odata** [comment]
The issue reported [here](https://github.com/OData/WebApi/issues/1177#issuecomment-353738261) is due to empty supported content type.
Looking at AspNetCore.Mvc.Core's implementation related to to the [GetSupportedContentTypes](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Formatters/InputFormatter.cs#L127), I believe that the InputFormatter is required to have the complete combination of supported parameters in order to support all forms of content-type headers that are intended to be supported. Otherwise, empty list after attempted match would result in System.InvalidOperationException.

**Comment by julealgon** [comment]
Folks, what's the latest on this? I'm assuming this would take care of #1177 / #1176 related to Swagger API documentation generation.

BTW, I'm wondering why the issues above were closed. I just hit the same issue on my side so they are still very well problems that need to be fixed.

**Comment by ckuetbach** [comment]
Will this issue enable handling Json with MediaType "application/json;IEEE754Compatible=true"? 
Right now, it seems, that serializing integer or decimals as strings is not possible. Or is there another Issue?

I thought this commit enabled this feature: https://github.com/OData/odata.net/commit/e0e628a495942fb3b6b8acfa62ddbf75d24a1ece
