### ISSUE TITLE
ODataRoute sample in samples/AspNetCoreODataSample

### ISSUE THREAD

**Issue by Mhirji** [OData/WebApi#1464]
Regarding the samples/AspNetCoreODataSample.Web project, would it be possible to update it with the latest bits (Beta4) and dotnet 2.1.  I am specifically looking for an example which the ODataRoute decorator because for some reason I am not able to wire it up correctly; keep getting a 404.  When changing ODataRoute to Route, I get a response, but its a json array.  This may have to do with #1447 but am not sure.

Many thanks!!

**Comment by Mhirji** [comment]
Forgot to mention, that I get a response with Route only if keeping EnableDependencyInjection(); after MapODataServiceRoute(xx,xx,model).  Otherwise I get InvalidOperationException: Cannot find the services container for the non-OData route.

**Comment by xuzhg** [comment]
@Mhirji Thanks for feedback. May I have your requirement/usage to update to 2.1.

By the way, the samles/AspNetCoreODataSample.Web project is targeting the Microsoft.AspNetCore.OData project reference, which in turn is the latest codes.


again by the way, if you are looking for the dotnet 2.1 updating. You can refer to my testing project at: 
https://github.com/xuzhg/WebApiSample/tree/master/AspNetCore

Please feel free to clone/build/run and give me some feedback if you have any concerns and questions.
