### ISSUE TITLE
Odata request by Guid not working

### ISSUE THREAD

**Issue by volgyesitamas90** [OData/WebApi#1468]
*Short summary (3-5 sentences) describing the issue.*

GET and POST  request are working fine, but if I need 
to find an item by Guid, it does not work. 

*Which assemblies and versions are known to be affected e.g. OData WebApi lib 6.1.0

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

The query for a get request looks like this:

{host}/odata/Foo(guid'0472fdea-cc5a-40d6-a66c-980ca16cceb1')

*What would happen if there wasn't a bug.*

JSON response:
[
{
"CountryCode": "TL",
"Name": "Timor-Leste",
"Partners": null,
"CountryBindId": "7ad792a2-1689-47aa-bb09-2bb5eb263498",
"CountryBind": null,
"ObjectState": 0,
"Id": "beb8ab00-86e2-47d6-82f7-0050e07c4146",
"Status": 1,
"ModifiedDate": "2017-02-15T15:53:41.403"
}
]

### Actual result

*What is actually happening.*

For GET, it says:
{"$id": "1","Message": "No HTTP resource was found that matches the request URI 'http://localhost:2479/odata/Container(guid'ac1f1c4c-4612-4dbe-bb0d-a8e86549b6dd')'.","MessageDetail": "No type was found that matches the controller named 'Container(guid'ac1f1c4c-4612-4dbe-bb0d-a8e86549b6dd')'."}

The PUT gives 404 Not Found error.

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

The controller: 

    public class FooController : ODataController
    {
        private FooServiceContext db = new FooServiceContext();

        // GET: odata/Countries(5)
        [System.Web.Http.HttpGet]
        [Route("Foo({key})")]
        public IHttpActionResult Get([FromODataUri] Guid id)
        {
        return Ok(db.Foos.Where(foo => foo.Id == id));
        }

ODataconfig:

            var modelBuilder = new ODataConventionModelBuilder();
            modelBuilder.EntitySet<Foo>("Foo");
            modelBuilder.GetEdmModel();
            config.Routes.MapODataServiceRoute("OData", "odata", modelBuilder.GetEdmModel());

            // enable query options for all properties
            var queryableAttribute = new ControlledQueryableAttribute();         
            config.EnableQuerySupport(queryableAttribute);

WebapiConfig:

            // Web API configuration and services
            config.MapHttpAttributeRoutes();

            // Web API routes
            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );

            // Web API routes
            config.Routes.MapHttpRoute(
                name: "DefaultApiAndAction",
                routeTemplate: "api/{controller}/{action}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );

            // Web API OData routes
            config.Routes.MapHttpRoute(
                name: "Api for OData",
                routeTemplate: "odata/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );

            ODataConfig.Register(config);

**Comment by xuzhg** [comment]
@volgyesitamas90 You are mix-using Web API and Web API OData.

1. you add Web API OData routes MapHttpRoute, meantime, you call MapODataServiceRoute. Each route will pick up in their register order to do routing.

2.  [Route] is web api routing attribute, OData use [ODataRoute].

3.  your method parameter is `[FromODataUri] Guid id`. `id` here is routed using route template `odata/{controller}/{id}`. Meantime, you also use [Route(...{key})]. 

4. {host}/odata/Foo(guid'0472fdea-cc5a-40d6-a66c-980ca16cceb1') is OData spec v3 syntax.  OData WebApi lib 6.1.0 is .NET implementation about OData v4 spec. 

So, would you please take a quick look our [tutorial](http://odata.github.io/WebApi/#01-02-getting-started). I don't think it's time consume, but it can help you to understand how to implement a OData service.  

Please let me know any other questions. Thanks.
