### ISSUE TITLE
How can I get a count of filtered results before any top/paging is applied?

### ISSUE THREAD

**Issue by freeranger** [OData/WebApi#1487]
I am accepting OData queries but not using the EDM and not returning OData formatted results - just a collection of results that match the supplied OData filter, top and skip options.

I would like to return the count of all items matching the filter, which I believe is what $count would do if we were using ODataController(?) as well as a count of items after top/skip have been applied.

Currently the only solution I have found is to apply the filter only and then apply the entire ODataQueryOptions since it does not seem to be possible to create a new ODataQueryOptions using values from an existing one.

Our code looks a bit like this:
```
public static IQueryable<TModel> Filter<TModel>(this IQueryable<TModel> list, ODataQueryOptions<TModel> options)
{
    var totalCount = ((IQueryable<TModel>)options.Filter.ApplyTo(list, new ODataQuerySettings()).Count;
    var filtered = (IQueryable<TModel>)options.ApplyTo(list);
    var filteredCount = filtered.Count();
    return filtered;
}
```

I am concerned that applying the filter twice could have an unexpected side effect or potentially have a performance impact.  
Is there a nicer way to achieve the same result?
I originally thought of creating a new ODataQueryOptions using everything except the filter but that is not possible because there is no suitable public constructor.

### Assemblies affected

Microsoft.AspNetCore.OData 7.0.0.20307

**Comment by xuzhg** [comment]
@freeranger maybe you can skip/ignore the filter clause after applying that to avoid applying twice.

**Comment by freeranger** [comment]
@xuzhg How can I do that?  I can’t create a new ODataqueryOptions containing everything except the filter, which is what I would like to do, but there is no public constructor I can use

**Comment by xuzhg** [comment]
@freeranger http://odata.github.io/WebApi/#04-16-ignore-query-option maybe help to you.

**Comment by freeranger** [comment]
Awesome, thanks!

**Comment by nonbob** [comment]
> @freeranger http://odata.github.io/WebApi/#04-16-ignore-query-option maybe help to you.

For those arriving late (like me): that link is now gone.  You can find the same content now in the [archive](https://web.archive.org/web/20190520110249/http://odata.github.io/WebApi/#04-16-ignore-query-option) or [here](https://docs.microsoft.com/en-us/odata/webapi/ignore-query-option) or [here](https://github.com/MicrosoftDocs/OData-docs/blob/master/Odata-docs/webapi/ignore-query-option.md)

The example is very apt (and fixes precisely the problem I was having).  Applying $filter or $orderby twice may be inefficient (and drastically so with large numbers of rows), but applying $skip twice is just plain broken.
