### ISSUE TITLE
Add support for optional parameters to WebAPI OData stack

### ISSUE THREAD

**Issue by mikepizzo** [OData/WebApi#1488]
*We have added support for optional parameters to OData Library.  This work item is to track exposing that support through the WebAPI OData stack.*

### Assemblies affected

OData WebApi lib 6.x

### Reproduce steps

See https://github.com/OData/odata.net/issues/782 for a good example.

### Additional detail

WebAPI OData 6.x and before has an "Optional" property on a parameter; however, it really means nullable.  In WebAPI OData 7.x we renamed this property to "Nullable" so that we could introduce an actual optional property.

**Comment by DavTheSuave** [comment]
Any clue how far off into the horizon this is? I don't need it for my current project but it would be really nice to have.

**Comment by xuzhg** [comment]
@DavTheSuave We implemented it in the latest [7.0.1](https://www.nuget.org/packages/Microsoft.AspNetCore.OData/7.0.1) version. Thanks.
