### ISSUE TITLE
ASP.NET Core 2.1 - Task-returning methods do not return OData envelope

### ISSUE THREAD

**Issue by aelij** [OData/WebApi#1498]
After upgrading to ASP.NET Core 2.1 (from 2.0), the OData endpoints do not return the envelope for task-returning methods.

### Assemblies affected

* OData WebApi 7 Beta 4

### Reproduce steps

* Create a task-returning method in an OData controller:
```csharp
[HttpGet, ODataRoute("X")]
public Task<X> GetX() { return ...; }
```

### Expected result
Returned JSON:

```js
{
    "@odata.context": "http://localhost:30006/api/odata/$metadata#Microsoft.Foo.Server.Provider.Model.X",
    "Field1": "xxxxx",
    "Field2": "xxxxxx"
}
```

### Actual result

```js
{
    "Field1": "xxxxx",
    "Field2": "xxxxxx"
}
```

**Comment by aelij** [comment]
cc: @davidmorissette

**Comment by aelij** [comment]
FYI I've verified this is fixed in ASP.NET 2.1.1: https://github.com/aspnet/Mvc/pull/7834

**Comment by xuzhg** [comment]
@aelij Thank for your information. However, i think we should:
1. do what i have done in the PR #1501 to make sure it can work in 2.0 and 2.1 version.
2. upgrade to v2.1?

**Comment by JohnGalt1717** [comment]
I'm using .NET Core 2.1.2 (latest) and the release version of oData for .NET core.

Using the documentation, I've set it up but the output is always simple json.

Adding these mvc options:  

options.RespectBrowserAcceptHeader = true;
options.ReturnHttpNotAcceptable = true;

results in a 406 error when requesting odata formats as if it isn't registering the formatters properly.
