### ISSUE TITLE
Consider automated server paging based on ResultLimit with next page links that use $skiptoken instead of $skip

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#15]
Next page links right now:  

[ http://localhost/Customers?$skip=10 Skiptoken is more performant and robust
](http://localhost/Customers?$skip=10

Skiptoken is more performant and robust) .  
## Work Item Details

**Original CodePlex Issue:**    [Issue 500](http://aspnetwebstack.codeplex.com/workitem/500)
**Status:** Active
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Oct 3, 2012 at 11:54 PM
**Reported by:**    youssefm
**Updated on:** Nov 24, 2014 at 11:54 PM
**Updated by:** goldenfire6

**Comment by chuanboz** [comment]
Any reason this is marked as low priority?
