### ISSUE TITLE
DataMember names don't work in filter queries

### ISSUE THREAD

**Issue by trampster** [OData/WebApi#1507]
When using a DataContract and DataMember to rename a property (to add a space) The result is serialized correctly with the rename, however the filter ?$filter='name with space' eq 'value' doesn't work (finds zero matches). I thought maybe it wasn't considering the rename so tried without the rename, this produces the following exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: Unknown LINQ expression of type 'Index'.

### Assemblies affected
I'm using the Microsoft.AspNet.ODATA 6.1.0 package from nuget

### Reproduce steps

- Create a ODATA entity with using DataContract and DataMember with name to add a space to the name
- Query the endpoint -> notice that the json contains the property with the new name
- using a ?$filter='with space' eq 'value' -> notice no matches when there should be
- try using ?$filter=withspace eq 'value' -> NotSupportedException

### Expected result

The results would be filtered as expected.

### Actual result

Doesn't find matches (empty result)

**Comment by xuzhg** [comment]
@trampster DataContract/DataMember works in correct renaming scenario. 

for example:
```C#
[DataContract]
public class Person
{
    [DataMember(Name = "id")]
    public int Id { get; set; }

    [DataMember(Name = "myName")]
    public string MyName { get; set; }
}
```
Then, i can do `http://localhost:5000/p/People?$filter=myName eq 'Peter'`

However, if you add a space into the renaming, for example:
```C#
[DataMember(Name = "my Name")] // a while space between my & Name.
public string MyName { get; set; }
```

Then, It's not acceptable when file a GET request: `http://localhost:5000/p/People?$filter=my Name eq 'Peter'`
So, Do not rename a property to violate the identifier naming convention as follows:

_15.2 Simple Identifier
A simple identifier is a Unicode character sequence with the following restrictions:
It consists of at least one and at most 128 Unicode characters. 
The first character MUST be the underscore character (U+005F) or any character in the Unicode category “Letter (L)” or “Letter number (Nl)”.
The remaining characters MUST be the underscore character (U+005F) or any character in the Unicode category “Letter (L)”, “Letter number (Nl)”, “Decimal number (Nd)”, “Non-spacing mark (Mn)”, “Combining spacing mark (Mc)”, “Connector punctuation (Pc)”, and “Other, format (Cf)”.
Non-normatively speaking it starts with a letter or underscore, followed by at most 127 letters, underscores or digits._
