### ISSUE TITLE
The ValidateAllNode and ValidateAnyNode methods in the class FilterQueryValidator should check if All/Any is allowed.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#151]
The 2 methods do not check if any/all is allowed. It should check it just as
what the below method does:  

    
    
        private static void ValidateFunction(string functionName, ODataValidationSettings settings)
        {
            AllowedFunctions convertedFunction = ToODataFunction(functionName);
            if ((settings.AllowedFunctions & convertedFunction) != convertedFunction)
            {
                // this means the given function is not allowed
                throw new ODataException(Error.Format(SRResources.NotAllowedFunction, functionName, "AllowedFunctions"));
            }
        }
    

This applies both to OData v3 and v4.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2125](http://aspnetwebstack.codeplex.com/workitem/2125)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Sep 1, 2014 at 4:15 AM
**Reported by:**	jinfutan
**Updated on:**	Sep 2, 2014 at 1:08 AM
**Updated by:**	azhou

**Comment by xuzhg** [comment]
Already added. See. https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Query/Validators/FilterQueryValidator.cs#L713-L718

Thanks.
