### ISSUE TITLE
Case mismatch on select/expand results in non-OData route

### ISSUE THREAD

**Issue by mitchdowd** [OData/WebApi#1515]
Adding OData query handling to an existing controller results in non-camelCase resulting property names when $select or $expand is used.  Ideally the results should be consistent.

### Assemblies affected

Currently using Microsoft.AspNetCore.OData v7.0.0

### Reproduce steps

Have an existing controller with a non-OData route.
```csharp
    [Route("api/values")]
    public class ValuesController : ODataController
    {
        private ValuesRepository _repo;

        public ValuesController(ValuesRepository repo)
        {
            _repo = repo;
        }

        [HttpGet]
        [EnableQuery]
        public IQueryable<Value> Get()
        {
            return _repo.Get();
        }
    }
```
Configure the OData EDM route, and also enable dependency injection for the existing controller route.
```csharp
    public void Configure(IApplicationBuilder app)
    {
        app.UseMvc(routeBuilder =>
        {
            var modelBuilder = new ODataConventionModelBuilder();

            // EDM builder for the /odata route.
            modelBuilder.EnableLowerCamelCase()
                .EntitySet<Value>("Values")
                    .EntityType
                    .Select();

            routeBuilder.MapODataServiceRoute("ODataRoute", "odata", modelBuilder.GetEdmModel());

            // Dependency injection for the /api route.
            routeBuilder
                .Select()
                .EnableDependencyInjection();
        });
    }
```
Access the resulting API call from:
 * http://localhost:8001/api/values (gives correct camelCasing)
 * http://localhost:8001/odata/values?$select=id (gives correct camelCasing)
 * http://localhost:8001/api/values?$select=id (gives incorrect PascalCasing)

### Expected result

I would expect consistent case-handling for both /api and /odata routes.  This would allow OData query parameters to be handled on existing APIs without breaking the resulting response packet.

### Actual result

While /odata/values?$select=id gives a correct response like `[ { "id": 1 } ]`, using the /api route will give `[ { "Id": 1 } ]`.

### Additional detail

Example standalone ASP.NET Core project: [ODataCamelCase.zip](https://github.com/OData/WebApi/files/2155768/ODataCamelCase.zip)

**Comment by mitchdowd** [comment]
Closing.  Explicitly setting JSON `SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver()` fixes it up.

**Comment by ayanmitra2021** [comment]
Any ideas on how the same thing can be achieved on a NestJS based Node api

**Comment by yoHasse** [comment]
This helped me which i found at:  
[GitHub OData: camel_case_scenarios.md](https://github.com/OData/AspNetCoreOData/blob/main/docs/camel_case_scenarios.md)

This is what resolved it for me:


```

builder.Services.AddControllers()
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.DictionaryKeyPolicy = JsonNamingPolicy.CamelCase;
        options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
    });

```
