### ISSUE TITLE
Getting error 404 when calling /odata

### ISSUE THREAD

**Issue by sorcer1** [OData/WebApi#1517]
When i calling my localhost project (https://localhost:88/odata) i get a 404 error.

### Assemblies affected

I'm using Microsoft.AspNetCore.OData 7.0

### Reproduce steps

Configuring :
 ```
  var model = ODataModelBuilder.GetEdmModel(app.ApplicationServices);
            app.UseMvc(builder =>
            {
                builder.Filter().Expand().Select().Count().OrderBy().MaxTop(null);
                builder.MapODataServiceRoute("odata", "odata", model);
            });
```

`services.AddOData();`

### Expected result

odata metadata

### Actual result

404 status code

### Additional detail
My controller inherits form different base classes :

My controller :
    ```
    public class ProductsController : GenericController<Products, IService<Products>>
    {
        public ProductsController(IService<Products> service) : base(service)
        {
        }

        [EnableQuery]
        public IQueryable<Products> GetProducts()
        {
            return service.Queryable();
        }
    }

    [ApiVersion("1")]
    [Route("api/{version:apiVersion}/[controller]")]
     public class GenericController<TEntityId, TService> : BaseResponsesController
        where TEntityId : IEntityId
        where TService : IService<TEntityId>
    {
        protected readonly TService service;

        public GenericController(TService service) : base()
        {
            this.service = service;
        }

        // Some stuff
    }

   public class BaseResponsesController : BaseController
    {
        public BaseResponsesController(): base() { }
        // Some stuff
   }

     public class BaseController : Controller
    {
        public BaseController()
        {
        }

    // Some stuff
    }
```

**Comment by xuzhg** [comment]
@sorcer1 

To get data metadata doesn't need any other controller.  Can you share us your startup.cs?

**Comment by sorcer1** [comment]
Hi,
This is my Startup.cs

[Startup.zip](https://github.com/OData/WebApi/files/2175421/Startup.zip)

**Comment by xuzhg** [comment]
@sorcer1 It seems you call the "AddOData()" and Map the OData route in your "Startup.cs". Would you please debug it at your side to verify its routing to the "OData" route? Or, would you please share a repro for me to debug?

**Comment by sorcer1** [comment]
@xuzhg Hi, this is the trace from ASP.NET Core Web Server Output.
As you can see the endpoint is called, but i get an error 404.

> [10:58:07 INF] Request starting HTTP/1.1 GET http://localhost:88/OData  
> [10:58:07 DBG] GET https://localhost:88/OData
> [10:58:07 DBG] Cache-Control=max-age=0
> [10:58:07 DBG] Connection=Keep-Alive
> [10:58:07 DBG] Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
> [10:58:07 DBG] Accept-Encoding=gzip, deflate, br
> [10:58:07 DBG] Accept-Language=fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,pt;q=0.6
> [10:58:07 DBG] Host=localhost:88
> [10:58:07 DBG] User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
> [10:58:07 DBG] upgrade-insecure-requests=1
> [10:58:07 DBG] dnt=1
> [10:58:07 DBG] MS-ASPNETCORE-TOKEN=1a03d258-4aee-44e9-96b4-dc09f95cc105
> [10:58:07 DBG] X-Original-Proto=http
> [10:58:07 DBG] X-Original-For=127.0.0.1:52084
> [10:58:07 DBG] Request: 
> [10:58:07 INF] Request finished in 16.436ms 404

**Comment by xuzhg** [comment]
@sorcer1 Ok. Can you please share your link for your repro?

**Comment by gathogojr** [comment]
Issue from 2018. No reaction to a request to share a repro
