### ISSUE TITLE
Microsoft.AspNet.OData 7.0.0 Has Undeclared NuGet Dependencies

### ISSUE THREAD

**Issue by commonsensesoftware** [OData/WebApi#1518]
Version 7.0.0 of the **Microsoft.AspNet.OData** package has undeclared NuGet dependencies. The offending dependency is at least **Newtonsoft.Json**, but there may be others.

For reasons that are unclear, the [source project](../blob/master/src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj#L40) references **Newtonsoft.Json 10.0.0**, but this reference is not declared in the [\*.nuspec](../blob/master/src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.Release.nuspec
).

### Assemblies affected

Microsoft.AspNet.OData 7.0.0

### Reproduce steps

```powershell
Install-Package Microsoft.AspNet.OData -Version 7.0.0
```

### Expected result

Successful compilation without warnings.

### Actual result

**MSB3277** - _Found conflicts between different versions of "Newtonsoft.Json" that could not be resolved._

### Additional detail

**Newtonsoft.Json** is a transitive dependency. It's unclear if the latest OData package actually requires a newer version of the package. If it doesn't, then the project should reference **6.0.4**, which is the lowest version required by the lowest, supported version of ASP.NET Web API. If a higher version is required, then it needs to be explicitly defined in the \*.nuspec file.

I would also **strongly** recommend converting the source project to the new _SDK_ format just like the **Microsoft.AspNetCore.OData** project. This will avoid this type of issue in the future.

**Comment by xuzhg** [comment]
@commonsensesoftware I filed a PR to downgrade the reference version. See #1519.

**Comment by commonsensesoftware** [comment]
Great! Thanks for the quick turnaround. Pending the test run, the changes looks good to me.

**Comment by xuzhg** [comment]
Merged. Thanks.
