### ISSUE TITLE
virtualPathRoot is null in GlobalConfiguration.DefaultServer.Configuration when using DefaultOdataBatchHandler with katana self-hosting scenario.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#152]
My config of Katana is:  

    
    
     public static IAppBuilder UseAdminPanel(this IAppBuilder app)
            {
                var config = new HttpConfiguration();
    
                Func<IEdmModel> getEdmModel = () =>
                {
                    var builder = new ODataConventionModelBuilder();
                    var es = builder.EntitySet<User>("User");                
                    return builder.GetEdmModel();
                };
                
                config.Routes.MapODataRoute(
                    "odata", 
                    "odata", 
                    getEdmModel(),
                    new DefaultODataBatchHandler(GlobalConfiguration.DefaultServer)
                    );
    
                app.UseWebApi(config);
    
                return app;
            }       

When using self-hosted scenario any client call to hostname/odata/$batch
resulting in 200 OK but in the body i see exception:  

    
    
    {"Message":"An error has occurred.","ExceptionMessage":"Value cannot be null.\r\nParameter name: virtualPathRoot","ExceptionType":"System.ArgumentNullException","StackTrace":"   at System.Web.Http.WebHost.Routing.HttpRequestMessageWrapper..ctor(String virtualPathRoot, HttpRequestMessage httpRequest)\r\n   at System.Web.Http.WebHost.Routing.HttpRequestMessageContextWrapper..ctor(String virtualPathRoot, HttpRequestMessage httpRequest)\r\n   at System.Web.Http.WebHost.Routing.HostedHttpRouteCollection.GetRouteData(HttpRequestMessage request)\r\n   at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Web.Http.HttpServer.<>n__FabricatedMethod9(HttpRequestMessage , CancellationToken )\r\n   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"}

and the GlobalConfiguration.DefaulServer.Configuration.VirtualPathRoot is
really null, which is not the case for IIS hosting scenario(it is "/" there).  
  
I am using theese packages  

    
    
    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="Breeze.Angular" version="1.0.0" targetFramework="net45" />
      <package id="Breeze.Angular.Directives" version="1.3.7" targetFramework="net45" />
      <package id="Breeze.Client" version="1.5.0" targetFramework="net45" />
      <package id="datajs" version="1.1.3" targetFramework="net45" />
      <package id="EntityFramework" version="6.1.1" targetFramework="net45" />
      <package id="EntityFramework.SqlServerCompact" version="6.1.1" targetFramework="net45" />
      <package id="jQuery" version="2.1.1" targetFramework="net45" />
      <package id="log4net" version="2.0.3" targetFramework="net45" />
      <package id="Microsoft.AspNet.Identity.Core" version="2.1.0" targetFramework="net45" />
      <package id="Microsoft.AspNet.Identity.EntityFramework" version="2.1.0" targetFramework="net45" />
      <package id="Microsoft.AspNet.Identity.Owin" version="2.1.0" targetFramework="net45" />
      <package id="Microsoft.AspNet.Mvc" version="5.2.2" targetFramework="net45" />
      <package id="Microsoft.AspNet.Razor" version="3.2.2" targetFramework="net45" />
      <package id="Microsoft.AspNet.SignalR.Core" version="2.1.1" targetFramework="net45" />
      <package id="Microsoft.AspNet.SignalR.JS" version="2.1.1" targetFramework="net45" />
      <package id="Microsoft.AspNet.SignalR.Owin" version="1.2.2" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebApi" version="5.2.2" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebApi.Client" version="5.2.2" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebApi.Core" version="5.2.2" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebApi.OData" version="5.2.2" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.2" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebApi.OwinSelfHost" version="5.2.2" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebApi.SelfHost" version="5.2.2" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebApi.Tracing" version="5.2.2" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.2" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebPages" version="3.2.2" targetFramework="net45" />
      <package id="Microsoft.Bcl" version="1.1.9" targetFramework="net45" />
      <package id="Microsoft.Bcl.Build" version="1.0.17-beta" targetFramework="net45" />
      <package id="Microsoft.Data.Edm" version="5.6.2" targetFramework="net45" />
      <package id="Microsoft.Data.OData" version="5.6.2" targetFramework="net45" />
      <package id="Microsoft.Net.Http" version="2.2.28" targetFramework="net45" />
      <package id="Microsoft.Owin" version="3.0.0" targetFramework="net45" />
      <package id="Microsoft.Owin.Diagnostics" version="3.0.0" targetFramework="net45" />
      <package id="Microsoft.Owin.FileSystems" version="3.0.0" targetFramework="net45" />
      <package id="Microsoft.Owin.Host.HttpListener" version="3.0.0" targetFramework="net45" />
      <package id="Microsoft.Owin.Hosting" version="3.0.0" targetFramework="net45" />
      <package id="Microsoft.Owin.Security" version="3.0.0" targetFramework="net45" />
      <package id="Microsoft.Owin.Security.Cookies" version="3.0.0" targetFramework="net45" />
      <package id="Microsoft.Owin.Security.OAuth" version="3.0.0" targetFramework="net45" />
      <package id="Microsoft.Owin.SelfHost" version="3.0.0" targetFramework="net45" />
      <package id="Microsoft.Owin.StaticFiles" version="3.0.0" targetFramework="net45" />
      <package id="Microsoft.SqlServer.Compact" version="4.0.8876.1" targetFramework="net45" />
      <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
      <package id="Newtonsoft.Json" version="6.0.4" targetFramework="net45" />
      <package id="Owin" version="1.0" targetFramework="net45" />
      <package id="Q" version="1.0.1" targetFramework="net45" />
      <package id="System.Spatial" version="5.6.2" targetFramework="net45" />
      <package id="Unity" version="3.5.1405-prerelease" targetFramework="net45" />
    </packages>

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2127](http://aspnetwebstack.codeplex.com/workitem/2127)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Sep 3, 2014 at 3:51 PM
**Reported by:**	Yfer
**Updated on:**	Sep 11, 2014 at 11:43 PM
**Updated by:**	yishaigalatzer

**Comment by LianwMS** [comment]
On *2014-09-04 22:36:06 UTC*, **Yfer** commented:

Well, i've solved this, but the way it's done i think is not right, because i'm instancing new HttpServer instead of one in the internals of katana. Could you please give me comment or some link to documentation where i can understand the subject and the
 structure of this?:
 public static IAppBuilder UseAdminPanel(this IAppBuilder app)
        {
            var config = new HttpConfiguration();

            Func<IEdmModel> getEdmModel = () =>
            {
                var builder = new ODataConventionModelBuilder();
                var es = builder.EntitySet<User>("User");                
                return builder.GetEdmModel();
            };
            var server = new HttpServer(config); //this line new
            config.Routes.MapODataRoute(
                "odata", 
                "odata", 
                getEdmModel(),
                new DefaultODataBatchHandler(server) //i pass instantiated server
                );

            app.UseWebApi(config);

            return app;
        }

**Comment by LianwMS** [comment]
Investigate and Follow Up Later

**Comment by xuzhg** [comment]
Close it. If you have any more concern, please reopen it. Thanks.

**Comment by rahul7720** [comment]
I can still reproduce this issue with lates version of nuget packages.
Still GlobalConfiguration.DefaultServer == null in self hosted environment.
Is there any specific reason behind this?

**Comment by ysmoradi** [comment]
As far as I know, we may not use static versions of HttpServer, HttpConfiguration or GlobalHub (signalr & web API), they're based on ASP.NET pipeline. you've to instanciate HttpServer, HttpConfiguration and HubConfiguration and put them on Owin pipeline. This works on ASP.NET/IIS (Katana), Owin Self host (HttpListener), ASP.NET Core (Kestrel). I've not tested other owin/asp.net/asp.net core based servers, but there won't be a problem I think.

**Comment by heysaad** [comment]
I recently faced similar issue. The main cause of this error is following line
`appBuilder.UseWebApi(config);`
changing it to `appBuilder.UseWebApi(httpServer);` solved my issue
