### ISSUE TITLE
aspnetcoreodatasample.web does not compile

### ISSUE THREAD

**Issue by NetTecture** [OData/WebApi#1526]
Current Git (master branch Commit 4fd6ce54)

The project does not compile.

Error on my computer is:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1105	Unable to find project information for 'C:\Work\WebApi-OData\src\Microsoft.AspNetCore.OData\Microsoft.AspNetCore.OData.csproj'. The project file may be invalid or missing targets required for restore.	AspNetCoreODataSample.Web	C:\Work\WebApi-OData\samples\AspNetCoreODataSample.Web\AspNetCoreODataSample.Web.csproj	1	

This is straight from master.

NuGet Microsoft.ASpnetCore.All (2.0.5) is yello wmarket, Projects Micrsofot.ASpnetCore.Odata is yellow market.

**Comment by biaol-odata** [comment]
@NetTecture CI build on master branch shows the build is in good state. Would you please check whether [this link related to NU1105](https://stackoverflow.com/questions/47695504/error-nu1105-unable-to-find-project-information-the-project-file-may-be-invali) can help to resolve the issue on your box?

**Comment by NetTecture** [comment]
Ah, yes.

You reference a project, but it is not in the solution. The moment I add it to the solution, it works.

I try this on a current VS - 2017. 15.7.4 - this could be some feature that older versions lack? Project reference seems not to be valid unless the referenced project is also in the solution containing the referencing project.

MSBuild or othersstuff may not care - Visual Studio seems to. That would explain why Cl may work, but it fails in visual studio.

**Comment by biaol-odata** [comment]
@NetTecture yes, the sample project is contained in the WebApiOData.AspNetCore.sln, which is used to open the sample project along with aspnetcore.OData project.
