### ISSUE TITLE
[ODataV3]The mothods BindCeiling, BindFloor and BindRound in FilterBinder.cs treat nullable double as decimal

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#153]
The reason is that these methods don't handle nullable double:  

    
    
    MethodInfo round = arguments[0].Type == typeof(double) ? ClrCanonicalFunctions.RoundOfDouble : ClrCanonicalFunctions.RoundOfDecimal;

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2128](http://aspnetwebstack.codeplex.com/workitem/2128)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Sep 5, 2014 at 3:26 AM
**Reported by:**	jinfutan
**Updated on:**	Dec 10, 2014 at 12:31 AM
**Updated by:**	yishaigalatzer

**Comment by xuzhg** [comment]
Resolved:
d684a1cb7eeea4ae775ded41d5c5f70336b5f241
