### ISSUE TITLE
Expand bug on derived entities

### ISSUE THREAD

**Issue by jpiquot** [OData/WebApi#1530]
The Json response is incomplete when querying a derived object with a expand.

### Assemblies affected

OData WebApi lib 7 lastest from master branch.
.NET Core SDK 2.1.300
EF Core 2.1

### Reproduce steps
```

public class Site{
    public int Id {get;set;}
    public string Name {get;set;}
   
    [InverseProperty(nameof(Organization.Site))]
    public ICollection<Organization> Organizations {get;set;}
}
public class Organization
{
    public int Id {get;set;}
    public int SiteId {get;set;}
    public string Name {get;set;}

    [ForeignKey(nameof(SiteId))]
    public Site Site {get;set}
}
public class LegalEntity: Organization 
{
    public string LegalName {get;set;}
   ...
}

builder.EntitySet<Organization>("Organizations");
builder.EntitySet<Site>("Sites")..EntityType.HasMany(p => p.Organizations);
builder.EntitySet<LegalEntity>("LegalEntity");

```
### Expected result

> http://localhost:5000/odata/LegalEntities?$top=2&$select=Id,Name&$expand=Site($select=Name)

```
{
    "@odata.context": "http://localhost:5000/odata/$metadata#LegalEntities(Id,Name,Site(Name))",
    "value": [
        {
            "@odata.type": "#WarehouseManagement.LogisticPlatform",
            "@odata.etag": "W/\"YmluYXJ5J0FBQUFBQUFBRXEwPSc=\"",
            "Id": 1,
            "Name": "Garonor 318305 318305",
            "Site": {
                "@odata.etag": "W/\"YmluYXJ5J0FBQUFBQUFBRXFvPSc=\"",
                "Name": "Garonor 318305 318305"
            }
        },
        {
            "@odata.type": "#WarehouseManagement.LogisticPlatform",
            "@odata.etag": "W/\"YmluYXJ5J0FBQUFBQUFBRXE0PSc=\"",
            "Id": 2,
            "Name": "Maurepas 318306 318306",
            "Site": {
                "@odata.etag": "W/\"YmluYXJ5J0FBQUFBQUFBRXFzPSc=\"",
                "Name": "Maurepas 318306 318306"
            }
        }
    ]
}
```
### Actual result

> http://localhost:5000/odata/LegalEntities?$top=2&$select=Id,Name&$expand=Site($select=Name)

```
{"@odata.context":"http://localhost:5000/odata/$metadata#LegalEntities(Id,Name,Site(Name))","value":[ <- end of message
```
the data and the closing ]} are missing

### Additional detail
If I query the base class, everything is OK : 

> http://localhost:5000/odata/organizations?$top=2&$select=Id,Name&$expand=Site($select=Name)

```
{
    "@odata.context": "http://localhost:5000/odata/$metadata#Organizations(Id,Name,Site(Name))",
    "value": [
        {
            "@odata.type": "#WarehouseManagement.LogisticPlatform",
            "@odata.etag": "W/\"YmluYXJ5J0FBQUFBQUFBRXEwPSc=\"",
            "Id": 1,
            "Name": "Garonor 318305 318305",
            "Site": {
                "@odata.etag": "W/\"YmluYXJ5J0FBQUFBQUFBRXFvPSc=\"",
                "Name": "Garonor 318305 318305"
            }
        },
        {
            "@odata.type": "#WarehouseManagement.LogisticPlatform",
            "@odata.etag": "W/\"YmluYXJ5J0FBQUFBQUFBRXE0PSc=\"",
            "Id": 2,
            "Name": "Maurepas 318306 318306",
            "Site": {
                "@odata.etag": "W/\"YmluYXJ5J0FBQUFBQUFBRXFzPSc=\"",
                "Name": "Maurepas 318306 318306"
            }
        }
    ]
}

```
The error is line 129 of ODataResourceSetSerializer.cs when the foreach loop tries to get the first object from "enumerable".

  ```
         foreach (object item in enumerable)
            {
                if (item == null || item is NullEdmComplexObject)
                {
  
```
enumerable contains the expression : 
`{value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[GlobalAddressBook.LegalEntity]).OrderBy($it => $it.Id).Select(Param_0 => new SelectAllAndExpand`1() {ModelID = "46ce33e2-b068-4883-a104-3558a56860f1", Instance = Param_0, UseInstanceForProperties = True, Container = new SingleExpandedProperty`1() {Name = "Site", Value = new SelectSomeAndInheritance`1() {ModelID = "46ce33e2-b068-4883-a104-3558a56860f1", InstanceType = IIF(((Param_0 As Organization).Site Is SupplyChannel), "WarehouseManagement.SupplyChannel", "GlobalAddressBook.Site"), Container = new NamedPropertyWithNext1`1() {Name = "Name", Value = (Param_0 As Organization).Site.Name, Next0 = new AutoSelectedNamedProperty`1() {Name = "Id", Value = Convert((Param_0 As Organization).Site.Id, Nullable`1)}, Next1 = new AutoSelectedNamedProperty`1() {Name = "RowVersion", Value = (Param_0 As Organization).Site.RowVersion}}}, IsNull = (Convert((Param_0 As Organization).Site.Id, Nullable`1) == null)}}).Take(value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.Int32]).TypedProperty)}`

**Comment by jpiquot** [comment]
I think this is EF Model issue in my application. The issue can be closed.

**Comment by xuzhg** [comment]
close it. Thanks.
