### ISSUE TITLE
Trouble with routing to custom functions 

### ISSUE THREAD

**Issue by TehWardy** [OData/WebApi#1549]
Currently running **v6.1.0 of the odata framework** in my solution.

I'm having some trouble understanding routing in an api scenario where I have an app collection and I want to provide a download method on the controller for a file at a given path for example ...

> HTTP GET ~/App(2)/Download('Foo/Bar/test.txt')

As per the docs, I add to my existing working "CRUD" controller the download method ...

```
public class AppController 
{
       [ODataRoute("Download({p})")]
        public HttpResponseMessage Download([FromODataUri]int key, [FromODataUri]string p)
        {
                /// i'm trying to get this method to be called using the above url
        }
}
```

Having defined my method I have added the following in to my model ...
```
var d = Builder.EntityType<Objects.Entities.CMS.App>().Function("Download");
d.Parameter<string>("p");
d.Returns<HttpResponseMessage>();
```
... but no luck.

I've been bashing around different ideas but i figured it's time i just gave up and asked you guys how this is meant to work ? 

Clarification ...

**Expected result**
Breakpoint in my action method gets hit.

**Actual result** 
If I definde an empty debug routing convention (see below) and put a breakpoint in that after adding it to the first position in the conventions collection on app load it doesn't get hit, the framework bombs out way before even considering any routing with a "IIS 10.0 Detailed Error - 404.0 - Not Found".

Debug routing convention code:

```
 public class DebugRoutingConvention : EntitySetRoutingConvention, IODataRoutingConvention
{
    public override string SelectAction(ODataPath odataPath, HttpControllerContext context, ILookup<string, HttpActionDescriptor> actionMap)
    {
        return null;
    }
}
```

I was hoping this would at least get hit as a basic start point.

**Comment by xuzhg** [comment]
@TehWardy 

First, I would say that you don't need to add your own routing convention to route the function call. It's built in Web API OData.

Second, Your codes maybe change a little bit to work. 

1. The controller should be derived from "ODataController"
2. The controller name should be "{entitySetName}Controller"
3. `[ODataRoute("Download({p})")]` is wrong, and it can be removed.
4. You should put [HttpGet] at your method. 
5. `d.Returns<HttpResponseMessage>();` maybe to change to return any primitive type. 
6. Your request string should escape.  '/' -> '%2F'
7. ...

I create a sample project for your reference. You can find [here](https://github.com/xuzhg/WebApiSample/tree/master/v6.x/SimpleFunctionTest), please let me know any problems.

Besides, There are also a [blog](https://blogs.msdn.microsoft.com/odatateam/2014/12/08/tutorial-sample-functions-actions-in-web-api-v2-2-for-odata-v4-0-type-scenario/) that you can refer to. 

Thanks.
