### ISSUE TITLE
Add support for $search query option

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#155]
Hi,  
  
Is it possible to add the support for $search query option, as defined here :
[ http://docs.oasis-open.org/odata/odata/v4.0/os/part2-url-
conventions/odata-v4.0-os-part2-url-conventions.html#_Toc372793865
](http://docs.oasis-open.org/odata/odata/v4.0/os/part2-url-
conventions/odata-v4.0-os-part2-url-conventions.html#_Toc372793865)  
  
Thank you.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2141](http://aspnetwebstack.codeplex.com/workitem/2141)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Sep 22, 2014 at 2:02 PM
**Reported by:**	ldasilva
**Updated on:**	Sep 29, 2014 at 9:45 PM
**Updated by:**	yishaigalatzer

**Comment by LianwMS** [comment]
Xuzhg follow up

**Comment by chinadragon0515** [comment]
Same as #66 and #69

**Comment by xuzhg** [comment]
Resolved as duplicated #66. Thanks.
