### ISSUE TITLE
$batch MessageQuotas.MaxOperationsPerChangeset has no effect

### ISSUE THREAD

**Issue by OlivierDeRivoyre** [OData/WebApi#1550]
Setting the MessageQuotes in the ODataBatchHandler has no effect. If we try to do a $batch with more than 100 sub requests, we have the following error:

    ODataException: The current batch message contains too many parts. A maximum number of '100' query operations and change sets are allowed in a batch message.

To increase the default limit from 100 to 10000, I'm setting the MaxOperationsPerChangeset and MaxPartsPerBatch properties. But when I try, I still have the limit at 100. 
In my opinion, the bug is that the MessageQuotas config from the ODataBatchHandler is not used by ODataBatchReader in IncreaseBatchSize()

### Assemblies affected

WebApiOData.AspNetCore branch feature/netcore
The bug seems to be in OData.Net45 (I'm not sure to understand how the two solutions interract).

### Reproduce steps

In WebApiOData.AspNetCore branch feature/netcore, enable the $batch feature in Startup.cs:

    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        app.UseODataBatching();
        app.UseAuthentication();
        app.UseMvc(builder =>
        {
           builder.MapODataServiceRoute("odata", "odata",
              configureAction: containerBuilder => containerBuilder
                  .AddService(Microsoft.OData.ServiceLifetime.Singleton, typeof(IEdmModel),
                      sp => EdmModelBuilder.GetEdmModel())
                  .AddService(Microsoft.OData.ServiceLifetime.Singleton, typeof(IEnumerable<IODataRoutingConvention>),
                      sp => ODataRoutingConventions.CreateDefaultWithAttributeRouting("odata", builder))
                  .AddService(Microsoft.OData.ServiceLifetime.Singleton, typeof(ODataUriResolver),
                      sp => new StringAsEnumResolver())
                  .AddService(Microsoft.OData.ServiceLifetime.Singleton, typeof(ODataBatchHandler),
                      sp => {
                          var oDataBatchHandler = new DefaultODataBatchHandler();
                          oDataBatchHandler.MessageQuotas.MaxOperationsPerChangeset = 10_000;
                          oDataBatchHandler.MessageQuotas.MaxPartsPerBatch= 10_000;
                          return oDataBatchHandler;
                      }));

       });
    }

The $batch should work:

    POST http://localhost:5912/odata/$batch
    Content-Type: multipart/mixed; boundary=####

    --####
    Content-Type: application/http
    Content-Transfer-Encoding:binary
    
    GET /odata/Movies HTTP/1.1
    Accept: application/json
    Content-Type: application/json
    
    --####
    Content-Type: application/http
    Content-Transfer-Encoding:binary
    
    GET /odata/Movies HTTP/1.1
    Accept: application/json
    Content-Type: application/json

Edit the request's body to have more than 100 sub request.

### Expected result

    --batchresponse_bbe40c94-fde9-4f0c-a1b8-369a759a21c5
    Content-Type: application/http
    Content-Transfer-Encoding: binary
    
    HTTP/1.1 200 OK
    Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
    OData-Version: 4.0
    
    {"@odata.context":"http://localhost:5912/odata/$metadata#Movies","value":[{"ID":1,"Title":"Conan","ReleaseDate":"2017-03-03T00:00:00+01:00","Genre":"Comedy","Price":1.99}]}
    --batchresponse_bbe40c94-fde9-4f0c-a1b8-369a759a21c5
    Content-Type: application/http
    Content-Transfer-Encoding: binary
    
    HTTP/1.1 200 OK
    Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
    OData-Version: 4.0
    
    {"@odata.context":"http://localhost:5912/odata/$metadata#Movies","value":[{"ID":1,"Title":"Conan","ReleaseDate":"2017-03-03T00:00:00+01:00","Genre":"Comedy","Price":1.99}]}
    --batchresponse_bbe40c94-fde9-4f0c-a1b8-369a759a21c5--
    ...
    ... 
    x 100

### Actual result

    An unhandled exception occurred while processing the request.
    ODataException: The current batch message contains too many parts. A maximum number of &#x27;100&#x27; query operations and change sets are allowed in a batch message.

**Comment by biaol-odata** [comment]
@OlivierDeRivoyre As an overview, the ODataBatchHandler in WebApi coordinates the batch processing via the ODL's batch reader & writer. 

Therefore, the ODataBatchHandler does not contain logic to limit the batch size of the request message, and ODataBatchHandler.MessageQuota, which you are trying to use as config setting, is not the one that gets populated to the ODL reader, which does the batch size limiting upon request message is received. On the other hand, ODataBatchHandler.MessageQuota that you are trying to set is only used by ODataBatchHandler to check the size of the batch *response*.

For size limiting on batch request, batch reader uses setting specified in ODataMessageReaderSettings.MessageQuota (see [AspNet](https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData/Batch/ODataHttpContentExtensions.cs#L55) and [AspNetCore](https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNetCore.OData/Batch/HttpRequestExtensions.cs#L50)), which can be set via dependency injection.

I scanned thru the code in WebApi-v6/ ODL-v7.3 and WebApi-v7/ODL-v7.4, and believe that they have the same behavior.

In summary, use, e.g., the following DI for Mvc config action:
```
configureAction: containerBuilder =>
                containerBuilder.AddService(
                    Microsoft.OData.ServiceLifetime.Singleton, 
                    typeof(ODataMessageReaderSettings),
                    sp => {
                      return new ODataMessageReaderSettings() {
                            MessageQuotas.MaxOperationsPerChangeset = 10_000;
                            MessageQuotas.MaxPartsPerBatch= 10_000;
                            // other setting here...
                        }
                  })
```
; in addition to the DI of ODataBatchHandler.MessageQuota for proper processing of batch response.

Also, I will like to point out that the WebApi's feature/core branch you mentioned above was a development branch for AspNetCore of WebApi and has been superseded by WebApi/master branch, and you should consider switching if you haven't.

**Comment by OlivierDeRivoyre** [comment]
Hi Bill,

Thank you for your help, it solved my problem.

For googler, and since I've lost some time on this trick, note that there is two ODataMessageReaderSettings:
 - Microsoft.OData.ODataMessageReaderSettings
 - Microsoft.Data.OData.ODataMessageReaderSettings
The one you need to inject is Microsoft.OData.ODataMessageReaderSettings.

**Comment by biaol-odata** [comment]
Microsoft.Data.OData.ODataMessageReaderSettings is for OData 5.x only. We only have Microsoft.OData.ODataMessageReaderSettings in OData 6 and beyond.
