### ISSUE TITLE
Documentation/Code: How to set up cotained entity in code?

### ISSUE THREAD

**Issue by NetTecture** [OData/WebApi#1551]
Current Version.

The examples are very nice in using the [Contained]attribute. Sadly - like all odata attributes-  that comes with tremendous costs (namely pulling in the whole stack up to asp.net) and is not feasible if you want to share an assembly.

As such, I set up all properties in code.

Containment fails.

            var bb2 = builder.EntityType<Event>().ContainsOptional(x => x.Response)
                ;
            var bb1 = builder.EntityType<EventResponse>()
                .InNamespace("PropertyCore");

(InNamespace just setting the namespace)

on an EntityType EventResponse with key results in an EntitySet created. No containment.

On an EntityType EventResposne WITHOUT key it results in an error on GetEdmModel: System.InvalidOperationException: 'The entity 'EventResponse' does not have a key defined.'

There is no documentation at all how to set up a contained entity.

http://odata.github.io/WebApi/ searching for containment has zero info outside of HasManyPath() and HasSinglePath overloads. One hit for "Containment"

Microsoft docs at https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/odata-containment-in-web-api-22

have - no information how to set this up in code at all. The only modlel insists on using the attribute. It is arguably old.

Those 2 are the only official sources. The official samples are - not containing.

Searching incidents leads to only
https://github.com/OData/WebApi/issues/19

which was closed as supported in 5.9 - no documentation.

**Comment by xuzhg** [comment]
@NetTecture Thank for your input.

Let me provide some test as below:

```C#
private static IEdmModel GetEdmModel()
{
   var b = new ODataConventionModelBuilder();
   // var eventType = b.EntitySet<Event>("Events").EntityType;  // same as the following line.
    var eventType = b.EntityType<Event>();
    eventType.ContainsOptional(e => e.Response);
    //   eventType.ContainsRequired(e => e.Response2);  // will throw exception as without key defined.
     return b.GetEdmModel();
 }

public class Event
 {
       public int Id { get; set; }
       public EventResponse Response { get; set; }
       public EventResponse2 Response2 { get; set; }
 }
public class EventResponse
{
   [Key]
   public int MyKey { get; set; }
}
public class EventResponse2
{
   public int MyKey { get; set; }
}
```

The model build will create as following with `Response` as a contained navigation property, meantime, the `Response2` is a structural property.

```
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="SimpleContainmentTest" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityType Name="Event">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int32" Nullable="false" />
                <Property Name="Response2" Type="SimpleContainmentTest.EventResponse2" />
                <NavigationProperty Name="Response" Type="SimpleContainmentTest.EventResponse" ContainsTarget="true" />
            </EntityType>
            <EntityType Name="EventResponse">
                <Key>
                    <PropertyRef Name="MyKey" />
                </Key>
                <Property Name="MyKey" Type="Edm.Int32" Nullable="false" />
            </EntityType>
            <ComplexType Name="EventResponse2">
                <Property Name="MyKey" Type="Edm.Int32" Nullable="false" />
            </ComplexType>
        </Schema>
        <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityContainer Name="Container" />
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>
```

**Comment by NetTecture** [comment]
@xuzhg  Ah - no? Does not work. Now, I made a complete test, so... no Schema document. And Iget exceptions ;) Exceptions.

According to the documentation at https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/odata-containment-in-web-api-22 I shall cotrol containment with an Attribute on the navigation property. Reasons not to do that is mostly - I dont pollute a DTO library iwth the whole asp.net stack, sadly. Can not. ANyhow, the example is clear:

    [Contained]         
    public IList<PaymentInstrument> PayinPIs { get; set; } 

And the rule says that basically a contained type does not need a primary key. Ok.

Let's go. COmplete code.

        [TestMethod]
        public async Task Containment()
        {
            var b = new ODataConventionModelBuilder();
            b.EntityType<AccountProfile>();
            b.EntityType<AccountRole>();
            var eb = b.EntityType<Account>();
            eb.ContainsOptional(x => x.Profile);
            eb.ContainsOptional(x => x.Roles);
            
            var model = b.GetEdmModel();
        }

        public class Account
        {
            [Key]
            public string Identity { get; set; }
            public AccountProfile Profile { get; set; }
            public ICollection<AccountRole> Roles { get; set; }
        }

        public class AccountProfile
        {
            public string Name { get; set; }
            public string AccountingReference { get; set; }
        }

        public class AccountRole
        {
            public string UserName { get; set; }
            public string Role { get; set; }
        }

Does not work. Period.

Result StackTrace:	
at Microsoft.AspNet.OData.Builder.ODataModelBuilder.ValidateModel(IEdmModel model)
   at Microsoft.AspNet.OData.Builder.ODataConventionModelBuilder.GetEdmModel()
   at Tests.Api.Odata.Web.EdmTests.Containment() in C:\Work\OBB\Source.Backend\Tests.Api.Odata.Web\EdmTests.cs:line 34
Result Message:	
Test method Tests.Api.Odata.Web.EdmTests.Containment threw exception: 
System.InvalidOperationException: The entity 'AccountProfile' does not have a key defined.

I never even get an edmmodel, so I can not get a metadata document.

**Comment by xuzhg** [comment]
Would you please point me where do you get the rule: "And the rule says that basically a contained type does not need a primary key".
