### ISSUE TITLE
BUG: Odata ignoring EntityFrameworkCore included data, forces a requery and N+1

### ISSUE THREAD

**Issue by NetTecture** [OData/WebApi#1552]
Current 7.0.2

I finally got EF data working and I am astonished by being hit by an N+1 phenomeon on expand althuogh I actually do not need it.

I know ENtityFrameworkCore is not really smart with auto includes. Which is why I am.

Given:
* get method written with fully parsing of the ODataQueryOptions to get the proper includes:

We work on 2 entiteis, User and Expand=Account.

public ActionResult<D> Get([FromQuery] ODataQueryOptions<D> options = null)
        {
            IEnumerable<string> includes = EmptyIncludes;
            if (options != null) {
                includes = GetIncludesFromExpandClause(options.SelectExpand);
            }

            var query = Repository.Set<E>()
                .ProjectTo<D>(new Dictionary<string, object>(), includes.ToArray())
            ;

Yeah, I know. ProjectTo. EVIL - ah no.

The resulting expression is:

.Call System.Linq.Queryable.Select(
    .Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Data.Core.IDTLogin]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Data.Core.IDTLogin]),
    '(.Lambda #Lambda1<System.Func`2[Data.Core.IDTLogin,Api.Odata.User]>))

.Lambda #Lambda1<System.Func`2[Data.Core.IDTLogin,Api.Odata.User]>(Data.Core.IDTLogin $dtoIDTLogin) {
    .New Api.Odata.User(){
        Account = .Call System.Linq.Enumerable.ToList(.Call System.Linq.Enumerable.Select(
                $dtoIDTLogin.GTMandators,
                .Lambda #Lambda2<System.Func`2[Data.Core.GTMandator,Api.Odata.Account]>)),
        Comment = $dtoIDTLogin.SComment,
        Created = $dtoIDTLogin.DCreateDate,
        Email = $dtoIDTLogin.SEMail,
        FirstName = $dtoIDTLogin.SFirstName,
        Id = $dtoIDTLogin.PkLoginID,
        Identity = $dtoIDTLogin.GIdentity,
        LastName = $dtoIDTLogin.SLastName,
        LoginSource = $dtoIDTLogin.ILoginSource,
    }
}

.Lambda #Lambda2<System.Func`2[Data.Core.GTMandator,Api.Odata.Account]>(Data.Core.GTMandator $dtoGTMandator) {
    .New Api.Odata.Account(){
        Created = $dtoGTMandator.DCreateDate,
        Id = $dtoGTMandator.PkMandatorID,
        Identity = $dtoGTMandator.GIdentity,
        Name = $dtoGTMandator.SName
    }
}

And is as easy as it gets.

Quite simple.

2 test cases:

            var data = query.ToList();
            return Ok(query);

* The first one materializes to list. The debug output shows exactly what is should, ONE query:

Api.Odata.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Api.Odata.Web>       Executed DbCommand (61ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
Api.Odata.Web>       SELECT [t].[pkLoginID], [f.GTMandators].[dCreateDate] AS [Created], [f.GTMandators].[pkMandatorID] AS [Id], [f.GTMandators].[gIdentity] AS [Identity], [f.GTMandators].[sName] AS [Name], [f.GTMandators].[fkLoginID]
Api.Odata.Web>       FROM [dbo].[G_TMandator] AS [f.GTMandators]
Api.Odata.Web>       INNER JOIN (
Api.Odata.Web>           SELECT [f0].[pkLoginID]
Api.Odata.Web>           FROM [dbo].[ID_TLogin] AS [f0]
Api.Odata.Web>           WHERE CHARINDEX(N'{deleted}', [f0].[sEMail]) <= 0
Api.Odata.Web>       ) AS [t] ON [f.GTMandators].[fkLoginID] = [t].[pkLoginID]
Api.Odata.Web>       ORDER BY [t].[pkLoginID]

And because of extracting the includes, related data is there.

  | Name | Value | Type
-- | -- | -- | --
◢ | data | Count = 247 | System.Collections.Generic.List<Api.Odata.User>
  | ◢ [0] | {Api.Odata.User} | Api.Odata.User
  | ◢ Account | Count = 1 | System.Collections.Generic.ICollection<Api.Odata.Account> {System.Collections.Generic.List<Api.Odata.Account>}
  | ▶ [0] | {Api.Odata.Account} | Api.Odata.Account

Nice. As it should be.

Now test 2. We hand this exact same lambda over to OData and see and behold:

Api.Odata.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Api.Odata.Web>       Executed DbCommand (95ms) [Parameters=[@__p_1='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
Api.Odata.Web>       SELECT TOP(@__p_1) [f].[sComment] AS [Comment], [f].[dCreateDate] AS [Created], [f].[sEMail] AS [Email], [f].[sFirstName] AS [FirstName], [f].[pkLoginID] AS [Id], [f].[gIdentity] AS [Identity], [f].[sLastName] AS [LastName], [f].[iLoginSource] AS [LoginSource], [f].[sMailingAddress] AS [MailingAddress], [f].[sPhoneBusiness] AS [PhoneBusiness], [f].[sPhoneMobile] AS [PhoneMobile], [f].[sPosition] AS [Position], [f].[sTitle] AS [Title],
Api.Odata.Web>       FROM [dbo].[ID_TLogin] AS [f]
Api.Odata.Web>       WHERE CHARINDEX(N'{deleted}', [f].[sEMail]) <= 0
Api.Odata.Web>       ORDER BY [Identity], [f].[pkLoginID]
Api.Odata.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Api.Odata.Web>       Executed DbCommand (68ms) [Parameters=[@__p_1='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
Api.Odata.Web>       SELECT [t].[gIdentity], [t].[pkLoginID], [f.GTMandators].[dCreateDate] AS [Created], [f.GTMandators].[pkMandatorID] AS [Id], [f.GTMandators].[gIdentity] AS [Identity], [f.GTMandators].[sName] AS [Name], [f.GTMandators].[fkLoginID]
Api.Odata.Web>       FROM [dbo].[G_TMandator] AS [f.GTMandators]
Api.Odata.Web>       INNER JOIN (
Api.Odata.Web>           SELECT TOP(@__p_1) [f0].[gIdentity], [f0].[pkLoginID]
Api.Odata.Web>           FROM [dbo].[ID_TLogin] AS [f0]
Api.Odata.Web>           WHERE CHARINDEX(N'{deleted}', [f0].[sEMail]) <= 0
Api.Odata.Web>           ORDER BY [f0].[gIdentity], [f0].[pkLoginID]
Api.Odata.Web>       ) AS [t] ON [f.GTMandators].[fkLoginID] = [t].[pkLoginID]
Api.Odata.Web>       ORDER BY [t].[gIdentity], [t].[pkLoginID]
Api.Odata.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Api.Odata.Web>       Executed DbCommand (49ms) [Parameters=[@_outer_PkLoginID='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
Api.Odata.Web>       SELECT [dtoGTMandator].[dCreateDate] AS [Created], [dtoGTMandator].[pkMandatorID] AS [Id], [dtoGTMandator].[gIdentity] AS [Identity], [dtoGTMandator].[sName] AS [Name]
Api.Odata.Web>       FROM [dbo].[G_TMandator] AS [dtoGTMandator]
Api.Odata.Web>       WHERE @_outer_PkLoginID = [dtoGTMandator].[fkLoginID]
Api.Odata.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Api.Odata.Web>       Executed DbCommand (46ms) [Parameters=[@_outer_PkLoginID='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
Api.Odata.Web>       SELECT [dtoGTMandator].[dCreateDate] AS [Created], [dtoGTMandator].[pkMandatorID] AS [Id], [dtoGTMandator].[gIdentity] AS [Identity], [dtoGTMandator].[sName] AS [Name]
Api.Odata.Web>       FROM [dbo].[G_TMandator] AS [dtoGTMandator]
Api.Odata.Web>       WHERE @_outer_PkLoginID = [dtoGTMandator].[fkLoginID]
Api.Odata.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Api.Odata.Web>       Executed DbCommand (45ms) [Parameters=[@_outer_PkLoginID='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
Api.Odata.Web>       SELECT [dtoGTMandator].[dCreateDate] AS [Created], [dtoGTMandator].[pkMandatorID] AS [Id], [dtoGTMandator].[gIdentity] AS [Identity], [dtoGTMandator].[sName] AS [Name]
Api.Odata.Web>       FROM [dbo].[G_TMandator] AS [dtoGTMandator]
Api.Odata.Web>       WHERE @_outer_PkLoginID = [dtoGTMandator].[fkLoginID]
Api.Odata.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Api.Odata.Web>       Executed DbCommand (45ms) [Parameters=[@_outer_PkLoginID='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
Api.Odata.Web>       SELECT [dtoGTMandator].[dCreateDate] AS [Created], [dtoGTMandator].[pkMandatorID] AS [Id], [dtoGTMandator].[gIdentity] AS [Identity], [dtoGTMandator].[sName] AS [Name]
Api.Odata.Web>       FROM [dbo].[G_TMandator] AS [dtoGTMandator]
Api.Odata.Web>       WHERE @_outer_PkLoginID = [dtoGTMandator].[fkLoginID]

A serious repetitive "I don't ahve the accounts, lets get them for every user" sequence started. Odata is actively ignoring the fact that the properties are already filled and is asking for them one by one a second time.

Fix:

This is redundant, not needed, a regression to old behavior. If a related propery from EF comes with the collection set, then this collection has been loaded (through an include) and should not be requeried. 

Sub-Queries shuold only be issued for property instances where the collection has NOT been initialized, in line with the behavior of selective data loading of Entity Framework Core.

OData is actively ignoring data provided by EntityFramework core.

**Comment by smasherprog** [comment]
https://github.com/OData/WebApi/issues/1463
