### ISSUE TITLE
Filter in a Guid property does not work, odata not recognizing guid literal

### ISSUE THREAD

**Issue by NetTecture** [OData/WebApi#1556]
Given an object Building with a Guid Identity
```xml
<EntityType Name="Building">
  <Key>
    <PropertyRef Name="Identity"/>
  </Key>
  <Property Name="Identity" Type="Edm.Guid" Nullable="false"/>

```
the following should work:

https://localhost:44361/Building?$filter=Identity%20eq%2027ca08f36c-c08a-42e6-9293-e4243377e505

but I do get:

{"error":{"code":"","message":"The query specified in the URI is not valid. Syntax error at position 50 in 'Identity eq 27ca08f36c-c08a-42e6-9293-e4243377e505'.","details":[],"innererror":{"message":"Syntax error at position 50 in 'Identity eq 27ca08f36c-c08a-42e6-9293-e4243377e505'.","type":"Microsoft.OData.ODataException","stacktrace":"   at Microsoft.OData.UriParser.ExpressionLexer.ValidateToken(ExpressionTokenKind t)\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseExpressionText(String expressionText)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()\r\n   at Microsoft.AspNet.OData.Query.FilterQueryOption.get_FilterClause()\r\n   at Microsoft.AspNet.OData.Query.Validators.FilterQueryValidator.Validate(FilterQueryOption filterQueryOption, ODataValidationSettings settings)\r\n   at Microsoft.AspNet.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ValidateQuery(HttpRequest request, ODataQueryOptions queryOptions)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.<>c__DisplayClass1_0.<OnActionExecuted>b__3(ODataQueryContext queryContext)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)"}}}

According to 

http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part2-url-conventions/odata-v4.0-errata02-os-part2-url-conventions-complete.html#_Toc406398153 5.1.1.5.1 this is the correct form of a GUID literal, indicating there is an error in the expression lexer.

GuidValue eq 01234567-89ab-cdef-0123-456789abcdef

is given as explicit example

**Comment by KanishManuja-MS** [comment]
I tried reproducing this with no luck. The filter query works for me for GUID, can you please share with me the entire metadata? Did your query have quotes or other special characters?

**Comment by xuzhg** [comment]
@NetTecture Filtering by Guid has been supporting for a while. Would you please share your non-working re-pro for us to investigate?

**Comment by KanishManuja-MS** [comment]
@NetTecture I see that you have the guid that you have used for the filtering query is not valid. Removing the prepended 27 to your guid - "27ca08f36c-c08a-42e6-9293-e4243377e505" shall fix the error thrown at you.
