### ISSUE TITLE
Don't assume port 80 for nextLink when request was HTTPS

### ISSUE THREAD

**Issue by andrewlock** [OData/WebApi#1559]
I just spent half a day debugging this issue, where Power BI could connect to an ASP.NET Core OData api over HTTP, but not over HTTPS. I finally figured out that the `@odata.nextLink` was returning an invalid port in the URL when accessed over HTTPS - port 80 instead of port 443.

### Assemblies affected

 OData WebApi lib 7.0.0

### Reproduce steps

The issue only appeared when the app was behind a reverse proxy (HAproxy and / or NGINX). In these cases, the ASP.NET Core `ForwardedHeadersMiddleware` wasn't explicitly setting the forwarded port (due to [this issue](https://github.com/aspnet/BasicMiddleware/issues/204)), so `request.Host.Port == null`.

That causes the `UriBuilder` in the `GetNextPageLink` function to use the default port of 80, even though the scheme is `"https"`. Requests to the next page link will consequently fail.

https://github.com/OData/WebApi/blob/8cf204777d183f909bc16c7743d5c058c52a6a78/src/Microsoft.AspNetCore.OData/Extensions/HttpRequestExtensions.cs#L268-L279

### Expected result

`@odata.nextLink` should use the correct port, e.g. https://example.com:80/odata/MyEntities?$skip=10
### Actual result

`@odata.nextLink` should use the correct port, e.g. https://example.com:443/odata/MyEntities?$skip=10 or https://example.com/odata/MyEntities?$skip=10 

### Additional detail

I believe this issue could be fixed by allowing `UriBuilder` to resolve the port itself if the port isn't set, e.g:

```c#
UriBuilder uriBuilder = new UriBuilder(request.Scheme, request.Host.Host) { Path = (request.PathBase + request.Path).ToUriComponent() };
if (request.Host.Port.HasValue)
{
    uriBuilder.Port = request.Host.Port.Value;
}
```

I'm happy to raise a PR for this if this sounds acceptable

**Comment by biaol-odata** [comment]
Ideally, we should relying on the ASP.NET Core to handle the reverse proxy scenario correctly, instead of trying to patch up in WebAPI?

**Comment by biaol-odata** [comment]
Adding ASP.NET Core issue link: https://github.com/aspnet/BasicMiddleware/issues/204

**Comment by biaol-odata** [comment]
@andrewlock I have pinged the ASP.NET Core issue owner for timeline of resolution of the underlying issue. If we don't get concrete information, we can consider patching it up in WebAPI as work around. Therefore, feel free to submit a PR. Thanks.

**Comment by goethalsf** [comment]
Hi,

I just wanted to add that i also encountered this issue where the "@odata.nextLink" has the wrong port 80 added instead of 443 , and would like to have it fixed :-)

I think no default-port assumptions should be used, as in my case , as for internal company development we uses different http/https ports then 80, 443
