### ISSUE TITLE
v5.5: Support Edm.Date & Edm.TimeOfDay

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#156]
ODL annouced the ship of V6.8.0 as below:  
[ http://www.nuget.org/packages/Microsoft.OData.Core/6.8.0
](http://www.nuget.org/packages/Microsoft.OData.Core/6.8.0)  
  
in this release, ODL supports two new primitive types: Edm.Date &
Edm.TimeOfDay  
  
So, please add the support for TimeOfDay and Date in Web API.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2158](http://aspnetwebstack.codeplex.com/workitem/2158)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Oct 16, 2014 at 3:19 AM
**Reported by:**	xuzhg
**Updated on:**	Today at 3:39 AM
**Updated by:**	xuzhg

**Comment by LianwMS** [comment]
On *2015-01-09 11:39:19 UTC*, **xuzhg** commented:

GitHub: Here

**Comment by congysu** [comment]
#2

**Comment by MrTomWhite** [comment]
Looks like @xuzhg closed #2 already, so we can probably close this issue.

**Comment by VikingsFan** [comment]
Close as #2
