### ISSUE TITLE
How to return data as XML

### ISSUE THREAD

**Issue by droyad** [OData/WebApi#1562]
I'm trying to port an application from ASP.NET OData 5.7.0 to .NET Core. The application returns the results in XML. However, despite my best efforts, it just keeps returning JSON, despite the `Accept: application/atom+xml, application/xml` header.

OData WebApi Core lib 7.0.1

I've created my own `OutputFormatterSelector` that returns the XML formatter first, then also set the content type on my `ObjectResult` to `application/xml` as well as adding just the XML Formatter to that result.

Where I am now is overriding the `ODataMediaTypeResolver` as that seems to be resetting it back to `json`. That is where I am stuck.

How can I get my output to be returned as XML?

**Comment by biaol-odata** [comment]
Closed. Feel free to reopen or open new one as needed.

**Comment by vladkolodka** [comment]
@biaol-odata but there is still XML formatter in the source code (see ODataOutputFormatterFactory.Create())
