### ISSUE TITLE
Is it currently possible to write your own logic to apply system query options?

### ISSUE THREAD

**Issue by DavTheSuave** [OData/WebApi#1563]
I have an OData service that indirectly exposes SQL tables. I want to convert system query options like $filter into part of the SQL call itself. I'm able to do this currently, but not without OData then taking my return value in the Get method and applying the query to it. This means my data is being filtered on twice, not the end of the world but not ideal either. I can't seem to find any way to stop OData from automatically applying the options, aside from manually calling ApplyTo (which defeats the purpose).

### Assemblies affected

Microsoft.AspNet.OData 7.0.0.20629

**Comment by biaol-odata** [comment]
@DavTheSuave I believe currently query options is *always and automatically* applied on the Get result, and I am not aware of any settings to achieve what you describe. IMHO, the current design helps to achieve a simple design with good usability.

**Comment by NetTecture** [comment]
How does your method signature look? Because this is what happens when YOU apply and then there is an EnableQuery attribute. It happens more if you ahve two EnableQuery (i.e. filters applied twice). But you do not NEED EnableQuery if you handle it yourself.

**Comment by DavTheSuave** [comment]
@NetTecture Good call! I assumed OData would reject query options if I removed the [EnableQuery] attribute, so I never thought to do it. This solved my issue, thank you.

**Comment by biaol-odata** [comment]
@DavTheSuave @NetTecture In retrospective, that actually makes sense. Thanks for pointing that out.

**Comment by biaol-odata** [comment]
Closed. Feel free to re-open or open new one as needed.
