### ISSUE TITLE
Odata count inside Expand [.Net Core]

### ISSUE THREAD

**Issue by albertoVieiraNeto** [OData/WebApi#1564]
### Short summary

Odata count function does not work properly when inside the expand property. either throws a exception or displays incorrect values. 

### Assemblies affected

Version affected/Tested :
Microsoft.AspNetCore.OData @7.0.1

### Reproduce steps

Create 2 models 

```csharp
public abstract class ModelBaseWithId {
        [Required]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public virtual Guid Guid { get; set; }

        [Required, DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTimeOffset CreatedUtc { get; set; }

        [Timestamp]
        public byte[] RowVersion { get; set; }
    }
```
```csharp
public class Company: ModelBaseWithId  {
        public string Name { get; set; }

        public string Description { get; set; }

        public string Domain { get; set; }

        public virtual ICollection<CompanyEnvironment> Environments { get; set; }
    }
```

```csharp
public class CompanyEnvironment: ModelBaseWithId {

        public string Name { get; set; }

        public string Description { get; set; }

        public string ConnectionString { get; set; }

        public virtual Company Company { get; set; }

    }
```

register the odata endpoint as per documentation, and try to hit the following url

`http://<serverAddress>/<configuredPath>/CompanyEnvironment?$expand=Company($count=true)&$count=true`

the '$count=true' inside the expand causes a Value Null Exception, the count outside works as expected.

> ArgumentNullException: Value cannot be null.
Parameter name: member

### Expected result

all expanded items should have a count in the format "fieldName@odata.count":number

### Actual result

either throws a exception on shows incorrect values

**Comment by biaol-odata** [comment]
Set to P2 due to NullValueExeception.

**Comment by NetTecture** [comment]
That is actually supposed to work?

I am asking because a similar URL does not even pass parsing in ODL libraries (which would be tracked under 809). This would actually possibly be a workaround one that is made working. So, this is actually supposed to work? NICE.

**Comment by gathogojr** [comment]
Fixed by https://github.com/OData/odata.net/pull/2051
