### ISSUE TITLE
Function bound to entity routing error [.Net Core]

### ISSUE THREAD

**Issue by albertoVieiraNeto** [OData/WebApi#1571]
*Short summary (3-5 sentences) describing the issue.*
functions bound to entity dont seem to be working

### Assemblies affected

Version affected/Tested :
Microsoft.AspNetCore.OData @7.0.1

### Reproduce steps

on the builder create a simple function bound to the entity:

```csharp
var teste = builder.EntityType<any_desired_type>().Function("IsTeste").Returns<bool>();
```
on the controller for that type create new simple function and leave a default one with enable query:

```csharp

        [HttpGet]
        [EnableQuery]
        public IQueryable<Post> Get([FromODataUri] int key)
        {
            return _DbContext.Post;
        }

        [HttpGet]
        [ODataRoute("Post({key})/Default.IsTeste()")]
        public bool teste(int key) {
            return true;
        }       

```
then hit:
` http://<server>/<route>/<type>(1)/Default.IsTeste()`

### Expected result

the route to be respected and the correct function be activated

### Actual result

odata grabs the first function that has the parameters ignoring the defined route.

### Question

Is this product realy out of beta? i've been seen some pretty strange issues

**Comment by albertoVieiraNeto** [comment]
changing the code to something like the example below, makes the routing works but i wanted something a little like what we could do with the older version [example](https://blogs.msdn.microsoft.com/odatateam/2014/12/08/tutorial-sample-functions-actions-in-web-api-v2-2-for-odata-v4-0-type-scenario/#comments)

declaration:
```csharp
var teste = builder.EntityType<any_desired_type>().Function("teste").Returns<bool>();
```
function inside the controller
```csharp
[HttpGet]
public bool teste(int key) {
   return true;
}       
```

**Comment by xuzhg** [comment]
@albertoVieiraNeto Please let us know any further helps on it
