### ISSUE TITLE
OData deserializer swallows errors if ILogger service is registered

### ISSUE THREAD

**Issue by nkilzer** [OData/WebApi#1572]
Model binding errors for malformed data when invoking Post() methods (and probably others) are not propagated to the controller method if a service with the `Microsoft.Extensions.Logging.ILogger` interface is registered.

### Assemblies tested
Microsoft.AspNetCore.OData 7.0.1 (from Nuget)

### Reproduction steps

I haven't had time to put together a complete sample project for the issue (my test project includes a number of additional bits specific to our environment), but I did pull out enough into a gist that should be able to demonstrate the issue. If I get some additional time this week, I'll try to put together a more complete sample solution. The gist should be reachable here: https://gist.github.com/nkilzer/63d676bd8ad5817d6708b1fca94ccc44

The issue occurs when sending malformed (e.g. not conforming to datatype, or valdation rules) data to the `[FromBody]` parameter of a `Post()` endpoint - but only when a service for `Microsoft.Extensions.Logging.ILogger` is registered in the application service provider.

### Expected results

The `ModelState.IsValid` property would return false, and `ModelState` would contain a collection of errors about what properties were invalid, and why (as in all normal model-binding scenarios).

### Actual Results

When attempting to send invalid (malformed, etc.) data to the `Post()` endpoint to determine how best to handle errors, I was consistently getting a result where the incoming model parameter would be null, but the `ModelState.IsValid` value was returning true, and there were no errors in the `ModelState` collection.

If the service is not registered, the model binder appears to propagate an error state correctly to the controller method.

### Additional details

I was able to isolate the root cause to this block by creating a decorator for `ILogger` and checking the call-stack at the point that the logging method was called:
https://github.com/OData/WebApi/blob/f9d10191efcb13fee7f995fa4ec2188860d8c6fd/src/Microsoft.AspNetCore.OData/Formatter/ODataInputFormatter.cs#L130-L139

Given that the commit comment indicates that this was part of the addition of OData batching support, I'm not sure I have a useful contribution to what an appropriate fix is - just going back to throwing the exception in all cases seems like it would break the batching behavior.

### Workarounds

My current workaround is to ensure that at any site where `ModelState.IsValid` is checked, that there is also a check for `IsValid && input == null`, as I don't have any use cases that would involve a potentially empty object being posted to the endpoint.

**Comment by gathogojr** [comment]
More recent issue to track the described bug/issue
