### ISSUE TITLE
Star select ($select=*) not returning dynamic properties

### ISSUE THREAD

**Issue by maximpashuk** [OData/WebApi#1579]
Hi I am using **Microsoft.AspNetCore.OData 7.0.1**

I always think that call to "**/movies**" should be equals to call to "**/movies?$select=***".
But this is not true in a case of dynamic properties.

This behavior can be simply reproduced in sample app in this repo **([AspNetCoreODataSample.Web](https://github.com/OData/WebApi/tree/master/samples/AspNetCoreODataSample.Web)).**

If you add to Movie model

```csharp
public class Movie
{
    public int ID { get; set; }
    ...
    [NotMapped] // attribute required by ef core
    public IDictionary<string, object> DynamicProperties { get; set; }
}
```

and later in MoviesController you add some example data
```csharp
Movie m = new Movie
{
    Title = "Conan",
    ...
    DynamicProperties = new Dictionary<string, object>
    {
        {"key1", "value1" },
        {"key2", "value2" },
    }
};
```

call to "efcore/Movies" returns dynamic properties, while call to "efcore/Movies?$select=*" does not return dynamic properties.

[ODATA specs](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#sec_SystemQueryOptionselect) said about that

> It is also possible to request all structural properties, **including any dynamic properties, using the star operator**

So I think this behavior is a bug that should be fixed.

**Comment by xuzhg** [comment]
Merged.
