### ISSUE TITLE
OData builder does not honor namespace

### ISSUE THREAD

**Issue by RamjotSingh** [OData/WebApi#1591]
*Short summary (3-5 sentences) describing the issue.*
OData EDM builder does not add new entity and complex types automatically to the namespace registered in ODataConventionModelBuilder.

### Assemblies affected

OData 7.X assemblies

### Reproduce steps

ODataConventionModelBuilder builder = new ODataConventionModelBuilder
            {
                Namespace = "MyCustomNamespace",
            };

builder.EntitySet<MyEntity>("myentities");

### Expected result

MyEntity should be registered with MyCustomNamespace namespace

### Actual result

MyEntity is registered with Default namespace

### Additional detail
One way to fix this is to do something like
builder.EntitySet<MyEntity>("myentities").EntityType.Namespace = "MyCustomNamespace";
but this does not work with automatic registration, hence not a really usable workaround.

**Comment by biaol-odata** [comment]
Closed as merger.
