### ISSUE TITLE
Publish PDBs to Microsoft Symbol Server

### ISSUE THREAD

**Issue by Danielku15** [OData/WebApi#1595]
Most of the Microsoft.AspNetCore.* projects publish their debug symbols (PDBs) including SourceLink support to the Microsoft Symbol Services so you can step into the sources while debugging. The Microsoft.AspNetCore.OData PDBs seem to be one of the only ones missing. 

### Assemblies affected

Microsoft.AspNetCore.OData.dll - 7.00.1.20718 (711BE7D3B49657DBB39831AF956E78601) 
*via released NuGet Package Microsoft.AspNetCore.Owin 2.1.1.*

(I didn't check the non-core DLL but I assume it is also missing). 

### Reproduce steps

- Disable Just My Code Debugging
- Enable Source server support 
- Enable Source Link support
- Enable the Microsoft Symbol Server 
- Setup a project with asp.net core and use the OData package. 
- Try to step into the any OData related code. 

### Expected result

- PDBs are loaded are sources are loaded via GitHub. 
- Stepping into OData related code is possible.

### Actual result

- PDBs are not loaded as they are not found on the Microsoft Symbol Server. 

### Additional detail

The Symbol Load Information shows the following log: 

```
SYMSRV:  BYINDEX: 0x8E
         D:\temp\Symbols*https://msdl.microsoft.com/download/symbols
         Microsoft.AspNetCore.OData.pdb
         711BE7D3B49657DBB39831AF956E78601
SYMSRV:  UNC: D:\temp\Symbols\Microsoft.AspNetCore.OData.pdb\711BE7D3B49657DBB39831AF956E78601\Microsoft.AspNetCore.OData.pdb - path not found
SYMSRV:  UNC: D:\temp\Symbols\Microsoft.AspNetCore.OData.pdb\711BE7D3B49657DBB39831AF956E78601\Microsoft.AspNetCore.OData.pd_ - path not found
SYMSRV:  UNC: D:\temp\Symbols\Microsoft.AspNetCore.OData.pdb\711BE7D3B49657DBB39831AF956E78601\file.ptr - path not found
SYMSRV:  HTTPGET: /download/symbols/Microsoft.AspNetCore.OData.pdb/711BE7D3B49657DBB39831AF956E78601/Microsoft.AspNetCore.OData.pdb
SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
SYMSRV:  HTTPGET: /download/symbols/Microsoft.AspNetCore.OData.pdb/711BE7D3B49657DBB39831AF956E78601/Microsoft.AspNetCore.OData.pd_
SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
SYMSRV:  HTTPGET: /download/symbols/Microsoft.AspNetCore.OData.pdb/711BE7D3B49657DBB39831AF956E78601/file.ptr
SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
SYMSRV:  RESULT: 0x80190194
https://msdl.microsoft.com/download/symbols: Symbols not found on symbol server.
```

As comparison another AspNetcore assembly which has symbols: 
```
SYMSRV:  BYINDEX: 0x6B
         D:\temp\Symbols*https://msdl.microsoft.com/download/symbols
         Microsoft.AspNetCore.Mvc.Razor.Extensions.pdb
         C9517587F95F4BA3A213F73C17F5A658ffffffff
SYMSRV:  UNC: D:\temp\Symbols\Microsoft.AspNetCore.Mvc.Razor.Extensions.pdb\C9517587F95F4BA3A213F73C17F5A658ffffffff\Microsoft.AspNetCore.Mvc.Razor.Extensions.pdb - path not found
SYMSRV:  UNC: D:\temp\Symbols\Microsoft.AspNetCore.Mvc.Razor.Extensions.pdb\C9517587F95F4BA3A213F73C17F5A658ffffffff\Microsoft.AspNetCore.Mvc.Razor.Extensions.pd_ - path not found
SYMSRV:  UNC: D:\temp\Symbols\Microsoft.AspNetCore.Mvc.Razor.Extensions.pdb\C9517587F95F4BA3A213F73C17F5A658ffffffff\file.ptr - path not found
SYMSRV:  HTTPGET: /download/symbols/Microsoft.AspNetCore.Mvc.Razor.Extensions.pdb/C9517587F95F4BA3A213F73C17F5A658ffffffff/Microsoft.AspNetCore.Mvc.Razor.Extensions.pdb
SYMSRV:  HttpQueryInfo: 801900c8 - HTTP_STATUS_OK
SYMSRV:  Microsoft.AspNetCore.Mvc.Razor.Extensions.pdb from https://msdl.microsoft.com/download/symbols: 21904 bytes 
SYMSRV:  PATH: D:\temp\Symbols\Microsoft.AspNetCore.Mvc.Razor.Extensions.pdb\C9517587F95F4BA3A213F73C17F5A658ffffffff\Microsoft.AspNetCore.Mvc.Razor.Extensions.pdb
SYMSRV:  RESULT: 0x00000000
https://msdl.microsoft.com/download/symbols: Symbols downloaded from symbol server.
D:\temp\Symbols\Microsoft.AspNetCore.Mvc.Razor.Extensions.pdb\C9517587F95F4BA3A213F73C17F5A658ffffffff\Microsoft.AspNetCore.Mvc.Razor.Extensions.pdb: Symbols loaded.

```

**Comment by xuzhg** [comment]
@Danielku15 

Actually, We published the symbols to server: `https://nuget.smbsrc.net/`.  And I can debug into ASP.NET Core OData and ODL source codes. 

I checked it at my side, all `Microsoft.AspNetCore.dll` symbols were uploaded to this server. 
![image](https://user-images.githubusercontent.com/9426627/44806511-07cd7580-ab7c-11e8-9f37-410cce30bcad.png)

Would you please add `https://nuget.smbsrc.net` into the Symbol location:

![image](https://user-images.githubusercontent.com/9426627/44806563-27fd3480-ab7c-11e8-99f0-efcc6b339a74.png)


Hope it can help. If it still can't load the symbol, please let me know. 

Thanks.

**Comment by Danielku15** [comment]
Thanks, debugging is working perfectly now. Was the PDB location documented somewhere and I missed it?

**Comment by xuzhg** [comment]
No, you don't. It's still in a https://github.com/OData/WebApi/pull/1590.

**Comment by xuzhg** [comment]
@rossbuggins No, the latest version symbol is not, owing to the cert problem. And it seems there's no one maintaining that server. Later, i'd think to include the PDB using snupkg. See https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

**Comment by KanishManuja-MS** [comment]
@rossbuggins The symbols should be available on the same server now. Please let me know if you run into problems.

**Comment by rossbuggins** [comment]
Great, I’ll take a look next week, thanks
