### ISSUE TITLE
Consider the strategy for interface property in convention model builder

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#16]
Currently, we don't do anything special for interface. It will be added as an
entity type or complex type depending on the entity key convention.  
  
We can ignore interface property in convention model builder as it sounds like
not a supported scenario.  
  
Or we can make interface same as abstract class, then we need to change our
convention to mark it as abstract in edm model.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 514](http://aspnetwebstack.codeplex.com/workitem/514)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Oct 6, 2012 at 12:29 AM
**Reported by:**	hongyes
**Updated on:**	Sep 19, 2013 at 11:30 PM
**Updated by:**	danroth27

**Comment by LianwMS** [comment]
On *2012-10-09 07:35:00 UTC*, **HongmeiG** commented:

WE need to add a new convention for marking this type as abstract when it is interface.

**Comment by LianwMS** [comment]
On *2013-04-02 08:25:26 UTC*, **HongmeiG** commented:

Interface is different from abstract base class because it supports multiple inheritance. And Edm model does not support multiple inheritance.

**Comment by xuzhg** [comment]
Close it.
