### ISSUE TITLE
CreateODataValue on ODataPrimitiveSerializer is sealed

### ISSUE THREAD

**Issue by mtroth-microsoft** [OData/WebApi#1603]
Is there a particular reason why this implementation of the method is sealed? to properly handle some scenarios (when i have wrapped my primitive types in a class), I need to be able to override this method and unbox the value before passing it to the base implementation.

**Comment by xuzhg** [comment]
@mtroth-microsoft I can't remember the reason. Can't you override the before virtual function "WriteProperty" and the after virtual function "CreateODataPrimitiveValue"?
