### ISSUE TITLE
v5.6: Serialization of EdmEntityObject, donot honour $Select clause

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#161]
On using the $select for untyped objects, the response give the complete
object with null values, rather than providing only the properties mentioned
in the select clause,  

We have to add an extra line in the controller to overcome the serializer
issue.  

```
// Add this line to show the select expand clause in the serializer to overcome the serializer issue.
if (queryOptions.SelectExpand != null && queryOptions.SelectExpand.SelectExpandClause != null)
{
    Request.ODataProperties().SelectExpandClause = queryOptions.SelectExpand.SelectExpandClause;
}
```
## Work Item Details

**Original CodePlex Issue:**    [Issue 2174](http://aspnetwebstack.codeplex.com/workitem/2174)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Nov 3, 2014 at 8:56 AM
**Reported by:**    ShahzorKhan
**Updated on:** Tue at 8:53 AM
**Updated by:** cysu

**Comment by LianwMS** [comment]
On *2015-01-06 16:53:19 UTC*, **cysu** commented:

Review with other untyped asks.

**Comment by xuzhg** [comment]
Related #165
