### ISSUE TITLE
v5.6: PropertyRoutingConvention donot support generic handling.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#162]
Few details here,  
The PropertyRoutingConvention expects the following functions to be
implemented in controller,  

```
string actionName = actionMap.FindMatchingAction(
    "Get" + property.Name + "From" + declaringType.Name,
    "Get" + property.Name);
```

This donot allow support for generic routing function. Also it doesnot provide
an easy override for this support.  
Expected functionName is  

```
GetProperty(string entityName, string key, string propertyName)
PutProperty(string entityName, string key, string propertyName, [FromBody]object propertyValue)
```

This also brings the following complications, Since the function can have any
property type, the syntax takes in object type, which causes deserialization
issues,  
We have to currently override it to deserialize object using the following.  

```
config.Formatters.InsertRange(0, ODataMediaTypeFormatters.Create(new CustomODataSerializerProvider(), new CustomODataDeserializerProvider()));

...

internal class CustomODataDeserializerProvider : DefaultODataDeserializerProvider
{
    public override ODataDeserializer GetODataDeserializer(Microsoft.OData.Edm.IEdmModel model, Type type, System.Net.Http.HttpRequestMessage request)
    {
        if (type == typeof(object))
        {
            IEdmTypeReference typeReference = request.ODataProperties().Path.EdmType.ToEdmTypeReference(true);
            if (typeReference is IEdmComplexTypeReference)
            {
                return new CustomODataComplexTypeDeserializer(this);
            }
            else
            {
                ODataDeserializer deserializer = GetEdmTypeDeserializer(typeReference);
            }
        }
        return base.GetODataDeserializer(model, type, request);
    }
}

internal class CustomODataComplexTypeDeserializer : ODataComplexTypeDeserializer
{
    public CustomODataComplexTypeDeserializer(ODataDeserializerProvider deserializerProvider)
        : base(deserializerProvider)
    { }

    public override object Read(Microsoft.OData.Core.ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)
    {
        if (type == typeof(object))
        {
            Debug.Assert(readContext != null, "ArgumentNull readContext");
            Debug.Assert(type != null, "ArgumentNull type");
            Debug.Assert(readContext.Request.ODataProperties().Path.EdmType is IEdmComplexType, "PathEdmType should be IEdmComplexType");

            IEdmComplexTypeReference complexTypeReference = (EdmComplexTypeReference)readContext.Request.ODataProperties().Path.EdmType.ToEdmTypeReference(true);
            readContext.ResourceType = typeof(EdmComplexObject);
            ODataProperty property = messageReader.ReadProperty(complexTypeReference);

            return ReadInline(property.Value, complexTypeReference, readContext);
        }
        else return base.Read(messageReader, type, readContext);
    }
}
```

The following code only provides the newtonsoft objects here, which we later
correct based on the EdmProperty type,  

```
HttpResponseMessage PutProperty(string entityName, string key, string propertyName, [FromBody]object propertyValue){
    ...
    object translatedPropertyValue = GetTranslatedPropertyValue(edmProperty, propertyValue);
    // use this value
}

object GetTranslatedPropertyValue(IEdmProperty edmProperty, object propertyValue)
    {
        // Handling for Primitive Types
        if (propertyValue is Newtonsoft.Json.Linq.JObject)
        {
            Newtonsoft.Json.Linq.JToken newValue = null;

            // return null if no entity is found for property "value"
            if (!((Newtonsoft.Json.Linq.JObject)propertyValue).TryGetValue("value", out newValue))
            {
                return null;
            }
            else
            {
                Newtonsoft.Json.Linq.JValue jValue = (Newtonsoft.Json.Linq.JValue)newValue;
                if(edmProperty.Type.IsBinary())
                {
                    return Convert.FromBase64String(newValue.ToString());
                }
                                    // Similarly handle for others. 
            }
        }
        // Handling for Complex Types
        else
        {
            return propertyValue;
        }
    }
```

Expected behavior is the WebAPI code automatically detect the EdmProperty type
and serialize to the appropriate object value.  
## Work Item Details

**Original CodePlex Issue:**    [Issue 2175](http://aspnetwebstack.codeplex.com/workitem/2175)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Nov 3, 2014 at 9:20 AM
**Reported by:**    ShahzorKhan
**Updated on:** Tue at 8:51 AM
**Updated by:** cysu

**Comment by LianwMS** [comment]
On *2014-11-03 17:55:06 UTC*, **ShahzorKhan** commented:

Also note here the Serializer Provider changes for serializing object types
internal class CustomODataSerializerProvider : DefaultODataSerializerProvider
{
    public override ODataSerializer GetODataPayloadSerializer(Microsoft.OData.Edm.IEdmModel model, Type type, System.Net.Http.HttpRequestMessage request)
    {
        if (type == typeof(object))
        {
            IEdmTypeReference typeReference = request.ODataProperties().Path.EdmType.ToEdmTypeReference(true);
            return GetEdmTypeSerializer(typeReference);
        }

        return base.GetODataPayloadSerializer(model, type, request);
    }
}

**Comment by LianwMS** [comment]
On *2015-01-06 16:51:26 UTC*, **cysu** commented:

Depends on ODL's template parser.

**Comment by vojtechvit** [comment]
+1 for this one. 

It's even more important when considered together with the support for PATCH of complex types https://github.com/OData/WebApi/issues/135
In some of our projects we have entities with a lot of complex properties - some of them even nested. We want to be able to patch them individually on their URLs.

**Comment by congysu** [comment]
Workaround available, we might need a sample or page.
