### ISSUE TITLE
Support unknow type converter in Web API

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#163]
Here's two scenarios:  

  1. the user has a user-defined class "utcdatetime" and this type used everywhere to define his business model. Now, he don't want to change his model and want to use utcdatetime directly in Web API.   

  2. DateTime is not in OData V4 spec. It's an unknown Edm type and by default it maps to "DateTimeOffset" in Web API . But some users want to map their "DateTime" as Edm.Date or Edm.TimeOfDay.   

So, Can WebAPI provide a type conversion logic by which the user can map the
unknown type to any known type?  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2176](http://aspnetwebstack.codeplex.com/workitem/2176)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Nov 4, 2014 at 3:26 AM
**Reported by:**	xuzhg
**Updated on:**	Dec 15, 2014 at 4:03 AM
**Updated by:**	xuzhg

**Comment by xuzhg** [comment]
Close it. Similar solution is in https://github.com/OData/WebApi/pull/600.
