### ISSUE TITLE
Multiple types were found that match the controller named 'Metadata'

### ISSUE THREAD

**Issue by TehWardy** [OData/WebApi#1630]
After updating solution to reference latest version of OData framework I am now getting this exception across my solution.

### Assemblies affected

Microsoft.AspNet.OData .. i think?

### Reproduce steps

build solution on OData V6.*
update references to V7.* using nuget, 
fix namespace changes.

### Expected result

Continued working solution

### Actual result

Exception detailed above.
I put in a hack in a custom controller selector i already had that basically takes "Microsoft.AspNet.OData.MetadataController" in this situation as it only happens when loading the root of my new OData API, everything else seems fine.

### Additional detail

The request for 'Metadata' has found the following matching controllers:
  - Microsoft.AspNet.OData.MetadataController
  - System.Web.OData.MetadataController'

**Comment by xuzhg** [comment]
@TehWardy did you uninstall the old installed web api odata nuget package before you install the new one?

**Comment by xuzhg** [comment]
@TehWardy Would you please share with us your project reference?

**Comment by icnocop** [comment]
Did you try a Clean and then Rebuild?

**Comment by TehWardy** [comment]
I have multiple OData projects in my solution but taking a couple and looking at them I see that I have the following references …

- Microsoft.OData.Core
- Microsoft.OData.Edm
- Microsoft.AspNet.Odata
- Micorsoft.AspNet.Identity.Core
- Microsoft.AspNet.Identity.Owin
- Microsoft.AspNet.Identity.EntityFramework

I have a bunch of other owin references, and I use Ninject for DI then I I have a bunch of System.Web.* stuff that comes with the WebApi / MVC framework.

No mention of System.Web.OData though.
To simplify my complex stack I wrapped up mosto f the OData / Api common construction / workings in my own wrapper around the OData / WebApi + other NTier stuff in to Core.* assemblies each of which do various pieces and have subsets of these + other references of their own, but i'm not seeing any reference at all to System.Web.Odata in my entire project stack.

That was the key thing that confused me … 
I have clearly not created a "MetadataController" else the code would have broken long before this update, so I was confused as to how this happened.

I've also picked a few of the projects and gone to the bin folders where the compilation results live and taken a look through … no System.web.OData.dll anywhere in them. 
So that perplexed me even more!

At that point I started digging through the OData code on here looking for the namespace System.Web.Odata and couldn't find it (for presumably good reason). 

I logged this when I left scratching my head thinking "hell the hell did that happen?".
I have noticed though … the hack I mentioned above … I can't remove it without the code breaking again despite all this.

Any ideas?

**Comment by jlkalberer** [comment]
@TehWardy I ran into this problem working with Azure. I had to change my publish settings to clear all files when publishing.

I'd make sure that wherever you're publishing to, you remove the old DLLs

**Comment by TehWardy** [comment]
Weird, it turns out there's some odd stuff going on in VS ... when I do a debug build if some of the dependencies exist in the release builds bin folder it seems to use those.

I guess this is a VS bug not an OData one.
Having done a clean out of the other bin folder for the release build it works fine.

**Comment by icnocop** [comment]
@TehWardy, thank you for following up with your solution.

Can this issue be closed?

**Comment by TehWardy** [comment]
Yeh I think so, seemed to be VS not OData ... sorry closing now.
