### ISSUE TITLE
Incorrect `NextLink` generated when '$skip' and '$top' operators are not all lowercase

### ISSUE THREAD

**Issue by julealgon** [OData/WebApi#1639]
When sending requests with `$skip` and `$top` not all on lowercase, the `nextLink` generated by `GetNextPageLink(int)` incorrectly fails to detect them and creates invalid URLs.

### Assemblies affected

Microsoft.AspNetCore.OData 7.0.1

### Reproduce steps

Call an OData API with uppercase `$skip` or `$top` and manually write the `@odata.nextlink` value by using `GetNextPageLink(int)`.

Sample:
- Request: `http://localhost/api/randomdata?$SKIP=1`
- PageSize: 3

### Expected result

`"@odata.nextLink":"http://localhost/api/randomdata?$skip=4"`

### Actual result

`"@odata.nextLink":"http://localhost/api/randomdata?$SKIP=1&$skip=2"`

(notice the 2 "skips" in the final URL)

### Additional detail

https://github.com/OData/WebApi/blob/d02bc61ea7b31ada1e54abbeebbecb3c5df0e3ac/src/Microsoft.AspNet.OData.Shared/GetNextPageHelper.cs#L27-L43

As can be seen here, there is no case handling at all on the query string keys, meaning that only completely lowercase will match and apply the logic.

Since OData operators can have any casing, there needs to be some handling here.

Suggestion:
- Change `switch(key)` to `switch(key.ToLower())` here:

https://github.com/OData/WebApi/blob/d02bc61ea7b31ada1e54abbeebbecb3c5df0e3ac/src/Microsoft.AspNet.OData.Shared/GetNextPageHelper.cs#L31

**Comment by KanishManuja-MS** [comment]
@julealgon Thanks for catching this. I will fix it with my next PR.
