### ISSUE TITLE
OData EdmxReader should understand EF ClrType custom annotation

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#164]
Hi,  
  
I'm working on a Web Api 2 project and I wanted to support OData query options
in my endpoints so I followed [ this ](http://www.asp.net/web-api/overview
/odata-support-in-aspnet-web-api/supporting-odata-query-options) tutorial.  
  
After some measurements I found that generating a ODataQueryOptions is a
costly operation because of the usage of the ODataConventionModelBuilder. So I
wrote my own HttpParameterBinding to build a new ODataQueryOptions faster by
using the same model EF uses as [ 802
](https://aspnetwebstack.codeplex.com/workitem/802) suggests.  
  
The code used to convert from EF model to OData model goes through
serialization and deserialization of EDMX model, but there is a bug (as
reported [ here ](https://gist.github.com/raghuramn/5864013) ) when entities
used by EF DbContext have a different namespace than DbContext. This bug
prevent the usage of constructed model by the OData pipeline (because of
entity namespace mismatch)  
  
It would be nice to have  

  * Support for ClrType custom annotation (used by EF) 
  * An hook/extension point to provide an IEdmModel inside ODataQueryParameterBinding (to increse perf by sharing EF model without rewriting the entire ODataQueryParameterBinding) 
  * A better way to share the IEdmModel between EF and OData (Serialize and Deserialize isn't so pretty)   

Attached is a simple console application that show the explained problem  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2178](http://aspnetwebstack.codeplex.com/workitem/2178)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	challenh
**Reported on:**	Nov 5, 2014 at 2:59 PM
**Reported by:**	iLMaX
**Updated on:**	Tue at 10:00 AM
**Updated by:**	challenh

#### Binary Attachments

[EdmxWriterBug.zip](http://aspnetwebstack.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=aspnetwebstack&WorkItemId=2178&FileAttachmentId=928511)

**Comment by LianwMS** [comment]
On *2015-01-06 16:49:48 UTC*, **cysu** commented:

Suggest checking RESTier (http://github.com/OData/RESTier)

**Comment by LianwMS** [comment]
On *2015-01-06 18:00:15 UTC*, **challenh** commented:

RESTier helps to build OData service on top of EF , within Web api odata's environment :
https://github.com/OData/RESTier/wiki , it is in public preview, the get-started sample @

https://github.com/OData/RESTier/wiki/Samples-1:-Getting-started---basic

just FYI: 
https://github.com/OData/RESTier/issues/5
these EF attributes are verified in RESTier (either reflected on OData Edm or no effect )： Table, Column, NotMapped, Computed, ConcurrencyCheck ,Required,MaxMinLength,Timestamp.


you are welcome to comment on the above github issue.

**Comment by xuzhg** [comment]
Close it. Please file a new issue if you have further concern. Thanks.
