### ISSUE TITLE
Question: Action Method Without Parameters Not Working

### ISSUE THREAD

**Issue by rjperes** [OData/WebApi#1642]
Hi,

The following action method causes an exception when my OData project starts:

`
[EnableQuery]
[ODataRoute("Something")]
public IActionResult GetSomething()
{
      var response = //doesn't matter
      return this.Ok(response);
}
`

The actual error is:

> The path template 'Something' on the action 'GetSomething' in controller 'Xpto' is not a valid OData path template. Resource not found for the segment 'Something'.

To be clear, this error does not show when I try to access the action - it doesn't find it - but when the project starts.

If, on the other hand, I change the route to be:

`[ODataRoute("Xpto/Something")]`

Then I get:

> The path template 'Xpto/Something' on the action 'GetSomething' in controller 'Xpto' is not a valid OData path template. Bad Request - Error in query syntax.

I would like to be able to access this method. Do I need to add it to the IEdmModel? I tried to do it like this:

`var xptoEntitySet = builder.EntitySet<Xpto>(nameof(Xpto));
var func = xptoEntitySet.EntityType.Function("Something").Returns<Xpto>();`

But no luck.
Can anyone help? Thanks in advance!

RP

**Comment by xuzhg** [comment]
@rjperes 
`Do I need to add it to the IEdmModel?` -> Yes.

Besides:
1. Make sure you want a Edm function call or Edm action call?  function call should be "Get" request method, while action call should be "Post" request method.
2. Make sure you want to call the operation (function or action) on collection of resource, or on single resource. In your scenario, `[ODataRoute("Xpto/Something")]` looks call the operation on entity set, you should model the function on collection as bellows:

```C#
var func = xptoEntitySet.EntityType.**Collection**.Function("Something").Returns<Xpto>();
```

**Comment by rjperes** [comment]
Thanks, it did work! I didn't have to add the [ODataRoute] attribute, and I don't really understand the scenarios where it is needed, but that is another question! Thanks, again!
