### ISSUE TITLE
OData $batch queries do not honor/preserve prefer headers.

### ISSUE THREAD

**Issue by preston-m-price** [OData/WebApi#1657]
I am researching an issue affecting our service where **prefer** headers are not preserved in $batch queries.

### Assemblies affected

OData WebApi lib 6.2.2

### Reproduce steps
For example this GET works as expected:
```
GET https://myservice/_odata/Entity?$select=Field1,Field2 HTTP/1.1
prefer: odata.maxpagesize=5
```
But this $batch request body does not:
```
--batch_e17f47a9-41f9-45ad-b59b-98282d06975c
Content-Type: application/http
Content-Transfer-Encoding: binary
prefer: odata.maxpagesize=5

GET https://myservice/_odata/Entity?$select=Field1,Field2 HTTP/1.1

--batch_e17f47a9-41f9-45ad-b59b-98282d06975c
```
### Expected result

The $batch response should honor the **prefer** header and respond with a limited page size and nextLink.

### Actual result

The $batch request does not honor the **prefer** header.

### Additional detail

The GET request honors the prefer header and we get a page size of 5 with a nextLink. However, the response from the $batch request does not honor the page size. Digging into the code I see the entire prefer header is missing from the ODataBatchRequestItem returned by the DefaultODataBatchHandler.ParseBatchRequestsAsync method. The [spec for multipart media types](https://tools.ietf.org/html/rfc2046#page-17) suggests that any header that does not start with “Content-“ MAY be ignored but SHOULD be retained. Is this behavior by design, or should these headers in $batch operations be retained?

I have not tested with other headers but I suspect **prefer** is not the only header affected by this behavior.

**Comment by KanishManuja-MS** [comment]
@preston-m-price According to the [standard](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#_Toc505771136), a batch request should not support this preference header. However, we did find a regression in our 7.x version of the library for the single GET request. Thanks for writing this issue, please let us know if having this with every GET request is too painful.

**Comment by preston-m-price** [comment]
I am confused by your response. The spec you referenced says: 

> The maxpagesize preference SHOULD NOT be applied to a batch request, but MAY be applied to individual requests within a batch.

In my $batch example above the header is being set in the POST body for the GET sub-request, not on the POST $batch request itself. So it seems like this should be in spec, right? Or maybe I'm misunderstanding. Does the regression you reference affect the general GET scenario or the GET sub-request within a $batch?

Thanks

**Comment by KanishManuja-MS** [comment]
@preston-m-price Sorry for the confusion, I misread your example. The regression that I mentioned references general GET scenario (for 7.x) which would also include GET sub-requests within a batch. 
I thought that you were running into this issue when you had the preference header for the batch request but not the sub-requests. Let me investigate the code again.

**Comment by biaol-odata** [comment]
Closed as merged.
