### ISSUE TITLE
Odata V4 group by with Top and skip not working

### ISSUE THREAD

**Issue by SachinKotnala** [OData/WebApi#1659]
I am not able to get groupby to work with top and skip which should be most simplest thing. I am fetching data using OData and able to get output using the query below

https://localhost:6523/api/OData/AssetUsage/?$apply=groupby((assetId,Asset/name),aggregate(interactions with sum as totalInteractions, uniqueInteractions with sum as totalUniqueInteractions))&$orderBy=totalInteractions asc

Output of the above query

However when I try to apply skip or top on the above generated output, I get an error mentioned below

https://localhost:6523/api/OData/AssetUsage/?$apply=groupby((assetId,Asset/name),aggregate(interactions with sum as totalInteractions, uniqueInteractions with sum as totalUniqueInteractions))&$orderBy=totalInteractions asc&$top=1

Error -

message": "The query specified in the URI is not valid. Could not find a property named 'Asset' on type 'Portal.Models.Entities.AssetUsage'.",

"innererror":

-"message": "Could not find a property named 'Asset' on type 'Portal.Models.Entities.AssetUsage'.",

-"type": "Microsoft.OData.ODataException",

Entity class structure

public class AssetUsage
{
    public int Id { get; set; }
    [ForeignKey("Asset")]
    public int? AssetId { get; set; }
    public int YearMonthId { get; set; }
    public int Interactions { get; set; }
    public int UniqueInteractions { get; set; }
    public DateTimeOffset Recency { get; set; }
    public virtual Asset Asset { get; set; }

}

**Comment by pielegacy** [comment]
We're needing to implement pagination powered by OData and this limitation is affecting our application as well. This seems like a pretty standard use case for OData and if this cannot be fixed we'll be forced to look into GraphQL which seems to [handle this kind of logic in a much cleaner fashion](https://graphql.org/learn/pagination/).

**Comment by biaol-odata** [comment]
@SachinKotnala Error is related to query option parsing. Not sure why the extra $top (or $skip as you mentioned) triggered the error. Do yo have more detail information such as inner stack trace available?

**Comment by SachinKotnala** [comment]
@biaol-odata Thanks for investigating this issue. I have attached inner stack trace below.

{
    "error": {
        "code": "",
        "message": "The query specified in the URI is not valid. Could not find a property named 'Asset' on type 'Portal.Models.Entities.AssetUsage'.",
        
"innererror": {
            
"message": "Could not find a property named 'Asset' on type 'Portal.Models.Entities.AssetUsage'.",
            "type": "Microsoft.OData.ODataException",
            
"stacktrace": "   at Microsoft.OData.UriParser.InnerPathTokenBinder.BindInnerPathSegment(InnerPathToken segmentToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)\r\n   at Microsoft.OData.UriParser.EndPathBinder.BindEndPath(EndPathToken endPathToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)\r\n   at Microsoft.OData.UriParser.Aggregation.ApplyBinder.BindGroupByToken(GroupByToken token)\r\n   at Microsoft.OData.UriParser.Aggregation.ApplyBinder.BindApply(IEnumerable`1 tokens)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseApplyImplementation(String apply, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseApply()\r\n   at Microsoft.AspNet.OData.Query.ODataQueryOptions.EnsureStableSortOrderBy(OrderByQueryOption orderBy, ODataQueryContext context, List`1 applySortOptions)\r\n   at Microsoft.AspNet.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)"
        }
    }
}

**Comment by biaol-odata** [comment]
@SachinKotnala The PR above should enable the case-insensitive in your scenario, among others.

**Comment by SachinKotnala** [comment]
Thanks for your prompt response @biaol-odata 
Yes, you were right. its because I am using EnableLowerCamelCase(). By turning this off, I can get the desired output. However I am using it to achieve JSON output with camel-casing. By rewriting the query in proper casing with EnableLowerCamelCase , I get another error.

**Query-**
     https://localhost:6523/api/OData/AssetUsage/?$apply=groupby((assetId,asset/name),aggregate(interactions with sum as totalInteractions, uniqueInteractions with sum as totalUniqueInteractions))&$orderBy=totalInteractions asc&$top=1

{
    "error": {
          "code": "",
           "message": "The query specified in the URI is not valid. Property or path Asset isn't available in the current context. It was removed in earlier transformation.",
          "innererror": {
            "message": "Property or path Asset isn't available in the current context. It was removed in earlier transformation.",
            "type": "Microsoft.OData.ODataException",


"stacktrace": "   at Microsoft.AspNet.OData.Query.Expressions.ExpressionBinderBase.GetFlattenedPropertyExpression(String propertyPath)\r\n   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.CreatePropertyAccessExpression(Expression source, IEdmProperty property, String propertyPath)\r\n   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindPropertyAccessQueryNode(SingleValuePropertyAccessNode propertyAccessNode)\r\n   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindExpression(SingleValueNode expression, RangeVariable rangeVariable, Type elementType)\r\n   at Microsoft.AspNet.OData.Query.OrderByQueryOption.AddOrderByQueryForProperty(IQueryable query, ODataQuerySettings querySettings, OrderByClause orderbyClause, IQueryable querySoFar, OrderByDirection direction, Boolean alreadyOrdered)\r\n   at Microsoft.AspNet.OData.Query.OrderByQueryOption.ApplyToCore(IQueryable query, ODataQuerySettings querySettings)\r\n   at Microsoft.AspNet.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)"
        }
    }
}

**Comment by biaol-odata** [comment]
@SachinKotnala I think for now you might have to use exact casing. And I hope that after the PR is merged, your case of camelCase will work.

**Comment by SachinKotnala** [comment]
@biaol-odata Thanks for your efforts. Use of exact casing has resolves the issue for me. Thanks again.

**Comment by pielegacy** [comment]
I too had this issue! Thank you @SachinKotnala for helping and @biaol-odata

**Comment by biaol-odata** [comment]
@SachinKotnala We should keep this opened until the PR is merged.

**Comment by madansr7** [comment]
closing since the PR has been merged and the issue has been resolved.
