### ISSUE TITLE
Typo routePrerix

### ISSUE THREAD

**Issue by cornem** [OData/WebApi#1679]
There is a typo here:

https://github.com/OData/WebApi/blob/90a24d55715b0afe54404a34bf2df4e0c870de14/src/Microsoft.AspNetCore.OData/Extensions/ODataApplicationBuilderExtensions.cs#L62

The variable `routePrerix` should probably be renamed to `routePrefix`.

### Assemblies affected

Microsoft.AspNetCore.OData, Version 7.0.1

**Comment by biaol-odata** [comment]
Closed as merged.
