### ISSUE TITLE
v5.6: Add support for date(Edm.DateTimeOffset) function

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#168]
OData v.4 [ date ](http://docs.oasis-
open.org/odata/odata/v4.0/errata01/os/complete/part2-url-
conventions/odata-v4.0-errata01-os-part2-url-conventions-
complete.html#_Toc395267151) function in queries like  

    
    
    http://localhost:8084/Alerts?$filter=date(DateAlert) gt 2014-06-19

throws  

    
    
    {
      "error":{
        "code":"","message":"The query specified in the URI is not valid. Unknown function 'date'.","innererror":{
          "message":"Unknown function 'date'.","type":"System.NotImplementedException","stacktrace":"   at System.Web.OData.Query.Expressions.FilterBinder.BindSingleValueFunctionCallNode(SingleValueFunctionCallNode node)\r\n   at System.Web.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)\r\n   at System.Web.OData.Query.Expressions.FilterBinder.BindBinaryOperatorNode(BinaryOperatorNode binaryOperatorNode)\r\n   at System.Web.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)\r\n   at System.Web.OData.Query.Expressions.FilterBinder.BindExpression(SingleValueNode expression, RangeVariable rangeVariable, Type elementType)\r\n   at System.Web.OData.Query.Expressions.FilterBinder.Bind(FilterClause filterClause, Type filterType, IEdmModel model, IAssembliesResolver assembliesResolver, ODataQuerySettings querySettings)\r\n   at System.Web.OData.Query.FilterQueryOption.ApplyTo(IQueryable query, ODataQuerySettings querySettings, IAssembliesResolver assembliesResolver)\r\n   at System.Web.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\r\n   at System.Web.OData.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)\r\n   at System.Web.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor)\r\n   at System.Web.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)"
        }
      }
    }

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2185](http://aspnetwebstack.codeplex.com/workitem/2185)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Nov 10, 2014 at 1:57 PM
**Reported by:**	cdori
**Updated on:**	Tue at 8:39 AM
**Updated by:**	cysu

**Comment by LianwMS** [comment]
On *2015-01-06 16:39:17 UTC*, **cysu** commented:

Based on another feature of Edm.Date in v5.5.

**Comment by xuzhg** [comment]
I think it's supported as commit: aa53472
