### ISSUE TITLE
[feature/netcore] RouteAttribute causes AmbiguousActionException

### ISSUE THREAD

**Issue by cornem** [OData/WebApi#1682]
I am adding OData actions to an existing API. I want the OData-enabled endpoint to be available under the same route as my existing actions. My controller was available under `/api/salesorders`. I have changed the controller so it now inherits from `ODataController`. I have added these actions:
````
public SalesOrdersController : ODataController
{
    [EnableQuery]
    public IQueryable<SalesOrder> Get()
    {
        return _context.SalesOrders;
    }

    [EnableQuery]
    public SalesOrder Get(int key)
    {
        return _context.SalesOrders.Find(key);
    }
}
````

In my `Startup` class, I have registered OData:

    app.UseMvc(routes =>
    {
        routes.Select().Expand().Filter().OrderBy().MaxTop(100).Count();
        routes.MapODataServiceRoute("odata", "api", GetEdmModel());
    });

This works while there is no controller-level `RouteAttribute` specified. If I add `[Route("api/salesorders")]` to the controller (for the benefit of my non-OData actions), the request `GET /api/salesorders` will fail with an `AmbiguousActionException`. (It now considers the `Get()` and `Get(int key)` as ambiguous. Note that `GET /api/salesorders(1)` will still succeed.)

Adding additional `[HttpGet]` or `[ODataRoute]` attributes on the `Get()` and `Get(int key)` actions makes no difference.

### Assemblies affected

Microsoft.AspNetCore.OData 7.0.1

### Reproduce steps

- Create a new ASP.NET Core project
- Configure OData
- Add an OData controller with a `Get()` and `Get(int key)` method
- Add `[Route("someroute")]` to the controller
- Try to access the `Get()` action

### Expected result

The `Get()` action method should be executed.

### Actual result

The request fails with an `AmbiguousActionException`.

**Comment by raheph** [comment]
@cornem Can you try "[ODataRoute]" attribute and let us know the result? Thanks.

**Comment by cornem** [comment]
@raheph I'm at a loss as to how I should use it then. I have tried the following (just to be clear, the controller has this attribute: '[Route("api/salesorders")]`):

```
[EnableQuery, ODataRoute]
public IQueryable<SalesOrder> Get()             // AmbiguousActionException

[EnableQuery, ODataRoute]
public SalesOrder Get(int key)                  // Works
```
```
[EnableQuery, ODataRoute(RouteName = "odata")]
public IQueryable<SalesOrder> Get()             // AmbiguousActionException

[EnableQuery, ODataRoute(RouteName = "odata")]
public SalesOrder Get(int key)                  // Works
```
```
[EnableQuery, ODataRoute("SalesOrders")]
public IQueryable<SalesOrder> Get()             // AmbiguousActionException

[EnableQuery, ODataRoute("SalesOrders({key})")]
public SalesOrder Get(int key)                  // Works
```
```
[EnableQuery, ODataRoute("api/SalesOrders")]
public IQueryable<SalesOrder> Get()             // AmbiguousActionException

[EnableQuery, ODataRoute("api/SalesOrders({key})")]
public SalesOrder Get(int key)                  // InvalidOperationException
```

So how should `[ODataRoute]` be applied when using `[Route]` on the controller?
As a temporary fix, I can make everything work by removing `[Route]` from the controller, and adding attributes to my non-OData actions.

However, it would be great if OData wouldn't break when using controller-level attribute routing.

**Comment by biaol-odata** [comment]
@cornem You shouldn't mix WebAPI [Route] with OData-WebAPI [ODataRoute]. For annotating the controller, you should use [ODataRoutePrefix].
