### ISSUE TITLE
$filter on nested collection items does not work

### ISSUE THREAD

**Issue by kedrzu** [OData/WebApi#1696]
I want to make some filter over items in a nested collection:
`ClassTypes?$filter=customAttributes/any(d: d/attributeDefinitionId eq 48)`

I'm getting error, that property `attributeDefinitionId` is not filterable, although it is. I can filter on property when accessing entity directly.

### Assemblies affected

OData WebApi lib 6.1.0
OData WebApi lib 7.1.0

Probably also other between those (those two I checked).

### Reproduce steps

Suppose I have an entity, with collection as prop:

```
public class ClassType {
    [Key]
    public long Id { get; set; }
    
    // some more properties here

    public ICollection<ClassTypeCustomAttribute> CustomAttributes { get; set; }
}

public class ClassTypeCustomAttribute {
    [Key, Column(Order = 1)]
    public long AttributeDefinitionId { get; set; }

    // some more properties here
}
```

In model builder I marked `ClassType.CustomAttributes` property to be both expandable and filterable, and marked `ClassTypeCustomAttribute.AttributeDefinitionId` to be filterable.

Expanding works well, filtering by `ClassTypeCustomAttribute.AttributeDefinitionId` works fine, when querying `ClassTypeCustomAttribute` entity directly.

However when I want to query `ClassType` and filter out by `CustomAttributes` property, it fails. Heres exemplary query:
`ClassTypes?$filter=customAttributes/any(d: d/attributeDefinitionId eq 48)`

### Expected result

It should definitely be able to be filtered.

### Actual result

It gives me error:
```
{
    "error": {
        "code": "",
        "message": "The query specified in the URI is not valid. The property 'attributeDefinitionId' cannot be used in the $filter query option.",
        "innererror": {
            "message": "The property 'attributeDefinitionId' cannot be used in the $filter query option.",
            "type": "Microsoft.OData.ODataException",
            "stacktrace": "   at Microsoft.AspNet.OData.Query.Validators.FilterQueryValidator.ValidateSingleValuePropertyAccessNode(SingleValuePropertyAccessNode propertyAccessNode, ODataValidationSettings settings)\r\n   at Microsoft.AspNet.OData.Query.Validators.FilterQueryValidator.ValidateLogicalOperator(BinaryOperatorNode binaryNode, ODataValidationSettings settings)\r\n   at Microsoft.AspNet.OData.Query.Validators.FilterQueryValidator.ValidateLogicalOperator(BinaryOperatorNode binaryNode, ODataValidationSettings settings)\r\n   at Microsoft.AspNet.OData.Query.Validators.FilterQueryValidator.ValidateAnyNode(AnyNode anyNode, ODataValidationSettings settings)\r\n   at Microsoft.AspNet.OData.Query.FilterQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ValidateQuery(HttpRequestMessage request, ODataQueryOptions queryOptions)\r\n   at PerfectGym.Api.Core.ODataQueryableAttribute.ValidateQuery(HttpRequestMessage request, ODataQueryOptions queryOptions) in D:\\PerfectGym\\PerfectGym.Api.V2\\Core\\ODataQueryableAttribute.cs:line 81\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.<>c__DisplayClass0_0.<OnActionExecuted>b__3(ODataQueryContext queryContext)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)"
        }
    }
}
```

### Additional detail

I did some debugging of the AspNet.OData library (in version both 6.1 and 7.1), and found some very cumbersome logic for calculating which property is filterable and which is not.
Check this exact method `EdmLibHelpers.IsNotFilterable`:
https://github.com/OData/WebApi/blob/12d998c0e60ed9bcf1a45dbdc650a51a3578b763/src/Microsoft.AspNet.OData.Shared/Formatter/EdmLibHelpers.cs#L285

It is called when applying query validator. When the validation is applied to abovementioned property `attributeDefinitionId`:
- parameter `edmProperty` points to this property (I mean `ClassTypeCustomAttribute.AttributeDefinitionId`)
- parameter `pathEdmProperty` is null (it is taken from `_property` field in validator which is set to null on initializing the validator)
- parameter `pathEdmStructuredType` is pointing to EDM type for `ClassTypeCustomAttribute` as expected
- parameter `edmModel` is the whole EDM model
- parameter `enableFilter` is some default from query settings (`false` in my case)

So far so good. But check on call to method `GetModelBoundQuerySettings` 
https://github.com/OData/WebApi/blob/12d998c0e60ed9bcf1a45dbdc650a51a3578b763/src/Microsoft.AspNet.OData.Shared/Formatter/EdmLibHelpers.cs#L301

Here you see, `pathEdmProperty` is passed, which is `null`.

Inside of this `GetModelBoundQuerySettings` method lays logic for calculating dictionary, that maps properties to whether they are filterable or not.

https://github.com/OData/WebApi/blob/12d998c0e60ed9bcf1a45dbdc650a51a3578b763/src/Microsoft.AspNet.OData.Shared/Formatter/EdmLibHelpers.cs#L567

And this is the part that is very shady: this dictionary is not calculated for the type we are checking, but for the parent one: `ClassType`.
These settings are merged with some other dictionary, calculated from property, but since property is null, nothing is merged in fact.

And here lays the dragon: we check if some property from nested type is filterable, by checking if property with the same name, but for parent type is filterable!
I mean, we check if `ClassTypeCustomAttribute.AttributeDefinitionId` is filterable by searching dictionary that contains properties of `ClassType`.
For example, it by accident, there would property with the same name: `ClassType.AttributeDefinitionId` and it would be filterable, it would work!

**Comment by KanishManuja-MS** [comment]
@kedrzu This does look like a bug. Thanks for pointing out and we appreciate the details in this issue.

Since you have already done quite a bit of investigation, it would be great if you can submit a PR for the fix. Please let us know if that is something you 'd consider.

**Comment by kedrzu** [comment]
@KanishManuja-MS I don't know OData codebase, my investigation was purely based on live debugging my application with OData decompiled with R#. 

I think that this fix may involve some deeper change. There are few intermediate structures, that hold information extracted from EDM model, and their purpose is somewhat shady.

I may try to look at the code and fix it, but cannot promise that.

**Comment by mikepizzo** [comment]
@kedrzu  -- thanks for the detailed investigation. We'll look at trying to get this fixed.
