### ISSUE TITLE
ODataConventionModelBuilder doesn't work with MetadataTypeAttribute

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#17]
This scenario is quite common in EF DB generated code. User can't change
generated code. So they have to use metadata type to specify the data
annotation attributes.  

For example, I have model:  

```
[MetadataType(typeof(TodoModel))]
public class Todo
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class TodoModel
{
    [Required]
    public string Name { get; set; }
}

   static IEdmModel GetEdmModel()
    {
        ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
        builder.EntitySet<Todo>("Todo");
        return builder.GetEdmModel();
    }
```

The required attribute will not be recognized in conventions.  
## Work Item Details

**Original CodePlex Issue:**    [Issue 515](http://aspnetwebstack.codeplex.com/workitem/515)
**Status:** Active
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Oct 6, 2012 at 12:43 AM
**Reported by:**    hongyes
**Updated on:** Apr 30, 2014 at 5:29 PM
**Updated by:** lybax

**Comment by LianwMS** [comment]
On *2012-10-09 07:29:35 UTC*, **HongmeiG** commented:

We can add this feature to post BUILD.

**Comment by LianwMS** [comment]
On *2014-05-01 00:29:39 UTC*, **lybax** commented:

Both Required attribute and PrimitiveTypeConfiguration IsRequired method are now working (latest nightly).
builder.EntitySet<Country>("Countries").EntityType.Property(x => x.Name).IsRequired()
Another useful string data annotation is however still missing:

MaxLength (EF's HasMaxLength method)

**Comment by xuzhg** [comment]
`MetadataTypeAttribute` specifies the metadata class to associate with a data model class.

You use the MetadataTypeAttribute attribute as follows:

•In your application, create a file in which you create the data-model partial class that you want to modify. 


•Create the associated metadata class. 


•Apply the MetadataTypeAttribute attribute to the partial entity class, specifying the associated class. 


When you apply this attribute, you must adhere to the following usage constraints:

•The attribute can only be applied to a class.


•The attribute cannot be inherited by derived classes.


•The attribute can be applied only one time.

**Comment by xuzhg** [comment]
[MetadataType(typeof(EFCustomerMetadataType))]
    public class EfCustomer
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }

    public class EFCustomerMetadataType
    {
        [Required]
        public string Name { get; set; }
    }

**Comment by xuzhg** [comment]
I think we can support it in 5.9.
