### ISSUE TITLE
Open type and dynamic property on un-type scenario

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#171]
Support Open type and dynamic property on un-type scenario.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2193](http://aspnetwebstack.codeplex.com/workitem/2193)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Nov 25, 2014 at 9:16 AM
**Reported by:**	xuzhg
**Updated on:**	Tue at 8:34 AM
**Updated by:**	cysu

**Comment by LianwMS** [comment]
On *2015-01-06 16:34:08 UTC*, **cysu** commented:

Review together with other untyped features.

**Comment by VikingsFan** [comment]
Checked in 07ae38d4cc1184285a826c72735d2df2c47c6354
