### ISSUE TITLE
v5.6: ETagMessageHandler is not supporting Typeless Entities

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#172]
ETagMessageHandler is not generating ETag for Type less models(entities).  
In SendAsync method, it is trying get the edmEntityType from the value in the
response. It works for typed model but in case of type less model(entities)
the type of the value would be EdmEntityObject which will not exist in model
hence EdmTypeReference would be null.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2196](http://aspnetwebstack.codeplex.com/workitem/2196)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Nov 28, 2014 at 5:03 AM
**Reported by:**	sasikalasandu
**Updated on:**	Tue at 8:23 AM
**Updated by:**	cysu

**Comment by LianwMS** [comment]
On *2015-01-06 16:23:09 UTC*, **cysu** commented:

Review with other typeless asks.

**Comment by xuzhg** [comment]
Fixed. Thanks.
