### ISSUE TITLE
Implement custom DefaultODataSerializerProvider in ASP.Net Core

### ISSUE THREAD

**Issue by JafarAmiri** [OData/WebApi#1721]
Hi,
I am trying to implement custom DefaultODataSerializerProvider in Asp.Net Core. 

**Assemblies affected**

Microsoft.AspNetCore.OData, Version=7.0.1.20718

**Expected result**

I need to have a class like ODataEntityTypeSerializer to override CreateStructuralProperty method.

**Question**
How can I implement a CustomODataEntityTypeSerializer in ASP.Net Core?

**Comment by xuzhg** [comment]
Hi, JafarAmiri

can the tests in "https://github.com/OData/WebApi/blob/master/test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/ODataFormatterTests.cs#L338-L398" answer your question?

**Comment by JafarAmiri** [comment]
Hi xuzhg,
Thank you for your reply.
I have implemented a custom ODataResourceSerializer and the problem has been solved.
