### ISSUE TITLE
DeleteRef Fails if navigation property is a derived type

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#173]
I've got a problem that a DeleteRef fails when the navigation property is a
derived type of a entityset type. It will fail on the $id, because the
ElementType.Definition doesn't match the id.edmType in the
DefaultODataPathHandler.  
  
What I did was I created and entity called Destination which is a base entity,
that for example can be used as target for an email. Then i created an entity
call DestinationGroup which inherits from Destination and is used to create
groups of destinations. So Destination has a navigation property named Parents
that points to a collection of DestinationGroup and DestinationGroup has a
navigation property named Children that points to a collection of Destination.  
  
In the OData Controller i've implemented the CreateRef and DeleteRef methods
and they work for:  

  * Create Reference between DestinationGroup and Destination over Children property, 
  * Delete Reference between DestinationGroup and Destination over Children property. 
  * Create Reference between Destination And DestinationGroup over Parents property.   

It only fails when deleting a reference between Destination and
DestinationGroup over parents property, because the navigation property
expects a DestinationGroup and the $id collection resolves a destination
Entity.  
  
The part of code fails in the DefaultODataPathHandler:  

    
    
     if (!enableUriTemplateParsing && path.LastSegment is Semantic.NavigationPropertyLinkSegment)
                {
                    IEdmCollectionType lastSegmentEdmType = path.LastSegment.EdmType as IEdmCollectionType;
    
                    if (lastSegmentEdmType != null)
                    {
                        Semantic.EntityIdSegment entityIdSegment = null;
                        bool exceptionThrown = false;
    
                        try
                        {
                            entityIdSegment = uriParser.ParseEntityId();
    
                            if (entityIdSegment != null)
                            {
                                // Create another ODataUriParser to parse $id, which is absolute or relative.
                                ODataUriParser parser = new ODataUriParser(model, serviceRootUri, entityIdSegment.Id);
                                id = parser.ParsePath().LastSegment as Semantic.KeySegment;
                            }
                        }
                        catch (ODataException)
                        {
                            // Exception was thrown while parsing the $id.
                            // We will throw another exception about the invalid $id.
                            exceptionThrown = true;
                        }
    
                        if (exceptionThrown ||
                            (entityIdSegment != null &&
                                (id == null || lastSegmentEdmType.ElementType.Definition != id.EdmType)))
                        {
                            throw new ODataException(Error.Format(SRResources.InvalidDollarId, queryString.Get("$id")));
                        }
                    }
                }

Derived types aren't included in the comparison, so it will fail on the entity
type comparison  

    
    
    lastSegmentEdmType.ElementType.Definition != id.EdmType

I've attached a sample Project with the destinations entities and controller.
You only need to attach the System.Web.OData library.  
  
Maybe a valid solution would be something like this:  

    
    
    if (exceptionThrown ||
      (entityIdSegment != null &&
        (id == null || 
         !(lastSegmentEdmType.ElementType.Definition.IsOrInheritsFrom(id.EdmType) || 
           id.EdmType.IsOrInheritsFrom(lastSegmentEdmType.ElementType.Definition)))))
          {
            throw new ODataException(Error.Format(SRResources.InvalidDollarId, queryString.Get("$id")));
          }

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2197](http://aspnetwebstack.codeplex.com/workitem/2197)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Dec 1, 2014 at 3:08 PM
**Reported by:**	Jeroen_Smits
**Updated on:**	Tue at 8:21 AM
**Updated by:**	cysu

#### Binary Attachments

[DeleteRef Issue.zip](http://aspnetwebstack.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=aspnetwebstack&WorkItemId=2197&FileAttachmentId=959974)

**Comment by LianwMS** [comment]
On *2015-01-06 16:21:44 UTC*, **cysu** commented:

Suggest fix.

**Comment by xuzhg** [comment]
Resolved: 
9a039b1252e4a9b7e554104ee42f72f41f5b9348
