### ISSUE TITLE
Publish symbols packages to NuGet

### ISSUE THREAD

**Issue by robertmclaws** [OData/WebApi#1740]
## Issue
OData builds should include symbols packages to make it easier to debug issues with the core OData framework from other libraries.

## Suggestion
[Implement the proper changes](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg) to generate `*.snupkg` packages during the build, and have them published to NuGet.

## Additional Information
- [NuGet spec for symbols packages](https://github.com/NuGet/Home/wiki/NuGet-Package-Debugging-&-Symbols-Improvements).

**Comment by xuzhg** [comment]
@robertmclaws FYI, we publish the symbols for each release at https://nuget.smbsrc.net/

See http://odata.github.io/WebApi/10-01-debug-webapi-source/

**Comment by phatcher** [comment]
Can I also suggest including SourceLink support

**Comment by gathogojr** [comment]
The symbol package is currently published to Nuget. One for current Microsoft.AspNetCore.OData 7.5.14 package is available [here](https://www.nuget.org/api/v2/symbolpackage/Microsoft.AspNetCore.OData/7.5.14)
