### ISSUE TITLE
change parameter name from key to id

### ISSUE THREAD

**Issue by ericbehughes** [OData/WebApi#1745]
It's impossible to change the parameter name from key to id
### Assemblies affected

Microsoft.AspNetCore.OData 7.1.0
Microsoft.AspNetCore 2.2.0

### Reproduce steps

     [HttpGet]
        public SingleResult<SomeObject> Get(int id)

### Expected result

Method gets hit 

### Actual result

Method does not get hit and goes to Get() with no parenthesis

### Additional detail

c# for the win

**Comment by gathogojr** [comment]
Issue from 2019. Issue reporter advised on a solution. No fresh activity since
