### ISSUE TITLE
@odata.nextLink ignores query parameters like $select, $expand 

### ISSUE THREAD

**Issue by osemyonov** [OData/WebApi#1756]
Get item by key with expand navigation property
e.g.  **Item(1)**?$select = ID&**$expand**=Property1 (collection), Property2

in response:
navigation Property1 collection **oversteps** default Pagesize

**The issue**:
OData lib generates @odata.netxLink without odata query parameters like $select etc:
@odata.nextLink: http://server/item(1)/Property?$skip = Pagesize

### Assemblies affected

"Microsoft.OData.Core" version="7.5.0"
"Microsoft.OData.Edm" version="7.5.0"
"Microsoft.AspNet.OData" version="7.0.1"
"Microsoft.AspNet.WebApi" version="5.2.6"

targetFramework="net472"

**Comment by KanishManuja-MS** [comment]
@osemyonov Do you want to apply $select to the Property1? If that is the case, you should have it inside the expand clause like - $expand=Property1($select=ID). The nextlink that you are sharing is for the expanded collection resource and the $select is applied for the top-level item resource. 

The nextlink will not have the $select due to a different issue which is being fixed

**Comment by osemyonov** [comment]
No,
I don't want to apply $select to the Property1. It is clear from my sample.

It is just a query sample to explain the issue. I simplified more complex request. 

To avoid a confuse let's replace my query sample to another:
Item(1)?$select = ID&$expand=Property1 ($select=ID)

In my simple sample I want:
1) In single result I select only Id
2) In single result I want to expand Property1 as collection

The issue:
If 2) inner collection results oversteps pagesize (e.g. 100) 
Odata lib generates incorrect 'next' link without $select for Item and for inner collection (2)
Item(1)/Property1?$skip=100"

I would expect to see the next response:
@odata.nextLink: http://server/Item(1)?$select = ID&$expand=Property1 (**$skip=PageSize**, $select=ID)

I mean if odata lib sees pagination in inner collection, $skip and $top should be inject into $expand

Let me know if I should explain this issue in details

**Comment by KanishManuja-MS** [comment]
@osemyonov Yes. I understand the issue. It does seem to be a subset of #1722.

**Comment by KanishManuja-MS** [comment]
#1724 fixes this.
