### ISSUE TITLE
Get generated SQL query from IQueryable odata

### ISSUE THREAD

**Issue by nitish29391** [OData/WebApi#1759]
**I am trying to get sql query which is generated after I pass commands in URL**

*For Example if I hit below URL*

    http://localhost:57097/Lead?$filter=LeadId eq 9254238 and AssignedToID eq 21987

Then I am expecting generated SQL query which OData generates to fetch data from database.

*Expected Result:*

> select * from lead where LeadId = 9254238 and AssignedToID = 21987

**Comment by xuzhg** [comment]
@nitish29391 Web API OData creates the linq expression based on the $filter clause, that expression is converted into SQL by the a SQL provider, such as the Entity Framework. If that provider doesn't have such tracing ability, you can use Database profile tools.

**Comment by KanishManuja-MS** [comment]
@nitish29391 Does that answer your question? Should we close this one?

**Comment by NickBehrends** [comment]
FYI if using EF Core you can setup a logging factory and odata queries will be logged as well. Something like:

        //Dump EF SQL to output window
        public static readonly LoggerFactory _myLoggerFactory =
            new LoggerFactory(new[] {
                new Microsoft.Extensions.Logging.Debug.DebugLoggerProvider()
            });

        public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseLoggerFactory(_myLoggerFactory);
        }
