### ISSUE TITLE
OData writer raw json string, no serialization

### ISSUE THREAD

**Issue by rossbuggins** [OData/WebApi#1760]
If a data source is returning json (eg mongodb) from an odata linq query, how best to write this as odata output, without having to derialize into objects to then serialise this again before writing out? This is for a simple odata feed, with no expands etc. Would it need a custom ODataWriter? Thanks

**Comment by xuzhg** [comment]
@rossbuggins Can you customize the OData serializer to accomplish that?

**Comment by KanishManuja-MS** [comment]
@rossbuggins Does that work for you? We would like to close this issue if that is the case.
