### ISSUE TITLE
Nuget package dependencies

### ISSUE THREAD

**Issue by raffaeler** [OData/WebApi#1761]
*Summary*
In a project we are using Microsoft.AspNetCore.OData package version 7.10
These packages have dependencies over the AspNetCore 2.0 assemblies, while we need to use version 2.1.
As a result, the 2.0 version of an ASP.NET Core assembly is loaded and a method not found exception is thown, since that method is only available starting from version ASP.NET Core 2.1.

Please provide updated packages to support ASPNET Core version 2.1

### Packages affected
- Microsoft.AspNetCore.OData
- Microsoft.OData.Core

### Reproduce steps

Create a project with the follwing packages and look at the deps json file to see the dependencies on the version 2.0 of ASP.NET Core assemblies

```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="7.1.0" />
    <PackageReference Include="Microsoft.OData.Core" Version="7.5.3" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.5.0" />
    <PackageReference Include="System.Diagnostics.Tracing" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Handles" Version="4.3.0" />
    <PackageReference Include="System.Runtime.InteropServices" Version="4.3.0" />
  </ItemGroup>
```

**Comment by raffaeler** [comment]
#### More info 

When the project does not reference OData, we can load and run ` EntityFrameworkCore 2.2`.
As soon as OData is referenced an exception is thrown: `FileNotFoundException` for `Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.2.0.0`

We can see in the deps.json file, that OData references the 2.1 release.
This means that `Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.1` is loaded from OData (overwriting the 2.2 version in the bin folder).
As soon as EF Core tries to load version 2.2, the `FileNotFoundException` is thrown.

**Comment by gathogojr** [comment]
List of frameworks supported by Microsoft.AspNetCore.OData library are netcoreapp3.1 and netstandard2.0.
