### ISSUE TITLE
AspNetCore + EfCore Odata $top adds an additional Order by 

### ISSUE THREAD

**Issue by baywet** [OData/WebApi#1765]
When adding $top to a request that already has a $orderby, the underlying SQL query contains 2 order by clauses instead of one. One on the order by property and one on the primary key. It should only have one on the order by key.

### Assemblies affected
OData Web API 7.1.0

### Reproduce steps

Consider the following data structure:
```CSharp
public class Sensor
{
public Guid Id {get;set;}
}
public class DataPoint
{
public Guid Id {get;set;}
public Sensor Sensor {get;set;}
public DateTimeOffset ReadTimeUTC { get;set;}
}
```
Now imagine you have a EFCore DbContext with DataSets of DataPoints and Sensors.
Here is my action
```CSharp
[EnableQuery]
        public async Task<IActionResult> GetDataPointsFromSensor([FromODataUri] Guid key)
        {
            try
            {
                return Ok(_dbContext.DataPoints.Where(x => x.SensorId == key));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "");
                return StatusCode(500);
            }
        }
```
Consider this request `/api/Sensors/080300c5-5fd6-4e0f-8695-6a5af8f622f5/DataPoints?$top=1&$orderby=ReadTimeUTC desc`
### Expected result
Should be translated by this query
```SQL
SELECT TOP(1) [x].[Id], [x].[ReadTimeUtc], [x].[SensorId], [x].[TenantId], [x].[Value]
FROM [DataPoints] AS [x]
WHERE [x].[SensorId] = '080300c5-5fd6-4e0f-8695-6a5af8f622f5'
ORDER BY [x].[ReadTimeUtc] DESC
```
### Actual result
Gets translated by this query
```SQL
SELECT TOP(1) [x].[Id], [x].[ReadTimeUtc], [x].[SensorId], [x].[TenantId], [x].[Value]
FROM [DataPoints] AS [x]
WHERE [x].[SensorId] = '080300c5-5fd6-4e0f-8695-6a5af8f622f5'
ORDER BY [x].[ReadTimeUtc] DESC, [x].[Id]
```

**Comment by NetTecture** [comment]
At least you example is wrong. ReadTimeUTC is no necessarily unique, and as such it is not suitable as a key that has to GUARANTEE a similar order. As such, at least in this case, the key is added to make sure the order is ALWAYS guaranteed.

**Comment by baywet** [comment]
hum, I had not thought of it this way, thanks!
So let's suppose that I add another column DataPointOrderHash, which is a concat of epoch + primary key and has a unique contraint, adapting my OData request to order by that column instead, should that result in a SQL query with only one order by statement?

**Comment by NetTecture** [comment]
Theoretically yes, but I think there is no way to express this guarnateed uniqueness in the configuration so you will not stop odata from "forcing" known order without a LOT of code rewriting and possibly making your own version. So, the answer is likely no.

**Comment by baywet** [comment]
So basically the OData provider will more or less always add an additional order by statement on the primary key whenever there is a $top to guarantee idempotence if the $orderby is not on the primary key. Then it's a matter of me choosing the right primary key if I want to optimize this scenario.
Thanks a lot! that clarifies it, closing.
