### ISSUE TITLE
Unable use REST Routes

### ISSUE THREAD

**Issue by Daniel127** [OData/WebApi#1769]
How can I use the REST routes with OData?.

The OData Routes are:

"api/v1/MyEntity"
"api/v1/MyEntity({key})"

But, i want this:

"api/v1/MyEntity"
"api/v1/MyEntity/{id}"

**Comment by xuzhg** [comment]
@Daniel127 

The latest version of ASP.NET OData ([Core](https://www.nuget.org/packages/Microsoft.AspNetCore.OData/)/[Classic](https://www.nuget.org/packages/Microsoft.AspNet.OData/)) enables key as segment by default. Would you please try it out.  Thanks.
