### ISSUE TITLE
WebAPI OData V3 EntityReference links do not support $inlinecount query option

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#178]
When requesting entity reference links with $inlinecount option, the result
does not contains the actual count. In ODataEntityReferenceLinksSerializer
class, Count value of ODataEntityReferenceLinks was not set.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2208](http://aspnetwebstack.codeplex.com/workitem/2208)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Dec 8, 2014 at 2:55 AM
**Reported by:**	karata
**Updated on:**	Tue at 8:09 AM
**Updated by:**	cysu

**Comment by LianwMS** [comment]
On *2015-01-06 16:09:16 UTC*, **cysu** commented:

Also fix v4's $count.

**Comment by xuzhg** [comment]
Resolved:
25216c23e3196fd4abbe01fb7577ea05124559ea
