### ISSUE TITLE
Unable to PATCH a complex property on an Open Type

### ISSUE THREAD

**Issue by andyward** [OData/WebApi#1780]
Given an open type `A` and EntitySet `AEntities`, and a Complex Type of `B`, it IS possible to patch an `A` Entity with a Collection of `B`s as follows:

```
PATCH /odata/AEntities(1)
{
    'BCollection@odata.type':'#Collection(B)',
    'BCollection': [{ 'Foo': 'bar' }]
}
```
... however it's NOT possible to PATCH a single Property with a Complex Type of `B`:

```
PATCH /odata/AEntities(1)
{
    'B': {
         '@odata.type':'#B',
         'Foo': 'bar'
   }
}
```
There seems to be an issue in the deserialisation of `Delta<A>` that causes this discrepancy. 

Is this supported?

### Assemblies affected

OData 7.1.0 on .NET Framework.

### Reproduce steps

I've created a E2E test with a more real-world example in the existing `OpenType/TypedTest` class that reproduces the issue using the standard test controllers: https://github.com/andyward/WebApi/commit/9cd34ff6176380cfa89d7b23d57a5535e663fd68

### Expected result

I would expect `A.B` to be deserialised in `Delta<A>` so the property could be persisted.

### Actual result

`Delta<A>.B` is null, while `Delta<A>.BCollection` is instantiated and populated with deserialised array of Bs

### Additional detail

The Controller Action is defined as

``` csharp
[HttpPatch]
public IActionResult Patch(int key, [FromBody]Delta<A> patch, ODataQueryOptions<A> queryOptions)
{
    // Patch implementation
}
```

**Comment by xuzhg** [comment]
@andyward Thanks for reporting it to us. we will take a look. Basically, i think it supports. Thanks.

**Comment by raheph** [comment]
@xuzhg please take a look

**Comment by andyward** [comment]
Did you get a chance to look at this @xuzhg ?

**Comment by jinhong-** [comment]
Any updates? We seem to be experiencing the same issue
