### ISSUE TITLE
IModelConfiguration

### ISSUE THREAD

**Issue by grahamehorner** [OData/WebApi#1783]
As a developer I would like to use DependencyInjection of the IServiceCollection into the constructor of the IModelConfiguration so I may configure additional services/resources at start up at present this is not working and IServiceCollection is not getting resolved at runtime.

**Comment by xuzhg** [comment]
@grahamehorner Would you please share more detail usage about your IModelConfiguration?

**Comment by grahamehorner** [comment]
the IModelConfiguration is shown below:-

        public void Apply(ODataModelBuilder builder, ApiVersion apiVersion)
        {
            var cachePolicy = builder.EntitySet<ItemCachePolicy>("ItemCachePolicy")
                .EntityType;
            cachePolicy.HasKey(e => e.ID);
        }

**Comment by grahamehorner** [comment]
resolved
