### ISSUE TITLE
WebAPI V3 EntityReferences Link does not support JSON & doesn't support GET

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#179]
When requesting EntityReferences with JSON, the response contains following
message:  
  
{  
"odata.error":{  

    
    
    "code":"","message":{
      "lang":"en-US","value":"An error has occurred."
    },"innererror":{
      "message":"The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; charset=utf-8'.","type":"System.InvalidOperationException","stacktrace":"","internalexception":{
        "message":"The entity set name or navigation property name for the top level entity reference link collection is unknown. When writing a JSON response, the entity set and navigation property must be passed to the ODataMessageWriter.WriteEntityReferenceLinks method or the ODataEntityReferenceLinksSerializationInfo must be set on the ODataEntityReferenceLinks.","type":"Microsoft.Data.OData.ODataException","stacktrace":"   at Microsoft.Data.OData.JsonLight.ODataJsonLightMetadataUriBuilder.DefaultMetadataUriBuilder.TryBuildEntityReferenceLinksMetadataUri(ODataEntityReferenceLinksSerializationInfo serializationInfo, IEdmEntitySet entitySet, IEdmNavigationProperty navigationProperty, Uri& metadataUri)\r\n   at Microsoft.Data.OData.JsonLight.ODataJsonLightEntityReferenceLinkSerializer.WriteEntityReferenceLinksImplementation(ODataEntityReferenceLinks entityReferenceLinks, IEdmEntitySet entitySet, IEdmNavigationProperty navigationProperty)\r\n   at Microsoft.Data.OData.JsonLight.ODataJsonLightEntityReferenceLinkSerializer.<>c__DisplayClass4.<WriteEntityReferenceLinks>b__3()\r\n   at Microsoft.Data.OData.JsonLight.ODataJsonLightSerializer.WriteTopLevelPayload(Action payloadWriterAction)\r\n   at Microsoft.Data.OData.JsonLight.ODataJsonLightEntityReferenceLinkSerializer.WriteEntityReferenceLinks(ODataEntityReferenceLinks entityReferenceLinks, IEdmEntitySet entitySet, IEdmNavigationProperty navigationProperty)\r\n   at Microsoft.Data.OData.JsonLight.ODataJsonLightOutputContext.WriteEntityReferenceLinksImplementation(ODataEntityReferenceLinks links, IEdmEntitySet entitySet, IEdmNavigationProperty navigationProperty)\r\n   at Microsoft.Data.OData.JsonLight.ODataJsonLightOutputContext.WriteEntityReferenceLinks(ODataEntityReferenceLinks links, IEdmEntitySet entitySet, IEdmNavigationProperty navigationProperty)\r\n   at Microsoft.Data.OData.ODataMessageWriter.<>c__DisplayClass30.<WriteEntityReferenceLinks>b__2f(ODataOutputContext context)\r\n   at Microsoft.Data.OData.ODataMessageWriter.WriteToOutput(ODataPayloadKind payloadKind, Action verifyHeaders, Action`1 writeAction)\r\n   at Microsoft.Data.OData.ODataMessageWriter.WriteEntityReferenceLinks(ODataEntityReferenceLinks links, IEdmEntitySet entitySet, IEdmNavigationProperty navigationProperty)\r\n   at Microsoft.Data.OData.ODataMessageWriter.WriteEntityReferenceLinks(ODataEntityReferenceLinks links)\r\n   at ODataService.Extensions.CustomEntityReferenceLinksSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext) in d:\\webapi\\sample\\aspnet\\Samples\\WebApi\\OData\\v3\\ODataServiceSample\\ODataService\\Extensions\\CustomODataMediaFormatter.cs:line 44\r\n   at System.Web.Http.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders)\r\n   at System.Web.Http.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()"
      }
    }

}  
}  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2209](http://aspnetwebstack.codeplex.com/workitem/2209)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Dec 8, 2014 at 6:41 AM
**Reported by:**	karata
**Updated on:**	Dec 24, 2014 at 6:12 AM
**Updated by:**	xuzhg

**Comment by xuzhg** [comment]
Resolved:
25216c23e3196fd4abbe01fb7577ea05124559ea
