### ISSUE TITLE
Custom query option ignored on controller action in .NET Core

### ISSUE THREAD

**Issue by aboryczko** [OData/WebApi#1794]
I'm migrating my app from .NET Framework to Core. I have a custom query option on a Get method in my controller and it seems to not work in .NET Core, although it did in Framework.
Is there some special convention in .NET Core to make this work properly?

### Assemblies affected

Microsoft.AspNetCore.OData, Version=7.1.0.21120

### Reproduce steps

Create two Get methods on your controller
```csharp
[EnableQuery]
public IActionResult Get([FromQuery] string custom)
{
...
}

[EnableQuery]
public IActionResult Get()
{
...
}
```
Issue a request to /api/Controller?custom=123

### Expected result

`Get(string)` should be invoked

### Actual result

`Get()` is invoked

### Additional detail

I tried different forms of `Get(string)` with `[FromQuery]` and without it. Both actions are properly discovered by `Microsoft.AspNet.OData.Routing.ODataActionSelector.SelectCandidates` but the proper action is discarded by `Microsoft.AspNet.OData.Routing.ODataActionSelector.SelectBestCandidate`

**Comment by KanishManuja-MS** [comment]
@aboryczko This appears to be a bug in our routing convention. In the meanwhile, you can use a single controller method and get the query parameter from the request URI. 
If you can share more details about how you are configuring the routing, we can suggest other workarounds.

**Comment by aboryczko** [comment]
I've figured that getting the data straight from the `Request` property should work.
As for my routing startup it's nothing out of the ordinary:
```csharp
app.UseMvc(b =>
{
    b.Count().Filter().OrderBy().Expand().Select().MaxTop(null);
    b.MapODataServiceRoute("OData", "api", GetEdmModel());
});
```
this is on .NET Core 2.2 with `EnableEndpointRouting = false`

**Comment by ferdiozaydin** [comment]
Change

app.UseEndpoints(endpoints =>
            {
                ......
                endpoints.MapODataRoute("odata", "**odata**", modelBuilder.GetEdmModel(app.ApplicationServices));
            });

to

app.UseEndpoints(endpoints =>
            {
                ......
                endpoints.MapODataRoute("odata", "**api**", modelBuilder.GetEdmModel(app.ApplicationServices));
            });

Some reasons odata routing with "odata" not working with query string

**Comment by aboryczko** [comment]
works as expected with current version
