### ISSUE TITLE
$filter lt null throws InvalidOperationException

### ISSUE THREAD

**Issue by bverb** [OData/WebApi#1795]
I have the following non-nullable int

`public int CustomerCount{ get; set; }`

`$filter=customerCount lt null` throws an InvalidOperationException from FilterBinder.cs

`System.InvalidOperationException: 'The binary operator GreaterThan is not defined for the types 'System.Nullable`1[System.Int32]' and 'System.Object'.'`

**Comment by xuzhg** [comment]
@bverb

I can't understand what's your scenario about `$filter=customerCount lt null`, 

1. for comparing null literal, can you just use `eq` or `ne`?
2. you use "lt", but get "GreaterThan" from error message? The error message seems from other problem.
3. CusotmerCount is non-nullable, but the message shows System.Nullable[System.int32]?

Can you share us your call-stack or Can you verify your example?

**Comment by bverb** [comment]
This seemed to be more of an implementation issue than an actual issue with the OData library. Closing as it has been resolved.
