### ISSUE TITLE
v5.5: OData layer is unable to deserialize EdmEntityCollection as Feed.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#180]
The current implementation of WebAPI OData 6.8.1, is unable to desterilize
feeds directly from stream.  
  
The read call defaults to:  

    
    
            public virtual object ODataDeserializer::Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)
            {
                throw Error.NotSupported(SRResources.DeserializerDoesNotSupportRead, GetType().Name);
            }

As a workaround, the Read(ODataMessageReader messageReader, Type type,
ODataDeserializerContext readContext) method needs to be overridden and
implemented.  
  
It would be great if this functionality was baked into the OData layer.  
  
The reason to introduce this functionality is to consume EdmEntityCollections
in the EntityController endpoint.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2211](http://aspnetwebstack.codeplex.com/workitem/2211)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Dec 12, 2014 at 7:11 AM
**Reported by:**	abkmr
**Updated on:**	Tue at 8:07 AM
**Updated by:**	cysu

**Comment by LianwMS** [comment]
On *2015-01-06 16:07:47 UTC*, **cysu** commented:

Handle together with entity object.

**Comment by xuzhg** [comment]
There's no such scenarios to POST/PUT/PATCH feed. And for action scenario, it supports in 5.5. So, I close it. If you have more issue about it, please file a new issue to track. Thanks.
