### ISSUE TITLE
ODataEnumDeserializer.ReadInline fails with InvalidCastException when edmType comes from CsdlParser

### ISSUE THREAD

**Issue by DJackman123** [OData/WebApi#1802]
Our OData service uses a model that's generated from the CsdlParser parsing an EDMX string.  Because of this, when ODataEnumDeserializer.ReadInline is called for an enum type, an InvalidCastException is thrown when it tries to cast the edmType parameter to an IEdmEnumTypeReference.

### Assemblies affected

Microsoft.AspNetCore.OData/Microsoft.AspNet.OData v7.1.0

### Reproduce steps

Create a simple OData service with an entity type that includes an enum type. In the call to MapODataServiceRoute, use a model created by parsing EDMX with CsdlParser.  Use a client to post an instance of the type to a collection.

### Expected result

Parsing of enum type in incoming type will work and object will be posted.

### Actual result

InvalidCastException is thrown. In my service test, this resulted in a null value being passed to the Post method in the controller.

### Additional detail

This bug was introduced in version 7.1.0.
I have created a PR with a unit test that shows this bug and also a fix for it.

**Comment by xuzhg** [comment]
Merged at: https://github.com/OData/WebApi/commit/2cbf4e3cf48af96b41ec856d62df38d3eb475e70
