### ISSUE TITLE
When would you support $compute and $search?

### ISSUE THREAD

**Issue by kuacci** [OData/WebApi#1812]
Is there any plan for $compute and $search in OData v4.01?

Thanks,

**Comment by kosinsky** [comment]
ODL part needed for `$compute` is already done (https://github.com/OData/odata.net/pull/1425) and should go out with 7.6. I'm working on implementation of `$apply=compute(..)` first, however don't have ETA yet. I'll reference PR in that issue as soon as it will be ready.

**Comment by kuacci** [comment]
Cool. Thank you.
