### ISSUE TITLE
Can we have CreateODataResult<T>.Entity back please

### ISSUE THREAD

**Issue by phatcher** [OData/WebApi#1814]
For the WebApi version CreateODataResult<T> had an Entity property which then allowed us to write integration tests for the controllers which proved the data had been passed through custom business logic,

For the .NET Core version, the Entity property has been removed and the result store in a private field _innerResult, so we have to resort to reflection to get this.

We are already coupled to T by the definition of the class, so it seems a bit mean to keep it private. At least make it protected so I can make my own class version if you don't want to change the public interface.

### Assemblies affected

Microsoft.AspNetCore.OData 7.x

**Comment by KanishManuja-MS** [comment]
@phatcher Thanks for pointing out. We can consider making the getter public.

**Comment by phatcher** [comment]
@KanishManuja-MS You need to do the same for UpdatedODataResult, here's the code I'm using in the meantime in case it's useful to someone else...

```
/// <summary>
/// Get the entity from the result (via reflection)
/// </summary>
/// <typeparam name="TEntity"></typeparam>
/// <param name="result"></param>
/// <returns></returns>
public static TEntity Entity<TEntity>(this CreatedODataResult<TEntity> result)
{
	// TODO: Could cache but not used that much
	var t = result.GetType();

	var pi = t.GetField("_innerResult", BindingFlags.NonPublic | BindingFlags.Instance);

	return (TEntity) pi.GetValue(result);
}

/// <summary>
/// Get the entity from the result (via reflection)
/// </summary>
/// <typeparam name="TEntity"></typeparam>
/// <param name="result"></param>
/// <returns></returns>
public static TEntity Entity<TEntity>(this UpdatedODataResult<TEntity> result)
{
	// TODO: Could cache but not used that much
	var t = result.GetType();

	var pi = t.GetField("_innerResult", BindingFlags.NonPublic | BindingFlags.Instance);

	return (TEntity)pi.GetValue(result);
}
```

**Comment by xuzhg** [comment]
.NET Classic has have the proposal.
So, add that for .NET Core version.

**Comment by xuzhg** [comment]
Fixed and Close it.
