### ISSUE TITLE
DefaultValueAttribute not considered in EDM 

### ISSUE THREAD

**Issue by Danielku15** [OData/WebApi#1819]
When you annotate a property with a `DefaultValueAttribute` in C# the generated CSDL/EDM does not contain a XML attribute `DefaultAttribute` as [per specification](http://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/cs01/odata-csdl-xml-v4.01-cs01.html#sec_DefaultValue). Also there is no way to manually set it afterwards as the `EdmStructuralProperty.DefaultValueString` is readonly. 

### Assemblies affected

Microsoft.AspNetCore.OData 7.1.0
Microsoft.AspNet.WebApi.OData 5.7.0
Master Branch

### Reproduce steps

Create an entity and annotate it with a [DefaultValueAttribute]:
```csharp
class User
{
    [DefaultValue(100)]
    [Required]
    public int Test {get;set;}
}
```

### Expected result

The EDM should contain an XML attribute according to http://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/cs01/odata-csdl-xml-v4.01-cs01.html#sec_DefaultValue
```xml
<EntityType Name="Person">
   <Property Name="Test" Type="Edm.Int32" Nullable="false" DefaultValue="100" />
</EntityType>
```

### Actual result

The attribute is not respected and no DefaultValue XML attribute is written: 

```xml
<EntityType Name="Person">
   <Property Name="Test" Type="Edm.Int32" Nullable="false" />
</EntityType>
```

### Additional detail

The `EdmTypeBuilder` does not consider any default values when adding structural properties: 

https://github.com/OData/WebApi/blob/9a908285e9e235e95b46ffaf34f3d0efba9c020a/src/Microsoft.AspNet.OData.Shared/Builder/EdmTypeBuilder.cs#L253-L256

The PropertyConfigurations would need to be updated to allow specifying the default value. Then the `ODataConventionModelBuilder` would need to be updated to respect the `DefaultValueAttribute` and fill it accordingly.

**Comment by xuzhg** [comment]
Fixed and close it.
