### ISSUE TITLE
v5.5: Support of Derived EntityTypes to define their own keys. - Metadata Serializer

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#182]
Keys defined by derived types should be rendered in the metadata  

    
    
       <EntityType Name="baseEntity" Abstract="true" />
       <EntityType Name="account" BaseType="ns.crmbaseentity">
              <key>
                     <Property Name="accountid" Type="Edm.Guid" />
              </key>
       </EntityType>

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2216](http://aspnetwebstack.codeplex.com/workitem/2216)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Dec 19, 2014 at 9:28 AM
**Reported by:**	ShahzorKhan
**Updated on:**	Tue at 7:53 AM
**Updated by:**	cysu

**Comment by congysu** [comment]
The issue #4, #5, #6 are parts of this work item.

**Comment by congysu** [comment]
Checked in: https://github.com/OData/WebApi/commit/889bba29cfc7829c02d6434ed50dd0d0f2c6b169
