### ISSUE TITLE
v5.5: Entity as Action Parameter sent by the T4 Client should be serializable by Server,

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#183]
Entity as Action Parameter sent by the T4 Client should be serializable by
Server,  
  
T4 template adds [ @odata.type ](mailto:@odata.type) annotation to the
navigation properties of Entity object when sending as an Action
Parameter/Payload,  
  
Entity Serialization fails if Navigation properties have [ @odata.type
](mailto:@odata.type) annotation, with the following exception  

    
    
    The navigation property “<NavigationPropertyName>' has a property annotation 'odata.type'. Navigation links in request payloads can only have the 'odata.bind' property annotation.
    
    

Eg.  

    
    
     <EntityType Name="crmbaseentity" Abstract="true" />
     <EntityType Name="account" BaseType="mscrm.crmbaseentity">
        <NavigationProperty Name="accountleads_association" Type="Collection(ns.lead)" Partner="accountleads_association" />
     </EntityType>
    ..
    <Action Name="Create">
       <Parameter Name="SuppressDuplicateDetection" Type="Edm.Boolean" />
       <Parameter Name="Target" Type="ns.baseentity" Nullable="false" />
    </Action>
    
    
    

Payload:  

    
    
    {
    "SuppressDuplicateDetection": false,
    "Target": {
        "@odata.type": "#mscrm.account",
        "accountleads_association@odata.type": "#Collection(ns.lead)",
        "accountleads_association": []
    }
    

Exception received.  

    
    
    The navigation property 'accountleads_association' has a property annotation 'odata.type'. Navigation links in request payloads can only have the 'odata.bind' property annotation.

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2217](http://aspnetwebstack.codeplex.com/workitem/2217)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Dec 19, 2014 at 9:36 AM
**Reported by:**	ShahzorKhan
**Updated on:**	Tue at 7:51 AM
**Updated by:**	cysu

**Comment by congysu** [comment]
Checked in https://github.com/OData/WebApi/commit/047d2504cca694fc5bd4bf99eb5d7b4f91f97941; #7
