### ISSUE TITLE
SetDefaultODataOptions doesn't work/has dead code

### ISSUE THREAD

**Issue by Megasware128** [OData/WebApi#1837]
While browsing the source I came across [this piece of code](https://github.com/OData/WebApi/blob/3b4aa3ca5910d3393fdc5404f475ceb0cb1139e0/src/Microsoft.AspNetCore.OData/Extensions/ODataRouteBuilderExtensions.cs#L263). As you can see it [retrieves options from the service provider](https://github.com/OData/WebApi/blob/3b4aa3ca5910d3393fdc5404f475ceb0cb1139e0/src/Microsoft.AspNetCore.OData/Extensions/ODataRouteBuilderExtensions.cs#L275) and [replaces it in the local scope with the new one](https://github.com/OData/WebApi/blob/3b4aa3ca5910d3393fdc5404f475ceb0cb1139e0/src/Microsoft.AspNetCore.OData/Extensions/ODataRouteBuilderExtensions.cs#L281). Unless there is some compiler magic going on I don't think this is going to work.

**Comment by KanishManuja-MS** [comment]
@Megasware128 Thanks for pointing out.

**Comment by xuzhg** [comment]
Closed.
