### ISSUE TITLE
Response to a request whose URL has a type cast doesn't include the correct context URL

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#184]
The response to  
  
GET [ http://host/service/Bases(key)/Namespace.Derived
](http://host/service/Bases\(key\)/Namespace.Derived)  
  
should have the context URL  
  
[ @odata.context=http://host/service/metadata#Bases/Namespace.Derived/$entity
but ](mailto:@odata.context=http://host/service/metadata#Bases/Namespace.Deriv
ed/$entity

but) Web API OData gives  
  
[ @odata.context=http://host/service/metadata#Bases/$entity instead
](mailto:@odata.context=http://host/service/metadata#Bases/$entity

instead) .  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2222](http://aspnetwebstack.codeplex.com/workitem/2222)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Sun at 2:04 AM
**Reported by:**	yidingms
**Updated on:**	Tue at 7:21 AM
**Updated by:**	cysu

**Comment by LianwMS** [comment]
On *2015-01-06 15:21:38 UTC*, **cysu** commented:

Suggest fix.

**Comment by xuzhg** [comment]
Resolved: 
733cdc7031c552b2ecded079af59000e52884b98
