### ISSUE TITLE
7.x nightlies don't exist any more?

### ISSUE THREAD

**Issue by matdavies** [OData/WebApi#1841]
The readme.md file makes reference to nightly builds for the 7.x version:

https://github.com/OData/WebApi/blame/master/README.md#L81

They should, according to that document, be available here: https://www.myget.org/gallery/webapinetcore

However, there is no such package on MyGet.  So only the 6.x nightly builds are available. 

Where are the 7.x nightlies?

**Comment by matdavies** [comment]
To confirm, the actual MyGet Feed for the 7.x nightlies DOES exist, here: 

https://www.myget.org/F/webapinetcore

However, the readme makes reference to the gallery page, which does not exist - would probably be better to either have that gallery page exist, or to remove the reference to it in readme.md?

**Comment by KanishManuja-MS** [comment]
@matdavies Yes, you are right. The feed existed but it was not available in the gallery. Now, it is available in the gallery.

**Comment by matdavies** [comment]
Thanks @KanishManuja-MS !
