### ISSUE TITLE
v5.7: Support IsOf function in OData

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#185]
Currently there is no support for the isof('Namespace.Type') function in Web
API OData.  
  
Please add support, as it makes handling inherited types very difficult.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2223](http://aspnetwebstack.codeplex.com/workitem/2223)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mon at 4:42 PM
**Reported by:**	TimMc
**Updated on:**	Tue at 7:40 AM
**Updated by:**	cysu

**Comment by LianwMS** [comment]
On *2015-01-06 15:40:45 UTC*, **cysu** commented:

Also check other built-in functions not supported by webapi.odata.

**Comment by vxa123** [comment]
Any update? We need it too.

**Comment by vxa123** [comment]
Can I checkin this fix?

**Comment by vxa123** [comment]
Please make it high priority.

**Comment by xuzhg** [comment]
@vxa123 You are welcome to send us Pull Request to support this.

**Comment by VikingsFan** [comment]
Merged f07a9d3412114cefb2f0eb8b4e36cc2b0a3305d3
