### ISSUE TITLE
How to use OData's Display.FormattedValue

### ISSUE THREAD

**Issue by bdebaere** [OData/WebApi#1850]
I've been trying to use the ability of OData's `Display.FormattedValue`, but I cannot find any good source on how to implement it. I've searched the code in the entire OData organization (which yields no code for `formattedvalue`, `displayablevalue`). 

I've read many links, including the following:

- http://odata.github.io/WebApi/04-19-odataIncludeAnnotations/   
- https://github.com/OData/odata.net/issues/75   
- https://issues.oasis-open.org/browse/ODATA-787

But I still don't understand how to implement it.

Does anyone know?

**Comment by genusP** [comment]
After build model use `AddVocabularyAnnotation` method for add annotation instance linked to entity property.
http://odata.github.io/odata.net/#02-07-define-annotations

**Comment by bdebaere** [comment]
@genusP Do you have sample code on what kind of annotation I have to add to enable FormattedValue? Because there are multiple annotations. And most importantly how does OData know what to property to show?

**Comment by genusP** [comment]
@bdebaere 
if you need add annotation to metadata document use solution from previous comment.
if you need add annotation to entity serialization result, see https://docs.microsoft.com/ru-ru/odata/webapi/customize-formatter

**Comment by bdebaere** [comment]
@genusP Thanks
