### ISSUE TITLE
Does Odata support $filter Contains syntax against MongoDB

### ISSUE THREAD

**Issue by alberk8** [OData/WebApi#1856]
*Short summary (3-5 sentences) describing the issue.*
I have Odata working with MongoDB doing normal Query (like all and exact match). But I cannot search data based on "Like" condition.

### Assemblies affected
Microsoft.AspNetCore.Odata v7.1.0.
MongoDB.Driver v2.8.1

### Reproduce steps
I have posted the issue on slackoverflow
https://stackoverflow.com/questions/56962714/asp-net-core-odata-on-mongodb-like-filter
*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result

return the filtered results

### Actual result

System error

**Comment by genusP** [comment]
@alberk8  try disable [HandleNullPropagation](https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/Query/ODataQuerySettings.cs#L70). This option enable additional checks to null value.

**Comment by alberk8** [comment]
Thank you do much.  It fixed the issue.
