### ISSUE TITLE
Fix Patch() of Open Type Dynamic Properties in Delta<T>

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#186]
Delta<T>.Patch() replaces all Open Type dynamic properties instead of merging in changed dynamic properties. 

Open Types use a property defined as:

     public IDictionary<string, object> DynamicProperties { get; set; }

Where the property name can be different than DynamicProperties since a property of interface IDictionary<string, object> is the correct way to identify the property to use. 

Calling deltaEntity.Patch(originalEntity) results in dynamic properties of the originalEntity getting replaced with the contents of the dynamic properties of deltaEntity. 

To correctly support Open Types the deltaEntity's dynamic properties key value pairs should get merged into originalEntity's dynamic properties. The merge should be such that matching keys in originalEntity's dynamic properties get there value replaced with the deltaEntity value for that key and unmatched keys get their key value pairs added to originalEntity's dynamic properties. 

Open Types can exist anywhere in types used by the entity so Delta<T>.Patch() needs to recursively apply the merge logic down all object instances of complex types, navigation properties, and collections. 

I encountered the issue with an entity of type User with this structure where the Open Type is in the Data class:

public class User
{
    public string Email { get; set; }

    /// <summary>
    /// Optional, additional data to associate with the user.
    /// </summary>
    public Data Data { get; set; }
}

public class Data
{
    public IDictionary<string, object> DynamicProperties { get; set; }
}

Delta<T> correctly patched Email but not Data.

Work Item Details

Original CodePlex Issue: Issue 2226
Status: Proposed
Reason Closed: Unassigned
Assigned to: Unassigned
Reported on: Oct 22, 2014 at 6:21 PM
Reported by: danroth27
Updated on: Oct 22, 2014 at 10:34 PM
Updated by: danroth27

**Comment by LianwMS** [comment]
Follow up

**Comment by xuzhg** [comment]
It fixed. See my test: https://github.com/xuzhg/WebApiSample/blob/master/PatchDynamicClass.cs
