### ISSUE TITLE
OData error using $select and $expand

### ISSUE THREAD

**Issue by nissimlevy** [OData/WebApi#1865]
I am using:

.NET Framework 4.7.2
Visual Studio 2017
OData V4
Web API V 5.2.4 with Entity Framework V6.2 code first with existing MS SQL DB

My $expand and $select commands are generating an error. For example, when I use the select command as follows:

http://localhost:62681/data/Advances?$select=Description
I get the following error:

The query specified in the URI is not valid. Could not find a property named 'Description' on type 'Microsoft.AspNet.OData.Query.Expressions.SelectSome_1OfAdvance'

$filter and $orderby do work

The odd thing is that this used to work a couple of weeks ago, but when I came back from vacation I could not get it to work. Any help is appreciated.

I've scoured the internet for any clue to my problem, but no luck.

I've upgraded to Microsoft.OData.Core version=7.5.0 and Microsoft.OData.Edm" version="7.5.0

My register method in WebApi.Config does have the line config.Select().Expand().Filter().OrderBy().Count().MaxTop(null);

public static void Register(HttpConfiguration config)
    {
        // Web API configuration and services

        // Web API routes
        config.MapHttpAttributeRoutes();           

        config.Routes.MapHttpRoute(
            name: "DefaultApi",
            routeTemplate: "api/{controller}/{id}",
            defaults: new { id = RouteParameter.Optional }
        );

        ODataModelBuilder builder = new ODataConventionModelBuilder(); 

        config.Select().Expand().Filter().OrderBy().Count().MaxTop(null);

        builder.EntitySet<Advance>("Advances");
        builder.EntitySet<Advance_Payments>("Advance_Payments");

        config.MapODataServiceRoute(
            routeName: "ODataRoute",
            routePrefix: "data",
            model: builder.GetEdmModel());

        config.AddODataQueryFilter(new SecureAccess2Attribute());
    }
What am I doing wrong?

**Comment by KanishManuja-MS** [comment]
@nissimlevy Can you please share your csdl? Also, an example where $filter is working against the Description field and stacktrace if you have it. Did something change between when it worked and it did not?

**Comment by gathogojr** [comment]
Issue from 2019. No reaction to share more details
