### ISSUE TITLE
WebApi repository seems to be missing documentation on building, testing, and contributing to WebApi

### ISSUE THREAD

**Issue by MrTomWhite** [OData/WebApi#187]
### Description
The Github community has a general practice of including some documentation in repositories to make them easier to consume, browse, and modify. For example: `Readme.md` files in the root directory of a repository are used to give an overview of the repository and typically feature instructions for getting started and links to other documentation. `Contributing.md` files are often use to outline rules and guidelines for contribution. Currently, the web api repository lacks these basic forms of documentation, which directly impedes developer's ability to contribute to the project.  

### Minimal repro steps
1. Browse the repository 
2. README.md missing
3. Contribution guidelines missing 
4. Documentation on building and testing the project missing 

### Expected result
Basic documentation should be present. 

### Further technical details
Odata.Net has done a decent job of including these sorts of documentation. Their repository can be accessed here:  https://github.com/OData/odata.net  You can also look to other commonly used github repositories to get a better idea about how projects tend to self-document.

Additionally, an automated tool called "flint" can be used to analyze your github repository and report issues that can cause developer friction. That can be accessed here.  https://github.com/pengwynn/flint

**Comment by VikingsFan** [comment]
@MrTomWhite this seems to be done by now, any further suggestions?

**Comment by MrTomWhite** [comment]
Yeah I think this issue can be closed.

I haven't had the time to take a serious look at anything Odata related. I can make some time over the weekend and see if I can follow your docs for most dev use cases. If there's anything that looks too bad I'll just open separate issues.

Thank you!

**Comment by VikingsFan** [comment]
@MrTomWhite Cool, any suggestions is very appreciate!
