### ISSUE TITLE
How to Handle OData Optional Parameter in C# Web API

### ISSUE THREAD

**Issue by kuldip1490** [OData/WebApi#1870]
@xuzhg  i need EmpId as a optional

i found resource  from here [https://docs.microsoft.com/en-us/odata/odatalib/optional-parameters](url) but i don't know how to use

- Microsoft.Aspnet.OData = 7.1.0.21120

- Model 

public class Employee
 
   {

        [Key]
        public string Id { get; set; }

       
        public string EmpID { get; set; }

        
        public string Name { get; set; }

        
        public string Address { get; set; }
    }

- Controller
[ODataRoutePrefix("Employee")]
    public class EmployeeController : ODataController
    {

        

        [EnableQuery]      
        [ODataRoute("GetEmployee(Id={Id},EmpId={EmpId})")]
        [HttpGet]
        public IHttpActionResult GetEmployee(string Id, string EmpId )
        {

            try
            {
                return Ok();
            }
            catch (ODataErrorException ex)
            {
                return Content(HttpStatusCode.BadRequest, ex);
            }

        }

    }

- WebApiConfig
 ODataModelBuilder builder = new ODataConventionModelBuilder();

            builder.Namespace = "eV";
            builder.ContainerName = "Default";

            EntitySetConfiguration<Employee> objEmployee = builder.EntitySet<Employee>("Employee");// ....Create Entity of Employee            
            FunctionConfiguration getEmployeeOptional = objEmployee.EntityType.Collection.Function("GetEmployee");
            getEmployeeOptional.Parameter<string>("Id");
            getEmployeeOptional.Parameter<string>("EmpId"); // need this optional
            getEmployeeOptional.ReturnsFromEntitySet<Employee>("Employee");

**Comment by KyleMcMaster** [comment]
@kuldip1490
Can you explain your issue with a little more detail? In my experience, I have OData functions that take in multiple parameters that can be "optional" by passing empty strings in the request url for the values in the function parameters. An example request url might be something like 
`
localhost:62891/odata/employee/getemployee(Id='123',EmpId='')
` where empid is passed in as an empty string and then I have some basic logic in my controller or handler based on the parameters:

```
[ODataRoutePrefix("Employee")]
public class EmployeeController : ODataController
{
    [EnableQuery]      
    [ODataRoute("GetEmployee(Id={Id},EmpId={EmpId})")]
    [HttpGet]
    public IHttpActionResult GetEmployee(string Id, string EmpId)
    {
        try
        {
            if (!string.IsNullOrWhiteSpace(Id))
            {
                //Do something with Id
            }

            if (!string.IsNullOrWhiteSpace(EmpId))
            {
                //Do something else with EmpId
            }

            //usually returning some sort of IQueryable here
            return Ok();
        }
        catch (ODataErrorException ex)
        {
            return Content(HttpStatusCode.BadRequest, ex);
        }
    }
}
```


If you could explain your exact issue or error message, I would be happy to assist you in resolving your problem :)

**Comment by kuldip1490** [comment]
@KyleMcMaster  thank you for your feedback, that is good explanations and this example will help me to resolve my issues but one doubt that is it possible to  URL should be possible like  [localhost:62891/odata/employee/getemployee(Id='123')](url) instead of [localhost:62891/odata/employee/getemployee(Id='123',EmpId='')](url)  with the same function ?

**Comment by xuzhg** [comment]
@kuldip1490 can you try call `Optional()` fluent API after setting the parameter. Sams as `getEmployeeOptional.Parameter<string>("EmpId").Optional(); // need this optional`

Let me know whether it works or not

**Comment by kuldip1490** [comment]
> @kuldip1490 can you try call `Optional()` fluent API after setting the parameter. Sams as `getEmployeeOptional.Parameter<string>("EmpId").Optional(); // need this optional`
> 
> Let me know whether it works or not

I m not using Entity frame work so i cant use fluent API in my custom Emplyee class

**Comment by genusP** [comment]
@kuldip1490 
This code in your Edm model defenition 

```
      builder.Namespace = "eV";
      builder.ContainerName = "Default";

      EntitySetConfiguration<Employee> objEmployee = builder.EntitySet<Employee>("Employee");// ....Create Entity of Employee            
      FunctionConfiguration getEmployeeOptional = objEmployee.EntityType.Collection.Function("GetEmployee");
      getEmployeeOptional.Parameter<string>("Id");
      getEmployeeOptional.Parameter<string>("EmpId").Optional(); // need this optional
      getEmployeeOptional.ReturnsFromEntitySet<Employee>("Employee");
``

**Comment by kuldip1490** [comment]
> @kuldip1490
> This code in your Edm model defenition
> 
> ```
>       builder.Namespace = "eV";
>       builder.ContainerName = "Default";
> 
>       EntitySetConfiguration<Employee> objEmployee = builder.EntitySet<Employee>("Employee");// ....Create Entity of Employee            
>       FunctionConfiguration getEmployeeOptional = objEmployee.EntityType.Collection.Function("GetEmployee");
>       getEmployeeOptional.Parameter<string>("Id");
>       getEmployeeOptional.Parameter<string>("EmpId").Optional(); // need this optional
>       getEmployeeOptional.ReturnsFromEntitySet<Employee>("Employee");
> ``
> ```

yes, that's exactly

**Comment by gathogojr** [comment]
Issue reporter advised on how to go about resolving the issue. No fresh activity since
