### ISSUE TITLE
Current assembly versioning structure breaks upgrades

### ISSUE THREAD

**Issue by robertmclaws** [OData/WebApi#1872]
## The Problem
In the current build system for both ODL and WebApi, the versioning system puts a build number in the AssemblyVersionAttribute. This then gets put in the NuGet package, and that version is added to the web.config assembly binding redirects.

When you upgrade a NuGet package, the binding redirects are not automatically updated, and your app breaks at runtime. This can happen even if "Update binding redirects automatically" is checked in the Project Properties, because the system that calculates those bindings is, shall we say... less than awesome.

## The Solution
- Move the current version information to AssemblyFileVersionAttribute. That will make the version readable when you hover over the file in Windows Explorer.
- Change the current AssemblyVersionAttribute information to stop changing between minor releases. If you release version 7.2, then the version should be 7.2.0.0 until you release either 7.3 or 8.0. Anything else breaks customers unnecessarily.

Happy to dig in if you folks have any questions. HTH!

**Comment by madansr7** [comment]
@robertmclaws , we are investigating this issue and will fix with our next release. 
+@xuzhg

**Comment by xuzhg** [comment]
@robertmclaws Would you take a look the PR?

**Comment by xuzhg** [comment]
Merged and close it. Thanks.
