### ISSUE TITLE
'StartArray' node was found when reading from the JSON reader. A 'StartObject' node was expected.

### ISSUE THREAD

**Issue by cdarrigo** [OData/WebApi#1873]
When attempting to consume my odata feed of my EF Core DbContext, I get the following error message:

 An unexpected 'StartArray' node was found when reading from the JSON reader. A 'StartObject' node was expected.

### Assemblies affected

"Microsoft.AspNetCore.All" Version="2.1.5"
"Microsoft.AspNetCore.OData" Version="7.1.0"

### Reproduce steps

New api project, add an EF data context. 

Add Odata package to solution

Add the following to startup:

Some startup extensions:
```

  public static IServiceCollection AddODataSupport(this IServiceCollection services)
        {
            services.AddOData();
            //Workaround: https://github.com/OData/WebApi/issues/1177
            services.AddMvcCore(options =>
            {
                foreach (var outputFormatter in options.OutputFormatters.OfType<ODataOutputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
                {
                    outputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
                }
                foreach (var inputFormatter in options.InputFormatters.OfType<ODataInputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
                {
                    inputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
                }
            });

            return services;
        }

public static void ConfigureODataRouteForContext<TContext>(this IRouteBuilder routeBuilder, IApplicationBuilder app) where TContext:class
        {
            routeBuilder.EnableDependencyInjection();
            routeBuilder.Select().Filter().OrderBy().Expand().Count().MaxTop(100);
            routeBuilder.MapODataServiceRoute("odata", "odata", GetEdmModel());
        }
        
        private static IEdmModel GetEdmModel()
        {
            var obuilder = new ODataConventionModelBuilder();
            obuilder.EntitySet<TransactionEntity>("Transactions");
            return obuilder.GetEdmModel();
        }

```

and a controller:

  ```
public class ODataController : ControllerBase
    {
        private readonly ITmDataContext dataContext;

        public ODataController(ITmDataContext dataContext)
        {
            this.dataContext = dataContext;
        }
      
        [Route("odata/transactions")]
        [HttpGet]
        [EnableQuery]
        public ActionResult<IEnumerable<object>> GetTransactions()
        {
            return dataContext.Transactions;
        }

    }
```

Run the app, I can hit the metadata endpoint and get back my schema.

```
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="TMS.DataManagement.Service.Data.Entities" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityType Name="TransactionEntity">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
               <Property Name="Id" Type="Edm.Int32" Nullable="false" />
...

```

Try to consume it using excel (2016).  Data-> New Query ->  Other Sources -> OData Feed -> provider route (http://localhost:5000/odata). 

*What would happen if there wasn't a bug.*
I could download the data from the feed. 

### Actual result

 I get the navigator pane populated with my Transactions node, but when I attempt to click on it to get a preview, or attempt to download the data I get:

> DataSource.Error: OData: An unexpected 'StartArray' node was found when reading from the JSON reader. A 'StartObject' node was expected.
> Details:
>     DataSourceKind=OData
>     DataSourcePath=https://localhost:5001/odata/Transactions

**Comment by kosinsky** [comment]
Controller should derive from ODataController or use ODataFormatting attribute to generate standard OData serialization in a form
```JSON
{
"@odata.context":"https://localhost:5001/odata/$metadata/#",
value":[{
"Id": 1
}]
}
```
instead of base JSON serialization
```JSON
[{
"Id": 1
}]
```

**Comment by cdarrigo** [comment]
Adding the attribute and changing the controller base didn't seem to resolve this issue:

```
  [ODataFormatting]
    public class ODataController : Microsoft.AspNet.OData.ODataController
    {
        private readonly ITmDataContext dataContext;

        public ODataController(ITmDataContext dataContext)
        {
            this.dataContext = dataContext;
        }
...
```

![image](https://user-images.githubusercontent.com/5930755/62411641-2924b600-b5c4-11e9-8ccf-b484ea587ce0.png)

I've also noticed that commands like count aren't working, but expand is.  the Count argument seems to be ignored, and instead It just returns the default payload
![image](https://user-images.githubusercontent.com/5930755/62411663-a3553a80-b5c4-11e9-84db-c7a32fe7a3ba.png)

**Comment by kosinsky** [comment]
From your screenshot I can see that output is vanilla JSON instead of proper OData format (not @odata.context and values collection present).
I was able to reproduce issue. Looks like basic ASP.Net Core routing break formatting for OData. As a result you need to remove `[Route("odata/transactions")]`
OData uses own route selection based on conventions.
Following two lines:
` routeBuilder.MapODataServiceRoute("odata", "odata", GetEdmModel());`
and 
`obuilder.EntitySet<TransactionEntity>("Transactions");` configure that for `odata/Transactions` uri TransactionsController.Get() method will be executed as a result you need to rename your ODataController to TransactionsController and GetTransaction() to Get(). Also implementation of Get method should look like:
`return Ok(dataContext.Transactions);`

Full 
```C#
  public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<MovieContext>(opt => opt.UseInMemoryDatabase("MovieList"));
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            AddODataSupport(services);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseMvc(builder =>
            {
                //ConfigureODataRouteForContext<MovieContext>(builder, app);
                builder.EnableDependencyInjection();
                builder.Select().Filter().OrderBy().Expand().Count().MaxTop(100);
                builder.MapODataServiceRoute("odata", "odata", GetEdmModel());
            });
        }

        public static IServiceCollection AddODataSupport(IServiceCollection services)
        {
            services.AddOData();

            return services;
        }

        public static void ConfigureODataRouteForContext<TContext>(IRouteBuilder routeBuilder, IApplicationBuilder app) where TContext : class
        {
            routeBuilder.EnableDependencyInjection();
            routeBuilder.Select().Filter().OrderBy().Expand().Count().MaxTop(100);
            routeBuilder.MapODataServiceRoute("odata", "odata", GetEdmModel());
        }

        private static IEdmModel GetEdmModel()
        {
            var obuilder = new ODataConventionModelBuilder();
            obuilder.EntitySet<Movie>("Movies");
            return obuilder.GetEdmModel();
        }

    }


    //[Route("api/[controller]")]
    //[ApiController]
    [ODataFormatting]
    public class MoviesController : Microsoft.AspNet.OData.ODataController
    {
        private readonly MovieContext dataContext;

        public MoviesController(MovieContext dataContext)
        {
            this.dataContext = dataContext;
        }

        //[Route("odata/Movies")]
        [HttpGet]
        [EnableQuery]
        public ActionResult<IEnumerable<object>> Get()
        {
            return Ok(dataContext.Movies);
        }
    }

```

**Comment by xuzhg** [comment]
@cdarrigo Can you try to use really model type not the 'object' in the action result of `public ActionResult<IEnumerable<object>> Get()`

**Comment by TehWardy** [comment]
Probably related to this ...

https://stackoverflow.com/questions/37993788/odata-collection-parameter-bindings-do-they-actually-work/38051214#38051214

... hopefully my experience might offer some insight here.

**Comment by Zzarek** [comment]
Im having the same issues [FromBody] and a post of ienumerable<EntityType>

**Comment by qwertie** [comment]
When I got this error, the problem turned out to be that I was returning `IEnumerable<object>` instead of `IEnumerable<TheCorrectODataType>`. Somehow this causes the wrong JSON format. Your API should produce a JSON object that starts with a `"@odata.context"` key; this error occurs when a plain array is produced instead.

In addition, I found it necessary to do the standard cache-clearing bullshht: in Power BI, go to `File -> Options and settings -> Options`, and under "Data Load", scroll down to **Data Cache Management Options** and click **Clear Cache**.

**Comment by gathogojr** [comment]
Issue from 2019. Attributable to a misconfigured OData service. No fresh activity from reporter since 2019

**Comment by dennis-garavsky** [comment]
We also experienced the same issue in DevExpress products ([our real use-case scenario](https://docs.devexpress.com/WindowsForms/117786/common-features/data-binding/binding-to-odata) is more complex and includes a data grid connected to an OData service and grouping by grid columns).

Attached you can find a simple Console App ([ODataClientServer.zip](https://github.com/user-attachments/files/15919186/ODataClientServer.zip)) that demonstrates the error in action. Please also see our comments in code of ConsoleApp1/Program.cs.

```cs


using System;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var serviceRoot = "http://localhost:5275/odata";
            var context = new Default.Container(new Uri(serviceRoot));
            context.BuildingRequest += (s, e) =>
            {
                Console.WriteLine("Executing " + e.RequestUri + " ...");
            };

            // It's working fine.
            /*IEnumerable<OrderItem> orders = context.OrderItems.ToList();
            foreach (var item in orders)
            {
                Console.WriteLine("{0} {1} {2}", item.ID, item.ProductName, item.Quantity);
            }*/

            // Not working.
            // Request URL: http://localhost:5275/odata/OrderItems?$apply=groupby((ProductName))
            // Expected console output:
            //    Product 0
            //    Product 1
            //    Product 2
            var uniqueProducts = context.OrderItems.GroupBy(o => o.ProductName, (key, items) => new
            {
                ProductName = key
            });
            foreach (var product in uniqueProducts)
            {
                Console.Write(product);
            }

            Console.ReadKey();
        }
    }
}
```

We cannot really work around this without compromising performance a lot, so we would appreciate a fix from the OData team. Feel free to contact us if you have any questions.
