### ISSUE TITLE
$Expand does not work when i get one item

### ISSUE THREAD

**Issue by JannyM85** [OData/WebApi#1878]
I prepare Odata API for mobile application, and i have a problem with $Expand. When i use this query everything works ok.

Query: .../odata/forms?$expand=FormFields($expand=FormFieldRadios)&$filter=FormId eq 1

But when i use this query:

.../odata/forms(1)?$expand=FormFields($expand=FormFieldRadios)

Expand does not work and items collection si empy.

More information about configuration here: https://stackoverflow.com/questions/57358424/expand-does-not-work-when-i-get-one-item

**Comment by KanishManuja-MS** [comment]
@JannyM85 It may be a bug, can you try removing the expand query option enabling code from the model builder and instead only use routeBuilder to enable to query option.

**Comment by JannyM85** [comment]
I found the error. When i build EDM model i use bad type in .EntitySet<BadType>("Devices"). Thanks.

**Comment by JannyM85** [comment]
Hi i was try it, but does not help.

**Comment by gathogojr** [comment]
Issue from 2019. Not reproducible since $expand against an entity works okay currently. Reporter can reopen if they're still experiencing the issue
