### ISSUE TITLE
ArgumentException: 'select' and 'expand' cannot be both null or empty.

### ISSUE THREAD

**Issue by luanle1106** [OData/WebApi#1881]
Hi, i get this error when run request below:

http://localhost:60365/odata/Orders?select=

ArgumentException: 'select' and 'expand' cannot be both null or empty.
Microsoft.AspNet.OData.Query.SelectExpandQueryOption..ctor(string select, string expand, ODataQueryContext context, ODataQueryOptionParser queryOptionParser)

How can i handle this error?
And this error should be from 400 client error instead of 500 error server?

**Comment by genusP** [comment]
What you expecting from this request?

**Comment by luanle1106** [comment]
If select or $select is null or empty. I wan't to get all properties of entity.
How can i do that?

**Comment by genusP** [comment]
For this you must use this request:
http://localhost:60365/odata/Orders?select=*

**Comment by luanle1106** [comment]
If the user request like this: http://localhost:60365/odata/Orders?select=
So, i must translate to http://localhost:60365/odata/Orders?select=*, is it's right?

I using QueryBuilder to build new query with select=*.

But i think this is not the best way for handle this scenario.

Do you have any better idea?

**Comment by genusP** [comment]
Yes all right.
