### ISSUE TITLE
Skip token does not respect EnableLowerCamelCase convention

### ISSUE THREAD

**Issue by FolkCoder** [OData/WebApi#1894]
When an `ODataConventionModelBuilder` enables camel-case formatting of property names via the `EnableLowerCamelCase` extension, generated skip tokens use the model's original property name rather than the formatted camel-case name. In models with non-integer key properties, the difference in casing between the skip token and the EDM property causes an exception to be throw when navigating to the next link.

### Assemblies affected

This issue is present in Microsoft.AspNetCore.OData v7.2.1.

### Reproduce steps

Create an API project that uses an ODataConventionModelBuilder with the EnableLowerCamelCase convention and request a paged collection of an entity containing a decimal key property. Navigate to the next page link.

A sample repository is available [here](https://github.com/FolkCoder/TestDecimalSkipToken).

### Expected result

When using camel-case formatting, the skip token identifier should match the formatting of its formatted EDM property.

### Actual result

A generated skip token contains the original property name rather than its formatted API property format (e.g., $skiptoken=Id-1 rather than @skiptoken=id-1). 

When using a decimal key, the following error is thrown:

> System.InvalidOperationException: \'The binary operator GreaterThan is not defined for the types 'System.Nullable\`1[System.Decimal]\' and '\System.Nullable\`1[System.Int32]\'.\'

### Additional detail

The `DefaultSkipHandler` class uses the CLR rather than the EDM property name to generate a skip token. When applying the paging specified in the next page link, the `DefaultSkipHandler` class fails to resolve the property associated with the skip token because it cannot match the formatted EDM property name against the original CLR property name. As a fallback, the `DefaultSkipHandler` determines the property type based on the skip token's value, with low-value numbers resolving to integers. When attempting to filter the collection, the expression cannot resolve a comparison between the decimal key defined by the CLR and the int key resolved by the skip handler.

**Comment by mikepizzo** [comment]
Addressed  PR #1895
