### ISSUE TITLE
[FromBody] parameter null when using Microsoft.OData.Client 7.6.0

### ISSUE THREAD

**Issue by groogiam** [OData/WebApi#1896]
Model binding does not seem to work for PUT/PATCH and POST operations when using the Microsoft.OData.Client in ASP.NET CORE 2.2 ODATA

### Assemblies affected

Microsoft.AspNetCore.OData 7.2.0

### Reproduce steps

entity parameter is always null on the controller action below when a PATCH/PUT request is generated from Microsoft.OData.Client

```c#
 [HttpPatch]
  public async Task<IActionResult> PatchFoo([FromODataUri] Guid key, [FromBody] Foo entity)
```

Example Request

```
PATCH http://localhost:5000/api/Foo(e75a0825-2242-0c53-0153-39dfd921dd56) HTTP/1.1
Host: localhost:5000
OData-Version: 4.0
OData-MaxVersion: 4.0
Prefer: return=representation
Accept: application/json; odata.metadata=minimal
Accept-Charset: UTF-8
User-Agent: Microsoft.OData.Client/7.6.0
Connection: Keep-Alive
Content-Type: application/json; odata.metadata=minimal
Content-Length: 562

{"@odata.type":"#http://www.odatatest.com/Foo", "Id":"e75a0825-2242-0c53-0153-39dfd921dd56","InvariantId":"c392548e-88e0-4751-977f-f12de77b1186"}

```

### Expected result

[FromBody] action parameter should be populated with the body of the request.

### Actual result

[FromBody] action parameter is always null.

**Comment by groogiam** [comment]
There was another issue causing the serialization to fail.

**Comment by raulandresduque** [comment]
Hi @groogiam,
Could you please provide extra details about the serialization issue you experimented with?
I'm having the same problem always the **[FromBody]** object is null for a PUT method.
When I use a **[FromBody] dynamic**, the date is there.

**Comment by groogiam** [comment]
Its been quite a while but looking at my source code history this seems to have been caused by a missing Microsoft.OData.Client.IgnoreClientProperty annotation on some of my client side models. The issue was not on the server it was on the client for me.

**Comment by raulandresduque** [comment]
I tried to deserialize manually the json and the issue is because of TimeSpan values.
