### ISSUE TITLE
AmbiguousMatchException in ApplyTo method

### ISSUE THREAD

**Issue by komdil** [OData/WebApi#1899]
As you know in C# we can create the same properties in different cases. For example, I can create `Title `and `TITLE `properties. When I create properties like that in $select query of these properties I'm getting `AmbiguousMatchException `

### Reproduce steps
Create the same properties with different cases: 
`public class Product
{
    [Key]
    public Guid Id { get; set; }
    public string Name { get; set; }
    public decimal Price { get; set; }
    public string Category { get; set; }

    [NotMapped]
    public virtual string Title { get; set; }

    [NotMapped]
    public virtual string TITLE { get; set; }
}`

Include them in builder:
` builder.EntityType<Product>().Property(a => a.Title);
  builder.EntityType<Product>().Property(a => a.TITLE);`

Create controller with action: 
` public IHttpActionResult Get(ODataQueryOptions<Product> queryOptions, CancellationToken cancellationToken)
  {
     Context = GetContext();
     var products = Context.GetEntities<Product>();
     var result = queryOptions.ApplyTo(products);
     return Ok(result);
  }` 
Start service and send request: https://localhost:*****/Products?$select=Id,Title

### Expected result

I should be able to get Title and TITLE with $select query

### Actual result
Exception:
`System.Reflection.AmbiguousMatchException: 'Ambiguous match found.'`

**Comment by xuzhg** [comment]
@komdil We should first search the property using exact naming, then using the case insensitive. It seems it's a bug in the code. Are you interested in contributing it?

**Comment by madansr7** [comment]
closing since the fix has been merged to master.
