### ISSUE TITLE
Add containment support to the OData model builder

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#19]
We expose all the entity sets at the root level in the service document. we
should support containment scenarios.  
As an example, entity set 'orders' is contained by the entity set 'customers'.
One cannot address an order without getting to the customer who owns that
order.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 566](http://aspnetwebstack.codeplex.com/workitem/566)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Oct 19, 2012 at 3:49 AM
**Reported by:**	raghuramn
**Updated on:**	Feb 4, 2014 at 8:11 PM
**Updated by:**	thebothead

**Comment by LianwMS** [comment]
On *2012-10-19 10:50:55 UTC*, **raghuramn** commented:

we should also consider changing the link generation conventions to support this scenario out-of-the-box.

**Comment by LianwMS** [comment]
On *2012-10-20 01:27:25 UTC*, **HongmeiG** commented:

New feature request is post Build.

**Comment by LianwMS** [comment]
On *2012-10-26 08:17:10 UTC*, **HongmeiG** commented:

This includes two work items:

update the metadata to indicate one entity set is contained in another; when generating link, you need to used the containing controller;

Moving this out since user can customize the model through convention and they can customize the link generation through link factory.

**Comment by xuzhg** [comment]
Containment was supported. Thanks.
