### ISSUE TITLE
PageSize on global HttpConfiguration is ignored

### ISSUE THREAD

**Issue by olsh** [OData/WebApi#1908]
PageSize on global HttpConfiguration is ignored.

### Assemblies affected

Microsoft.AspNet.OData 7.2.1

### Reproduce steps

1. Set the global configuration with `PageSize = 5`

```
config.Count().Filter().OrderBy().Expand().Select().MaxTop(1000).AddODataQueryFilter(new EnableQueryAttribute { PageSize  = 5 });
```

2. Add `[EnableQuery]` to an action
3. Send an HTTP request to the action with `$top=100` 

### Expected result

Only 5 entries are returned from the server.

### Actual result

100 entries are returned from the server.

### Additional detail

We are using MVC5 on .NET Framework 4.6.1

**Comment by robertmclaws** [comment]
I can confirm this behavior in my apps.

**Comment by KanishManuja-MS** [comment]
@olsh Seems like a bug got introduced with the paging changes in the last release.

**Comment by KanishManuja-MS** [comment]
@olsh Does this filter ever get called? I tried debugging, it does set the pageSize correctly but the OnActionExecuted for the EnableQueryAttribute gets called.

**Comment by olsh** [comment]
Hi @KanishManuja-MS 
Sorry for the late response, yes, it seems like `AddODataQueryFilter` doesn't change anything.

**Comment by olsh** [comment]
Emm, but why the issue was closed?
From my perspective, it's at least a misleading API design. Could you please explain the purpose of `AddODataQueryFilter`?
