### ISSUE TITLE
Support filtering string arrays

### ISSUE THREAD

**Issue by bdebaere** [OData/WebApi#1912]
What would it take to support filtering inside string arrays?

Suppose I had the class below, and wanted to filter on Contacts?$filter=any(PhoneNumbers, contains(item, '001')).

```csharp
public class Contact
{
    public int Id { get; set; }

    public string[] PhoneNumbers { get; set; }
}
```

**Comment by KanishManuja-MS** [comment]
@bdebaere Can you try Contacts?$filter=PhoneNumbers/any(p: contains(p,'001') ? I am not sure if it would work but this would be the correct syntax in my opinion.

**Comment by bdebaere** [comment]
@KanishManuja-MS Thanks, one more ) leads to a working solution: $filter=PhoneNumbers/any(p: contains(p,'001')).
I also tested $filter=PhoneNumbers/any(p: p eq '001') which returns the expected result.
