### ISSUE TITLE
Support $select multiple sub-fields in paranthesis

### ISSUE THREAD

**Issue by dotnetwise** [OData/WebApi#192]
e.g. `?$select=FirstName,LastName,Address/(Line1,Line2,PostCode)`
rather than `?$select=FirstName,LastName,Address/Line1,Address/Line2,Address/PostCode`

**Comment by congysu** [comment]
Check ABNF: http://docs.oasis-open.org/odata/odata/v4.0/os/abnf/

**Comment by dotnetwise** [comment]
Can you be more explicit please?

**Comment by VikingsFan** [comment]
For the first url: ?$select=FirstName,LastName,Address/(Line1,Line2,PostCode)
Checked ABNF, and it is not support in ODL according to the spec, as well as OData/WebApi, thanks for this comment, maybe you can customize your parser by now.
For the second url: ?$select=FirstName,LastName,Address/Line1,Address/Line2,Address/PostCode
This one is supported in ODL, but WebAPI doesn't, opened an issue to track:
https://github.com/OData/WebApi/issues/196

**Comment by xuzhg** [comment]
Close it because new issue was created. Thanks your input.
