### ISSUE TITLE
string.Replace is missing

### ISSUE THREAD

**Issue by bdebaere** [OData/WebApi#1937]
The replace functionality on string properties is missing. For example /odata/MyEntity?$filter=replace(string, 'query', 'query2') eq 'query2' throws with exception "Unknown function 'replace'".

**Comment by mikepizzo** [comment]
We actually intentionally omit string.Replace because it was identified as a possible DOS attack surface. Using string.Replace, a bad actor could potentially create a request that would overflow the server.

Life was some much easier before we really had security...

**Comment by bdebaere** [comment]
@mikepizzo Interesting, would you consider adding Regex.Match?
