### ISSUE TITLE
Custom Serializer ODataProperty DateTime ODataPrimitiveValue can only wrap values which can be represented as primitive EDM types.'

### ISSUE THREAD

**Issue by rossbuggins** [OData/WebApi#1945]
When implementing a custom serializer I'm getting the below exception when a DateTime object is added to ODataProperty. DateTimeOffset is fine. Looking at Microsoft.Odata.Core, there are some ifs around DateTime but not DateTimeOffset, lines 104 and 115 at https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Metadata/EdmLibraryExtensions.cs

Whats the reason behind this?

### Assemblies affected

Odata 7.2.2

### Reproduce steps

```
var dateTime = DateTime.Now;
new ODataProperty() { Name = "UtcStart", Value = dateTime}
```

### Expected result

Accept DateTime as a valid object, like DateTimeOffset is:

```
var dateTime = DateTime.Now;
new ODataProperty() { Name = "UtcStart", Value = new DateTimeOffset(dateTime, TimeSpan.Zero) }
```

### Actual result

Microsoft.OData.ODataException: 'An ODataPrimitiveValue was instantiated with a value of type 'System.DateTime'. ODataPrimitiveValue can only wrap values which can be represented as primitive EDM types.'

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by xuzhg** [comment]
@rossbuggins DateTime is removed from OData built-in primitive type. Can you change to use "DateTimeOffset"?
