### ISSUE TITLE
Navigation link is not correctly generated for nested containment propert

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#195]
If you have an entity set with an entity type that has a containment navigation property, which the target type also has a containment navigation property, when you do a GET on an entity in the first contained entity set the navigation link(s) for that entity's navigation properties are incorrect. 

 Example... 

 Entity w/ Entity Set 'Foos' 
 Foo 
 { 
 Property 'Bars' with Contains = true for contained entity set 
 } 

 Bars 
 { 
 Property 'Boos' with Contains = true for contained entity set 
 } 

 When doing a GET on w/ odata.metadata=full 
 ~\Foo(id)\Bar(id) 

 The navigation link is as follows: 
Boos@odata.navigationLink=http://127.0.0.1:82/api/Bars(id)/Boos 

 Where it should be: 
Boos@odata.navigationLink=http://127.0.0.1:82/api/Foos(id)/Bars(id)/Boos

**Comment by ificator** [comment]
Our service is running in to this bug as well - do we have an estimate as to when it's planned to be fixed?

**Comment by congysu** [comment]
See why Web API does not fallback to ODataLib.

**Comment by VikingsFan** [comment]
Checked in
