### ISSUE TITLE
$select = complexProperty/complexColProperty query option is not support

### ISSUE THREAD

**Issue by VikingsFan** [OData/WebApi#196]
query like ?$select=Address/Line1,Address/Line2,Address/PostCode is not support
In System.Web.OData.Formatter.Serialization.SelectExpandNode 
ValidatePathIsSupported function :
when segmentCount  == 2, only support first segment is a Type Segment, only support paths of type 'cast/structuralOrNavPropertyOrAction'

**Comment by robertmclaws** [comment]
Is there an ETA for supporting this yet? Going on two and a half years now, and it's still needed. Maybe @robward-ms can re-assign it to someone else?

Thanks!

**Comment by bdebaere** [comment]
@robward-ms Any news on this feature?

**Comment by brjohnstmsft** [comment]
This issue affects Azure Search as well. We are expanding the semantics of $select in our API to handle complex types.

I investigated this issue to the point where I have a sense of the scope of the fix, and it's not small. I already have a workaround in place, so unfortunately it's not worth the effort for my team to take this on. However, I did write an E2E test that will be useful for the next person who tackles this. That was surprisingly difficult too due to some EF dependencies in the E2E tests. I'll send a PR for that shortly.

**Comment by vsopko** [comment]
@robward-ms, @xuzhg is there any news on this feature?

**Comment by NimaAra** [comment]
@mikepizzo @xuzhg Any idea on when we can expect to get this feature?

**Comment by suadev** [comment]
@robward-ms, @xuzhg is there any news on this feature?

**Comment by xuzhg** [comment]
@suadev Thanks for querying. I am busy on this feature now. I hope I can finish it quickly and release it in the next version.

**Comment by VenuMadhavPerumalla** [comment]
@xuzhg - We're extending our Api to support Complex Properties and getting the same error during serialization. Kindly let me know if the fix that you're implementing is part of System.Web.OData v5.x and when can we expect the fix to be released

Version of System.Web.Odata being used - 5.9.1

**Comment by xuzhg** [comment]
@VenuMadhavPerumalla  Thanks for letting us know your scenarios. Unfortunately, We are focus on 7.x version and 5.x is in maintenance status.

**Comment by keatkeat87** [comment]
It block me to use ef core owned type, any workaround for this ? 
@xuzhg nice to hear that you are start doing this feature. Can give a estimate time when the next version release ? 
is it possible end of this year ?

**Comment by xuzhg** [comment]
@keatkeat87 Thanks for querying this. I just created a PR to enable it. Hope i can finish it as soon as possible if the code review works well. 
BTW, for any one who is interested in this feature are welcome to leave any comments to the PR at #1941.

**Comment by suadev** [comment]
@xuzhg and news for your PR?

**Comment by xuzhg** [comment]
My PR got merged.
