### ISSUE TITLE
$apply aggregation failing to convert enumerable to string

### ISSUE THREAD

**Issue by TimonFeldmann** [OData/WebApi#1961]
When executing an aggregate function e.g. ?$apply=groupby((Enumerable)) on an entity's enumerable property, the returned aggregation's value is not converted to the enumerable's EnumMember value counterpart and the raw value is returned instead.

Performing an OData operation against the same entity without an aggregation returns the entity with all enumerables converted to their EnumMember values as expected.

### Assemblies affected

OData WebApi lib 7.2.2

### Reproduce steps

**Create an entity with an enumerable as a property:**
```C#
[DataContract]
public enum MyEnum
    {
        [EnumMember(Value = "Member 1")]
        Member1 = 1,
        [EnumMember(Value = "Member 2")]
        Member2 = 2,
        [EnumMember(Value = "Member 3")]
        Member3 = 3
    }
    public class EntityWithEnumerable
    {
        [Key]
        public Guid Id { get; set; }
        public MyEnum MemberType { get; set; }
    }
```
**Configure OData and EDM Model:**
```C#
app.UseMvc(routeBuilder =>
            {
                routeBuilder.EnableDependencyInjection();
                routeBuilder.Select().Expand().Filter().OrderBy().MaxTop(null).Count();

                var builder = new ODataConventionModelBuilder(app.ApplicationServices);

                builder.EntitySet<EntityWithEnumerable>(nameof(EntityWithEnumerable));
                builder.EntityType<EntityWithEnumerable>().EnumProperty(c => c.MemberType);

                routeBuilder.MapODataServiceRoute("odata", "odata", builder.GetEdmModel()); 
            });
```
**Create a controller method returning the EntityWithEnumerable IQueryable:**
```C#
namespace Api.Controllers
{
    public class MyController : ODataController
    {
        [ProducesResponseType(typeof(ODataValue), Status200OK)]
        [ODataRoute("EntityWithEnumerable")]
        [EnableQuery]
        public IActionResult GetEntityWithEnumerable()
        {
            return Ok(_dbContext.EntityWithEnumerable);
        }
    }
}
```
### Expected result

When hitting MyController with the following request:

> /odata/EntityWithEnumerable/?$apply=groupby((MemeberType))

We expect to receive the EnumMember value as the aggregation value. We receive the EnumMember value when we do not perform an aggregation as expected.

### Actual result

The enumerable's integer value is returned instead of the EnumMember value. When applying a $filter to the aggregate:

> odata/EntityWithEnumerable/?$apply=groupby((MemberType))&$top=1000&$filter=contains(tolower(MemberType),%27test%27)

The following error is returned:

> No function signature for the function with name 'tolower' matches the specified arguments. The function signatures considered are: tolower(Edm.String Nullable=true).

### Additional detail
![Sample](https://user-images.githubusercontent.com/32442292/69102027-3fe60000-0a2f-11ea-867d-55c70b14dad3.png)

**Comment by xuzhg** [comment]
@TimonFeldmann Can the following work at your side : `..filter=contains(tolower(cast(MemberType, Edm.String))`?

**Comment by hidegh** [comment]
@TimonFeldmann does the return value type differ when you query without the groupby and with groupin'?

**Comment by TimonFeldmann** [comment]
@xuzhg @hidegh 
I apologize for the late reply on this.
We ended up running into this issue again on another team at my workplace and discovered the issue lies in returning the IQueryable of the entity inside of an ActionResult.

**Does not work with aggregates:**
```C#
namespace Api.Controllers
{
    public class MyController : ODataController
    {
        [ProducesResponseType(typeof(ODataValue), Status200OK)]
        [ODataRoute("EntityWithEnumerable")]
        [EnableQuery]
        public IActionResult GetEntityWithEnumerable()
        {
            return Ok(_dbContext.EntityWithEnumerable);
        }
    }
}
```

**Works with aggregates and resolves all issues:**
```C#
namespace Api.Controllers
{
    public class MyController : ODataController
    {
        [ProducesResponseType(typeof(ODataValue), Status200OK)]
        [ODataRoute("EntityWithEnumerable")]
        [EnableQuery]
        public IQueryable<EntityWithEnumerable> GetEntityWithEnumerable()
        {
            return _dbContext.EntityWithEnumerable;
        }
    }
}
```

The key here being that the return result of the OData route needs to be an IQueryable with a generic representing the entity type registered with OData.

This is the solution to my original issue and this ticket can be closed.

Thank you for your attention regarding this @xuzhg and @hidegh !
