### ISSUE TITLE
Filtering on a property of casted object fails

### ISSUE THREAD

**Issue by KanishManuja-MS** [OData/WebApi#1962]
### Issue
Filtering on a property of a casted object fails with the following error message - 
Instance property 'PropertyName' is not defined for type 'System.Object'. 

### Assemblies affected
WebAPI 7.2.0

### Reproduce steps
Create an entity set of vehicles and you want to get all the 4-door cars from the entity set. One would expect the following query to work - 

```
~/vehicles?$filter=cast('NS.Car')/DoorCount eq 4
```
### Expected result

Cars with 4 doors. 

### Actual result
An error occurs - Property Name DoorCount does not exist on instance of System.Object. 

### Additional detail
If the protocol should support this, the issue is likely around binding the cast binding - https://github.com/OData/WebApi/blob/5061dcad757599b93ff990079832123a73e0e091/src/Microsoft.AspNet.OData.Shared/Query/Expressions/FilterBinder.cs#L368/

**Comment by xuzhg** [comment]
@KanishManuja-MS 

Does ODL and Web API support `$filter=NS.Car/DoorCount eq 4`?

Besides, according to the ABNF, the type name should not have the single quote.

**Comment by xuzhg** [comment]
Merged. Close it.
