### ISSUE TITLE
Inconsistent behavior on 'key' parameter convention for OData routes

### ISSUE THREAD

**Issue by julealgon** [OData/WebApi#1965]
The OData standard route convention for entity sets with a single ID property does not behave consistently when using composite key convention: the entityset route is matched, but binding does not occur and arguments have default values.

My team spent a couple hours trying to figure out why the value was 0 on the controller even though they were passing the correct value in the URL.

### Assemblies affected

- Microsoft.AspNetCore.OData 7.2.2

### Reproduce steps

1. Create an entity with a single key property.
2. Create a get endpoint by key, and use `key{PropertyName}` as the argument (instead of `key`)
3. Call into the route, passing a value for the key: eg `GET /odata/entities(10)`
4. Notice how the route matches and hits the controller, but `key{PropertyName}` is 0

Use the following repo as a minimal repro:
- https://github.com/julealgon/ODataBindingIssue.git

`GET http://localhost:33616/odata/entities(10)`

![image](https://user-images.githubusercontent.com/461579/69378059-4d4bf600-0c8c-11ea-9b53-b2e3678cbaf8.png)

VS

![image](https://user-images.githubusercontent.com/461579/69378567-64d7ae80-0c8d-11ea-8b23-01b4229a8fe2.png)

### Expected result

2 possibilities:
1. The route should NOT be matched when the key convention is incorrect. Follow existing convention: `key` for single key, `keyX`, `keyY` for composite X/Y key
2. The route should match and the value should be BOUND. Allow for composite key convention when not using composite keys: bind either `key` OR `keyX` for entity X key property

The second seems slightly more intuitive to me, but the first also makes sense if we want to follow strict conventions in the library.

### Actual result

Route matches, but key value is not bound.

### Additional detail

The most puzzling aspect of this problem is how inconsistent it behaves, and leads people into incorrect assumptions.

On scenario 3 below, if I change from `keyOnly` to `keyThisDoesNotExist`, the route does not match anymore. It's clearly using a separate process to define the route match and then to perform argument binding.

These processes should use the same logic to avoid this problem.

Scenario 1: Composite Key + Composite Key convention
✔️  CORRECT

Matches route: `GET /server/entities(10,'a')`

```
class Entity
{
    [Key]
    int First { get; set; }

    [Key]
    string Second { get; set; }
}

class EntitiesController
{
    IQueryable<Entity> Get(int keyFirst, string keySecond)
    ...
}

```
```
keyFirst = 10
keySecond = "a"
```

---

Scenario 2: Single Key + Single Key convention
✔️  CORRECT

Matches route: `GET /server/entities(10)`

```
class Entity
{
    [Key]
    int Only { get; set; }
}

class EntitiesController
{
    IQueryable<Entity> Get(int key)
    ...
}

```
``` 
key = 10
``` 

---

Scenario 3: Single Key + Composite Key convention:
❌  INCORRECT

Matches route: `GET /server/entities(10)`

```
class Entity
{
    [Key]
    int Only { get; set; }
}

class EntitiesController
{
    IQueryable<Entity> Get(int keyOnly)
    ...
}
```

``` 
keyOnly = 0 (default value)
```

**Comment by KanishManuja-MS** [comment]
@julealgon Thanks for the suggestion.

**Comment by habbes** [comment]
Hey @julealgon (cc @odero)

I used the repo you shared to reproduce the behavior you described, and all scenarios worked as you described except for the following one:

I changed `Get(int keyOnly)` to `Get(int keyThisDoesNotExist)` and the route was still matched.

Furthermore, I found out the following interesting cases about the routing:

- when the controller only defines `Get(int key)`:
  - both `odata/Entities(10)` (with key set to 10) and `odata/Entities` (with key set to default 0) are routed to that method
- when only `Get(int keyProp)` is defined:
  - both` odata/Entities(10)` (with key set to default 0) and `odata/Entities` (with key set to default 0) are routed to that method

- when only `Get()` is defined:
  - both `odata/Entities(10)` and `odata/Entities` are routed to that method

- when `Get(int key)` and `Get()` are defined:
  - `odata/Entities(10)` is routed to `Get(int key)` (with key set to 10)
  - `odata/Entities` is routed to `Get()`

- when `Get(int keyProp)` and `Get()` are defined:
  - both `odata/Entities(10)` and `odata/Entities` are routed to `Get()`
  - `Get(int keyProp)` is effectively ignored

And obviously defining both `Get(int keyProp)` and `Get(int key)` won't compile.

So it appears that the current default behavior when only one `Get()` method is defined is to route the GET request to that method regardless of its parameters.

**Comment by julealgon** [comment]
@habbes , my apologies, I was thinking about that scenario from memory and forgot to double check it in the sample.

The problem actually happens when declaring named parameters on the call, not by renaming the argument. So in that case, try calling `odata/Entities(This DoesNotExist=10)` and `odata/Entities(Only=10)`: the former causes a 404, whereas the later his the controller.

My bad for the confusion on the one.

**Comment by habbes** [comment]
@julealgon thanks for the clarification. I've also tested, and it works as you describe. `odata/Entities(Only=10)` is treated the same as `odata/Entities(10)` (including the binding issues) and `odata/Entities(ThisDoesNotExist=10)` returns a 404.

**Comment by habbes** [comment]
@julealgon We'll add support for binding to `keyPropName` as you suggested. Let's address the other unexpected behavior (routing entity set and entity by key requests to the same `Get()` method) in a separate issue: #1973

**Comment by habbes** [comment]
It's also worth mentioning that the behavior is the same when using `PUT` and `PATCH`, i.e.:

- `Put(int keyPropName)` gets called with `keyPropName` set to 0
- `Patch(int keyPropName)` gets called with `keyPropName` set to 0
