### ISSUE TITLE
E2E V3: Clean up the warning for obsolete function call

### ISSUE THREAD

**Issue by xuzhg** [OData/WebApi#197]
If you run buildqa.cmd in e2e, you will get a lot of warnings. For example:

QueryComposition\Fuzzing\FuzzingController.cs(27,10): warning CS0618: 'System.W
eb.Http.QueryableAttribute' is obsolete: 'This class is obsolete; use the Enabl
eQueryAttribute class from the System.Web.Http.OData or System.Web.OData namesp
ace.' [D:\visualstudioOnline\odatateam\webapie2ev3\src\WebStack.QA.Test.OData\W
ebStack.QA.Test.OData.csproj]

Please clean up all the warning.

**Comment by VikingsFan** [comment]
Fixed

**Comment by VikingsFan** [comment]
commit: b1273f29f77dfa23e3918ec060eda11fb0a1e069

**Comment by xuzhg** [comment]
Verified.
