### ISSUE TITLE
3.0: Issue with enums

### ISSUE THREAD

**Issue by Diraekt** [OData/WebApi#1971]
*Short summary (3-5 sentences) describing the issue.*
Filter by Assembly-Full-Qualified Enum Value don't work.
(worked in .Net Core 2.2 with Full Framework targeted)

### Assemblies affected
**Microsoft.OData.Core.dll** -> BinaryOperatorBinder.cs -> GetOperandFromToken

*Which assemblies and versions are known to be affected e.g. OData WebApi lib 6.1.0
**7.3.0-Nightly201911272029**
### Reproduce steps

Filter by an enum Value ex:
http://localhost/odata/v3/job?$filter=Name eq 'maaaaaTestJob' and JobStatus eq SharedDto.PublicApi.JobStatus'Solved''

### Expected result

**The filtered result should be returned**

### Actual result

`  {"error":{"code":"Microsoft.OData.ODataException: The string 'SharedDto.PublicApi.JobStatus'Solved'' is not a valid enumeration type constant.\r\n   at Microsoft.OData.UriParser.DottedIdentifierBinder.BindDottedIdentifier(DottedIdentifierToken dottedIdentifierToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.BindCast(DottedIdentifierToken dottedIdentifierToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)\r\n   at Microsoft.OData.UriParser.BinaryOperatorBinder.GetOperandFromToken(BinaryOperatorKind operatorKind, QueryToken queryToken)\r\n   at Microsoft.OData.UriParser.BinaryOperatorBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)\r\n   at Microsoft.OData.UriParser.BinaryOperatorBinder.GetOperandFromToken(BinaryOperatorKind operatorKind, QueryToken queryToken)\r\n   at Microsoft.OData.UriParser.BinaryOperatorBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)\r\n   at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()\r\n   at Microsoft.AspNet.OData.Query.FilterQueryOption.get_FilterClause()\r\n   at MyAppApi.Base.ODataQueryOptionsParser.GetExpandedProperties(ODataQueryOptions queryOptions) in C:\\Work\\Base\\ODataQueryOptionsParser.cs:line 15\r\n   at MyAppApi.Base.BaseIdentityEntityController`2.ProjectToDto(IQueryable`1 itemsQuery, ODataQueryOptions`1 oDataQueryOptions) in C:\\Work\\Base\\BaseEntityOdataController.cs:line 292\r\n   at MyAppApi.Base.DynamicColumnBaseEntityOdataController`2.ProjectToDto(IQueryable`1 itemsQuery, ODataQueryOptions`1 oDataQueryOptions) in C:\\Work\\Base\\DynamicColumnBaseEntityOdataController.cs:line 71\r\n   at MyAppApi.Base.BaseIdentityEntityController`2.Get(ODataQueryOptions`1 options) in C:\\Work\\Base\\BaseEntityOdataController.cs:line 80\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)","message":"Microsoft.OData.ODataException: The string 'SharedDto.PublicApi.JobStatus'Erledigt'' is not a valid enumeration type constant.\r\n   at Microsoft.OData.UriParser.DottedIdentifierBinder.BindDottedIdentifier(DottedIdentifierToken dottedIdentifierToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.BindCast(DottedIdentifierToken dottedIdentifierToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)\r\n   at Microsoft.OData.UriParser.BinaryOperatorBinder.GetOperandFromToken(BinaryOperatorKind operatorKind, QueryToken queryToken)\r\n   at Microsoft.OData.UriParser.BinaryOperatorBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)\r\n   at Microsoft.OData.UriParser.BinaryOperatorBinder.GetOperandFromToken(BinaryOperatorKind operatorKind, QueryToken queryToken)\r\n   at Microsoft.OData.UriParser.BinaryOperatorBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)\r\n   at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()\r\n   at Microsoft.AspNet.OData.Query.FilterQueryOption.get_FilterClause()\r\n   at MyAppApi.Base.ODataQueryOptionsParser.GetExpandedProperties(ODataQueryOptions queryOptions) in C:\\Work\\Base\\ODataQueryOptionsParser.cs:line 15\r\n   at MyAppApi.Base.BaseIdentityEntityController`2.ProjectToDto(IQueryable`1 itemsQuery, ODataQueryOptions`1 oDataQueryOptions) in C:\\Work\\Base\\BaseEntityOdataController.cs:line 292\r\n   at MyAppApi.Base.DynamicColumnBaseEntityOdataController`2.ProjectToDto(IQueryable`1 itemsQuery, ODataQueryOptions`1 oDataQueryOptions) in C:\\Work\\Base\\DynamicColumnBaseEntityOdataController.cs:line 71\r\n   at MyAppApi.Base.BaseIdentityEntityController`2.Get(ODataQueryOptions`1 options) in C:\\Work\\Base\\BaseEntityOdataController.cs:line 80\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)"}}Internal Server Error`

**Comment by alex-ariza-aml** [comment]
Did you find a solution for this??
