### ISSUE TITLE
Not able to expand a null navigation property that is based on a foreign key with shadow property

### ISSUE THREAD

**Issue by obohaciak** [OData/WebApi#1979]
I have an ASP.NET Core app that uses OData to query DB using entities mapped with EntityFramework Core. The DB contains 2 tables joined with FK, both having composite PKs. Both tables are exposed as entities where one of the columns in PK is a shadow property. When expanding a navigation property based on this FK, OData fails to serialize the result when navigation property is null.

### Assemblies affected

Microsoft.AspNetCore.OData (7.2.2), targetting ASP.NET Core 2.2 (contains Microsoft.EntityFrameworkCore 2.2.6)

### Reproduce steps
These are the tables
```
CREATE TABLE [dbo].[Person](
	[ShadowId] [int] NOT NULL DEFAULT 1,
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NULL,
    CONSTRAINT [PK_Owner] PRIMARY KEY CLUSTERED ([ShadowId] ASC, [Id] ASC)
)
GO

CREATE TABLE [dbo].[Pet](
	[ShadowId] [int] NOT NULL DEFAULT 1,
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[OwnerId] [int] NULL,
    CONSTRAINT [PK_Pets] PRIMARY KEY CLUSTERED ([ShadowId] ASC, [Id] ASC)
)
GO

ALTER TABLE [dbo].[Pet]  WITH CHECK ADD  CONSTRAINT [FK_Pet_Owner] FOREIGN KEY([ShadowId], [OwnerId]) REFERENCES [dbo].[Person] ([ShadowId], [Id])
GO
```
Let's add 2 rows to show cases when the principal entity is null and non-null
```
SET IDENTITY_INSERT [dbo].[Person] ON 
INSERT [dbo].[Person] ([Id], [Name]) VALUES (4, N'Annie')
SET IDENTITY_INSERT [dbo].[Person] OFF
GO

SET IDENTITY_INSERT [dbo].[Pet] ON 
INSERT [dbo].[Pet] ([Id], [Name], [OwnerId]) VALUES (4, N'Mittens', 4)
INSERT [dbo].[Pet] ([Id], [Name], [OwnerId]) VALUES (5, N'Patches', NULL)
SET IDENTITY_INSERT [dbo].[Pet] OFF
GO 
```

This is my DbContext's model
```
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {            
            modelBuilder.Entity<Person>(entity =>
            {
                entity.Property<int>("ShadowId");
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.HasKey("ShadowId", "Id");
                entity.Property(e => e.Name).HasMaxLength(100).IsRequired(false);
            });

            modelBuilder.Entity<Pet>(entity =>
            {
                entity.Property<int>("ShadowId");
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.HasKey("ShadowId", "Id");
                entity.Property(e => e.Name).HasMaxLength(100).IsRequired(false);
                entity.HasOne(d => d.Owner)
                    .WithOne()
                    .HasForeignKey<Pet>("ShadowId", "OwnerId");                
            });

            OnModelCreatingPartial(modelBuilder);
        }
```

OData query
```
https://localhost:44306/odata/Pets?$expand=Owner
```

and generated query
```
SELECT [p].[ShadowId], [p].[Id], [p].[Name], [p].[OwnerId], [p.Owner].[ShadowId], [p.Owner].[Id], [p.Owner].[Name]
FROM [Pet] AS [p]
LEFT JOIN [Person] AS [p.Owner] ON ([p].[ShadowId] = [p.Owner].[ShadowId]) AND ([p].[OwnerId] = [p.Owner].[Id])
```

### Expected result

Expanding a null navigation property that is based on shadow properties works the same a withs field-backed property.

### Actual result

Serialization issue - _SyntaxError: JSON.parse: unexpected end of data at line 1 column 84 of the JSON data_

_The EDM instance of type '[ODataEFCoreShadowKeys.Person Nullable=True]' is missing the property 'Id'_

stacktrace

```
   at Microsoft.AspNet.OData.ResourceContext.GetPropertyValue(String propertyName)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateStructuralProperty(IEdmStructuralProperty structuralProperty, ResourceContext resourceContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateStructuralPropertyBag(IEnumerable`1 structuralProperties, ResourceContext resourceContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateResource(SelectExpandNode selectExpandNode, ResourceContext resourceContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteComplexAndExpandedNavigationProperty(IEdmProperty edmProperty, ExpandedNavigationSelectItem expandedNavigationSelectItem, ResourceContext resourceContext, ODataWriter writer, Boolean expandReference)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteExpandedNavigationProperties(SelectExpandNode selectExpandNode, ResourceContext resourceContext, ODataWriter writer)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
```

### Additional detail

I have created a repository with a minimal repro case described in this example at [obohaciak/ODataEFCoreShadowKeys](https://github.com/obohaciak/ODataEFCoreShadowKeys)

@xsmerek has created a PR with a proposed fix, see #https://github.com/obohaciak/WebApi/pull/1. It also describes his analysis of the root cause,

**Comment by odero** [comment]
@obohaciak I used your sample project but was unable to reproduce the error. Instead I'm getting a different odd behaviour. Hitting `https://localhost:44306/odata/Pets?$expand=Owner`
doesn't raise any errors and instead only returns results for the Pet where Owner is not null.

```json
{
    "@odata.context": "https://localhost:44304/odata/$metadata#Pets(Owner())",
    "value": [
        {
            "Id": 4,
            "Name": "Mittens",
            "Owner": {
                "Id": 4,
                "Name": "Annie"
            }
        }
    ]
}
```

Similarly, hitting `https://localhost:44306/odata/Pets` returns
```json
{
    "@odata.context": "https://localhost:44304/odata/$metadata#Pets",
    "value": [
        {
            "Id": 4,
            "Name": "Mittens"
        }
    ]
}
```

@xuzhg it would be worth reviewing https://github.com/obohaciak/WebApi/pull/1 to see if it's a viable fix for a merge

**Comment by obohaciak** [comment]
Thank you @odero for reviewing the sample project. I'm sorry but I can't explain the behavior you're observing. I tried again just now to make sure I haven't messed up the repro case, but it works on my end as I've described above. Can you check through SQL Server Provider or Logging that the SQL queries sent by EF Core to MSSQL run OK and return 2 rows with expected data?

**Comment by xuzhg** [comment]
@odero I am glad to see the contribution from @obohaciak . 

@obohaciak It's better to create a PR for us to review. Looking forward your contributions.

**Comment by obohaciak** [comment]
@xuzhg, I have created a PR #1983 for you to review. Thank you

**Comment by xuzhg** [comment]
@obohaciak Thanks.

**Comment by gathogojr** [comment]
@obohaciak I think I managed to reproduce the issue. With your sample scenario above, what I observed is that any query that returns results with pet that has no owner will result into a malformed JSON response. If the client tries to process or parse that malformed JSON the serialization error that you reported would be observed.

See screenshots for two different queries below:

http://localhost:4074/odata/Pets?$expand=Owner
![image](https://user-images.githubusercontent.com/28291332/73055892-cb9c6280-3e9e-11ea-9535-a4b2b9387d2b.png)


http://localhost:4074/odata/Pets(5)?$expand=Owner
![image](https://user-images.githubusercontent.com/28291332/73055825-b1628480-3e9e-11ea-82ee-f1aadb7d5d29.png)

I'll spend some time to identify the exact source of the error, assess options to addressing it and also review the PR that @xsmerek created

**Comment by xsmerek** [comment]
@gathogojr I've tried to reproduce the issue on version **7.3.0** with **.NET Core 3.1** and the problem is not reproducible. The call returns expected result:

```
{
    "@odata.context": "https://localhost:44391/odata/$metadata#Pets(Owner())",
    "value": [
        {
            "Id": 4,
            "Name": "Mittens",
            "Owner": {
                "Id": 4,
                "Name": "Annie"
            }
        },
        {
            "Id": 5,
            "Name": "Patches",
            "Owner": null
        }
    ]
}
```

I've discussed the issue with @obohaciak and since we plan to move to .NET Core 3.1 next month, we consider this issue resolved and it can be closed.

**Comment by gathogojr** [comment]
@xsmerek I was just about let you know about the same. I created a reference [working solution](https://github.com/gathogojr/Repro01ODataWebApiIssue1979) against the following framework and packages:
- ASP.NET Core 3.1
- Microsoft.EntityFrameworkCore 3.1.1
- Microsoft.AspNetCore.OData 7.3.0

**Comment by xsmerek** [comment]
@gathogojr Thank you very much, I'm glad that the issue is resolved. I'm looking forward to switching to ASP.NET Core 3.1.

**Comment by obohaciak** [comment]
Thank you @gathogojr  & and @xsmerek. I believe the issue can be closed as no longer reproducible on ASP.NET Core 3.1 which is the LTS version as per https://dotnet.microsoft.com/platform/support/policy/dotnet-core. With ASP.NET 2.2 now at EOL, the fix is to upgrade to supported version of ASP.NET Core.

**Comment by Ken-ISC** [comment]
I'm having the same issue but in getting the XML format @gathogojr , hoping you could help me.
link to my post here : https://stackoverflow.com/questions/72566646/odata-select-and-expand-not-working-on-xml-response
