### ISSUE TITLE
$select on property of type byte[] not working anymore since 7.2.3

### ISSUE THREAD

**Issue by wurst0815** [OData/WebApi#1984]
*Short summary (3-5 sentences) describing the issue.*
Until 7.2.2 we were able to use $select on an entity to select only values of a specific property of type byte[]. Since 7.2.3 this throws an InvalidOperationException.
### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData WebApi lib 6.1.0
Microsoft.AspNet.OData 7.2.3
### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*
Have an Entity with a Property of type byte[]. Try to query an EntitySet and to only select this specific property e.g. $select=myPropertyOfTypeByte.
### Expected result
Serialized Byte Array
*What would happen if there wasn't a bug.*

### Actual result

     "internalexception": {
        "message": "DbExpressionBinding requires an input expression with a collection ResultType.\r\nParameter name: input",
        "type": "System.ArgumentException",
        "stacktrace": "   at System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder.DbExpressionBuilder.BindAs(DbExpression input, String varName)\r\n   at

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by xuzhg** [comment]
@wurst0815 Thanks for reporting this. It seems "byte[]" and "char[]" has the similar problem, because both of them are considered as a non-collection primitive type.  I had a PR for it. Would you please take a look, thanks.

**Comment by xuzhg** [comment]
I had a pr https://github.com/OData/WebApi/pull/1985

**Comment by xuzhg** [comment]
Merged at 7.3. RTM. Please let me know if you have further questions
