### ISSUE TITLE
Calling Page(0, 0) throws exception with incorrect error message

### ISSUE THREAD

**Issue by YishaiHornbacher** [OData/WebApi#1989]
calling `ODataModelBuilder.EntitySet<T>("someName").EntityType.Page(0,0)` throws the following exception:

 
> ---> System.ArgumentOutOfRangeException: Value must be greater than or equal to 0. (Parameter 'value')
> Actual value was 0.

### Assemblies affected

AspNetCore.OData 7.3.0-Nightly201911222308, but likely a more general problem.

### Reproduce steps

`new ODataConventionModelBuilder(app.ApplicationServices).EntitySet<SomeObject>("SomeObject").EntityType.Page(0, 0).GetEdmModel();`

### Expected result

Either it would not throw an exception or the exception message would indicate that the number must be greater than zero. I assume the former as the value is allowed to be null, so why treat zero any differently? But either way, one of them is wrong.

### Actual result

An exception is being thrown with an incorrect message.

### Additional detail
in `ModelBoundQuerySettings`

```
    public int? MaxTop
    {
      get
      {
        return this._maxTop;
      }
      set
      {
        if (value.HasValue)
        {
          int? nullable = value;
          int num = 0;
          if (nullable.GetValueOrDefault() <= num & nullable.HasValue)
            throw Error.ArgumentMustBeGreaterThanOrEqualTo(nameof (value), (object) value, (object) 0);
        }
        this._maxTop = value;
      }
    }

```
(As an aside HasValue is checked twice for no reason)

Either that should be `nullable.GetValueOrDefault() < num` or `Error.ArgumentMustBeGreaterThanOrEqualTo(nameof (value), (object) value, (object) 1)`, whichever is the correct resolution.

This code is duplicated in the set method of PageSize as well.

**Comment by Sreejithpin** [comment]
HI Yishai,
   For pagesize, there is a difference between null and zero. When you say null OData assumes it as "not configured" and bypass it. But once you put 0 it means its configured and its configured wrongly as pagesize 0 doesnt make sense. Thats why there is a difference between 0 and null. Please let us know if that clarifies your question or else we can have further discussions

**Comment by YishaiHornbacher** [comment]
Hi Sreejithpin,

OK, that makes sense. So then the problem is with the error message. A small bug.

**Comment by xuzhg** [comment]
Merged. Thanks.
