### ISSUE TITLE
broken build after new year

### ISSUE THREAD

**Issue by MolallaComm** [OData/WebApi#1998]
It would appear that webapi no longer builds in the new year.

The expression "[System.Convert]::ToInt16(40102)" cannot be evaluated.

Something to do with the way the revision number is calculated from the date I think:

WebApi\tools\WebStack.versions.settings.targets

Looked at it briefly and couldn't figure out how to fix it.

**Comment by xuzhg** [comment]
@MolallaComm can you point me the build link?

**Comment by MolallaComm** [comment]
Just clone the repo and try to build it using VS2019 - when you go to open the project, it won't load because it runs into the above error where 40102 is greater than that max value allowed for In16.

**Comment by xuzhg** [comment]
@MolallaComm Thanks. I just fixed it using the same fix in maintenance-v3.  Try it and let me know any other problems. Thanks.
