### ISSUE TITLE
Error on $expand with a [NotMapped] property

### ISSUE THREAD

**Issue by dvanschepdael** [OData/WebApi#1999]
Hi!

I don't know if it is a bug or if I did something wrong but it worked on the previous version.
The problem occurs when I tried to $expand a (collection type) property marked as [NotMapped] but added to EDM with HasMany().

### Assemblies affected

Microsoft.AspNetCore.OData v7.3.0

### Reproduce steps

Repo: https://github.com/dvanschepdael/ODataBug
.NET Core 2.2: http://localhost:5001/api/Articles?$expand=tags
.NET Core 3.1: http://localhost:5000/api/Articles?$expand=tags

### Expected result

Json data

### Actual result

Throw an exception:
`ArgumentException: Expression of type 'System.Object' cannot be used for parameter of type 'System.String' of method 'WebApplication.Models.Tag GetParameterValue[Tag](Microsoft.EntityFrameworkCore.Query.QueryContext, System.String)' (Parameter 'arg1')`

### Additional detail

Worked fine on previous version v7.2.3 with .NET Core 2.2

PS: Thanks for this amazing framework !

**Comment by KanishManuja-MS** [comment]
@dvanschepdael Did the EF version referenced change between your updates? It seems like the error is stemming from EF.

**Comment by dvanschepdael** [comment]
I don't think it comes from EF.
We did some tests in .NET Core 3.1 with my friend @rdhainaut, and it works when we use a "CollectionProperty" instead of a "HasMany". But in this case, the $expand is no more required and data are included systematically.

`articleEntitySetConfiguration.EntityType.CollectionProperty(a => a.Tags);
//articleEntitySetConfiguration.EntityType.HasMany(a => a.Tags); //error`

**Comment by dvanschepdael** [comment]
Osef complet
