### ISSUE TITLE
V5.5: Support Edm.Date & Edm.TimeOfDay primitive data types

### ISSUE THREAD

**Issue by xuzhg** [OData/WebApi#2]
ODL announced the release of V6.8.0 as below: 
http://www.nuget.org/packages/Microsoft.OData.Core/6.8.0 

In this release, ODL supports two new primitive types: Edm.Date & Edm.TimeOfDay.

Customers need these two new types supported in Web API.

**Comment by xuzhg** [comment]
CodePlex: https://aspnetwebstack.codeplex.com/workitem/2158

**Comment by xuzhg** [comment]
Checked in. Thanks.

**Comment by xuzhg** [comment]
Please refer to: [Edm.Date & Edm.TimeOfDay Support in Web API OData V4](http://odata.github.io/WebApi/Date-and-TimeOfDay-Support/) for simple tutorial.

**Comment by mj1856** [comment]
FYI - I am working on adding proper `Date` and `TimeOfDay` support to .NET Core.  See dotnet/corefx#700 and http://github.com/mj1856/corefx-dateandtime

At some point in the future (not now), it may be worth using these and dropping the ones in `Microosft.OData.Edm.Library`.

@xuzhg - Your input would be appreciated on the project.  Thanks.
