### ISSUE TITLE
Add support in the ODataPathParser for case insensitive comparisons

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#20]
May be nice-to-have  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 619](http://aspnetwebstack.codeplex.com/workitem/619)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Nov 10, 2012 at 12:24 AM
**Reported by:**	youssefm
**Updated on:**	Sep 23, 2013 at 7:46 PM
**Updated by:**	danroth27

**Comment by LianwMS** [comment]
On *2013-09-24 02:46:08 UTC*, **danroth27** commented:

We will do case insensitivity all at once.

**Comment by xuzhg** [comment]
Please see the check-in: 7b3367371b1632cf33161cc090e67994c0b6067a

**Comment by MrTomWhite** [comment]
:tada: This is awesome! Great fix @xuzhg :+1:
