### ISSUE TITLE
When requesting V4 service with unknown header, server returns 404

### ISSUE THREAD

**Issue by karataliu** [OData/WebApi#200]
When sending request to a WebAPI OData V4 endpoint with V3 header, say MaxDataServiceVersion: 3.0, the service returns 404.

As the service version is V4, it may ignore the V3 service header here.

Request:
GET http://services.odata.org/TripPinWebApiService/People HTTP/1.1
MaxDataServiceVersion: 3.0
Host: services.odata.org

Response
HTTP/1.1 404 Not Found
Content-Length: 103
Content-Type: text/html
Server: Microsoft-IIS/8.0
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=e4d1669c37164237c21bb787422f6703d540a38737e92635ddc25140f717e705;Path=/;Domain=services.odata.org
Date: Fri, 23 Jan 2015 02:32:24 GMT

The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by LianwMS** [comment]
Sync with @karataliu, the issue will be solved with the fix of  https://github.com/OData/WebApi/issues/191
