### ISSUE TITLE
OData WebApi (Microsoft.AspNet.OData) - Changelog missing for version 7.3.0

### ISSUE THREAD

**Issue by IgorWolbers** [OData/WebApi#2005]
The [official changelog site "OData WebApi changelog"][1] of does not include the changelog for version 7.3.0 of [`Microsoft.AspNet.OData`][0]

*side note: I believe this is the correct place to post this but if not let me know where I should post this. Thanks in advance.*

### Assemblies affected

[`Microsoft.AspNet.OData`][0] version 7.3.0

### Reproduce steps
N/A

### Expected result

N/A

### Actual result

N/A

### Additional detail

[0]: https://www.nuget.org/packages/Microsoft.AspNet.OData/7.3.0
[1]: https://docs.microsoft.com/en-us/odata/changelog/webapi-7x

**Comment by KanishManuja-MS** [comment]
@IgorWolbers Thanks for letting us know. We will follow-up on that and have release notes for 7.3.0 uploaded. 
@xuzhg can you check why it has not been published?

**Comment by xuzhg** [comment]
@IgorWolbers the release note is in the PR.  Will merge today. https://github.com/MicrosoftDocs/OData-docs/pull/87

**Comment by xuzhg** [comment]
here it is. https://docs.microsoft.com/en-us/odata/changelog/webapi-7x
