### ISSUE TITLE
Should fetch the Uri Literal value from ODL ODataPath, doesn't calculate it by WebAPI again

### ISSUE THREAD

**Issue by xuzhg** [OData/WebApi#201]
For example:

~/Customers(1)/Default.MyFunction(p1=xxxx)

ODL ODataPath includes the OperationPathSegment in which has the parameter value. 

Web API should fetch the parameter value directly form ODL ODataPath.

This fix can help to fix the Enum Prefix free problem.

**Comment by congysu** [comment]
Resolved as part of #7.
