### ISSUE TITLE
$top affects sorting

### ISSUE THREAD

**Issue by markbeij** [OData/WebApi#2011]
Doing requests without $top gives me a different item as the first record. I expect $top not affect sorting.

### Assemblies affected

OData WebApi lib 7.2.2 up to 7.3.0. Probably in earlier versions as well

### Reproduce steps
* Run AspNetCoreODataSample.Web from my fork: https://github.com/markbeij/WebApi
* Request GET /Sample
* Request GET /Sample?$top=1
* Request GET /Sample2
* Request GET /Sample2?$top=1
* Request GET /Sample3
* Request GET /Sample3?$top=1

See my latest commit to see what I adde

### Expected result

With or without $top, I expect the first result to be the same for all these calls

### Actual result

With $top the first result is not the same as when $top is omitted for the calls to GET /Sample and GET /Sample2.
GET /Sample3 gives the same first result with or without $top=1 as expected

**Comment by xuzhg** [comment]
@markbeij I think it's related stand sorting if you have (only have) $top. 
Could you please try set "EnsureStableOrdering" as false on [EnableQuery] and let us know the result?

**Comment by markbeij** [comment]
Thanks for the tip, I will give it a try

**Comment by markbeij** [comment]
`EnsureStableOrdering` solved this issue, thanks!
