### ISSUE TITLE
Action and open-type

### ISSUE THREAD

**Issue by cfauchere** [OData/WebApi#2013]
I have been playing around with OData actions and functions. As documented I can add parameters to an action using the Parameter<> method but it forces me to declare every single parameter which does not work well if the action acts on an open-type. Adding extra parameters to the request leads to a null ODataActionParameter.
The ugly workaround I have found is to create an open-type property bag complex-type and add a parameter of this type. But this does not align well with the open-type semantic where all properties are flatten.

### Assemblies affected

Microsoft.AspNetCore.OData 7.2.3

### Reproduce steps

** Model **

var myEntityAction = myEntity.Collection.Action("dosomething");
myEntityAction.Parameter<string>("arg").Required();

** controller **
public async Task<IActionResult> DoSomethingAsync(ODataActionParameters actionParameters)
{
}

** request body **
{
"arg":"hello".
"otherarg": "world"
}

### Expected result

the method in the controller gets an instance of ODataActionParameters that contains all properties including those that are not declared in the model

### Actual result

the ODataActionParameters is null

**Comment by xuzhg** [comment]
Close as duplicated at #2020
