### ISSUE TITLE
Question: When do you think endpoint routing for OData is available?

### ISSUE THREAD

**Issue by jan-johansson-mr** [OData/WebApi#2018]
Hi,

Thanks for a good project!

I am curious to when you think OData will be enabled with endpoint routing (as written in the [dev blog article](https://devblogs.microsoft.com/odata/experimenting-with-odata-in-asp-net-core-3-1/))?

Kind regards,
Jan Johansson

**Comment by xuzhg** [comment]
@jan-johansson-mr Thanks for querying. Endpoint routing is our high priority task to support.
