### ISSUE TITLE
[.NET Core 3.1] Hot to configure OData with Swagger?

### ISSUE THREAD

**Issue by MDzyga** [OData/WebApi#2024]
Hi,
I would like to configure Swagger (Swashbuckle vr 5.0.0) in my project (.NET Core 3.1) with OData (vr 7.3). Currently I get an exception:

`{"message":"No media types found in 'Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.SupportedMediaTypes'. Add at least one media type to the list of supported media types. "}`
### Assemblies affected
Microsoft.AspNetCore.OData 7.3.0
Swashbuckle.AspNetCore 5.0.0
.NET Core 3.1

### Reproduce steps
1) Create project with .NET Core 3.1
2) Configure Swashbuckle (my configuration it's here https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1442)
3) Create ODATA endpoint & standard endpoint
4) Run application

### Expected result
You will see at least standard endpoint.

### Actual result
You will see Swagger page with information 'Failed to load API Definition'

### Additional detail
In my opinion API/Swagger shouldn't generate OData endpoints because they are marked as ignored ([ApiExplorerSettings(IgnoreApi = true)])

**Comment by Mhirji** [comment]
We managed to get this working by adding this:

services.AddMvcCore(options =>
        {
            foreach (var outputFormatter in options.OutputFormatters.OfType<ODataOutputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
            {
                outputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
            }
            foreach (var inputFormatter in options.InputFormatters.OfType<ODataInputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
            {
                inputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
            }
        });

**Comment by MDzyga** [comment]
Could you tell me what type should I use?
In my case OfType() method requires type declaration

**Comment by MDzyga** [comment]
Ok, the solution is:

```
services.AddMvcCore(options =>
            {
                foreach (var outputFormatter in options.OutputFormatters.OfType<OutputFormatter>().Where(x => x.SupportedMediaTypes.Count == 0))
                {
                    outputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
                }

                foreach (var inputFormatter in options.InputFormatters.OfType<InputFormatter>().Where(x => x.SupportedMediaTypes.Count == 0))
                {
                    inputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
                }
            });
```

**Comment by KishorNaik** [comment]
I have created a service extension for the same.
Please check following link.
https://github.com/KishorNaik/Sol_OData_Swagger_Support

**Comment by Pzixel** [comment]
Works to me. Important note: formatters must be fixed AFTER odata is registered. This is why my original code `AddMvcCore(...).AddOData()` didn't work. Be careful.

**Comment by VarunSaiTeja** [comment]
> services.AddMvcCore(options =>
> {
>    foreach (var outputFormatter in options.OutputFormatters.OfType<OutputFormatter>().Where(x => x.SupportedMediaTypes.Count == 0))
>    {
>           outputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
>     }
> 
>    foreach (var inputFormatter in options.InputFormatters.OfType<InputFormatter>().Where(x => x.SupportedMediaTypes.Count == 0))
>    {
>          inputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
>    }
> });

It works
