### ISSUE TITLE
Question: OData architecture and where it fits

### ISSUE THREAD

**Issue by jan-johansson-mr** [OData/WebApi#2025]
Hi,

Testing out and kicking the tires of OData gave me an idea of how OData operates, I think like this:

- OData sits between my endpoint (controller) and client facing endpoint (OData uri route)
- OData want to operate on data context to do all of its magic, like select and so on
- E.g. Client -> OData route -> Controller -> OData magic -> Result to client

My first question is if I got this right...

My second question is if there is a way to intercept operations by OData, say that I want to intercept a `skip` or `select` before it happens, and make alternative or complementary actions.

Thanks

**Comment by xuzhg** [comment]
For your 2#, you can get the ODataQueryOptions from your method in the controller. 

before call ApplyTo(), you can modify the query options, includes $top, $skip.

**Comment by jan-johansson-mr** [comment]
Great! Thanks!
For 2#, It was nice to see that I can "inject" ODataQueryOptions into my method.

I'm doing some more labb with OData, and I'm busy trying to relax the connection to a data store (context) with OData. This is my scenario: I want to retrieve data from endpoints given the select, filtering, order and what not from OData query. Like this:

Client -> OData route -> Controller -> Endpoint(s) -> OData -> Result to client

In this case I don't want OData to do much magic on the result set! E.g. if I know there is a $skip=1 in the query, and I do skip 1 to the remote endpoint, then I don't want OData to do an additional skip 1 on that set.

What I've figured is that authoring some `IQueryable` and `IQueryProvider`, and plug that into my controller and return `IQueryable` to OData, then maybe I'll be able to achieve this.

E.g.

```
        [HttpGet]
        [EnableQuery]
        public IQueryable<Person> GetClassifications(ODataQueryOptions<Person> options)
        {
            return _persons;
        }
```
Where the provider kicks in when OData want the set from the `IQueryable<Person>`. I'm kinda half way through the provider already, but I want to check with a followup question.

My follow up question is, is this the way to go, or is there some other path with OData to consume data/datafragments from endpoints and aggregate into whatever set defined?

Thanks!
