### ISSUE TITLE
in 3.1: Any changes for actions and payloads? Migration fails for actions with no payload deserialized from body

### ISSUE THREAD

**Issue by NetTecture** [OData/WebApi#2027]
I am moving a marjor odata library in an attempt from dotnetcore 2.2 to 3.1. I have 342 unit tests and i am down to 19 red tests failing. So far this is only a dotnetcore upgrade, no efcore yet.

The following action:

        [HttpPost()]
        [ODataRoute("MaintenanceContract({key})/Operations.CanOperate")]
        public IActionResult ActionOperationsCanOperate(Guid key, [FromBody] Actions.OperationsRequest payload) {

worked fine in 2.2. In 3.1 i get no payload at all, it basically is null.  Any documentation of this change?

The calling code has not changed:

            var result = await c.For<OdataApi.MaintenanceContract>()
                .Key(contract.Identity)
                .Action("Operations.CanOperate")
                .Set(new {
                    Operation = OdataApi.Operations.Update
                })
                .ExecuteAsSingleAsync<OdataApi.OperationsCheckResult>();

using simple.odata.client, and again - in 2.2 this one shows green. It is possible this is related to the "." in the query url, but I am at a loss here. This definitely looks like a regression to me.

**Comment by NetTecture** [comment]
Ok, some hour later and I found out that this works:

public IActionResult ActionOperationsCanOperate([FromODataUri] Guid key, ODataActionParameters parameters) {

and (why am I not surprised) there is no available way to easily retrieve the values in a strong typed fasion, like a OdataActionParameters<T> extension that allows one to just get Value as object. Or some "To<T> mapping that just can be involved.

Time to rewrite all my actions then and write a little extension method to ODataActionParameters that covers my use cases because I am so totally not in the mood to write standard binding code manually ;)

Well, looks like this is "works as designed just with less allowed abuses than before" and I fell right into this trap of using standard binding ;)

**Comment by gathogojr** [comment]
Hi @NetTecture. Thank for the question. Glad that you figured out a solution that works. We'll proceed to close the issue.
