### ISSUE TITLE
MaxExpansionDepth is ignored when generating the response

### ISSUE THREAD

**Issue by fabiano** [OData/WebApi#2028]
The response doesn't contain all the expanded levels. The MaxExpansionDepth property of the EnableQuery attribute is only working to validate the number of levels requested.

The response is not affected by it. It's only returning 2 levels.

### Assemblies affected

Microsoft.AspNetCore.OData 7.3.0

### Reproduce steps

1. Clone the repository https://github.com/fabiano/max-expansion-depth
2. Run the project
2. Execute this HTTP request https://localhost:44314/Tenants?$expand=Companies($expand=People($expand=Phones))

### Expected result

The response must include the Phones collection.

### Actual result

The response doesn't include the Phones collection.

**Comment by KanishManuja-MS** [comment]
@fabiano In your repo, you have specified Max Expansion depth as 0. I wonder if the library ignores non-positive values. Do you see this not being enforced when it is set to 1?

**Comment by fabiano** [comment]
@KanishManuja-MS I tested with 3/10/int.MaxValue and the behaviour was the same.

**Comment by KenitoInc** [comment]
Hey @fabiano 
I have looked at your repo and the main cause of the MaxExpansionDepth issue is how you have define your navigation properties. You can either use one of the below solutions
- Add a Contained attribute to the expanded properties in the model
- Add entity sets for all entity types in the model builder

Below is some valuable information regarding navigation properties.
Odata supports navigation properties in two ways.
1. Contained navigation
2. Non-contained navigation

### Contained navigation
An entity belongs to an entity set declared within the entity container. 
When defining the model, we add a `Contained` attribute to define a contained navigation property
```csharp
public class Company
{
        public Guid Id { get; set; }

        public string Name { get; set; }

        [Contained]
        public IList<Person> People { get; set; }
}
```

In CSDL, the navigation property will be represented as:
```xml
<EntityType Name="Tenant">
    <Key><PropertyRef Name="Id"/></Key>
    <Property Name="Id" Nullable="false" Type="Edm.Guid"/>
    <Property Name="Name" Type="Edm.String"/>
    <NavigationProperty Name="Companies" Type="Collection(MaxExpansionDepth.Company)" ContainsTarget="true"/>
</EntityType>
```
We have an attribute `ContainsTarget="true"`

### Non-contained navigation
The Entity type being defined as a navigation property, exists on its own. It belongs to an entity set declared within the entity container.

We add entity sets using the model builder
```csharp
  builder.EntitySet<Tenant>("Tenants");
  builder.EntitySet<Company>("Companies");
  builder.EntitySet<Person>("People");
  builder.EntitySet<Phone>("Phones");
```
In CSDL, the navigation property will be represented as:
```xml
<EntityContainer Name="Container">
    <EntitySet Name="Tenants" EntityType="MaxExpansionDepth.Tenant"><NavigationPropertyBinding Target="Companies" Path="Companies"/>
    </EntitySet>
    <EntitySet Name="Companies" EntityType="MaxExpansionDepth.Company"><NavigationPropertyBinding Target="People" Path="People"/>
    </EntitySet>
    <EntitySet Name="People" EntityType="MaxExpansionDepth.Person"><NavigationPropertyBinding Target="Phones" Path="Phones"/>
    </EntitySet>
    <EntitySet Name="Phones" EntityType="MaxExpansionDepth.Phone"/>
</EntityContainer>
```
In this csdl, ContainsTarget attribute is not defined (It’s false by default)
For non-contained navigation, it’s highly recommended that an entity set or a singleton SHOULD contain a navigation property binding for each navigation property of its entity type. 

Related issue: https://github.com/OData/WebApi/issues/226

**Comment by KenitoInc** [comment]
Hey @fabiano 
Did you get a chance to look at my suggested fixes?

**Comment by fabiano** [comment]
@KenitoInc Yes, I was able to use the non-contained navigation solution without problems. Thank you for your help.

**Comment by KenitoInc** [comment]
@fabiano That's great. Let me close this issue for now. Incase you have more issues, feel free to reopen this issue or create a new issue
