### ISSUE TITLE
Entity type with ICollection<Nullable<>>

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#203]
A controller for a type that contains an ICollection<double?> (or any nullable) will fail to serialize the collection if it contains a null value. It will fail with a null reference exception in ODataCollectionSerializer.CreateODataCollectionValue() when it does an item.GetType() on a null item. 

The fix is likely to be something like (untested):

```
foreach (object item in enumerable)
{
    if (item == null)
    {
        valueCollection.Add(null);
    }
    else
    {
        IEdmTypeReference actualType = writeContext.GetEdmType(item, item.GetType());
        Contract.Assert(actualType != null);
        itemSerializer = itemSerializer ?? SerializerProvider.GetEdmTypeSerializer(actualType);
        if (itemSerializer == null)
        {
            throw new SerializationException(
                Error.Format(SRResources.TypeCannotBeSerialized, actualType.FullName(),
                typeof(ODataMediaTypeFormatter).Name));
        }
        // ODataCollectionWriter expects the individual elements in the collection to be the underlying
        // values and not ODataValues.
        valueCollection.Add(
            itemSerializer.CreateODataValue(item, actualType, writeContext).GetInnerValue());
    }
}
```

From: https://aspnetwebstack.codeplex.com/workitem/2230

**Comment by LianwMS** [comment]
cysu wrote Jan 6 at 3:47 PM

Follow up a way of extending OData formatters.

**Comment by congysu** [comment]
OData Web API 5.4 beta should fix this.

**Comment by VikingsFan** [comment]
And OData Web API 5.4 beta is available now, 
Can get it form NuGet: https://www.nuget.org/packages/Microsoft.AspNet.OData/5.4.0-beta
