### ISSUE TITLE
Question: How to do ABAC with OData.

### ISSUE THREAD

**Issue by pavinan** [OData/WebApi#2032]
Are there any docs/samples. related to securing and restricting access to data in the .Net core?

For example, I don't want to return "BillingAddress" property from an "Organisation entity" for a user with "Basic" role.

**Comment by odero** [comment]
@pavinan This might help https://docs.microsoft.com/en-us/odata/webapi/odata-security#edm-security

**Comment by gathogojr** [comment]
Hi @pavinan. Thank you for the question. OData protocol provides annotations for specifying required permissions on an entity or even single property. These can be specified using Edm library. We currently don't have any built-in support in the WebApi to automatically apply such permissions. You'd have filter the properties returned by your controller methods.
