### ISSUE TITLE
OData Request By Guid Key Not Working .NET Core 3.1

### ISSUE THREAD

**Issue by groogiam** [OData/WebApi#2037]
*Short summary (3-5 sentences) describing the issue.*
OData Get via guid key does not seem to work in ASP.NET Core

### Assemblies affected
Microsoft.AspNetCore.OData 7.3.0

### Reproduce steps

The following never resolves. It either returns 404 or an empty response. 

http://localhost:5001/odata/Schools(c911b750-ab77-4206-ad60-3d6aab4baec9)

```c#
        [HttpGet]
        [EnableQuery]
        public async Task<IActionResult> GetSchools([FromODataUri] Guid key)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var school = await _context.Schools.FindAsync(key);

            if (school == null)
            {
                return NotFound();
            }

            return Ok(school);
        }
```
### Expected result

The url above would resolve and execute the route in the code block. Note: If the type of the route above is changed to int or long the action is executed on the server.

### Actual result

404 or empty response

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by xuzhg** [comment]
@groogiam By Routing convention, `GetSchools` handles the request like `~/odata/Schools`.

If you want to query single entity, the method name should be as:

```C#
.... Get([FromODataUri]Guid key)
.... Get + TypeNameOfEntitySet([FromODataUri]Guid key)
```

So, in your scenario, change
```C#
public async Task<IActionResult> GetSchools([FromODataUri] Guid key)
```
as:

```C#
public async Task<IActionResult> Get([FromODataUri] Guid key)

public async Task<IActionResult> GetSchool([FromODataUri] Guid key)

```

Both should work fine. Please let me know any further problems.

**Comment by groogiam** [comment]
Looks like that did the trick. Thanks.

**Comment by Steinblock** [comment]
@xuzhg 

Thanks alot. I spend half a day figuring this out because I had a `Get(string id)` and a `Get()` method in my code and the `Get(string id)` was never called.

The funny thing:

If I removed the `Get()` method, my `Get(string id)` would be called.

Renaming the method instantly worked (even renaming it to `GetSchool` did the trick 🤦 

```
        [ODataRoute("{id}")]
        public async Task<IActionResult> GetCustomer([FromODataUri] string id)
        {
         
        }

        [ODataRoute]
        public IQueryable<Customer> Get()
        {
            ...
        }
```
