### ISSUE TITLE
OData adding unwanted properties in the response

### ISSUE THREAD

**Issue by sunnyverma01** [OData/WebApi#2038]
*OData adding unwanted properties in the response when using the default System.Text.Json serializer in .net core 3.1. Changing the json serializer to Newtonsoft fixes the issue*

### Assemblies affected

*AspnetCore OData WebApi lib 7.3.0*

### Reproduce Steps

I created a .net core 3.1 web api and enabled the query options on the controller actions.
Startup.cs:
--------------
Have below in the ConfigureServices() method:
services.AddOData();
services.AddControllers(options => {
                options.EnableEndpointRouting = false;
}

Have below in the Configure() method :
app.UseMvc(routeBuilder => {
                routeBuilder.EnableDependencyInjection();
                routeBuilder.Expand().Select().OrderBy().Filter();
            });

OData url: GET /api/students?$expand=students($filter=id eq '123' or id eq '124';$select=id,nickname,name)

### Expected result

*{
	"students": [
            {
                "id": "123",
                "nickname": "Bill",
                "name": "William Smith",                
            },
            {
                "id": "124",
                "nickname": "John",
                "name": "John Doe",
            }
        ]
}*

### Actual result

*{
    "instance": {
        "students": [
            {
                "id": "123",
                "nickname": "Bill",
                "name": "William Smith",                
            },
            {
                "id": "124",
                "nickname": "John",
                "name": "John Doe",
            }
        ]
    },
    "container": {},
    "modelID": "fd9f6c72-dab4-4935-b492-d03c75348a90",
    "untypedInstance": {
        "students": [
            {
                "id": "123",
                "nickname": "Bill",
                "name": "William Smith",                
            },
            {
                "id": "124",
                "nickname": "John",
                "name": "John Doe",
            }
        ]
    },
    "instanceType": null,
    "useInstanceForProperties": true
}*

**Comment by KanishManuja-MS** [comment]
@sunnyverma01 Can you use MapODataServiceRoute in UseMvc to map your ODataRoute?

**Comment by sunnyverma01** [comment]
Unfortunately, no. I'm not creating EDM Models. I've just enabled the OData query options in my web api to provide the consumers a way to filter, select the response.

**Comment by ademlabs** [comment]
I am having the same issues and need a way to fix this urgently. Using NewtonSoftJson serializer instead does fix the issue but it changes my dictionary responses with Key: xx, Value: xx items instead of key:value items. I'd rather use System.Text.Json as well. I'm not using Edm models either.

**Comment by sunnyverma01** [comment]
@KanishManuja-MS  any update on this?

**Comment by j-childers** [comment]
Also having the same problem.  We are using MapODataServiceRoute in UseMvc.

**Comment by AnastasiyaKislach** [comment]
Have you tried using AddNewtonsoftJson after AddControllers()?

**Comment by j-childers** [comment]
@AnastasiyaKislach Yes, that's what I was referring to what saying "switching everything back to Newtonsoft.Json" (along with reverting all the converters and annotations).  Would be interesting to see the OData/ODataSamples repo updated, so that there's a known-working reference to compare against.

**Comment by ademlabs** [comment]
I'm still having issues with the Odata serializer. Any dictionaries in my response is now changing to something like this (key, value properties) within an array:

        "references": [
          {
            "key": "ProductProviderId",
            "value": "30266"
          },
          {
            "key": "FulfilmentId",
            "value": "14706639"
          },
        ]

Without the Odata filtering, my responses look like this:

        "references": {
          "productProviderId": "30266",
          "fulfilmentId": "14706639"
        }

Has anyone experienced this problem? It doesn't occur when not using Newtonsoft.Json but then the filters don't work and unwanted properties are added to the response.
