### ISSUE TITLE
Decoding issues with geometries

### ISSUE THREAD

**Issue by Terriuss** [OData/WebApi#2039]
When using Geodata (for example Point from NetTopologySuite.Geometries) the JSON decoding is broken. The attribute is beeind decoded in an endless loop (see image). This happens only with odata enabled.

### Assemblies affected

OData Asp.net Core API 7.3.0
Entity Framework Core 3.1

### Reproduce steps

Create a model with a "Point" attribute, enable odata and try get the results

### Expected result

The Point attribute should be decoded as:
![image](https://user-images.githubusercontent.com/46931375/73666202-b72c4700-46a2-11ea-842e-8fbefc491f57.png)

### Actual result

It gets looped like this 
![image](https://user-images.githubusercontent.com/46931375/73666006-61f03580-46a2-11ea-8f62-c3a1adbebb8e.png)

**Comment by KanishManuja-MS** [comment]
@Shigerua Can you please provide a repro? It will help us dig deeper and find the root cause. OData uses a separate Microsoft.Spatial library to represent GeoSpatial types. If you are using other types, you may have to represent those as complex types in WebAPI OData or define some other compatible mapping.

**Comment by ufonator** [comment]
I have the same issue. Any thoughts?

**Comment by Kasper888** [comment]
I have the same issue. Any thoughts?

**Comment by xuzhg** [comment]
@Kasper888 @ufonator 

You can build the model by including the required properties.

```C#
        public static IEdmModel GetEdmModel()
        {
            var builder = new ODataModelBuilder();

            builder.EntitySet<Customer>("Customers");
            var customer = builder.EntityType<Customer>();
            customer.Property(c => c.Id);
            customer.Property(c => c.Name);
            customer.ComplexProperty(c => c.Location);
            customer.HasKey(c => c.Id);

            var point = builder.ComplexType<Point>();
            point.Property(p => p.X);
            point.Property(p => p.Y);
            point.Property(p => p.Z);
            point.Property(p => p.M);
            point.ComplexProperty(p => p.CoordinateSequence);
            point.Property(p => p.NumPoints);

            var coordinateSequence = builder.ComplexType<CoordinateSequence>();
            coordinateSequence.Property(c => c.Dimension);
            coordinateSequence.Property(c => c.Measures);
            coordinateSequence.Property(c => c.Spatial);
          //  coordinateSequence.Property(c => c.Ordinates);
            coordinateSequence.Property(c => c.HasZ);
            coordinateSequence.Property(c => c.HasM);
            coordinateSequence.Property(c => c.ZOrdinateIndex);
            coordinateSequence.Property(c => c.MOrdinateIndex);
            coordinateSequence.Property(c => c.Count);

            return builder.GetEdmModel();
        }
```

Then, I can have the following output:

![image](https://user-images.githubusercontent.com/9426627/135517777-f2fc918c-7dc1-4e0d-958e-bcff904a0ac4.png)
