### ISSUE TITLE
Batch request copies content headers to embedded requests without content

### ISSUE THREAD

**Issue by habbes** [OData/WebApi#2055]
When a batch request is received, GET and DELETE requests inside the batch get the content-type and content-length headers of the overall batch request even though they don't have content.

In general, the batch request headers are copied to the individual requests, but if an individual request inside the batch defines the same headers, then they will replace the inherited ones. Since batch requests are POST requests with a body, they always have a content-length and content-type, and since GET and DELETE requests don't have content, and therefore no content-length or content-type headers, they'll keep the inherited ones.

### Assemblies affected

OData WebAPI 7.3.0

### Reproduce steps

Create an OData WebAPI app with a basic model and convention routing. Add a controller with a `Delete(int key)` method.

Inside the method add break points so you can inspect the headers, or add the following print statements:
```c#
Console.WriteLine(ControllerContext.HttpContext.Request.Headers.ContentLength);
Console.WriteLine(ControllerContext.HttpContext.ContentType);
```

### Expected result

ContentLength and ContentType should be null.

### Actual result

ContentLength is set to the size of the entire batch request body.

ContentType is set to the content type of the batch request (e.g. `multipart/mixed; boundary=batch_e22ea856-3770-4803-b579-3cfccc999775`)

### Additional detail

[The ReadOperationInternalAsync method of the ODataBatchReaderExtensions class](https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNetCore.OData/Batch/ODataBatchReaderExtensions.cs#L141-L147) creates copies headers from an individual request in the batch to replace the headers inherited from the overall batch request, but this doesn't remove undesired headers inherited from the batch.

**Comment by mikepizzo** [comment]
CreateHttpContext in ODataBatchReaderExtensions should not copy over headers that are listed in http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_HeaderFields that don't specifically say that they are inherited. We should continue to copy headers not in this list.  Specifically, we should NOT copy over:
Content-Length
Content-Type (we *could* copy this over as the default if it is not multipart/mixed (i.e., json) but it SHOULD be specified on the individual request)
continue-on-error preference
respond-async

**Comment by habbes** [comment]
Thanks for the clarifications @mikepizzo.
When you say we _could_ copy  Content-Type as the default if it's not multipart, but it SHOULD be specified on the individual request, does that mean that I should check whether it's missing from the individual request and copy it over if it is? Or I do not copy it and assume that it is specified on the individual request.

**Comment by habbes** [comment]
@mikepizzo  Another question regarding the handling of the Prefer header. According to the spec, some of the preferences should be inherited if they are not specified in the individual requests, e.g. `allow-entityreferences` and `include-annotations`.

Assuming the overall batch request specifies a Prefer header with multiple preference tokens, including some which should be inherited, and some which should not, like:
```http
Prefer: allow-entityreferences, respond-async, include-annotations="display.*", continue-on-error
```
How should we handle such cases?
Should we strip the preferences that are not inherited from the header and just copy over the following:
```http
Prefer: allow-entityreferences, include-annotations="display.*"
```
Or should we copy over the whole thing for simplicity?

And if the individual request defines its own Prefer header, should it be merged with the inherited ones from the overall batch request or should it simply just overwrite the Prefer header from the overall batch (I assume the later is the current behaviour).

For example, assuming the overall batch request contains the following Prefer header:
```http
Prefer: allow-entityreferences, respond-async, include-annotations="display.*", continue-on-error
```
and an individual request contains the following Prefer header:
```http
Prefer: handling=lenient, wait=100
```
What should the final Prefer header for the individual request look like?
1) Individual request's Prefer header is used and the batch's Prefer header is discarded: (Current behaviour)
```http
Prefer: handling=lenient, wait=100
```
2) Non-inherited preferences are removed from the batch's header and they are combined with the individual request's preferences:
```http
Prefer: handling=lenient, wait=100, allow-entityreferences, include-annotations="display.*"
```
3) The individual request retains both its preferences and those of the batch, without any preference getting removed
```http
Prefer: handling=lenient, wait=100, allow-entityreferences, respond-async, include-annotations="display.*", continue-on-error
```

If the individual request specifies a Prefer header, I would go with option 1 because it's the simplest and reflects the current behavior. However, given that the spec specifies that preferences like `include-annotations` should be inherited if they are not defined in the individual request, it appears that option 2 is the more correct interpretation of the spec.

**Comment by mikepizzo** [comment]
Regarding Content-type; it's a good question whether we should copy the Content-Type from the overall request if not supplied on the individual request. It might be handy to avoid having to repeat on each statement, but it's not defined behavior. According to [HTTP spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7.2.1), individual requests with a content-body SHOULD specify the content-type, and there actually is defined behavior for the absence of the content-type header (the server is allowed to "guess" based on content, or default to application/octet-stream.) I would rather not have clients rely on this behavior, so I think it's fine not to copy it.

Regarding the Preference header; unfortunately 2 is the only correct behavior for handling preference headers-combine any except continue-on-error with whatever is specified on the individual request.

**Comment by habbes** [comment]
@mikepizzo I've created a draft pull request that implements option 2 for Prefer headers and that does not copy Content-Type and Content-Length.

Here's the PR: https://github.com/OData/WebApi/pull/2064

The PR still has some issues worth addressing:
-  it uses a naive comma-based splitting that does not account for escaped values, which might lead to errors when preferences have values that contain commas
- it does make any effort to deal with cases where the overall batch request contains multiple definitions of the Prefer header (which is allowed according to the spec).
