### ISSUE TITLE
Make filter work on DateTime property

### ISSUE THREAD

**Issue by xuzhg** [OData/WebApi#206]
For example, if the Birthday is a DateTime, the following filter will be fail:

?$filter=Birthday eq 2015-12-31T20:12:30Z

Reason is that: 

in `private Expression ConvertNonStandardPrimitives(Expression source)`

The following codes just return the "DateTime" expression. We should convert it to DateTimeOffset.
```
case TypeCode.DateTime:
                            convertedExpression = source;
                            break;

```

**Comment by BrentSouza** [comment]
Oh just saw this issue after commenting on #136. 
https://github.com/OData/WebApi/issues/136#issuecomment-72107283

I tried making the change your identifying above, but that introduces a CAST in the query that gets submitted to the database, e.g:

SELECT Name FROM People WHERE CAST(Birthday AS DATETIMEOFFSET) = @filterParam

This might cause issues with the query optimizer when considering partition elimination, indexing etc.  Also, the default offset SQL Server uses (0) is different from what .NET uses (local offset), which could be problematic if a user doesn't provider a filter constant with an offset.

**Comment by xuzhg** [comment]
Please check the checked-in:  073f8818cb18f6f618d6637c257f48f501aa6c4c

please re-open it if you have more concern. Thanks.
