### ISSUE TITLE
Installing Microsoft.AspNetCore.OData NuGet to a class library - dependency errors

### ISSUE THREAD

**Issue by toresenneseth** [OData/WebApi#2061]
I'm having trouble creating an ODataController in a class library. When I Add the Microsoft.AspNetCore.OData 7.3.0 NuGet package to the class library, it complains that there is a version mismatch with Microsoft.AspNetCore.Mvc.Core.

### Assemblies affected

Microsoft.AspNetCore.OData 7.3.0

### Reproduce steps

- Create a new .NET Core 3.1 Web Application and Class library.
- Add NuGet Microsoft.AspnetCore.OData 7.3.0 to the Class library.
- Create a Controller that inherits from ODataController. This requires / prompts you to install Microsoft.AspNetCore.Mvc.Core (2.2.5).
- Install package Microsoft.AspNetCore.Mvc.Core to the class library
- You get the error shown below:

### Expected result

I would expect that the required dependencies were installed, so that I could create an ODataController i a class library.

### Actual result

```
Assembly 'Microsoft.AspNetCore.OData' with identity 'Microsoft.AspNetCore.OData, Version=7.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.AspNetCore.Mvc.Core' with identity 'Microsoft.AspNetCore.Mvc.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

### Additional detail

What I need to do to make this work in a class library, is to add a FrameworkReference to **Microsoft.AspNetCore.App** to the .csproj-file.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="7.3.0" />   
    <FrameworkReference Include="Microsoft.AspNetCore.App" /> 
  </ItemGroup>
  
</Project>

```
Is this the intended behavior, or am I using the wrong NuGet package in the class library?

-Thanks

**Comment by habbes** [comment]
@toresenneseth Thank you for submitting the issue. When you added a FrameworkReference to **Microsoft.AspNetCore.App**, were you still prompted to install Microsoft.AspNetCore.Mvc.Core (2.2.5)? Or did it work with you having to manually install Microsoft.AspNetCore.Mvc.Core?

**Comment by toresenneseth** [comment]
I didn't have to install Microsoft.AspNet.Mvc.Core. I just had to add the FrameworkReference, and it worked.

**Comment by habbes** [comment]
Hi @toresenneseth according to [this guide](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-3.1&tabs=visual-studio), class libraries using the `Microsoft.NET.Sdk` and using ASP.NET Core APIs should add a framework reference to `Microsoft.AspNetCore.App`. So I believe what you experienced was intended behaviour.
