### ISSUE TITLE
"A request container already exists on the request" exception for batch requests 

### ISSUE THREAD

**Issue by ud09** [OData/WebApi#2068]
When I used `v7.3.0,` I got the error at https://github.com/OData/WebApi/issues/2009  when the response is returning
Then I tried the latest nightly build `7.4.0-nightly202002252317` that seems to include a fix for that.
Now I get the below error when the request is coming:
 **!!! No errors if I don't use endpoint routing !!!**
```
System.Exception
  HResult=0x80131500
  Message=System.InvalidOperationException: A request container already exists on the request.
   at Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.CreateRequestContainer(HttpRequest request, String routeName)
   at Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ParseBatchRequestsAsync(HttpContext context)
   at Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ProcessBatchAsync(HttpContext context, RequestDelegate nextHandler)
   at Microsoft.AspNet.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
HEADERS
```http
Content-Type: multipart/mixed; boundary=batch_7f5b7766-597d-4546-bc0a-f214f9a4ca69
Host: localhost:9802
Content-Length: 700
session-guid: 7a90b3bb-664e-4285-b0dc-c3d9065a7ed2
OData-Version: 4.0
```
### Assemblies affected
`microsoft.aspnetcore.odata  7.4.0-nightly202002252317`

### Reproduce steps
My startup configuration is 
```csharp

	if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
	}

	app.UseRouting();

	app.UseAuthentication();

	app.UseAuthorization();

	app.UseODataBatching();

	app.UseEndpoints(endpoints =>
	{
		endpoints.Select().Expand().Filter().OrderBy().MaxTop(100).Count();
		endpoints.MapODataRoute("odata", "", GetEdmModel(), new DefaultODataBatchHandler());
	});
```

**Comment by marabooy** [comment]
@ud09 The support for endpoint routing is going to be part of the beta release scheduled for this week.

**Comment by ud09** [comment]
Added UseODataBatching before UseRouting.  

    app.UseODataBatching();
    app.UseRouting();
    app.UseAuthentication();
    app.UseAuthorization();
    app.UseEndpoints(endpoints =>
    {
        endpoints.Select().Expand().Filter().OrderBy().MaxTop(100).Count();
        endpoints.MapODataRoute("odata", null, GetEdmModel(), new DefaultODataBatchHandler());
    });

Now I got the following error with endpoint routing with the 7.4.0-beta.
No errors if I don't use endpoint routing. 

    System.NullReferenceException
    Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Routing.UrlHelper.GetVirtualPathData(string routeName, Microsoft.AspNetCore.Routing.RouteValueDictionary values) Line 94	C#
    Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Routing.UrlHelper.RouteUrl(Microsoft.AspNetCore.Mvc.Routing.UrlRouteContext routeContext) Line 76	C#
    Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Routing.UrlHelperBase.Link(string routeName, object values) Line 111	C#
    Microsoft.AspNetCore.OData.dll!Microsoft.AspNet.OData.Batch.ODataBatchHttpRequestExtensions.GetODataBatchBaseUri(Microsoft.AspNetCore.Http.HttpRequest request, string oDataRouteName, Microsoft.AspNetCore.Routing.IRouter route)	Unknown
    Microsoft.AspNetCore.OData.dll!Microsoft.AspNet.OData.Batch.ODataBatchHandler.GetBaseUri(Microsoft.AspNetCore.Http.HttpRequest request)	Unknown
    Microsoft.AspNetCore.OData.dll!Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ParseBatchRequestsAsync(Microsoft.AspNetCore.Http.HttpContext context)	Unknown
    Microsoft.AspNetCore.OData.dll!Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ProcessBatchAsync(Microsoft.AspNetCore.Http.HttpContext context, Microsoft.AspNetCore.Http.RequestDelegate nextHandler)	Unknown
    Microsoft.AspNetCore.OData.dll!Microsoft.AspNet.OData.Batch.ODataBatchMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext context)	Unknown
    Microsoft.AspNetCore.Hosting.dll!Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Microsoft.AspNetCore.Hosting.HostingApplication.Context context) Line 87	C#

**Comment by xuzhg** [comment]
@ud09 Are you using the original 7.4.beta nightly or 7.4.beta Nuget? 

I think the lastest [7.4.beta Nuget](https://www.nuget.org/packages/Microsoft.AspNetCore.OData/7.4.0-beta) fixed that problem. Can you try it and let me know the result? Thanks.

**Comment by ud09** [comment]
Both beta and nightly build throw this exception.

**Comment by xuzhg** [comment]
@ud09 can you share me your rep?

**Comment by ud09** [comment]
I will try to create a sample that reproduces the issue tomorrow. Thank you.

**Comment by ud09** [comment]
Sorry it was my fault. Another library also had a reference to the nightly build. Now it works with all referencing the beta build. Thanks again.

**Comment by xuzhg** [comment]
@ud09 Glad to hear that. Please try more and feel free to file issues for new concerns. Thanks.
