### ISSUE TITLE
BATCH request in odata v4 service is not returning the CR as specified in RFC2046

### ISSUE THREAD

**Issue by siasty** [OData/WebApi#2073]
Hi, i have problem with odata service .I created a simple application where I use batch request

When checking in _Batch, function _deserializeBatchResponse I observe that the first boundary is not detected. This is because the CR (ASCII 13, \r) is missing.

Has anyone had such a problem or can tell me why my service is not returning the CR as specified in RFC2046?

the app is at https://demo.hgs3.pl [ login Admin/Th9S38vk@@ ]

Best Regarrds 
Maciej

**Comment by siasty** [comment]
Hi, has anyone found any solution?

I wrote to the authors of the sapui5 solution, they also found the same error 
https://github.com/SAP/openui5/issues/2830#issuecomment-593406590

new link for odataV4 http://51.68.141.73:5000/odata/

**Comment by siasty** [comment]
Hi,
I found what the problem is. 
When i run odate on linux respond has POSIX style \n, when run on windows is windows style \r\n.

**Comment by marabooy** [comment]
@siasty & @xuzhg this should be solved once the new OData library is released as the message writer got fixed in https://github.com/OData/odata.net/pull/1844.

**Comment by siasty** [comment]
Hi, I update app to new library but i have problem with batch request.
when i test bacht request  - responde has no found but when check request has link respond is found. 
![odata](https://user-images.githubusercontent.com/39690589/96848247-794f9880-1454-11eb-97eb-bbb8354113fd.png)
can you tell me what's wrong?

**Comment by marabooy** [comment]
Hi @siasty thanks for testing out the preview. From your startup you seem to be missing this call. Do let me know if this fixes the issue.
```
 app.UseODataBatching(); // call before "UseRouting"
    app.UseRouting();
```

**Comment by siasty** [comment]
I did as suggested but there is no result

**Comment by siasty** [comment]
Thank you for your help, new ODL 7.7.3 releases solved the problem
