### ISSUE TITLE
$count without =true value returns 404.

### ISSUE THREAD

**Issue by cdarrigo** [OData/WebApi#2091]
http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc31360944
states the ODATA api supports a $count operation without specifying a value. 
(e.g.  products/$count vs products/$count=true).

The current implementation requires the =true value to be appended to the query string, violating the Odata specification . 

### Assemblies affected

Microsoft.ASPNetCore.Odata 7.3.0
### Reproduce steps

Configure an asp.net core site for Odata, and issue a call to an exposed odata endpoint, specifying $count with no arguments. 

GET products?$count

### Expected result
```
{
"@odata.context": "...",
"@odata.count": 0,
"value": []
}
```

### Actual result

```
{
"error": {
"code": "",
"message": "The query specified in the URI is not valid. The value for OData query '$count' cannot be empty.",
"details": [],
"innererror": {
"message": "The value for OData query '$count' cannot be empty.",
"type": "Microsoft.OData.ODataException",
"stacktrace": "   at Microsoft.AspNet.OData.Query.ODataQueryOptions.ThrowIfEmpty(String queryValue, String queryName)\r\n   at Microsoft.AspNet.OData.Query.ODataQueryOptions.BuildQueryOptions(IDictionary`2 queryParameters)\r\n   at Microsoft.AspNet.OData.Query.ODataQueryOptions.Initialize(ODataQueryContext context)\r\n   at Microsoft.AspNet.OData.Query.ODataQueryOptions..ctor(ODataQueryContext context, HttpRequest request)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.CreateAndValidateQueryOptions(HttpRequest request, ODataQueryContext queryContext)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.<>c__DisplayClass1_0.<OnActionExecuted>b__1(ODataQueryContext queryContext)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)"
}
}
}
```
### Additional detail

The BuildQueryOptions method should not be performing a thowIfEmpty check on the count argument.

**Comment by mikepizzo** [comment]
@cdarrigo -- thanks for the report and following on with a contribution! 

I think there is confusion around what is/is not supported per protocol.

According to protocol, the $count query option, which includes the count along with the results, requires the boolean. See "inlinecount" in http://docs.oasis-open.org/odata/odata/v4.01/cos01/abnf/odata-abnf-construction-rules.txt:
            inlinecount = ( "$count" / "count" ) EQ booleanValue

I believe the confusion comes around the fact that $count is also used as a path segment, to say that the count of a collection is returned instead of the members of the collection. In this case, there is no boolean. See "count" which is used exclusively in path segments:
            count = '/$count'

**Comment by habbes** [comment]
@cdarrigo Thank you for the contribution. Closing this issue because the current implementation is correct with respect to the protocol, as explained in the comment above. Please let us know if the explanation is not clear.
