### ISSUE TITLE
API randomly throws HTTP 400, when using two not nested any() 

### ISSUE THREAD

**Issue by gkalchev93** [OData/WebApi#2095]
HTTP 400 errors when using two not nested any() in concurrent requests.
We are using the latest version of OData and we know about this issue:
https://github.com/OData/WebApi/issues/1083
But I think our case is kind different, because we also don't have problems with one any(). 
But when we add the second one sometimes the API returns 400 with this message: 
_The Any/All nesting limit of '1' has been exceeded_
This exception is thrown by the _FilterQueryValidator_ in _EnterLambda_ method:
![image](https://user-images.githubusercontent.com/19348405/77168865-3a71f280-6ac1-11ea-9c39-bd78677b0d06.png)

### Assemblies affected
https://www.nuget.org/packages/Microsoft.AspNet.OData/7.3.0

Even latest code version 7.4.0 (built by me for the test).

### Reproduce steps
Just use the sample query to fire big count of asynchronous calls (100 always throws the error) :
http://localhost/webapi/orders/SalesOrders?$filter=DocumentType eq 'invoice' and Items/any(d: d/SendDate ge 2019-12-04T06:05:15Z and d/SendDate le 2019-12-05T06:05:15Z) and Client/Id in ('123') and Address/City/PostCode in ('9000') and Address/City/Name in ('New York') and Address/Country in ('US') and Address/Streen/Number in ('032')&$expand=Items($filter=Address/Cleints/any(c: c/Id in ('123')) and SendDate ge 2019-12-04T06:05:15Z and SendDate le 2019-12-05T06:05:15Z; $expand=Address($expand=Clients), Invoice($expand=Ticket)), Client, Address($expand=City,Country)
### Expected result

Expected result is always 200

### Actual result

Sometimes the API returns 400 with "_The Any/All nesting limit of '1' has been exceeded_".

### Additional detail

On the screenshot you can see that the value of _currentAnyAllExpressionDepth is 0.
I also insert a line which logs the value of that variable in the debug console to prevent any messing from the threads:

odata: _currentAnyAllExpressionDepth = 0
odata: _currentAnyAllExpressionDepth = 0
odata: _currentAnyAllExpressionDepth = 0
odata: _currentAnyAllExpressionDepth = 0
odata: _currentAnyAllExpressionDepth = 0
odata: _currentAnyAllExpressionDepth = 0
odata: _currentAnyAllExpressionDepth = 0
odata: _currentAnyAllExpressionDepth = 0
odata: _currentAnyAllExpressionDepth = 0
odata: _currentAnyAllExpressionDepth = 0
odata: _currentAnyAllExpressionDepth = 0
odata: _currentAnyAllExpressionDepth = 0
The Any/All nesting limit of '1' has been exceeded. 'MaxAnyAllExpressionDepth' can be configured on ODataQuerySettings or EnableQueryAttribute.

**Comment by KanishManuja-MS** [comment]
@gkalchev93 Can you please provide us with a link to a repro? We have not been able to reproduce it as we don't see concurrent calls being made for two any. A sample repro should help accelerate this.

**Comment by gkalchev93** [comment]
@KanishManuja-MS 
Hello, I am not able to share you a link to repro. 
The code is a part of enterprise application. 
Is it possible to try reproduce it on something like public API? 
If Yes can you share one, which is fine for you?

**Comment by chrisspre** [comment]
Hello Georgi, we are unable to reproduce the behavior and have not seen it before. The code doesn't seem to indicate that the validation logic is called concurrently, so I have no clue how this count can become mangled. In absence of a way to reproduce can you please share how you are making the  100 asynchronous calls? Would you also have the time to try the latest release please.

**Comment by gkalchev93** [comment]
Hello Chriss,
this is the test code:
`var tasks = Enumerable.Range(0, 50).Select(_ => Task.Run(GetOrders));
Task.WhenAll(tasks).Wait();`

Currently we are using Version: "7.6.3.0".
Thanks!

**Comment by chrisspre** [comment]
Hello, what is the GetOrders method?
Is that the actual method on the controller reusing the same controller for each call? Or is this a wrapper arround the http call ?
The way the library is designed, the query validation is not thread safe. This is typically not a problem since a new instance of the controller (including the validation) is created per http call.

**Comment by chrisspre** [comment]
Gentle ping. @gkalchev93
Can you please clarify how this calling the controller code directly (e.g. from a test) or is this going through an HTTP call ?
