### ISSUE TITLE
OData not working completely

### ISSUE THREAD

**Issue by fairking** [OData/WebApi#2096]
I am trying to setup a simple sample but all failed. This Asp.Net Core Odata is totally mess.
For example (very simple, no crazy magic):
```
services.AddOData();
app.UseEndpoints(endpoints =>
{
    endpoints.EnableDependencyInjection();
    endpoints.Expand().Select().Count().OrderBy().Filter().MaxTop(100);
    endpoints.MapODataRoute("odata", null, GetEdmModel());
});
```
if I go to 'http://localhost:5001/odata/weatherforecast' I got my data, fine.
if I go to 'http://localhost:5001/odata/weatherforecast?$select=key,summary' it returns this `[{"instance":null,"container":{},"modelID":"d5389bf8-1e44-43a4-8ab6-f0aed65a2231","untypedInstance":null,"instanceType":null,"useInstanceForProperties":false}, .... ]`
if I go to 'http://localhost:5001/odata/$metadata' I got 404.

How can I get a metadata guys? Searched whole www didn't find anything.

### Assemblies affected

Microsoft.AspNetCore.OData 7.4.0-beta [link](https://www.nuget.org/packages/Microsoft.AspNetCore.OData/7.4.0-beta)

### Reproduce steps

Example: https://github.com/fairking/ODataTest

### Expected result

$metadata should return a schema

### Actual result

404 response

**Comment by xuzhg** [comment]
@fairking Thanks for trying OData. 

However, I can't agree with your title. OData has been working for almost decades ( 😄  ) and it's widely used in a bunch of products. I agree that our library has some issues and feature gap. We are trying our best to improve our libraries to help more customers to achieve more. Any issues or feature requests are welcome.

For your issues, if you have read a little bit from our [docs](https://docs.microsoft.com/en-us/odata/)/[blogs](https://devblogs.microsoft.com/odata), you maybe find the root cause. 

`endpoints.MapODataRoute("odata", null, GetEdmModel());` 

the first argument is the route name, the second is the route prefix. 
route name is used for internal tracking the route. route prefix is used to match the request uri. 

for your request uri, "'http://localhost:5001/odata/$metadata`, there's no route match. So, you got 404, that's the expected, correct response. Because there's no route prefixed with "odata".

Try the request like
`http://localhost:5001/$metadata`, you can get: 
```xml
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="ODataTest" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityType Name="WeatherForecast">
                <Key>
                    <PropertyRef Name="key" />
                </Key>
                <Property Name="key" Type="Edm.String" Nullable="false" />
                <Property Name="date" Type="Edm.DateTimeOffset" Nullable="false" />
                <Property Name="temperatureC" Type="Edm.Int32" Nullable="false" />
                <Property Name="summary" Type="Edm.String" />
            </EntityType>
        </Schema>
        <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityContainer Name="Container">
                <EntitySet Name="WeatherForecast" EntityType="ODataTest.WeatherForecast" />
            </EntityContainer>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>
```

try the request:  http://localhost:5000/WeatherForecast

```json
{
    "@odata.context": "http://localhost:5000/$metadata#WeatherForecast",
    "value": [
        {
            "key": "dcaba7d2045c4f2ba75e155b7e6aa637",
            "date": "2020-03-21T13:05:52.0940512-07:00",
            "temperatureC": 54,
            "summary": "Bracing"
        },
        {
            "key": "dfb1474972f74882aa5d8fb5051bbf85",
            "date": "2020-03-22T13:05:52.0950345-07:00",
            "temperatureC": 30,
            "summary": "Balmy"
        },
        {
            "key": "1f6098824fd3409b870ef7465b13499f",
            "date": "2020-03-23T13:05:52.095164-07:00",
            "temperatureC": 54,
            "summary": "Bracing"
        },
        {
            "key": "9b04b20362734380b2564404b5aac91e",
            "date": "2020-03-24T13:05:52.095275-07:00",
            "temperatureC": 17,
            "summary": "Cool"
        },
        {
            "key": "1d12156fbdcb41bba2056a25a8c24937",
            "date": "2020-03-25T13:05:52.095356-07:00",
            "temperatureC": 32,
            "summary": "Warm"
        }
    ]
}
```

Any other concerns, please file new issues or just leave comments here. I'd like to help you. Thanks.

**Comment by fairking** [comment]
Ok, looks like it shows me the entity models. But why the `$metadata` doesn't show my controllers/actions? How the client would know what actions could be called?

regarding all those routes it must be simplified like:
```
services.AddOData();
app.UseOData(); // Optional: app.UseOData(options)
```
otherwise people will find it hard to use and understand.

**Comment by fairking** [comment]
Again in my other project, I tried add the same lines and it works in different way, have no idea why???
The url 'http://localhost:8050/odata/Tickets' gives data.
The url 'http://localhost:8050/odata/$metadata' gives 404.
The url 'http://localhost:8050/odata/' gives the scheme (that what $metadata' must give).

It the any way to check how all those routes work? Like some kind of tracer or debugger? It must register a standard route 'odata' with no issues in any instance.

**Comment by xuzhg** [comment]
1) $metadata only shows the schema data of your service, for the controller and action, you may need Swagger/openAPI.  you can see sample example in https://github.com/microsoft/aspnet-api-versioning to get started.

2) UseOData() pattern? Yes, we took it consideration. So far, we don't have good design for it. Maybe you can share more.

3) The others request similar "http://localhost:8050/odata/Tickets" can work because you has the attribute routing on your controller. [Route(....)]. Asp.NET Core will match that route if no others matched before.

4) odata/$metadata gives 404, because there's no route match.

5)  'http://localhost:8050/' gives your service document, meanwhile "'http://localhost:8050/$metadata" gives your the metadata. There's no magic. Because Our library provides the default "metadata controller". 

6) We don't have route tracer or debugger. However, i think you can create your "middleware" and register it into the pipeline to track the routing.

Hope it can help you.

**Comment by fairking** [comment]
And regarding:

> if I go to 'http://localhost:5001/odata/weatherforecast?$select=key,summary' it returns this [{"instance":null,"container":{},"modelID":"d5389bf8-1e44-43a4-8ab6-f0aed65a2231","untypedInstance":null,"instanceType":null,"useInstanceForProperties":false}, .... ]

Why does the odata module returns some scheme instead of actual data?
I expect something like this:
```
[
{ key: '1', summary: 'bla-bla' },
{ key: '2', summary: 'bla-bla' },
...
]
```

**Comment by xuzhg** [comment]
It works fine at my side:

![image](https://user-images.githubusercontent.com/9426627/77210698-e108c400-6abe-11ea-9376-d2abb6862e26.png)

Consider to remove "EnableDependencyInject" for non-OData route query. 

Below is my change to your codes:

![image](https://user-images.githubusercontent.com/9426627/77210797-16adad00-6abf-11ea-8f7d-4ec60d5c1b37.png)

**Comment by fairking** [comment]
I cannot understand everything :-(
1. I fixed `builder.EntitySet<WeatherForecast>("WeatherForecast");` however I cannot understand why it is important and why it should fix the issue?
2. I tried to remove `endpoints.EnableDependencyInjection();` and the app doesn't run but throws the following error:
```
InvalidOperationException: Cannot find the services container for the non-OData route. This can occur when using OData components on the non-OData route and is usually a configuration issue. Call EnableDependencyInjection() to enable OData components on non-OData routes. This may also occur when a request was mistakenly handled by the ASP.NET Core routing layer instead of the OData routing layer, for instance the URL does not include the OData route prefix configured via a call to MapODataServiceRoute().
```

Will all those attempts to fix it I cannot get `$select` working.
![image](https://user-images.githubusercontent.com/13495631/77230624-68bd0400-6b8d-11ea-95f7-33832b71cb8b.png)

Making OData work is so confusing and complicated.

**Comment by fairking** [comment]
@xuzhg 

> I fixed builder.EntitySet<WeatherForecast>("WeatherForecast"); however I cannot understand why it is important and why it should fix the issue?

Ok, I have just found that the "WeatherForecast" is actually a controller name. Please add it to the documentation as I was confusing with it:
![image](https://user-images.githubusercontent.com/13495631/77345746-fd119d00-6d2c-11ea-92f2-52d840a93c45.png)

**Comment by xuzhg** [comment]
@fairking That information is documented at: https://docs.microsoft.com/en-us/odata/webapi/built-in-routing-conventions
And from this page or others, you can learn all the convention routing.

Register the EdmModel form controller? Yes. You can use the non-Edm model pattern, or non-OData route pattern. Please refer to this blog for more information: https://devblogs.microsoft.com/odata/supercharging-asp-net-core-api-with-odata/

Thanks.

**Comment by fairking** [comment]
Thank you @xuzhg for all your replies. Every example and every doc is very useful to me. I still got some issues with setting up the routes but I will look at examples and read more docs before I ask any new questions here. The issue in this topic was with setting up very simple example which I finally managed to fix. (https://github.com/fairking/ODataTest)

I think there are few things which need to be fixed or provided a better explanation for users.
1. I was confused with the relation between EntitySet and controller/action. I could not understand what is the `WeatherData` for in `builder.EntitySet<WeatherForecast>("WeatherData")`.
2. I think all those methods against `endpoints` must go into the options and there must be only one method `UseOData(options)` against application builder.
3. Better explanation for beginners about: How to add metadata to any contoller/action. Lets say my route is `endpoints.MapControllerRoute(name: "api", pattern: "Api/{service}/{operation}/{id?}", defaults: new { controller = "MyApi", action = "Default" })` and eg. Url: `http://localhost/api/Core/Contacts/`. The question how to add metadata to that route.

Closing the issue. Thanks again for all your help @xuzhg .

**Comment by xuzhg** [comment]
Welcome. What you have mentioned is related to the "CONVENTION".

OData is conventional, which means it depends/acts/runs on a certain of conventions. 
With convention, you don't need to set any configurations/metadatas/constraints, etc. especially for the routing/Uri convention.

I'd suggest your to refer to: https://www.odata.org/documentation/ for OData spec.
Especially for this doc: http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html

Feel free to file any issues if you have any concerns/questions. Thanks.

**Comment by hsinyu-chen** [comment]
@fairking  if you use `net core 3.1` ,you may need AddNewtonsoftJson() for odata 

[https://stackoverflow.com/questions/59381408/odata-on-net-core-doesnt-return-the-right-results-on-select?answertab=votes#tab-top](https://stackoverflow.com/questions/59381408/odata-on-net-core-doesnt-return-the-right-results-on-select?answertab=votes#tab-top)

**Comment by fairking** [comment]
@hsinyu-chen Yeah. I knew it as my NHibernate IQueriable wasn't working without `AddNewtonsoftJson()`. Ones more many thanks for you guys.
https://github.com/nhibernate/nhibernate-core/issues/2334#issuecomment-606111593
