### ISSUE TITLE
ODataConventionModelBuilder doesn't know about nested CLR types and generates ambiguous names for the counterpart Entity Types

### ISSUE THREAD

**Issue by nkamensky** [OData/WebApi#2097]
Full runtime name of the nested CLR type looks like:
**some.example.namespace.RootType+Level1Type+Level2Type+Level3Type**

For the Entity Type backed by such CLR type _ODataConventionModelBuilder_ generates bogus full name:
**some.example.namespace.Level3Type**

### Assemblies affected

Microsoft.AspNetCore.OData 7.4.0-beta

### Reproduce steps

1. Create _ODataConventionModelBuilder_
2. Call _AddEntityType()_ with some nested type as argument

### Expected result

Nested CLR types should be supported without any additional efforts from the OData WebApi users.

### Actual result

Nested CLR types can't be used freely with OData WebApi.

**Comment by habbes** [comment]
@nkamensky just to check whether I understand the issue, you mean that if you have a class like
```c#
public class RootType
{
   public class Level1Type
   {
      public class Level2Type
      {
          public class Level3Type
          {
                public int Id { get; set; }
          }
       }
   }
}
```
And you add the `RootType.Level1Type.Level2Type.Level3Type` class to the model, then the name generated in the model will be `some.example.namespace.Level3Type`?

And is there any other side effect or unexpected behavior that you observed besides the naming? Was the EntityType generated in the model correct in terms of the properties, references to it from other functions, related entities, etc.?

**Comment by habbes** [comment]
@nkamensky OData does not define a concept of nested types. We need to develop a mapping between CLR nested types and OData.

**Comment by chrisspre** [comment]
If that leads to a naming conflict for example in this case

```
    public class Bar
    {
    }

    public class Foo
    {
        public class Bar
        {
        }
    }
```
One can explicitly create a "sub"-namespace
```
    var x = builder.EntityType<Bar>();
    var y = builder.EntityType<Foo>();
    var z = builder.EntityType<Foo.Bar>();
    z.Namespace = "Foo";
```

**Comment by nkamensky** [comment]
@habbes 

> And you add the `RootType.Level1Type.Level2Type.Level3Type` class to the model, then the name generated in the model will be `some.example.namespace.Level3Type`?

Yes.

> And is there any other side effect or unexpected behavior that you observed besides the naming?

My code already triggers the name collisions. So I don't dig further.

**Comment by nkamensky** [comment]
If "path" types are generics, then name became even more grotesque.

**Comment by nkamensky** [comment]
> In the mean time, you could try to set the namespace manually after creating the entity type using the fluent API.

For some cases this is a workaround. Looks like model builder uses **Type** as key and the references are resolved correctly.

**Comment by KenitoInc** [comment]
@nkamensky 
Workaround provided.
Closing this issue. Feel free to open a new issue.

**Comment by jimbromley-avanade** [comment]
@KenitoInc I feel this closure was pre-mature. While I could see the argument for this maybe not being a bug; the exception messaging needs to be improved. In my testing this is thrown at EdmLibraryExtensions.cs line 1591 when type is Edm.AmbiguousType. 

I'd advocate for at minimum clearer messaging of the error indicating both that the type is ambiguous and what underlying type is causing the issue.

**Comment by KenitoInc** [comment]
Kindly create a new issue @jimbromley-avanade
