### ISSUE TITLE
Make function/action parameter and return type as Nullable

### ISSUE THREAD

**Issue by xuzhg** [OData/WebApi#210]
### a) Return Type

__12.3.2 Attribute Nullable__

A return type MAY specify a Boolean value for the Nullable attribute. If not specified, the Nullable attribute defaults to true.

If the return type has a Type attribute that does not specify a collection, the value of true means that the action or function may return a single null value. A value of false means that the action or function will never return a null value and instead fail with an error response if it cannot compute a result. 

If the return type has a Type attribute that specifies a collection, the result will always exist, but the collection MAY be empty. In this case, the Nullable attribute applies to members of the collection and specifies whether the collection can contain null values. 

### b) Parameter Type

__12.4.3 Attribute Nullable__

A parameter whose Type attribute does not specify a collection MAY specify a Boolean value for the Nullable attribute. If not specified, the Nullable attribute defaults to true.

The value of true means that the parameter accepts a null value.

===================================================================
So, I would like to make the parameter 'p3' nullable and the return type as nullable.
 Currently, there is no api on the ActionConfiguration/FunctionConfiguration which can make it
 Optional or Nullable. 

```C#
var actionConfig = vehicle.Action("TestAction1").Returns<string>;
 actionConfig.Parameter<string>("p1");
 actionConfig.Parameter<string>("p2");
 actionConfig.Parameter<string>("p3"); 
```

**Comment by nickkin-msft** [comment]
This is not supported by the client
