### ISSUE TITLE
No attribute to allow us to get OData to ignore certain properties which leads to Ambiguous match found

### ISSUE THREAD

**Issue by burrowj** [OData/WebApi#2100]
OData seems unable to allow for a user to create entity classes in which a child class hides a parent property of one type and creates a new one of a different type.  This may not be a common issue I understand, but it would be nice to have the ability. If we could be given an attribute to use so that OData would ignore the hidden property during reflection that would be great.

For instance in TypedEdmStructuredObject.CreatePropertyGetter the line

PropertyInfo property = type.GetProperty(propertyName);

could exclude properties with this attribute

also the reflection in

Microsoft.AspNet.OData.Query.Expressions.SelectExpandBinder.CreatePropertyValueExpression
could be made to ignore properties with this attribute

### Assemblies affected

Microsoft.AspNet.OData 7.3.0

### Reproduce steps

Create a base class A with property Id of type object
Create a class B which inherits A and hides property Id with Id of type Guid

We now have two properties of the same name

When we try serializing this class in a controller result or allow the "select" option with the controller on this class we get "Ambiguous match found" because there are two properties of the same name.

### Expected result

The child class property to be exposed only

### Actual result

child and parent property exposed giving rise to Ambiguous

**Comment by NetTecture** [comment]
Ah, have you tried the sstandard NotMapped attribute? I am using this to suppress odata from seeing attributes I am not using on the odata layer.

**Comment by burrowj** [comment]
Thanks but unfortunately that doesn't work in this scenario

**Comment by burrowj** [comment]
Don't get me wrong though.  I'd be very happy to use that attribute and then have the code changed for example in  TypedEdmStructuredObject.CreatePropertyGetter
From
PropertyInfo property = type.GetProperty(propertyName);
To something like
                type.GetProperties()
                    .Where(property => property.Name==propertyName && property.GetCustomAttribute(typeof(NotMappedAttribute)) == null).FirstOrDefault();

**Comment by burrowj** [comment]
or IgnoreDataMemberAttribute  or both

**Comment by KenitoInc** [comment]
@burrowj Why doesn't `NotMapped` attribute work for you?
Which scenario are you dealing with
1. The property is omitted from the base odata type
2. The property is present in the base odata type but overridden in the derived odata type

**Comment by burrowj** [comment]
The situation that I would like to work is by putting something like [NotMapped] in the Id property of the base type and still allow the derived Id field to come through.  Hence I'm not hiding a property completely from serialization.  Simply obscuring the base type property so that it doesn't cause issues in the class methods mentioned in the description of this issue above.  Namely

TypedEdmStructuredObject.CreatePropertyGetter
Microsoft.AspNet.OData.Query.Expressions.SelectExpandBinder.CreatePropertyValueExpression

I assume there would be matching methods in the deserialization process

**Comment by burrowj** [comment]
Sorry I mean TypedEdmStructuredObject.CreatePropertyGetter in terms of deserialization process.  
Microsoft.AspNet.OData.Query.Expressions.SelectExpandBinder.CreatePropertyValueExpression causes an issue on the query process if i choose to use the "$select" option

**Comment by bdebaere** [comment]
@burrowj I think you are out of luck with this one. This is the behavior of System.Reflection. The issue lies in Type.GetProperties() returning multiple PropertyInfo objects. As is evident by the code below. The only way OData could fix your problem is if TypedEdmStructuredObject.CreatePropertyGetter would modify its GetProperty call to use BindingFlags.DeclaredOnly, which would of course break everyone's code who is using inheritance properly.

```csharp 
void Main()
{
	var type = typeof(Product);
	
	Console.WriteLine("No BindingFlags:");
	foreach(var property in type.GetProperties())
	{
		Console.WriteLine($"{property.PropertyType} {property.Name}");
	}
	
	Console.WriteLine("\nBindingFlags.Instance | BindingFlags.Public:");
	foreach(var property in type.GetProperties(BindingFlags.Instance | BindingFlags.Public))
	{
		Console.WriteLine($"{property.PropertyType} {property.Name}");
	}
	
	Console.WriteLine("\nBindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public:");
	foreach(var property in type.GetProperties(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public))
	{
		Console.WriteLine($"{property.PropertyType} {property.Name}");
	}
}

public class BaseType
{
    public object Id { get; set; }
}

public class Product : BaseType
{
    public new int Id { get; set; }
}
```

I think you should really question why your C# class design is having a base type with an object property, that you overwrite with a different type in an inheriting class. This feels very wrong to me. I would suggest you either create multiple base classes or create a generic base class, see the code below.

```csharp
void Main()
{
	var type = typeof(Product);
	
	Console.WriteLine("No BindingFlags:");
	foreach(var property in type.GetProperties())
	{
		Console.WriteLine($"{property.PropertyType} {property.Name}");
	}
	
	Console.WriteLine("\nBindingFlags.Instance | BindingFlags.Public:");
	foreach(var property in type.GetProperties(BindingFlags.Instance | BindingFlags.Public))
	{
		Console.WriteLine($"{property.PropertyType} {property.Name}");
	}
	
	Console.WriteLine("\nBindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public:");
	foreach(var property in type.GetProperties(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public))
	{
		Console.WriteLine($"{property.PropertyType} {property.Name}");
	}
}

public class BaseType<T>
{
    public T Id { get; set; }
}

public class Product : BaseType<int>
{
}
```

**Comment by burrowj** [comment]
bdebaere thanks for your feedback and your generics suggestion.  My orig suggestion was to use a new attribute to solve the problem which would then make the functionality optional without breaking existing code.

**Comment by bdebaere** [comment]
@burrowj I understand your original suggestion. But sometimes you have to ask yourself: "if this is not supported by the language I am coding in, am I really going in the right direction here?". And I believe this is such a case. You are asking something of the C# language for which it was not designed.
It can definitely be solved via a custom attribute, but it can just as easily be solved with different classes or generics, which is already supported by C#. Supporting this brings no advantage for OData.

**Comment by KenitoInc** [comment]
Closing this due to no response.
