### ISSUE TITLE
Support MaxLength,Precision,Scale .. for parameter

### ISSUE THREAD

**Issue by xuzhg** [OData/WebApi#211]
From the schema, there seem to be other attributes like "MaxLength",
 "Precision", "Scale" etc. that can be provided for FunctionImport's
 parameters: 

``` xml
<xs:attribute name="Name" type="edm:TSimpleIdentifier" use="required" />
<xs:attribute name="Type" type="edm:TFunctionImportParameterAndReturnType" use="required" />
<xs:attribute name="Mode" type="edm:TParameterMode" use="optional" />
<xs:attribute name="Nullable" type="xs:boolean" use="optional" />
<xs:attribute name="MaxLength" type="edm:TMaxLengthFacet" use="optional" />
<xs:attribute name="Precision" type="edm:TPrecisionFacet" use="optional" />
<xs:attribute name="Scale" type="edm:TScaleFacet" use="optional" />
<xs:attribute name="SRID" type="edm:TSridFacet" use="optional" />
<xs:anyAttribute namespace="##other" processContents="lax" />
```

Please investigate to add this functionality.

**Comment by escape-llc** [comment]
This also applies to Structural Properties in Entity Types!  Need this feature badly; front-end validation desperately wants these, maxlength in particular.

**Comment by VikingsFan** [comment]
Cost estimation: 2 days

Introduce StringPropertyConfiguration, Binary.., Decimal... to make this feature work both in Fluent API and ConventionModelBuilder.

**Comment by VikingsFan** [comment]
@escape-llc would you please help to review my [PR](https://github.com/OData/WebApi/pull/571) ?

**Comment by escape-llc** [comment]
Based on my beginner understanding of the framework, it all looks pretty straightforward.  I assume the tests pass; are there any test cases for the "optional" cases (e.g. max length was not supplied).

The only stylistic recommendation I can make is in the static methods in `EdmTypeBuilder.cs` e.g. `AddLengthConfigInPrimitiveTypeReference`.  Personally I do not advocate ever re-assigning to parameters, so I would encourage changing the re-assignment to a simple `return` that makes it clearer.

That also stops the "fall-through" technique, which to me requires the reader scrutinize the control flow completely to see if the "right value" is coming out the other side.  It is simple now but doesn't take much to be a cognitive burden (as in `CreateStructuralTypeBody` to me that needs some refactor).  Using `return` eliminates any such burden.

As a refactor suggestion for `CreateStructuralTypeBody` a factory method pattern with (type, config, property) in and `IEdmProperty` out.  Some variation of `Func` will suffice.  Then put them in a map or array indexed on `PropertyKind` that can all be static methods that are shareable.  That might be overkill but it opens the possibility to customize that piece "externally" if necessary.

**Comment by VikingsFan** [comment]
@escape-llc Thanks for your feedback, I have updated the code, about `CreateStructuralTypeBody`'s refactor, you can give a PR like mine with your customize scenario, that's very welcome!

**Comment by habbes** [comment]
Closing this issue since it seems to have been addressed by the linked PR. If this still affects the latest versions of the library, kindly open a new issue.

**Comment by andygjp** [comment]
So how do I go about setting the MaxLength on a parameter? It doesn't seem like ParameterConfiguration has any way of setting it with version 8.0.7 of Microsoft.AspNetCore.OData.
