### ISSUE TITLE
Orderby incoherent with expand

### ISSUE THREAD

**Issue by Biratus** [OData/WebApi#2119]
*I am trying to order a list of entities according to a value in a link entity*

### Reproduce steps

Have a list of entities A (here: incidents). Each of those reference one other entity B (here: motive) which has a *label* field:
So *incident* is structured like this:
``` 
{
    "motive":{
        "label" : "value"
    }
 }
``` 
Mutliple entities A can reference the same entity B

HTTP request: 
`http://server/incidents?$expand=motive($orderby=label)`

### Expected result

A list of *incident* ordered by the label of their motive
Example:
``` 
[ 
    {"motive":{   "label" : "value1" }},
    {"motive":{   "label" : "value2" }},
    {"motive":{   "label" : "value3" }}
]
```

### Actual result

`Microsoft.Crm.CrmHttpException "Only $select and $filter clause can be provided while doing $expand on many-to-one relationship."`

### Additional detail

I don't understand why we get this error, it's a simple request which sould be accepted.
I've also tried my luck with these:
`http://server/incidents?$orderby=motive/label` : `System.NullReferenceException "Object reference not set to an instance of an object."`
`http://server/incidents?$expand=motive/$ref($orderby=label)` works but is not ordered

**Comment by gathogojr** [comment]
@Biratus If you want to order by the property `label` of the `incident`'s navigation property `motive` and at the same time expand `motive`, this might work for you:

`http://ServiceRoot/incidents?$expand=motive&$orderby=motive/label`

**Comment by Biratus** [comment]
@gathogojr Adding the $expand doesn't change anything compared to:
`http://server/incidents?$orderby=motive/label`
I still get the same error: `System.NullReferenceException "Object reference not set to an instance of an object."`
HOWEVER: The motive entity is a **lookup** of incidents. and the answer to my issue turned out to be:
`$orderby=_motive_value`
