### ISSUE TITLE
Instance property 'Id' is not defined for type 'DynamicTypeWrapper'

### ISSUE THREAD

**Issue by ramil-mux** [OData/WebApi#2123]
I'm getting an error when using $orderby with $apply=groupby in classic ASP.NET application
I sent this request to my controller: `odata/Logs?$apply=groupby((UserLogin))&$orderby=UserLogin`

 and server returned me 500 Internal Server Error with exception like in title.

This exception is thrown if I set the following configuration in **WebApiConfig**:
 ```
config.AddODataQueryFilter(new EnableQueryAttribute()
            {
                PageSize = 500,
                MaxNodeCount = 1000,
                MaxOrderByNodeCount = 15
            });
ODataModelBuilder builder = new ODataConventionModelBuilder();
builder.EntitySet<Log>("Logs");
ODataBatchHandler odataBatchHandler = new DefaultODataBatchHandler(GlobalConfiguration.DefaultServer);
odataBatchHandler.MessageQuotas.MaxOperationsPerChangeset = 150;
odataBatchHandler.MessageQuotas.MaxPartsPerBatch = 150;

config.MapODataServiceRoute("odata", "odata",
                model: builder.GetEdmModel(),
                batchHandler: odataBatchHandler);

config.Select()
      .Expand()
      .Filter()
      .OrderBy()
      .MaxTop(null)
      .Count();
```
And my controller have next GET method:
```
public class GenericODataController<T, U> : ODataController where T : EntityBase<U>
{
        private readonly IEntityService<T> _entityService;

        public GenericODataController([Import]IEntityService<T> entityService)
        {
            _entityService = entityService;
        }

        public IQueryable<T> Get()
        {
            var ret = _entityService.GetEntities().AsNoTracking();
            return ret;
        }

        public SingleResult<T> Get([FromODataUri] U key)
        {
            IQueryable<T> result = Get().Where(p => (object)p.Id == (object)key).AsNoTracking();
            return SingleResult.Create(result);
        }    
}
```
Log entity is:
```
public partial class Log: EntityBase<long>
{
        public long Id { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? ReportId { get; set; }
        public string UserLogin { get; set; }
        public string LogLevel { get; set; }
        public string Message { get; set; }
}
```

**BUT** if I add `[EnableQuery]` attribute to GET method request work fine.
Should you explain me how I can avoid `[EnableQuery]` attribute and using only `HttpConfigurationExtensions.AddODataQueryFilter` method?
Does `[EnableQuery]` attribute supress settings in `AddODataQueryFilter`?

My Microsoft.AspNet.OData packge version is 6.0.0 and Microsoft.OData.Core is 7.1.1

Thanks,
Ramil Mukhametshin

**Comment by gathogojr** [comment]
@ramil-mux Assuming that you're creating an OData v4 service, the `EnableQuery` attribute is what enables clients to modify the query, by using query options such as $filter, $sort, $orderby, etc. That together with the fact that your controller action method returns `IQueryable`. You'll need that to use the system query options.

**Comment by ramil-mux** [comment]
@gathogojr Yes, you are right, but doesn't `AddODataQueryFilter` do the same for all `IQueryable` action methods?
This error occurs when I use **$apply** and **$sort** together in queury and don't use `EnableQuery` attribute. Can I use these query options without `EnableQuery` attribute using only `AddODataQueryFilter`?

**Comment by gathogojr** [comment]
@ramil-mux You're right. The global configuration for EnableQuery should work. Can you try the latest OData WebAPI library?

**Comment by ramil-mux** [comment]
@gathogojr Thank you very much! I've updated the OData library and now all requests work fine.
