### ISSUE TITLE
Ordering by filtered expand count does not work

### ISSUE THREAD

**Issue by joshcomley** [OData/WebApi#2129]
I am using `Microsoft.AspNetCore.OData` v7.3.0 in an app configured as `netcoreapp3.1`.

I can get a count value returned from OData for a filtered expand:

    /People?$expand=Addresses($filter=Price gt 50000;$count=true)

Which will give me:

    {
        ....
        "Addresses@odata.count": 10,
        "Addresses": [..ten entries..]
        ....
    }

But attempting to order by this number does not work:

    /People?$orderby=Addresses($filter=Price gt 50000)/$count

`The query specified in the URI is not valid. Could not find a property named 'Price' on type 'User'.`

It doesn't appear to be correctly mapping the inner contents of the expand when it is an `orderby`.

**Comment by paulodero** [comment]
@joshcomley Could you please share the model used in this case and clarify on the examples you have provided to help us understand the issue better?

**Comment by KenitoInc** [comment]
Closing this since no repro was shared. 

@joshcomley Feel free to open a new issue if you encounter any more problems
