### ISSUE TITLE
IN operator with quote (") or %22 fails

### ISSUE THREAD

**Issue by hidegh** [OData/WebApi#2136]
Similar to to: https://github.com/OData/WebApi/issues/1596 - IN operator value(s) parsing issues

**An HTTP OData V4 request using a filter with the IN operator with strings containing " fails.**

**Custom endpoint:**
$filter=EquipmentName in ( 'Scot"t', 'another string' )

**Error:**
ExceptionMessage, Invalid JSON. A comma character ',' was expected in scope 'Array'. Every two elements in an array and properties of an object must be separated by commas.

**Additional detail:**
Microsoft.AspNetCore.OData 7.4
Microsoft.OData.Core 7.6.4
.NET Core 2.2.0

---
**OData v4 sample endpoint:**
https://services.odata.org/TripPinRESTierService/People?$filter=FirstName in ('Scot"t')

**Error:**
```
{
    "error": {
        "code": "",
        "message": "Syntax error at position 12 in 'FirstName in ('Scot\"t')'."
    }
}
```

---

**Expected behaviour:**
Just like in case of: https://services.odata.org/TripPinRESTierService/People?$filter=contains(FirstName, 'Scot"t') the API returns a list of values meeting filter criteria & does not throws an error.

**Comment by hidegh** [comment]
NOTE: currently as we do use a custom toOdataString tool, we can convert any 'in' operator to a composite 'or' operator with fields: [field eq value(i)]...but not everyone might have this luxury:
```
    if (filter.operator === 'in') {

      const values = isArray(filter.value) ? filter.value : [filter.value];

      const dontUseInOperator = settings.filter.dontUseInOperator || (filter as any).dontUseInOperator;
      const dontUseInOperatorWithStringsContainingQuotes =
        settings.filter.dontUseInOperatorWithStringsContainingQuotes
        && values.some(v => isString(v) && v.indexOf('"') > -1);

      if (dontUseInOperator || dontUseInOperatorWithStringsContainingQuotes) {

        const anyValueFilter = {
          logic: 'or',
          filters: values.map( v =>
            ({ field: filter.field, operator: 'eq', value: v })
          ) as FilterDescriptor[]
        } as CompositeFilterDescriptor;

        return compositeFilterSerializationFn(anyValueFilter, settings);
      }

    }
```

**Comment by gathogojr** [comment]
@hidegh Kindly note that we were able to reproduce this issue. Seems that `$filter=FirstName eq 'Scot"t'` is parsed correctly but `$filter=FirstName in (`Scot"t')` isn't. We have added the issue to our backlog so it can get some attention.
Kindly note that we also accept pull requests just in case you're in a position to contribute. Either way, thank you for bringing the issue to our attention

**Comment by xuzhg** [comment]
FYI,
1) In a single quote wrapped string, it can contain single quote, whose value should escape to "double single quotes". It also can contain double quote, whose value don't need to escape it.
2) in a double quote wrapped string (JSON string), it can contain single quote, the single quote should not escape, but for double quote, we should escape it use "\"

**Comment by gathogojr** [comment]
@xuzhg In the case highlighted above, what you have in `Scot"t` is not "double single quotes" but "double quotes". I also thought it was double single quotes until I copied and pasted the value to my local environment. Like you noted, the double quote does not need to be escaped but an exception is being thrown if you use it within a single-quoted string

Escaped single quotes, i.e. double single quotes like in `Scot''t` are being handled okay.

**Comment by xuzhg** [comment]
@hidegh.  Would you please try the nightly named "Microsoft.OData.Core.7.6.4-Nightly202005061030.nupkg". It should have the changes.
You can use this nightly feed: "https://www.myget.org/F/odatanightly/api/v3/index.json".

Install "Microsoft.AspNetCore.OData 7.4", after that update the installed Microsoft.OData.Core to the above nightly.

Please let me know the result.

**Comment by xuzhg** [comment]
ODL 7.6.4 and 7.7 has shipped. So, close it.
