### ISSUE TITLE
EnableCaseInsensitive doesn't work right when $top used

### ISSUE THREAD

**Issue by ImanMahmoudinasab** [OData/WebApi#214]
`config.EnableCaseInsensitive(true);`  works prefect except when there is `$top` in the url and property name is camelCase then it gives me error that the property not exist:

example:
`/api/Reports?$orderby=id desc&$top=3&$count=true`
this is OK and
`/api/Reports?$orderby=reportNo desc&$count=true` 
this is OK but:
`/api/Reports?$orderby=reportNo desc&$top=3&$count=true`
causes error: `Could not find a property named 'reportNo' on type 'Some.Namespace'.`

**Comment by xuzhg** [comment]
Thanks. It's a Web API Bug.

Because $skip or $top require a stable sort for predictable results. When to create a stable sort order by, We only create a default query option parser. While the default query option parser doesn't support case insensitive.
We will fix it soon.

**Comment by ImanMahmoudinasab** [comment]
You are welcome,
Hope to see it is fixed soon.
Have a good time.

**Comment by xuzhg** [comment]
@ImanMahmoudinasab, would you please try the new fixed and let us know any more concerns? I'd be very happy to help. Thanks.

**Comment by ImanMahmoudinasab** [comment]
@xuzhg, Thanks for resolving the issue.
Unfortunately I am busy these days but I would try it upon there is a nuget package  for v5.4.1.
 Thank you for your time and effort.

**Comment by xuzhg** [comment]
@ImanMahmoudinasab 

I closed this issue. If you find further problem, please feel free to re-active it. Thanks.
