### ISSUE TITLE
Wrong @odata.context value when using base path

### ISSUE THREAD

**Issue by PatrickHofman** [OData/WebApi#2141]
When the OData endpoint uses a path relative from the base path, the wrong value for @odata.context is generated.

### Assemblies affected

* Microsoft.AspNetCore.OData 7.4.0

### Reproduce steps

Use this code in `Startup`:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();
    services.AddOData();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    else
    {
        app.UseExceptionHandler("/Error");
    }

    app.UseRouting();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllers();

        endpoints.Select().Filter().OrderBy().Count().MaxTop(10);
        endpoints.MapODataRoute("odata", "odata", GetEdmModel());
    });
}

private IEdmModel GetEdmModel()
{
    var odataBuilder = new ODataConventionModelBuilder();
    odataBuilder.EntitySet<WeatherForecast>("WeatherForecast");
    return odataBuilder.GetEdmModel();
}
```

Then go to the project settings in Visual Studio, Debug, App URL, and change it from something like `http://localhost:56503` to `http://localhost:56503/test` (see the additional 'test').

Run the project and navigate to `http://localhost:56503/test/odata`.

### Expected result

The service should return the 'test' path in the URL in @odata.context:

```
{"@odata.context":"http://localhost:56503/test/odata/$metadata","value":[{"name":"WeatherForecast","kind":"EntitySet","url":"WeatherForecast"}]}
```

### Actual result

The service returns a value for @odata.context omitting the path 'test':

```
{"@odata.context":"http://localhost:56503/odata/$metadata","value":[{"name":"WeatherForecast","kind":"EntitySet","url":"WeatherForecast"}]}
```

### Additional detail

Test project: https://github.com/PatrickHofman/odata-webapi-issue-2141

**Comment by PatrickHofman** [comment]
Some more analysis. It seems the wrong URL is provided through the default base address as defined here:

https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatter.cs#L282

Which eventually calls:

https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData/Extensions/UrlHelperExtensions.cs#L81

It seems the wrong value is returned from `Link`. The `routeName` is correct (`odata`). The `odataPath` is empty.

To me, `Link` is a ASP.NET Core MVC method. I am not sure if there is any specific OData code in between it that causes this method to behave differently. It seems strange this method is broken, since it should have been found by thousands of developers already then. I hope someone else has some pointers to investigate further.

**Comment by PatrickHofman** [comment]
Furthermore, it seems that the path is splitted in the `HttpRequest` class obtained from `HttpContext.Request` into `Path` and `PathBase`. I guess the latter isn't included in the generated URL somewhere:

![image](https://user-images.githubusercontent.com/9336133/80689334-73908000-8acd-11ea-8e56-bb31b43a5a4b.png)

**Comment by xuzhg** [comment]
@PatrickHofman Did you meet this error when set the appUrl in properties=>Debug

![image](https://user-images.githubusercontent.com/9426627/81033201-87c6db00-8e47-11ea-922d-1df47dd82a98.png)

**Comment by PatrickHofman** [comment]
@xuzhg Ah, okay. I didn't see it indeed. Thanks for investigating.

**Comment by xuzhg** [comment]
Merged the PR. Thanks.

**Comment by PatrickHofman** [comment]
Thanks all for your effort!
