### ISSUE TITLE
ODataController's Created(entity) method synthesizes incomplete Location header

### ISSUE THREAD

**Issue by henrikdahl8240** [OData/WebApi#2144]
The Location header in the response from creating new instances miss the application name.

My situation:
A simple project, where I can create e.g. Cars. So I have a CarsController which derives from ODataController. The Cars controller has a Post method like:
```
public async Task<IActionResult> Post([FromBody] Car car)
{
    if (!ModelState.IsValid)
    {
        return BadRequest(ModelState);
    }

    DbContext.Cars.Add(car);
    await DbContext.SaveChangesAsync();
    return Created(car);
}

```

The url used for creating a car looks like:
`http://mymachine/myapp/odata-internal/Worlds`

The reponse starts with this:
```
HTTP/1.1 201 Created
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
Location: http://mymachine/odata-internal/Worlds(13e2da1f-2ffb-4951-e0d5-08d7f00703b5)
Server: Microsoft-IIS/10.0

```
It seems like the Location header is wrong, as it does not contain myapp. Shouldn't it rather be:
`Location: http://mymachine/myapp/odata-internal/Worlds(13e2da1f-2ffb-4951-e0d5-08d7f00703b5)`

Should I do something in order to make the Location header to include the application name, in this example `myapp`?

For your information, I am using the feature in Visual Studio for running the ASP.NET project using IIS.

I am using .NET 5.0 preview 3, but it's the same problem using .Net Core 3.1.3. I am using Microsoft.AspNetCore.OData 7.4.

**Comment by henrikdahl8240** [comment]
@xuzhg, perhaps you can mention as you will have a nightly build, where the problems should be corrected because then I would like to try/verify it.

**Comment by xuzhg** [comment]
@henrikdahl8240 Cool. The nightly named "Microsoft.OData.Core.7.6.4-Nightly202005061030.nupkg" should have the changes. 
You can use this nightly feed: "https://www.myget.org/F/odatanightly/api/v3/index.json". 
 please let me know the result

**Comment by henrikdahl8240** [comment]
@xuzhg, Unfortunately it does not work. The Location header is exactly as before, i.e. without the application name.

For your information, I record the dialogue using Fiddler, where I can see, that the Location header still does not include the name of the application.

Can it be, that your correction only addresses the other problem you referred to, i.e. https://github.com/OData/WebApi/issues/2141?

As far as I understand, the https://github.com/OData/WebApi/issues/2141 situation used Kestrel whereas I use IIS.

If you make a new nightly build, please inform me, and I will try it quickly.

In my project file I have:
```
<ItemGroup>
  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.3" />
  <PackageReference Include="Microsoft.AspNetCore.OData" Version="7.4.0" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="5.0.0-preview.3.20181.2" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0-preview.3.20181.2" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.0-preview.3.20181.2">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  </PackageReference>
  <PackageReference Include="Microsoft.OData.Core" Version="7.6.4-Nightly202005061030" />
</ItemGroup>

```
As you can see, I have indeed used the nightly build you referred to.

**Comment by xuzhg** [comment]
@henrikdahl8240 Ah, I see, I made a mistake, I confused this issue with others. This issue's fix is still in PR of WebAPI repo. I should give you a WebAPI nightly, not a OData.net nightly. Let me create a webapi and share the link for you. Sorry for confusing.

**Comment by henrikdahl8240** [comment]
@xuzhg It is perfectly fine. I look forward trying it.

**Comment by xuzhg** [comment]
@henrikdahl8240 Here we are. 
The nightly package is named "[Microsoft.AspNet.OData 7.4.0-Nightly202005071659](https://www.myget.org/feed/webapinetcore/package/nuget/Microsoft.AspNet.OData)"

The feed is "https://www.myget.org/F/webapinetcore/api/v3/index.json".
Just update the WebAPI package to this version, needn't change the referenced OData.net package. Let me know the result. Thanks a lot.

**Comment by henrikdahl8240** [comment]
@xuzhg It seems like it works fine. The Location header now includes the name of the web application as I was expecting. Will the correction make it to version 7.5.0 or before that?
Would you say that it's OK to use your nightly build or there are some incomplete areas in this nightly drop?
Should I close the issue despite the solution has not made it to a released version yet?

**Comment by xuzhg** [comment]
@henrikdahl8240 Glad to hear that.
If you want to use a package in your product, i'd like you to wait couple days to use the official version. 
I can plan to release a new version (maybe 7.4.1) to include that. I will update you if i have certain release date.
I closed this issue, if you have further concerns, we can continuously use it to communicate, or feel free file new issue. Thanks a lot.
