### ISSUE TITLE
Return 404 for Function defined with HttpPost

### ISSUE THREAD

**Issue by alvachien** [OData/WebApi#2145]
Function defined with HttpPost doesn't work.

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData WebApi lib 6.1.0
OData WebAPI 7.4
ASP.NET Core 3.1.3

### Reproduce steps

A reproducible repo: https://github.com/alvachien/odatatest
This repo copied from [ODataSamples ](https://github.com/OData/ODataSamples/tree/master/WebApiCore/ODataFunctionSample)  but changed it to suite ASP.NET Core 3.1.
Besides that, the only change is following for Method MostExpensive:
        // [HttpGet]
        [HttpPost]

Execute it and got a 404:
POST http://localhost:9010/odata/Products/Default.MostExpensive()

### Expected result

It shall work like HttpGet.
*What would happen if there wasn't a bug.*

### Actual result

Status Code 404 Returned.

*What is actually happening.*

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by henrikdahl8240** [comment]
Functions are invoked by HTTP Get. Actions are invoked by HTTP Post. Therefore you can either declare it as an action and invoke it by HTTP Post as you want or invoke what you have by HTTP Get.

**Comment by alvachien** [comment]
> Functions are invoked by HTTP Get. Actions are invoked by HTTP Post. Therefore you can either declare it as an action and invoke it by HTTP Post as you want or invoke what you have by HTTP Get.

Thank you. Rechecked the OData document, it stated clearly:
> To invoke a function bound to a resource, the client issues a GET request to a function URL.

[Link](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#_Toc31359009)
