### ISSUE TITLE
UpdatedODataResult returns empty body and status code 204

### ISSUE THREAD

**Issue by alvachien** [OData/WebApi#2146]
When updating an entry, and the controller returns Updated(entity), the BODY is empty.

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData WebApi lib 6.1.0
OData WebAPI 7.4
ASP.NET Core 3.1

### Reproduce steps

A reproducible repo: https://github.com/alvachien/odatatest
This repo copied from ODataSamples but changed it to suite ASP.NET Core 3.1.

Besides that, one more method added for supporing HttpPut
``` 
        // Update
        [HttpPut]
        public IActionResult Put([FromODataUri] int key, Product prd)
        {
            Product retval;
            if (_data.TryGetValue(key, out retval))
            {
                return Updated(retval);
            }
            else
            {
                return NotFound();
            }
        }
```

Try call it: http://localhost:54436/odata/Products(1)
The key 1 is exists and debugging inside, the *retval* contains value.

### Expected result

API shall return the updated result.

### Actual result

Status code 204 is returned with an empty BODY.

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by ElizabethOkerio** [comment]
@alvachien by default in odata created resources are returned but updated resources are not and this can be controlled by the preference header using return=representation to return the updated resource. Here is a link to the return preference in odata. http://docs.oasis-open.org/odata/odata/v4.01/os/part1-protocol/odata-v4.01-os-part1-protocol.html#sec_Preferencereturnrepresentationandret
