### ISSUE TITLE
Issue about Web API model validation and ODataUntypedActionParameters etc.

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#215]
`System.Web.OData.PerRequestParameterBinding.ExeucteBindingAsync` eventually executes `DefaultBodyModelValidator`, and `DefaultBodyModelValidator` picks up the CSDL types to validate such as CsdlSemanticsEntityTypeDefinition. It takes time to complete.

Since the generic Web API validator has no knowledge on EDM, consider disabling validation for `ODataUntypedActionParameters`, `EdmEntityObject`, etc.

E.g.,
Add `NonValidatingParameterBinding` attribute to those types

-or-

Create a custom body model validator to not validate
`ODataUntypedActionParameters`
`ODataActionParameters`
`EdmEntityObject`
`EdmModel`
`EdmEntityType`
`EdmStructuralProperty`
`EdmNavigationProperty`

**Comment by xuzhg** [comment]
Fixed at:  185ace5e4fbbdfa2c3699914ec2e6bad3762635e
