### ISSUE TITLE
OData endpoint routing not working with either the OData Connected Service client or the Unchase OData Connected Service client.

### ISSUE THREAD

**Issue by ImGonaRot** [OData/WebApi#2150]
Linked from previous issue.
https://github.com/OData/WebApi/issues/2029

Code to reproduce
https://github.com/OData/WebApi/issues/2029#issuecomment-607307659

Added the new 7.4.0 beta to my OData core 3.1 project and the endpoint routing is not working with either the OData Connected Service client or the Unchase OData Connected Service client.
https://docs.microsoft.com/en-us/odata/client/code-generation-tool
The "GET" is working but the "PUT", "POST", "PATCH" are not working with those clients.

Basically to get these clients to work, I had to roll back to use MVC routing.

```c#
services.AddControllers(mvcOptions => mvcOptions.EnableEndpointRouting = false);

// NOTE: If you remove the UseMvc it will break the OData Client proxy
// TODO: Remove the UseMvc once the OData team gets it working. 
app.UseMvc(routeBuilder =>
{
    routeBuilder.Select().Filter().OrderBy().Count().MaxTop(100);
    routeBuilder.MapODataServiceRoute("odata", "odata", GetEdmModel());
});


// NOTE: If you add the UseEndpoints it will break the OData Client proxy
// TODO: Add the UseEndpoints once the OData team gets it working. 
//app.UseEndpoints(endpoints =>
//{
//    endpoints.MapControllers();
//    endpoints.Select().Filter().OrderBy().Count().MaxTop(100);
//    endpoints.MapODataRoute("odata", "odata", GetEdmModel());
//});
```

Sample project
https://github.com/OData/WebApi/issues/2029#issuecomment-608174541

@xuzhg

Here is a link to the test project.
It includes both a Console client and an IIS Express OData site.

https://github.com/tcon47/tcon47.github.io/tree/master/TestODataCore

**Comment by habbes** [comment]
@ImGonaRot  Hi thanks for sharing the test project. I tested it on my end and all operations ran successfully, even when using endpoint routing. Generally the routing implementation should not affect a client as long as it sends valid requests, using valid urls and payloads.

Furthermore, when you say the clients do not work, what do you mean specifically? Are they throwing an exception? If so, which one?

Could you inspect the requests sent from the client using a tool like Fiddler and verify whether the requests are sent correctly?

**Comment by ImGonaRot** [comment]
In the TestODataCore.sln I provided there are 2 projects. 

1. TestClient.csproj --> Windows console app using OData Connected Services, proxy generated from MS OData Connected Services

2. TestODataCore.csproj --> OData Core service.

If you run the solution and follow the steps listed above on commenting in / out the routing information under the "AddControllers" inside the "Startup.cs", it will show you that on the Console Client the "PUT", "POST", "PATCH" will not work.

The Console Client program.cs has a test for "GET", "PUT", "POST", and "DELETE".
Just run the solution provided and hit 1 - 6 to see the problem.

**Comment by KenitoInc** [comment]
@ImGonaRot Was this issue resolved? If yes, kindly close the issue

**Comment by KenitoInc** [comment]
Closing due to non response. Feel free to open a new issue.
