### ISSUE TITLE
`$count=true&$top=0` is no longer returns a value

### ISSUE THREAD

**Issue by cilerler** [OData/WebApi#2158]
`$count=true&$top=0` is no longer returns a value instead it returns **HTTP/1.1 404 Not Found** where `$count=true&$top=1` works as expected.

### Assemblies affected

AspNetCore 7.4.0

##### Get total counts without getting any value
```HTTP
GET {{finalUrl}}?$count=true&$top=0 HTTP/1.1
Host: {{host}}
Cache-Control: no-cache
```
where it works for

##### Get total counts with getting a record
```HTTP
GET {{finalUrl}}?$count=true&$top=1 HTTP/1.1
Host: {{host}}
Cache-Control: no-cache
```

### Expected result

the query with `?$count=true&$top=0` should return the total count of the records as it returns in `?$count=true&$top=1`

### Actual result

it returns `NotFound.`

### Additional detail

It was working with earlier versions.

**Comment by hidegh** [comment]
**NotFound so 404 is probably an URI issue, less likely related to the OData querystring.** Could not reproduce this on my pet-project.

---

I have updated the reference to latest OData in one of my public projects (https://github.com/hidegh/Meal-tracker), and it works with latest version ofAspNetCore 7.4.0!

So the https://{{netAppApi_domain}}/Users/4/meals/?$count=true&$top=0&$filter=mealsCount ne 3 will yield this result:
```
{
    "value": [],
    "@odata.count": 30,
    "@odata.nextLink": ""
}
```

If you would like to test it, just download the project, build & run it, load the postman collection, execute the login (with admin) and then use the meals endpoint (rest must not have odata exposed).

**Comment by cilerler** [comment]
According to [here](https://github.com/hidegh/Meal-tracker/blob/9798d8685f15e87e03fd414156b184de49a3c8c1/RMeals-server-dotNet/src/RMealsAPI/RMealsAPI.csproj#L15) you are not using 7.4 which supports endpoints which according to here [here](https://github.com/hidegh/Meal-tracker/blob/9798d8685f15e87e03fd414156b184de49a3c8c1/RMeals-server-dotNet/src/RMealsAPI/Startup.cs#L241-L245) you are not using it.

**Comment by KanishManuja-MS** [comment]
@cilerler Can you please share your repro? It is really strange as query options do not influence routing. I would anticipate a bad request but not a not found error response.

**Comment by bdebaere** [comment]
@cilerler Seems to be working fine to me. Can you share a repro of this failing?

This is my configuration:
netcoreapp3.1
Microsoft.AspNetCore.OData 7.4.1

```csharp
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            var queryAttribute = new EnableQueryAttribute()
            {
                MaxTop = 3,
                PageSize = 4
            };
            services.AddOData();
            services.AddODataQueryFilter(queryAttribute);
            services.AddMvcCore();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.Select().Filter().OrderBy().Count().MaxTop(null);
                endpoints.MapODataRoute("odata", "odata", GetEdmModel());
            });
        }

        private IEdmModel GetEdmModel()
        {
            var odataBuilder = new ODataConventionModelBuilder();
            odataBuilder.EntitySet<Product>("Products");

            return odataBuilder.GetEdmModel();
        }
    }

    public class ProductsController : ODataController
    {
        private readonly IQueryable<Product> products;

        public ProductsController()
        {
            products = new List<Product>
            {
                new Product
                {
                    Id = 1,
                },
                new Product
                {
                    Id = 2,
                },
                new Product
                {
                    Id = 3,
                },
                new Product
                {
                    Id = 4,
                },
                new Product
                {
                    Id = 5,
                },
            }.AsQueryable();
        }

        public IQueryable<Product> Get()
        {
            return products;
        }
    }

    public class Product
    {
        public int Id { get; set; }
    }
```

This is the result when calling /odata/Products?$count=true&$top=0:
![afbeelding](https://user-images.githubusercontent.com/1436449/84988215-e6b78980-b141-11ea-9337-a01a2955c08f.png)

**Comment by cilerler** [comment]
I'm sorry, somehow I did miss this thread. I just complete the initial test, and you are right; it is working.  
However, it is not working on my Blazor project and trying to narrow the scope; I will provide a repo/sample code as soon as I reproduce the issue with your sample.

**Comment by cilerler** [comment]
I finally figured it out.  Incase if someone hits the same issue; in code below `records.Any()`'s `Any()` part comes from `using Microsoft.EntityFrameworkCore.Internal;` and it causes `$count` to not work.

```csharp
        /// <summary>
        /// Retrieves all records
        /// </summary>
        /// <param name="options">The current OData query options.</param>
        /// <returns>All available records.</returns>
        /// <response code="400">The parameters are invalid.</response>
        /// <response code="404">The record does not exist.</response>
        /// <response code="200">The record was successfully retrieved.</response>
        [HttpGet]
        [ODataRoute]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        //[ProducesResponseType(typeof(ODataValue<IEnumerable<Product>>), StatusCodes.Status200OK)]
        public IActionResult Get(ODataQueryOptions<Product> options)
        {
            var validationSettings = new ODataValidationSettings()
            {
                // AllowedOrderByProperties = { "Id", "Name" },
                AllowedQueryOptions = AllowedQueryOptions.All,
                AllowedArithmeticOperators = AllowedArithmeticOperators.All,
                AllowedFunctions = AllowedFunctions.AllFunctions,
                AllowedLogicalOperators = AllowedLogicalOperators.All,
                MaxOrderByNodeCount = 2,
                MaxTop = 100,
                MaxSkip = 100000,
                MaxNodeCount = 200,
                MaxAnyAllExpressionDepth = 3,
                MaxExpansionDepth = 3
            };

            try
            {
                options.Validate(validationSettings);
            }            catch (ODataException oe)
            {
                return BadRequest(oe);
            }

            var query = _products.AsQueryable();
            var records = options.ApplyTo(query);
            if (!records.Any())
            {
                return NotFound();
            }

            return Ok(records);
        }
```

## Microsoft.EntityFrameworkCore.Internal

```csharp
        public static bool Any([NotNull] this IEnumerable source)
        {
            foreach (var _ in source)
            {
                return true;
            }

            return false;
        }
```

Again, thank you @KanishManuja-MS and @bdebaere for looking into it.

**Comment by bdebaere** [comment]
@cilerler Be aware that by calling Any you are effectively executing an additional database query.

Also, I'm not familiar why you would decide to return a 404, instead of an empty array of products when no products are found matching the criteria.

GET Product/1 to me means get me the product with id 1, of course if it does not exist a 404 should be returned.
GET Products to me means, in an OData context, get me all the products matching a certain criteria. Returning 404 would mean that the Products resource does not exist, which is never the case.

**Comment by cilerler** [comment]
I appreciate the heads-up @bdebaere, thank you.

I'm 100% with you on 404, it still doesn't make sense to me, and I don't like it at all.
Unfortunately, there is a practice going on lately that some major B2B APIs on the Internet is returning 404 for not found records, even if the URL exists.  And according to the business requirements for this project, I have to return 404 _(so I have no choice)_

![](https://sdk.bitmoji.com/render/panel/fb82c679-2fe8-4acf-8f3e-e1846c970479-1d989a62-ae8a-48a8-b04f-0f575358153a-v1.png?transparent=1&palette=1)
