### ISSUE TITLE
Nullable foreign key in 5.4.0

### ISSUE THREAD

**Issue by pascalberger** [OData/WebApi#216]
After Update to Version 5.4.0 I receive the following error in my application:

> Error: The 'ObjectContent`1' type failed to serialize the response body for content type 
> 'application/json; odata=fullmetadata; charset=utf-8'.; The property 'MyProperty[Nullable=False]' of 
> type 'Edm.String' has a null value, which is not allowed.;

The correspondig model looks like this:

    public class MyModel
    {
        [Key]
        public int Id { get; set; }

        [ForeignKey("MyProperty")]
        public string MyPropertyId { get; set; }

        public virtual MyReferenceType MyProperty { get; set; }
    }

In the case where the error is thrown MyProperty has no value assigned. This worked fine in 5.3.1. I assume this has to do with the new [referential constraints](http://odata.github.io/WebApi/referential-constraint/), but I'm not sure what I need to change to make my code working again (meaning MyProperty should allow null)

**Comment by xuzhg** [comment]
@pascalberger Did you make sure the MyProperty is an optional navigation property?

**Comment by pascalberger** [comment]
How do you mean making it an optional navigation property? Since it is a string it can be null. I don't explicitely set it somewhere optional, but also never did in 5.3.1.

**Comment by xuzhg** [comment]
@pascalberger 

[OData V4 spec](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part3-csdl/odata-v4.0-errata02-os-part3-csdl-complete.html#_Toc406397969) says:
The type of the dependent property MUST match the type of the principal property. If the navigation property on which the referential constraint is defined or the principal property is nullable, then the dependent property MUST be nullable. If both the navigation property and the principal property are not nullable, then the dependent property MUST be marked with the Nullable="false" attribute value.

==================================
So, the nullable value of "MyPropertyId" depends on the nullable of principal property and the nullable of navigation property.

Supposed the principal property is "PropertyId", So, the nullable mapping can be shown as:

|PropertyId|MyProperty |MyPropertyId 
--------------|----------------|------------------
true|true|true
true|false|true
false|true|true
false|false|false

note: true means nullable, false means non-nullable. 
So, can you show us your model builder codes?

**Comment by pascalberger** [comment]
It's with OData v3 (not v4). 

Here's my (simplified) builder:

    var builder = new ODataConventionModelBuilder();
    builder.EntitySet<MyModel>("MyModels");
    builder.EntitySet<MyReferenceType>("MyReferenceTypes");
    builder.Namespace = typeof(MyModel).Namespace;

    config.Routes.MapODataRoute(
        routeName: "ODataRoute",
        routePrefix: "odata",
        model: builder.GetEdmModel(),
        batchHandler: new DefaultODataBatchHandler(GlobalConfiguration.DefaultServer));

And here's the definition of `MyReferenceType`:
    public class MyReferenceType
    {
        [Key]
        public string Id { get; set; }
    }

Since MyModel.MyPropertyId is a string (and therefore nullable) and MyReferenceType.Id is also a string (and therefore nullable) I would expect that MyModel.MyProperty is also handled as nullable.

**Comment by xuzhg** [comment]
For V3, please refer to [10.4 Referential constraint](http://www.odata.org/documentation/odata-version-3-0/common-schema-definition-language-csdl)

*It says: The property references for the principal entity MUST be the same property references specified in the edm:Key of the principal entity type, however they need not share the same order.*

Because the edm:Key is always required (non-nullable). So, the dependent property is always required. 

Yes, your `MyModel.MyPropertyId` is a string, however, meantime it's also a key. 

<h4>Keys are always required (non-nullable). </h4>

You can't identify a property nullable or not from CLR model. You'd check it from Edm Model. The better way is to check the metadata document.

**Comment by pascalberger** [comment]
OK, I get the point with the key being required. But this means there is no way to let my code run under WebApi for OData 3 5.4.0? From the business logic point of view `MyModel.MyProperty` is optional and therefore there will be data returned with `MyModel.MyProperty == null`. I don't see how I can model this differently to make the business requirements and the OData spec both happy.

**Comment by xuzhg** [comment]
Can you explicitly set the property as nullable?

**Comment by pascalberger** [comment]
Which property or how to explicitely set as nullable? 

MyModel.MyPropertyId is a string and therefore nullable by design, MyModel.MyProperty is a reference type and also nullable by design.

**Comment by xuzhg** [comment]
@pascalberger: please re-open or file new issue if you find further concern.

**Comment by DisgruntledDog** [comment]
Has this been resolved for ODataV3? I got the latest build and I still have this same problem. 

I can't move to OData V4 as it appears that SharePoint (or at least the Visual Studio External Content Type generator) can't cope with V4.

Cheers,
Chris

**Comment by pascalberger** [comment]
Unfortunately I cannot reopen this issue. I therefor opened a new issue asking for OData v3 support, since I also need it with v3. See https://github.com/OData/WebApi/issues/415
