### ISSUE TITLE
Using the default OData path handler and routing conventions disables navigation properties

### ISSUE THREAD

**Issue by mitselplik** [OData/WebApi#2164]
I'm not sure if this is a bug or simply my lack of understanding, but...
If the route builder is coded like this (note the commented out lines):
```cs-lang
app.UseMvc(routeBuilder =>
	{
		PropertyModelBuilder modelBuilder = new PropertyModelBuilder();

		routeBuilder.MapODataServiceRoute("PropertyODataRoutes", "odata",
			modelBuilder.GetEdmModel(app.ApplicationServices),
			//new DefaultODataPathHandler(),
			//ODataRoutingConventions.CreateDefault(),
			new TransactionedODataBatchHandler());
	});
```
then Urls like this work fine:  `~/odata/Account(12345)/PropertyOwner`  

The controller method for the above Url is defined as follows and is invoked:
```cs-lang
        [EnableQuery(PageSize = 100, MaxExpansionDepth = 5)]
        [ODataRoute("Account({key})/PropertyOwner")]
        public IQueryable<PropertyOwner> GetPropertyOwnersForAccount([FromODataUri] int key)
            => _context.PropertyOwner.Where(r => r.OwnerId == key);
```
If I uncomment the two lines in my routeBuilder however, the controller method is no longer invoked and a *404 Not Found* status is returned.

I wouldn't care and would simply leave the lines commented, but I am also attempting to add a custom routing convention to handle Urls like `~/odata/Account(12345)/PropertyOwner(2019)` (note the `key` and `relatedKey` fields.)

I was able to accomplish this by building a class that derives from `IOdataRoutingConvention`.  It works wonderfully for such routes if I include it in the routing conventions like so:
```cs-lang
		var routingConventions = ODataRoutingConventions.CreateDefault();
		routingConventions.Insert(0, new NavigationIndexRoutingConvention());

		routeBuilder.MapODataServiceRoute("NavigationIndexODataRoutes", "odata",
			modelBuilder.GetEdmModel(app.ApplicationServices),
			new DefaultODataPathHandler(),
			routingConventions,
			new TransactionedODataBatchHandler());
```

But as I said, this approach requires using the default OData routing conventions, which causes the issue of no navigation properties.  I _think_ this is because the default routing conventions don't include an attribute routing convention.  However, I cannot find any complete examples online of using `ODataRoutingConventions.CreateDefaultWithAttributeRouting(...)` that are current and don't leave little details out like how to create one without a route name :-)

**Comment by xuzhg** [comment]
@mitselplik

A example that you can refer to is at: https://github.com/OData/WebApi/blob/master/samples/AspNetCore3xEndpointSample.Web/Startup.cs#L64

Simple change "endpoints.ServiceProvider" as "routeBuilder.ServiceProvider". Let me know if it can't work.

**Comment by mitselplik** [comment]
@xuzhg My understanding from [this blog](https://devblogs.microsoft.com/odata/experimenting-with-odata-in-asp-net-core-3-1/) posted back in December was that OData doesn't support end-point routing yet and that routes still required configuration through UseMvc(...).  Is that no longer the case?

**Comment by xuzhg** [comment]
@mitselplik Endpoint routing is enabled in 7.4 version. Hassan also has a blog describing endpoint routing used in OData at https://devblogs.microsoft.com/odata/enabling-endpoint-routing-in-odata/

**Comment by mitselplik** [comment]
The endpoint routing code changes worked and allow me to inject my custom routing convention.  But I think I am either doing something wrong, or what I want to do is simply non-standard and not supported.

Basically, I am trying to get a URL like `~/Parent({key})/Children({relatedKey})` to work in a situation where the child class actually has a composite key, so that the Uri returns a sub-set of all the parent's children by partial key match, i.e., I am attempting to short-cut what can currently be returned using `~/odata/Parent({key})?$expand=Children($filter=Year eq 2019)`.

My latest attempt causes the following error "The path template 'Parent({key})/Children({keyYear})' on the action 'GetChildrenForYear' in controller 'Parent' is not a valid OData path template. The number of keys specified in the URI does not match number of key properties for the resource 'MyDbContext.Child'."

**Comment by xuzhg** [comment]
@mitselplik I am sorry I can't fully understand your problem? maybe it's better for us to help you if you can provide a repro, you can just create a repo on github with codes and share a link with me?

**Comment by mitselplik** [comment]
@xuzhg Sam think you so very much :-)  I have a completed sample project at https://github.com/mitselplik/widget-web-api
Please look for the "THIS DOESN'T WORK"comments in the controllers.

**Comment by xuzhg** [comment]
@mitselplik I took a look your repo, sorry for delay.

For the composite key, the template for it should be same as the function parameter.`key={key}`

So, I changed it as:
```C#
[ODataRoute("Supplier({keySupplierId})/Part(SupplierId={keySupplierId}, PartId={keyPartId})")]
```
It works.

**Comment by KenitoInc** [comment]
@mitselplik  I assume this question was resolved. Closing this issue
