### ISSUE TITLE
Same property exposed twice in complex type.

### ISSUE THREAD

**Issue by xuzhg** [OData/WebApi#217]
For example:

```C#

    [DataContract]
    public class People
    {
        [IgnoreDataMember]
        public decimal Height { get; set; }
    }

    [DataContract]
    public class Employee : People
    {
        [DataMember]
        public long Id { get; set; }

        [DataMember]
        public int Age { get; set; }
    }

 var builder = new ODataConventionModelBuilder();
 var employee = builder.ComplexType<Employee>();
 employee.Property(p => p.Age).IsOptional();
 employee.Property(p => p.Height).IsOptional();
```

Edm XML schema generated:

```xml
<ComplexType Name="Employee">
<Property Name="Age" Type="Edm.Int32"/>
<Property Name="Height" Type="Edm.Decimal"/>
<Property Name="Id" Type="Edm.Int64"/>
<Property Name="Height" Type="Edm.Decimal" Nullable="false"/>      2nd Height Property?
</ComplexType>
```
Two questions here:
1.Although Height is marked as an [IgnoredDataMember], why is it still exposed in the Edm schema in OData V4? (note that in OData V3 the Height property in this case won’t be exposed though marked as optional)

2. Both Age and Height are set as IsOptional() properties, but why is Height property being exposed twice? 

3. The same problem maybe exist in entity type.

**Comment by xuzhg** [comment]
It's the reason that the

```C# 
PropertyInfo
 ```
has the different value when access the same property from different class.

**Comment by Casimodo72** [comment]
@xuzhg,
this issue is not related to the PropertyInfo type, because in ODataConventionModelBuilder.MapStructuralProperty the property is looked up by its name.
Here the explicit property is set on the reflected property:
``` addedEdmProperty.AddedExplicitly = addedExplicitly; ```
This results in duplicate properties, plus conventions will *not* be applied to any of both properties. 
For me this behavior does not seem to make sense.

On the other hand, explicit navigation properties are overwriting reflected properties. In MapEntityType we have:
```c#
// don't add this property if the user has already added it.
if (!entity.NavigationProperties.Any(p => p.Name == property.Name))
```

In (https://github.com/OData/WebApi/issues/355) I have asked what ODataConventionModelBuilder is intended for. Does anyone actually know? Is there a design description?

Regards,
Kasimier Buchcik

**Comment by Casimodo72** [comment]
@VikingsFan,
in the other thread you write that fixing this bug could break other assumptions. Can you point me to those assumptions or tests?

**Comment by Casimodo72** [comment]
Please, can someone clarify why the machinery can't just *ignore* the duplicate reflected property as it does already with navigation properties. This would fix the bug.
@VikingsFan: the API will not break by fixing this. The *current* API is broken as it has public methods which produce this bug when being used. For Thor's sake, just *define* the ODataConventionModelBuilder's property methods as a way to *overwrite* reflected properties and you will heal the current API at least a bit and confuse the people out there a bit less.

**Comment by VikingsFan** [comment]
@Casimodo72: **This** issue is related to the PropertyInfo type, please check the content carefully.
And what you say about addedEdmProperty.AddedExplicitly is the issue that use ConventionModelBuilder and explicit declare key or navigation properties together.
Reopen #355

**Comment by xuzhg** [comment]
Merged. @Casimodo72, can you try it out and let us know nay issue. Thanks
