### ISSUE TITLE
Problem when generating OData nextlink skiptoken with date containing offset

### ISSUE THREAD

**Issue by YoannaAtanasova** [OData/WebApi#2177]
There is a problem when using Odata Web API with dates that are not in UTC time zone. When we get the first page of data there is a nextlink with skip token generated, like so:

"@odata.nextLink":"https://localhost:44331/odata/weatherforecast?$skiptoken=StartDate-2020-05-29T08:48:29.2464819+01:00"

This is problematic. because of the special characters like '+', that cannot be passed as a query string parameter. So when we use this link we get the following exception:

The query specified in the URI is not valid. The DateTimeOffset text '2020-05-29T08:48:29.2464819' should be in format 'yyyy-mm-ddThh:mm:ss('.'s+)?(zzzzzz)?' and each field value is within valid range.

For the generated nextlink to work the skip token must be encoded, like so:

"@odata.nextLink":"https://localhost:44331/odata/weatherforecast?$skiptoken=StartDate-2020-05-29T08%3A48%3A29.2464819%2B01%3A00"

For the purpose of reproducing the issue I have created a simple .Net Core 3.1 project, with the latest version of the library:
https://github.com/YoannaAtanasova/ODataOffsetProblemPOC

**Comment by xuzhg** [comment]
@YoannaAtanasova I remember it supports to customize the SkipToken through DI. See https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/Extensions/ContainerBuilderExtensions.cs#L54
Can you try it?

**Comment by YoannaAtanasova** [comment]
Hi @xuzhg ,

I don't need to customize the SkipToken.
I need the SkipToken values to be encoded as you do with the Filters values.

Otherwise the default SkipToken is useless when special characters are included.

I think it's a bug that need to be fixed.

Do you suggest me to try to find a workaround for the issue?

**Comment by YoannaAtanasova** [comment]
The issue is resolved with version 7.5
