### ISSUE TITLE
How to make automatic implement for querying a single property of an entity object?

### ISSUE THREAD

**Issue by anranruye** [OData/WebApi#2178]
In the part of OData Web API of book _Professional C#_, the author defines odata controllers, each controller have two Get methods to return entity collection and single entity, no other methods.The author introduces some queries like:
        ~/odata/books(1)/title
        ~/odata/books(1)/chapters
But when i run this sample project myself,these queries do not work.

I do know that i can create additional methods like GetTitle and GetChapters to make these queries work,but the book  _Professional C#_ doesn't mention this step absolutely.

Does the author omit these additional methods, or the old version of Microsoft.AspNetCore.OData just does not need these additional methods?And are there any approaches to make a default implement for querying a single property of an entity object? 

### Assemblies affected

The source code of  _Professional C# i download uses
      Microsoft.AspNetCore.OData 7.0.0-Nightly201802051329

**Comment by xuzhg** [comment]
@anranruye Would you please share the link for your repo? or the Book "Professional C#"?

At OData, by default you need a addition methods like "Get+PropertyName" to query a single property. For example, `~/odata/books(1)/title` needs a method named "GetTitle"

**Comment by anranruye** [comment]
@xuzhg Forget the book and let's just face the problem itself.
There seems to be no other solution than add additional methods like "GetTitle" and "GetChapters"?
And without these additional methods,I can only perform queries like:
~/odata/books(1)?$select=title,
~/odata/books(1)?$select=chapters&$expand=chapters,
~/odata/chapters?$filter=bookId eq 1
instead.
Is this right?
