### ISSUE TITLE
REOPEN: Publish symbols to Microsoft symbol server

### ISSUE THREAD

**Issue by garethj-msft** [OData/WebApi#2183]
The nuget symbol server is terminally unreliable - please publish to Microsoft symbol server instead.
This is a reopen of  #1595 
It also gives the strong impression that OData isn't a serious part of the Microsoft stack when it isn't part of the normal debugging set and you have to go to a different symbol server.

### Assemblies affected

All OData assemblies.

### Reproduce steps

Try to use symbols to debug or step source.  

### Expected result

Debugging works.
### Actual result

*What is actually happening.*

Persistent certificate or reliability problems mean debugging fails.

**Comment by xuzhg** [comment]
@garethj-msft Do you know any guide about how to push package to Microsoft Symbol server?

**Comment by xuzhg** [comment]
The symbols are published in the nuget server since 7.5. Please file new issue if you have other concerns.
