### ISSUE TITLE
$select and $expand does not for properties only in derived types, when the query options are allowed only on controller actions and not globally.

### ISSUE THREAD

**Issue by agrabhi** [OData/WebApi#2184]
'If query options is not enabled in webapi.config and enabled only in controller action. 
and if the derived type has navigational property which is not in base
then expand and select on derived type doesn't work. 

This works if the query options are enabled in webapicofig.cs. 
Showed the issue to SamXu

### Assemblies affected

Microsoft.AspNet.OData - 7.4.1.0

### Reproduce steps

Use the project here 
https://github.com/agrabhi/Samples/tree/expandrepro/IdentityProvidersModelling
build it 

and run the below url 
https://localhost:44391/odata/identity/userFlows/B2X_1_Partner?$expand=Microsoft.Graph.b2xIdentityUserFlow/identityProviders

Error is 
{
    "error": {
        "code": "",
        "message": "The query specified in the URI is not valid. The property 'identityProviders' cannot be used in the $expand query option.",
        "innererror": {
            "message": "The property 'identityProviders' cannot be used in the $expand query option.",
            "type": "Microsoft.OData.ODataException",
            "stacktrace": "   at Microsoft.AspNet.OData.Query.Validators.SelectExpandQueryValidator.ValidateRestrictions(Nullable`1 remainDepth, Int32 currentDepth, SelectExpandClause selectExpandClause, IEdmNavigationProperty navigationProperty, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.Validators.SelectExpandQueryValidator.Validate(SelectExpandQueryOption selectExpandQueryOption, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.SelectExpandQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ValidateQuery(HttpRequestMessage request, ODataQueryOptions queryOptions)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.<>c__DisplayClass0_0.<OnActionExecuted>b__1(ODataQueryContext queryContext)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)"
        }
    }
}

### Expected result

We'll get the data

### Actual result

Errror

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by nsunmaz** [comment]
I solved this problem by adding this code in Startup.cs;

```
app.UseMvc(routeBuilder =>
    {
        // and this line to enable OData query option, for example $filter
        routeBuilder.Select().Expand().Filter().OrderBy().MaxTop(100).Count();

        routeBuilder.MapODataServiceRoute("ODataRoute", "odata", builder.GetEdmModel());

        // uncomment the following line to Work-around for #1175 in beta1
        // routeBuilder.EnableDependencyInjection();
    });
```

now i use select with expand same time.

Other detail: https://docs.microsoft.com/tr-tr/odata/webapi/netcore

**Comment by drventure** [comment]
I'm seeing this same behavior. Looks like the Query Attributes only seem to work when applied at the CLASS level, not at the property level. The solution above does work, but basically it turns on ALL query options for ALL actions of ALL controllers, which is something that you might not want.

Still trying to figure out how to get the attrs to apply at the property level.

**Comment by gathogojr** [comment]
@agrabhi @necipsunmaz @drventure 

The `Select`, `Filter`, `OrderBy`, `Expand`, `Count`, `MaxTop` and `SkipToken` methods that are called from start-up code toggle `EnableSelect`, `EnableFilter`, `EnableOrderBy`, `EnableExpand`, `EnableCount`, `MaxTop`, and `EnableSkipToken` query options respectively **globally**.

They supersede other query option configuration that may be applied elsewhere across the application.

The `AllowedQueryOptions` property of `EnableQuery` attribute on the other hand is used to more granularly **limit** what query options may be applied to a particular executable endpoint.

The keyword here is **limit**. If `EnableSelect` query option is not enabled globally for example, the attribute,
```csharp
[EnableQuery(AllowedQueryOptions = AllowedQueryOptions.Select)]
```
will not have the effect of enabling `$select` query option on the executable endpoint it's applied to.
This is by current design and not a bug.

More granular control over query options can be achieved by applying query attributes on the models or by using the model builder API.

### Using model-bound attributes:
```csharp
[Select("Id", "Name", SelectType = SelectExpandType.Allowed)]
[Select("CreditLimit", SelectType = SelectExpandType.Disabled)]
[Filter("CreditLimit", Disabled = true)]
public class Customer
{
    public int Id { get; set; }
    public string Name { get; set; }
    public decimal CreditLimit { get; set; }
    public List<Order> Orders { get; set; }
}
```

To achieve the following outcomes:
- Allow `$select` on `Id` and `Name` properties - the default behaviour
- Disallow `$select` on `CreditLimit` property
- Disallow `$filter` on `CreditLimit` property

### Using model builder API:
```csharp
var modelBuilder = new ODataConventionModelBuilder();
var customerEntityTypeConfiguration = modelBuilder.EntitySet<Customer>("Customers").EntityType;
customerEntityTypeConfiguration.ContainsMany(d => d.Orders).NotExpandable = true;
```

To disable `$expand` on `Orders` navigation property.

### Further reading
- [Registering OData services](https://learn.microsoft.com/en-us/odata/webapi-8/fundamentals/query-options?tabs=net60#registering-odata-services)
- [Limiting query options](https://learn.microsoft.com/en-us/odata/webapi-8/fundamentals/query-options?tabs=net60#limiting-query-options)
- [Configured vs allowed query options](https://learn.microsoft.com/en-us/odata/webapi-8/fundamentals/query-options?tabs=net60#configured-vs-allowed-query-options)

**Comment by drventure** [comment]
Ahh.. Ok. Makes sense. 
Thanks for the explanation!
