### ISSUE TITLE
@odata.context for contained entities

### ISSUE THREAD

**Issue by NGromann** [OData/WebApi#2186]
Stated in [OData Version 4.0. Part 1: Protocol Plus Errata 03](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_Toc453752257) 10.2
`If the entities are contained, then entity-set is the top-level entity set followed by the path to the containment navigation property of the containing entity.`
But when I request a contained entity set, the `@odata.context` property does not show the top-level entity set. (See the example below)

### Assemblies affected

Microsoft.AspNetCore.OData 7.4.1

### Reproduce steps
Configuration
```c#
public void Configure(IApplicationBuilder app)
{
    var builder = new ODataConventionModelBuilder(app.ApplicationServices);

    builder.EntitySet<Cube>("Cubes");

    builder.EntitySet<Database>("Databases");

    app.UseMvc(routeBuilder =>
    {
        routeBuilder.Select().Expand(QueryOptionSetting.Allowed).Filter().OrderBy().MaxTop(null).Count();
        routeBuilder.MapODataServiceRoute("ODataRoute", "odata", builder.GetEdmModel());
    });
}
```
Models
```c#
public class Database
{
    public int ID { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Cube> Cubes { get; set; }
}

public class Cube
{
    public int ID { get; set; }
    public string Name { get; set; }
}
```
Api
```c#
[EnableQuery]
[ODataRoute("Databases({databaseId})/Cubes")]
public IQueryable<Cube> GetCubes(int databaseId)
{
    return databases.First(x => x.ID == databaseId).Cubes.AsQueryable();
}
```

### Expected result
The odata context should show the Database set.
`odata/$metadata#Databases(1)/Cubes`
```
GET http://localhost:9721/odata/Databases(1)/Cubes

{
    "@odata.context": "http://localhost:9721/odata/$metadata#Databases(1)/Cubes",
    "value": [
        {
            "ID": 1,
            "Name": "Sales"
        }
    ]
}
```

### Actual result
Instead it only shows the contained cube set.
`odata/$metadata#Cubes`
```
GET http://localhost:9721/odata/Databases(1)/Cubes

{
    "@odata.context": "http://localhost:9721/odata/$metadata#Cubes",
    "value": [
        {
            "ID": 1,
            "Name": "Sales"
        }
    ]
}
```

**Comment by marabooy** [comment]
@NGromann  A contained navigation in this case would only exist in the collection of the parent and can only be accessed through the parent.

In your case the model you have built doesn't describe containment. In order to fix it you would need to 
1. remove cube from the model description 

```csharp
  var builder = new ODataConventionModelBuilder(app.ApplicationServices);
   // builder.EntitySet<Cube>("Cubes");  remove this line
    builder.EntitySet<Database>("Databases");
```
2. Add the contained Attribute to the property that defines the relationship
```csharp
public class Database
{
// removed for brevity
    [Contained]
    public virtual ICollection<Cube> Cubes { get; set; }
}
```
Kindly do check [this tutorial ](https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/odata-containment-in-web-api-22)out which shows how to implement containment in OData WebApi
