### ISSUE TITLE
Consider supporting parsing and generating key values in KeyValuePathSegment

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#22]
So user doesn't need to call ODataUriUtils.ConvertToUriLiteral or
ODataUriUtils.ConvertFromUriLiteral to parse the id by himself.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 674](http://aspnetwebstack.codeplex.com/workitem/674)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Dec 5, 2012 at 2:26 AM
**Reported by:**	hongyes
**Updated on:**	Sep 23, 2013 at 7:31 PM
**Updated by:**	danroth27

**Comment by LianwMS** [comment]
On *2012-12-07 07:42:04 UTC*, **HongmeiG** commented:

Change the Value property to RawValue on KeyValuePathSegment. 

We can add ReadAs<guid>() to parse the key to guid. 
ReadAsKey<guid>(myGuidKey); 

Write<guid>(guidKey); 
Write(dictionary<string, object>)

**Comment by LianwMS** [comment]
On *2013-04-02 05:47:44 UTC*, **HongmeiG** commented:

This will be useful to generate the link according to the OData format. 

The ReadAsKey will be useful on the client side or in the unit tests.

**Comment by xuzhg** [comment]
Follow： https://github.com/OData/WebApi/pull/727

**Comment by xuzhg** [comment]
Modified at commit at 4e23aabcf9a171a844bd11f1882bf1038cb4a3b8, thanks.
