### ISSUE TITLE
Issue with long query string

### ISSUE THREAD

**Issue by pashokchakravarthi** [OData/WebApi#2204]
**Issue:** We prepare odata query string based on user's  column & filter section and make API call to fetch data. Due to query string length limitation of HTTP Get request, some times we are unable to get data from API.
As a workaround, we are trying to make POST request and setting odata Query params in action method(before any odata code executed by EnableQuery action filter) : 
_HttpContext.Request.QueryString = new QueryString("?"+Model.ODataQuery);_
For some reason, this doesnt seem to work. 

_Is there any way to solve this issue? 
Do we need to change any other HttpRequest model properties to make this approach work?_

**Comment by mikepizzo** [comment]
Hi @pashokchakravarthi --

HTTP does not specify a maximum length for a URL, however, web services (like IIS) may impose max limits on a URL length.  If you own the service you are calling, you may be able to se the URL length to a larger value to accommodate larger URLs.

Historically, folks have worked around the long URL problem by creating single-statement batch requests.  With batch requests, the actual URL is in the body, so it is not subject to URL length constraints. 

Not that there is overhead associated with wrapping and unwrapping each request within the $batch, so in OData 4.01 we added a pattern for handling long URLs by [passing the query options in the request body](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_PassingQueryOptionsintheRequestBody) (similar to what you suggest above).  We have an [implementation of this](#2191) in our OData WebAPI stack, but it is not yet checked in. 

If you can wait for the upcoming release that incorporates #2191, then that will be your best bet. In the meantime, the best way to support this in the current stack is through a single-valued batch request.
