### ISSUE TITLE
OData Web API v 5.4 doesnot support DateTime completely

### ISSUE THREAD

**Issue by mkothari1123** [OData/WebApi#221]
In 5.4 version of OData Web API, the DateTime support is not complete. Its able to return data with DateTime fields but doesnot support OData clauses for filter & orderby when used with DateTime fields.
For e.g. This url: http://localhost:5011/user-timesheet-service/Timesheet?$filter=TimePeriodEndDate%20eq%20cast(2015-02-15T00:00:00%2B00:00,Edm.DateTimeOffset)
results in this error:
"The query specified in the URI is not valid. The binary operator Equal is not defined for the types 'System.Nullable`1[System.DateTime]' and 'System.Nullable`1[System.DateTimeOffset]'.\",\"innererror\":{\r\n      \"message\":\"The binary operator Equal is not defined for the types 'System.Nullable`1[System.DateTime]' and 'System.Nullable`1[System.DateTimeOffset]' 

This fix doesn't really do much good. There is this fork (https://aspnetwebstack.codeplex.com/SourceControl/network/forks/_kj_/odata53datetime?branch=odata-v5.3-rtm) which supports DateTime for all the cases. Can you model the solution as per this and release a new version please.

Thanks!

**Comment by xuzhg** [comment]
Both are using mapping between DateTime & DateTimeOffset. However, we do consider the Time Zone information. 
For filter & orderby, we will fix it soon.

**Comment by mkothari1123** [comment]
Any tentative date for 5.5 release? I have been earlier waiting for 5.4 hoping it will fix DateTime but with the filter & orderby limitation its of not much help. Appreciate if you can add this support asap.
If you see below fork, it does support filter clause:
https://aspnetwebstack.codeplex.com/SourceControl/network/forks/_kj_/odata53datetime?branch=odata-v5.3-rtm)

Thanks

**Comment by mkothari1123** [comment]
Any tentative date for 5.5 release? I have been earlier waiting for 5.4 hoping it will fix DateTime but with the filter & orderby limitation its of not much help. Appreciate if you can add this support asap.
If you see below fork, it does support filter clause:
https://aspnetwebstack.codeplex.com/SourceControl/network/forks/_kj_/odata53datetime?branch=odata-v5.3-rtm)

Thanks

**Comment by xuzhg** [comment]
@mkothari1123  Would you please try the new checked in? You can get the package from nightly build.
https://www.myget.org/F/aspnetwebstacknightly/
Thanks.

**Comment by xuzhg** [comment]
Please re-active it if you have any more concern. Thanks.

**Comment by xuzhg** [comment]
Please re-active it if you have any more concern. Thanks.

**Comment by mkothari1123** [comment]
I tested the 16th Feb nightly build and the issue still persist. If I query with this url:
http://localhost:5011/user-timesheet-service/Timesheet?$filter=TimePeriodEndDate%20eq%20cast(2015-02-15T00:00:00%2B00:00,Edm.DateTimeOffset), 
I get this error:
"message":"The query specified in the URI is not valid. The binary operator Equal is not defined for the types 'System.Nullable`1[System.DateTime]' and 'System.Nullable`1[System.DateTimeOffset]'."

**Comment by daw451-duplicate** [comment]
WHAT IS THE STATUS OF THIS? WHERE CAN WE GET 5.4.1? HAVING DATETIME FILTER ISSUES ON 5.4.0...
http://localhost:2011/odata/Messages?$count=true&$filter=messageSender eq 'e308601e-be91-4839-9d96-1232b2e02e6b' and messageType eq 'NewRx' and messageDate le datetimeoffset'2015-03-24T04:00:00.000Z'&$orderby=messageDate desc

TRIED WITH JUST DATETIME AS WELL...NO GO....

**Comment by lothargrieb** [comment]
Can anyone from Microsoft explain me, why it is so complicated to make this very important and 100% essential DateTime compatibility in all cases, like quering, selecting ($select), filtering($filter), and sorting ($orderby) running? There are many and many huge projects which wants to be extended to use modern odata v4 technology.

**Comment by congysu** [comment]
The change here has issue with EF.  A later change is at https://github.com/OData/WebApi/commit/073f8818cb18f6f618d6637c257f48f501aa6c4c.
