### ISSUE TITLE
Expand Base property

### ISSUE THREAD

**Issue by eduardoxvii** [OData/WebApi#2213]
I can't expand property in base class.

**Assemblies affected**
Microsoft.AspNetCore.OData 7.4.1

```C#
public class StreetAddress
{
public int Id { get; set; }
public string Street { get; set; }
public string City { get; set; }
}

public class Order
{
    public int Id { get; set; }
    public string Description { get; set; }
}

public abstract class Place
{
public int Id { get; set; }
public string Name { get; set; }
public StreetAddress ShippingAddress { get; set; }
}

public class School : Place
{
public Order Order { get; set; }
}
```
**Reproduce steps**
I made these requists: 
**http://localhost:5000/School?$expand=Order** **(Working)**
**http://localhost:5000/School?$select=Name** **(Working)**
But
**http://localhost:5000/School?$expand=ShippingAddress**  **(Not Working)**

**Actual result**

EF.Property called with wrong property name.

**Comment by gathogojr** [comment]
@eduardoxvii `$expand` is only applicable to navigation property (comprising entity or entity collection). `ShippingAddress` in your example is a complex type. It should be included in the default response

**Comment by eduardoxvii** [comment]
> @eduardoxvii `$expand` is only applicable to navigation properties (comprising entity or entity collection). `ShippingAddress` in your example is a complex type. It should be included in the default response

Are you saying that 'ShippingAddress' is a complex class because I forgot to put the id property?
How could I include 'ShippingAddress' in the default response?

**Comment by gathogojr** [comment]
@eduardoxvii If `ShippingAddress` is an entity type as per your latest code sample, then `$expand` should work on that as well.
I just fired up a quick repro mirroring your exact scenario above and I'm able to expand `ShippingAddress`:

Request: `http://localhost:28541/odata/School?$expand=ShippingAddress`
Response:
```json
{
  "@odata.context": "http://ServiceRoot/$metadata#School(ShippingAddress())",
  "value": [
    {
      "Id": 1,
      "Name": "School 1",
      "ShippingAddress": {
        "Id": 1,
        "Street": "Street 1",
        "City": "City 1"
      }
    }
  ]
}
```
Are you using conventional model builder? Can you share the model builder snippet? Here's the model builder code for the repro that produced the output above:
```c#
var modelBuilder = new ODataConventionModelBuilder();
modelBuilder.EntitySet<School>("School");
```
Here's the metadata:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
   <edmx:DataServices>
      <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="NS.Models">
         <EntityType Name="School">
            <Key>
               <PropertyRef Name="Id" />
            </Key>
            <Property Name="Id" Type="Edm.Int32" Nullable="false" />
            <Property Name="Name" Type="Edm.String" />
            <NavigationProperty Name="Order" Type="NS.Models.Order" />
            <NavigationProperty Name="ShippingAddress" Type="NS.Models.StreetAddress" />
         </EntityType>
         <EntityType Name="Order">
            <Key>
               <PropertyRef Name="Id" />
            </Key>
            <Property Name="Id" Type="Edm.Int32" Nullable="false" />
            <Property Name="Description" Type="Edm.String" />
         </EntityType>
         <EntityType Name="StreetAddress">
            <Key>
               <PropertyRef Name="Id" />
            </Key>
            <Property Name="Id" Type="Edm.Int32" Nullable="false" />
            <Property Name="Street" Type="Edm.String" />
            <Property Name="City" Type="Edm.String" />
         </EntityType>
      </Schema>
      <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Default">
         <EntityContainer Name="Container">
            <EntitySet Name="School" EntityType="NS.Models.School" />
         </EntityContainer>
      </Schema>
   </edmx:DataServices>
</edmx:Edmx>="StreetAddress">
<Key>
<PropertyRef Name="Id"/>
</Key>
<Property Name="Id" Type="Edm.Int32" Nullable="false"/>
<Property Name="Street" Type="Edm.String"/>
<Property Name="City" Type="Edm.String"/>
</EntityType>
</Schema>
<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Default">
<EntityContainer Name="Container">
<EntitySet Name="School" EntityType="NS.Models.School"/>
</EntityContainer>
</Schema>
</edmx:DataServices>
</edmx:Edmx>
```

**Comment by eduardoxvii** [comment]
> 
> Are you using conventional model builder? Can you share the model builder snippet? 
> ```
Gathogojr, I'm using enpoint:
```
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.EnableDependencyInjection();
                endpoints.Select().Filter().Expand().Count().MaxTop(10);
            });
```

**Comment by gathogojr** [comment]
@eduardoxvii Using endpoint routing doesn't stop you from using the model builder, unless you want to go for a Non-Edm Approach. Either way, here's a resource on using endpoint routing in OData that covers both the Edm and Non-Edm approach https://devblogs.microsoft.com/odata/enabling-endpoint-routing-in-odata/

I have also gone ahead and pushed a repro I used to verify that `$expand` works for both Edm and Non-Edm approaches https://github.com/gathogojr/ODataWebApiIssue2213Repro

Note that in the repro I'm returning `IQueryable` and I'm not having to add `.Include()` in the query. In short, it's not an issue with `ShippingAddress` belonging to the base class.
I hope this helps.

**Comment by gathogojr** [comment]
Closing issue after sharing repro confirming $expand works on a base type navigation property for both Edm and Non-Edm OData service.
@eduardoxvii Feel free to reopen the issue if there's any angle that was not covered

**Comment by vbray1979** [comment]
Hi, I am experiencing the same issue describe in test IV by @eduardoxvii using EF Core 3.1.5 and AspNetCore.OData 7.4.1
How did you managed to solve it or workaround it?

**Comment by gathogojr** [comment]
@vbray1979 I only went as far as demonstrating that there's no issue with `$expand` when applied to a navigation property inherited from the base class. As for invalid query being generated when you use `.Include()`, could you kindly report the issue with [EF Core](https://github.com/dotnet/efcore/issues)

**Comment by vbray1979** [comment]
Done under https://github.com/dotnet/efcore/issues/21546#issue-652321327

**Comment by eduardoxvii** [comment]
gathogojr, I managed to reproduce the error in your project! In my project it never works, but yours insisted on working! So far!

**Comment by vbray1979** [comment]
> @eduardoxvii If `ShippingAddress` is an entity type as per your latest code sample, then `$expand` should work on that as well.
> I just fired up a quick repro mirroring your exact scenario above and I'm able to expand `ShippingAddress`:
> 
> Request: `http://localhost:28541/odata/School?$expand=ShippingAddress`
> Response:
> 
> ```json
> {
>   "@odata.context": "http://ServiceRoot/$metadata#School(ShippingAddress())",
>   "value": [
>     {
>       "Id": 1,
>       "Name": "School 1",
>       "ShippingAddress": {
>         "Id": 1,
>         "Street": "Street 1",
>         "City": "City 1"
>       }
>     }
>   ]
> }
> ```
> 
> Are you using conventional model builder? Can you share the model builder snippet? Here's the model builder code for the repro that produced the output above:
> 
> ```cs
> var modelBuilder = new ODataConventionModelBuilder();
> modelBuilder.EntitySet<School>("School");
> ```
> 
> Here's the metadata:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
>    <edmx:DataServices>
>       <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="NS.Models">
>          <EntityType Name="School">
>             <Key>
>                <PropertyRef Name="Id" />
>             </Key>
>             <Property Name="Id" Type="Edm.Int32" Nullable="false" />
>             <Property Name="Name" Type="Edm.String" />
>             <NavigationProperty Name="Order" Type="NS.Models.Order" />
>             <NavigationProperty Name="ShippingAddress" Type="NS.Models.StreetAddress" />
>          </EntityType>
>          <EntityType Name="Order">
>             <Key>
>                <PropertyRef Name="Id" />
>             </Key>
>             <Property Name="Id" Type="Edm.Int32" Nullable="false" />
>             <Property Name="Description" Type="Edm.String" />
>          </EntityType>
>          <EntityType Name="StreetAddress">
>             <Key>
>                <PropertyRef Name="Id" />
>             </Key>
>             <Property Name="Id" Type="Edm.Int32" Nullable="false" />
>             <Property Name="Street" Type="Edm.String" />
>             <Property Name="City" Type="Edm.String" />
>          </EntityType>
>       </Schema>
>       <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Default">
>          <EntityContainer Name="Container">
>             <EntitySet Name="School" EntityType="NS.Models.School" />
>          </EntityContainer>
>       </Schema>
>    </edmx:DataServices>
> </edmx:Edmx>
> ```

I just realised that your metadata does not include any basetype property but instead bring back the base navigation property to the derived object... There must be some configuration difference. Here is my definition..

```
 [Table("Asset", Schema = "Asset")]
    public class AssetModel : IInsertable, IUpdatable
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid AssetId { get; set; }

        [Required]
        public string AssetSymbol { get; set; }

        [Required]
        [ForeignKey("AssetType")]
        public Guid AssetTypeId { get; set; }

        public virtual AssetTypeModel AssetType { get; set; }
```
```
 public class FinancialAssetModel : AssetModel
    {
        public string Ticker { get; set; }
```
and the related metadata

```
<EntityType Name="AssetModel">
<Key>
<PropertyRef Name="assetId" />
</Key>
...
<NavigationProperty Name="assetType" Type="AMI.AssetTypeModel">
     <ReferentialConstraint Property="assetTypeId" ReferencedProperty="assetTypeId" />
</NavigationProperty>
</EntityType>

<EntityType Name="FinancialAssetModel" BaseType="AMI.AssetModel">
<Property Name="ticker" Type="Edm.String" />
</EntityType>
```
and my configuration

` var Assets = builder.EntitySet<AssetModel>("Assets").EntityType.HasKey(x => x.AssetId);`

**Comment by eduardoxvii** [comment]
I found a second situation capable of break the expand (http://localhost:28541/school?$expand=StreetAddress):
**SITUATION I**
```
    public class School : Place
    {
        public Place Branch { get; set; } <-- Break expand
    }
```
**SITUATION II**
```
    public abstract class Physicist : Place
    {
        public Company Branch { get; set; }
        public List<Physicist> Sectors { get; set; } <-- Break expand
    }
    public class School : Physicist
    {
        public Order Order { get; set; }
    }
```

**Comment by vbray1979** [comment]
Dear @gathogojr, based on @eduardoxvii finding plus the fact the issue we face is replicable by adding the base class entityset,
`modelBuilder.EntitySet<Place>("Place").EntityType.HasKey(x => x.Id);`
and querying the base navigation property like this 
`http://localhost:28541/School?$expand=ShippingAddress`
give the folowing error message:
`System.InvalidOperationException: EF.Property called with wrong property name.`

We need more explanation:
 -Option 1: This is a bug at odata level as it seems to be working fine when declaring **only** the derived entity
 -Option 2: Provide a odata query to get the base entity from the derived entity, if we should not define the base entity but only the derived
 -Option 3: Provide working sample declaring the base plus derived entity allowing to query the base navigation property from the derived one

Thank you for your help

**Comment by gathogojr** [comment]
@eduardoxvii @vbray1979 I'm reopening the issue. I'm a bit slammed at the moment but I plan to find time this week to revisit it. Thank for the above feedback. I'll take it into consideration

**Comment by vbray1979** [comment]
Hi I managed to get it working using EF Core 5.0.0-preview.6.20312.4. This is indeed an EF issues resolved in future version 5.
Can be closed on my side.

**Comment by eduardoxvii** [comment]
All the situations previously mentioned by me were solved in this version that @vbray1979 mentioned!
Thanks, @vbray1979!
Can I migrate my entire real project to this preview version?

**Comment by Sreejithpin** [comment]
Can be closed as you could get it working
