### ISSUE TITLE
isof/cast/any not working as expected against my returned collection in my scenario

### ISSUE THREAD

**Issue by drozee** [OData/WebApi#2227]
I currently have a controller with a singleton container object from which I return a collection that is a property on the singleton container object.  The collection has a base type with various subtypes against which I want to filter for various subtypes.  When I attempt to use the filter lambdas or operators such as isof/cast/any I am getting various errors.

#region Assembly Microsoft.AspNetCore.OData, Version=7.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
*Which assemblies and versions are known to be affected e.g. OData WebApi lib 6.1.0

My Controller:

`namespace Microsoft.Online.IntelligentUpdate.Service.Controllers
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Core.Datamodel.Common;
using Core.Telemetry.Interfaces;
using Core.Wrappers;
using Microsoft.AspNet.OData.Query;
using Microsoft.AspNet.OData.Routing;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Online.IntelligentUpdate.Service.ControllerLogic;
using Microsoft.Wufb.Deployments; 

public class ApprovalCatalogController : ODataControllerBase
{
  private readonly IApprovalCatalogControllerLogic approvalCatalogControllerLogic; 
static ApprovalCatalogController(){InitData();} 

public ApprovalCatalogController(ICosmosDBWrapper dbWrapper,ILogger logger,IRequestContext webContext,IApprovalCatalogControllerLogic approvalCatalogControllerLogic): base(dbWrapper, logger, webContext)

{
this.approvalCatalogControllerLogic = approvalCatalogControllerLogic;} 
public static ApprovalCatalog ApprovalCatalog { get; private set; } 

[ODataRoute("ApprovalCatalog/Entries")]
public async Task<IActionResult> GetApprovalCatalogEntries(ODataQueryOptions<ApprovalCatalogEntry> queryOptions){this.Logger.LogInfo($"GetApprovalCatalogEntries invoked: {queryOptions.Request.QueryString}"); List<ApprovalCatalogEntry> entries = await this.approvalCatalogControllerLogic.GetApprovalCatalogEntriesAsync(); this.Logger.LogInfo($"Retrieved {entries.Count}"); IQueryable queryable = null; try{queryable = queryOptions.ApplyTo(entries.AsQueryable());}catch (Exception ex){this.Logger.LogInfo($"Error {ex.ToString()}");throw;} return new OkObjectResult(queryable);} private static void InitData(){ApprovalCatalog = new ApprovalCatalog(){Id = "1",Entries = new List<ApprovalCatalogEntry>(),};}}}
`
The query string:

http://localhost:8230/v2/ApprovalCatalog/Entries?$filter=any(d:isof(d, QualityUpdateCatalogEntry))

It filters based on the subtype

*What would happen if there wasn't a bug.*

various errors such as COR_E_INVALIDOPERATION - "Could not find a property named 'ApprovalCatalogEntry' on type ApprovalCatalogEntry'."

Not sure why it looks for property on the collection type

*What is actually happening.*

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by gathogojr** [comment]
@drozee This should work:
```
/ApprovalCatalog/Entries?$filter=isof('NS.QualityUpdateCatalogEntry')
```
You need to specify the type by its fullname, i.e., `<Namespace>.QualityUpdateCatalogEntry` for example
