### ISSUE TITLE
ODataConventionModelBuilder shows metadata for some models but ignores others

### ISSUE THREAD

**Issue by Alfetta159** [OData/WebApi#2228]
When using the `GetEdmModel` method from the `ODataConventionModelBuilder`, some models that I add as an `EntitySet` return the correct metadata in their response and others don't.

### Assemblies affected

Microsoft.AspNetCore.OData, Version=7.4.1.0

### Reproduce steps

1. Create an OData API
2. Inject code to generate the EDM Model:
```
	app.UseMvc(routeBuilder =>
	{
		routeBuilder.Select().Expand().Filter().OrderBy().MaxTop(100).Count();
		routeBuilder.EnableDependencyInjection();
		var check = routeBuilder.MapODataServiceRoute("odata", "odata", GetEdmModel(), new DefaultODataPathHandler(), conventions);
		System.Diagnostics.Debug.WriteLine(check.Name);
	});
```
```
	private static IEdmModel GetEdmModel()
	{
		var builder = new ODataConventionModelBuilder();

		builder.EntitySet<Edi846PromiseDate>("Edi846PromiseDates");
		builder.EntitySet<Book>("Books");

		return builder.GetEdmModel();
	}
```
3. Use two models:

```
    public partial class Edi846PromiseDate
    {
        [Key]
        public string SystemId { get; set; }
    }
```
```
    public class Book
    {
        public int Id { get; set; }
        public string ISBN { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public decimal Price { get; set; }
 }
```

### Expected result

Both endpoints that respectively return responses for those models should have metadata.

_**or**_

The result of the `GetEdmModel` should contain metadata indicating why it can't assimilate/parse the model to present metadata for that endpoint.

### Actual result

Only the books endpoint shows metadata.

### Additional detail

I'm not sure this is a bug so much as I'm not sure how to interpret why the convention builder cannot create metadata for the `Edi846PromiseData` model.

**Comment by xuzhg** [comment]
@Alfetta159 What do you mean "Only the books endpoint shows metadata"?  can you share more about the "endpoint".

I use your CLR model and your convention model codes, it shows me the follow metadata:

```xml
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="AspNetCore3xEndpointSample.Web" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityType Name="Edi846PromiseDate">
                <Key>
                    <PropertyRef Name="SystemId" />
                </Key>
                <Property Name="SystemId" Type="Edm.String" Nullable="false" />
            </EntityType>
            <EntityType Name="Book">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int32" Nullable="false" />
                <Property Name="ISBN" Type="Edm.String" />
                <Property Name="Title" Type="Edm.String" />
                <Property Name="Author" Type="Edm.String" />
                <Property Name="Price" Type="Edm.Decimal" Nullable="false" />
            </EntityType>
        </Schema>
        <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityContainer Name="Container">
                <EntitySet Name="Edi846PromiseDates" EntityType="AspNetCore3xEndpointSample.Web.Edi846PromiseDate" />
                <EntitySet Name="Books" EntityType="AspNetCore3xEndpointSample.Web.Book" />
            </EntityContainer>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>
```

**Comment by Alfetta159** [comment]
{baseUrl}/odata/($metadata) yields:

```
{
    "@odata.context": "http://localhost:44390/odata/$metadata",
    "value": [
        {
            "name": "Edi846PromiseDates",
            "kind": "EntitySet",
            "url": "Edi846PromiseDates"
        },
        {
            "name": "Books",
            "kind": "EntitySet",
            "url": "Books"
        }
    ]
}
```
{baseUrl}/odata/Books yields:
```
{
    "@odata.context": "http://localhost:44390/odata/$metadata#Books",
    "value": [
        {
            "Id": 0,
            "ISBN": null,
            "Title": null,
            "Author": null,
            "Price": 0,
            "Location": null
        }
    ],
    "@odata.nextLink": "http://localhost:44390/odata/Books?$skip=1"
}
```
{baseUrl}/odata/Edi846PromiseDates?$top=10 yields: (no `@odata.context`)
```
[
    {
        "systemId": "Meyer"
    },
    {
        "systemId": "Meyer"
    },
    {
        "systemId": "Meyer"
    },
    {
        "systemId": "Meyer"
    },
    {
        "systemId": "Meyer"
    },
    {
        "systemId": "Meyer"
    },
    {
        "systemId": "Meyer"
    },
    {
        "systemId": "Meyer"
    },
    {
        "systemId": "Meyer"
    },
    {
        "systemId": "Meyer"
    }
]
```

What happens is that if I try to import this into something like PowerBI, PowerBI understands the Odata feed and its entities. It also understands the books entity, but it can't understand the Promise Dates entity as there is no metadata when looking at the result of that endpoint.

**Comment by xuzhg** [comment]
@Alfetta159 Can you share your repro?

**Comment by Alfetta159** [comment]
Enjoy,

https://github.com/Alfetta159/OdataTestSample

**Comment by xuzhg** [comment]
@Alfetta159 I can't run it since the installed .NET SDK. 
But, i think it should work if you remove "[Route("odata/[controller]")]" in `Edi846PromiseDatesController`. 
Would you please try and let me know the result?

**Comment by Alfetta159** [comment]
Initially, that seems to fix the issue. I'm surprised because while the model I'm using is generated directly from the database with Entity Framework, I still have to add `[Key]` attributes to the model class definitions because I was getting an exception stating that the model types that I was using as a type parameter for the `EntitySet` method on the `ODataConventionModelBuilder` instance didn't have keys.

However, I'm suddenly getting a 404 when I look at the base url, so I've traded one issue for another. I have to step away from this for now, so I'll try to update this later, but feel free to close this.

Thank you very much.

**Comment by xuzhg** [comment]
@Alfetta159 Thanks for updating. Feel free to file new issue if you meet new problem. Thanks.
