### ISSUE TITLE
FromODataUri attribute not work for string parameter

### ISSUE THREAD

**Issue by karataliu** [OData/WebApi#223]
For bound function with string parameter, the string parameter passed from Uri could would become null in controller.

 [HttpGet]
public IHttpActionResult SomeFunc([FromODataUri]string tags)
...

query: Set/TestNS.SomeFunc(tags='abc')
result: tags=null

query: Set/TestNS.SomeFunc(tags='123')
result: tags=123

**Comment by Jerther** [comment]
See also this SO answer:
http://stackoverflow.com/a/28440340/2498426

**Comment by xuzhg** [comment]
@Jerther Thanks your comments.
Adding attribute routing can solve the problem as the work around. However, The problem is for the convention routing, It still need to fix it.

**Comment by xuzhg** [comment]
String parameter for convention routing with FromODataUriAttribute is working now. Thanks.

**Comment by Jerther** [comment]
Alright thanks!
