### ISSUE TITLE
Deltas do not bind to non string values

### ISSUE THREAD

**Issue by JamesBarea** [OData/WebApi#2241]
I have been attempting to set up a REST API with GET, POST, PUT, PATCH methods. 
Everything works fine apart from the PATCH method Where I am accepting Delta<Class>.
Bool values will bind if I don't wrap them in strings and I can't get Guids to bind at all.

### Assemblies affected
AspNetCore 3.1
Microsoft.AspNetCore.OData/7.4.1

### Reproduce steps

- Set up new dot net Core 3.1 Project
- Install OData 7.4.1
- Install Microsoft.AspNetCore.Mvc.NewtonsoftJson (Deltas won't bind any property without)
- Add Minimum OData Configuration to Startup.cs
- Create ExampleClass with multiple data types
- Create Patch method with Delta<ExampleClass>
- Send Patch request

### Expected result

{
    "ExampleId": "ca830c8b-5832-428e-b6ca-690403676c7a",
    "ExampleString": "Testing",
    "ExampleBool": "true"
}
From the above all data types to bind successfully (Guid, String, bool)

### Actual result

ExampleString is the only property that binds which can be seen from:
DeltaParameter.GetChangedPropertyNames().ToList();

### Additional detail

Similarly described Issue here: https://github.com/OData/WebApi/issues/2115  (Although I have no Issue with PUT)

Attached minimal reproduction of the issue
[CorePatchIssue.zip](https://github.com/OData/WebApi/files/5015487/CorePatchIssue.zip)

**Comment by gathogojr** [comment]
@JamesBarea Kindly explain what you mean by this statement 

> Install Microsoft.AspNetCore.Mvc.NewtonsoftJson (Deltas won't bind any property without)

I'm not aware of NewtonsoftJson as a dependency for PATCH to work.
I did try to create a repro mirroring your scenario (but without NewtonsoftJson dependency) and everything appeared to work as expected...

**Model**
```c#
public class Example
{
    [Key]
    public Guid GuidField { get; set; }
    public string StringField { get; set; }
    public bool BooleanField { get; set; }
}
```
**Startup class**
```c#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc(
            options => options.EnableEndpointRouting = false).SetCompatibilityVersion(CompatibilityVersion.Version_3_0);
        services.AddOData();
    }

    public void Configure(IApplicationBuilder app)
    {
        ODataModelBuilder modelBuilder = new ODataConventionModelBuilder();
        modelBuilder.EntitySet<Example>("Examples");

        app.UseMvc(routeBuilder =>
        {
            routeBuilder.Select().Filter().Expand().Count().OrderBy().SkipToken().MaxTop(100);
            routeBuilder.MapODataServiceRoute("odata", "odata", modelBuilder.GetEdmModel());
            routeBuilder.EnableDependencyInjection();
        });
    }    
}
```
**Controller**
```c#
public class ExamplesController : ODataController
{
    public IActionResult Put([FromODataUri] Guid key, [FromBody] Example example)
    {
        if (!ModelState.IsValid)
            return BadRequest(ModelState);
        // ...

        return Ok();
    }

    public IActionResult Patch([FromODataUri] Guid key, [FromBody] Delta<Example> delta)
    {
        if (!ModelState.IsValid)
            return BadRequest(ModelState);

        var changedProperties = delta.GetChangedPropertyNames();
        // ...

        return Ok();
    }
}
```
**Request**
```
http://ServiceRoot/Examples(00000000-0000-0000-0000-000000000000)

{
    "GuidField": "00000000-0000-0000-0000-000000000000",
    "StringField": "Hello World!",
    "BooleanField": "true"
}
```
**Screen grab of Patch method**

![image](https://user-images.githubusercontent.com/28291332/89329079-ff9ae080-d696-11ea-9c4e-ac23ed977333.png)

So I downloaded the zipped project that you shared and after making a few changes I was able to achieve the same...

**Screen grab of modified Patch method from the project you shared**

![image](https://user-images.githubusercontent.com/28291332/89330854-82bd3600-d699-11ea-8744-431ebfe595ee.png)

**Request:**
```
http://localhost:8965/odata/Example(00000000-0000-0000-0000-000000000000)

{
    "ExampleId": "00000000-0000-0000-0000-000000000000",
    "ExampleString": "Hello World!",
    "ExampleBool": "true"
}
```

Here's some feedback that you might find useful:
- NewtonsoftJson is not required for PATCH functionality to work.
- In the `Patch` method, the value for the key property should be passed from the Uri, not delta. You can't practically patch the key field.
- If you choose to go with endpoint routing, there's no need to have both `UseMvc()` and `UseEndpoints()`. When using endpoint routing, you can call `MapODataRoute()` to achieve the same goal that `MapODataServiceRoute()` does.  Here's a good resource on using endpoint routing in OData https://devblogs.microsoft.com/odata/enabling-endpoint-routing-in-odata/
- Ideally, you should pass a boolean value for boolean properties, i.e., `true` instead of `"true"`.

Here is your modified project:
[CorePatchIssue.zip](https://github.com/OData/WebApi/files/5023955/CorePatchIssue.zip)

**Comment by gathogojr** [comment]
@JamesBarea Kindly let me know if the response I provided above addressed your issue. I'll proceed and close the issue for now. Feel free to reopen if necessary

**Comment by JamesBarea** [comment]
@gathogojr  Thanks for getting back to me, Sorry I missed your first message.
To answer your first question about NewtonsoftJson, I was finding that with .AddNewtonsoftJson() in my Startup.cs - my boolean and string values would at least bind to the Delta, without it - no data types would.

Thank you for your feedback, the MapODataServiceRoute was good to know about.

Interestingly, I've downloaded and ran the modified project you've attached and still no properties are binding at all for me.
I've also sent the same project to another person to ask if they have success running it on their machine but they get the same result as I do. 

Could you please give me as much information about your local configuration as you can.

**Comment by gathogojr** [comment]
Hi @JamesBarea. I ran the project from Microsoft Visual Studio Enterprise 2019 Version 16.6.5.
To cover a wider base, I have also ran the project from Microsoft Visual Studio Enterprise 2017 Version 15.9.25 and it works just fine.
However, you don't need Enterprise edition for it work. What makes you believe that the Guid and Boolean properties are not being bound? Could you attach a screenshot like I did above to demonstrate what is being returned by `GetChangedPropertyNames()`?
FYI, I used Postman to send the request to the service. What are you using to trigger the request? Could the issue be there?

**Comment by JamesBarea** [comment]
Hi @gathogojr,

I've been running it in Rider but have just tried using Visual studio and get the same result. 
To give a bit more information I used Microsoft Visual Studio Professional 2019 Version 16.4.6 and I am also using Postman to send my requests as well.
I've created a screencast to better show the situation. If you watch the video all the way through you can see what I mean about Newtonsoft that I mentioned earlier: https://drive.google.com/file/d/1Tnoyv4IjaX4IXz65Kj2RYFzc3JYnMKPs/view?usp=sharing

Thanks again for your help with this

**Comment by gathogojr** [comment]
@JamesBarea Thanks for sharing the recording. I was able to observe what is causing the buggy behaviour

Note that you have a route prefix "odata" on this line:
```
routeBuilder.MapODataServiceRoute("odata", "odata", GetEdmModel());
```
This means that the correct endpoint for the patch request should be
```
http://localhost:8965/odata/Example
```
**NOT**
```
http://localhost:8965/Example
```
If you do not want to have "odata" on the request url, set the `routePrefix` parameter to `null` or `string.Empty` when calling `MapODataServiceRoute`.

After you fix that, you'll get a 404 if you don't include the key on the url like this:
```
http://localhost:8965/odata/Example(6c467616-1bae-4c43-a432-8932f9fba793)
```
Note that if you set the key on the url as single-qouted string, you'll get a 404, i.e., **DO NOT** do it this way:
```
http://localhost:8965/odata/Example('6c467616-1bae-4c43-a432-8932f9fba793')
```

**Comment by gathogojr** [comment]
@JamesBarea One question you might have is why the `Patch` action was being matched in spite of the request url being 
`http://localhost:8965/Example`. It's being matched thanks to ASP.NET Core MVC that seems not to be paying attention to the OData route prefix. The reason ASP.NET Core MVC is able to play a part in action selection is because your controller derives from `ControllerBase`. I'd advise you to derive your controllers from `ODataController` to ensure that OData action selector is applied. If you had done that, you'd have gotten a 404 when attempting to send the patch request to `http://localhost:8965/Example` and that would have been easier to debug.

**Comment by JamesBarea** [comment]
@gathogojr You were correct in diagnosis of the URL path being the problem. My issue was because I was using a URL in my requests which was incorrect however most of the functionality was working which lead me down a bad path of troubleshooting.

I'll explain in more depth to help anyone else that comes against this(BTW John I've tested this and the following scenario is relevant even when inheriting the ODataController).

Scenario 1 - If your URL is 'Source/Entity/Guid'  (and you've set no route prefix in startup.cs) - the ActionResult will be found and run, the entity key in URL will bind and the string and bool values in the request body also bind. 

Scenario 2(the correct way) - If your URL is 'Source/Entity(Guid)' (again I'm not using a route prefix) - the ActionResult will be found and everything will bind. However, this will require [FromODataUri] in ActionResult parameter to bind the Key.

Interestingly, Scenario 1 will only bind some data types in the body when using .AddNewtonsoftJson() otherwise only the Key will bind.

Thank you very much for your help John. Excellent support and I appreciate your time running through this with me :)

**Comment by gathogojr** [comment]
@JamesBarea Glad to have been of help. I'll find some time to verify the scenarios you highlighted

**Comment by zdzislaw** [comment]
I solved it by duplicating the class:

Microsoft.AspNetCore.OData.Deltas namespace
public class Delta<T>


I needed to change the TrySetPropertyValuepublic method.

```
private bool TrySetPropertyValuepublic(string name, object value)
        {
            Debug.Assert(name != null, "Argument name is null");

            if (!(_allProperties.ContainsKey(name) && _updatableProperties.Contains(name)))
            {
                return false;
            }

            PropertyAccessor<T> cacheHit = _allProperties[name];

            if (value == null && !cacheHit.Property.PropertyType.IsNullable())
            {
                return false;
            }

            Type propertyType = cacheHit.Property.PropertyType;
            // Adjusting delta
            if (value != null && !TypeHelper.IsCollection(propertyType) &&
                (!propertyType.IsPrimitive &&
                !propertyType.IsAssignableFrom(value.GetType())) &&
                (propertyType.IsPrimitive && !CanConvert(value, propertyType)))
            {
                return false;
            }


            if (propertyType.IsPrimitive)
            {
                cacheHit.SetValue(_instance, Convert.ChangeType(value, propertyType));
            }
            else
            {
                cacheHit.SetValue(_instance, value);
            }


            _changedProperties.Add(name);
            return true;
        }

        public bool CanConvert(object? value, Type conversionType)
        {
            try
            {
                Convert.ChangeType(value, conversionType);
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }
```




I'll try to run some tests and see how I can commit to the official repository.
