### ISSUE TITLE
FilterBinder test "CastToQuotedEntityOrComplexType_DerivedProductName" seems incorrect.

### ISSUE THREAD

**Issue by BlaiseD** [OData/WebApi#2255]
The [CastToQuotedEntityOrComplexType_DerivedProductName test](https://github.com/OData/WebApi/blob/40b8e57fe9f29490cbbe04aadfb2acf3e4fd7638/test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/FilterBinderTests.cs#L2320) has the following filter clause `cast(Category,'FilterBuilder.Tests.Model.DerivedCategory')/DerivedCategoryName eq null`.  Category is a member of the Product entity.

The expected result as defined for the test is `$it => (($it As DerivedCategory).DerivedCategoryName == null)` so casting DerivedCategory (subclass of Category) against the $it Product parameter.

### Assemblies affected

I'm using the source code in this repository.

### Reproduce steps

Just build and execute [tCastToQuotedEntityOrComplexType_DerivedProductName](https://github.com/OData/WebApi/blob/40b8e57fe9f29490cbbe04aadfb2acf3e4fd7638/test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/FilterBinderTests.cs#L2320).

### Expected result

I would have the thought the defined expected result would be:  `$it => (($it.Category As DerivedCategory).DerivedCategoryName == null)`.

### Actual result

The test succeeds hence the question.  Why is that the correct behavior or is it a bug?

**Comment by xuzhg** [comment]
Merged at: https://github.com/OData/WebApi/commit/800166239db589dfb606bb120f793f4aa75eef31
