### ISSUE TITLE
Invalid, partial json response happens when expanding an entity with more items than the allowed 'PageSize' for an endpoint.

### ISSUE THREAD

**Issue by UmairB** [OData/WebApi#2262]
Invalid, partial json response happens when expanding a contained entity with more items than the allowed `PageSize` for an endpoint.

### Assemblies affected

Microsoft.AspNetCore.OData 7.4.1

### Reproduce steps

Entities:
```
    public class Store
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public virtual IEnumerable<Employee> Employees { get; set; }
    }

    public class Employee
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
```

Configuration:
```
            app.UseEndpoints(endpoints =>
            {
                // odata
                //endpoints.MapControllers();
                endpoints
                    .Select().Filter().OrderBy().Count().Expand().MaxTop(50)
                    .SetUrlKeyDelimiter(ODataUrlKeyDelimiter.Parentheses);

                var defaultBatchHandler = new DefaultODataBatchHandler();
                defaultBatchHandler.MessageQuotas.MaxNestingDepth = 2;
                defaultBatchHandler.MessageQuotas.MaxOperationsPerChangeset = 10;

                endpoints.MapODataRoute("odata", string.Empty, GetEdmModel(), defaultBatchHandler);
            });

        private static IEdmModel GetEdmModel()
        {
            var builder = new ODataConventionModelBuilder();

            builder.EntitySet<Store>("Stores")
                .EntityType
                .HasKey(e => e.Id)
                .ContainsMany(e => e.Employees).IsNavigable()
                .Expand()
                .Select()
                .Filter()
                .OrderBy()
                .Page(null, null);

            builder.EntityType<Employee>()
                .HasKey(e => e.Id);

            var model = builder.GetEdmModel();
            return model;
        }
```

Metadata:
```
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="Scratchpad.OData.Web.Entities" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityType Name="Store">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int32" Nullable="false" />
                <Property Name="Name" Type="Edm.String" />
                <NavigationProperty Name="Employees" Type="Collection(Scratchpad.OData.Web.Entities.Employee)" ContainsTarget="true" />
            </EntityType>
            <EntityType Name="Employee">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int32" Nullable="false" />
                <Property Name="Name" Type="Edm.String" />
                <NavigationProperty Name="Store" Type="Scratchpad.OData.Web.Entities.Store" Nullable="false" />
            </EntityType>
        </Schema>
        <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityContainer Name="Container">
                <EntitySet Name="Stores" EntityType="Scratchpad.OData.Web.Entities.Store" />
            </EntityContainer>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>
```

Endpoint:
```
        [HttpGet]
        [EnableQuery(AllowedQueryOptions = AllowedQueryOptions.All, MaxTop = 50, PageSize = 50)]
        public IQueryable<Store> Get()
            => Repository.Stores.AsQueryable();
```

For a store with > 50 employees, the following query
```
https://localhost:44372/stores?$expand=Employees
```

Results in partial json.
### Expected result

Would expect full json response, together with a `Employees@odata.nextLink` property to be generated on the `Store` with employees greater than 50, to obtain the next batch of employees.

### Actual result

Json response cuts off at the last, 50th employee in the expanded list:

```
{
    @odata.context": "https://localhost:44372/$metadata#Stores(Employees())",
    "value": [
        {
            "Id": 639,
            "Name": "Store A",
            "Employees": [
                . 
                .
                .
                {
                    "Id": 963,
                    "Name": "Natalie Fahey"
                }
```

### Additional detail

This seems to be happening because odata doesn't know how to generate the next link property for the employees. Resulting in a null value, which then isn't handling. This throws an exception which is swallowed by the asp.net core middleware with no indication of an error.

Occurs in the method `GetNestedNextPageLink` in the class `ODataResourceSetSerializer`:
```
            IEdmNavigationSource sourceNavigationSource = writeContext.ExpandedResource.NavigationSource;
            NavigationSourceLinkBuilderAnnotation linkBuilder = writeContext.Model.GetNavigationSourceLinkBuilder(sourceNavigationSource);
            Uri navigationLink =
                linkBuilder.BuildNavigationLink(writeContext.ExpandedResource, writeContext.NavigationProperty);
```
Here `navigationLink` is null. And exception is thrown in the code after this. Which is then caught in ODataOutputFormatter:
```
            try
            {
                 // 
            }
            catch (Exception ex)
            {
                return TaskHelpers.FromError(ex);
            }
```
The return exception is not handled by the asp.net core middleware.

Now, I understand that odata doesn't know how to generate the next link for the contained entity, ideally I would like it to be something like `"Employees@odata.nextLink": "https://localhost:44372/stores(id)/Employees?$skip=50"` so I need to know how to configure this.

Also the fact that the null value and the exception isn't handled is a bit bad.

**Comment by KenitoInc** [comment]
Hey @UmairB 
We will look into the issue and get back to you. Thanks for the great repro.

**Comment by UmairB** [comment]
Hello. Any updates on this? Or atleast a workaround? How can I register links for child entities for example?

**Comment by KenitoInc** [comment]
> Hello. Any updates on this? Or atleast a workaround? How can I register links for child entities for example?

You can use _Non-Contained_ navigation, by creating an EntitySet for the `Employee` EntityType. We are working on the fix.

**Comment by UmairB** [comment]
Is there no way to manually register links? Even by fiddling about with the edm model? It needs to be contained for us.

**Comment by KenitoInc** [comment]
> Is there no way to manually register links? Even by fiddling about with the edm model? It needs to be contained for us.

@UmairB Let me dig into the issue, if I can get a work around, I will share with you.

**Comment by UmairB** [comment]
@KenitoInc thank you! 😊

**Comment by KenitoInc** [comment]
@UmairB The fix should be in the next release.

**Comment by ireneherbedz** [comment]
Hi, @KenitoInc I'm still able to reproduce this issue, could you please help to resolve it?

Steps to reproduce:
- Use Microsoft.AspNetCore.OData Version 7.5.2
- Use Edm model
- Add [EnableQuery(PageSize = 100)] to your endpoint
- try to load just 1 item and apply $expand to a property with array type which has more than 100 records 
(endpoint_name?$expand=array_property_name)

EXPECTED: 
  data loaded successfully
ACTUAL:
 response body has broken json (SyntaxError: Unexpected end of JSON input)

**Comment by KenitoInc** [comment]
@ireneherbedz Share your repro code if you can.

**Comment by ireneherbedz** [comment]
Sure, here we go:
[TestOdata.zip](https://github.com/OData/WebApi/files/5588150/TestOdata.zip)

Just start this project by using project configuration (not iis) and try to make a request like this: https://localhost:5001/odata/stores?$expand=Books
Then try to parse your response body -> you will see that JSON is broken.
![image](https://user-images.githubusercontent.com/74591637/100063101-c1fbd680-2e84-11eb-99f8-b8f56274b6f2.png)

**Comment by KenitoInc** [comment]
Hey @ireneherbedz 
I had a look at your code.
Since you didn't add a `Books` entity set when creating the `EdmModel` in `Startup.cs` file, you are creating a `Contained` navigation.
The model should look as follows

```csharp
public class Store
    {
        public int Id { get; set; }
        [Contained]
        public List<Book> Books { get; set; }
    }

    public class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
```
Note: The `Contained` attribute is used for `Books` navigation property.
Tell me if this works for you.

**Comment by KenitoInc** [comment]
Alternatively,
You can remove the `Contained` attribute and create an `non-contained` navigation property by defining a `Books` entity set in `startup.cs` as follows:
```csharp
static IEdmModel GetEdmModel()
{
    var builder = new ODataConventionModelBuilder();
    builder.EntitySet<Store>("Stores");
    builder.EntitySet<Book>("Books");
    return builder.GetEdmModel();
}
```

**Comment by ireneherbedz** [comment]
Hi @KenitoInc I tried to use [Contained] attribute and it helped to expand 1 level, but when I tried to expand 2nd level -> I've got the same error.

I've sent you updated repo. Start it please and try this request to reproduce my issue: 
https://localhost:5001/odata/stores?$expand=Books($expand=Author, Readers)

And I also found that I cannot expand Address(it is loaded automatically without using expand), got this error message: _"The query specified in the URI is not valid. Property 'Address' on type 'TestOdata.Controllers.Store' is not a navigation property or complex property. Only navigation properties can be expanded._ Interesting thing here is I can expand StoreOwner,Manager,ShoppingAssistant,Cleaner, but I cannot expand Address, could you please explain to me why? To reproduce try this request please: 
https://localhost:5001/odata/stores?$expand=StoreOwner,Manager,ShoppingAssistant,Cleaner,Address

[TestOdata.zip](https://github.com/OData/WebApi/files/5619011/TestOdata.zip)

**Comment by GowrishKumar** [comment]
Dear @KenitoInc , 

Just checking to see if there is any update on this issue...thanks!

**Comment by krishnamadhavmajety** [comment]
Hi @KenitoInc ,
 
Please share if there is any update on this issue.. Thanks!
