### ISSUE TITLE
Question:  Correct Replacement for [Route("odata/Common/[Controller]")]

### ISSUE THREAD

**Issue by occurrance** [OData/WebApi#2263]
*I'm working on a long overdue upgrade of a large .Net Core 1.x application to Standard 2.0  We make extensive use of the Route Parameter for all of our Odata Endpoints.  After the upgrade, everything seems to be working, except the response does not include the @odata.context wrapper, but instead is a plain JSON result.*

### Assemblies affected

*Microsoft.AspNet.Mvc (5.2.3)
Microsoft.AspNetCore.OData (7.4.1)*

### Reproduce steps

*Start with a working Odata controller
Add Route Attribute to specify sub-folder URI for Odata Endpoint*
[Route("odata/Common/[Controller]")]

### Expected result

*Odata Results include "@odata.context" header*

{"@odata.context":"http://localhost:44305/odata/Common/$metadata#Books","value":[{"Id":2,"ISBN":"063-6-920-02371-5","Title":"Enterprise Games","Author":"Michael Hugos","Price":49.99,"Location":{"City":"Bellevue","Street":"Main ST"}}]}

### Actual result

*Odata seems to work for select and filtering, but does not include header*

[{"id":2,"isbn":"063-6-920-02371-5","title":"Enterprise Games","author":"Michael Hugos","price":49.99,"location":{"city":"Bellevue","street":"Main ST"},"press":null}]

### Additional Information

*I've done quite a bit of debugging, it seems the IODataFeature is not set on the HTTPContext, so the ODataOutputFormatter is not being used.  The CanWriteResult is false because the Path is not set*

**Comment by xuzhg** [comment]
@occurrance Can you change [RouteAttribute] to use [ODataRouteAttribute] to see whether it can work or not?

**Comment by occurrance** [comment]
@xuzhg , I've tried various combinations of that.   

**[ODataRoute("odata/Common/Books")]  on the Method:**
*System.InvalidOperationException: The path template 'odata/Common/Books' on the action 'Get' in controller 'CommonBooks' is not a valid OData path template. Resource not found for the segment 'odata'.*

**[ODataRoute("Common/Books")] on the Method:**
*System.InvalidOperationException: The path template 'Common/Books' on the action 'Get' in controller 'CommonBooks' is not a valid OData path template. Resource not found for the segment 'Common'.*

Both break odata completely.  
I've also tried variations of ODataRoutePrefix on the controller class, all resulting in 404.

**Comment by xuzhg** [comment]
@occurrance  Would you please share me your "startup.cs" and the "C# classes"? 
Or it's better if you can share me your csdl/metadata?

**Comment by occurrance** [comment]
@xuzhg , will a repo work?
https://github.com/occurrance/ODataTest

**Comment by xuzhg** [comment]
@occurrance 
Thanks for the repo. 

I checked with your repo, you have the following OData model builder:

```C#
private static IEdmModel GetEdmModel(ODataConventionModelBuilder builder)
{
            builder.EntitySet<Book>("Books");
            builder.EntitySet<Press>("Presses");
            return builder.GetEdmModel();
}
```

Meanwhile, you have the following routing config:

```C#
routebuilder.MapODataServiceRoute("odata", "odata", GetEdmModel(odataBuilder));
```

So, I don't know where comes from the "Common" in your routing attribute.

Therefore, 
1, [ODataRoute("odata/Common/Books")] can't work because "odata", "common" doesn't make sense.
2, [ODataRoute("Common/Books")]  can't work becase "common" doesn't make sense.

In actual, **[ODataRoute("Books")]** should work at all.

**Comment by occurrance** [comment]
Hi @xuzhg , Yes, odata/Books works correctly.   All of our existing OData routes are under a sub-folder.   They are organized with a folder per feature:  /odata/Feature1, /odata/Feature2, etc..  and I was trying to reproduce the existing behavior.    Is there a way to create a functional endpoint for books at  "/odata/Common/Books"?

**Comment by occurrance** [comment]
Hi @xuzhg , I may have answered my own question...    Is this acceptable?
`               var edmModel = GetEdmModel(odataBuilder);

                //Set Odata Base Routes
                routebuilder.MapODataServiceRoute("odataCommon", "odata/Common", edmModel);
                routebuilder.MapODataServiceRoute("odata", "odata", edmModel);`

**Comment by xuzhg** [comment]
@occurrance Yes, it's ok.
Besides, it also supports the basic template, for example:

```
routebuilder.MapODataServiceRoute("odataCommon", "odata/{folder}", edmModel);
```

So, here "folder" is the place holder that you can replace this using any string when files the request.

for example:

```C#
~/.../odata/common/Books
~/.../odata/Feature2/Books
```
You can retrieve the "folder" placeholder string through the route data in each request. Hope it can help.

**Comment by xuzhg** [comment]
@occurrance is it ok to close this issue?

**Comment by occurrance** [comment]
@xuzhg , Yes, you can close.   Thanks for the assistance.
