### ISSUE TITLE
OData $filter + GroupBy where filter is not in GroupBy

### ISSUE THREAD

**Issue by thancock14** [OData/WebApi#2268]
When the field in the $filter is not included in the GroupBy/Aggregation validation fails.

### Assemblies affected
netcoreapp3.1
Microsoft.AspNetCore.OData 7.3.0 and 7.4.0 and 7.4.1

### Reproduce steps
Download:
https://github.com/kosinsky/ODataDemos/tree/master/AggregationSample
Then attempt this query:
```
http://localhost:5000/odata/Orders?$filter=TotalAmount lt 40&$apply=groupby((Title))
```
this is an attempt to get unique Title's for all Orders with a TotalAmount less than 40.  

### Expected result

```
{
@odata.context: "http://localhost:5000/odata/$metadata#Orders(Title)",
value: [
{
@odata.id: null,
Title: "Redonse"
},
{
@odata.id: null,
Title: "Bellewe"
},
{
@odata.id: null,
Title: "Newcastle"
}
]
}
```

### Actual result

```
{
error: {
code: "",
message: "The query specified in the URI is not valid. $apply/groupby grouping expression 'TotalAmount' must evaluate to a property access value.",
details: [ ],
innererror: {
message: "$apply/groupby grouping expression 'TotalAmount' must evaluate to a property access value.",
type: "Microsoft.OData.ODataException",
stacktrace: " at Microsoft.OData.UriParser.EndPathBinder.BindEndPath(EndPathToken endPathToken) at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token) at Microsoft.OData.UriParser.BinaryOperatorBinder.GetOperandFromToken(BinaryOperatorKind operatorKind, QueryToken queryToken) at Microsoft.OData.UriParser.BinaryOperatorBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken) at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token) at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter) at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo) at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter() at Microsoft.AspNet.OData.Query.FilterQueryOption.get_FilterClause() at Microsoft.AspNet.OData.Query.Validators.FilterQueryValidator.Validate(FilterQueryOption filterQueryOption, ODataValidationSettings settings) at Microsoft.AspNet.OData.Query.FilterQueryOption.Validate(ODataValidationSettings validationSettings) at Microsoft.AspNet.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings) at Microsoft.AspNet.OData.EnableQueryAttribute.ValidateQuery(HttpRequest request, ODataQueryOptions queryOptions) at Microsoft.AspNet.OData.EnableQueryAttribute.<>c__DisplayClass1_0.<OnActionExecuted>b__1(ODataQueryContext queryContext) at Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction) at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)"
}
}
}
```

### Additional detail

I can get it to work by an odd way.
if you add an aggregation to the end it appears to work.
```
http://localhost:5000/odata/Orders?$filter=TotalAmount lt 40&$apply=groupby((Title), aggregate(TotalAmount with sum as TotalAmount))
```
But this aggregate MUST end with "as TotalAmount" which matches the field in the filter part.

This works: 
```
http://localhost:5000/odata/Orders?$apply=groupby((Title))
```
but does not allow the filter to be applied.

----
In .net core 2.2 this query worked fine.  Now it appears to execute the $filter POST apply/aggregation, when it is intuitive that it should be filtered PRIOR to the aggregation if it's in the $filter.  (I honestly didn't know you could filter after aggregation)

Here is another query that acts differently:
```
http://localhost:5000/odata/Orders?$filter=TotalAmount gt 23&$apply=groupby((Customer/Name), aggregate($count as OrderCount, TotalAmount with sum as TotalAmount))
```
This query appears to execute the $filter=TotalAmount gt 23 After it performs the groupby and aggregate.  but if you look at the query you would assume it would execute before the groupby and aggregate.  I would assume it would be filtering the input to the $apply.

Am I reading the documentation for the OData v4 spec incorrectly?

**Comment by gathogojr** [comment]
Hi @kosinsky Can you take a look at this and advise whether we support this so we can follow up?

**Comment by kosinsky** [comment]
That's by design http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs02/odata-data-aggregation-ext-v4.0-cs02.html#_Toc435016590 
> The new system query option $apply is evaluated first, then the other system query options are evaluated, if applicable, on the result of $apply in their normal order (see [OData-Protocol, section 11.2.1]). If the result is a collection, $filter, $orderby, $expand and $select work as usual on properties that are defined on the output set after evaluating $apply.

You could use `filter()` transformation to filter before `groupby` (https://devblogs.microsoft.com/odata/aggregation-extensions-in-odata-asp-net-core/#filter-transformation)

```
http://localhost:5000/odata/Orders?$apply=filter(TotalAmount lt 40)/groupby((Title))
```

Also, order of options in the query doesn't matter: `$filter=...&$apply=...` and `$apply=..&$filter=...` are the same.

**Comment by gathogojr** [comment]
Thanks @kosinsky. This is very helpful

**Comment by thancock14** [comment]
thank you @kosinsky !   that does make sense now. 
I am thinking the validation in .net core 2.2 was not as strict, which is why I was getting away with it.

I have been using OData on top of mongodb for a few years now, and there are a few quirks.  One of them is the ApplyExpandSelect cannot be used against Mongodb, the linq provider/driver doesn't support everything OData spits out yet.  so we got around that by forcing the $filter to get applied then materialize the data in memory IQueryable<T>  then allowing OData pipeline to evaluate the select/expand/ and apply part of the OData querystring.  
Is there any way to extract the "filter()" part of an apply with any ODataQueryOptions or anything?  that way I can apply the filter similarly to how I am doing it?

**Comment by thancock14** [comment]
Closing because it was a misunderstanding of the OData spec.
.net Core 3.1 has better validation of the URL which throws an error instead of allowing us to process the $filter before the $apply.
