### ISSUE TITLE
OData expand should use custom repository

### ISSUE THREAD

**Issue by alc86** [OData/WebApi#2270]
We use a repository pattern in our application which does some additional filtering (all rows where DeletedDate is NULL). This works perfect beside the expand of OData. The problem is that the expand is handled by EF Core directly. We need the opportunity to handle the expand with our own repository.

**Comment by gathogojr** [comment]
@alc86 Thank you for the question. If the idea is to be able to get hold of the query options and process that by yourself, you could apply the `ODataQueryOptions` parameter to the controller action and from this you could get the raw query options and add the extra filters. Can you provide more details so we're able to understand what behaviour you're looking for?

**Comment by gathogojr** [comment]
Hi @alc86. Did you manage to get this issue sorted?
