### ISSUE TITLE
Update reference to ODL

### ISSUE THREAD

**Issue by mikepizzo** [OData/WebApi#2274]
We fixed some issues with WebAPI Batch processing to make it truly asynchronous in order not to have to set the allowsynchronous flag in ASPNetCore for batch.

This uncovered some issues with ODL in that some ODL async calls were incorrectly making sync calls under the covers.

The issues in ODL were fixed, but since API specifies an earlier version of ODL, applications using batch with that (default) earlier version will encounter runtime issues in certain $batch scenarios.

We should update the reference to ODL to be 7.7.1.

**Comment by xuzhg** [comment]
Merged the PR. Thanks.
