### ISSUE TITLE
Unable to $select complex types after version 7.2.2

### ISSUE THREAD

**Issue by MathiasJor** [OData/WebApi#2281]
Hi :).

We're attempting to upgrade from Microsoft.AspNet.OData 7.0.0 to the newest version, but are encountering some issues. We seem to be unable to select/expand any of our complex types, where we were able to on earlier versions. 

### Assemblies affected

From `Microsoft.AspNet.OData 7.2.3` up to and including `Microsoft.AspNet.OData 7.4.1` (current newest).

### Reproduce steps

I found [this](https://github.com/OData/ODataSamples/tree/master/RESTier/Trippin) (slightly outdated) sample project, which has a complex type called "Location", similar to what we have in our project. Using that as a base, to reproduce:

1. Clone repo
2. Upgrade nuget packages (that project is on Microsoft.AspNet.OData 7.2.1, which works fine)
3. Run the solution and try to query Events: 
(1) `http://localhost:18384/Events`
(2) `http://localhost:18384/Events?$select=occursAt`

Here the "OccursAt" field is of the complex type "Location". 

### Expected result
This is what you get on version 7.2.2 and below:
(1) `{"@odata.context":"http://localhost:18384/$metadata#Events","value":[{"Id":1,"Description":null,"OccursAt":{"Address":"Address1"}}]}`

(2) `{"@odata.context":"http://localhost:18384/$metadata#Events(OccursAt)","value":[{"OccursAt":{"Address":"Address1"}}]}`

### Actual result
This is what you get on versions above 7.2.2:
(1) `{"@odata.context":"http://localhost:18384/$metadata#Events","value":[{"Id":1,"Description":null,"OccursAt":{"Address":"Address1"}}]}`

(2) `{"error":{"code":"","message":"Cannot compare elements of type 'Microsoft.OData.Service.Sample.Trippin.Models.Location'. Only primitive types, enumeration types and entity types are supported."}}`

### Additional detail

As you can see, the complex types appear fine as long as we have an empty query (example (1)). It crashes however, as soon as we try to select the complex type.

**Comment by xuzhg** [comment]
@MathiasJor  Can you help to verify `Microsoft.AspNet.OData.7.5.0-Nightly202009150040.nupkg` whether it's working at your side?

**Comment by xuzhg** [comment]
Close it since the PR got merged. Please help check the nightly or the coming 7.5 RTM. If still has problem, please reopen it and let us know it.

**Comment by MathiasJor** [comment]
Hey, thanks for your reply :).

I still have the issue, both in our project and the sample project on `Microsoft.AspNet.OData 7.5.0-Nightly202009150040`.
