### ISSUE TITLE
Still unable to $select complex types after version 7.2.2

### ISSUE THREAD

**Issue by MathiasJor** [OData/WebApi#2284]
Hey again, I seem to be unable to re-open the original issue, so I had to open a new one. This #2281 is still there on nightly Microsoft.AspNet.OData 7.5.0-Nightly202009150040. Both on the sample project I linked in that issue, and in our custom project. The issue can still be reproduced in the same steps provided in that issue. 

### Assemblies affected

- Microsoft.AspNet.OData 7.5.0-Nightly202009150040
- From `Microsoft.AspNet.OData 7.2.3` up to and including `Microsoft.AspNet.OData 7.4.1` (current newest).

### Reproduce steps _(Copied from #2281)_
I found [this](https://github.com/OData/ODataSamples/tree/master/RESTier/Trippin) (slightly outdated) sample project, which has a complex type called "Location", similar to what we have in our project. Using that as a base, to reproduce:

1. Clone repo
2. Upgrade nuget packages (that project is on Microsoft.AspNet.OData 7.2.1, which works fine)
3. Run the solution and try to query Events: 
(1) `http://localhost:18384/Events`
(2) `http://localhost:18384/Events?$select=occursAt`

Here the "OccursAt" field is of the complex type "Location". 

### Expected result _(Copied from #2281)_
This is what you get on version 7.2.2 and below:
(1) `{"@odata.context":"http://localhost:18384/$metadata#Events","value":[{"Id":1,"Description":null,"OccursAt":{"Address":"Address1"}}]}`

(2) `{"@odata.context":"http://localhost:18384/$metadata#Events(OccursAt)","value":[{"OccursAt":{"Address":"Address1"}}]}`

### Actual result _(Copied from #2281)_
This is what you get on versions above 7.2.2:
(1) `{"@odata.context":"http://localhost:18384/$metadata#Events","value":[{"Id":1,"Description":null,"OccursAt":{"Address":"Address1"}}]}`

(2) `{"error":{"code":"","message":"Cannot compare elements of type 'Microsoft.OData.Service.Sample.Trippin.Models.Location'. Only primitive types, enumeration types and entity types are supported."}}`

**Comment by xuzhg** [comment]
@MathiasJor How about this version?

 https://www.myget.org/feed/webapinetcore/package/nuget/Microsoft.AspNet.OData/7.5.0-Nightly202009142118

**Comment by xuzhg** [comment]
@MathiasJor Alright, 

1) 
https://www.myget.org/feed/webapinetcore/package/nuget/Microsoft.AspNet.OData/7.5.0-Nightly202009142118
should work, it hardly removes the null check.

2) 
https://www.myget.org/feed/webapinetcore/package/nuget/Microsoft.AspNet.OData/7.5.0-Nightly202009150728

now works at my side. It comes from this PR https://github.com/OData/WebApi/pull/2285. 

![image](https://user-images.githubusercontent.com/9426627/93180153-9a052f80-f6eb-11ea-8ff8-a6b1339e075a.png)

The previous (Nightly202009150040) nightly can't work because the Restier Trippin service is using [this](https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Core/QueryableSource.cs#L13), the old implementation can't process this provider and any other customized provider. 

Let me know any problem.

**Comment by MathiasJor** [comment]
So now it seems to work fine for the sample project, thanks :). 

However, in our custom project we also have a custom deserializer, and this still fails for all of our complex types. 

![image](https://user-images.githubusercontent.com/14106477/93180590-aadb9280-f737-11ea-8245-bfd8d7d163b0.png)

Attempting to get the ResourceInstance of the expanded resource fails, but only when selecting a complex type (similar query to the original issue). Selecting any normal entity, or property works as expected. 

Updating comment with stacktrace in 2minutes.

**Comment by MathiasJor** [comment]
I was able to recreate the serializer issue in the trippin sample. I uploaded the modified version to [this](https://github.com/MathiasJor/ODataComplexTypeIssueSample) repository. Try to run these queries:

http://localhost:18384/Events (Should work as expected)
http://localhost:18384/Events?$select=occursAt Throws error at line 51 of CustomODataSerializerProvider. http://localhost:18384/Events?$select=occursAt,testTime Throws error at line 47 of CustomODataSerializerProvider.

**Comment by xuzhg** [comment]
@MathiasJor There's some feature gaps that can't create the Resource instance if a select or expand in the query.

I have a quick fix at #2288, Would you please try this nightly **Microsoft.AspNet.OData.7.5.0-Nightly202009152040**?

It should work and it worked at my side using your github repo.

![image](https://user-images.githubusercontent.com/9426627/93265101-f5bbd100-f75c-11ea-9c39-f386b6b6782f.png)

**Comment by MathiasJor** [comment]
Yes, that seems to work on my end! 

Thanks a lot for your quick responses and help :). So we can assume this will be available with the release of 7.5.0? :).

**Comment by xuzhg** [comment]
Merged the PR https://github.com/OData/WebApi/pull/2288, it will be in 7.5 RTM

**Comment by ificator** [comment]
Hi @MathiasJor the fix for this issue introduced another (#2316). We've got another fix in flight (#2320) but I want to ensure it doesn't regress your scenario again - could you validate that Nightly202010092336 still works for you?
