### ISSUE TITLE
substringof method did not work in mono 6.8.x ,Microsoft.AspNet.OData 7.4.1 , .net framework 4.6.1 @guxing2  Moving this to WebApi. Also could you kindly provide some more information to make the repro steps easier.

### ISSUE THREAD

**Issue by guxing2** [OData/WebApi#2290]
@guxing2  Moving this to WebApi. Also could you kindly provide some more information to make the repro steps easier.

_Originally posted by @marabooy in https://github.com/OData/WebApi/issues/2286#issuecomment-692709923_

**Comment by xuzhg** [comment]
closed as duplicated as #2286
