### ISSUE TITLE
Can't unit test code that generates OData links

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#23]
There's no unit that encapsulates the logic around generating a full OData
link, so tests end up integration style. Having an odata link factory
abstraction allows unit testing such code.  
  
We are putting two related properties together on the request: path handler
and route name. These are a pair, which is a code smell that there's one
abstraction here that should be used instead. Having an odata link factor also
solves this problem.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 769](http://aspnetwebstack.codeplex.com/workitem/769)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jan 12, 2013 at 1:50 AM
**Reported by:**	davidmatson
**Updated on:**	Sep 23, 2013 at 7:45 PM
**Updated by:**	danroth27

**Comment by LianwMS** [comment]
On *2013-03-13 05:15:42 UTC*, **HongmeiG** commented:

Can you improve this as part of your unit testability work?

**Comment by xuzhg** [comment]
Close it. Please file a new issue if you have further concern. Thanks.
