### ISSUE TITLE
$select throws serialization error for custom model odata .net core

### ISSUE THREAD

**Issue by punitsinghi** [OData/WebApi#2303]
I am using Odata in .net core API project and it is failing when I return custom model from my api. It is throwing serialization error when I use $select in request uri. It works fine for $filter / $top or without select. I am using 7.5. Nuget package of OData.

`cRequest uri-    https://localhost:44359/odata/States?$select=code&$filter=Code eq 'AK'  `

``` csharp
 public IQueryable<**ODataState**> GetStates()
    {
        return (_oDataUnitOfWork.GetRepository<IStateRepository>().GetDbContext() as ODataContext).
            State.AsQueryable().Select(x => new ODataState { Code = x.Code, Name = x.Name });
    }

```
Below is the **custom** model-
```csharp
public class ODataState
{
    public string Code { get; set; }
    public string Name { get; set; }
}

```
Below **State** is Entity-

```csharp
[Table("State", Schema = "Common")]
    public class State : DbEntityBase
    {
        public State()
        {

        }

        [Key]
        public string Code { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public bool DisallowTableFunding { get; set; } // DisallowTableFunding
        public bool RequiresBrokerLicense { get; set; } // RequiresBrokerLicense
        public byte[] TimeStamps { get; private set; } // TimeStamps (length: 8)
        public bool IsCommunityProperty { get; set; }  //IsCommunityProperty
        public bool IsOptInCommunityProperty { get; set; }  //IsOptInCommunityProperty
    }

```
**Error** - 

``` "'EnumerableQuery`1' cannot be serialized using the ODataMediaTypeFormatter.   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.GetSerializer(Type type, Object value, IWebApiRequestMessage internalRequest, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer)\r\n   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)\r\n   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Abacus.Core.ErrorHandling.Api.ExceptionHandlingMiddleware.InvokeAsync(HttpContext context)",```

**Comment by gathogojr** [comment]
If you're using the **Edm approach**, the fix is to add `ODataState` to your Edm model. That way, the OData message writer will "know" the structure of `ODataState` and won't have a problem writing `ODataState` instances into the response. You could do it the following way:

Assuming you already have the following two lines in your service configuration code:
```c#
var modelBuilder = new ODataConventionModelBuilder();
modelBuilder.EntitySet<State>("States");
```
Go ahead and decorate the `Code` property on `ODataState` with `Key` attribute, i.e.
```c#
public class ODataState
{
    [Key]
    public string Code { get; set; }
    public string Name { get; set; }
}
```
Then in your service configuration code,
```c#
modelBuilder.EntityType<ODataState>();
```

Another way, would be to represent `ODataState` as a complex type - if you didn't want to make changes to the `ODataState` class, i.e.
```c#
modelBuilder.ComplexType<ODataState>();
```
Admittedly, this would look a bit strange since your `Get` controller action would be returning instances of a complex type. All the same, it'd cure the serialization problem.

The reason why `$filter`, `$top`, `$orderby`, etc will work even when `ODataState` is not in the Edm model is because they're applied way earlier in the game, before serialization even commences.



If you're using the **Non-Edm approach**, there's a related issue [here](https://github.com/OData/WebApi/issues/2143) assigned to @xuzhg. Kindly let me know if this helps you get unblocked

**Comment by gathogojr** [comment]
As an update, when using the **Non-Edm approach**, you can call `AddNewtonsoftJson()` to resolve the formatting issue with `$select`. Read more about that on this [blog post](https://devblogs.microsoft.com/odata/enabling-endpoint-routing-in-odata/#non-edm-approach).

**Comment by punitsinghi** [comment]
Thanks for the update it helps.

**Comment by Ken-ISC** [comment]
I'm having the same issue but in getting the XML format @gathogojr, hoping you could help me.
link to my post here : https://stackoverflow.com/questions/72566646/odata-select-and-expand-not-working-on-xml-response
