### ISSUE TITLE
An unknown function with name 'matchesPattern' was found.

### ISSUE THREAD

**Issue by StefanoVuerich** [OData/WebApi#2304]
I'm using Microsoft.AspNet.OData.

I'm trying to use $filter=matchesPattern(Property, '%pattern%') but I'm receiving Exception: Microsoft.OData.ODataException: 'An unknown function with name 'matchesPattern' was found. This may also be a function import or a key lookup on a navigation property, which is not allowed.'

Is 'matchesPattern' function not supported?

It is a [specification](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_matchesPattern) of OData v4 protocol

**Comment by Arithmomaniac** [comment]
Correct, see https://github.com/OData/AspNetCoreOData/issues/331

**Comment by au5ton** [comment]
It seems like matchesPattern support was [added to the .NET Core version](https://github.com/OData/AspNetCoreOData/pull/729). Does this seem like something that is possible to bring to this project?
