### ISSUE TITLE
EnableQuery attribute changes response to an empty list

### ISSUE THREAD

**Issue by frankpeng7** [OData/WebApi#2305]
### Problem Description
We have an API using ODataController with ASP.NET Core 2.1. This is one of the actions:
```csharp
[HttpGet]
[ODataRoute("route_redacted")]
[EnableQuery(AllowedQueryOptions = AllowedQueryOptions.Filter)]
public async Task<IActionResult> name_redacted([FromServices] ODataQueryOptions<type_redacted> oDataQueryOptions)
```
When calling this API using: `<route_redacted>?$filter=<parameter_name_redacted>%20eq%20<value_redacted>`

The response is always an empty list
```json
{
    "@odata.context": "context_redacted",
    "value": []
}
```

However, if I remove the line `[ODataRoute("route_redacted")]` then it works. Response looks like:
```jsonc
{
    "@odata.context": "context_redacted",
    "value": [
        {
            "id": "id_redacted",
            // rest of object redacted
        }
    ]
}
```

Could this behavior be related to the EnableQuery attribute or other Odata stuff?

### Other findings
In our use case, `value_redacted` is an url and is partially encoded. So the actual request URL looks lie 
```
<route_redacted>?filter=SomeUrl%20eq%20https://teams.microsoft.com/l/meetup-join/19%3ameeting_MGQ
```
As described above, this will result in an empty list in response, but if I change the the URL to a fully encoded one
```
https%3A%2F%2Fteams.microsoft.com%2Fl%2Fmeetup-join%2F19%253ameeting_MGQ4MDQ
```
the response turns back to normal (the second one above)

**Comment by marabooy** [comment]
@frankpeng7 Could you kindly share what version of WebApi you are using as well as try with 7.4 as 7.5 has a known regression affecting route selection.

**Comment by frankpeng7** [comment]
Hi @marabooy thanks for the quick response! If you're talking about `Microsoft.AspNet.WebApi` we are using 5.2.7

**Comment by xuzhg** [comment]
@frankpeng7 how do you use "oDataQueryOptions" in your action?

**Comment by marabooy** [comment]
@xuzhg It seems like the input of the query is being Url Decoded and this causes a mismatch when the ApplyQuery function is called. e.g. when the input url in the query is `http://example.com/10%3Asegment1%3Fc%3D%7B%22jsonkey%22%3A%22jsonvalue%22%7D` the query options will contain the decoded value which is `http://example.com/10:segment1?c={"jsonkey":"jsonvalue"}`  and the apply query in this case filters out all encoded urls.

**Comment by marabooy** [comment]
A workaround that overrides the default behavior for the EnableQuery.ApplyQuery function should be able to solve the issue where the user can override the behavior of how to treat links as the default string comparison can be inadequate for urls ad the two urls above are the same. The other option is to have the urls decoded in the response for the default behaviour to work.
@frankpeng7 closing this do feel free to reopen in case of anything.
