### ISSUE TITLE
DeleteRef fails if navigation property is derived type and there is no corresponding entity set

### ISSUE THREAD

**Issue by pschmiedge** [OData/WebApi#231]
I am reporting this as a variant of issue #173, as the fix for that issue does not resolve this case.  Consider the following scenario, based on the existing scenario in ODataRoutingModel.cs and ODataRoutingTest.cs:

Model:

    public class RoutingCustomer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public virtual List<SpecialProduct> SpecialProducts { get; set; }
    }

    public class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }

    public class SpecialProduct : Product
    {
        public int Value { get; set; }
        public virtual List<RoutingCustomer> RoutingCustomers { get; set; }
    }

Controller setup:

    ODataConventionModelBuilder builder = new ODataConventionModelBuilder(configuration);
    builder.EntitySet<RoutingCustomer>("RoutingCustomers");
    builder.EntitySet<Product>("Products");

Notably, a `SpecialProducts` route is *not* mapped.  The only way to access a `SpecialProduct` is through `Products`.

The following two requests will fail with a 404:

    DELETE RoutingCustomers(1)/SpecialProducts/$ref?$id=http://localhost/Products(5)
    DELETE RoutingCustomers(1)/SpecialProducts/$ref?$id=http://localhost/Products(5)/System.Web.OData.Routing.SpecialProducts

I would expect at least one of these to succeed.

Like #173, the issue is still in DefaultODataPathHandler:

    try
    {
        entityIdSegment = uriParser.ParseEntityId();

        if (entityIdSegment != null)
        {
            // Create another ODataUriParser to parse $id, which is absolute or relative.
            ODataUriParser parser = new ODataUriParser(model, serviceRootUri, entityIdSegment.Id);
            id = parser.ParsePath().LastSegment as Semantic.KeySegment;
        }
    }
    catch (ODataException)
    {
        // Exception was thrown while parsing the $id.
        // We will throw another exception about the invalid $id.
        exceptionThrown = true;
    }

    if (exceptionThrown ||
        (entityIdSegment != null &&
            (id == null || !id.EdmType.IsOrInheritsFrom(lastSegmentEdmType.ElementType.Definition))))
    {
        throw new ODataException(Error.Format(SRResources.InvalidDollarId, queryString.Get("$id")));
    }

In the first request (no cast), the problem is that the last segment of the `$id` parameter is appears to be of type `Product`, not `SpecialProduct`, which makes it incompatible with the `SpecialProducts` navigation property.  The failure point is `!id.EdmType.IsOrInheritsFrom(lastSegmentEdmType.ElementType.Definition)`

In the second request (with cast), the problem is that the last segment of the `$id` parameter is not a `KeySegment`; it is a `TypeSegment`.  Thus the failure point is `id == null`.

A simple fix to support the second scenario would be to replace:

    id = parser.ParsePath().LastSegment as Semantic.KeySegment;

With

    id = parser.Segments.OfType<Semantic.KeySegment>().LastOrDefault();

Supporting the first scenario would probably require "sniffing" the type of the `$id`, or going with the original solution proposed in #173:

    if (exceptionThrown ||
      (entityIdSegment != null &&
        (id == null || 
         !(lastSegmentEdmType.ElementType.Definition.IsOrInheritsFrom(id.EdmType) || 
           id.EdmType.IsOrInheritsFrom(lastSegmentEdmType.ElementType.Definition)))))
          {
            throw new ODataException(Error.Format(SRResources.InvalidDollarId, queryString.Get("$id")));
          }

In this case, it would be up to the author of the Controller to verify that the incoming key is compatible with the navigation property.

**Comment by VikingsFan** [comment]
Hi, thanks for your comment, the second way to delete ref link is not support in webapi because the odata spec doesn't define that, the first way can work after your fix, please leave comment in my pull request if you have any concern!

**Comment by congysu** [comment]
Checked in: ff354b22aaaaf4a4d793b9339b8d2f9b6043fc2d
