### ISSUE TITLE
Selecting a complex property with a null value in a feed fails

### ISSUE THREAD

**Issue by ificator** [OData/WebApi#2316]
If I have a simple object model like this:
```
    public class Simple
    {
        [DataMember]
        public Complex Complex { get; set; }

        [Key]
        public string Id { get; set; }

        [DataMember]
        public string Name { get; set; }
    }

    public class Complex
    {
        public string Value { get; set; }
    }
```
*Where `Simple` is used for the entity set.*

And I make a query like this:
`.../Simple?$select=Complex`

The request will fail if any of the `Simple` instances have a null value for `Complex`

### Assemblies affected

Microsoft.AspNet.OData 7.5.0

### Reproduce steps

https://github.com/ificator/examples/tree/missingpropertyrepro/OData/MissingProperty

1. Hit `https://localhost:44324/odata/Data?$select=Complex&repro=1` and it will generate an invalid response with console output stating:
```
System.InvalidOperationException: The EDM instance of type '[ODataAnnotations.Complex Nullable=True]' is missing the property 'Value'.
   at Microsoft.AspNet.OData.ResourceContext.GetPropertyValue(String propertyName)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateStructuralProperty(IEdmStructuralProperty structuralProperty, ResourceContext resourceContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateStructuralPropertyBag(SelectExpandNode selectExpandNode, ResourceContext resourceContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateResource(SelectExpandNode selectExpandNode, ResourceContext resourceContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
```
2. Hit `https://localhost:44324/odata/Data?$select=Complex` and it will work as expected

### Additional detail

It seems that `resourceContext.GetPropertyValue("Complex")` is returning an "empty" `SelectExpandWrapper` instance instead of the expected value of `null`.

**Comment by ificator** [comment]
This seems to be the result of #2285 - in the repro the value of `_dataSourceProviderKind` is `DataSourceProviderKind.None`, which means the null check that was previously taking place is not. As a result, `resourceContext.GetPropertyValue("Complex")` returns a `SelectExpandWrapper` with no container, `UseInstanceForProperties = true`, and `Instance = null`. This is not enough for the system to know what properties exist and so it throws the `InvalidOperationException`.

**Comment by mikepizzo** [comment]
It appears that we should be adding the null check if _dataSourceProviderKind == DataSourceProviderKind.None.

Alternatively, perhaps we should be checking for the cases where we *don't* do the null check, and make doing the null check the default?

**Comment by ificator** [comment]
I'm wondering if `GetDataSourceProviderKind` should default to `InMemory` instead of `None`.. it's trying to derive the source from the `IQueryable` instance and so if it's not one of the `EF*` variants we can probably assume it's an in-memory source.

**Comment by ificator** [comment]
Here's a unit test repro and possible fix:
https://github.com/OData/WebApi/compare/master...ificator:issue2316

**Comment by VatroslavSrzic** [comment]
I have stumbled upon this today and after examining the source code and debugging my project have concluded that the `GetDataSourceProviderKind(...)` is the source of the problem, same as @ificator.
However, unlike @ificator, I think that default should stay `None `but new case should be introduced for `Linq2ObjectsQueryProviderNamespace` (constant already defined in `HandleNullPropagationOptionHelper`) with return value of `InMemory`.

So the suggestion is:
```
public static DataSourceProviderKind GetDataSourceProviderKind(this IQueryable query)
{
	string queryProviderNamespace = query.Provider.GetType().Namespace;
	switch (queryProviderNamespace)
	{
		case EntityFrameworkQueryProviderNamespace:
		case Linq2SqlQueryProviderNamespace:
		case ObjectContextQueryProviderNamespaceEF5:
		case ObjectContextQueryProviderNamespaceEF6:
			return DataSourceProviderKind.EFClassic;

		case ObjectContextQueryProviderNamespaceEFCore2:
			return DataSourceProviderKind.EFCore;

		case Linq2ObjectsQueryProviderNamespace:
			return DataSourceProviderKind.InMemory;

		default:
			return DataSourceProviderKind.None;
	}
}
```

**Comment by ificator** [comment]
That seems reasonable.

If we limit `InMemory` to `System.Linq` I think we'll need to change this check to ensure the behavior is what it used to be for custom implementations of `IQueryProvider`:
```
            if (_dataSourceProviderKind == DataSourceProviderKind.EFCore ||
                _dataSourceProviderKind == DataSourceProviderKind.InMemory)
            {
                nullCheck = GetNullCheckExpression(structuralProperty, propertyValue, subSelectExpandClause);
            }
```
Going back to what @mikepizzo said, perhaps we should change this to explicitly exclude the one known case that has issue with the null check and leave all others with the null check in place.

**Comment by xuzhg** [comment]
@ificator @VatroslavSrzic Thanks for investigation and discussion. Would you please share a contribution by a pull request? We'd love to use the PR to create a nightly or hot fix to try.

**Comment by ificator** [comment]
I have an update based on what @VatroslavSrzic suggested - I'll push it now.

**Comment by xuzhg** [comment]
Merged at https://github.com/OData/WebApi/commit/50a759df9d451e002f58d26a2b425207cb8b4221
