### ISSUE TITLE
Injecting additional children filters or filtering resulting list of objects

### ISSUE THREAD

**Issue by EvilVir** [OData/WebApi#2353]
Hi,

I have standard GET method, that returns `IQueryable<T>` and `[EnableQuery]` sitting on top of it. I'm able successfully interact with this endpoint via OData protocol. The problem is that my `T` has some child collections which I need to filter based on some property of each of the object.

To make an example, let's assume following code:

```
public class MyModel
{
    public int Id { get; set; }
    public ICollection<MyChildModel> Children { get; set; }
}

public class MyChildModel
{
    public int Id { get; set; }
    public int Rank { get; set; }
}

public class MyODataController : ODataController
{
    [EnableQuery]
    public IQueryable<MyModel> GetAll() =>
        dbContext.MyModels.AsQueryable();
}
```

And now I need to ensure, that whenever somebody expands `Children` property with OData query, only children with value of property `Rank` higher than 4 will be returned. To make things more complicated, threshold value is not static, but depends on claims that user has.

I tried following approaches and with each and everyone I hit the wall at some point:

1. Just make `Children` property ignored on OData model and instead introduce `FilteredChildren` property (ignored on EF side in turn) that would apply the filtering on fly. Cool but there's no access to current HttpContext from within that property, so I can't obtain threshold claim.

2. Extend `EnableQueryAttribute` and "just" add/alter FilterClauses where needed. No-go because somebody clever decided to make all setters private (really, why???) I can workaround this with reflection obviously but that's hacky + there is one more problem: although entry-point `ODataQueryOptions` does have `Context` property, from which I can obtain CLR Type, the `IEdmType` descriptors used deeper in the `SelectExpand` structures have no means to tell what CLR Type they refer to (again, why???). On top of that instead of using standard C# Expressions, there is some strange OData-specific expressions replacements used (why?!?!?!?). All in all doable but in like 10000 lines of code probably.

3. Next approach - capture the output in `IActionFilterAttribute.OnActionExecuted` or `EnableQuery.OnActionExecuted` - no go, OData at this point didn't yet kicked in, all I have here is plain `IQueryable<T>` returned from my method, no filters OData applied yet.

4. EF Core global filters. Doable but let's face it - this feature of EF has issues on its own + that means that I will need to call `.DisableFilters()` everywhere but my `GetAll` method. Not great solution.

5. Last one I tried - use `ODataQueryOptions<T>` as a parameter of my `GetAllFunction` and then call its `.ApplyTo`. Well ok but there is no way to obtain final in-memory list of `T` objects. Because, depending on what OData query user used, the resulting `IQueryable` carries different types - sometimes it's just my `T` and more often some `Microsoft.AspNet.OData.Query.Expressions.SelectExpandBinder.SelectAllAndExpand<T>` which is also marked as internal (you guys surely love hiding everything from library users :)

6. This one I didn't tried yet as it already looks cumbersome - I can take `ODataQueryOptions<T>` input parameter and do all the filtering, counting, selecting and expanding on my own. I would effectively rewrite OData library probably :D Not going that way, nope.

So, what I'm missing. I don't believe that such basic feature as ability to limit what's inside expanded collections is not there. There must be a way if anything then for security reasons at least! Help me out here, how to filter these expanded childrens?

**Comment by anranruye** [comment]
Just do the following:

```
public class MyModel
{
    public int Id { get; set; }
    public **IEnumerable**<MyChildModel> Children { get; set; } 
}

public class MyChildModel
{
    public int Id { get; set; }
    public int Rank { get; set; }
}

public class MyODataController : ODataController
{
    [EnableQuery]
    public IQueryable<MyModel> GetAll()
    {
        var claim = GetClaim(User);
        return  dbContext.MyModels.Select(e => new MyModel
        {
               Id = e.Id,
               Children = e.Children.Where(child => child.Rank > claim)
        } );
    }
}

```

Before transfer the IQueryable<T> object to OData, do the filtering yourself, and leave other things to OData.

If you use EF Core, it's Ok. If you use EF, mapping from MyModel to MyModel is invalid, you might need a Dto type to map to.

Notice that the type of Children property is IEnumerable<T> which avoid to call ToList() after Where method. A call to ToList() may cause trouble for the further query of OData.

If you have many navigation properties in the entity type, be sure there is always a $select query option provided by the api consumer. If the consumer does not provide, you can add it yourself like this:

```

protected void AddODataSelectQueryOption<TEntity>()
        {
            if (Request.Query["$select"].Count == 0)
            {
                Request.QueryString = Request.QueryString.Add(QueryString.Create(new Dictionary<string, Microsoft.Extensions.Primitives.StringValues>
                {
                    {
                        "$select", 
                        new [] 
                        {
                            string.Join(',', typeof(TEntity).GetProperties().Select(pi => pi.Name))
                        }
                    }
                }));
            }
        }

```
If there is no $select parameter,  all navigation properties included in the select clause will be taken from database. These properties will not be searilized by odata searlizer, so there is no risk to expose these data. However, database resources are spent.

I think using EF Core global filters is a better approach if the filter is widely used, just like its name 'global'. However, as you said, global filter has its own issues and can't use in all scenarios.

**Comment by EvilVir** [comment]
Hm, that looks promising, thank you @Sreejithpin, I will give it a shot tomorrow! But this looks really good if it's still able to do other filtering and expands as API consumer desires then I'll take that additional database calls hit for sake of simplicity.

Anyway, as a feature proposition it would be great to be able to provide filtering function when configuring EDM model, something like:

```myEdmModel.EntitySet<MyEntity>().Property(nameof(MyEntity.SubCollectionProperty)).HasFilter((entity, context) => true)```

Where `context` would be able to carry `IServiceProvider` (so probably can be just current `HttpContext` and then such delegate would be applied by OData everytime certain collection is expanded, that would solve sooooo much problems with access-control.

Anyway, thanks again for your input, I will check that tomorrow and see if that solves my issue :)

**Comment by anranruye** [comment]
@EvilVir 

friend, I must inform you that I am not the guy who from the odata team. my answer is not on behalf of official. it works in my own app, but I can not promise it's suitable for you. before an official answer, be caution. I want to know their ideas too.

**Comment by anranruye** [comment]
is there anything wrong with my approach? @Sreejithpin

**Comment by EvilVir** [comment]
@anranruye ah, sorry I marked @Sreejithpin instead of you :D Anyway yes, I do understand that and I also understand (most of) implications. But hey! If that works, I'll take it. Haven't yet a chance to check this out (working on something else at the moment) but it really looks like what I can use. Thanks again! Will let you know how it went.

**Comment by EvilVir** [comment]
Hey @anranruye it's working :) Thanks, this is really helpful! By changing from `ICollection` to `IEnumerable` I lost the ability to add items directly to this collection, but I can live with it or make some passthrough when needed. But yep, filtering of child collection is working!

As a side note: EF Core 5 was just released and it has filterable includes, this combined with `ODataQueryOptions` can also be some solution. 

Both solutions aren't perfect, as still one needs to do all this manually with usage scenario context in mind which can become cumbersome when collection that has to be filtered is deeper than directly on the main entity, but it's working.

Thanks again!

**Comment by anranruye** [comment]
@EvilVir 

A good news is that there is no need to use IEnumerable with ef core 5. Calling to tolist() does not throw errors any more. 

For filterable includes,  yes it is better in this scenario. As I know,  this attribute is  implemented by some extension libraries early before ef core 5, like ef plus wrote by zzz project.This time ef team include this attribute in ef core package. I just forgot it(never used it in both packages before). 

And there are things 'filterable includes' can't do. In my own app,  I use the pre-select to change the result from database.  For example,  hiding harmful or secret information. The flag fields which judge harmful or not may be removed from the final result by odata $select query option,  so this must be done before odata doing its own work. And sometimes I do calculation in the select method. In this way,  I think pre-select(also called projection?) can be more widely used. 

I don't think it's possible to do these works in a more intelligent way,  doing all things manually could be necessary sometimes. AutoMapper may help(it can also do projection to IQueryable object besides mapping between normal CLR types), but I'm not sure. Now I'm interested in whether new 'with' clause in c# 9 can use in expression,  but haven't a try.  If it works,  it helps to reduce codes related to properties not changed, like 'Id = e. Id'. 

It's a pleasure to discuss with you.

**Comment by KenitoInc** [comment]
This question seems to have been answered.
Let me close this issue
