### ISSUE TITLE
.net 5.0 ComponentModel.DataAnnotations dependency conflict in v8.0.0-preview2

### ISSUE THREAD

**Issue by engenb** [OData/WebApi#2357]
I'm updating a project to .net 5 runtime.  I'm intending to use the latest EF Core release with OData which I'd bet is a common expected configuration.

The latest EF Core (5.0.0) has a dependency on ComponentModel.Annotations >= 5.0.0

```AspNetCore.OData v8.0.0-preview2``` has a dependency tree as such:
```Microsoft.AspNetCore.OData 8.0.0-preview2``` > ```Microsoft.Odata.ModelBuilder 1.0.4``` > ```System.ComponentModel.Annotations (>= 4.6.0 && < 5.0.0)```
This version constraint of ```< 5.0.0``` causes a conflict with other recently released .net 5 libs (like EF Core) that specify a version constraint of ```ComponentModel.Annotations >= 5.0.0```.

I just wanted to check to see if this is intended to stay this way for the final 8.0 release.

Thanks!

**Comment by xuzhg** [comment]
Update the ModelBuilder repo, see at: https://github.com/OData/ModelBuilder/commit/085446190a61999042e0a727e557c35ad07aa210

**Comment by engenb** [comment]
I specifically installed the new Microsoft.Odata.ModelBuilder released today (1.0.5) and this resolved the issue

**Comment by AGDholo** [comment]
Has the problem been solved? My .net 5 app still has this error.
