### ISSUE TITLE
.net 5 System.ComponentModel.Annotations conflict in v8.0.0-preview2

### ISSUE THREAD

**Issue by AGDholo** [OData/WebApi#2365]
I started a new ASP. Net 5 program, install oData return error.

### Assemblies affected

Microsoft.EntityFrameworkCore.Sqlite 5.0.0 -> Microsoft.EntityFrameworkCore.Sqlite.Core 5.0.0 -> Microsoft.EntityFrameworkCore.Relational 5.0.0 -> Microsoft.EntityFrameworkCore 5.0.0 -> System.ComponentModel.Annotations (>= 5.0.0)
vapour -> Microsoft.AspNetCore.OData 8.0.0-preview2 -> Microsoft.OData.ModelBuilder 1.0.4 -> System.ComponentModel.Annotations (>= 4.6.0 && < 5.0.0).

### Deps lits

``` xml
  <ItemGroup>
    <PackageReference Include="AutoWrapper.Core" Version="4.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.0" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.0" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
  </ItemGroup>
```

**Comment by xuzhg** [comment]
@AGDholo To update the Microsoft.OData.ModelBuilder to 1.0.5 can resolve this problem.

**Comment by AGDholo** [comment]
@xuzhg Thanks!

Give some tips to anyone who encounters the same mistake next:

Install Microsoft.OData.ModelBuilder first,
Then add Microsoft.AspNetCore.OData.
