### ISSUE TITLE
$select doesn't work with MongoDB Driver

### ISSUE THREAD

**Issue by SymbioticKilla** [OData/WebApi#2366]
Hi,

there is an old bug with $select on MongoDB driver:
https://jira.mongodb.org/browse/CSHARP-1423
The last answer from devs was back in 2016:
```
I'm not completely positive this is our issue. 
OData does some very interesting things with an expression tree which require us to handle special OData specific types. 
We don't have any current plans to handle this. I'll bring it up in our next planning meeting.
```
Is it a problem on MongoDB Driver site or can it be fixed in odata?

Thank you!

### Assemblies affected
Microsoft.AspNetCore.OData 7.5.1
MongoDB.Driver 2.11.3

### Reproduce steps

any $select query using mongoDB Driver in backend

### Expected result

Result with selected columns

### Actual result
Exception:
"message": "Value type of serializer is Microsoft.AspNet.OData.Query.Expressions.PropertyContainer+AutoSelectedNamedProperty`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] and does not match member type Microsoft.AspNet.OData.Query.Expressions.PropertyContainer. (Parameter 'serializer')",

**Comment by marabooy** [comment]
@SymbioticKilla could you kindly share the version of WebApi you are using plus the EF version and MongoDB driver version.

**Comment by SymbioticKilla** [comment]
@marabooy Sorry, I have updated first Post.
Addeded to Assemblies affected:
Microsoft.AspNetCore.OData 7.5.1
MongoDB.Driver 2.11.3

**Comment by SymbioticKilla** [comment]
I've got an answer form MongoDB Driver Team:
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/59652865/100321597-3a68b180-2fc3-11eb-9517-fa1aa7143452.png)

They are working on solution(new LINQ implementation):
[[CSHARP-1771] Support IIF method in LINQ - MongoDB](https://jira.mongodb.org/browse/CSHARP-1771)

If there is no things to improve on oData site you can close this issue.

Thank you!

**Comment by marabooy** [comment]
Thanks @SymbioticKilla  I will go ahead and close the issue.
