### ISSUE TITLE
ArgumentNullException if expanded items count is greater than PageSize

### ISSUE THREAD

**Issue by TomekPi** [OData/WebApi#2367]
ArgumentNullException is thrown for queries with $expand property, when properties count is larger than set PageSize.

### Assemblies affected

Microsoft.AspNet.OData 7.5.2

### Reproduce steps

1. Describe method with attribute `[EnableQuery(PageSize = 1)]`
2. `Members` collection contains more than 1 item
3. Run query which includes `$expand=members` parameter

### Expected result

Return 1 element with 1 `members` item.

### Actual result

Exception is returned:
``{
  "error": {
    "code": "",
    "message": "An error has occurred.",
    "innererror": {
      "message": "The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; odata.metadata=minimal'.",
      "type": "System.InvalidOperationException",
      "stacktrace": "",
      "internalexception": {
        "message": "Value cannot be null.\r\nParameter name: uri",
        "type": "System.ArgumentNullException",
        "stacktrace": "   at Microsoft.OData.ExceptionUtils.CheckArgumentNotNull[T](T value, String parameterName)\r\n   at Microsoft.OData.UriParser.ODataUriParser..ctor(IEdmModel model, Uri serviceRoot, Uri uri, IServiceProvider container)\r\n   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.GenerateQueryFromExpandedItem(ODataSerializerContext writeContext, Uri navigationLink)\r\n   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.GetNestedNextPageLink(ODataSerializerContext writeContext, Int32 pageSize, Object obj)\r\n   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)\r\n   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteExpandedNavigationProperties(SelectExpandNode selectExpandNode, ResourceContext resourceContext, ODataWriter writer)\r\n   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)\r\n   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)\r\n   at Microsoft.AspNet.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__22.MoveNext()"
      }
    }
  }
}``

### Additional detail

The same behavior when `Members` property has set PageSize property using model attribute or Fluent API configuration.

**Comment by KenitoInc** [comment]
Hey @TomekPi 
Kindly share a full repro code if possible, so that we can investigate this issue.
Thanks

**Comment by NAGENDR4** [comment]
Hi @karataliu  we are also facing the similar issue, can you please let us know the planned release date for this bug.

**Comment by karataliu** [comment]
cc @xuzhg

**Comment by NAGENDR4** [comment]
@xuzhg  -  Is there any ETC for above issue. If so, can you please let us know.

**Comment by niksonnet** [comment]
@xuzhg / @karataliu / @KenitoInc - Thanks for looking into this issue.

I am facing this issue for the last few months, is there any way to handle it in a more meaningful way till It is fixed?
or can I catch the exception in EnableQueryAttribute and insert my custom error message? 

I.e
`{
  Author : "John Doe", 
  Books : [
	    { Title : "1" , ISBN : "xxxxx-xxxxx-xxxxx...."},
	    { Title : "111" , ISBN : "xxxxx-xxxxx-xxxxx....."},
	    { Title : "2221" , ISBN : "xxxxx-xxxxx-xxxxx...."},
	    { Title : "1334" , ISBN : "xxxxx-xxxxx-xxxxx...."},
	    { Title : "1444" , ISBN : "xxxxx-xxxxx-xxxxx....."},
	    { Title : "155333" , ISBN : "xxxxx-xxxxx-xxxxx....."},
	    { Title : "15667" , ISBN : "xxxxx-xxxxx-xxxxx......"},
	    {
                Custom Error Message to handle.
		/*
			"Message" : Value cannot be null.\r\n Parameter name: uri,
			"Source" : "Microsoft.OData.Core",
			"StackTrace": " ............................................"
		*/
	    }
          ] 	
}`

**Comment by KenitoInc** [comment]
Closing this since the customer did not share a full repro.

@TomekPi  Feel free to reopen this if you need more assistance.
