### ISSUE TITLE
Wrong dependencies in version 7.5.4

### ISSUE THREAD

**Issue by HGSandhagen** [OData/WebApi#2391]
I created a new WebApi project and added package "Microsoft.AspNetCore.OData".

When building, I got a lot of errors from the controllers: 
error CS1705: Assembly "Microsoft.AspNetCore.OData" mit Identität "Microsoft.AspNetCore.OData, Version=7.5.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" verwendet "Microsoft.OData.Core, Version=7.7.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" mit einer höheren Version als die referenzierte Assembly "Microsoft.OData.Core" mit Identität "Microsoft.OData.Core, Version=7.7.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35".  

Explicitly added package "Microsoft.OData.Core" (which adds version 7.8.1) solves the problem.

**Comment by snebjorn** [comment]
This has been merged and released.

Please close.

**Comment by xuzhg** [comment]
Yes. It's fixed in 7.5.5
