### ISSUE TITLE
Not existing property should return error in OpenTypes

### ISSUE THREAD

**Issue by komdil** [OData/WebApi#2392]
When I select not exising property it is returning empty value instead of error. 

### Assemblies affected

I am using Microsoft.AspNetCore.OData
```

public class Student
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public IBackpack Backpack
        {
            get
            {
                return new Backpack() { Id = Guid.NewGuid() };
            }
            set
            {

            }
        }

        Dictionary<string, object> interfaces;
        public Dictionary<string, object> Interfaces
        {
            get
            {
                if (interfaces == null)
                {
                    interfaces = new Dictionary<string, object>
                    {
                        { "Backpack", this.Backpack as Backpack }
                    };
                }
                return interfaces;
            }
            set
            {
            }
        }
    } 

```
Send query `https://localhost:44383/odata/Student?$select=XYZ`

### Expected result

I am expecting an error: property XYZ couldn;t be found on entity......

```
{
    "@odata.context": "https://localhost:44383/OData/$metadata#Student/ODataCoreTest.EntityBase(XYZ)",
    "value": [
        {}
    ]
}
```

### Additional detail

I found some workarrounds on selecting properties but I have trouble with complex queries like expand and filter

**Comment by xuzhg** [comment]
@komdil  The empty value is expected.

**Comment by komdil** [comment]
> @komdil The empty value is expected.

What is the reason of returning empty value? Dictionary and model does not contain this property. It looks like a bug

**Comment by komdil** [comment]
Workarround was shown here: https://stackoverflow.com/questions/65627495/how-to-turn-off-using-non-existing-property-of-opentypes-in-odata/65770754#65770754
