### ISSUE TITLE
Action Parameter is null

### ISSUE THREAD

**Issue by friendbool** [OData/WebApi#2394]
Any Action with name equals to a field of the bounded entity causes the parameter ODataActionParameter to be always null. No issues instead if the action name is different.

### Assemblies affected

Microsoft.AspNetCore.OData 7.4.1 + asp net core 3.1

### Reproduce steps

``` csharp
public class MyEntity
{
  public string Id{get;set;}
  public IEnumerable<string> MyField { get; set; }
}

builder.EntitySet<MyEntity>("MyEntities");
var myEntityType = builder.EntityType<MyEntity>();
var action = myEntityType.Action("MyField");
action.CollectionParameter<string>("myValues");
action.ReturnsFromEntitySet<MyEntity>("MyEntities");

public class MyEntitiesController : ODataController
{
  [HttpPost]
  [ODataRoute("MyEntities({key})/MyField")]
  public IActionResult MyField([FromODataUri]string key, ODataActionParameters parameters)
  {
    // parameters is null
  }
}
```

### Expected result

parameters is not null

### Actual result

parameters is null

**Comment by xuzhg** [comment]
@friendbool 

Although it's valid to define a bound action name same as the property name of entity type, it's not "recommended" to define that.
 
However, in your scenario, it should work if you put the namespace in the attribute.

` [ODataRoute("MyEntities({key})/YourNameSpace.MyField")]`
