### ISSUE TITLE
Named Streams

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#24]
WCF DataServices enables attaching streams to entities by marking them with
HasStreamAttribute and implementing IDataServiceStreamProvider. There is
currently no equivalent support in WebApi.  

Adding support would enable a NuGet compatible data source to be implemented
in WebApi, where today it is not possible to provide the src attribute on the
content element (see [ http://nuget.org/api/v2/Packages/?$top=1
](http://nuget.org/api/v2/Packages/?$top=1) for an example).  
## Work Item Details

**Original CodePlex Issue:**    [Issue 770](http://aspnetwebstack.codeplex.com/workitem/770)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Jan 14, 2013 at 6:14 PM
**Reported by:**    chriseldredge
**Updated on:** Sep 23, 2013 at 7:30 PM
**Updated by:** danroth27

**Comment by LianwMS** [comment]
On *2013-01-24 06:39:36 UTC*, **danroth27** commented:

We will look at supporting named streams in a future release.

**Comment by LianwMS** [comment]
On *2013-04-02 01:38:37 UTC*, **HongmeiG** commented:

OData formatter extensibility has made this scenario very simple.

**Comment by LianwMS** [comment]
On *2013-04-02 02:56:51 UTC*, **chriseldredge** commented:

Is there an example somewhere or some documentation on how I can use OData formatter extensibility to accomplish this?

**Comment by LianwMS** [comment]
On *2013-04-02 03:11:00 UTC*, **HongmeiG** commented:

The spec should be posted to 
http://aspnetwebstack.codeplex.com/wikipage?title=OData%20formatter%20extensibility soon.

**Comment by congysu** [comment]
Related issue: https://github.com/OData/WebApi/issues/149

**Comment by congysu** [comment]
Related issue https://github.com/OData/WebApi/issues/328
