### ISSUE TITLE
FunctionImport with IncludeInServiceDocument set to true does not appear in service document

### ISSUE THREAD

**Issue by karataliu** [OData/WebApi#240]
http://services.odata.org/TripPinWebApiService/$metadata

There's a function import:
```xml
<FunctionImport Name="GetNearestAirport" IncludeInServiceDocument="true" EntitySet="Airports" Function="ODataSamples.WebApiService.Models.GetNearestAirport"/>
```

but in service document, it does not appear.

**Comment by congysu** [comment]
This is for our [sample service]( https://github.com/OData/ODataSamples/tree/master/Scenarios/TripPin/src/webapi).  We might need to update it to use latest version of OData Web API.

**Comment by xuzhg** [comment]
Hi, @karataliu 
[OData V4 spec ](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part3-csdl/odata-v4.0-errata02-os-part3-csdl-complete.html#_7.1_The_edm:ComplexType) says:
The edm:FunctionImport for a **parameterless** function MAY include the IncludeInServiceDocument attribute whose Boolean value indicates whether the function import is advertised in the service document.

Web API OData follows up this spec. So, only function import for a **parameterless** function and include the "IncludeInServiceDocument" attribute with "true" value will be advertised in the service document.

**Comment by xuzhg** [comment]
@karataliu, if you have further concern, please re-active it. Thanks.
