### ISSUE TITLE
Problem how i delet it?

### ISSUE THREAD

**Issue by zeeedooo** [OData/WebApi#2405]

**Comment by xuzhg** [comment]
@zeeedooo Would you please provide detail information about your question?

**Comment by marabooy** [comment]
Hi @zeeedooo to create a delete enpoint while using WebApi Kindly follow the [documentation here](https://docs.microsoft.com/en-us/odata/webapi/getting-started) an on step D add the following method below the defined Get method.

```csharp
        public IActionResult Delete(int key)
        {
            // logic to remove the item from the store.
            return NoContent();
        }
```
If this doesn't work/answer your question kindly do open a new Issue while providing more information.
