### ISSUE TITLE
OData AspNetCore support for long URLs useing $query is not working

### ISSUE THREAD

**Issue by navidzehi** [OData/WebApi#2414]
### Expected result
_For more elegant view of this issue please visit the question on [stackoverflow](https://stackoverflow.com/questions/65611721/odata-aspnetcore-support-for-long-urls-useing-query-is-not-working)._

As it is been pointed in [this ](https://devblogs.microsoft.com/odata/passing-odata-query-options-in-the-request-body/) article, with $query keyword you can solve the problem of long OData URLs after the version **7.5** of Microsoft.AspNetCore.OData.

but in my project(I tried both version **8.preview3** and 7.5.4) I tried the use this but I keep getting 404 not found error. Here are my working URL examples:
```

https://localhost:44346/odata/WFC/APost/
https://localhost:44346/odata/WFC/APost/?$select=id
...
```
but when I use a POST request with $query I receive 404 error:
```

POST: https://localhost:44346/odata/WFC/APost/$query
    Content-Type: text/plain
    Request Body: $select=id
```

I wonder if I have to add any code to enable the $query functionality !?
Here are relevant pieces of my code :

```
// version 8.preview3 of Microsoft.AspNetCore.OData code

     services.AddOData(
           opt => opt.AddModel("odata", GetEdmModel()).Select().Count().Filter().OrderBy().SetAttributeRouting(true));
    
    ...
    
     public IEdmModel GetEdmModel()
            {
                var builder = new ODataConventionModelBuilder();
                var s = builder.EntitySet<WeatherForecast>("WFC").EntityType;
                s.Collection.Action("APost");
                return builder.GetEdmModel();
            }
```

and the controller :

```
[ODataRoutePrefix("WFC")]
    public class WeatherForecast2Controller : ODataController
    {
     ...
        [HttpPost]
        [EnableQuery]
        [ODataRoute("APost")]
        public IEnumerable<WeatherForecast> APost()
        {
            // this function just returns array of 10 WeatherForecast(s) . 
            ...
        }

    }
```

### Additional detail

version 8.preview3 
version 7.5.4

**Comment by gathogojr** [comment]
@navidzehi The short answer is that the `$query` feature doesn't work with actions. As the protocal states, [alternative for **GET requests** is to append /$query to the resource path of the URL, use the POST verb instead of GET, and pass the query options part of the URL in the request body](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_PassingQueryOptionsintheRequestBody). Actions are implemented on the controller with the POST.
FYI, internally we just transform the $query POST request into a GET such that its handled by the HttpGet action methods on your controller.

**Comment by navidzehi** [comment]
@gathogojr Thank you for your answer. So what should I do now ? I used POST method and did exactly as the examples. What change should I apply to my controller.

**Comment by gathogojr** [comment]
@navidzehi It will work with any HttpGet action methods decorated with the `EnableQuery` attribute.
For example,

```csharp
[EnableQuery]
[HttpGet]
[ODataRoute("AGet")]
public IEnumerable<WeatherForecast> AGet()
{
    // this returns array of 10 WeatherForecast(s) . 
    ...
}
```

Then you can send a POST request to the $query endpoint as follows
```
POST: https://localhost:44346/odata/WFC/AGet/$query
Content-Type: text/plain
Request Body: $select=id
```

**Comment by navidzehi** [comment]
@gathogojr 

It worked. Thank you for your answer. I should have create a HttpGet method but send a POST request to it with $query at the end.

**Comment by conradyacat** [comment]
@gathogojr Can you please add an example how to make this work with version 8.0.6? I have followed this and has made some changes to use version 8.0.6 but it returning 404 for Post request.

https://github.com/MicrosoftDocs/OData-docs/blob/main/Odata-docs/webapi/query-options-in-request-body.md

**Comment by navidzehi** [comment]
@conradyacat You may also have my problem. You should create a GET method but call it as a POST method.

**Comment by conradyacat** [comment]
@navidzehi That is what I have tried. However, I found you have to ensure to add this OData middleware when using version 8.0.6.

`app.UseODataQueryRequest(); `

If anyone is also encountering this issue, you can refer to the sample code:

[](https://github.com/OData/AspNetCoreOData/blob/main/sample/ODataRoutingSample/Startup.cs)

**Comment by antonio-cordoba** [comment]
/$query is not working for me :(  ... I get 
`HTTP/1.1 405 Method Not Allowed`
`Content-Length: 0`
`Connection: close`
`Date: Tue, 16 Aug 2022 21:21:25 GMT`
`Server: Kestrel`
`Allow: DELETE, GET, PATCH, PUT`
I use convention routing and my controller has all methods for GET, GET(id), POST, PATCH(id), PUT(id), and DELETE(id), so from the response above I take my request : `POST {{service}}/resource/$query` with query options in the body seems to be getting routed to something with an (id) and it somehow thinks /$query is the /id of the resource I'm trying to affect.   I do have `app.UseODataQueryRequest();` but it doesn't make a difference with or without it.

**Comment by Ivan-Leshchanka** [comment]
I have the same issue. I consistently receive a 404 status code when making this request: 'request'.
I'm using oData version 8.2.3.

Endpoint:

**Comment by karthikd70** [comment]
@MrMTaylor Thank you for the suggestion. I had to correct "plain/text" to "text/plain". Hope it helps someone.
