### ISSUE TITLE
Enum prefix free doesn't work for function parameter

### ISSUE THREAD

**Issue by karataliu** [OData/WebApi#243]
We have a bound function named "GetCustomerByGender", with an enum parameter named "gender", type is Enum type.

~/Customers/Default.GetCustomerByGender(gender='Male')

Does not work:

{ "error":{ "code":"","message":"An error has occurred.","innererror":{ "message":"Expected literal type token but found token ''Male''.","type":"Microsoft.OData.Core.ODataException","stacktrace":" at Microsoft.OData.Core.UriParser.ExpressionLexerLiteralExtensions.ReadLiteralToken(ExpressionLexer expressionLexer)\r\n at Microsoft.OData.Core.UriParser.ODataUriUtils.ConvertFromUriLiteral(String value, ODataVersion version, IEdmModel model, IEdmTypeReference typeReference)\r\n at System.Web.OData.Routing.BoundFunctionPathSegment.GetParameterValue(String parameterName)\r\n at System.Web.OData.Routing.Conventions.ProcedureRoutingConventionHelpers.AddFunctionParameterToRouteData(HttpControllerContext controllerContext, BoundFunctionPathSegment functionSegment)\r\n at System.Web.OData.Routing.Conventions.FunctionRoutingConvention.SelectAction(ODataPath odataPath, HttpControllerContext controllerContext, ILookup`2 actionMap)\r\n at System.Web.OData.Routing.ODataActionSelector.SelectAction(HttpControllerContext controllerContext)\r\n at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)\r\n at System.Web.Http.Dispatcher.HttpControllerDispatcher.d__1.MoveNext()" } } }

**Comment by xuzhg** [comment]
Checked in. Thanks.
