### ISSUE TITLE
OData query returns next page link even tho item count is less than page size

### ISSUE THREAD

**Issue by ozanerdogan90** [OData/WebApi#2434]
Current behavior:
Recently we experience a bug on OData queries. when we use a query that doesnt include $top; oOData returns next page link even tho the entity count is less than the page size.
Ex : {{url}}/orders$filter=(id eq 'some guid value') .as this query only returns one item , next page link still exists and contains sth like : {{url}}/orders$filter=(id eq 'some guid value')&$skip=20

We rely on the next page to fetch all data and with that case it creates a loop and breaks our system

Expected;
Next page link is null when there is no more item with page size

**Comment by Sreejithpin** [comment]
Can you please share a Repro.? Also please let us know which version are you using

**Comment by KenitoInc** [comment]
@ozanerdogan90 Was your issue resolved?
If not kindly share a repro
