### ISSUE TITLE
Extend runtime Type methods of OperationConfiguration

### ISSUE THREAD

**Issue by bdebaere** [OData/WebApi#2439]
Because I am lazy I have an extension method which automatically registers all functions on my controllers to OData. This has been working fine for a long time. For single parameters I'm using the `OperationConfiguration.Parameter(Type,string)` method. However, such a method does not exist for the other parameter types, like collection parameter. To register the collection parameters I currently have to use System.Reflection to call the generic `OperationConfiguration.CollectionParameter` method. This seems like something which can easily be solved by simply adding these additional methods that can accept a runtime `Type`.

**Comment by xuzhg** [comment]
merged.
