### ISSUE TITLE
When using $expand asp.net core does not return the expanded collection when using ODataQueryOptions

### ISSUE THREAD

**Issue by mlop3s** [OData/WebApi#2441]
i've adapted an existing asp.net based rest api and although the query seems to work, the controller is not returning the expanded collection.

### Assemblies affected

Microsoft.AspNetCore.OData" Version="7.5.6"

### Reproduce steps

Use a ODataQueryOptions<GeminiIssue> options and try to expand a collection.

### Expected result

The expanded collection. See additional details.

### Actual result

Although the collection is expanded on the service side, the client does not receive it. See additional details.

### Additional detail

The Get is done like this:

``` C#
[HttpGet("projects/{projectId}/issues", Name = "GetOdataGeminiIssues")]
[Produces("application/json")]
[ProducesResponseType(typeof(IQueryable<GeminiIssue>), Status200OK)]
[ProducesResponseType(Status400BadRequest)]
public async Task<IActionResult> GetGeminiIssues(long projectId, ODataQueryOptions<GeminiIssue> options)
        {
            var issues = await _geminiRepository
                    .GetQueryableIssues(projectId)
                    .GetQueryAsync(_mapper, options, new QuerySettings { ODataSettings = new ODataSettings { HandleNullPropagation = HandleNullPropagationOption.False } });

            return Ok(issues);
        }
```
The EDM Model. I had only builder.EntitySet<GeminiIssue>("projects"); before, i've tried to define the relations to see if it works but no success there:

``` C#
        private static IEdmModel GetEdmModel()
        {
            var builder = new ODataConventionModelBuilder();
            var issue = builder.EntityType<GeminiIssue>().Expand(10).Filter().Count().Select().Page();
            issue.HasMany<GeminiIssueHistory>(x => x.HistoryItems);
            issue.HasMany<GeminiCustomField>(x => x.CustomFields);
            builder.EntitySet<GeminiIssue>("projects");

            builder.EntitySet<GeminiIssueHistory>(nameof(GeminiIssueHistory));
            builder.EntitySet<GeminiCustomField>(nameof(GeminiCustomField));
            return builder.GetEdmModel();
        }
```
The models - this are the DTOs that i map to from EF Core.
``` C#
    public class GeminiIssue
    {
        [Key]
        public decimal IssueId { get; set; }

        //... more properties

        public ICollection<GeminiIssueHistory>? HistoryItems { get; set; }

        public ICollection<GeminiCustomField>? CustomFields { get; set; }
    }

    public class GeminiIssueHistory
    {
        [Key]
        public decimal HistoryId { get; set; }
        
       //... more properties, however no link back to GeminiIssue
    }

```
The startup:
``` C#

            services.AddOData().EnableApiVersioning();

            services.AddODataApiExplorer(setupAction =>
            {
                setupAction.GroupNameFormat = "'v'VV";
                setupAction.SubstituteApiVersionInUrl = true;
            });
...
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();                
                endpoints.MapODataRoute("odata", "odata", GetEdmModel(), new DefaultODataBatchHandler());
                endpoints.Filter().OrderBy().Expand().Select().MaxTop(null);
            });
```
My request is straightforward:
http://localhost:45179/odata/projects/184/issues?$expand=HistoryItems&$top=1

But I get no expansions:

``` json
{
    "@odata.context": "http://localhost:45179/odata/$metadata#Collection(Gemini.Shared.Models.GeminiIssue)",
    "value": [
        {
            "@odata.type": "#Gemini.Shared.Models.GeminiIssue",
            "IssueId": 90318,
            "IssueTypeId": 101,
            "ReportedById": 179,
            "Sprint": "",
            "CreatedDate": "2021-01-18T00:00:00+01:00",
            "AcceptedDate": null,
            "ResolvedDate": null,
            "ClosedDate": null,
            "ProjectId": 184,
            "Summary": "Some issue",
            "IssueResolutionId": 1,
            "IssueStatusId": 17,
            "IssueKey": "ISSUE-90318",
            "Version": null,
            "Description": "",
            "Status": "taken",
            "IssueUri": null
        }
    ]
}
```
And the packages:
``` xml
    <PackageReference Include="AutoMapper.AspNetCore.OData.EFCore" Version="2.1.1" />
    <PackageReference Include="AutoMapper.Extensions.ExpressionMapping" Version="4.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="7.5.6" />
    <PackageReference Include="Microsoft.AspNetCore.OData.Versioning.ApiExplorer" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.PlatformAbstractions" Version="1.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.1.0" />
```
The strange thing is that if i execute the query, it shows me that the expanded items are there, but they do not reach the client:

![image](https://user-images.githubusercontent.com/2886188/111273224-d8948c00-8633-11eb-9629-e789783fe3f1.png)

Thanks,
Marco

**Comment by xuzhg** [comment]
1) What's the `issues` related to `Projects`? Can you share your metadata CSDL?

2) Your context URI `http://localhost:45179/odata/$metadata#Collection(Gemini.Shared.Models.GeminiIssue)` doesn't reflect the expand payload.  it looks like a normal collection

3) I don't have the codes about `GetQueryAsync`, did you call ApplyTo(...) method?

It's better to share us your repro to dig more.

**Comment by mlop3s** [comment]
Hi,

I'm preparing a a project for this issue here in GitHub.
Please give me 2 days.

1. projects is used as url but we do not have a project class as it's not needed to query it.
2. This is my first odata server project. I'm not sure what exactly i should expect there. Before i was returning IQueriable but as i'm using AplyTo I saw no reason why to return it. When I se a breakpoint there the Expanded Collection is there, is just not reaching the client.
3. See 2

Thanks for the Feedback.

Cheers,
Marco

**Comment by mlop3s** [comment]
@xuzhg I've found the problem. As you said, it's related to the route
Changing 
       [HttpGet("projects/{projectId}/issues", Name = "GetOdataGeminiIssues")]
To
       [HttpGet("projects/{projectId}", Name = "GetOdataGeminiIssues")]

I wonder how can i get the first one working, without exposing the project entity?

Thanks.
Cheers
