### ISSUE TITLE
For an Odata API the DataMember name is not reflecting in the API response

### ISSUE THREAD

**Issue by Vasumithra23** [OData/WebApi#2443]
Hi,

I have a C# class called students.cs with the below property:

[DataMember(Name = "dept_no")]
public byte DeptNo { get; set; }

The problem is that I am getting DeptNo instead of dept_no in the API response.If I disable the pagesize its working fine else not. Can you help me with this issue?

Thanks.

**Comment by xuzhg** [comment]
@Vasumithra23 Do you have [DataContract] on your C# class?  to be clear, DataMember works closely with [DataContract].

You mentioned "disable pagesize" makes it working. Can you share more codes related about it?

**Comment by Vasumithra23** [comment]
Hi @xuzhg 

Yes ,I have[DataContract] in C# class.
I have used EnableQuery in my controller, which is as follows:
//[EnableQuery(EnableCorrelatedSubqueryBuffering = true)]// without pagesize its working fine
//[EnableQuery(EnableCorrelatedSubqueryBuffering = true,PageSize =100)]// with pagesize its not giving desired output.

Could you me help with this issue?

Thanks.

**Comment by Vasumithra23** [comment]
Can you help me with this issue?
