### ISSUE TITLE
I cannot get the odata next page link for pagination

### ISSUE THREAD

**Issue by vutung3196** [OData/WebApi#2458]
Hi there, I am currently struggling with getting the next page ( "@odata.nextLink":...  ) for my rest API.
I am currently using .NET Core 5.0 and AspNetCoreOData 7.5.7
![image](https://user-images.githubusercontent.com/24209332/113408746-22be9100-93da-11eb-8efb-3aedec42bff1.png)

Here is my controller:
```
        [HttpGet]
        [EnableQuery(PageSize = 5)]
        // Pagination and searching
        public async Task<IActionResult> GetAll()
        {
            var a = (await (_patientService.GetAsync())).AsQueryable();
            return Ok(a);
        }

```

This is how I register Odata in Startup.cs
```
`     // Odata
            services.AddControllers(mvcOptions => mvcOptions.EnableEndpointRouting = false);
            services.AddOData();
`
```

```
            app.UseMvc(routeBuilder =>
            {
                routeBuilder.MaxTop(10).Expand().Filter().OrderBy().Build();
                routeBuilder.EnableDependencyInjection();
                routeBuilder.MapODataServiceRoute("odata", "odata", GetEdmModel());
            });
```

And I also write the GetEdmModel();

```
      IEdmModel GetEdmModel()
      {
          var odataBuilder = new ODataConventionModelBuilder();
          odataBuilder.EntitySet<PatientDto>("Patients");

          return odataBuilder.GetEdmModel();
      }
```

Hope you guys can help me.

**Comment by gathogojr** [comment]
@vutung3196 It looks like the OData serializer is not being invoked in your service. Does you controller inherit from ODataController?

**Comment by vutung3196** [comment]
Hi, I don't because I want something like {url}/api/patients to get the data instead of {url}/odata/...

**Comment by gathogojr** [comment]
@vutung3196 `api` and `odata` above are just route prefixes. Inheriting from `ODataController` with endpoint routing configured in your service should help you achieve what you're trying. Otherwise, when you inherit from `ControllerBase` directly, your service is falling back on ASP.NET Core serialization or Newtonsoft if you have that configured, leaving no room for OData to apply paging support.
Here is an article demonstrating Endpoint routing in OData https://devblogs.microsoft.com/odata/enabling-endpoint-routing-in-odata/

**Comment by vutung3196** [comment]
Thanks for your information, but in your suggested article, I don't see the Author uses the OdataController, he actually uses ControllerBase.

**Comment by vutung3196** [comment]
But yeah I will try the OdataController inheriting approach.

**Comment by vutung3196** [comment]
Hi @gathogojr , I use this approach but cannot get the `@odata.nextLink`
![image](https://user-images.githubusercontent.com/24209332/114516865-00ddcd80-9c68-11eb-8daf-062e67d6219f.png)
Hope u can support me. Thanks.

**Comment by gathogojr** [comment]
Hi @vutung3196. Sorry it has taken me a bit of time to revert. I'm a bit swamped at the moment. Unfortunately, I'm not to repro your issue. I used to use code similar to what your supplied - _writing it a little differently where necessary for brevity_ - and I still get back `@odata.nextLink`

Service configuration:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers(options => options.EnableEndpointRouting = false);
    services.AddOData();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    var modelBuilder = new ODataConventionModelBuilder();
    modelBuilder.EntitySet<Patient>("Patients");

    app.UseMvc(routeBuilder =>
    {
        routeBuilder.MaxTop(10).Expand().Filter().OrderBy().Build();
        routeBuilder.EnableDependencyInjection();
        routeBuilder.MapODataServiceRoute("odata", "odata", modelBuilder.GetEdmModel());
    });
}
```
Controller:
```csharp
public class PatientsController : ControllerBase
{
    private static IList<Patient> patients = new List<Patient>(
        Enumerable.Range(1, 7).Select(idx => new Patient { Id = idx, Name = $"Patient {idx}" }));

    [EnableQuery(PageSize = 5)]
    public async Task<IActionResult> Get()
    {
        return await Task.Run(() => Ok(patients));
    }
}
```
Request:
```
http://localhost:port/odata/Patients
```
Response:
```json
{
    "@odata.context": "http://localhost:24318/odata/$metadata#Patients",
    "value": [
        {
            "Id": 1,
            "Name": "Patient 1"
        },
        {
            "Id": 2,
            "Name": "Patient 2"
        },
        {
            "Id": 3,
            "Name": "Patient 3"
        },
        {
            "Id": 4,
            "Name": "Patient 4"
        },
        {
            "Id": 5,
            "Name": "Patient 5"
        }
    ],
    "@odata.nextLink": "http://localhost:24318/odata/Patients?$skip=5"
}
```
Try to identify what you're doing differently, otherwise share a link to complete repro that we can look at.

**Comment by vutung3196** [comment]
Hi @gathogojr , I kinda use the same like you, you can see in my repro https://github.com/vutung3196/AffordableClinic/tree/feature/test-odata
in file PatientController and Startup.cs

**Comment by gathogojr** [comment]
@vutung3196 The link you shared opens a project that is too large to be considered a repro. It's hard to tell what is responsible for the issue you're observing. I'd advise you to dissect the issue by creating a very simple app, confirm that `@data.nextLink` is returned, then expand your investigation to the larger project.

**Comment by vutung3196** [comment]
Hi I think it's not that big project, I will take a look at a simple app though.

**Comment by vutung3196** [comment]
Happy to close this issue.
