### ISSUE TITLE
Freestyle or unobtrusive OData

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#246]
This can be one of the design goals of OData Web API vNext.  OData is a set of RESTful API conventions, and allow user to freely choose: model, query, formatting.

Currently, to create an OData service with OData Web API, user needs to:
1. Create an EDM model:
   -  Use OData conventional model builder: `builder.Entityset<Customer>("Customers")`
   -  Use OData model builder: `builder.EntityType<Customer>().HasKey(c => c.CustomerId)`
   -  Use EDM APIs
2. Map an OData route: `MapODataServiceRoute`
3. Create one or more OData Controllers: `ODataController`

In future, enabling OData should be as simple as:
`services.AddMvc().AddORest()`
`app.UseMvc().UseORest()`
and with a `DbContext` or optionally an `ApiContext`

``` c#
public class ApiContext
{
  public IEnumerable<Customer> Customers { get; set; }
  public IEnumerable<Order> Orders { get; set; }
}
```

**Comment by PinpointTownes** [comment]
I'm not sure OData vNext should be that simple: this kind of simplicity - that have been massively criticized during the WCF Data Services era - has a major downside: it hides the necessity to scrupulously think about each entity, each property, each navigation property you add and the security/performance implications it might have.

Actually, I would even suggest the opposite: making explicit model building mandatory to make sure people realize that exposing their whole domain without any limit is a bad idea: https://github.com/OData/WebApi/issues/229#issuecomment-78227463

On the other hand, it sounds like a nice objective for RESTier.
