### ISSUE TITLE
[NotNavigable] attribute doesn't work

### ISSUE THREAD

**Issue by snappyfoo** [OData/WebApi#2460]
I want to disable a simple property from being selectable, the documentation suggests this can be achieved with the [NotNavigable] attribute:

> NotNavigable -- $select
> https://docs.microsoft.com/en-us/odata/webapi/capabilities-vocabulary-support

Example given in documentation:
```C#
[NotNavigable]
public string Email { get; set; }
```

It has no effect for me - have confirmed that [NonFilterable] and [NotSortable] **do** work however.

**Comment by xuzhg** [comment]
https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/Builder/EdmModelHelperMethods.cs#L752-L756

**Comment by snappyfoo** [comment]
Thinking through this, it possibly doesn’t make any sense to make simple properties non-selectable as they would be selected by default and disabling select probably only makes sense for navigations that aren’t already auto-expanded. 

I was seeking a way to hide a property from all operations, but as I am hiding it in my response with JsonIgnore already, preventing select (if that is even a solid

**Comment by snappyfoo** [comment]
Use case which may help:

I want the key on my edm model to be hidden and protected. 

In my model I am applying these attributes: 
[Key, JsonIgnore, NonFilterable, NotSortable, NotNavigable]

JsonIgnore prevents it appearing when the full model is selected (the default case for us as everything auto expanded)

I need to confirm with data in place but I suspect if selecting just the key (eg by someone guessing the property name) then the Select wrapper dictionary that’s serialised might serialise it despite the JsonIgnore on the main model. What I do know for sure is get no error if I try to select the key (unlike when I try to filter or sort on it, which does produce the expected error.)

**Comment by xuzhg** [comment]
@snappyfoo 
[NotNavigable], [NotFiltable], etc are attributes introduced before the [capabilities vocabulary annotation](https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Capabilities.V1.xml). 

At that time, there's a miss-understanding about navigable. It considers navigable for $expand. 
See here: https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/Builder/EdmModelHelperMethods.cs#L808-L811
So, if you put this attribute on key property, it won't work.

As a workaround, you can create the serializer from ODataResourceSerializer and override the  CreateResource to exclude the hidden or protected property.
The process:
1) Create the vocabulary annotation using https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Capabilities.V1.xml#L319

2) in your serializer,  you can retrieve the vocabulary annotation from the model based on the edm property

3) exclude the property from ODataResource.Properties.

Hope it can help you.

**Comment by snappyfoo** [comment]
@xuzhg thank you, I’ll look into that more when at my desk. I have a slight suspicion this might be the wrong area for our use case. 

The converter used to serialise is this isn’t it?

https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/Query/Expressions/SelectExpandWrapperConverter.cs

Also is there a way to just prevent it being selected? Maybe a validator?

**Comment by xuzhg** [comment]
@snappyfoo the serializer is this: https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceSerializer.cs

a way to "prevent it being selected" is to customize a Filter. It's same as EnableQueryAttribute at: https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNetCore.OData/EnableQueryAttribute.cs#L37

You can do query validator in the `public override void OnActionExecuting(ActionExecutingContext context)`

**Comment by snappyfoo** [comment]
@xuzhg thanks, I’ll look into all this. We don’t use EnableQuery or other action filters, we manually build a SelectExpandQueryOption from a custom named query string param and ApplyTo our queryable and return that, not sure if this makes a difference, I will find out :)

**Comment by snappyfoo** [comment]
> @snappyfoo
> [NotNavigable], [NotFiltable], etc are attributes introduced before the [capabilities vocabulary annotation](https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Capabilities.V1.xml).
> 
> At that time, there's a miss-understanding about navigable. It considers navigable for $expand.
> See here: https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/Builder/EdmModelHelperMethods.cs#L808-L811
> So, if you put this attribute on key property, it won't work.
> 
> As a workaround, you can create the serializer from ODataResourceSerializer and override the CreateResource to exclude the hidden or protected property.
> The process:
> 
> 1. Create the vocabulary annotation using https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Capabilities.V1.xml#L319
> 2. in your serializer,  you can retrieve the vocabulary annotation from the model based on the edm property
> 3. exclude the property from ODataResource.Properties.
> 
> Hope it can help you.

I wasn't able to follow this.

I think there is fundamentally a bug that [JsonIgnore] is not respected when selecting a nested
