### ISSUE TITLE
AutoExpand has no effect on Entity returned from Function

### ISSUE THREAD

**Issue by papillon** [OData/WebApi#2465]
Setting the AutoExpand property on a navigation property does not work when that entity is returned from a function. This happens when the returned entity is not the same as the entity where the function is defined on.

### Assemblies affected

OData WebApi v7.5.7

### Reproduce steps

Here is your sample application extended with the following features to demonstrate the issue:
- order items 
- function to get a random order of a certain customer

 [samples/AspNetCore3xODataSample.Web](https://github.com/papillon/WebApi/commit/9477e514172d9e09dd46271c87ba3a9d67aa4dfa)

### Expected result

http://localhost:15580/odata/customers(1)/GetRandomOrder

`{
    "@odata.context": "http://localhost:15580/odata/$metadata#Order(Items())/$entity",
    "Id": 3,
    "Title": "abc1",
    "Items": [
        {
            "Id": 3,
            "Name": "Item A0",
            "Quantity": 5
        },
        {
            "Id": 4,
            "Name": "Item A1",
            "Quantity": 6
        }
    ]
}`

(notice the order items got auto-expanded)

### Actual result

`{"@odata.context":"http://localhost:15580/odata/$metadata#Order/$entity","Id":2,"Title":"abc0"}`

(AutoExpand has no effect)

### Additional detail

I think that is caused by the function GetAutoExpandRawValue() getting the auto expand navigation properties from Context.TargetStructuredType instead of Context.ElementClrType.

The following commit fixes the behaviour to return the expected result: [66b2b18](https://github.com/papillon/WebApi/commit/66b2b18072a4afd59633655da0547dc1df354741)

**Comment by ElizabethOkerio** [comment]
@papillon thanks for raising the issue and exploring a solution. Please do a PR so we can look at it and merge.

**Comment by ificator** [comment]
Just noticed this PR - looks like it's attempting to solve the same underlying issue that my new PR (https://github.com/OData/WebApi/pull/2565) is. If this approach (using `ElementClrType` instead of making sure `TargetStructuredType` is populated for operations) is the preferred I can close out my PR.

**Comment by KenitoInc** [comment]
Issue fixed by #2565
