### ISSUE TITLE
Solution does not build under Linux because of wrong lettercase in filenames

### ISSUE THREAD

**Issue by obohaciak** [OData/WebApi#2469]
*When building the WebApiOData.AspNetCore.sln under Linux, several files have wrong letter cases causing the compilation to fail. Case-insensitive OS like Windows is more permissive and does not fail to compile the solution.*

### Assemblies affected

Current master, as of 2020/04/20.

### Reproduce steps

Run `dotnet build ./sln/WebApiOData.AspNetCore.sln` in shell.

### Expected result

Solution compiles.

### Actual result

Compiler reports following errors:
```
##[error]CSC(0,0): Error CS2001: Source file '/home/vsts/work/1/s/src/Microsoft.AspNet.OData.Shared/Builder/NonbindingParameterConfiguration.cs' could not be found.
##[error]CSC(0,0): Error CS2001: Source file '/home/vsts/work/1/s/test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/PlainTextODataQueryOptionsParserTest.cs' could not be found.
##[error]CSC(0,0): Error CS1566: Error reading resource 'Microsoft.AspNet.OData.Test.Resources.ProductsCsdl.xml' -- 'Could not find file '/home/vsts/work/1/s/test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Resources/ProductsCsdl.xml'.'
```
### Additional detail

Clearly, the offending filenames were supposed to be Pascal-cased but either a part of the filename was not capitalized or an acronym did not follow .NET casing guideline.

**Comment by obohaciak** [comment]
The fix is trivial, I'll prepare a PR immediately.

**Comment by habbes** [comment]
@obohaciak  Thanks for raising this and for the quick PR. We'll review it.
