### ISSUE TITLE
The Count property is not updated in OData after applying filters

### ISSUE THREAD

**Issue by yaagraw** [OData/WebApi#2485]
When we are using filter query, in the response we are getting the filtererd result but the `Odata.Count` property is not updated.

### Assemblies affected

OData 7.X assemblies

### Reproduce steps

Hit an API that returns collection of data. After applying filter (using EnableQueryAttribute), the response contains the filtered data but incorrect count.

### Expected result

`

    "@odata.context": "https://canary.graph.microsoft.com/testprodbetateamsgraphyaagraw/$metadata#teams('b50eb36f-1d0b-472a-b38d-2197e8ac2c97')/installedApps(teamsAppDefinition(id,teamsAppId))",

    "@odata.count": 1,

    "value": [

        {

            "id": "YjUwZWIzNmYtMWQwYi00NzJhLWIzOGQtMjE5N2U4YWMyYzk3IyMxNTQyNjI5Yy0wMWIzLTRhNmQtOGY3Ni0xOTM4Yjc3OWU0OGQ=",

            "teamsAppDefinition": {

                "id": "MTU0MjYyOWMtMDFiMy00YTZkLThmNzYtMTkzOGI3NzllNDhkIyMyLjAuMSMjUHVibGlzaGVk",

                "teamsAppId": "1542629c-01b3-4a6d-8f76-1938b779e48d"

            }

        }

    ]
`

### Actual result

`

    "@odata.context": "https://canary.graph.microsoft.com/testprodbetateamsgraphyaagraw/$metadata#teams('b50eb36f-1d0b-472a-b38d-2197e8ac2c97')/installedApps(teamsAppDefinition(id,teamsAppId))",

    "@odata.count": 52,

    "value": [

        {

            "id": "YjUwZWIzNmYtMWQwYi00NzJhLWIzOGQtMjE5N2U4YWMyYzk3IyMxNTQyNjI5Yy0wMWIzLTRhNmQtOGY3Ni0xOTM4Yjc3OWU0OGQ=",

            "teamsAppDefinition": {

                "id": "MTU0MjYyOWMtMDFiMy00YTZkLThmNzYtMTkzOGI3NzllNDhkIyMyLjAuMSMjUHVibGlzaGVk",

                "teamsAppId": "1542629c-01b3-4a6d-8f76-1938b779e48d"

            }

        }

    ]
`

**The total count of data is 52 but after using filter it should be updated to 1.**

### Additional detail

Currently using following implementation (by overriding the OnActionEecuted Method) to solve this issue temporarily.

`

        public override void OnActionExecuted(ActionExecutedContext actionExecutedContext)
        {
            base.OnActionExecuted(actionExecutedContext);

            HttpRequest request = actionExecutedContext.HttpContext.Request;

            ObjectResult objectResult = actionExecutedContext.Result as ObjectResult;
            IEnumerable<object> enumerableObjects = null;

            if (objectResult != null)
            {
                enumerableObjects = objectResult.Value as IEnumerable<object>;

                if (enumerableObjects != null)
                {
                    request.ODataFeature().TotalCount = enumerableObjects.Count();
                }
            }
        }
`

But this implementation is expensive as in some cases the .Count() method will run through the entire collection ([reference](https://github.com/dotnet/corefx/blob/b8b81a66738bb10ef0790023598396861d92b2c4/src/System.Linq/src/System/Linq/Count.cs#L12)) and we will computer the collection again when serialization happens.

Is there a way to update the count efficiently ?

**Comment by KenitoInc** [comment]
Hey @yaagraw 
I can't repro this issue.

I have run the queries below using my sample project and the results are returned correctly.

`http://localhost:6143/odata/books?$count=true&$filter=Id eq 1`
`http://localhost:6143/odata/books?$expand=Authors($count=true;$filter=Id eq 1)`

**Comment by KenitoInc** [comment]
Closing this since the customer was not using the `$count=true` query option.
