### ISSUE TITLE
ClrTypeCache has a memory leak and ClrType cache is not working

### ISSUE THREAD

**Issue by ikhancevich** [OData/WebApi#2489]
The GetClrType method in src/Microsoft.AspNet.OData.Shared/Formatter/ClrTypeCache.cs 

### Assemblies affected

Microsoft.AspNet.OData.Shared, starting from 7.5.4

### Reproduce steps

Make a lot of the same OData requests.

### Expected result

ClrTypeCache._edmToClrTypeCache doesn't contain duplicated records with the same FullName, the cache is working and doesn't lead to a memory leak.

### Actual result

ClrTypeCache._edmToClrTypeCache contains a lot of keys with the same FullName, leads to a memory leak and the ClrType cache is not working.

### Additional detail

Type GetClrType(IEdmTypeReference edmType, IEdmModel edmModel)
The method receives a new instance for the edmType argument and there is no custom equality comparer for the dictionary.

**Comment by xuzhg** [comment]
@ikhancevich I have a fix in the master. It should be in the coming nightly. Would you please try and let me know any result?

**Comment by ikhancevich** [comment]
> 
> 
> @ikhancevich I have a fix in the master. It should be in the coming nightly. Would you please try and let me know any result?

Thank you for the fix, will check it ASAP.

**Comment by habbes** [comment]
Closing the issue. @ikhancevich please re-open if issue was not resolved.
