### ISSUE TITLE
Creating links to other OData routes is hard

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#25]
I have to figure out the appropriate path handler to use. The framework
already knows which path handler should be used when I provide a route name;
it shouldn't ask me for it.  
  
Possible scenarios:  
I want to create an OData link from an ODataController associated with a
different model. In particular, I might be versioning and want to create a
link from one version (v2) to another (v1).  
I want to create an OData link from an ApiController (non-OData). In
particular, I might want to migrate to OData and this method would give me an
entry point to the OData world from the non-OData world.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 771](http://aspnetwebstack.codeplex.com/workitem/771)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jan 14, 2013 at 8:02 PM
**Reported by:**	davidmatson
**Updated on:**	Sep 23, 2013 at 7:43 PM
**Updated by:**	danroth27

**Comment by LianwMS** [comment]
On *2013-01-15 14:57:57 UTC*, **HongmeiG** commented:

This is a valid request. I am moving it to vNext so that we can provide a better url helper extension method to make this easier. This is an advance scenario. It is an advance scenario, and it is ok to punt since we are closing down RTM release.

**Comment by LianwMS** [comment]
On *2013-03-30 07:06:25 UTC*, **HongmeiG** commented:

In order to have the runtime to figure out the path handler, we will need to go back to the configuration and trying to retrieve it from the odata route constraint. It will be a lot simpler if user can pass the path handler directly. Usually that should
 be a singleton.

**Comment by xuzhg** [comment]
Needn't. Close it. Thanks.
