### ISSUE TITLE
MaxTop() configuration not used

### ISSUE THREAD

**Issue by adrien-constant** [OData/WebApi#2504]
- When the action of the controller returns an IQueryable with EF Core
- If I don't specify manually the `PageSize` value in `EnableQuery` : `[EnableQuery(PageSize = 1000)]`

- Then the default value from MaxTop in end endpoint configuration is ignored . The SQL is not modified to limit the number of rows returned as it should be.

### Assemblies affected

Microsoft.AspNetCore.OData 7.5.8

### Reproduce steps

Create a controller with a default Get() action returning an IQueryable (DbSet from EF Core).

Configuration :
```
app.UseEndpoints(endpoints =>
{
                endpoints.Count().Expand().Select().OrderBy().Filter().MaxTop(maxTop);
                MapVersionedODataRoutes<TModelConfiguration>(...);
});
```

### Expected result

I would expect the query to be modified to return only 1000 rows as if `$top=1000` or `[EnableQuery(PageSize = 1000)]` was specified.

### Actual result

All the rows are returned. In my case it raises an exception :
_System.InvalidOperationException: 'AsyncEnumerableReader' reached the configured maximum size of the buffer when enumerating a value of type ..._

### Additional comments

This may be related to https://github.com/OData/WebApi/issues/2308

**Comment by habbes** [comment]
Hi @adrien-constant

The `MaxTop()` sets the maximum value that can be set for the `$top` query parameter. It does not directly limit the number of items returned per request. The discussion thread on the issue you have linked to explains the nuances behind `MaxTop()`, `PageSize` and `$top` in more detail.

I don't think the library currently provides a mechanism to set a global page size for all requests (@xuzhg @mikepizzo is this correct?)

**Comment by JosephDesmet** [comment]
Any news about this one?
