### ISSUE TITLE
Cannot return errors in WebApi with EnableFilter on.

### ISSUE THREAD

**Issue by marabooy** [OData/WebApi#2511]
*Short summary (3-5 sentences) describing the issue.*

Trying to return an error object from an endpoint that has EnableQuery results in an error.
### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData WebApi lib 7.6.5

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*
```csharp
[EnableQuery(AllowedQueryOptions = AllowedQueryOptions.Filter)]
public IActionResult Get()
{
        return this.StatusCode(500, new { Error = new { Code = "500", Message ="Some message"} });
}
```
### Expected result
*What would happen if there wasn't a bug.*

```json 

{
    "error": {
        "code": "500",
        "message": "Some message"
    }
}
```

### Actual result

*What is actually happening.*
```js
{
    "error": {
        "code": "",
        "message": "The query specified in the URI is not valid. The requested resource is not a collection. Query options $filter, $orderby, $count, $skip, and $top can be applied only on collections.",
        "details": [],
        "innererror": {
            "message": "The requested resource is not a collection. Query options $filter, $orderby, $count, $skip, and $top can be applied only on collections.",
            "type": "Microsoft.OData.ODataException"
      }
}
```
### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*
EnableQueryAttribute

```csharp
 // actionExecutedContext.Result might also indicate a status code that has not yet
// been applied to the result; make sure it's also successful.
StatusCodeResult statusCodeResult = actionExecutedContext.Result as StatusCodeResult;
// Potential bug as the this.StatusCode(int, obj) returns an ObjectResult instead of a Status code result. Pre core 2.2 did not have IStatusCodeActionResult.
// StatusCodeResult & ObjectResult all implement IStatusCodeActionResult

```

**Comment by frankpeng7** [comment]
Hi @marabooy thanks for opening this! Is there a workaround I could use to show the correct error message before the fix gets released?

**Comment by marabooy** [comment]
Hi @frankpeng7 you could use the API for OData error result which should format the error message to what you need unless if you have special formatters.

`this.ODataErrorResult(string code, string message)`

**Comment by frankpeng7** [comment]
Thanks for the response @marabooy ! Unfortunately Graph, as a developer API, has it's own error message format. The major difference I see is that `OdataErrorResult` is returning something like `{"ErrorCode": "", "Message": ""}` while our gateway is expecting `{"Code": "", "Message": ""}`.

Getting back to the fix, how long does it normally take for a code fix to be released for Odata?

**Comment by marabooy** [comment]
@frankpeng7 The other workaround as we await a hotfix would be to subclass Action result as done [here](https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNetCore.OData/Results/ODataErrorResult.cs). The code tries to apply filter on items that subclass ObjectResult. I will get back to you on when a hotfix can be released.

**Comment by frankpeng7** [comment]
Hi @marabooy are there any updates on this?

**Comment by marabooy** [comment]
Hi @frankpeng7 this should be in our next release. Currently migrating this repo to dotnet framework and this should have a release then. I will keep you updated with the migration and anticipated release date.
