### ISSUE TITLE
OData Post(Create) endpoint CreateCommand class different from Representation class

### ISSUE THREAD

**Issue by 1Jesper1** [OData/WebApi#2517]
*Use a CreateCommand class instead of representation class for Create Odata endpoint*
When I try this I get an UnsupportedMediaTypeException exception.
```
public class CreateCommand
    {
        //Only needed for Create/Update Odata endpoints
        public Guid BusinessUnitId { get; set; }
        //Needed for GET Odata endpoints.
        public BusinessUnit BusinessUnit { get; set; }
    }
```

### Assemblies affected

Microsoft.AspNet.OData 6.0.0

### Reproduce steps

_public async virtual Task < TRepresentation > Post(TCreateCommand command)_

### Expected result

Use a different class for posting to Odata endpoint, so you can send e.g property Guid BusinessUnitId instead of property (class) BusinessUnit. 

### Actual result
UnsupportedMediaTypeException

### Additional detail
Workaround would be to use properties in representation class like Guid BusinessUnitId to send to Create endpoint and not return BusinessUnitId, instead return BusinessUnit.
Is it possible to not return a specific property in the representation class?
Otherwise there are properties in the representation class which are not needed when returning (Get).
https://stackoverflow.com/a/27815189/2908623

**Comment by 1Jesper1** [comment]
Is it possible to have a Web Api route _"test/"_ with `HttpGet `and an OData route _"test/"_ with `HttpPost`?

**Comment by habbes** [comment]
Hi @1Jesper1 thanks for sharing this. Could you share a sample request body?

Is the `TCreateCommand` type that you're using in the `Post()` method argument related to the `CreateCommand` class mentioned at the beginning of your description? Or are they supposed to be the same type?

Could you also share a stack trace of the exception?

I am also trying to see whether I can reproduce the issue locally and get back to you.

**Comment by habbes** [comment]
> Is it possible to have a Web Api route _"test/"_ with `HttpGet `and an OData route _"test/"_ with `HttpPost`?

I'm not sure I have fully understood this question.

What does `test/` refer to? The OData route needs to refer to entity set or an action defined in your OData model so that you can post to it. If it's an arbitrary endpoint that does not match anything in your OData model, I don't think it can be used as an `ODataRoute`. It has to be a valid OData path.

**Comment by 1Jesper1** [comment]
@habbes  Yes, TCreateCommand is supposed to be the same type as CreateCommand.
You should get the exception when you use a different input class than the result (output) class.

_Works_
public async virtual Task < ItemRepresentation> Post(ItemRepresentation representation)

_Does not work_
public async virtual Task < ItemRepresentation> Post(CreateItemCommand command)

I will try to get the stack trace.

_Is it possible to have a Web Api route "test/" with HttpGet and an OData route "test/" with HttpPost?_
We created a Odatacontroller for an entity set, that is "test".
We also created an non Odata ApiController with an endpoint HttpGet on "test".
It seems the Odatacontroller won't allow the non Odata HttpGet endpoint  "test" with the Odata HttpPost endpoint "test".

**Comment by habbes** [comment]
Thanks for the additional details @1Jesper1, could you also share how you're defining your OData model? Like what classes you've built your model with? Is `CreateCommand` a type in your EdmModel as well?

**Comment by 1Jesper1** [comment]
@habbes If I add the class as entityType the command is always **null** when doing the post request.

If I do not register the command class as entityType I get the mediaformatter exception:

_{
  "error": {
    "code": "",
    "message": "The request entity's media type 'application/json' is not supported for this resource.",
    "innererror": {
      "message": "No MediaTypeFormatter is available to read an object of type 'CreateQualityIssueCommand' from content with media type 'application/json'.",
      "type": "System.Net.Http.UnsupportedMediaTypeException",
      "stacktrace": "   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)\r\n   at System.Web.Http.ModelBinding.FormatterParameterBinding.ReadContentAsync(HttpRequestMessage request, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)"
    }
  }
}_

**Comment by habbes** [comment]
Hi @1Jesper1 I've not been able to reproduce the issue. Actually when I use `CreateCommand` as the argument of the `Post()` method, it works fine even without having to add `CreateCommand` to the `EdmModel`. I see that you're reporting this version 6.0. Can you test it in the latest 7.x version and see whether the issue still occurs?

**Comment by 1Jesper1** [comment]
@habbes I'm going to test!

**Comment by 1Jesper1** [comment]
@habbes 
When I do not add the CreateCommand to the EdmModel, I get the mediatypeformatter exception again.
When I add the CreateCommand to the EdmModel I get this exception:
`Microsoft.OData.ODataException: 'The entity type 'CreateCommand' is not compatible with the base type 'Test' of the provided entity set 'Test'. When an entity type is specified for an OData resource set or resource reader, it has to be the same or a subtype of the base type of the specified entity set.'`

**Comment by 1Jesper1** [comment]
@habbes We managed to get it working when CreateCommand extends Test. We don't need to add CreateCommand as entitytype to the EdmModel, because Test is also added to the EdmModel. With this scenario we can add properties to the command class which won't be added to Test, so these properties won't be return in the result.

**Comment by habbes** [comment]
Thanks for the follow-up @1Jesper1. I'll go ahead and close this issue now. Is it still on 6.x that you managed to get it to work?

**Comment by 1Jesper1** [comment]
@habbes Yes, we stay on version 6, because we didn't manage to setup version 7 with Swagger. Thanks for the help.

**Comment by 1Jesper1** [comment]
ComplexType did the trick to work with a command class without inheriting the representation class.
