### ISSUE TITLE
OData routing for multiple keys

### ISSUE THREAD

**Issue by shahinjabbar** [OData/WebApi#2522]
I am facing a problem when tryna add action which accepts two parameters, for example: host/Prodcucts(productId='dkd5',id='fd54') This route is not working. I added ODataRoute attribute and tried again but request is not getting to this action. My entity:
`public class Product
{
  [Key]
  public Guid ProductId{get;set;}

  [Key]
  public Guid Id{get;set;}
}`
And controller:

` public class ProductController : ODataController
 {

    [EnableQuery]
    [ODataRoute("Product(productId={keyProductId},id={keyId})")]
    public IHttpActionResult Get([FromODataUri] string keyProductId, [FromODataUri] string keyId)
    {
        // some logic
    }`
Any suggestions?

**Comment by habbes** [comment]
Hi @shahinjabbar it's possible that you have typos in your code. In the description you've mentioned `Prodcucts` as the endpoint, but in the `ODataRoute` you're using `Product`.

Could you share how your `EdmModel` is defined? Specifically what name did you give to the entity set that corresponds to the `Product` entity type?

For conventional OData routing to work, the controller should be name after the corresponding entity set. For example, if `Product` is the name of the entity type, and `Products` the name of the entity set, the controller should be called `ProductsController` (notice the plural form).

This should be able to work without using `ODataRoute`. But if you do use `ODataRoute`, then endpoint should also match the name of the entity set, i.e. `Products` not `Product`.

**Comment by habbes** [comment]
Hi @shahinjabbar did you get a chance to try the suggestions above?

**Comment by KenitoInc** [comment]
Closing this since it's been inactive for long.
@shahinjabbar  Feel free to reopen the issue if it's yet to be resolved.

**Comment by ljsomm** [comment]
I'm very late!
But generally to fix that issue you just need to have the parameters in alphabetical order:

`public IHttpActionResult Get([FromODataUri] string keyId, [FromODataUri] string keyProductId)
`
