### ISSUE TITLE
Release notes of 7.5.9 are not correct

### ISSUE THREAD

**Issue by komdil** [OData/WebApi#2553]
Go to https://www.nuget.org/packages/Microsoft.AspNet.OData/7.5.9
Go to Release Notes https://docs.microsoft.com/en-us/odata/changelog/webapi-7x 

There is WebAPI 7.5.8 but no notes about 7.5.9

**Comment by xuzhg** [comment]
@komdil The change note is avaiable at https://docs.microsoft.com/en-us/odata/changelog/webapi-7x
