### ISSUE TITLE
7.5.10 has compilation issue in IISexpress

### ISSUE THREAD

**Issue by marcelwokkemarin** [OData/WebApi#2556]
*After updating to version 7.5.10 Asp webapi servicedoes not run anymore*
Stops with error: 
Could not load file or assembly 'Microsoft.AspNet.OData' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

### Assemblies affected

*Microsoft.AspNet.Odata.7.5.10

### Reproduce steps

* Update a aspnet web api project from 7.5.9 to 7.5.10
* Hit run button to launch in Visual Studio 2019

### Expected result

*Normal view of service*

### Actual result

*Could not load file or assembly 'Microsoft.AspNet.OData' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)*

### Additional detail

Also occurs when precompiling during a release. A normal build works fine though.

**Comment by aimi617** [comment]
The same is happening in our project after updating to Microsoft.AspNet.Odata.7.5.10, the Release doesn't compile with an error "Could not load file or assembly 'Microsoft.AspNet.OData' or one of its dependencies ... (Exception from HRESULT: 0x80131045)", and we have to rollback to v.7.5.9 and put the constraint in project file

`<PackageReference Include="Microsoft.AspNet.OData">`
`<Version>[7.5.9]</Version>`
`</PackageReference>`

The possible workaround is set Any CPU to x64 platform, it compiles locally but the crash happens on production server with the same error.

**Comment by marabooy** [comment]
@aimi617 & @marcelwokkemarin We recently migrated WebApi to use the [dotnetfoundation pipeline](https://github.com/OData/WebApi/pull/2529) and the signing key has changed as a result.

**Comment by marcelwokkemarin** [comment]
@marabooy Thanks for the reply. Could it be that this migration changed the way 7.5.10 is signed? As that seems to be the direction the error message is pointing.

Or do I need to change or fix something in my project setup to be able to use 7.5.10?

**Comment by robertmclaws** [comment]
Question: Why would moving to the .NET Foundation have changed the .SNK file needed to strong-name sign the assembly? A) That shouldn't have mattered, strong-name signing is not a security feature, and so it doesn't really matter the the same key is used for other Microsoft stuff, b) changing the SNK is a SemVer breaking change that would have required an update to the Major version of the assembly to let people know it's not an in-place update.

OData on .NET Framework often REQUIRES binding redirects to make sure different dependencies (like Simple.OData.Client) don't pull in their own references. Releasing this way will break anyone that needs binding redirects in the web.config file to point to the proper versions.

There has to be a way to solve this problem in the build process that does not expose Microsoft's SNK file and also does not break customers.

**Comment by marabooy** [comment]
Thanks for the update @robertmclaws I am currently working on a fix for this.

**Comment by smasherprog** [comment]
I am also facing this so I cannot update to the latest version

**Comment by eligf22** [comment]
I am facing this issue on my project. Using 7.5.8 version for now.

**Comment by marabooy** [comment]
Thanks @eligf22 & @smasherprog Our next release which should be on the horizon should have this fixed.

**Comment by marabooy** [comment]
A new package has been released which fixes the strong name issue. Kindly validate that this works for you.

**Comment by jimivey** [comment]
> A new package has been released which fixes the strong name issue. Kindly validate that this works for you.

So far, so good. Compiled, signed, deployed, and ran a series of tests successfully. I'll confirm last bits after our integration build.

Thank you!

**Comment by jimivey** [comment]
> > A new package has been released which fixes the strong name issue. Kindly validate that this works for you.
> 
> So far, so good. Compiled, signed, deployed, and ran a series of tests successfully. I'll confirm last bits after our integration build.
> 
> Thank you!

Confirmed, everything working for us. Thanks again for fixing this.

**Comment by marabooy** [comment]
Thanks for confirming this. Closing the issue.
