### ISSUE TITLE
EnableCaseInsensitive doesn't work on ODataQueryOptions

### ISSUE THREAD

**Issue by mj1856** [OData/WebApi#256]
Setting `config.EnableCaseInsensitive(true);` in the WebAPI configuration appears to only work on a full OData endpoint.  It doesn't have any effect when using a regular `ApiController` method that accepts an `ODataQueryOptions` parameter, as [described on the asp.net/webapi site](http://www.asp.net/web-api/overview/odata-support-in-aspnet-web-api/supporting-odata-query-options).

**Comment by mj1856** [comment]
Digging a bit deeper, it would appear that if I set `EnsureStableOrdering = false`, then it works.

I'll see if I can find the root cause and send a PR.

**Comment by mj1856** [comment]
Nevermind.  It appears to work just fine when I use version `5.5.0-beta`.   I was using `5.4.0` when it failed.

I think it was fixed by side-effect of fixing #214.

**Comment by vanman314** [comment]
Im on 5.7 and it doesnt work for me.  Even if I add EnsureStableOrdering = false,    
 I have added  config.EnableCaseInsensitive(true);  to my webapiconfig.   Why cant OData options find my property PersonName when personName is the JsonContract resolver??? aaargh
