### ISSUE TITLE
OData Function not working when assigning a custom namespace to the function.

### ISSUE THREAD

**Issue by idurotPauley** [OData/WebApi#2564]
Hi, 

I have several different entities who has a bound function applied for each entity with the same name. Initially, I was getting an error when adding a function with the same name under the same namespace. So my solution is to add the function for each entity under a different namespace.

However, it seem's that it doesn't work as expected and I keep getting 404 errors. I'm currently on OData V7.10
Please note that the function Master bound to Office (default namespace), while Member is not (custom namespace).  

The following URI's work: 
.../odata/Office/Master()
.../odata/Office/Default.Master()

The following URI's don't work.
.../odata/Member/Replication()
.../odata/Member/DDF.Core.Entities.Member/Replication()

Here are some of the code that is present.

### Office Controller
     
        [EnableCustomQuery(AllowedQueryOptions = Filter)]
        [HttpGet] 
        [ODataRoute("Office/Default.Master")]
        public async Task<IActionResult> Master(ODataQueryOptions<Office> options)
        {
            // removed for brevity
            return Ok(resources);
        }

### Office Model Configuration
            
            public class OfficeModelConfiguration : IModelConfiguration
            {
            public void Apply(ODataModelBuilder builder, ApiVersion apiVersion, string routePrefix)
            {
 
            var officeModel = builder.EntitySet<Office>("Office").EntityType;

            var function = builder.EntityType<Office>()
                                .Collection.Function("Master")
                                    .ReturnsCollection<Office>()
                                    .Parameter<int?>("DestinationId").Optional();
        }
    }
### Member Controller
        
        [ODataRoute("Member/DDF.Core.Entities.Member.Replication")]
        [Produces("application/json")]
        [ProducesResponseType(typeof(ODataValue<IEnumerable<Member>>), Status200OK)]
        [EnableCustomQuery(PageSize = PageSize)]
        [HttpGet]
        public async Task<IActionResult> Replication(ODataQueryOptions<Member> options)
        {
             /// Removed for brevity
            return Ok(result);
        }

        [ODataRoute("Member/DDF.Core.Entities.Member.Replication(DestinationId={DestinationId})")]
        [Produces("application/json")]
        [ProducesResponseType(typeof(ODataValue<IEnumerable<Member>>), Status200OK)]
        [EnableCustomQuery(PageSize = PageSize)]
        [HttpGet]
        public async Task<IActionResult> Replication(int? DestinationID, ODataQueryOptions<Member> options)
        {
            /// removed logic
            return Ok(result);
        }

### Member Model Configuration
        public void Apply(ODataModelBuilder builder, ApiVersion apiVersion, string routePrefix)
        {
            
            var memberModel = builder.EntitySet<Member>("Member").EntityType;
       
            var function = builder.EntityType<Member>().Collection.Function("Replication");
            function.Namespace = "DDF.Core.Entities.Member";
            function.ReturnsCollection<Member>()
                    .Parameter<int?>("DestinationID").Optional();
        }

**Comment by Sreejithpin** [comment]
Can you please share your model

**Comment by KenitoInc** [comment]
Closing since the model wasn't shared.
