### ISSUE TITLE
Remove support for netcoreapp2.0

### ISSUE THREAD

**Issue by dxrdxr** [OData/WebApi#2569]
Netcoreapp2.0 is included in the src and test but that version of .Net Core has been at [End Of Support](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) since 2018.

Actually all versions from .Net Core 3.0 and earlier are currently at End Of Support.
The only older version supported is .NET Core 3.1.

Removal of unsupported versions will clarify the source code, allow newer language/API constructs to be used, eliminate significant test code and complexity, and improve build times.

Note: net45 is also past End Of Support.

**Comment by xuzhg** [comment]
ODL also supports the end of support version. We should consider them together.

**Comment by mikepizzo** [comment]
Now that 8.0 is out, we will be deprecating microsoft.aspnet.odata and microsoft.aspnetcore.odata 7.x (and, when microsoft.odata.* 8.0 is out we will deprecate the 7.x version of those libraries). Unless it simplifies maintenance, I don't know that the value of dropping support for the end-of-life platforms in the deprecated versions of the libraries would be worth the potential of breaking folks still using those platforms, even if they are at end of support.
