### ISSUE TITLE
Support Async

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#257]
ODataLib supports it after [v6.4](https://www.nuget.org/packages/Microsoft.OData.Core/6.4.0).  The protocol spec: [11.6 Asynchronous Requests](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398358)

**Comment by mikepizzo** [comment]
This would be a great feature to add, but so far we haven't gotten anyone asking for it.
