### ISSUE TITLE
'Microsoft.AspNet.OData, Version=7.5.10.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

### ISSUE THREAD

**Issue by magneto-81** [OData/WebApi#2573]
I updated Microsoft.AspNet.OData assembly from nuget feed to version 7.5.10, the following error is throw at runtime:
Could not load file or assembly 'Microsoft.AspNet.OData, Version=7.5.10.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

### Assemblies affected

Microsoft.AspNet.OData, Version=7.5.10.0

**Comment by marabooy** [comment]
Closing this as it is a duplicate of https://github.com/OData/WebApi/issues/2556
