### ISSUE TITLE
Add support for documentation to ODataConventionModelBuilder

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#26]
This can be done easily by looking for the System.ComponentModel.Description
attribute on entities and properties, and using the EDM model's
SetDocumentation() method.  
## Work Item Details

**Original CodePlex Issue:**    [Issue 784](http://aspnetwebstack.codeplex.com/workitem/784)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Jan 18, 2013 at 9:44 AM
**Reported by:**    thargy
**Updated on:** Feb 7, 2014 at 7:01 PM
**Updated by:** troydalldorf

**Comment by LianwMS** [comment]
On *2013-04-02 03:06:18 UTC*, **HongmeiG** commented:

Nice feature request Thargy! Today you could add the documentation yourself after the model is built by the conventional model builder.

**Comment by LianwMS** [comment]
On *2013-04-09 08:35:58 UTC*, **raghuramn** commented:


private static IEdmModel GetEdmModel()
{
    ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
    builder.EntitySet<Customer>("Customers");
    builder.EntitySet<Order>("Orders");

    IEdmModel model = builder.GetEdmModel();
    DocumentModel(model);

    return model;
}

private static void DocumentModel(IEdmModel model)
{
    foreach (IEdmType edmType in model.SchemaElements.OfType<IEdmType>())
    {
        Type clrType = model.GetAnnotationValue<ClrTypeAnnotation>(edmType).ClrType;

        model.SetDocumentation(edmType, new EdmDocumentation("Summary", "Description"));
    }
}

**Comment by LianwMS** [comment]
On *2013-09-06 05:56:56 UTC*, **KevinBurton** commented:

So for the slow how is this used? For example one of the resources that I am adding looks like:
        var schedules = modelBuilder.EntitySet<ScheduleRepresentation>("Schedules");

A portion of the ScheduleRepresentation looks like:
public class ScheduleRepresentation
{
    [Key]
    public string Id { get; set; }
    public string Name { get; set; }
    public string TitleType { get; set; }
    public string FolderId { get; set; }

Is it as simple as adding /// comments to each property? If so should they be /// <summary> ?

Thank you.

**Comment by LianwMS** [comment]
On *2013-09-06 07:23:08 UTC*, **raghuramn** commented:

@Kevin: we don't automatically parse the xml documentation and populate the model with it. The above sample shows how to annotate an EDM model with documentation. You should write code to parse the xml doc file or wherever your documentation lives and
 annotate your model.

**Comment by jeffabailey** [comment]
@LianwMS I'm trying to use your method posted on Jan 11th to simply set the documentation. I am finding that the SetDocumentation method is internal, how then can this be done at this point?

Here is the Edm version I'm using.

 <package id="Microsoft.Data.Edm" version="5.6.3" targetFramework="net452" />

Here is the static method.

internal static void SetDocumentation(this IEdmModel model, IEdmElement element, IEdmDocumentation documentation)

I've been trying to muck around to find how to do this but it's slow going.

**Comment by xuzhg** [comment]
Close this because OData V4 spec doesn't have Document element.
