### ISSUE TITLE
.NET6 / OData 8 not serializing OData responses properly

### ISSUE THREAD

**Issue by gordon-matt** [OData/WebApi#2602]
After updating from **.NET 5 / OData 7** to **.NET 6 / OData 8**, I am getting this error:

![NET6 Error](https://user-images.githubusercontent.com/2860937/142282786-51c0d653-e487-4482-96a1-033e0274b118.PNG)

Not sure exactly why it's not serializing properly. I wondered if it might be the default JSON serializer having issues, so I changed to Newtonsoft.JSON, but it made no difference.

You can test it for yourself with my code here: https://github.com/gordon-matt/Extenso

Working **.NET 5 / OData 7** : `master` branch
Broken **.NET6 / OData 8** : `feature/NET6` branch

Run either of the following demo projects to check:

Demo.Extenso.AspNetCore.Mvc.OData
Demo.Extenso.AspNetCore.Blazor.OData

**Comment by habbes** [comment]
@gordon-matt I have tried to go through your repro but it seems that there's a lost of custom code wrapping the OData layer. I tried running the demo but it fails due errors connecting to SQL Server. I tried to change the `AddDbContext` configuration to use an in-memory database, but still go the same error. In short, I was not able to reproduce the issue. Would I be required to provide my own implementation of `IRepository<T>`?

Could you share a simpler, self-contained repro that isolates the parts that fails, ideally with no dependency to SQL Server or any other external system?

**Comment by gordon-matt** [comment]
Thank you for taking the time to have a look. All of the source code is in the solution and it's not very complex. Everything is setup already to use the default `IRepository<T>` (look in `Startup.cs`, under `ConfigureContainer()`), so you just need to run it and not care about that at all. However, I suppose it would be easier if I had provided a database. Sorry about that.. here's a link to a zip archive containing both a .bak file (which you can restore with MSSQL 2019) and a database generation script that I created.. as I don't know what version of MSSQL you have, I decided to use an old version (2012) just in case:

[ExtensoDemo.zip](https://www.mediafire.com/file/hwzk110gku71uja/ExtensoDemo.zip/file)

**Comment by gordon-matt** [comment]
By the way, the reason you still got a SQL error even when changing `AddDbContext` to in-memory is most likely because you also would need to change it to in-memory in one more place: `/Data/ApplicationDbContextFactory.cs`

**Comment by gordon-matt** [comment]
I was looking at this again.. decided to try serialize the entities to JSON myself as a test in case to see what would happen.. As per the screenshot below, you can see it serialized perfectly fine. But when passed to `Ok()`, it doesn't come out right on the client side. This was never an issue before (and I've been using the same code since MVC5 and several versions of .NET Core.. right up to .NET 5).. only now when updating to the latest version of OData with .NET 6 and suddenly it's an issue. I have several projects I can't update to .NET 6 yet, because they rely on OData. Please help me figure out what the issue is. 

![odata json](https://user-images.githubusercontent.com/2860937/145157382-a89af9e3-ce42-4f12-b9c9-b86836e0c1e6.PNG)

**Comment by gordon-matt** [comment]
@habbes Any chance you could look at this soon?

**Comment by gordon-matt** [comment]
Closing this as I have moved the issue to the correct report, at: https://github.com/OData/AspNetCoreOData/issues/424
