### ISSUE TITLE
How to make key property select by default

### ISSUE THREAD

**Issue by komdil** [OData/WebApi#2603]
I want to show key value of entities even if they were not selected

Microsoft.AspNetCore.OData 7.5.12

### Reproduce steps
In this request I will get all properties: https://localhost:44383/OData/Student
```
{
    "@odata.context": "https://localhost:44383/odata/$metadata#Student",
    "value": [
        {
            "Id": "adba377f-94c7-4d2f-b6b1-06a07981f6ad",
            "Name": "Name17",
            "LastName": null,
            "FullName": "Name17 ",
            "Score": 17
        }
    ]
}
```
But when I send request https://localhost:44383/OData/Student?$select=Name, I will get only name:
```
{
    "@odata.context": "https://localhost:44383/odata/$metadata#Student(Name)",
    "value": [
        {
            "Name": "Name17"
        }
    ]
}
```

### Expected result

I want to see Id also even if it was not selected. Is it possible with custom serializer or somehow else?

### Actual result

Returning only Name

**Comment by xuzhg** [comment]
@komdil 
1) Try to use a model-based query setting and use https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/Query/SelectExpandType.cs#L23

2) Or add a middleware to add the "Id" into the $select

3) Or customize EnableQueryAttribute to add "Id" into $select

4) Or customize Serializer (maybe more codes).

**Comment by komdil** [comment]
@xuzhg  I would like to see some examples

**Comment by komdil** [comment]
I override CreateSelectExpandNode method in resource serializer and set property there:

var keyProperty = resourceContext.StructuredType.StructuralProperties().FirstOrDefault(s => s.Name == "Id");
selectExpandNode.SelectedStructuralProperties.Add(keyProperty );

It is working
