### ISSUE TITLE
Is there a way to get the Options applied result from Odata?

### ISSUE THREAD

**Issue by TehWardy** [OData/WebApi#2605]
Using the latest build from github of all libs for .Net 5.
Lets say I do thing like ...

        Api/SomeType?$expand=ChildItems,Parent&$select=Id,Name,Parent,ChildItems

I'm looking to get an IQueryable like ...

```json
[
   {
        "Id": 123,
        "Name": "Test Item",
        "Parent": {  ... }
        "ChildItems": [  ... ]
   }
    ...
]
```
... I'm doing this in a custom formatter that inherits from TextOutputFormatter, my thinking is that if I can get the object tree in the right structure then I can simply give this object to my serializer. 
Right now I get some sort of "SelectExpandWrapper" object that doesn't reflect my underlying type information the way I expect.

Unless there's some API on this I can use to "iterate items only selecting the stuff that's relevant to my result"?
I'm asusming there is a solution to this as the framework itself does exactly this, i'm just not sure where to look.

some additional context ... Here's an example of typical formatter code highlighting what i'm trying to solve ...

```cs
    public class XmlFormatter : TextOutputFormatter
    {
        public XmlFormatter()
        {
            SupportedMediaTypes.Add(MediaTypeHeaderValue.Parse("application/xml"));
            SupportedMediaTypes.Add(MediaTypeHeaderValue.Parse("text/xml"));

            SupportedEncodings.Add(Encoding.UTF8);
            SupportedEncodings.Add(Encoding.Unicode);
        }

        protected override bool CanWriteType(Type type) => true;

        public override async Task WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
        {
                var resultObject = context.Object;
                var outputSelection = GetODataParamsAppliedVersion(resultObject );
        }
        
        object GetODataParamsAppliedVersion(object, contextObject) 
        {   
             ///????  How do I do this ???? 
        }
    }
```

**Comment by xuzhg** [comment]
$select and $expand will return `ISelectExpandWrapper`. 
 you can refer to sample code here `https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/Query/Expressions/SelectExpandWrapperConverter.cs#L44 to retrieve something.

**Comment by TehWardy** [comment]
Hmmm thx @xuzhg  ... hopefully the work you're doing with Hassan Habib will improve this as it feel clunky.
I was hoping to be able to get the transformed result inside a custom formatter,  it looks like i'm going to have to manually do this work :(

**Comment by KenitoInc** [comment]
The question has been answered.
