### ISSUE TITLE
Support Custom Odata Annotation @odata.RequiredSelect in Response

### ISSUE THREAD

**Issue by akhilkohlimicrosoft** [OData/WebApi#2611]
Looking for ways to support custom Odata Annotation with @odata.RequiredProperty in Response?
The response example:-
{
    "@odata.context":"https://localhost:9000/odata/$metadata#Documents","value":
    [
        {
            "@odata.RequiredProperty":"testProperty"
             ,"ID":1,"Name":"Another.txt","Content":"test"
        },
        {
            "@odata.RequiredProperty":"testProperty2"
             ,"ID":2,"Name":"Another2.txt","Content":"test2"
        }
    ]
}

Thanks for help!

**Comment by xuzhg** [comment]
@akhilkohlimicrosoft odata is the reserved prefix name in the annotation. you can use other namespace names other than odata.

In the WebAPI 7.x version, you can use the new feature merged at https://github.com/OData/WebApi/pull/2219 to create instance annotation.

**Comment by KenitoInc** [comment]
@akhilkohlimicrosoft Did you manage to resolve this?

**Comment by KenitoInc** [comment]
Closed due to inactivity
