### ISSUE TITLE
(de)serialization of dynamic properties

### ISSUE THREAD

**Issue by richardu** [OData/WebApi#2612]
Model properties that are declared as 'dynamic', e.g.:

`public dynamic Value { get; set; }`

(not to be confused with dynamic properties which are held in a container property of type `IDictionary<string, object>`)

aren't handled by OData (de)serialization.

Json.NET (Newtonsoft.Json) works correctly.

Would it be possible to simply call: `Type type = value.GetType()` as per `ODataPrimitiveSerializer()` and serialize accordingly?

If not, what's the best way of implementing this functionality? There are many potential extension points (e.g. implementing a new `IODataEdmTypeSerializer` and overriding one of the methods) but it's not clear which would be best suited.

**Comment by mikepizzo** [comment]
IODataEdmTypeSerializer could solve the serialization/deserialization, but what other functionality do you want with the property? i.e., do you want to be able to filter/sort on it?

In your scenario, could the actual type by any type, or would it be restricted to primitive types? Complex types? could it ever be an entity type?

How would it be represented in $metadata?  Edm.Untyped?

**Comment by richardu** [comment]
I solved it using:

`public override ODataValue CreateODataValue(object graph, IEdmTypeReference expectedType, ODataSerializerContext writeContext)
{
    var value = new ODataUntypedValue();
    value.RawValue = JsonConvert.SerializeObject(graph);

    return value;
}`

I'll need to implement the other functionality you describe manually, since the API is actually Neo4j-backed, not SQL (EF). Currently only primitive types. The value seems to be passed into the OData serialization framework as Edm.Untyped.
