### ISSUE TITLE
What is the difference between Microsoft.AspNetCore.OData and Microsoft.AspNet.OData.dll?

### ISSUE THREAD

**Issue by qwertie** [OData/WebApi#2619]
I don't know what to make of this. These two packages have roughly the same number of downloads, and they are fairly similar but have seemingly random differences (e.g. one has DefaultODataSerializerProvider and the other does not; one has MapODataServiceRoute and the other does not; one has FromODataBodyAttribute and the other does not).

Whenever I google for documentation, without exception I find code `using ...AspNet...`, not `using ...AspNetCore...`. However I'm making a .NET 6 project and all my other packages are "AspNetCore" so I figure that I should be using the AspNetCore package for OData. Is this correct?

Why are there two packages? Why are they significantly different? What are the differences? And are there a set of samples for AspNetCore like there are for AspNet?

To make this more confusing, the Microsoft.AspNetCore.OData package 7.5.8\lib\netcoreapp3.1 places its contents in Microsoft.AspNet namespaces, while Microsoft.AspNetCore.OData package 8.0.2\lib\netcoreapp3.1 uses Microsoft.AspNet namespaces. What's up with that? It looks like the [OData documentation here](https://docs.microsoft.com/en-us/odata/) actually has documentation for both of these (and _not_ for Microsoft.AspNet.OData.dll...?) in the _same_ treeview, which is unusual for Microsoft API documentation.

(And for anyone wondering about the difference between Microsoft.AspNet.WebApi.OData, Microsoft.Data.OData and Microsoft.AspNet.OData, [see SO](https://stackoverflow.com/questions/38774217/what-is-the-difference-between-microsoft-aspnet-webapi-odata-and-microsoft-data).)

**Comment by gathogojr** [comment]
Hi @qwertie. The target for the Microsoft.AspNet.OData package is ASP.NET Classic//.NET Framework while the target for Microsoft.AspNetCore.OData is ASP.NET Core//.NET Core framework.
In 7.x, both packages share the Microsoft.AspNet.OData namespace. A lot of code is shared between the two projects/libraries so it made sense to have a shared namespace for easier referencing.
8.x targets only the ASP.NET Core runtime so Microsoft.AspNetCore.OData is applied consistently.

Microsoft.AspNet.WebApi.OData and Microsoft.Data.OData are legacy OData libraries and are not currently maintained.

**Comment by qwertie** [comment]
FWIW, I located the [repo for the new library (8.x)](https://github.com/OData/AspNetCoreOData) that uses the Microsoft.AspNetCore.OData namespace. There doesn't appear to be a corresponding set of [samples](https://github.com/OData/ODataSamples) for it.
