### ISSUE TITLE
Update from Microsoft.AspNet.OData v.7.5.11 to v.7.5.13 Delta is null

### ISSUE THREAD

**Issue by premiaware** [OData/WebApi#2629]
I have update  Microsoft.AspNet.OData v.7.5.11 to v.7.5.13, i use DbGeography data type using this implementation

https://devblogs.microsoft.com/odata/how-to-consume-sql-spatial-data-with-web-api-v2-2-for-odata-v4/

with version v.7.5.11 e previous all working well, 
if I update my project to v.7.5.13 stop working when I try to patch data with this error:

The request is invalid: Nullable values cannot be made null by OData Patch delta

how can fix the issue?

**Comment by KenitoInc** [comment]
Kind share the error stacktrace so that we can investigate this issue.
Note: we made some changes in v7.5.12 to ignore unmapped properties in Delta. PR #2544

**Comment by Sreejithpin** [comment]
@premiaware  We also had a PR where we return T from Path method, this is for handling complex types. If you could share more details would be great. We can sit and can troubleshoot

**Comment by premiaware** [comment]
Hi, thank's for support me,

I have a generic controller in my Asp.Net WebApi

public class GenericController<T> : baseGenericODataController where T: class, BaseGenericModel
........
.......

    public async Task<IHttpActionResult> Patch([FromODataUri] long key, Delta<T> delta)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var entity = await TableForT().FindAsync(key);
            if (entity == null)
            {
                return NotFound();
            }
            delta.Patch(entity);
            try
            {
               await Request.GetContext().SaveChangesAsync();
            }
           catch (DbUpdateConcurrencyException)
            {
                if (!Exists(key))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
           return Updated(entity);
        }

using  v.7.5.13, 
If <T> contain  DbGeography data type using this implementation

https://devblogs.microsoft.com/odata/how-to-consume-sql-spatial-data-with-web-api-v2-2-for-odata-v4/

i have this situation:
Delta<T> delta = null 
ModelState.IsValid = false

if <T> not contain DbGeography all working well

if using  v.7.5.11 all is ok with or witout DbGeography

**Comment by Sreejithpin** [comment]
@premiaware Can you please give a repro and we can sit working towards it

**Comment by premiaware** [comment]
i can try but i think it will take me some time

**Comment by Sreejithpin** [comment]
@premiaware no worries, but would be really helpful

**Comment by Sreejithpin** [comment]
@premiaware Can you please give the request (payload and url) details as well

**Comment by Sreejithpin** [comment]
@premiaware I tried with a request for a repro sam created and delta was not null. Can we sit together to fix

**Comment by premiaware** [comment]
Hi, in this Moment i have few time to prepare repo. Is possible that i share my developer machine with you? We can chat with Skype? My account Is premiaware

**Comment by Sreejithpin** [comment]
@premiaware Yes we can sit, please tell me whenever you are free at the earliest

**Comment by Sreejithpin** [comment]
@premiaware Can you pls give you id/email

**Comment by premiaware** [comment]
info@premiaware.com 
skype: premiaware

**Comment by Sreejithpin** [comment]
Thanks . sending a meeting request. Would you be able to use Teams?

**Comment by premiaware** [comment]
no teams no work, is possibile to use anydesk.com and skype for chat?

**Comment by Sreejithpin** [comment]
let me try, can you use zoom?

**Comment by premiaware** [comment]
i would prefer anydesk, with zoom i had virus problems.

**Comment by Sreejithpin** [comment]
Ok let me try will mail you, thanks

**Comment by Sreejithpin** [comment]
I have installed anydesk, would you need both skype and anydesk or can we connect call over anydesk?

**Comment by Sreejithpin** [comment]
Hi sent you a sky[pe invite

**Comment by Sreejithpin** [comment]
pls try joining https://join.skype.com/XOJeBWwBwfb4

**Comment by Sreejithpin** [comment]
I am in the call, are you able to join
