### ISSUE TITLE
NuGet Package 7.5.13 Has Wrong Dependency Versions

### ISSUE THREAD

**Issue by commonsensesoftware** [OData/WebApi#2632]
**Microsoft.AspNet.OData** NuGet package version 7.5.13 has the wrong dependency versions. The package claims that the supported dependency on **Microsoft.OData.Core** is `>= 7.9.0 && <= 8.0.0`, but the actual referenced version is 7.10.0. This results in a NuGet package validation failure when referencing the package. You cannot have an actual reference lower than your stated reference. It's unclear if the package was created incorrectly or the incorrect reference was used. Maybe it should have been 7.9.0?

>💡 TIP: Historically, this is not the first time this has happened. Refactoring to use the intrinsic NuGet capabilities in MSBuild instead of crafting the `*.nuspec` file in a custom manner will very likely avoid this problem now and in the future. 

### Assemblies affected

7.5.13

### Reproduce steps

Add a reference to the NuGet package

### Expected result

No failures.

### Actual result

`CSC : error CS1705: Assembly 'Microsoft.AspNet.OData' with identity 'Microsoft.AspNet.OData, Version=7.5.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Microsoft.OData.Core, Version=7.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'Microsoft.OData.Core' with identity 'Microsoft.OData.Core, Version=7.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'`

### Additional detail

![image](https://user-images.githubusercontent.com/11765008/157131535-86d42cc5-9b6d-4629-8275-1a0292875a99.png)

**Comment by xuzhg** [comment]
@commonsensesoftware It's a known issue and we had a fix at https://github.com/OData/WebApi/pull/2628.

We just un-list 7.5.13 and will ship a new version when we are ready.

**Comment by commonsensesoftware** [comment]
Thanks @xuzhg. It was a confusing landmine. If it was known, I'm not sure why it wasn't already unlisted. Regardless, thanks for confirming.

Again, I'm not sure why the build continues to build the `*.nuspec` by hand. I _think_ that's because you're still using MSBuild 14.0 without updating? 🤔 Even the new OData packages for ASP.NET Core do this. I would consider updating. The juice _is_ worth the squeeze. Creating the package from MSBuild 15+ is a breeze. It solves all the problems of dependencies and their versions. The only differences I see between the release and nightly files are are _prerelease_  suffix and release notes. These are first-class citizens through the MSBuild support via `<VersionSuffix>` and `<PackageReleaseNotes>` respectively. These are easy to pipe through the build pipeline.

Just a suggestion. If you need help pursing it, I'm willing to oblige.

Also, I noticed that the `*.nuspec` file includes sources that are **not** included. I presume whatever method packs the `*.nupkg` is not validating or is otherwise ignoring the errors about it:

```xml
<file src="$SourcesRoot$\src\Microsoft.AspNet.OData\**\*.cs" target="src\Microsoft.AspNet.OData" />
<file src="$SourcesRoot$\src\Microsoft.AspNet.OData.Shared\**\*.cs" target="src\Microsoft.AspNet.OData.Shared" />
```

It's not clear when this might have started happening, but they're definitely not apart of any release or nightly package. Unless you're not building out of a commit, I would recommend using SourceLink instead. I don't why anyone would want the source files for anything other than debugging. SourceLink is a superior alternative. At a minimum, these `<file>` inclusions should be removed since they are broken and are not actually included.

**Comment by xuzhg** [comment]
@commonsensesoftware There are some accidents that block us from finishing the building. 

OData is an open source project and any contributions are welcome. 

By the way, we enabled the sourcelink support I think. It can easy to debug using symbols from nuget.org on sourcelink enabled.

**Comment by mikepizzo** [comment]
7.5.13 has been unlisted due to this issue. 7.5.14 has been released to replace it.

**Comment by commonsensesoftware** [comment]
Great! Thanks for the quick turnaround on this one Sam and Mike.

You're right, it does look like SourceLink is enabled, but the packages are still showing untracked sources and nondeterministic builds. The following will fix it:

```xml
 <!-- REF: https://github.com/dotnet/sourcelink/blob/master/README.md -->
 <PropertyGroup Label="SourceLink">
  <EmbedUntrackedSources>true</EmbedUntrackedSources>
  <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>

  <!-- REF: https://github.com/clairernovotny/DeterministicBuilds -->
  <ContinuousIntegrationBuild Condition=" ('$(TF_BUILD)' == 'true') OR ('$(GITHUB_ACTIONS)' == 'true') ">true</ContinuousIntegrationBuild>
 </PropertyGroup>
```

Without that, this is what you'll get:
<img width="210" alt="image" src="https://user-images.githubusercontent.com/11765008/157355720-51b4d9c6-2448-463d-95bd-6c6859cfa92a.png">

Between work and my own project, I'm pretty buried at the moment. If I get a chance to circle back around on build improvements, I'm happy to help you out. For now, I'm glad we have a quick fix. Customers will appreciate that. Thanks. I consider this issue resolved.
