### ISSUE TITLE
Date filter is not working in Odata 7.8.3

### ISSUE THREAD

**Issue by padhumailin** [OData/WebApi#2636]
```json
[
	{
		"Name": Product A
		"StartDateTime":"2012-01-01T00:00:00Z"
		"License":
			[
				{
					"LicenseName":Test
					"StartDateTime":"2020-01-01T00:00:00Z"
					"EndDateTime": "2021-01-01T00:00:00Z"
				},
				{
					"LicenseName": Test2
					"StartDateTime": "2040-01-01T00:00:00Z"
					"EndDateTime": "2050-01-01T00:00:00Z"
				}
			]
		}
	},
	{
		"Name": Product B
		"StartDateTime":"2010-01-01T00:00:00Z"
		"License":
			[
				{
					"LicenseName":Test
					"StartDateTime":"2020-01-01T00:00:00Z"
					"EndDateTime": "2030-01-01T00:00:00Z"
				},
				{
					"LicenseName": Test2
					"StartDateTime": "2040-01-01T00:00:00Z"
					"EndDateTime": "2050-01-01T00:00:00Z"
				}
			]
		}
	}
]
```
when try to filter with below uri 

$filter= License/any(a:a/EndDateTime ge 2017-01-01) and License/any(a:a/EndDateTime le 2030-01-01)

Translated sql query formed like this,
```sql
 SELECT COUNT_BIG(*)
FROM [Devices] AS [p]
WHERE (EXISTS (
    SELECT 1
    FROM [License] AS [p1]
    WHERE ([p1].[DeviceId] = [p].[DeviceId]) AND **((((DATEPART(year, CAST([p1].[EndDateTime] AS datetimeoffset)) * 10000) + (DATEPART(month, CAST([p1].[EndDateTime] AS datetimeoffset)) * 100)) + DATEPART(day, CAST([p1].[EndDateTime] AS datetimeoffset)))** >= @__p_3))
	AND EXISTS (
    SELECT 1
    FROM [License] AS [p2]
    WHERE ([p2].[DeviceId] = [p].[DeviceId]) AND **((((DATEPART(year, CAST([p1].[EndDateTime] AS datetimeoffset)) * 10000) + (DATEPART(month, CAST([p1].[EndDateTime] AS datetimeoffset)) * 100)) + DATEPART(day, CAST([p1].[EndDateTime] AS datetimeoffset)))** >= @__p_4))
	)
```
	
	**Issue 1:** Here [License] table filter query generated with two EXISTS condition. Hence the expected results is mismatched and returns incorrect data
	**Issue 2:**In EXISTS condition DATEPART() is used to concat the date format which is also incorrect because condition is compared as a string type
	
	**Environment**:.Net5, EF5, OData 7.8.3

**Comment by xuzhg** [comment]
@[padhumailin](https://github.com/padhumailin) Can you share with us a repro to dig more?

Can you update the EF from 5 to 6? or even update to EF Core 6 to verify?

**Comment by xuzhg** [comment]
@padhumailin 
are the following expressions that can work at your side?

`$filter= License/any(a:a/EndDateTime ge 2017-01-01 and a/EndDateTime le 2030-01-01)`   or
`$filter= License/any(a:(a/EndDateTime ge 2017-01-01 and a/EndDateTime le 2030-01-01))`  

can you try that and let us know the result?

**Comment by padhumailin** [comment]
Thanks works good the suggested expression.
