### ISSUE TITLE
How to customize example value in open api documentation with odata specification

### ISSUE THREAD

**Issue by padhumailin** [OData/WebApi#2639]
Hi, i have designed a GET call api and it returns below as Example value in 
open api documentation of swagger.

**Responses:**
```json
[
    {
            "Id": "1234",
            "Name": "test",
            "Country": "Testing"
    }
]
```

But my expectation would be as shown below, since i have exposed the controller
as odata enabled query

**Responses:**
```json
{
    "value": [
	{
            "Id": "1234",
            "Name": "test",
            "Country": "Testing"
        }
 ]
}
```

Can someone please suggest, how i can include "value" in example value. Please suggest
how we can customize response body in open api documentation

**Comment by gathogojr** [comment]
@padhumailin The first response looks to me like outcome of fetching an entity by Id while the response you were expecting looks like the outcome of fetching an entity set (entity collection). Could you please share your Url? Maybe it'd also help to share a code sample implementation of your controller

**Comment by gathogojr** [comment]
@padhumailin Looks like the response is not being serialized by the OData serializer. Kindly share your setup logic so we're able to troubleshoot the issue.

**Comment by gathogojr** [comment]
@padhumailin Were you able to resolve the issue on your own? Can I close this issue?

**Comment by gathogojr** [comment]
Proceeding to close issue. No response from issue reporter
