### ISSUE TITLE
[vNext] Design and implement EDM model building

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/WebApi#269]
including support ODataConventionModelBuilder in vNext.
also support model building from context classes.

**Comment by dtotzke** [comment]
+1.  Please support model building form existing edmx generated DbContext classes.  Thank you.

**Comment by lewischeng-ms** [comment]
@dtotzke Yes, we shall support that.

**Comment by grahamehorner** [comment]
edmx as I understand it wont be supported by EF (v7) Core as only simple less complex models will only be supported and the EF team state if your doing complex edmx models you should use EF v6? is the plan to support EFv6 and EF (v7) Core ?
