### ISSUE TITLE
Microsoft.AspnetCore.OData 7.5.16 Breaks Restier

### ISSUE THREAD

**Issue by robertmclaws** [OData/WebApi#2700]
Hey folks! Just wanted to let you know that something happened in the 7.5.16 build, and a Restier service that was working in 7.5.15 started 404ing on every endpoint except $metadata. No idea why I'm going to have to go deep with the Router code and run my unit tests to see what happened, but you folks might want to pull this build, as I saw some other problems cropping up for people in this release as well.

### Assemblies affected
Microsoft.AspnetCore.OData 7.5.16

**Comment by habbes** [comment]
Hi @robertmclaws thanks for reporting this. Are there specific URLs that are failing, is there a noticeable pattern?

**Comment by robertmclaws** [comment]
Nope, no specific pattern, just 100% of the endpoints failed. 

I haven't been able to track down a cause, but a point release shouldn't be a breaking change. So if something broke, at the very least you should heavily consider hiding the release on NuGet until we track down the issue.

/cc @mikepizzo

**Comment by mikepizzo** [comment]
hmm...  I was able to update a Microsoft.Restier.AspNetCore 1.0.0-rc8.20220714.1 project to 7.5.16 and not encounter the 404 issue. I did have to update my newtonsoft.json and dependency injection references, and ended up moving to from .netcore3.1 to .net60, but after that everything worked fine.

**Comment by robertmclaws** [comment]
I'll see what I can do. We're already on .NET 6 and are running the latest everything on all of our Restier-based projects. When we upgraded to 7.5.16 last night, I noticed that the default changed to returning JSON instead of XML for the metadata, and all my methods started 404ing. Backing out to 7.5.15 fixed the issue.

I'll go into the Restier project itself tonight and update the references to see if any of the tests break.

**Comment by mikepizzo** [comment]
Are you using the latest preview nuget release of RESTier, or a later build directly from the repo?

**Comment by robertmclaws** [comment]
We're using the latest RC8 build on NuGet. Outside of this issue and the ones that you mentioned in your email, Restier RC8 is intended to be the same build as Restier RTM.

**Comment by habbes** [comment]
@robertmclaws thanks for sharing more details.

Regarding this statement:
>, as I saw some other problems cropping up for people in this release as well.

Would you mind sharing some examples of problems that cropped up? Were they also using Restier?

I have tried running the samples from the repository again, and I was not able to reproduce the issue. The `$metadata` endpoint returned XML as expected and the other routes also worked as expected.

Was there any other change you made after upgrading or it was just the version update?
@mikepizzo @xuzhg is there any precedent for this? Hiding the release for the moment does sound like a good idea. I have already published a blog post on this feature: https://devblogs.microsoft.com/odata/using-the-new-json-writer-in-odata/
I can add a warning that some issues have been reported after upgrading to Microsoft.AspNetCore.OData 7.5.16. I considered unpublishing the article yesterday, but I think it's better to keep it up (with a warning) since it might help us know if there are more people experiencing issues. It's also possible that some people had already read it (I've seen it shared on Twitter).

**Comment by mikepizzo** [comment]
Yes, we can hide releases.

I also ran into  #2701<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOData%2FWebApi%2Fissues%2F2701&data=05%7C01%7Cmikep%40microsoft.com%7C2e60cec1372644157d6508da811db580%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637964261873639870%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=j47hAEROS6XACCl1Er7C52OEgtKWCIoJ6lMcV0sY9Hc%3D&reserved=0>. It looks like our Newtonsoft reference is broken.

@Sam ***@***.***> - I thought we moved the NewtonSoft logic to a separate extension? I would love to not have references to NewtonSoft in our core libraries.

**Comment by mikepizzo** [comment]
Moved Newtonsoft logic to a separate extension is done at 8.x version. So, I am curious about the issue.

In the Web API 7.x repo, I bumped the newtosoft.json version to 13.0.1. That's the security vulnerabilities requirement.

I think it could be related to this line: https://github.com/OData/WebApi/blob/master/tools/WebStack.versions.settings.targets#L19,  we should update the dependency version for the nuget package also.

From: Michael Pizzo ***@***.***>
Sent: Thursday, August 18, 2022 10:04 AM
To: OData/WebApi ***@***.***>; Sam Xu ***@***.***>; Clement Habinshuti ***@***.***>
Subject: RE: [OData/WebApi] Microsoft.AspnetCore.OData 7.5.16 Breaks Restier (Issue #2700)

Yes, we can hide releases.

I also ran into  #2701<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOData%2FWebApi%2Fissues%2F2701&data=05%7C01%7Csaxu%40microsoft.com%7C53b148067579482cd59808da813b9b73%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637964390255473160%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BFEe6tFhtRoLnTINiSyCSwb%2FOIAmy8F0vwmbq0UfXJY%3D&reserved=0>. It looks like our Newtonsoft reference is broken.

@Sam ***@***.***> - I thought we moved the NewtonSoft logic to a separate extension? I would love to not have references to NewtonSoft in our core libraries.

**Comment by xuzhg** [comment]
Moved Newtonsoft logic to a separate extension is done at 8.x version. So, I am curious about the issue.

In the Web API 7.x repo, I bumped the newtosoft.json version to 13.0.1. That's the security vulnerabilities requirement.

I think it could be related to this line: https://github.com/OData/WebApi/blob/master/tools/WebStack.versions.settings.targets#L19,  we should update the dependency version for the nuget package also.

**Comment by robertmclaws** [comment]
Other 7.5.16 issues: https://github.com/OData/WebApi/issues/2653

**Comment by habbes** [comment]
> Other 7.5.16 issues: #2653

Strange. This one seems related to 7.5.15, the custom reports experiencing the issue after migrating from 7.5.14 to 7.5.16

**Comment by robertmclaws** [comment]
I believe this is resolved now. Closing. Thanks everyone!
