### ISSUE TITLE
Build warnings for latest 7.x Microsoft.AspNetCore.OData netstandard2.0 lib 

### ISSUE THREAD

**Issue by bahusoid** [OData/WebApi#2719]
Build for net48/netstandard2.0 project referencing latest Microsoft.AspNetCore.OData lib  gives a bunch of warnings like:
```
Microsoft.Common.CurrentVersion.targets(2304, 5): [MSB3277] Found conflicts between different versions of "Microsoft.AspNetCore.Http.Abstractions" that could not be resolved.
There was a conflict between "Microsoft.AspNetCore.Http.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" and "Microsoft.AspNetCore.Http.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60".
...
```
### Assemblies affected

Microsoft.AspNetCore.OData  7.5.18+
Latest working version: 7.5.17

### Reproduce steps
1) Create net48/netstandard2.0 project referencing  latest 7.x `Microsoft.AspNetCore.OData`  (7.6.1) 
2) Try to build it.

Attaching simple solution demonstrating the issue: 
[NetFxOdataBuildfail.zip](https://github.com/OData/WebApi/files/9907564/NetFxOdataBuildfail.zip)

### Expected result

Successful build

### Actual result

Build warnings or fails (with `TreatWarningsAsError` set to true)
[BuildWarningsLog.txt](https://github.com/OData/WebApi/files/9907827/BuildWarningsLog.txt)

**Comment by xuzhg** [comment]
@bahusoid Thanks for letting us know it. 
I think it's from this change: https://github.com/OData/WebApi/blob/8e983c4ad4d1af2f430ddeb89da5becfc17af8e1/src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj#L27

Since we changed the version in csproj, we must update the nuget files.
