### ISSUE TITLE
OData WebAPI V4 tooling scaffolding is Visual Studio

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#273]
Add VS scaffolding tool for OData WebAPI V4

**Comment by congysu** [comment]
Two of them:
1. For an in-mem data source.
2. For EF

**Comment by dtotzke** [comment]
Please be sure to support Model/Database-First EF with the tooling.  Ability to pick a type from an existing edmx and have it generate a controller.  Thanks.

**Comment by VikingsFan** [comment]
Checked in be6f51b1fb02651f17143b3ffec82b4b315396d3
