### ISSUE TITLE
DateTimeOffset serialized without timezone when working with DTO.

### ISSUE THREAD

**Issue by Molinware** [OData/WebApi#2741]
DateTimeOffset serialized without timezone when working with DTO.

### Assemblies affected

OData WebApi lib 8.0.12

### Reproduce steps

```
[EnableQuery]
public IQueryable Get()
{
    return _dbContext
        .Clients
        .AsNoTracking()
        .Select(
            x =>
            new ClientDto()
            {
                Id = x.Id,
                CreatedDate = x.CreatedDate
            })
}

public class Client
{
    public Guid Id { get; set; }
    public DateTimeOffset CreatedDate { get; set; }
}

public class ClientDto
{
    public Guid Id { get; set; }
    public DateTimeOffset CreatedDate { get; set; }
}
```

### Expected result

"CreatedDate":"2022-12-27T17:51:09.2125084+00:00"

### Actual result

"CreatedDate":"2022-12-27T17:51:09.2125084Z"

### Additional detail

- This is the data in SQL Server (Azure):
![image](https://user-images.githubusercontent.com/10515611/209803286-79e86681-274b-422a-a616-7c8aade91e2e.png)

**Comment by gathogojr** [comment]
@Molinware https://262.ecma-international.org/#sec-date-time-string-format
> Z is the UTC offset representation specified as "Z" (for UTC with no offset) or an offset of either "+" or "-" followed by a time expression HH:mm (indicating local time ahead of or behind UTC, respectively)

Therefore, "2022-12-27T17:51:09.2125084+00:00" and "2022-12-27T17:51:09.2125084Z" are equivalent.

**Comment by gathogojr** [comment]
@Molinware Alternatively, you could supply your own converter as follows:

1. Override `ODataPayloadValueConverter`
    ```csharp
    public class CustomODataPayloadValueConverter : ODataPayloadValueConverter
    {
        public override object ConvertToPayloadValue(object value, IEdmTypeReference edmTypeReference)
        {
            if (edmTypeReference.PrimitiveKind() == EdmPrimitiveTypeKind.DateTimeOffset)
            {
                var dateTimeOffset = (DateTimeOffset)value;
                return dateTimeOffset.ToString("yyyy-MM-dd'T'HH:mm:ss.fffffffzzz");
            }

            return base.ConvertToPayloadValue(value, edmTypeReference);
        }
    }
    ```
2. Inject the custom converter into the DI container
    ```csharp
    public void Configure(IApplicationBuilder app)
    {
        var modelBuilder = new ODataConventionModelBuilder();
        // YOUR LOGIC FOR BUILDING EDM MODEL

        app.UseRouting();

        app.UseEndpoints(endpoints =>
        {
            endpoints.Select().Filter().OrderBy().Expand().Count().SkipToken().MaxTop(null);
            endpoints.MapODataRoute("YOUR_ROUTE_NAME", "YOUR_ROUTE_PREFIX", builder =>
            {
                builder.AddService(Microsoft.OData.ServiceLifetime.Singleton,
                    _ => modelBuilder.GetEdmModel());
                builder.AddService<IEnumerable<IODataRoutingConvention>>(Microsoft.OData.ServiceLifetime.Singleton,
                    _ => ODataRoutingConventions.CreateDefaultWithAttributeRouting("YOUR_ROUTE_NAME", endpoints.ServiceProvider));
                builder.AddService(Microsoft.OData.ServiceLifetime.Singleton, typeof(ODataPayloadValueConverter),
                    _ => new CustomODataPayloadValueConverter());
            });
        });
    }
    ```

**Comment by gathogojr** [comment]
@Molinware Did you get a chance to review the responses I provided above? Please let me know if they helped get you unblocked...

**Comment by Molinware** [comment]
Hello @gathogojr I'll try the custom converter from the sugestion and let you know, but there's something that I want to point it out... When I try without the select:

```
return _dbContext
    .Clients
    .AsNoTracking()
```

2022-12-27T17:51:09.2125084+00:00

**Comment by gathogojr** [comment]
The OData team had a long discussion and decided against implementing a change to format `DateTimeOffset` values (and `DateTime` values by extension) into the longer format where the shorter UTC offset representation (using "Z") is possible. Both representations adhere to the ISO 8601 interchange standard and depending on the requirements, there are those who favour the shorter representation - for reason of payload size for example. Given that there's a reasonably easy-to-implement workaround to tweak the representation, the team prefers to maintain the current behaviour.

**Comment by robertmclaws** [comment]
There seems like an opportunity here for OData to ship the converter as part of the WebAPI library and give it a fluent way to register it.
