### ISSUE TITLE
Error with System.Web.Http depencency in Azure Cloud Service

### ISSUE THREAD

**Issue by cornem** [OData/WebApi#275]
When deploying a cloud service to Azure, web roles that take a dependency on `System.Web.Http.OData` and have the latest `Microsoft.AspNet.WebApi.Core` package installed (5.2.3) cannot start. The web role will remain `Busy`. Looking at the event viewer, the `WaIISHost` process executes code from `drive:\\approot\bin` and looks for `System.Web.Http` version `5.2.2.0` and then crashes. Adding a `bindingRedirect` to `web.config` doesn't fix this problem.

According to the log, it wants 5.2.2.0 because `System.Web.Http.OData` needs it.

After reverting the `Microsoft.AspNet.WebApi.*` packages back to 5.2.2, the role starts.
Is this a problem with this library or actually some bug in `WaIISHost`?

**Comment by DrNixx** [comment]
Yes, I have same problem

**Comment by b-butcher** [comment]
I have the same issue.  Hoping for a timely solution because I have other dependencies on webapi.* 5.2.3.

**Comment by cornem** [comment]
Is there an update on this?

**Comment by LianwMS** [comment]
@cornem @DrNixx @b-butcher Do you still have the same issue? Could you repro the same issue locally?

**Comment by brunotarghetta** [comment]
Please, somebody could fix this issue?

**Comment by congysu** [comment]
OData v3 Web API depends on: Microsoft.AspNet.WebApi.Core (≥ 5.2.2 && < 5.3.0).  @brunotarghetta , can you describe the repro steps, or share a repro project?

**Comment by LianwMS** [comment]
According to the following blog and questions:

Azure: [Blog] (https://azure.microsoft.com/en-us/blog/new-full-iis-capabilities-differences-from-hosted-web-core/)

Stackoverflow: 
[Q1](http://stackoverflow.com/questions/15226494/assembly-binding-redirect-not-working)
[Q2](http://stackoverflow.com/questions/7571208/can-i-access-web-config-from-my-azure-web-role-entry-point/12911703#12911703)

•	Azure SDK 1.3 -1.7 will look in WaIISHost.exe.config
•	Azure SDK 1.8+ will look in the WebRoleProjectName.dll.config.

Could you help to change and verify if it’s work?

**Comment by cornem** [comment]
We are not using Cloud Services anymore (using App Service instead), but
I'm pretty sure we were already using 2.x. If I remember correctly, when we
first started using Azure we already used 2.1.

Kind regards,

Corné Meerkerk



KvK: 08164242
