### ISSUE TITLE
Empty unbound function does not work.

### ISSUE THREAD

**Issue by cyh1220** [OData/WebApi#2762]
*Short summary (3-5 sentences) describing the issue.*

Is it possible to have "empty" unbound function?

I have two routing paths will be the same when the second one with entity
`config.MapODataServiceRoute("odata2", "{version}/{tenant}/groups/{group}/", model)`
`config.MapODataServiceRoute("odata", "{version}/{tenant}/", model)`

In model:
`var groups = builder.EntitySet<Group>("groups");`
`groups.EntityType.HasKey(w => w.Id);`
`groups.EntityType.Property(w => w.Id).Name = "id";`

I need to return the entity when the url hit the first one.

I tried "empty unbound function" in model:
`builder.Function("").ReturnsFromEntitySet<Group>("groups");`

In controller API:
`[ODataRoute("")]`
`public Group GetGroup([FromODataUri] Guid group) {...}`

When I request to the `{version}/{tenant}/groups/{group}` (it will hit the first one), I will get "**The related entity set or singleton cannot be found from the OData path**".

Is this by design or a bug?

When I change to

`builder.Function("test").ReturnsFromEntitySet<Group>("groups");`

In controller API:
`[ODataRoute("test")]`
`public Group GetGroup([FromODataUri] Guid group) {...}`

and request to `{version}/{tenant}/groups/{group}/test`, it works fine.

### Assemblies affected

microsoft.aspnet.odata\5.9.0

**Comment by xuzhg** [comment]
@cyh1220 'Is it possible to have an "empty" unbound function?' It seems you want to create an unbound function with an "empty" name. From the OData spec, the unbound function name should be a simple identifier.

**Comment by cyh1220** [comment]
@xuzhg  Thank you for the info. So this is not allowed. Can we have related limitation in the document? I can't find any like naming limitation in document 
https://learn.microsoft.com/en-us/odata/webapi-8/fundamentals/actions-functions#unbound-function
https://learn.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/odata-actions-and-functions#example-adding-an-unbound-function

**Comment by gathogojr** [comment]
Question responded to
