### ISSUE TITLE
Can support composite key in routing convention

### ISSUE THREAD

**Issue by xuzhg** [OData/WebApi#277]
for example:

I have an entity type with multiple keys. 
Now, I try to get the entity with the keys.
```C#
~/Customers(key1=x,key2=y)
```
but, the routing convention can't support this.

**Comment by LianwMS** [comment]
#307

**Comment by xuzhg** [comment]
See commit: 4e23aabcf9a171a844bd11f1882bf1038cb4a3b8

Thanks.
