### ISSUE TITLE
High CPU usage after updating to Microsoft.AspNet.OData 7.6.5

### ISSUE THREAD

**Issue by RyanMarcotte** [OData/WebApi#2782]
Related to #2731 

I updated from `Microsoft.AspNet.OData` from 7.5.14 to 7.6.5 and the new package version caused significant slowdown for our website deployed to Azure App Service.  The CPU trace I collected looks very similar (if not exactly the same) as what I collected for the original issue.

![image](https://github.com/OData/WebApi/assets/1458084/2cedd312-9e69-4ce9-8ae0-9c064b806432)

**Comment by robertmclaws** [comment]
Yep, I saw the same issue with the 7.6.5 release for [Restier](https://githun/odata/restier) and had to roll back to 7.5.18 as a result. I believe there is a race condition in the new "bulk processing" logic and the team has yet to track it down.

**Comment by KenitoInc** [comment]
This issue was fixed by #2769 
We will be releasing a new version before end of the week

**Comment by RyanMarcotte** [comment]
Sounds good, thank you

**Comment by KenitoInc** [comment]
Test the new version v7.7.0
https://github.com/OData/WebApi/releases/tag/v7.7.0
https://www.nuget.org/packages/Microsoft.AspNetCore.OData/7.7.0
https://www.nuget.org/packages/Microsoft.AspNet.OData/7.7.0

**Comment by RyanMarcotte** [comment]
Will do, thanks!

**Comment by mikepizzo** [comment]
@Robert ***@***.***> -- Can you see if the latest build addresses your performance issues?

Thanks!

________________________________
