### ISSUE TITLE
'Value cannot be null. (Parameter 'type')' on POST

### ISSUE THREAD

**Issue by komdil** [OData/WebApi#2787]
**Assemblies affected**
Microsoft.AspNetCore.OData 7.7.0

**Describe the bug**
I Just updated from 7.6.4 to 7.7.0 and my tests start failing because of this exception

**Reproduce steps**
Post entity

**Data Model**
My entity is simple. Here is metadata: 
```
<EntityType Name="SAStudent" BaseType="Model.Entities.IEntity">
                <Property Name="Id" Type="Edm.String" />
                <Property Name="IQ" Type="Edm.Int32" Nullable="false" />       
                <NavigationProperty Name="SABackpacks" Type="Collection(Model.Entities.SABackpack)" Label="Backpacks" DataType="SABackpack" IdealLength="0" />
                <Annotation Term="OData.Community.Keys.V1.AlternateKeys">
                    <Collection>
                        <Record Type="OData.Community.Keys.V1.AlternateKey">
                            <PropertyValue Property="Key">
                                <Collection>
                                    <Record Type="OData.Community.Keys.V1.PropertyRef">
                                        <PropertyValue Property="Alias" String="Id" />
                                        <PropertyValue Property="Name" PropertyPath="Id" />
                                    </Record>
                                </Collection>
                            </PropertyValue>
                        </Record>
                    </Collection>
                </Annotation>
            </EntityType>

```

**Request/Response**
My request info: 
OData feature path: ~/entityset
Request query: empty
I will provide more info if needed

**Expected behavior**
Post should work

**Additional context**
```
This exception was originally thrown at this call stack:
    Microsoft.OData.Edm.ExtensionMethods.NavigationProperties(Microsoft.OData.Edm.IEdmStructuredType)
    Microsoft.AspNet.OData.Query.ExpandQueryBuilder.GenerateExpandQueryStringInternal(object, Microsoft.OData.Edm.IEdmModel, bool)
    Microsoft.AspNet.OData.Query.ExpandQueryBuilder.GenerateExpandQueryParameter(object, Microsoft.OData.Edm.IEdmModel)
    Microsoft.AspNet.OData.EnableQueryAttribute.GenerateExpandQueryFromPayload(Microsoft.AspNetCore.Mvc.Filters.ActionExecutingContext)
    Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuting(Microsoft.AspNetCore.Mvc.Filters.ActionExecutingContext)
    Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(Microsoft.AspNetCore.Mvc.Filters.ActionExecutingContext, Microsoft.AspNetCore.Mvc.Filters.ActionExecutionDelegate)
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync.__Awaited|10_0(Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker, System.Threading.Tasks.Task, Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.State, Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Scope, object, bool)
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.ActionExecutedContextSealed)
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.State, ref Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Scope, ref object, ref bool)
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
    ...
```

**Comment by habbes** [comment]
Hello @komdil. What does the controller and POST request (body) look like?

**Comment by komdil** [comment]
> Hello @komdil. What does the controller and POST request (body) look like?

Body request contains JSON, and controller creates a new entity: 

```
        public IActionResult Post(ODataQueryOptions<TEntity> queryOptions, [FromBody] string jsonContent)
        {
            return PostEntity(jsonContent, queryOptions);
        }
```

Note: It is not hitting my breakpoint on POST method.

**Comment by habbes** [comment]
@komdil where is your breakpoint placed? On the return statement? And what is the value of `jsonContent` inside the controller when you make a request, is it `null`?

**Comment by komdil** [comment]
@habbes My JSON body is null. My request doesn't have any query.  My request is just **.../odata/SAStudent**. 
It was working in **7.6.4** version. I need to read a string from the body because in my case, the body can have dynamic properties, and can have two properties with the same name and different types and others. So, I cannot make it a fixed type

**Comment by jimivey** [comment]
fwiw, we just encountered a similar error when updating Microsoft.AspNet.OData from 7.6.5 to 7.7.0. POST operations work fine in a live environment (invoked via Postman), but fail in our NUnit tests, indicating there's potentially something in our mock environment that's triggering the problem).  Below is a partial traceback from the Internal Server Error that's thrown.

Summary:
- Updating Microsoft.Asp.Net.OData from 7.6.5 to 7.7.0
- POST actions fail with an Internal Server Error during unit tests.
- All other OData GET actions and query options are working fine.
- If we invoke them in a live environment (using IIS and Postman), they work fine.
- If we revert to 7.6.5 the POST actions start working again in the unit tests.
 
Hope the information helps with your diagnosis.


`at Microsoft.OData.Edm.EdmUtil.CheckArgumentNull[T](T value, String parameterName)
 at Microsoft.OData.Edm.ExtensionMethods.NavigationProperties(IEdmStructuredType type)
 at Microsoft.AspNet.OData.Query.ExpandQueryBuilder.GenerateExpandQueryStringInternal(Object value, IEdmModel model, Boolean isNestedExpand)
 at Microsoft.AspNet.OData.EnableQueryAttribute.GenerateExpandQueryFromPayload(HttpActionContext context)
 at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)
 at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutedAsync(HttpActionExecutedContext actionExecutedContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()]}`
