### ISSUE TITLE
Open type dictionary input is not getting parsed in ODataActionParameters

### ISSUE THREAD

**Issue by peetlotla** [OData/WebApi#2799]
Our service have two model classes, one for ContentProperties and another for CustomProperties. Both are open types. When custom properties (dynamic properties) are provided in the request payload the ODataActionParameters are getting set to NULL.

### Assemblies affected

Microsoft.AspNet.OData.dll
version: .nuget\packages\microsoft.aspnet.odata\7.4.1\lib\net45\Microsoft.AspNet.OData.dll

### Reproduce steps

Model two input classes as shown below. 
```csharp
public class ContentProperties
{
  // ...
    public CustomProperties CustomProperties { get; set; }
}

public class CustomProperties
{
  public Dictionary<string, object> DynamicProperties { get; set;}
}
```
Add following changes to the webapiconfig.cs
```csharp
builder.ComplexType<CustomProperties>();
```

And send the below payload in the request: 
```json
 "contentProperties":{         
         "customProperties":{
            "customer":[
               "contoso",
               "rebel"
            ],
            "devops":[
               "albie"
            ]
         }
      }
```

### Expected result

ODataActionParameters set with contentProperties, customProperties

### Actual result

ODataActionParameters set to NULL

### Additional detail

API used for testing --
public async Task<HttpResponseMessage> Post([FromODataUri] string userId, **ODataActionParameters** parameters)

**Comment by gathogojr** [comment]
Thank you @peetlotla for reporting this issue. I have a few questions:
- How is `ContentProperties` an open type? It doesn't have a property of a type assignable to `IDictionary<string, object>` like `CustomProperties` does.
- Is you Edm action bound or unbound?
- Can you include the Edm function configuration code snippet?

Assuming in your Edm configuration code you defined a parameter named `param` of type `ContentProperties`, your payload should look as follows:
```json
{
    "param": {
        "customProperties": {
            "customer": ["contoso", "rebel"],
            "devops": ["albie"]
        }
    }
}
```

Let me know if this helps.

**Comment by peetlotla** [comment]
Observation: 
A payload where the **customProperties** object does not contain collection values, i.e. using primitive keys and values goes through. The payload gets correct deserialized, the issue is with collections as values that we're facing.

[WebApiConfig.cs](https://o365exchange.visualstudio.com/O365%20Core/_git/M365-DCS?path=/sources/dev/Dlp/src/Dcs/Server/WebRole/App_Start/WebApiConfig.cs&_a=contents&version=GBmaster)

**Working:** 
         "customProperties":{
            "customer":"abc",
            "devops": 2
         }

**Not Working:**

         "customProperties":{
            "customer": ["abc"],
            "devops": ["x", "y"]
         }

**Comment by gathogojr** [comment]
You could try adding the `@odata.type` property annotation as follows:
```json
     "customProperties":{
        "customer@odata.type": "#Collection(Edm.String)",
        "customer": ["abc"],
        "devops@odata.type": "#Collection(Edm.String)",
        "devops": ["x", "y"]
     }
```

**Comment by peetlotla** [comment]
It's working with odata.type annotation. Should the clients require to sent this or any other way to address this from the server side?

**Comment by gathogojr** [comment]
The client shouldn't have to include the odata.type annotations for an array of strings or primitives. Based on the details provided, I can't tell whether there's an issue with the service setup.

**Comment by peetlotla** [comment]
Here's the code snippet for the edm model used by our service - can you take a look?

// ---------------------------------------------------------------------------
// <copyright file="WebApiConfig.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------

namespace Microsoft.O365.UnifiedDlp.Service
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net.Http;
    using System.Web.Http;
    using System.Web.Http.ExceptionHandling;
    using System.Web.Http.ModelBinding;
    using System.Web.Http.ModelBinding.Binders;
    using Microsoft.AspNet.OData.Builder;
    using Microsoft.AspNet.OData.Extensions;
    using Microsoft.AspNet.OData.Routing;
    using Microsoft.AspNet.OData.Routing.Conventions;
    using Microsoft.O365.UnifiedDlp.Server.Common;
    using Microsoft.O365.UnifiedDlp.Server.Contract;
    using Microsoft.O365.UnifiedDlp.Server.DcsFlightSettingMgmt;
    using Microsoft.OData;
    using Microsoft.OData.Edm;
    using Microsoft.OData.UriParser;
    using Microsoft.Owin.Security.OAuth;

    /// <summary>
    /// Class to configure the WebApi settings
    /// </summary>
    public static class WebApiConfig
    {
        /// <summary>
        /// Ambiguous enums in EDM model. These enums were found to have duplicate entries in EDM model
        /// schema elements. This is needed for mitigation and will be cleaned up later.
        /// </summary>
        private static readonly ISet<string> ambiguousEnumTypes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "AccessScope",
            "BrowserRestrictionTrigger",
            "RuleMode",
        };

        /// <summary>
        /// Namespace for the Contract project
        /// </summary>
        private const string ContractNamespace = "Microsoft.O365.UnifiedDlp.Server.Contract";

        /// <summary>
        /// Registers various settings
        /// </summary>
        /// <param name="config">object where the settings are configured</param>
        public static void Register(HttpConfiguration config)
        {
            // Only Json formatter
            var json = config.Formatters.JsonFormatter;
            json.SerializerSettings.PreserveReferencesHandling = Newtonsoft.Json.PreserveReferencesHandling.None;
            config.Formatters.Remove(config.Formatters.XmlFormatter);

            if (DedicatedDcsSettingsFlightsProvider.IsDedicatedAsynchronousRequestPipelineEnaled())
            {
                config.Formatters.JsonFormatter.SerializerSettings.Converters.Add(new BatchEvaluationInputJsonConverter());
                SimpleModelBinderProvider provider = new SimpleModelBinderProvider(typeof(GenericBatchRequest), new GenericRequestBatchApiInputBinder());
                config.Services.Insert(typeof(ModelBinderProvider), 0, provider);
            }

            // Exception handlers for all unhandled exceptions
            config.Services.Add(typeof(IExceptionLogger), new GlobalExceptionLogger());
            config.Services.Replace(typeof(IExceptionHandler), new GlobalExceptionHandler());

            // Set thread culture and log the request data. Logging is done here because this is
            // the first handler that gets invoked.
            config.MessageHandlers.Insert(0, new MessageCultureHandler());

            // Enable Odata query
            config.AddODataQueryFilter();

            if (!DedicatedDcsConfigurationProvider.IsDedicatedServiceMode)
            {
                config.Filters.Add(new RedirectionFilterAttribute());
            }

            config.Filters.Add(new ControllerActionFilterAttribute());

            // OData routes
            // config.SetUrlConventions(ODataUrlConventions.KeyAsSegment);
            // config.EnableUnqualifiedNameCall(true);
            // TODO VSO 961221, upgrade Odata to 4.01 part 2 or make onebox working with OData Conventional URL 

            // Remove MetadataRoutingConvention from default.
            // Block all requests which are not defined in edmModel.
            IEdmModel edmModel = GenerateODataModelBuilder(config).GetEdmModel();
            var defaultConventions = ODataRoutingConventions.CreateDefaultWithAttributeRouting("ODataMSGrpahRoute", config);
            var customizedConventions = defaultConventions.Except(defaultConventions.OfType<MetadataRoutingConvention>());

            IEdmModel edmModelOdataRoute = GenerateODataModelBuilder(config).GetEdmModel();
            var defaultConventionsOdataRoute = ODataRoutingConventions.CreateDefaultWithAttributeRouting("ODataRoute", config);
            var customizedConventionsOdataRoute = defaultConventionsOdataRoute.Except(defaultConventionsOdataRoute.OfType<MetadataRoutingConvention>());

            // Substrate getting labels APIs have a prefix "compliancePolicy".
            // Since DCS and Substrate are sharing the same MSGraph CSDL file, DCS has to support this prefix.
            config.Count().Filter().OrderBy().Expand().Select().MaxTop(null);
            config.MapODataServiceRoute(
               routeName: "ODataMSGrpahRoute",
               routePrefix: "compliancePolicy",
                builder =>
                builder.AddService<IEdmModel>(ServiceLifetime.Singleton, sp => edmModel)
                       .AddService<IODataPathHandler, DefaultODataPathHandler>(ServiceLifetime.Singleton)
                       .AddService<ODataUriResolver>(ServiceLifetime.Singleton, sp => new UnqualifiedCallAndEnumPrefixFreeResolver { EnableCaseInsensitive = true })
                       .AddService<IEnumerable<IODataRoutingConvention>>(ServiceLifetime.Singleton, sp => customizedConventions));
            config.MapODataServiceRoute(
               routeName: "ODataRoute",
               routePrefix: null,
                builder =>
                builder.AddService<IEdmModel>(ServiceLifetime.Singleton, sp => edmModelOdataRoute)
                       .AddService<IODataPathHandler, DefaultODataPathHandler>(ServiceLifetime.Singleton)
                       .AddService<ODataUriResolver>(ServiceLifetime.Singleton, sp => new UnqualifiedCallAndEnumPrefixFreeResolver { EnableCaseInsensitive = true })
                       .AddService<IEnumerable<IODataRoutingConvention>>(ServiceLifetime.Singleton, sp => customizedConventionsOdataRoute));
            config.EnableDependencyInjection();
        }

        /// <summary>
        /// Generate <see cref="ODataConventionModelBuilder"/>.
        /// </summary>
        /// <param name="config"><see cref="HttpConfiguration"/> object.</param>
        /// <returns><see cref="ODataConventionModelBuilder"/> object.</returns>
        private static ODataConventionModelBuilder GenerateODataModelBuilder(HttpConfiguration config)
        {
            ODataConventionModelBuilder builder = new ODataConventionModelBuilder(config);
            builder.Namespace = Constants.ODataNamespace;
            builder.OnModelCreating = FixAmbiguousEnumTypes;

            // Users Segment
            EntitySetConfiguration<User> userConfig = builder.EntitySet<User>(DlpConstants.ODataUsersEntityName);
           
            builder.EntityType<User>().ContainsOptional(e => e.InformationProtection).Name =
                DlpConstants.ODataInformationProtectionSingletonEntityName;

            // Data Classification segment
            builder.Singleton<DataClassification>(DlpConstants.ODataDataClassificationSingletonEntityName);
            
            // Information protection singleton
            builder.Singleton<InformationProtection>(DlpConstants.ODataInformationProtectionSingletonEntityName);

            builder.EntityType<DataClassification>().ContainsMany(e => e.SensitiveTypes).Name =
                DlpConstants.SensitiveTypesEntitySetName;

            builder.EntityType<DataClassification>().ContainsMany(e => e.Jobs).Name =
                DlpConstants.JobsEntitySetName;
            builder.EntityType<DataClassification>().ContainsMany(e => e.ClassifyTextJobs).Name =
                DlpConstants.ClassifyTextJobTypesEntitySetName;
            builder.EntityType<DataClassification>().ContainsMany(e => e.EvaluateLabelJobs).Name =
                DlpConstants.EvaluateLabelJobTypesEntitySetName;
            builder.EntityType<DataClassification>().ContainsMany(e => e.EvaluateDlpPoliciesJobs).Name =
                DlpConstants.EvaluateDlpPoliciesJobTypesEntitySetName;
            builder.EntityType<DataClassification>().ContainsMany(e => e.SensitivityLabels).Name =
                DlpConstants.LabelsEntitySetName;
            builder.EntityType<DataClassification>().ContainsMany(e => e.ClassifyText).Name =
                Constants.ClassifyTextODataActionName;
            builder.EntityType<DataClassification>().ContainsMany(e => e.Health).Name =
                Constants.HealthCheckODataActionName;
            builder.EntityType<DataClassification>().ContainsMany(e => e.ClassifyAndEvaluateJobs).Name =
                DlpConstants.EvaluateBatchJobTypesEntitySetName;
            builder.EntityType<DataClassification>().ContainsMany(e => e.Sessions).Name = 
                DlpConstants.SessionsEntitySetName;
            builder.AddEnumType(typeof(SensitiveTypeScope));

            // Make DetectedSensitiveContent and its derived classes complex types.
            builder.ComplexType<DetectedSensitiveContentBase>();
            builder.ComplexType<DetectedSensitiveContent>();
            builder.ComplexType<MlDetectedSensitiveContent>();

            // Make LabelPolicy a complex type.
            builder.ComplexType<LabelPolicy>();
            builder.ComplexType<DetectedSensitiveContentWrapper>();
            builder.ComplexType<MatchingLabel>();
            builder.ComplexType<ResponsibleSensitiveType>();
            builder.ComplexType<ResponsiblePolicy>();
            builder.ComplexType<CurrentLabel>();

            NavigationPropertyConfiguration sublabelsConfig = builder.EntityType<SensitivityLabel>().ContainsMany(e => e.Sublabels);
            sublabelsConfig.AutoExpand = true;
            sublabelsConfig.Name = Constants.SublabelsPropertyName;

            builder.Action(DlpConstants.OverrideUpdateODataActionName).Parameter<string>(Constants.ODataParamNameOverrideUpdate);
            builder.Action(DlpConstants.OverrideGetODataActionName).Returns<FlightSettingsOverrideResponse>();

            // Users Segment
            builder.EntityType<User>().ContainsOptional(e => e.InformationProtection).Name =
                DlpConstants.ODataInformationProtectionSingletonEntityName;

            // Information Protection Segment
            builder.EntityType<InformationProtection>().ContainsMany(e => e.SensitivityLabels).Name =
                DlpConstants.LabelsEntitySetName;
            builder.EntityType<InformationProtection>().ContainsMany(e => e.DlpPolicies).Name =
                DlpConstants.DlpPolicyEntitySetName;

            builder.EntityType<InformationProtection>().ContainsOptional(e => e.SensitivityPolicySettings).Name =
                DlpConstants.SensitivityPolicySettingsSingletonEntityName;

            FunctionConfiguration applicablePoliciesFunction = builder.EntityType<InformationProtection>().Function("GetApplicablePolicies");
            applicablePoliciesFunction.Parameter<string>("tenantId");
            applicablePoliciesFunction.Parameter<string>("policyType");
            applicablePoliciesFunction.Parameter<string>("workload");
            applicablePoliciesFunction.Returns<bool>();

            FunctionConfiguration serviceConfigFunction = builder.EntityType<InformationProtection>().Function("GetServiceConfiguration");
            serviceConfigFunction.ReturnsCollectionFromEntitySet<ServiceInfo>("serviceInfo");

            // Classify Text Action Definition
            ActionConfiguration classifyAction =
                builder.EntityType<DataClassification>().Action(Constants.ClassifyTextODataActionName);
            classifyAction.Parameter<string>(Constants.ODataParamNameText);
            classifyAction.Parameter<string>(Constants.ODataParamNameFileExtension);
            classifyAction.CollectionParameter<string>(Constants.ODataParamNameSensitiveTypeIds);
            classifyAction.Parameter<SensitiveTypeScope?>(Constants.ODataParamNameScopesToRun);
            classifyAction.Parameter<MlClassificationMatchTolerance?>(Constants.ODataParamNameMatchTolerance);
            classifyAction.Parameter<ClassifyFileUri>(Constants.ODataParamNameClassifyFileUri);
            classifyAction.Parameter<ContentMetaData>(Constants.ODataParamNameContentMetaData);
            classifyAction.ReturnsFromEntitySet<ClassificationJobResponse>(DlpConstants.ClassifyTextJobTypesEntitySetName);

            // Health check Action Definition
            ActionConfiguration healthAction =
                builder.EntityType<DataClassification>().Action(Constants.HealthCheckODataActionName);
            healthAction.Returns<HttpResponseMessage>();

            // Label Evaluation Action Definition
            ActionConfiguration labelAction =
                builder.EntityType<SensitivityLabel>().Collection.Action(DlpConstants.EvaluateLabelODataActionName);
            labelAction.CollectionParameter<DiscoveredSensitiveType>(Constants.ODataParamNameDiscoveredSensitiveTypes);
            labelAction.Parameter<string>(Constants.ODataParamNameApplicableTo);
            labelAction.ReturnsFromEntitySet<EvaluateLabelJobResponse>(DlpConstants.EvaluateLabelJobTypesEntitySetName);

            // DLP Policy Evaluation Action Definition
            ActionConfiguration dlpPolicyEvaluateAction =
                builder.EntityType<DlpPolicy>().Collection.Action(DlpConstants.EvaluateDlpPolicyODataActionName);
            dlpPolicyEvaluateAction.Parameter<string>(Constants.ODataParamNameTarget);
            dlpPolicyEvaluateAction.Parameter<DlpEvaluationInput>(Constants.ODataParamNameEvaluationInput);
            dlpPolicyEvaluateAction.Parameter<DlpNotification>(Constants.ODataParamNameNotificationInfo);
            dlpPolicyEvaluateAction.ReturnsFromEntitySet<DlpEvaluatePoliciesJobResponse>(DlpConstants.EvaluateDlpPoliciesJobTypesEntitySetName);

            // classify and evaluate batch api
            // Make customProperties, contentProperties and FileContentProperties Open type
            builder.ComplexType<CustomProperties>();
            builder.ComplexType<ContentProperties>();
            builder.ComplexType<FileContentProperties>();

            // Binding action
            ActionConfiguration batchEvaluateAction =
                builder.EntityType<InformationProtection>().Action(DlpConstants.BatchClassifyAndEvaluateODataActionName);
            batchEvaluateAction.Parameter<TextClassificationRequest>(Constants.ODataParamNameBatchClassifyText);
            batchEvaluateAction.Parameter<EvaluateSharedParametersRequest>(Constants.ODataParamNameBatchEvaluateSharedParameters);
            batchEvaluateAction.Parameter<LabelEvaluationRequest>(Constants.ODataParamNameBatchEvaluateLabel);
            batchEvaluateAction.Parameter<DlpPolicyEvaluationRequest>(Constants.ODataParamNameBatchEvaluateDlpPolicies);
            batchEvaluateAction.Parameter<EvaluationContextRequest>(Constants.ODataParamNameEvaluationContextParameters).Optional();
            batchEvaluateAction.ReturnsFromEntitySet<BatchClassifyAndEvaluateJobResponse>(DlpConstants.EvaluateBatchJobTypesEntitySetName);

            ActionConfiguration submitRequestConfiguration =
                builder.EntityType<InformationProtection>().Action(Constants.SubmitEvaluationRequestODataActionName);
            submitRequestConfiguration.Returns<HttpResponseMessage>();

            // Notify Tenant Change Action
            ActionConfiguration notifyTenantChange =
                builder.EntityType<DataClassification>().Action(Constants.NotifyTenantChangeODataActionName);
            notifyTenantChange.Parameter<TenantChangeType>(Constants.ODataParamNameTenantChangeType);

            return builder;
        }

        /// <summary>
        /// Types other than the ones defined in Contract project are registered with EDM model. This causes ambiguous element binding error
        /// since there are two types defined with same name. This method renames the types coming from other places to avoid the error. This
        /// is a temporary mitigation and will be cleaned up later.
        /// </summary>
        /// <param name="builder"></param>
        private static void FixAmbiguousEnumTypes(ODataConventionModelBuilder builder)
        {
            foreach (EnumTypeConfiguration enumDef in builder.EnumTypes)
            {
                if (ambiguousEnumTypes.Contains(enumDef.Name) && enumDef.ClrType.Namespace != ContractNamespace)
                {
                    enumDef.Name = "Duplicate" + enumDef.Name;
                }
            }
        }
    }
}

**Comment by gathogojr** [comment]
@peetlotla I don't see any Edm action here that accepts a `ContentProperties` parameter.

**Comment by gathogojr** [comment]
As discussed offline, for Microsoft.AspNet.OData 7.4.1, you're required to include `@odata.type` property annotations in the payload, i.e.:
```json
     "customProperties":{
        "customer@odata.type": "#Collection(Edm.String)",
        "customer": ["abc"],
        "devops@odata.type": "#Collection(Edm.String)",
        "devops": ["x", "y"]
     }
```
