### ISSUE TITLE
NullReferenceException in ExpandQueryBuilder when using camelCase property names

### ISSUE THREAD

**Issue by strandman** [OData/WebApi#2805]
NullReferenceException occures in ExpandQueryBuilder.GenerateExpandQueryStringInternal when using camelCase property names in OData

### Assemblies affected

Microsoft.AspNetCore.OData

### Reproduce steps

Post an camel cased payload to an OData endpoint thar requires an expand

### Expected result

No exception

### Actual result

NullReferenceException 

### Additional detail

[Line 73 in ExpandQueryBuilder.cs:](https://github.com/OData/WebApi/blob/117490b7fa9312e52aa3a9a2390ec2f01f5f6645/src/Microsoft.AspNet.OData.Shared/Query/ExpandQueryBuilder.cs#L73)

`//This does not work and "prop" will be null with camel cased properties`
`PropertyInfo prop = type.GetProperty(navProp.Name);`

**Comment by corranrogue9** [comment]
@strandman can you provide an example model and the request that you are making that causes the exception?

@xuzhg has some ideas on an extension method that the `ExpandQueryBuilder` should be calling instead

**Comment by KenitoInc** [comment]
@strandman Kindly share a repro
