### ISSUE TITLE
 'Microsoft.AspNet.WebApi.Core 5.3.0' is not compatible with 'Microsoft.AspNet.OData 7.7.2 constraint: Microsoft.AspNet.WebApi.Core (>= 5.2.2 && < 5.3.0)'

### ISSUE THREAD

**Issue by premiaware** [OData/WebApi#2818]
When i try to update my nuGet Pack in my ASPNet Web API i have follow message:

Severity	Code	Description	Project	File	Line	Suppression State
Unable to resolve dependencies. 'Microsoft.AspNet.WebApi.Core 5.3.0' is not compatible with 'Microsoft.AspNet.OData 7.7.2 constraint: Microsoft.AspNet.WebApi.Core (>= 5.2.2 && < 5.3.0)'.				

Is possibile to fix?

**Comment by xuzhg** [comment]
duplicated #2814.

**Comment by xuzhg** [comment]
We will relax the version and have a new version out soon.
