### ISSUE TITLE
No virtual method for creating Delta ComplexNestedResourceInfo

### ISSUE THREAD

**Issue by victorliu-microsoft** [OData/WebApi#2858]
I am writing a custom Odata serializer that inherits from ODataResourceSerializer, overriding the CreateResource method. My goal is to conditionally filter out some properties to hide them from certain apps calling our service. We have success in filtering out some structural properties from our resource. I am also able to filter out complex nested resources through overriding CreateComplexNestedResourceInfo. 

However, I am now trying to filter out a complex property for delta and noticed that the code doesn't run through CreateComplexNestedResourceInfo. It creates the complex resource through private methods in [WriteDeltaResource](https://github.com/OData/WebApi/blob/651c83ddb20703d13083d737ae8006ac0a3ec013/src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceSerializer.cs#L2089)

We need a way to override creating the delta complex resource, where if the overridden method returns null, that complex property won't show up in the serialized odata output. Something like a virtual "CreateDeltaComplexNestedResourceInfo".

### Assemblies affected

OData WebApi lib 7.7.6.0

**Comment by xuzhg** [comment]
Once I receive the approval, I will merge it and update the release version. So far, it could be 7.7.7.

**Comment by victorliu-microsoft** [comment]
@xuzhg Thanks for getting this in, do you know when it will be released and ready for me to use? Thank you!!
