### ISSUE TITLE
Support getting instance annotations in request payloads in Web API

### ISSUE THREAD

**Issue by dingeins** [OData/WebApi#289]
The requirement comes from CRM. They'd like to allow special control information to be passed together with the data to the service when doing posts/updates.

It's also useful from a general perspective, e.g. `@odata.type` annotation be passed together with the complex type in a entity post to indicate if a base type instance or a derived type instance is posted, if the base type is defined in the model.

The current behavior, as is confirmed by our engineer, is the core lib will ignore the instance annotations in request payloads. The support in Web API should be depending on this support.

**Comment by dingeins** [comment]
The related issue in ODataLib: https://github.com/OData/odata.net/issues/146

**Comment by mikepizzo** [comment]
Closing/Not Fixed in absence of a contribution or community support.

**Comment by RamjotSingh** [comment]
@mikepizzo Are there plans to fix this? We need this feature too. I see that odata.net repo does support instance annotations. If you can point me in the right direction on how to solve I can contribute the fix.

**Comment by xuzhg** [comment]
@RamjotSingh Thanks for querying this feature. Yes, we are working on this feature. @Sreejithpin takes the ownership of this. I'd like to see this feature in the next version. We'd love to see your contribution. Please contact with @Sreejithpin

**Comment by habbes** [comment]
Closing this issue as it appears to have been addressed in the linked PR. If this still affects the latest versions of the library, kindly open a new issue.
