### ISSUE TITLE
Please add support for entity key that are composed

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#29]
Currently in order to support composite entity key we have to add new routing
conventions to ODATA web api server.  
  
Since entity key may be composite according to ODATA spec it shall be a
feature ODATA web api supports out-of-the box.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 898](http://aspnetwebstack.codeplex.com/workitem/898)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 11, 2013 at 3:26 PM
**Reported by:**	h28669
**Updated on:**	Sep 15, 2014 at 7:40 PM
**Updated by:**	mattvan

**Comment by LianwMS** [comment]
On *2013-04-07 02:09:48 UTC*, **HongmeiG** commented:

We have an official sample to show you how you can make this work today. I will keep this feature request for vNext.


https://aspnet.codeplex.com/SourceControl/changeset/view/9cb7243bd9fe3b2df484bf2409af943f39533588#Samples/WebApi/ODataCompositeKeySample/ReadMe.txt

**Comment by xuzhg** [comment]
Follow： https://github.com/OData/WebApi/pull/727

**Comment by xuzhg** [comment]
Added in commit 4e23aabcf9a171a844bd11f1882bf1038cb4a3b8. Thanks.
