### ISSUE TITLE
orderby whith datetime field Broken in 5.5.1 woorked in 5.4

### ISSUE THREAD

**Issue by jonjalberghini** [OData/WebApi#293]
You have just released a version that breaks more than it fixes.
in 5.4 you added support for datetime and I could then use the orderby command without any work arounds this release (the only change I made )
breaks that see error below
http://localhost:18832/Aas/AppUsers?$orderby=CreatedAt%20desc

works currently with 5.4 with all components up-to-date with the newest stable versions.

CreatedAt is a datetime type using the fix supplied in 5.4 to allow datetime fields in the model.
Model definition (it doesn't matter if it is nullable or not)
		[Column(TypeName = "timestamp")]
		public System.DateTime? CreatedAt { get; set; }
		[Column(TypeName = "timestamp")]
		public System.DateTime? UpdatedAt { get; set; }

I install the new 5.5.1 and change nothing else rebuild and 
Install-Package Microsoft.AspNet.OData -Version 5.5.1
Install-Package Microsoft.AspNet.WebApi.OData -Version 5.5.1
I get the following error
{
  "error":{
    "code":"","message":"An error has occurred.","innererror":{
      "message":"The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; odata.metadata=minimal'.","type":"System.InvalidOperationException","stacktrace":"","internalexception":{
        "message":"The specified type member 'Kind' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported.","type":"System.NotSupportedException","stacktrace":"   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberAccessTranslator.TypedTranslate(ExpressionConverter parent, MemberExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.EqualsTranslator.TypedTranslate(ExpressionConverter parent, BinaryExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.BinaryTranslator.TypedTranslate(ExpressionConverter parent, BinaryExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.ConditionalTranslator.TypedTranslate(ExpressionConverter parent, ConditionalExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input, DbExpressionBinding& binding)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, DbExpression& source, DbExpressionBinding& sourceBinding, DbExpression& lambda)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SequenceMethodTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, SequenceMethod sequenceMethod)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.Convert()\r\n   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()\r\n   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()\r\n   at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()\r\n   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()\r\n   at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteFeed(IEnumerable enumerable, IEdmTypeReference feedType, ODataWriter writer, ODataSerializerContext writeContext)\r\n   at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)\r\n   at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)\r\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders)\r\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()"
      }
    }
  }
}

**Comment by VikingsFan** [comment]
@jonjalberghini , Thanks for your report!
We have a nightly build to unblock your service in myget , could you please try this build? 
Add this link http://www.myget.org/F/aspnetwebstacknightly/ in nuget to get our nightly build.
Waiting for your reply.

**Comment by jonjalberghini** [comment]
Thanks so much this nightly build ran on all my tests 


http://localhost:18832/Aas/AppUsers?$filter=CreatedAt eq 2015-04-08T18:05:57-05:00 

  

No need for casts anymore work perfect against MySQL and SQL server 

  

http://localhost:18832/Aas/AppUsers?$count=true 

  


http://localhost:18832/Aas/AppUsers?$orderby=CreatedAt desc &$count=true 

  

All are working Perfect THANK YOU!!! 

  

When will this release? 

  
----- Original Message -----

**Comment by jonjalberghini** [comment]
This doesn't throw an error but doesn't actually do anything. I am working with april 8th nightly build.

http://localhost:18832/Aas/Cases?$expand=ModifiedUser($filter=FirstName eq 'Eleri')&$count=true

Returns all cases.
This is the SQL produced and nowhere is the filter being applied
Opened connection at 08/04/2015 15:31:47 -04:00
SELECT
`GroupBy1`.`A1` AS `C1`
FROM (SELECT
COUNT(1) AS `A1`
FROM `Case` AS `Extent1`) AS `GroupBy1`
-- Executing at 08/04/2015 15:31:47 -04:00
-- Completed in 51 ms with result: EFMySqlDataReader

Closed connection at 08/04/2015 15:31:47 -04:00
Opened connection at 08/04/2015 15:31:48 -04:00
SELECT
`Extent1`.`Id`, 
@gp1 AS `C1`, 
`Extent1`.`RecordId`, 
`Extent1`.`ReferralId`, 
`Extent1`.`CaseId`, 
`Extent1`.`SourceId`, 
`Extent1`.`MarketingSourceId`, 
`Extent1`.`StatusId`, 
`Extent1`.`PaperId`, 
`Extent1`.`AppUserId`, 
`Extent1`.`PriorityId`, 
`Extent1`.`Summary`, 
`Extent1`.`SummaryDate`, 
`Extent1`.`IsOneOff`, 
`Extent1`.`ModifiedById`, 
`Extent1`.`CreatedAt`, 
`Extent1`.`UpdatedAt`, 
@gp2 AS `C2`, 
@gp3 AS `C3`, 
`Extent2`.`Id` AS `Id1`, 
`Extent2`.`LoginName`, 
`Extent2`.`FirstName`, 
`Extent2`.`LastName`, 
`Extent2`.`EmailAddress`, 
`Extent2`.`IPAddress`, 
`Extent2`.`CreatedAt` AS `CreatedAt1`, 
`Extent2`.`UpdatedAt` AS `UpdatedAt1`, 
0 AS `C4`
FROM `Case` AS `Extent1` INNER JOIN `AppUser` AS `Extent2` ON `Extent1`.`ModifiedById` = `Extent2`.`Id`
-- @gp1: '5c3884fa-2b4d-425a-a360-7bef4bfac38e' (Type = String, IsNullable = false, Size = 36)
-- @gp2: 'ModifiedUser' (Type = String, IsNullable = false, Size = 12)
-- @gp3: '5c3884fa-2b4d-425a-a360-7bef4bfac38e' (Type = String, IsNullable = false, Size = 36)
-- Executing at 08/04/2015 15:31:48 -04:00
-- Completed in 71 ms with result: EFMySqlDataReader

Closed connection at 08/04/2015 15:31:59 -04:00



Samples

{
  "@odata.context":"http://localhost:18832/Aas/$metadata#Cases","@odata.count":5931,"value":[
    {
      "CreatedAt":"2006-07-17T13:52:16Z","UpdatedAt":"2015-03-25T11:14:43Z","SummaryDate":"2005-06-20T00:00:00Z","Id":1,"RecordId":"20060717/1","ReferralId":1,"CaseId":null,"SourceId":29,"MarketingSourceId":5,"StatusId":1,"PaperId":null,"AppUserId":20,"PriorityId":3,"Summary":"On the 20th June \\'O5 the initial contact was made by Mrs Denise Sanderson via telephone on behalf of her sister, regarding her nephew Matthew Jones.","IsOneOff":true,"ModifiedById":20,"ModifiedUser":{
        "Id":20,"LoginName":"209540c0-d2e0-11e4-bf72-00219bfd78f1","FirstName":"Eleri","LastName":"Bingham","EmailAddress":"eleri@childcomwales.org.uk","IPAddress":"0.0.0.0","CreatedAt":"2010-10-08T09:04:31-05:00","UpdatedAt":"2015-03-25T06:14:38-05:00"
      }
    },{
      "CreatedAt":"2006-07-17T14:18:18Z","UpdatedAt":"2015-03-25T11:14:43Z","SummaryDate":"2006-07-17T00:00:00Z","Id":2,"RecordId":"20060717/2","ReferralId":1,"CaseId":null,"SourceId":3,"MarketingSourceId":5,"StatusId":4,"PaperId":null,"AppUserId":12,"PriorityId":3,"Summary":"Mr Adrian Davies has called regarding his son Joshua who has been out of school for 10  months due to bullying. Joshua has had 0 tuition for 8 months and limited tuition over the last 2 months. Joshua has started having behavioural issues. There is a history of sex abuse (2001) that the father does not wish to be brought up as the children have moved on. Joshua was at St Cyres school initially. The father applied for J to go to Stanwell. He was kept waiting for 4 months for a decision and then told the school could not accommodate him. The family went to appeal and the decision was upheld. It seems that Joshua is OFF THE REGISTER. Recently J has gone back to his original school and is having 1 hour a week tuition at St CYres","IsOneOff":false,"ModifiedById":12,"ModifiedUser":{
        "Id":12,"LoginName":"20954011-d2e0-11e4-bf72-00219bfd78f1","FirstName":"John","LastName":"Harford","EmailAddress":"johnh@childcomwales.org.uk","IPAddress":"10.100.1.17","CreatedAt":"2010-10-08T09:04:31-05:00","UpdatedAt":"2015-03-25T06:14:38-05:00"
      }
    },{

**Comment by congysu** [comment]
Filter by no-nullable DateTime: 46ec381f0b82bc9ce3e9f58ea9dbe3064a751b1d.  nested filter in expand question is tracked in https://github.com/OData/WebApi/issues/298.
