### ISSUE TITLE
Formatting issue in xml comments about True and False

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#294]
Specifically, the problems were:
1.	`<see>true</see>`
2.	`<see langword="true"/>`

The `<see>` tag is used for links. Need replace these with just plain text for `True` or `False`.

There were also places were `bool` values formatted as `<c>true</c>` which gets converted to inline code and is therefore probably okay.

**Comment by xuzhg** [comment]
Check at:  eeabd634eef7e422049930681c88859e658c2608
