### ISSUE TITLE
More Linq-to-* end to end tests

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#296]
End to end test cases should cover typical Linq providers: Linq-to-Objects, Linq-to-Entities, Linq-to-SQL.

**Comment by jonjalberghini** [comment]
Thanks so much this nightly build ran on all my tests 


http://localhost:18832/Aas/AppUsers?$filter=CreatedAt eq 2015-04-08T18:05:57-05:00 

  

No need for casts anymore work perfect against MySQL and SQL server 

  

http://localhost:18832/Aas/AppUsers?$count=true 

  


http://localhost:18832/Aas/AppUsers?$orderby=CreatedAt desc &$count=true 

  

All are working Perfect THANK YOU!!! 

  

When will this release?

**Comment by congysu** [comment]
@jonjalberghini Thanks very much for your feedback.  We released 5.6 beta to nuget.org:
http://www.nuget.org/packages/Microsoft.AspNet.OData/5.6.0-beta1
http://odata.github.io/WebApi/#07-06-5-6-beta1

**Comment by VikingsFan** [comment]
checked in b2d93580e4a772c505a95d6be16aa1a9ec7915b9
