### ISSUE TITLE
Nested filter in April 8th nightly build and 5.5.1 does nothing

### ISSUE THREAD

**Issue by jonjalberghini** [OData/WebApi#298]
This doesn't throw an error but doesn't actually do anything. I am working with april 8th nightly build.

http://localhost:18832/Aas/Cases?$expand=ModifiedUser($filter=FirstName eq 'Eleri')&$count=true

Returns all cases.
This is the SQL produced and nowhere is the filter being applied
Opened connection at 08/04/2015 15:31:47 -04:00
SELECT
`GroupBy1`.`A1` AS `C1`
FROM (SELECT
COUNT(1) AS `A1`
FROM `Case` AS `Extent1`) AS `GroupBy1`
-- Executing at 08/04/2015 15:31:47 -04:00
-- Completed in 51 ms with result: EFMySqlDataReader

Closed connection at 08/04/2015 15:31:47 -04:00
Opened connection at 08/04/2015 15:31:48 -04:00
SELECT
`Extent1`.`Id`, 
@gp1 AS `C1`, 
`Extent1`.`RecordId`, 
`Extent1`.`ReferralId`, 
`Extent1`.`CaseId`, 
`Extent1`.`SourceId`, 
`Extent1`.`MarketingSourceId`, 
`Extent1`.`StatusId`, 
`Extent1`.`PaperId`, 
`Extent1`.`AppUserId`, 
`Extent1`.`PriorityId`, 
`Extent1`.`Summary`, 
`Extent1`.`SummaryDate`, 
`Extent1`.`IsOneOff`, 
`Extent1`.`ModifiedById`, 
`Extent1`.`CreatedAt`, 
`Extent1`.`UpdatedAt`, 
@gp2 AS `C2`, 
@gp3 AS `C3`, 
`Extent2`.`Id` AS `Id1`, 
`Extent2`.`LoginName`, 
`Extent2`.`FirstName`, 
`Extent2`.`LastName`, 
`Extent2`.`EmailAddress`, 
`Extent2`.`IPAddress`, 
`Extent2`.`CreatedAt` AS `CreatedAt1`, 
`Extent2`.`UpdatedAt` AS `UpdatedAt1`, 
0 AS `C4`
FROM `Case` AS `Extent1` INNER JOIN `AppUser` AS `Extent2` ON `Extent1`.`ModifiedById` = `Extent2`.`Id`
-- @gp1: '5c3884fa-2b4d-425a-a360-7bef4bfac38e' (Type = String, IsNullable = false, Size = 36)
-- @gp2: 'ModifiedUser' (Type = String, IsNullable = false, Size = 12)
-- @gp3: '5c3884fa-2b4d-425a-a360-7bef4bfac38e' (Type = String, IsNullable = false, Size = 36)
-- Executing at 08/04/2015 15:31:48 -04:00
-- Completed in 71 ms with result: EFMySqlDataReader

Closed connection at 08/04/2015 15:31:59 -04:00

Samples

{
  "@odata.context":"http://localhost:18832/Aas/$metadata#Cases","@odata.count":5931,"value":[
    {
      "CreatedAt":"2006-07-17T13:52:16Z","UpdatedAt":"2015-03-25T11:14:43Z","SummaryDate":"2005-06-20T00:00:00Z","Id":1,"RecordId":"20060717/1","ReferralId":1,"CaseId":null,"SourceId":29,"MarketingSourceId":5,"StatusId":1,"PaperId":null,"AppUserId":20,"PriorityId":3,"Summary":"On the 20th June \\'O5 the initial contact was made by Mrs Denise Sanderson via telephone on behalf of her sister, regarding her nephew Matthew Jones.","IsOneOff":true,"ModifiedById":20,"ModifiedUser":{
        "Id":20,"LoginName":"209540c0-d2e0-11e4-bf72-00219bfd78f1","FirstName":"Eleri","LastName":"Bingham","EmailAddress":"eleri@childcomwales.org.uk","IPAddress":"0.0.0.0","CreatedAt":"2010-10-08T09:04:31-05:00","UpdatedAt":"2015-03-25T06:14:38-05:00"
      }
    },{
      "CreatedAt":"2006-07-17T14:18:18Z","UpdatedAt":"2015-03-25T11:14:43Z","SummaryDate":"2006-07-17T00:00:00Z","Id":2,"RecordId":"20060717/2","ReferralId":1,"CaseId":null,"SourceId":3,"MarketingSourceId":5,"StatusId":4,"PaperId":null,"AppUserId":12,"PriorityId":3,"Summary":"Mr Adrian Davies has called regarding his son Joshua who has been out of school for 10  months due to bullying. Joshua has had 0 tuition for 8 months and limited tuition over the last 2 months. Joshua has started having behavioural issues. There is a history of sex abuse (2001) that the father does not wish to be brought up as the children have moved on. Joshua was at St Cyres school initially. The father applied for J to go to Stanwell. He was kept waiting for 4 months for a decision and then told the school could not accommodate him. The family went to appeal and the decision was upheld. It seems that Joshua is OFF THE REGISTER. Recently J has gone back to his original school and is having 1 hour a week tuition at St CYres","IsOneOff":false,"ModifiedById":12,"ModifiedUser":{
        "Id":12,"LoginName":"20954011-d2e0-11e4-bf72-00219bfd78f1","FirstName":"John","LastName":"Harford","EmailAddress":"johnh@childcomwales.org.uk","IPAddress":"10.100.1.17","CreatedAt":"2010-10-08T09:04:31-05:00","UpdatedAt":"2015-03-25T06:14:38-05:00"
      }
    },{

**Comment by VikingsFan** [comment]
@jonjalberghini 
please try this uri: http://localhost:18832/Aas/Cases?$filter=ModifiedUser/FirstName eq 'Eleri'&$expand=ModifiedUser&$count=true

The ModifiedUser is not a list, so the filter is not working.

**Comment by jonjalberghini** [comment]
Thanks, That worked I understand. 
----- Original Message -----

**Comment by VikingsFan** [comment]
@jonjalberghini if the ModifiedUser is a list ,the filter in expand will work.
