### ISSUE TITLE
[Bug] Function Date doesn't work with Linq To Entity

### ISSUE THREAD

**Issue by katan4ig** [OData/WebApi#300]
Filter for example:
```
~/odata/Customers?$filter=date(Birthday) eq 2015-03-23
```
Field Birthday has type DateTimeOffset
After converting this function to Linq query, it looks as follows:
```
.Where($it => new Date($it.Birthday.Year, $it.Birthday.Month, $it.Birthday.Day) == 2015-03-23)
```
But Linq To Entity cannot convert this query to SQL, and throws next exception:
```
System.NotSupportedException: Only parameterless constructors and initializers are supported in LINQ to Entities
```
I use latest version Entity Framework(6.1.3) and Web Api Odata Libraries (6.11 and 5.5.1)

**Comment by VikingsFan** [comment]
time(DateTime) also doesn't work with same error

**Comment by xuzhg** [comment]
@katan4ig, would you please check my pull request works for your scenario?

**Comment by katan4ig** [comment]
@xuzhg, Thanks, your changes work fine.

**Comment by katan4ig** [comment]
@xuzhg I found that filter by "equal" doesn't work. 
For example:
~/odata/Customers?$filter=date(Birthday) eq 2015-03-23
If field Birthday contains Time in DB (2015-03-23 + Time), this filter returns 0 rows

**Comment by xuzhg** [comment]
@katan4ig 

date() function is to return the "Date" part of the DateTimeOffset, That's the year, month & day. While the "Date" part maybe different for the same DateTimeOffset in different TimeZone.
For example, for current implementation:

if: Birthday = 2015-03-23T01:02:03.004+8:00
then: date(Birthday ) =  2015-03-23

if: Birthday = Birhthday.ToUniversalTime;
then: date(Birthday ) =  2015-03-22

I don't know the type of "Birthday", Can you share me your sample codes? Thanks.

**Comment by xuzhg** [comment]
Checked in: 424764a

**Comment by xuzhg** [comment]
@katan4ig  please re-open or file a new issue if you have further concern.

**Comment by simoco** [comment]
Hello! Why this is not working
`~/odata/Customers?$filter=date(Birthday) eq 2015-03-23`

when Birthday is `DateTime` opposed to `DateTimeOffset`?
I got `No function signature for the function with name 'date' matches the specified arguments. The function signatures considered are: date(Edm.DateTimeOffset); date(Edm.DateTimeOffset Nullable=true).`. 
I'm using Microsoft.AspNet.OData ver 5.7.0. Thanks

**Comment by ShudderPig** [comment]
Hello, 
I have found the same Issue.
using `~/odata/Customers?$apply=filter(date(Birthday) eq 2015-03-23)`
seems to work, however
`~/odata/Customers?$filter=date(Birthday) eq 2015-03-23`
throws the same error as dmitryPavliv above.
`No function signature for the function with name 'date' matches the specified arguments. The function signatures considered are: date(Edm.DateTimeOffset); date(Edm.DateTimeOffset Nullable=true).`

sidenote: using` [EnableQuery(AllowedFunctions = AllowedFunctions.All)]` in the controller does not seem to fix this issue.
