### ISSUE TITLE
Swagger json generation for OData - compatible with Azure App Service

### ISSUE THREAD

**Issue by joshbooker** [OData/WebApi#302]
Azure App Service requires swagger metadata.  Swashbuckle is used in VS APIApp tooling to create the metadata using APIExplorer.  There are two problems preventing this from working in WebAPI OData projects:
1)  Odata Controller explicitly prevents APIExplorer
2)  Swashbuckle cannot handle routes and parameters for OData endpoints

Related issues:
https://github.com/OData/WebApi/issues/278
https://github.com/OData/ODataSamples/issues/13
https://github.com/OData/RESTier/issues/69

What is needed:
1) ability to shut off ignore APIExplorerSettings
2) swagger metadata builder tool, preferably customized swashbuckle swagger.config, to generate swagger metadata compatible with Azure APIApp.

Thanks for listening.

**Comment by congysu** [comment]
Need to support e.g.: `/odata/swagger.json`

**Comment by congysu** [comment]
Related issue: https://github.com/OData/odata.net/issues/129

**Comment by abkmr** [comment]
JSON metadata is also needed for Dynamics CRM

**Comment by joshbooker** [comment]
@TomDu,

I see from the latest PR #520 that swagger.json generation was added to WebAPIOdata...many thanks to OData team for that.

However, there is still a problem with the resulting swagger output in interoperability with Azure.  For example, AutoRest is a tool which generates client code from swagger.json and it requires OperationIDs on all operations.

https://github.com/Azure/autorest

The swagger being output from WebAPIOData is missing the required OperationIDs.

Not sure if this can be fixed before 5.8 release but it would be really swell if the resulting swagger was Azure compliant.

**Comment by xuzhg** [comment]
Added. Thanks.

**Comment by congysu** [comment]
operationId support is added in commit https://github.com/OData/WebApi/commit/d63e4e3e927754ecad45949d766a60cab6362704.
A pending work item is to ensure that the generated swagger.json passes swagger validation https://github.com/OData/lab/issues/25.
