### ISSUE TITLE
Support setting namespaces for operations in ODataConventionModelBuilder

### ISSUE THREAD

**Issue by vojtechvit** [OData/WebApi#304]
Right now the <code>ODataConventionModelBuilder</code> does not allow in any way to change the namespace of *individual* actions or functions from the "default" one to a custom one. This means that we have to use <code>EdmModel</code> instead, which is quite cumbersome. Please add this simple feature. We'd like to have namespaces for operations like [OneDrive API](https://api.onedrive.com/v1.0/$metadata).

**Comment by brjohnstmsft** [comment]
Agreed, this is a big pain point for us as well. Building the EdmModel directly is far more error-prone, but we have no choice because we need to set the namespace.

**Comment by VikingsFan** [comment]
Checked in 483ce56fa63b6950fd54f8a9119f866c2164468e

**Comment by vojtechvit** [comment]
Thanks guys!

**Comment by brjohnstmsft** [comment]
Thanks!
