### ISSUE TITLE
WebApi OData v3 OperationDescriptor returning different Title/Target URI depending on the format (ATOM vs JSON)

### ISSUE THREAD

**Issue by maboivin** [OData/WebApi#308]
I already asked this question/issue almost a week ago on StackOverflow and nobody seems to know the answer so far and I thought I'd ask the best guys to answer it. Here's the original link on SO http://stackoverflow.com/questions/29629758/webapi-odata-v3-operationdescriptor-returning-different-title-target-uri-dependi,

I'll copy the content here also:
Consider the following simple ASP.NET Web Api with OData v3.

MyEntity.cs

    public class MyEntity
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }

MyEntitiesController.cs

    public class MyEntitiesController : ODataController
    {
        public IEnumerable<MyEntity> Get()
        {
            return new MyEntity[] { new MyEntity() { Id = Guid.NewGuid(), Name = "Name" } };
        }

        [HttpPost]
        public string MyAction()
        {
            return "Hello World!";
        }
    }

WebApiConfig.cs

    public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            var modelBuilder = new ODataConventionModelBuilder();
            modelBuilder.Namespace = "MyNamespace";
            modelBuilder.ContainerName = "MyContainer";
            modelBuilder.EntitySet<MyEntity>("MyEntities");
            
            var action = modelBuilder.Entity<MyEntity>().Action("MyAction");
            action.Returns<string>();

            foreach (var structuralType in modelBuilder.StructuralTypes)
            {
                // Resets the namespace so that the service contains only 1 namespace.
                structuralType.GetType().GetProperty("Namespace").SetValue(structuralType, "MyNamespace");
            }

            var model = modelBuilder.GetEdmModel();
            config.Routes.MapODataServiceRoute("OData", "odata", model);
        }
    }

On the client side, I added a simple Service Reference.

Program.cs

    class Program
    {
        static void Main(string[] args)
        {
            var contextAtom = new MyContainer(new Uri("http://localhost:63939/odata/"));
            contextAtom.Format.UseAtom();
            var myEntityAtom = contextAtom.MyEntities.First();

            // Outputs: http://localhost:63939/odata/MyEntities(guid'2c2431cd-4afa-422b-805b-8398b9a29fec')/MyAction
            var uriAtom = contextAtom.GetEntityDescriptor(myEntityAtom).OperationDescriptors.First().Target;
            Console.WriteLine(uriAtom);
                
            // Works fine using ATOM format!
            var responseAtom = contextAtom.Execute<string>(uriAtom, "POST", true);

            var contextJson = new MyContainer(new Uri("http://localhost:63939/odata/"));
            contextJson.Format.UseJson();
            var myEntityJson = contextJson.MyEntities.First();

            // Outputs: http://localhost:63939/odata/MyEntities(guid'f31a8332-025b-4dc9-9bd1-27437ae7966a')/MyContainer.MyAction
            var uriJson = contextJson.GetEntityDescriptor(myEntityJson).OperationDescriptors.First().Target;
            Console.WriteLine(uriJson);

            // Throws an exception using the JSON uri in JSON format!
            var responseJson = contextJson.Execute<string>(uriJson, "POST", true);

            // Works fine using ATOM uri in JSON format!
            var responseJson2 = contextJson.Execute<string>(uriAtom, "POST", true);
        }
    }

My issue is that depending on the format used to query the entity, the operation descriptor title/target URI is different. The target URI coming from ATOM works fine, but the one coming from JSON always throws an exception.

**Instead of manually concatenating the URI, is there a way to have operation descriptors working when using both formats (ATOM and JSON)?** Am I missing something or it just doesn't work out of the box? Do I absolutely need to write a custom routing convention?

Note that I'm experiencing the same issue with OData v4, but getting MyNamespace.MyAction as the Title and Target URI instead of MyContainer.MyAction.

**Comment by lewischeng-ms** [comment]
A buggy V3 sample service related to this issue can be found in https://github.com/OData/ODataSamples/commit/ebf203b1eed4dfd21c7ea9bf5d85f3251f14e33e. Test with this project when the bug is fixed.
