### ISSUE TITLE
Add support for generating odata urls from razor views.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#31]
Context from this SO question,  
[ http://stackoverflow.com/questions/15488574/how-to-link-to-odata-collection-
in-razor-using-asp-net-mvc-web-api-odata
](http://stackoverflow.com/questions/15488574/how-to-link-to-odata-collection-
in-razor-using-asp-net-mvc-web-api-odata)  
## Work Item Details

**Original CodePlex Issue:**    [Issue 914](http://aspnetwebstack.codeplex.com/workitem/914)
**Status:** Active
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Mar 19, 2013 at 3:26 AM
**Reported by:**    raghuramn
**Updated on:** Jun 11, 2014 at 11:10 PM
**Updated by:** bplumlee_rtc

**Comment by LianwMS** [comment]
On *2013-03-30 05:31:32 UTC*, **HongmeiG** commented:

A simple extension method on the UrlHelper would do.

**Comment by LianwMS** [comment]
On *2013-04-04 03:28:15 UTC*, **HongmeiG** commented:

This new helper will require a new dll since we don't want to burn dependency on OData from razor or the other way around. So let us do it as a sample.

**Comment by LianwMS** [comment]
On *2013-09-24 02:39:07 UTC*, **danroth27** commented:

We have an ODataLink method on System.Web.Http.UrlHelper but we forgot to add one to the MVC System.Web.Mvc.UrlHelper. Till we add it, you can use this extension method,
namespace System.Web.Mvc
{
    public static class UrlHelperExtensions
    {
        private static IODataPathHandler _pathHandler = new DefaultODataPathHandler();

        public static string ODataUrl(this UrlHelper urlHelper, string routeName, params ODataPathSegment[] segments)
        {
            string odataPath = _pathHandler.Link(new ODataPath(segments));
            return urlHelper.HttpRouteUrl(
                routeName,
                new RouteValueDictionary() { { ODataRouteConstants.ODataPath, odataPath } });
        }
    }
}

and call it from your razor views by doing something like (assuming there is an entityset customers and you want to put the navigation link to orders on customers(42)),
@Url.ODataUrl("odata", new EntitySetPathSegment("customers"), new KeyValuePathSegment("42"), new NavigationPathSegment("orders"))

Make sure you have an @using System.Web.Http.OData.Routing directive in your razor view.

**Comment by joshmouch** [comment]
How does one use the above UrlExtension for a bound odata function?
For example, to get to the URL:
/odata/Entities/Namespace.SearchName(name='curb')

It seems that the BoundFunctionPathSegment constructor has an internal contructor that would work... but... it's internal (why's Microsoft always do this?).

This is what I envision I would need:
@Url.ODataUrl("odata", new EntitySetPathSegment("Entities"), new BoundFunctionPathSegment("SearchName", "curb"))
