### ISSUE TITLE
[WebApi] Can't ignore some query options like $skip

### ISSUE THREAD

**Issue by VikingsFan** [OData/WebApi#310]
Sample:

Call my odata service use this url: ~/people?$skip=10

but $top is to call other service in my controller, not a odata query option:

    [EnableQuery]
    public IQueryable<EnableQueryCustomer> Get()
    {
              myClient.GetAsync("~/people?$skip=10");
    }

the result will apply $skip twice by the service I called in controller and odata.

**Comment by congysu** [comment]
For example, in `ODataQueryOptions`, a query option, e.g., `SkipQueryOption` could have a flag, e.g., `Applied`, when `Applied == true`, `EnableQuery` does not need to apply the query option again.

**Comment by xuzhg** [comment]
Merged the PR. Thanks.
