### ISSUE TITLE
Can OData API controller does "expand" the item by default without specifying $expand

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#311]
e.g., in the model builder, allow specify whether a navigation property is by default expanded.  In `ODataQueryOptions`, build `SelectExpandQueryOption` from `ODataQueryContext Context`, if `RawValues.Expand` is `null`, and the `Context` contains a default expanded nav prop:
```c#
private void BuildQueryOptions(IDictionary<string, string> queryParameters)
{
    ...
    if (RawValues.Select != null || RawValues.Expand != null)
    {
        SelectExpand = new SelectExpandQueryOption(RawValues.Select, RawValues.Expand,
            Context, _queryOptionParser);
    }
    ...
```

**Comment by VikingsFan** [comment]
Checked in d21a410fb1b36b9455796dd18d5bbdcf10c2f5ad
