### ISSUE TITLE
[Feature] Add Stream Support to WebApi

### ISSUE THREAD

**Issue by liqian19891011** [OData/WebApi#328]
Add contents for Stream support in OData V4 on odata.github.io/WebApi.

We have related questions on [StackOverflow](http://stackoverflow.com/questions/30043442/stream-support-in-odata-v4)

**Comment by congysu** [comment]
Consider to support named stream (aka stream property) or media link entry (i.e., media entry)
If named stream, we need to change OData entry serializer.
```c#
public class CustomODataEntityTypeSerializer : ODataEntityTypeSerializer
{
    public CustomODataEntityTypeSerializer(IEdmEntityTypeReference entityType, ODataSerializerProvider serializerProvider)
        : base(entityType, serializerProvider)
    {
    }

    public override ODataProperty CreateStructuralProperty(IEdmStructuralProperty structuralProperty, object entityInstance, ODataSerializerContext writeContext)
    {
        if (structuralProperty.Type.IsStream())
        {
            return new ODataProperty { Name = structuralProperty.Name, Value = new ODataStreamReferenceValue { ReadLink = new Uri("http://image") } };
        }

        return base.CreateStructuralProperty(structuralProperty, entityInstance, writeContext);
    }
}
```

If media link entry, we need to create an entity type with HasStream set to true in OData v4.  E.g., use this ctor:
```c#
public EdmEntityType(string namespaceName, string name, IEdmEntityType baseType, bool isAbstract, bool isOpen, bool hasStream);
```
The change is in model builder.

**Comment by sammym1982** [comment]
thanks @congysu  Is this issue accepted for next release of libraries? 

For interim do you have any suggestion on how we can go ahead and add the stream support.

**Comment by congysu** [comment]
@sammym1982 The related issue is https://github.com/OData/WebApi/issues/149.  Can start from a blog: http://blogs.msdn.com/b/mrtechnocal/archive/2013/12/31/10462258.aspx, although it is for OData v3 Web API.

**Comment by sammym1982** [comment]
@congysu 

I do tried porting that code to V4 but the issue as I mentioned in my original post on stackoverflow is there is currently no way available to mark an entity as HasStream = true. The original IEdmModel.SetHasDefaultStream  seems like no longer available. 

Model we have is as followos:

Entity: Incident
NavigationProperties Collection: Attachments

Therefore We want all our attachment posts to happen as below:

POST: http://foo.com/incidents(1L)/Attachments

**Comment by VikingsFan** [comment]
@sammym1982 I have a pr #379 , expose the HasStream Property, which is helpful to your customize, would you help to review?

**Comment by congysu** [comment]
We shall port the sample http://blogs.msdn.com/b/mrtechnocal/archive/2013/12/31/10462258.aspx to v4.

**Comment by raffaeu** [comment]
Guys any news on this.
We are working with OData v 4.0 and now we are completely stuck, which is very disappointing.
Can you implement in the model builder this extension and release a fixture over Nuget ASAP?

**Comment by ivanko2000** [comment]
Pinging this as 'still relevant' in case anyone is listening... :)

**Comment by lthib** [comment]
Like @ivanko2000, this recently became relevant to my interests as well.

**Comment by GerdN67** [comment]
We also have OData Services V4 running, and cannot integrate former streaming. Waiting for the implementation of streaming support in OData V4, please implement ASAP

**Comment by kevinciq** [comment]
I'm not sure if this is what they're after, but I do have streams working in my code: https://stackoverflow.com/a/48851615

**Comment by biaol-odata** [comment]
@madansr7 please prioritize.

**Comment by TehWardy** [comment]
Any intention to release this yet ?
We are in year 4 since this was raised after all.

**Comment by Discjoggy** [comment]
Would be very glad to hear if this issue will be fixed or not.

**Comment by habbes** [comment]
Closed since it appears the issue was addressed by the linked PR. If the issue still exists in the latest versions of the library, kindly open a new issue.
