### ISSUE TITLE
Time zone conversions are not DST aware

### ISSUE THREAD

**Issue by mj1856** [OData/WebApi#334]
In [`OData.Formatter.EdmPrimitiveHelpers.ConvertPrimitiveValue`](https://github.com/OData/WebApi/blob/bad3b8cbec3af117903dcdd2748b1626f9f88c5c/OData/src/System.Web.OData/OData/Formatter/EdmPrimitiveHelpers.cs#L87) and [`OData.Formatter.Serialization.ODataPrimitiveSerializer.ConvertUnsupportedPrimitives`](https://github.com/OData/WebApi/blob/bad3b8cbec3af117903dcdd2748b1626f9f88c5c/OData/src/System.Web.OData/OData/Formatter/Serialization/ODataPrimitiveSerializer.cs#L148-L154), values are being incorrectly converted to a time zone using the time zone's `BaseUtcOffset`.

This essentially ignores all daylight saving time rules contained within the `TimeZoneInfo` object, and assumes that the time zone is in a single fixed offset for all values - which is not correct.  (See "Time Zone != Offset in [the timezone tag wiki on StackOverflow](http://stackoverflow.com/tags/timezone/info).)

The same mistake is repeated throughout many of the unit tests.  The tests also have a lot of noisy conversions back and forth between UTC and local time, many of which are unnecessary.

**Comment by xuzhg** [comment]
Merged the PR. Thanks.
