### ISSUE TITLE
Add support for Spatial Data types in OData

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#34]
Currently, there is no support for spatial data types in Web API OData.
Consider adding support for this as it makes impossible to develop any service
that has to deal with spatial data.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1010](http://aspnetwebstack.codeplex.com/workitem/1010)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Apr 25, 2013 at 10:00 PM
**Reported by:**	jacalvar
**Updated on:**	Nov 24, 2014 at 10:41 AM
**Updated by:**	jyparask

**Comment by LianwMS** [comment]
On *2013-05-02 04:25:39 UTC*, **yishaigalatzer** commented:

We will prioritize this against other feature work for RTM. For now assigning to be developed in RTM

**Comment by LianwMS** [comment]
On *2014-07-28 23:54:56 UTC*, **TimMc** commented:

Please fix this!

**Comment by congysu** [comment]
Related issue: #434

**Comment by nirinchev** [comment]
I've written a [blog post](https://medium.com/@nirinchev/dealing-with-spatial-data-in-odata-4e4051434ddb) that proposes a workaround for working with spatial data in Web API OData. Unfortunately, it requires slight modifications to ```ClrCanonicalFunctions``` and ```FilterBinder``` to add support for spatial queries (```geo.distance``` and so on). Do you think it would be reasonable change to push upstream? I'd be happy to send a PR for that.

**Comment by xuzhg** [comment]
@nirinchev

Warmly welcome your PR for spatial support.

Best Regards.
Sam Xu

**Comment by xuzhg** [comment]
See the commit: 7916898fd45ccf7ce73c87b0c9d3c831274f6527

Please re-open it if you have further concern.
