### ISSUE TITLE
Correct url usage to expand child of a child and also filter the middle child.

### ISSUE THREAD

**Issue by jonjalberghini** [OData/WebApi#348]
This url works fine bt is this the correct way to call it?
version Microsoft.AspNet.OData.5.6.0-beta1-150428-Nightly 
http://localhost:18832/Aas/Cases?&$filter=(SummaryDate ge 2012-08-09T00:00:00+02:00 and ModifiedById eq 114)&$expand=Schools,Activities($expand=ActivityAppUser),Activities($filter=Reminder ne null and IsComplete eq null)

see the 2 Activities entries? This works perfect just not sure if this is the correct approach.

Thanks

**Comment by jonjalberghini** [comment]
Please note ActivityAppUser is a set not one to one.

**Comment by LianwMS** [comment]
Activities($expand=ActivityAppUser & $filter=Reminder ne null and IsComplete eq null) is more clearly, but our ODL lib also support if you separate them

**Comment by jonjalberghini** [comment]
This doesn't work.
http://localhost:18832/Aas/Cases?&$filter=(SummaryDate ge 2012-08-09T00:00:00Z and ModifiedById eq 114)&$expand=Schools,Activities($expand=ActivityAppUser & $filter=Reminder ne null and IsComplete eq null)

Error
{"message":"The controller for path \u0027/Aas/Cases\u0027 was not found or does not implement IController."}

function should call
	[ODataRoutePrefix("Cases")]
	public class CasesController : BaseControllers.BaseController
	{

		[HttpGet]
		[ODataRoute]
		[EnableQuery]
		public IHttpActionResult Get()
		{
			return Ok(_db.Cases.AsQueryable());
		}
}

But this works
http://localhost:18832/Aas/Cases?&$filter=(SummaryDate ge 2012-08-09T00:00:00Z and ModifiedById eq 114)&$expand=Schools,Activities($expand=ActivityAppUser),Activities($filter=Reminder ne null and IsComplete eq null)

Any help would be appreciated.

Jon

**Comment by snebjorn** [comment]
Your query is incorrect. When you need multiple statements inside nested statements ie. $expand=foo(...) you use ; instead of & to add them.

This should work:
````html
Activities($expand=ActivityAppUser;$filter=Reminder ne null and IsComplete eq null)
````

Can't remember where I found it. But it was well hidden!

**Comment by jonjalberghini** [comment]
Thanks so much! Someone told me & and they are the one writing the software. Thats scary.

**Comment by jonjalberghini** [comment]
Thank you it works perfect they should really add that to the documentation

**Comment by LianwMS** [comment]
@jonjalberghini Sorry that the I make the mistake in response.
