### ISSUE TITLE
$expand contain $count don't work

### ISSUE THREAD

**Issue by CarefreeXT** [OData/WebApi#349]
Hi:
I use System.Web.OData[5.5.1.0]
http://localhost:3391/Suppliers?$count=true
http://localhost:3391/Suppliers?$count=true&$expand=Products
this url is OK.

But the url "$expand" contain "$count" can't work
For example: http://localhost:3391/Suppliers?$count=true&$expand=Products($count=true)

The [Products] property has't count.

**Comment by xuzhg** [comment]
Should work as commit 7255614 . Thanks.
