### ISSUE TITLE
[OData] Add support for nested paging.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#35]
Now that we have $expand support, we should add support for server-driven
paging for expanded feeds.  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1016](http://aspnetwebstack.codeplex.com/workitem/1016)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Apr 28, 2013 at 9:06 AM
**Reported by:**    raghuramn
**Updated on:** Dec 3, 2014 at 4:05 AM
**Updated by:** jorgeaguirre1

**Comment by LianwMS** [comment]
On *2013-05-03 06:28:21 UTC*, **eilonlipton** commented:

We should add support for the paging links only for OData. Support for JSON isn't needed now.

**Comment by LianwMS** [comment]
On *2013-09-24 02:57:06 UTC*, **danroth27** commented:

Parity with WCF DS. We should allow the page size to be set on the entity set in the model.

**Comment by LianwMS** [comment]
On *2013-09-27 11:30:28 UTC*, **ZackYang** commented:

We should config it at client-side.

**Comment by MrTomWhite** [comment]
@LianwMS: What is the status of this work item? I don't see it assigned to any milestones, so I take it that this isn't planned to be implemented int he short term? 

What would one need to do to implement this feature + What are the relevant pieces of code that should be changed to support this?

**Comment by gel** [comment]
Extremely important feature IMO. Additional queries can't scale.
