### ISSUE TITLE
Update project site in nuget packages to http://odata.github.io/.

### ISSUE THREAD

**Issue by LaylaLiu** [OData/WebApi#352]

**Comment by xuzhg** [comment]
Updated.

Please review:
https://odatateam.visualstudio.com/DefaultCollection/_git/webapitooling/commit/aefcb59f8c0ba88320f49a7ebe9fc50dbc7eddc2

**Comment by xuzhg** [comment]
See: https://www.nuget.org/packages/Microsoft.AspNet.OData/
