### ISSUE TITLE
Installing Web API OData V4 Prerelease 5.6.0-RC

### ISSUE THREAD

**Issue by kindermansx** [OData/WebApi#358]
Hi,

I updated to Web Api 2.2 for OData 4 5.6RC to test if the datetime issue would now work. After nuget update the API referenced version of System.Web.OData is incorrect. After update it references 5.5.0 and the api returns errors stating that it cannot find system.web.odata.dll. 

For testing purposes I manually changed the ref to System.Web.OData.dll 5.5.1 and it worked. 

Is this a issue in the package or with my solution?

Thanks, Xavier

**Comment by LianwMS** [comment]
Thanks Xavier, we will publish rc2 ASAP to fix the issue

**Comment by LianwMS** [comment]
@kindermansx Just updated, please confirm
