### ISSUE TITLE
Order by Datetime in v5.6RC still not working

### ISSUE THREAD

**Issue by kindermansx** [OData/WebApi#359]
Hi,

I updated to OData 4 prerelease but the issue of ordering by a datetime field is still there. 

We use EF 6.1.3 to get data from db.

Am I perhaps doing someting wrong in the API?

Thanks, Xavier

Request (Modified is DateTime):
GET http://localhost:54142/odata/testrequests?$orderby=Modified HTTP/1.1
User-Agent: Fiddler
Host: localhost:54142
Content-Type: application/json

Response:
HTTP/1.1 500 Internal Server Error
Cache-Control: private
Content-Type: application/json; odata.metadata=minimal
Server: Microsoft-IIS/8.0
OData-Version: 4.0
X-AspNet-Version: 4.0.30319
X-SourceFiles: =?UTF-8?B?QzpcQ29kZVxpbmZvZmx1eC52aXN1YWxzdHVkaW8uY29tXEZsdXhMYWJcSW5mb0ZsdXguUmVmQXJjaFxJbmZvRmx1eC5SZWZBcmNoLk9EYXRhQXBpXG9kYXRhXHRlc3RyZXF1ZXN0cw==?=
X-Powered-By: ASP.NET
Date: Sun, 24 May 2015 08:20:11 GMT
Content-Length: 5804

{
  "error":{
    "code":"","message":"An error has occurred.","innererror":{
      "message":"The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; odata.metadata=minimal'.","type":"System.InvalidOperationException","stacktrace":"","internalexception":{
        "message":"The specified type member 'Kind' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported.","type":"System.NotSupportedException","stacktrace":"   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberAccessTranslator.TypedTranslate(ExpressionConverter parent, MemberExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.EqualsTranslator.TypedTranslate(ExpressionConverter parent, BinaryExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.BinaryTranslator.TypedTranslate(ExpressionConverter parent, BinaryExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.ConditionalTranslator.TypedTranslate(ExpressionConverter parent, ConditionalExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input, DbExpressionBinding& binding)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, DbExpression& source, DbExpressionBinding& sourceBinding, DbExpression& lambda)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SequenceMethodTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, SequenceMethod sequenceMethod)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.Convert()\r\n   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()\r\n   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()\r\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()\r\n   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()\r\n   at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteFeed(IEnumerable enumerable, IEdmTypeReference feedType, ODataWriter writer, ODataSerializerContext writeContext)\r\n   at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)\r\n   at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)\r\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders)\r\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()"
      }
    }
  }
}

**Comment by jonjalberghini** [comment]
I cannot tell from this, but it does work with mssql EF / and mysql EF 6.1.3 and Microsoft.AspNet.OData.5.6.0-rc-150521-Nightly 

Send the result of your $metadata url and the class and controller get fiunction definitions. 

Jon 

----- Original Message -----

**Comment by jonjalberghini** [comment]
Even though the docs say it work only the 5.6 rc work with dates and datetimes. 


----- Original Message -----

**Comment by kindermansx** [comment]
Jon, metadata doc;
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/xml
Expires: -1
Server: Microsoft-IIS/8.0
OData-Version: 4.0
X-AspNet-Version: 4.0.30319
X-SourceFiles: =?UTF-8?B?QzpcQ29kZVxpbmZvZmx1eC52aXN1YWxzdHVkaW8uY29tXEZsdXhMYWJcSW5mb0ZsdXguUmVmQXJjaFxJbmZvRmx1eC5SZWZBcmNoLk9EYXRhQXBpXG9kYXRhXCRtZXRhZGF0YQ==?=
X-Powered-By: ASP.NET
Date: Mon, 25 May 2015 05:31:07 GMT
Content-Length: 14732

<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:DataServices>
    <Schema Namespace="InfoFlux.RefArch.Model" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="Company">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="Name" Type="Edm.String" Nullable="false" />
        <Property Name="Street" Type="Edm.String" Nullable="false" />
        <Property Name="City" Type="Edm.String" Nullable="false" />
        <Property Name="EMail" Type="Edm.String" Nullable="false" />
        <Property Name="About" Type="Edm.String" />
        <Property Name="CountryId" Type="Edm.Int32" />
        <Property Name="BillingDetailId" Type="Edm.Int32" />
        <Property Name="CreatedById" Type="Edm.String" />
        <Property Name="ModifiedById" Type="Edm.String" />
        <Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" />
        <Property Name="Modified" Type="Edm.DateTimeOffset" Nullable="false" />
        <NavigationProperty Name="Country" Type="InfoFlux.RefArch.Model.Country">
          <ReferentialConstraint Property="CountryId" ReferencedProperty="Id" />
        </NavigationProperty>
        <NavigationProperty Name="Contacts" Type="Collection(InfoFlux.RefArch.Model.Contact)" />
        <NavigationProperty Name="BillingInfo" Type="InfoFlux.RefArch.Model.BillingDetail" />
      </EntityType>
      <EntityType Name="Contact">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="FirstName" Type="Edm.String" />
        <Property Name="LastName" Type="Edm.String" />
        <Property Name="EMail" Type="Edm.String" />
        <Property Name="JobTitle" Type="Edm.String" />
        <Property Name="Age" Type="Edm.Int32" Nullable="false" />
        <Property Name="Gender" Type="InfoFlux.RefArch.Model.Gender" Nullable="false" />
        <Property Name="CompanyId" Type="Edm.Int32" />
        <Property Name="CreatedById" Type="Edm.String" />
        <Property Name="ModifiedById" Type="Edm.String" />
        <Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" />
        <Property Name="Modified" Type="Edm.DateTimeOffset" Nullable="false" />
        <NavigationProperty Name="Company" Type="InfoFlux.RefArch.Model.Company">
          <ReferentialConstraint Property="CompanyId" ReferencedProperty="Id" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name="Country">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="Name" Type="Edm.String" Nullable="false" />
        <Property Name="Code" Type="Edm.String" Nullable="false" />
        <Property Name="ContinentId" Type="Edm.Int32" Nullable="false" />
        <Property Name="Continent" Type="Edm.String" />
      </EntityType>
      <EntityType Name="Supplier">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="Name" Type="Edm.String" />
        <Property Name="CreatedById" Type="Edm.String" />
        <Property Name="ModifiedById" Type="Edm.String" />
        <Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" />
        <Property Name="Modified" Type="Edm.DateTimeOffset" Nullable="false" />
        <NavigationProperty Name="Products" Type="Collection(InfoFlux.RefArch.Model.Product)" />
      </EntityType>
      <EntityType Name="ProductCategory">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="Name" Type="Edm.String" Nullable="false" />
        <Property Name="Description" Type="Edm.String" />
        <Property Name="CreatedById" Type="Edm.String" />
        <Property Name="ModifiedById" Type="Edm.String" />
        <Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" />
        <Property Name="Modified" Type="Edm.DateTimeOffset" Nullable="false" />
      </EntityType>
      <EntityType Name="Product">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="Name" Type="Edm.String" />
        <Property Name="StandardCost" Type="Edm.Decimal" Nullable="false" />
        <Property Name="ListPrice" Type="Edm.Decimal" Nullable="false" />
        <Property Name="ProductNumber" Type="Edm.String" Nullable="false" />
        <Property Name="MakeFlag" Type="Edm.Boolean" Nullable="false" />
        <Property Name="FinishedGoodsFlag" Type="Edm.Boolean" Nullable="false" />
        <Property Name="ProductCategoryId" Type="Edm.Int32" />
        <Property Name="SupplierId" Type="Edm.Int32" />
        <Property Name="CreatedById" Type="Edm.String" />
        <Property Name="ModifiedById" Type="Edm.String" />
        <Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" />
        <Property Name="Modified" Type="Edm.DateTimeOffset" Nullable="false" />
        <NavigationProperty Name="Supplier" Type="InfoFlux.RefArch.Model.Supplier" />
        <NavigationProperty Name="ProductCategory" Type="InfoFlux.RefArch.Model.ProductCategory">
          <ReferentialConstraint Property="ProductCategoryId" ReferencedProperty="Id" />
        </NavigationProperty>
        <NavigationProperty Name="ProductRatings" Type="Collection(InfoFlux.RefArch.Model.ProductRating)" />
        <NavigationProperty Name="ProductPictures" Type="Collection(InfoFlux.RefArch.Model.ProductPictures)" />
        <NavigationProperty Name="Pictures" Type="Collection(InfoFlux.RefArch.Model.Picture)" ContainsTarget="true" />
      </EntityType>
      <EntityType Name="TestRequest">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="Name" Type="Edm.String" />
        <Property Name="Status" Type="Edm.Int32" Nullable="false" />
        <Property Name="CreatedById" Type="Edm.String" />
        <Property Name="ModifiedById" Type="Edm.String" />
        <Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" />
        <Property Name="Modified" Type="Edm.DateTimeOffset" Nullable="false" />
        <NavigationProperty Name="Tests" Type="Collection(InfoFlux.RefArch.Model.Test)" />
      </EntityType>
      <EntityType Name="Test" Abstract="true">
        <Key>
          <PropertyRef Name="TestId" />
        </Key>
        <Property Name="TestId" Type="Edm.Int32" Nullable="false" />
        <Property Name="Status" Type="Edm.Int32" Nullable="false" />
        <Property Name="Outcome" Type="Edm.Int32" Nullable="false" />
        <Property Name="ProductId" Type="Edm.Int32" />
        <Property Name="TestRequestId" Type="Edm.Int32" Nullable="false" />
        <Property Name="CreatedById" Type="Edm.String" />
        <Property Name="ModifiedById" Type="Edm.String" />
        <Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" />
        <Property Name="Modified" Type="Edm.DateTimeOffset" Nullable="false" />
        <NavigationProperty Name="Product" Type="InfoFlux.RefArch.Model.Product">
          <ReferentialConstraint Property="ProductId" ReferencedProperty="Id" />
        </NavigationProperty>
      </EntityType>
      <ComplexType Name="Shape" Abstract="true">
        <Property Name="HasBorder" Type="Edm.Boolean" Nullable="false" />
        <Property Name="Color" Type="InfoFlux.RefArch.Model.Color" Nullable="false" />
      </ComplexType>
      <EntityType Name="Window">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="Title" Type="Edm.String" />
        <Property Name="Shape" Type="InfoFlux.RefArch.Model.Shape" />
        <Property Name="InnerShapes" Type="Collection(InfoFlux.RefArch.Model.Shape)" />
      </EntityType>
      <EntityType Name="BillingDetail" Abstract="true">
        <Key>
          <PropertyRef Name="BillingDetailId" />
        </Key>
        <Property Name="BillingDetailId" Type="Edm.Int32" Nullable="false" />
        <Property Name="Owner" Type="Edm.String" />
        <Property Name="Number" Type="Edm.String" />
      </EntityType>
      <EntityType Name="BankAccount" BaseType="InfoFlux.RefArch.Model.BillingDetail">
        <Property Name="BankName" Type="Edm.String" />
        <Property Name="Swift" Type="Edm.String" />
      </EntityType>
      <EntityType Name="CreditCard" BaseType="InfoFlux.RefArch.Model.BillingDetail">
        <Property Name="CardType" Type="Edm.Int32" Nullable="false" />
        <Property Name="ExpiryMonth" Type="Edm.String" />
        <Property Name="ExpiryYear" Type="Edm.String" />
      </EntityType>
      <EntityType Name="ProductRating">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="Rating" Type="Edm.Int32" />
        <Property Name="ProductID" Type="Edm.Int32" Nullable="false" />
        <NavigationProperty Name="Product" Type="InfoFlux.RefArch.Model.Product" />
      </EntityType>
      <EntityType Name="ProductPictures">
        <Key>
          <PropertyRef Name="ProductPictureId" />
        </Key>
        <Property Name="ProductPictureId" Type="Edm.Int32" Nullable="false" />
        <Property Name="ProductId" Type="Edm.Int32" Nullable="false" />
        <Property Name="PictureId" Type="Edm.Int32" />
        <NavigationProperty Name="Picture" Type="InfoFlux.RefArch.Model.Picture">
          <ReferentialConstraint Property="PictureId" ReferencedProperty="PictureId" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name="Picture">
        <Key>
          <PropertyRef Name="PictureId" />
        </Key>
        <Property Name="PictureId" Type="Edm.Int32" Nullable="false" />
        <Property Name="FileName" Type="Edm.String" />
      </EntityType>
      <EntityType Name="ApplicationTest" BaseType="InfoFlux.RefArch.Model.Test">
        <Property Name="Os" Type="Edm.String" />
      </EntityType>
      <EntityType Name="PerformanceTest" BaseType="InfoFlux.RefArch.Model.Test">
        <Property Name="Speed" Type="Edm.Double" Nullable="false" />
        <Property Name="BatteryDurationHours" Type="Edm.Int32" Nullable="false" />
      </EntityType>
      <ComplexType Name="Rectangle" BaseType="InfoFlux.RefArch.Model.Shape">
        <Property Name="P1" Type="InfoFlux.RefArch.Model.Point" />
        <Property Name="P2" Type="InfoFlux.RefArch.Model.Point" />
        <Property Name="P3" Type="InfoFlux.RefArch.Model.Point" />
      </ComplexType>
      <ComplexType Name="Point">
        <Property Name="X" Type="Edm.Int32" Nullable="false" />
        <Property Name="Y" Type="Edm.Int32" Nullable="false" />
      </ComplexType>
      <ComplexType Name="Circle" BaseType="InfoFlux.RefArch.Model.Shape">
        <Property Name="Center" Type="InfoFlux.RefArch.Model.Point" />
        <Property Name="Radius" Type="Edm.Int32" Nullable="false" />
      </ComplexType>
      <EnumType Name="Gender">
        <Member Name="Male" Value="0" />
        <Member Name="Female" Value="1" />
      </EnumType>
      <EnumType Name="Color">
        <Member Name="Red" Value="0" />
        <Member Name="Blue" Value="1" />
        <Member Name="Green" Value="2" />
        <Member Name="Yellow" Value="3" />
      </EnumType>
    </Schema>
    <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <Action Name="addproducts" IsBound="true">
        <Parameter Name="bindingParameter" Type="InfoFlux.RefArch.Model.Supplier" />
        <Parameter Name="products" Type="Collection(InfoFlux.RefArch.Model.Product)" />
        <ReturnType Type="Collection(Edm.Int32)" Nullable="false" />
      </Action>
      <Action Name="rate" IsBound="true">
        <Parameter Name="bindingParameter" Type="InfoFlux.RefArch.Model.Product" />
        <Parameter Name="rating" Type="Edm.Int32" Nullable="false" />
      </Action>
      <Function Name="gettopratedproducts" IsBound="true">
        <Parameter Name="bindingParameter" Type="Collection(InfoFlux.RefArch.Model.Product)" />
        <Parameter Name="take" Type="Edm.Int32" Nullable="false" />
        <ReturnType Type="Collection(InfoFlux.RefArch.Model.Product)" />
      </Function>
      <Function Name="setrating" IsBound="true">
        <Parameter Name="bindingParameter" Type="InfoFlux.RefArch.Model.Product" />
        <Parameter Name="rating" Type="Edm.Int32" Nullable="false" />
        <ReturnType Type="InfoFlux.RefArch.Model.Product" />
      </Function>
      <EntityContainer Name="Container">
        <EntitySet Name="companies" EntityType="InfoFlux.RefArch.Model.Company">
          <NavigationPropertyBinding Path="Country" Target="countries" />
          <NavigationPropertyBinding Path="Contacts" Target="contacts" />
        </EntitySet>
        <EntitySet Name="contacts" EntityType="InfoFlux.RefArch.Model.Contact">
          <NavigationPropertyBinding Path="Company" Target="companies" />
        </EntitySet>
        <EntitySet Name="countries" EntityType="InfoFlux.RefArch.Model.Country" />
        <EntitySet Name="suppliers" EntityType="InfoFlux.RefArch.Model.Supplier">
          <NavigationPropertyBinding Path="Products" Target="products" />
        </EntitySet>
        <EntitySet Name="productcategories" EntityType="InfoFlux.RefArch.Model.ProductCategory" />
        <EntitySet Name="products" EntityType="InfoFlux.RefArch.Model.Product">
          <NavigationPropertyBinding Path="Supplier" Target="suppliers" />
          <NavigationPropertyBinding Path="ProductCategory" Target="productcategories" />
        </EntitySet>
        <EntitySet Name="testrequests" EntityType="InfoFlux.RefArch.Model.TestRequest">
          <NavigationPropertyBinding Path="Tests" Target="tests" />
        </EntitySet>
        <EntitySet Name="tests" EntityType="InfoFlux.RefArch.Model.Test">
          <NavigationPropertyBinding Path="Product" Target="products" />
        </EntitySet>
        <EntitySet Name="Windows" EntityType="InfoFlux.RefArch.Model.Window" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>

**Comment by kindermansx** [comment]
Jon

Quick update. Just to make sure my project might be causing the problem I started a new project referencing the nightly build and it seems to work now! 

Taking a closer look at my original project I notice that updating the OData package caused my refs to be all mangled up. After update System.Web.OData is version 5.6 (which is correct) but the api throws exceptions when I call an endpoint complaining that it cannot find v5.5.1. I'll investigate further and get back.

Thanks, Xavier

**Comment by xuzhg** [comment]
Thanks @jonjalberghini. 

@kindermansx, Appreciate your feedback and look forward your investigation. Thanks all to improve the Web API OData usability.

**Comment by xuzhg** [comment]
Please re-open it if you have further concern. Thanks.
