### ISSUE TITLE
EnableUnqualifiedNameCall(true) has no effect?

### ISSUE THREAD

**Issue by Casimodo72** [OData/WebApi#360]
Hi,
when I enable the "unqualified function and name call" option with EnableUnqualifiedNameCall and omit the namespace of a function in the URL then the OData uri parser throws an exception. So I wonder if this option is not implemented correctly or if I'm not understanding the purpose of it.

Scenario:
```c#
// We don't want to qualify enums and function calls with namespaces.
config.EnableEnumPrefixFree(true);
config.EnableUnqualifiedNameCall(true);

ODataModelBuilder builder = new ODataConventionModelBuilder();
builder.Namespace = "Ga";
builder.ContainerName = "Default";
var entity = builder.EntitySet<Person>("People").EntityType;
var func = entity.Collection
	.Function("DoIt")
	.ReturnsCollectionFromEntitySet<Person>("People");

// The Controller
namespace Ga.Web.ODataServices
{
    [ODataRoutePrefix("People")]
    public partial class PeopleController : ODataController
    {
        PeopleRepository _db = new PeopleRepository();

        [HttpGet]
        [EnableQuery(PageSize = 20, AllowedQueryOptions = AllowedQueryOptions.All)]
        [ODataRoute("Ga.DoIt()")]
        public System.Web.Http.IHttpActionResult DoIt()
        {
            return Ok(_db.Query());
        }
```
This request works fine:
GET http://localhost:26162/odata/People/Ga.DoIt() HTTP/1.1

This one not (note the omitted function namespace):
GET http://localhost:26162/odata/People/DoIt() HTTP/1.1

Exception:
```
Microsoft.OData.Core.ODataException

"Der Anforderungs-URI ist ungültig. Da das Segment 'People' auf eine Auflistung verweist, muss es das letzte Segment im Anforderungs-URI sein oder von einer Funktion oder Aktion gefolgt werden, die daran gebunden werden kann. Andernfalls müssen alle Zwischensegmente auf eine einzelne Ressource verweisen."

bei Microsoft.OData.Core.UriParser.Parsers.ODataPathParser.CheckSingleResult(Boolean isSingleResult, String identifier)
   bei Microsoft.OData.Core.UriParser.Parsers.ODataPathParser.CreateNextSegment(String text)
   bei Microsoft.OData.Core.UriParser.Parsers.ODataPathParser.ParsePath(ICollection`1 segments)
   bei Microsoft.OData.Core.UriParser.Parsers.ODataPathFactory.BindPath(ICollection`1 segments, ODataUriParserConfiguration configuration)
   bei Microsoft.OData.Core.UriParser.ODataUriParser.ParsePathImplementation()
   bei Microsoft.OData.Core.UriParser.ODataUriParser.Initialize()
   bei Microsoft.OData.Core.UriParser.ODataUriParser.ParsePath()
   bei System.Web.OData.Routing.DefaultODataPathHandler.Parse(IEdmModel model, String serviceRoot, String odataPath, ODataUriResolverSetttings resolverSettings, Boolean enableUriTemplateParsing) in c:\Dev\Lib\WebApi-OData\OData\src\System.Web.OData\OData\Routing\DefaultODataPathHandler.cs:Zeile 137.
```

Can someone clarify?

Best regards,
Kasimier Buchcik

**Comment by xuzhg** [comment]
@Kasimier

What Web API OData version did you refer to?

Before Web API OData V5.6, Unqualified name call doesn't wok on attribute routing. You can refer to: #280.

I think update to [Web API OData V5.6](http://www.nuget.org/packages/Microsoft.AspNet.OData/5.6.0-rc2) can resolve your problem.

And I create a simple project to verify it. You can refer to it [here](https://github.com/xuzhg/WebApiSample/tree/master/UnqualifiedNameCall).

Thanks your feedback and welcome any further questions and concerns.

**Comment by Casimodo72** [comment]
@xuzhg,
I'm using the master branch of Web API OData and ODataLib.
I took the time and debugged my app using the ODataLib sources. It turned out to be an ODataLib issue related to open types. I.e. using EnableUnqualifiedNameCall(true) on open types has no effect. Is this a bug in ODataLib or does the spec mandate this?

In your example, change the type to the following, making it an open type. The error will then show up.
```c#
public class Person
{
        public int Id { get; set; }
        public IDictionary<string, object> DynamicProperties { get; set; }
}
```
You'll find the relevant code following this path:
```
`ODataUriParser.ParsePath:
  -> ODataUriParser.Initialize:
         -> ODataUriParser.ParsePathImplementation:
                // fullUri: "http://localhost:7895/odata/People/DoIt()"
	      -> ODataPathFactory.BindPath:
	             // Resolver: System.Web.OData.UnqualifiedCallAndEnumPrefixFreeResolver
		     // Only the model is different
		     -> semanticPathParser.ParsePath(segments)
		            -> CreateNextSegment(segmentText)
			           -> TryCreateSegmentForOperation
	                                  // Difference: returns false for me
                                          -> TryBindingParametersAndMatchingOperation
                                               // Difference: returns false for me
						-> FunctionOverloadResolver.ResolveOperationFromList
                                                    // Comment: "If the previous segment is an open type, the service action name is required to be fully qualified"
```
https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/UriParser/Parsers/FunctionOverloadResolver.cs

Could we add a test for this to Web Api OData?

(Side note: I took me a while until I figured out that I have to use ```xml<hostingEnvironment shadowCopyBinAssemblies="false" />``` in my Web.config. Without that I got a signing exception with ODataLib. Maybe this should go into a FAQ?).

Regards,
Kasimier Buchcik

**Comment by Casimodo72** [comment]
Made the ODataLib team aware of this issue: https://github.com/OData/odata.net/issues/200

**Comment by xuzhg** [comment]
@Casimodo72 

Thanks your further feedback. I re-open this issue again to track the ODL fix and Web API OData verification.

Of course, you're warmly welcome to contribute the product codes and test codes by pulling request.

Regards,
Sam

**Comment by TomDu** [comment]
Fixed in https://github.com/OData/odata.net/pull/398, feedbacks are welcome.
