### ISSUE TITLE
Some links are broken

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#361]
In http://odata.github.io/WebApi/#07-04-5-5, the following links don't work:
Abstract entity type without keys or properties 182
Complex type, Entity reference, Entity, and collection as function/action parameters 7
Edm.Date & Edm.TimeOfDay support 156
Open type and dynamic property on un-type scenario 171
Nested $filter in $expand 127

**Comment by xuzhg** [comment]
Updated the links at [here](https://github.com/OData/WebApi/commit/bb795a045e3c7046abe2439af1f4825332fd60c6)
