### ISSUE TITLE
Calling functions that have no parameters without parentheses should not be allowed

### ISSUE THREAD

**Issue by vojtechvit** [OData/WebApi#362]
Mapping OData routes of functions without parameters like this:

`ODataRoute("getTime")`

should not be allowed. [OData-ABNF] specifies:

`functionParameters = OPEN [ functionParameter *( COMMA functionParameter ) ] CLOSE`

Hence, I assume that the only correct way to map a function route should be:

`ODataRoute("getTime()")`

Of course there may be some optional behavior relaxation, but it should be explicit as with case insensitivity.

**Comment by mikepizzo** [comment]
OData 4.01 adds support for omitting the parenthesis when calling a parameterless function.
