### ISSUE TITLE
Allow exposing/receiving enum types as integer type

### ISSUE THREAD

**Issue by levicui** [OData/WebApi#364]
Currently, when we define an enum type in data entity, they are serialized and deserialized as enum type string, for example:

OData.Models.Color'1'
or
OData.Models.Color'Blue'

However, to support "adding an enum type" as a non-breaking change for clients, it would be nicer to also support integer type being exposed and consumed for enum property or parameter. This would also help to lower the traffic overhead over the wire.

Given that Enum type definition is already exposed through edm metadata, the server and client has already established the enum protocol, so consuming/sending an enum property as an integer from client would be easy.

**Comment by mikepizzo** [comment]
According to the OData protocol, the string-form is the preferred form when serializing an enum value on the wire (for human readability).  The numeric value is supported in the protocol only for extreme edge cases (a numeric value has been stored in the underlying store for which there is no enum member defined).
