### ISSUE TITLE
Model-Database First Many-to-Many Relationship Problem

### ISSUE THREAD

**Issue by dtotzke** [OData/WebApi#368]
Is it possible in v4 to make a many-to-many relationship work? I'm using EF 6, WebApi 2.2, OData v4, and the Client Generator for OData v4. Database first with EF model generated from that.  I am using the most recent release of all of the above.

I have a User, SecurityRole and a table that contains only the Id from each called UserSecurityRole as an intersection. The intersection entity is hidden in the EF diagram and when expanding User.SecurityRoles it filters everything as it should. 

If I add a SecurityRole to a User the CreateRef method in the UsersController is called and I can create the link there.  When I try to remove a SecurityRole from a User, the DELETE method in the SecurityRolesController gets called.  I have added DeleteRef methods to the Users and SecurityRoles controllers to no avail.

Because I am doing database/model first, I am having to construct the model during WebApiConfig.Register method. Is there something more I need to do here to define the many-to-many relationship?  

What needs to be defined in the Controllers?

I feel that this is a very common case and the documentation for it is non-existent.

public static class WebApiConfig
{
    public static void Register(HttpConfiguration config)
    {
        ODataModelBuilder builder = new ODataConventionModelBuilder();
        builder.Namespace = typeof(User).Namespace;
 
        RegisterEntitySets(builder);
        config.MapODataServiceRoute("ODataRoute", "odata", builder.GetEdmModel());
 
    }
 
    private static void RegisterEntitySets(ODataModelBuilder builder)
    {
        builder.EntitySet<ApplicationSetting>("ApplicationSettings");
        builder.EntitySet<AccessControlClaim>("AccessControlClaims");
        builder.EntitySet<AuditLog>("AuditLogs");
        builder.EntitySet<CustomLogEntry>("CustomLogEntries");
        builder.EntitySet<Preference>("Preferences");
        builder.EntitySet<SecurityRole>("SecurityRoles");
        builder.EntitySet<User>("Users");
        builder.EntitySet<UserPreference>("UserPreferences").EntityType
            .HasKey<int>(u => u.UserId)
            .HasKey<int>(p => p.PreferenceId);
 
    }
}

**Comment by saramgsilva** [comment]
I did not understood all your problem, you should provide more details about your controls and maybe your model + migrations + database is not correct.

Why are you defining RegisterEntitySets on WebApiConfig?  Why not in DbContext? You are mixing things, is not?

Normally I follow this http://www.entityframeworktutorial.net/code-first/configure-many-to-many-relationship-in-code-first.aspx

**Comment by dtotzke** [comment]
This is NOT code-first. I have an existing database with an EF Model (edmx) generated from that.  I must build the IEdmModel manually and pass that to MapODataServiceRoute.  Everything works fine except for this many-to-many relationship.  It's the classic User and SecurityRoles.  One User can have Many SecurityRoles and many SecurityRoles can have the same User.  

I am missing something either on the server-side configuration or the implementation of the controllers or I am not doing something properly on the client-side.

On the client-side, if I do:

myUser.Roles.Remove(someRole); 

and then call SaveChanges() the DELETE method of the RolesController will get called instead of the DeleteRef method.  

Maybe this is an unsupported scenario but I have trouble believing that something so common wouldn't be supported this far into implementation.

**Comment by karataliu** [comment]
Should use following API to delete reference.
context.DeleteLink(myUser,"Roles",someRole);

Actually no extra work is needed for building model with many-to-many relationship. Offline synced with issue creater, this has solved the issue.
