### ISSUE TITLE
$orderBy with duplicate property in odata v4

### ISSUE THREAD

**Issue by weslleyleandro** [OData/WebApi#376]
Using the last version of webAPI for Odata v4 (version 5.6) the following problem has been noted:

Considering a query where order by is needed in two fields with the same name from different tables, for example:

>http://localhost:44300/API/Fields?$expand=FieldGroup&$orderby=FieldGroup/Order,Order

The following exception is thrown:

>{
  "error":{
    "code":"","message":"The query specified in the URI is not valid. Duplicate property named 'Order' is not supported in '$orderby'.","innererror":{
      "message":"Duplicate property named 'Order' is not supported in '$orderby'.","type":"Microsoft.OData.Core.ODataException","stacktrace":"   at System.Web.OData.Query.OrderByQueryOption.ApplyToCore(IQueryable query, ODataQuerySettings querySettings)\r\n   at System.Web.OData.Query.OrderByQueryOption.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\r\n   at System.Web.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\r\n   at System.Web.OData.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)\r\n   at System.Web.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor)\r\n   at System.Web.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)"
    }
  }
}

Its important to mention, that a query using similar syntaxis was working when operating with odata v3.

**Comment by VikingsFan** [comment]
@weslleyleandro I have a pr #386 for this, would you help to review?

**Comment by weslleyleandro** [comment]
Hi @VikingsFan, I have tried to test your solution however I didn't manage to integrate it with my project using the source codes. I am not used to do it without nuget package and I faced many reference errors (I am sorry for that).

I will keep trying to make it work and return to you as soon as I can.

**Comment by VikingsFan** [comment]
Try add this url https://www.myget.org/F/aspnetwebstacknightly/ in nuget to get our nightly build nuget package, upgrade to 5.7 can test it.

**Comment by weslleyleandro** [comment]
Hi @VikingsFan, thank you very much for the link. With it I managed to install the **Microsoft ASP.NET Web API 2.2 for OData v4.0 (nightly 2015 Jun 15)**, however I still have the same problem with the order by.

Just to be sure, I create an another small project with 2 classes (Project and Supplier) and tried to order by the name of both entities and the error remains:

>{
  "error":{
    "code":"","message":"The query specified in the URI is not valid. Duplicate property named 'Name' is not supported in '$orderby'.","innererror":{
      "message":"Duplicate property named 'Name' is not supported in '$orderby'.","type":"Microsoft.OData.Core.ODataException","stacktrace":"   at System.Web.OData.Query.OrderByQueryOption.ApplyToCore(IQueryable query, ODataQuerySettings querySettings)\r\n   at System.Web.OData.Query.OrderByQueryOption.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\r\n   at System.Web.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\r\n   at System.Web.OData.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)\r\n   at System.Web.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor)\r\n   at System.Web.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)"
    }
  }
}

**Comment by VikingsFan** [comment]
@weslleyleandro  the code didn't checked in so the nightly can't work, you can review the test case in my PR, and after I check in, you can test with nightly build, or just use our master code to build dll.

**Comment by xuzhg** [comment]
Merged the PR. Thanks.
