### ISSUE TITLE
Action/Function Configurations are exposed via $metadata as ...

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#381]
The following is incorrect for OData v4:
`Action/Function Configurations are exposed via $metadata as a <FunctionImport/> element.`
https://github.com/OData/WebApi/blob/3c2f90ec7ca407ed9ba2be96330036fa513ba4a3/OData/src/System.Web.OData/OData/Builder/ActionConfiguration.cs#L15
https://github.com/OData/WebApi/blob/3c2f90ec7ca407ed9ba2be96330036fa513ba4a3/OData/src/System.Web.OData/OData/Builder/FunctionConfiguration.cs#L14
https://github.com/OData/WebApi/blob/909465b1e1b3e4016be3cc49ecaa5c6d119a20a3/vNext/src/Microsoft.AspNet.OData/Builder/ActionConfiguration.cs#L15
https://github.com/OData/WebApi/blob/909465b1e1b3e4016be3cc49ecaa5c6d119a20a3/vNext/src/Microsoft.AspNet.OData/Builder/FunctionConfiguration.cs#L14

Such as:
```c#
    /// ActionConfigurations are exposed via $metadata as a <FunctionImport/> element.
    /// </remarks> 
    /// </summary>
    public class ActionConfiguration : ProcedureConfiguration
```

**Comment by VikingsFan** [comment]
Checked in 157e387
