### ISSUE TITLE
Web API OData $expand doesn't return complex types

### ISSUE THREAD

**Issue by Sedatk** [OData/WebApi#394]
this issue is mentioned in the following stackoverflow question

http://stackoverflow.com/questions/20137681/web-api-odata-expand-doesnt-return-complex-types

**Comment by xuzhg** [comment]
@Sedatk  I saw that you had been fixing. What's about it?

**Comment by xuzhg** [comment]
Close it. See more context in https://github.com/OData/WebApi/pull/396.
