### ISSUE TITLE
MapODataRoute and Relax version constraints

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#397]
Add code snippet that customer can directly use, such as:
```c#
config.MapODataServiceRoute(routeName, routePrefix, model).HasRelaxedODataVersionConstraint();
```

The page needs update:
http://odata.github.io/WebApi/version-constraint-relax-flag/

**Comment by LianwMS** [comment]
Fix with 7abac59d95b349c9f2d04c31473ef63b6b6fadbc
