### ISSUE TITLE
Change IsRelaxedMatch's default value to True

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#398]
The change is for both OData v3 and v4, such as:
https://github.com/OData/WebApi/blob/41b457a981b95545970b9ebf5a99bc517e66cff1/OData/src/System.Web.OData/OData/Routing/ODataVersionConstraint.cs#L44

**Comment by congysu** [comment]
Related issue:
https://github.com/OData/WebApi/issues/397
https://github.com/OData/ODataSamples/issues/22

**Comment by xuzhg** [comment]
Commit: 7abac59
Thanks.
