### ISSUE TITLE
IEdmModel with entities inside value objects

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#40]
I have an EDM Model where a Money object has a structure roughly as follows -
this is quite a common domain modeling example I believe:  
  
public class Money  
{  
public Currency Currency {get; set;}  
public decimal Amount {get; set;}  
}  
  
Money is a value object whereas Currency is an entity with a database id.
However, if I define my model as follows then my odata route is invalid.  
  
var builder = new ODataConventionModelBuilder();  
builder.EntitySet<Currency>("Currencies");  
builder.ComplexType<Money>();  
  
I get the following error:  
  
The complex type 'Dealogic.DemoService.Model.Money' refers to the entity type
'Dealogic.DemoService.Model.Currency' through the property 'Currency'.  
  
There are a couple of possible workarounds:  

  * Give the Money value object just a currency id (not ideal because money calculations need to work with currency fields) 
  * Give the Money value object a DummyId field and add it as an entity, as below (a hack that will lead to further problems)   

EntityTypeConfiguration money = builder.AddEntity(typeof(Money));  
money.AddProperty(entityType.GetProperty("DummyId"));  
money.HasKey(entityType.GetProperty("DummyId"));  
  
I just wondered if anyone else has run into this problem and how they have
dealt with it? Will entities inside value objects be supported in the official
release?  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1141](http://aspnetwebstack.codeplex.com/workitem/1141)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jul 17, 2013 at 1:30 PM
**Reported by:**	GaryArcher
**Updated on:**	Sep 23, 2013 at 7:55 PM
**Updated by:**	danroth27

**Comment by LianwMS** [comment]
On *2013-07-18 07:21:59 UTC*, **eilonlipton** commented:

The current OData support in Web API is using OData v3, which does not allow this model. We are looking to support OData v4 in a future version of Web API, and we will look at adding support for this when that work begins.

**Comment by xuzhg** [comment]
So far, complex type doesn't allow to include navigation property.
