### ISSUE TITLE
Conversion error for DateTime.MinValue or MaxValue

### ISSUE THREAD

**Issue by CrazyViper** [OData/WebApi#401]
Conversion from DateTimeMinValaue to DateTimeOffset fails with ArgumentOutOfRangeException: 
> The UTC time represented when the offset is applied must be between year 0 and 10,000.

It happens in ODataPrimitiveSerializer on line:
```
DateTimeOffset dateTimeOffset = new DateTimeOffset(dateTime, timeZone.GetUtcOffset(dateTime));
```
I assume that min and max values must de converted without timezone.

**Comment by xuzhg** [comment]
Merged. Thanks.
