### ISSUE TITLE
Support key alias syntax

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#403]
Such as:

```
http://host/api/customers/@id?@id=1
http://host/api/customers(@id)?@id=1
http://host/api/customers(id=@id)?@id=1
```

When the key contains `/ :` etc.

**Comment by xuzhg** [comment]
It depends on ODL issue fix: https://github.com/OData/odata.net/issues/570

**Comment by mikepizzo** [comment]
Closing due to lack of customer activity. Will re-visit based on any user feedback.

Note that the first format (http://host/api/customers/@id?@id=1) is ambiguous as the @ sign may be a legal character for the key field. I believe that the protocol requires using parens notation for this scenario.

**Comment by cam-m** [comment]
Any chance this can be revisited?
