### ISSUE TITLE
ODataRoutePrefix does not work in OWIN-hosted controller

### ISSUE THREAD

**Issue by skyarkitekten** [OData/WebApi#409]
When using an OWIN-hosted controller, the ODataRoutePrefix does not work. It works fine if hosted in ASP.NET, and ODataRoute works fine in OWIN.

**Comment by congysu** [comment]
@skyarkitekten, can you provide a sample code.  End to end test cases have OWIN hosting coverage: https://github.com/OData/WebApi/blob/41b457a981b95545970b9ebf5a99bc517e66cff1/OData/build.cmd#L32-L35

**Comment by xuzhg** [comment]
Close it. If you have further concern, please re-open it or file a new issue. Thanks
