### ISSUE TITLE
InlineCount does not work when chaining V3 odata

### ISSUE THREAD

**Issue by jaksmid** [OData/WebApi#414]
Hi all,

We have an internal backend webserver that provides access to our database through oData V3.
Then we have another web server that connects to the first one and provides some limited odata functionality.

Both uses the odata v3 - web api 5.5.1 and odata, spatial and edm in the version 5.6.4.

The api of the first server works flawlessly.
The second server passes the query to the second server by using DataServiceContext derived class and using CreateQuery method.
This second server also works great with one exception:
If we add the $inlinecount=allpages, We get this error:

{"Message":"The OData path is invalid.","ExceptionMessage":"Invalid action detected. '$count' is not an action that can bind to 'Collection ....

The IIS log: /ourapi/oururl()/$count

But we use the OData v3 that can just use inlinecount.
Seems like part of this is using some v4 functionality.

Many thanks for help.
Cheers,
Jakub

**Comment by congysu** [comment]
@jaksmid, can you take a look about our v3 end to end test case: https://github.com/OData/WebApi/blob/41b457a981b95545970b9ebf5a99bc517e66cff1/OData/test/E2ETestV3/WebStack.QA.Test.OData/Formatter/ServerDrivenPagingTests.cs#L63-L68.  Thanks.

**Comment by jaksmid** [comment]
@congysu, thanks for your response. Will look into that and update you.

Cheers,
Jakub

**Comment by jaksmid** [comment]
Hi,

if I use just HttpClient client as in your test case, the total count is retrieved.

However when I use the DataServiceContext (v 5.6.4 from package or 4.0 from .Net), particularly the CreateQuery method, I get the error that $count' is not an action that can bind to 'Collection.

Any idea?
Thanks,
Jakub

**Comment by xuzhg** [comment]
@jaksmid 
[Web API OData v3](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.OData/) doesn't support "$count" segment. 

for your request Uri, the codes will throw the exception. See the following code:
```C#
throw new ODataException(Error.Format(SRResources.NoActionFoundForCollection, segment, collectionType.ElementType));
```

However, `$inlinecount=allpages` is supported in v3. So, you can query as:

```c#
~/Customers?$inlinecount=allpages
```
It should work.

Summarily, in Web API OData v3,
1. `$inlinecount` is used in query option. it supports.
2. `$count` is used in segment. It doesn't support.

**Comment by jaksmid** [comment]
Hi,

thanks for your replies, I have found out what is wrong: 
The second oData controllers accessing the first one was not lazy, so it immediately executed the query on the first odata service before adding the ODataQueryOptions.

It basically called something like odataEndpoint/MyCollection/$inlinecount=allpages resulting in the count error message because it thought that you have only a collection. The resolution was to disable EnableQuery attribute and add the OData options manually.

I am not sure if this is desired, it seemed to me that you can easily chain the odata services, but this is not the case.

**Comment by jaksmid** [comment]
This illustrates the rpoblem and our workaround:
![capture](https://cloud.githubusercontent.com/assets/3618465/8477257/02634746-20c9-11e5-92b1-652d6f4912a0.PNG)
