### ISSUE TITLE
Public TypedEdmStructuredObject etc.

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#417]
RESTier can use the [TypedEdmStructuredObject](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Formatter/Serialization/TypedEdmStructuredObject.cs), and its derived classes etc. to make the Post, Update Update symmetric to Get.

**Comment by congysu** [comment]
@xuzhg and @karataliu have a sync on this.

**Comment by xuzhg** [comment]
close it. Thanks
