### ISSUE TITLE
Add a simple hook to re-write all outgoing OData links.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#42]
Right now, we generate a bunch of links in the OData response payloads. These
are,  
  
1) Self links - ID, edit and read links.  
2) Navigation links,  
3) Metadata links.  
  
Customers want to use ODataConventionModelBuilder and yet have a simple way to
rebase the links that get generated. Doing it right now involves fixing up
these links for each and every entity set and navigation property which is lot
of code. Also, the metadata link cannot be changed.  
  
WCF DS supports this scenario. Refer to this blog [ post
](http://blogs.msdn.com/b/peter_qian/archive/2010/03/24/overwriting-the-
service-root-uri-in-wcf-data-service.aspx) .  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1247](http://aspnetwebstack.codeplex.com/workitem/1247)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Aug 26, 2013 at 6:51 PM
**Reported by:**	raghuramn
**Updated on:**	Jan 27, 2014 at 6:10 AM
**Updated by:**	zjufish

**Comment by LianwMS** [comment]
On *2013-09-10 05:24:41 UTC*, **yishaigalatzer** commented:

Need to figure out customer impact and amount of work required to move this to 5.1 or 6.0.

**Comment by LianwMS** [comment]
On *2013-09-11 03:16:58 UTC*, **raghuramn** commented:

A workaround is to replace the UrlHelper on the Request with a custom UrlHelper with overridden methods that rewrite the generated links. A sample is
here.

**Comment by LianwMS** [comment]
On *2013-09-11 03:19:23 UTC*, **raghuramn** commented:

Unfortunately, the workaround above (custom UrlHelper) does not rewrite next page links as they don't go through the normal UrlHelper.Link generation code path. So, the sample above has added a custom feed serializer to rewrite the next page links before
 they are written to the response.

**Comment by congysu** [comment]
A sample is https://gist.github.com/raghuramn/6514213

**Comment by xuzhg** [comment]
Close it. If you find any more concern, please re-open it. Thanks.
