### ISSUE TITLE
indexof doesn't work on null values (OData v4)

### ISSUE THREAD

**Issue by esditm** [OData/WebApi#423]
Consider this query:
`Get ~/odata/Foos`

Will result in:
````json
{
    "value": [
        {
            "Id": 1,
            "SomeString": null,
        },
        {
            "Id": 2,
            "SomeString": "",
        },
        {
            "Id": 3,
            "SomeString": "123",
        },
    ]
}
````

Then this query with a "does not contain 123" filter:
`Get ~/odata/Foos?$filter=indexof(SomeString, '123') eq -1`

Should return:
````json
{
    "value": [
        {
            "Id": 1,
            "SomeString": null,
        },
        {
            "Id": 2,
            "SomeString": "",
        }
    ]
}
````

But it returns:
````json
{
    "value": [
        {
            "Id": 2,
            "SomeString": "",
        }
    ]
}
````

Which is incorrect if you ask me :)

**Comment by xuzhg** [comment]
I tested it:

Get ~/odata/Foos?$filter=indexof(SomeString, '123') ne -1

only returns: `"Id": 3,`

So, for "null" scenario, we should have a clearer semantics.

**Comment by xuzhg** [comment]
@esditm 

Can you use the "And" operator to test. For example:

Get ~/odata/Foos?$filter=SomeString eq null and indexof(SomeString, '123') eq -1

**Comment by esditm** [comment]
Ah thanks, that'll get me by for now :)

**Comment by xuzhg** [comment]
@esditm Please re-open it if you have further concern about this. Thanks.
