### ISSUE TITLE
CultureInfo property can't be seraialized

### ISSUE THREAD

**Issue by marinkobabic** [OData/WebApi#427]
The entity type 'System.Globalization.Calendar' cannot be configured as a complex type because the derived type 'System.Globalization.GregorianCalendar' is already configured as an entity type.

To reproduce the exception:

            ODataModelBuilder modelBuilder = new ODataConventionModelBuilder();
            modelBuilder.EntitySet<CultureInfo>("cultureInfo");
            IEdmModel model = modelBuilder.GetEdmModel();
            config.MapODataServiceRoute("ODataRoute", "odata", model);

or use a Entity which has CultureInfo as property. This worked in previous versions.

**Comment by congysu** [comment]
@marinkobabic Which versions does this work in?  Thanks.

**Comment by xuzhg** [comment]
Fixed. Thanks.
