### ISSUE TITLE
Trouble with installation of nightly nuget packages

### ISSUE THREAD

**Issue by Casimodo72** [OData/WebApi#433]
Hi,

I cannot build with the current nightly package. Essentially System.Web.OData seems now to reference Microsoft.OData.Core Version=6.13.0.0, which is not installable as described here: https://github.com/OData/odata.net/issues/255.

NuGet V 3.0.60602.486 installed on 2015-06-04
VS 2015 RC Enterprise
This is a .NET 4.5.1 Solution (no vNext)
Newest nightly ASP Web Stack packags installed (as of today)

Assembly 'System.Web.OData' with identity 'System.Web.OData, Version=5.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
uses 'Microsoft.OData.Core, Version=6.13.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
which has a higher version than referenced assembly 'Microsoft.OData.Core' 
with identity 'Microsoft.OData.Core, Version=6.12.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

I think the problem lies on the side of the ODataLib packages, but since OData WebApi depends on those, the issue cascades.

Any clues what's going on with the packages?
My current thoughts on this are: NuGet shows ODataLib version numbers without the **rc** (or **beta**) but it shows the **rc** (and **beta**) in the list of dependencies and maybe fails due to this reason to resolve the dependencies.

Example:
Microsoft.OData.Client 6.13.0-Nightly20150713 
constraint: 
Microsoft.OData.Core (= 6.13.0-**rc**-Nightly20150713)'

But there is no 
Microsoft.OData.Core (= 6.13.0-**rc**-Nightly20150713)',
there is only a
Microsoft.OData.Core 6.13.0-Nightly20150713
I.e. without the **rc**.

Help, I need somebody ;-)

**Comment by Casimodo72** [comment]
I'm really **stuck** now. I can't downgrade anymore to the version that worked for me.
The oldest downgradable package is 5.7.0-beta-150623-Nightly. Doesn't work.
Then there's only the option to downgrade to stoneage: 5.2.0-alpha1-140307.
Previously I had 150611 installed (I think).

**Comment by Casimodo72** [comment]
Wait a minute. I just created a pristine web application and installed only
id="Microsoft.AspNet.OData" version="5.7.0-beta-150713-Nightly"
from the ASP Web stack. Doing that, NuGet managed to fetch the needed ODataLib RC packages:
id="Microsoft.OData.Core" version="6.13.0-rc"

So there seems to be hope for me. Maybe the issue is that I used the OData nightly package source in my Solution (https://www.myget.org/F/odlnightly).


<package id="Microsoft.OData.Core" version="6.13.0-rc" targetFramework="net45" />

**Comment by Casimodo72** [comment]
Nope. Doesn't work.
The problem arises when one uses .NET 4.5.1 instead of .NET 4.5.
Using a pristine web application, setting it to .NET 4.5.1 and trying to install "Microsoft.AspNet.OData version="5.7.0-beta-150713-Nightly" produces the following error:

Attempting to gather dependencies information for package 'Microsoft.AspNet.OData.5.7.0-beta-150713-Nightly' with respect to project 'Ga.Web', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'Microsoft.AspNet.OData.5.7.0-beta-150713-Nightly' with DependencyBehavior 'Highest'
Resolving actions to install package 'Microsoft.AspNet.OData.5.7.0-beta-150713-Nightly'
Resolved actions to install package 'Microsoft.AspNet.OData.5.7.0-beta-150713-Nightly'
Unable to find metadata of Microsoft.OData.Client 6.12.0-Nightly20150611

Same error when trying with DependencyBehavior 'Lowest'

So no more .NET 4.5.1 with current Microsoft.AspNet.OData?

**Comment by Casimodo72** [comment]
Installation using .NET 4.5.2 fails as well, but with a lot more words:

Attempting to gather dependencies information for package 'Microsoft.AspNet.OData.5.7.0-beta-150713-Nightly' with respect to project 'Web04', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'Microsoft.AspNet.OData.5.7.0-beta-150713-Nightly' with DependencyBehavior 'Highest'
Resolving actions to install package 'Microsoft.AspNet.OData.5.7.0-beta-150713-Nightly'
Resolved actions to install package 'Microsoft.AspNet.OData.5.7.0-beta-150713-Nightly'
For adding package 'Microsoft.OData.Edm 6.13.0-rc' to project 'Web04' that targets 'net452'.
For adding package 'Microsoft.OData.Edm 6.13.0-rc' to project 'Web04' that targets 'net452'.
Adding package 'Microsoft.OData.Edm 6.13.0-rc' to folder 'C:\Dev\Playground\My\Web04\packages'
Added package 'Microsoft.OData.Edm 6.13.0-rc' to folder 'C:\Dev\Playground\My\Web04\packages'
Added reference 'Microsoft.OData.Edm' to project 'Web04'.
Added package 'Microsoft.OData.Edm 6.13.0-rc' to 'packages.config'
Successfully installed 'Microsoft.OData.Edm 6.13.0-rc' to Web04.
For adding package 'Microsoft.Spatial 6.13.0-rc' to project 'Web04' that targets 'net452'.
For adding package 'Microsoft.Spatial 6.13.0-rc' to project 'Web04' that targets 'net452'.
Adding package 'Microsoft.Spatial 6.13.0-rc' to folder 'C:\Dev\Playground\My\Web04\packages'
Added package 'Microsoft.Spatial 6.13.0-rc' to folder 'C:\Dev\Playground\My\Web04\packages'
Added reference 'Microsoft.Spatial' to project 'Web04'.
Added package 'Microsoft.Spatial 6.13.0-rc' to 'packages.config'
Successfully installed 'Microsoft.Spatial 6.13.0-rc' to Web04.
Install failed. Rolling back...
Package 'Microsoft.OData.Core 6.13.0-rc' does not exist in project 'Web04'
Removed package 'Microsoft.Spatial 6.13.0-rc' from 'packages.config'
Removed reference 'Microsoft.Spatial.dll' from project 'Web04'
Removed package 'Microsoft.OData.Edm 6.13.0-rc' from 'packages.config'
Removed reference 'Microsoft.OData.Edm.dll' from project 'Web04'
Package 'Microsoft.OData.Core 6.13.0-rc' does not exist in folder 'C:\Dev\Playground\My\Web04\packages'
Removing package 'Microsoft.Spatial 6.13.0-rc' from folder 'C:\Dev\Playground\My\Web04\packages'
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\zh-Hans'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\zh-Hant'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\de'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\es'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\fr'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\it'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\ja'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\ko'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\ru'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnxcore50\zh-Hans'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnxcore50\zh-Hant'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnx451\zh-Hans'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnx451\zh-Hant'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnxcore50\de'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnxcore50\es'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnxcore50\fr'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnxcore50\it'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnxcore50\ja'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnxcore50\ko'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnxcore50\ru'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnx451\de'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnx451\es'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnx451\fr'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnx451\it'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnx451\ja'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnx451\ko'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnx451\ru'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnxcore50'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib\dnx451'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc\lib'.
Removed file 'Microsoft.Spatial.6.13.0-rc.nupkg' to folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.Spatial.6.13.0-rc'.
Removed package 'Microsoft.Spatial 6.13.0-rc' from folder 'C:\Dev\Playground\My\Web04\packages'
Removing package 'Microsoft.OData.Edm 6.13.0-rc' from folder 'C:\Dev\Playground\My\Web04\packages'
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\zh-Hans'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\zh-Hant'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\de'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\es'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\fr'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\it'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\ja'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\ko'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa\ru'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\portable-net40+sl5+wp8+win8+wpa'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnxcore50\zh-Hans'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnxcore50\zh-Hant'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnx451\zh-Hans'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnx451\zh-Hant'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnxcore50\de'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnxcore50\es'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnxcore50\fr'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnxcore50\it'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnxcore50\ja'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnxcore50\ko'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnxcore50\ru'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnx451\de'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnx451\es'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnx451\fr'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnx451\it'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnx451\ja'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnx451\ko'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnx451\ru'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnxcore50'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib\dnx451'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc\lib'.
Removed file 'Microsoft.OData.Edm.6.13.0-rc.nupkg' to folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc'.
Removed folder 'C:\Dev\Playground\My\Web04\packages\Microsoft.OData.Edm.6.13.0-rc'.
Removed package 'Microsoft.OData.Edm 6.13.0-rc' from folder 'C:\Dev\Playground\My\Web04\packages'
NuGet.Protocol.Core.Types.NuGetProtocolException: An error occurred while downloading package 'Microsoft.OData.Core 6.13.0-rc' from source 'https://www.nuget.org/api/v2/'. ---> System.Data.Services.Client.DataServiceClientException: Error processing response stream. Server failed with following message:
An error occurred while processing this request.
   at System.Data.Services.Client.Xml.XmlAtomErrorReader.Read()
   at System.Data.Services.Client.AtomParser.Read()
   at System.Data.Services.Client.AtomMaterializer.Read()
   at System.Data.Services.Client.MaterializeAtom.MoveNextInternal()
   at System.Data.Services.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__1`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NuGet.DataServicePackageRepository.FindPackage(String packageId, SemanticVersion version)
   at NuGet.PackageRepositoryExtensions.FindPackage(IPackageRepository repository, String packageId, SemanticVersion version, IPackageConstraintProvider constraintProvider, Boolean allowPrereleaseVersions, Boolean allowUnlisted)
   at NuGet.PackageRepositoryExtensions.FindPackage(IPackageRepository repository, String packageId, SemanticVersion version)
   at NuGet.Protocol.Core.v2.DownloadResourceV2.<>c__DisplayClass3_0.<GetDownloadResourceResultAsync>b__0()
   --- End of inner exception stack trace ---
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Finished ==========

**Comment by Casimodo72** [comment]
Solved!
After trying out various combinations of the .NET framework and highest/lowest dependency behavior, this is what worked for me:
1) Delete the local packages folder
2) Switch to .NET framework 4.5.2
3) Install Microsoft.AspNet.OData 5.7.0-beta-150713-Nightly with dependency behavior "highest" ("lowest" didn't work) from  (https://www.myget.org/F/aspnetwebstacknightly/)

Now I have:
<package id="Microsoft.AspNet.OData" version="5.7.0-beta-150713-Nightly" targetFramework="net452" />
<package id="Microsoft.OData.Core" version="6.13.0-rc" targetFramework="net452" />
<package id="Microsoft.OData.Edm" version="6.13.0-rc" targetFramework="net452" />
<package id="Microsoft.Spatial" version="6.13.0-rc" targetFramework="net452" />

The lessons learned for me here:
1) Don't use the OData nightly stack (https://www.myget.org/F/odlnightly). if you're aready using  (https://www.myget.org/F/aspnetwebstacknightly/). If that means you can't try out those newly packages then so be it.
2) Don't trust NuGet and delete your local packages folder when strange things happen
3) Backup important local packages in case they disappear from the package sources and you become stuck
3) Update you .NET framework version or stick to the version everyone else uses
4) Don't post such issues on GitHub, because MS folks are using the sources and not the packages anyway, thus may not be a fruitful audience ;-)

Cheers

**Comment by Casimodo72** [comment]
This issue was fixed by @congysu (see other thread) :-)

**Comment by congysu** [comment]
The nightly package is with name, such as: Microsoft.AspNet.OData.5.7.0-*beta-*150729-Nightly.  It should be Microsoft.AspNet.OData.5.7.0-150729-Nightly, or Microsoft.AspNet.OData.5.7.0-150729.

**Comment by LianwMS** [comment]
Fixed, name of nightly package now is:  Microsoft.AspNet.OData.5.7.0-Nightly150803
