### ISSUE TITLE
Verify if geo.intersects(point, polygon) works

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#434]
In Web API, and in ODataLib.

**Comment by xuzhg** [comment]
ODL supports `geo.intersects` built-in function, while Web API OData doesn’t support it. 

However, I have a [sample project](https://github.com/xuzhg/WebApiSample/tree/master/ODataSpatialSample) as work around.

**Comment by congysu** [comment]
@xuzhg Can you create a pull request to ODataSamples repo?  Thanks.

**Comment by xuzhg** [comment]
@congysu I moved my sample into ODataSamples repo. See https://github.com/OData/ODataSamples/commit/2eb16717642a26bb0d3e262d9568eb75426237ea
thanks.

**Comment by xuzhg** [comment]
Close it because the verification has been done.
