### ISSUE TITLE
ODataRoutePrefixAttribute and navigation property routing is not working

### ISSUE THREAD

**Issue by kaspernortoft** [OData/WebApi#436]
If I use the ODataRoutePrefix attribute on a Controller the routing to the navigation properties seems to fail. 

Its possible to add [ODataRoute("{key}/property")] to the Get action of the navigation property to make it work, but it should not be necessary.

The Put/Post navigation property action does not work even with the ODataRoute attribute.

**Comment by congysu** [comment]
Need write a page about $ref with attribute routing.

**Comment by xuzhg** [comment]
Close it. Please file a new issue if you have more concern.
