### ISSUE TITLE
metadata is not exposed correctly for properties with query limitations

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#44]
Create a model with an entity and some properties.  
Limit anyone of them.  
Query the $metadata url.  
The metadata doesn't expose the limitation on the vocabulary for the property.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1451](http://aspnetwebstack.codeplex.com/workitem/1451)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	cysu
**Reported on:**	Nov 25, 2013 at 2:11 AM
**Reported by:**	jacalvar
**Updated on:**	Dec 3, 2014 at 4:19 AM
**Updated by:**	jorgeaguirre1

**Comment by LianwMS** [comment]
On *2014-01-24 15:00:20 UTC*, **zjufish** commented:

we need to put this in capability.

**Comment by LianwMS** [comment]
On *2014-05-22 06:24:07 UTC*, **cysu** commented:

Moved to vNext till ODL is ready for capability vocabulary.

**Comment by xuzhg** [comment]
Supported. See: https://github.com/OData/WebApi/commit/122c3b38c47c6259a57c30e4638d8b3a03a73f1d
