### ISSUE TITLE
BindDynamicPropertyAccessQueryNode should handle HandleNullPropagationOption 

### ISSUE THREAD

**Issue by karataliu** [OData/WebApi#445]
https://github.com/OData/WebApi/blob/41b457a981b95545970b9ebf5a99bc517e66cff1/OData/src/System.Web.OData/OData/Query/Expressions/FilterBinder.cs#L237 

It should also handle HandleNullPropagationOption option here, as property access functions do.

**Comment by VikingsFan** [comment]
Checked in d3e217b1595144af3f0ccd427664435c5035b8bb
