### ISSUE TITLE
Parsing the generated KeyValue in the KeyValuePathSegment should be done lazily

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#45]
We are parsing the generated key-value in the KeyValuePathSegment. This should
be done lazily for performance  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1459](http://aspnetwebstack.codeplex.com/workitem/1459)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Nov 26, 2013 at 12:19 AM
**Reported by:**    jacalvar
**Updated on:** Jan 27, 2014 at 6:09 AM
**Updated by:** zjufish

**Comment by xuzhg** [comment]
KeyValuePathSegment is changed at 4e23aabcf9a171a844bd11f1882bf1038cb4a3b8. Please file a new issue if you have further concern.
