### ISSUE TITLE
Migrate vNext to beta6

### ISSUE THREAD

**Issue by gfrappier** [OData/WebApi#458]
Upgrade the vNext code to use the 1.0.0.beta6 runtime version .

**Comment by congysu** [comment]
@gfrappier  Could you help contribute the code change of upgrading?

**Comment by dneimke** [comment]
Hi all, are there plans and timeframes for having a build which runs off of beta6 or higher?

**Comment by gfrappier** [comment]
I will create a pull request today that supports beta6.

**Comment by VikingsFan** [comment]
Merged f4fb5d9d3795a355c74624ab7802a26e717fa933
