### ISSUE TITLE
Consider adding IConvertible support to Delta<T>

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#46]
It's somewhat possible to deserialize Delta<T> with Json.Net, and we've posted
a sample of how to do this to show a full solution. It would get a lot of
users closer if we added support for IConvertable conversions in the
TrySetValue method of Delta<T>  
  
We need to be careful about perf impact for OData scenarios.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1554](http://aspnetwebstack.codeplex.com/workitem/1554)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Dec 14, 2013 at 1:53 AM
**Reported by:**	nowakra
**Updated on:**	Apr 17, 2014 at 9:42 AM
**Updated by:**	zjufish

**Comment by xuzhg** [comment]
`Delta` and `Delta<T>` are both decorated with `NonValidatingParameterBinding`. And they are also derived from `DynamicObject`. So, close it. please file a new issue if you have further concern. Thanks.
