### ISSUE TITLE
In Odata Service unable to generate metadata for Dictionary property

### ISSUE THREAD

**Issue by ashuthinks** [OData/WebApi#467]
In Employee.cs

 public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string test { get; set; }
        public Dictionary < string, object > _map;
    }
In WebApiConfig.cs
ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
            builder.EntitySet<Employee>("Employees");
            config.MapODataServiceRoute(
            routeName: "ODataRoute",
            routePrefix: "odata",
            model: builder.GetEdmModel());

Generated metadata is `http://localhost:52038/odata/$metadata`

    <edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
    <edmx:DataServices>
    <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="MyService.Models">
    <EntityType Name="Employee">
    <Key>
    <PropertyRef Name="Id"/>
    </Key>
    <Property Name="Id" Type="Edm.Int32" Nullable="false"/>
    <Property Name="Name" Type="Edm.String"/>
    <Property Name="test" Type="Edm.String"/>
    </EntityType>
    </Schema>
    <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Default">
    <EntityContainer Name="Container">
    <EntitySet Name="Employees" EntityType="MyService.Models.Employee"/>
    </EntityContainer>
    </Schema>
    </edmx:DataServices>
    </edmx:Edmx>

here property is missing public  Dictionary< string , object > _map why so? any clue?
but when I use property like public  Dictionary< string , string  > _map2 it works great.

**Comment by object** [comment]
You can't expose any CLR type over OData protocol. Bear in mind that your OData service exposes your data over HTTP, and clients can run on various platforms, including mobile. Since "object" says nothing about the underlying type of an instance behind it, you must redesign your service to expose Edm-compatible types.

**Comment by ashuthinks** [comment]
but then how Dictionary< int, object > is working fine?

**Comment by object** [comment]
Not sure what is exposed in that case. Can you check the service metadata? How is such dictionary exposed?

**Comment by VikingsFan** [comment]
The Dictionary support in OData is Open Type, _map there called dynamic properties, it won't show in metadata, you should the attribute in metadata:

    <EntityType Name="Employee" OpenType="true">

FYI : http://www.asp.net/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/use-open-types-in-odata-v4

**Comment by ashuthinks** [comment]
ok thanks but how to add OpenType="true" in metadata file ? as metadata is auto generated using following code.
ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
            builder.EntitySet<Employee>("Employees");
            config.MapODataServiceRoute(
            routeName: "ODataRoute",
            routePrefix: "odata",
            model: builder.GetEdmModel());

**Comment by ashuthinks** [comment]
Still not getting that dynamic property in metdata 

I have used  public IDictionary<string, object> MyProperty7 { get; set; }

<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
<edmx:DataServices>
<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="MyService.Models">
<EntityType Name="Employee" OpenType="true">
<Key>
<PropertyRef Name="Id"/>
</Key>
<Property Name="Id" Type="Edm.Int32" Nullable="false"/>
<Property Name="Name" Type="Edm.String"/>
<Property Name="test" Type="Edm.String"/>
</EntityType>
</Schema>
<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Default">
<EntityContainer Name="Container">
<EntitySet Name="Employees" EntityType="MyService.Models.Employee"/>
</EntityContainer>
</Schema>
</edmx:DataServices>
</edmx:Edmx>

**Comment by VikingsFan** [comment]
Yes, the dynamic property won't show in metadata, you get the 

    < EntityType Name="Employee" OpenType="true">

It represent Employee have a dictionary for dynamic property, you can see in the asp.net sample: POST an Entity, the entity Book didn't have property Price, but you can still post because it is an open type, there is no need to know the Dictionary name for client.

**Comment by ashuthinks** [comment]
great thanks i'm facing same issue for java also in java instead of having IDictionary I'm having Map in java.
 private Map<String, MyClass> demo;
 public void setDemo(Map<String, MyClass> demo) {
        this.demo= demo;
    }

**Comment by congysu** [comment]
Change field to a property should work with Dictionary:
```
public Dictionary < string, object > _map;
```
=>
```
public Dictionary < string, object > _map { get; set;};
```
