### ISSUE TITLE
Investigate to support DateTime in WebApi, OData lib v4 will not support it.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#47]
OData lib v4 will not support DateTime. But for customer, the DateTime is used
frequently. So, please investigate whether and how to support DateTime in
WebApi.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1559](http://aspnetwebstack.codeplex.com/workitem/1559)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Dec 17, 2013 at 6:04 AM
**Reported by:**	xuzhg
**Updated on:**	Dec 17, 2013 at 6:04 AM
**Updated by:**	xuzhg

**Comment by xuzhg** [comment]
Resolved as Duplicated as #136
