### ISSUE TITLE
double.NaN, decimal.MaxValue doesn't work

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#48]
ODataLib UriParser doesn't work on some condition values, such as double.NaN,
decimal.MaxValue, etc.  
So, WebApi can't work on them.  
  
Please track on the ODL fix and make these condition values work.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1560](http://aspnetwebstack.codeplex.com/workitem/1560)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Dec 17, 2013 at 6:08 AM
**Reported by:**	xuzhg
**Updated on:**	Dec 17, 2013 at 6:08 AM
**Updated by:**	xuzhg

**Comment by VikingsFan** [comment]
Verified
