### ISSUE TITLE
Web API does not support Edm.Date literal in $filter when the property is Edm.Date [Nullable=True] and the backend is EF

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/WebApi#482]
I am using EF as the backend LINQ provider. If I have a property called `Birthday` of type `Edm.Date` with `Nullable=True`, the following query:

    $filter=Birthday eq 1986-01-01

would cause EF to throw exception: 

    Unable to create a constant value of type 'System.Nullable`1[[Microsoft.OData.Edm.Library.Date, Microsoft.OData.Edm, Version=6.13.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]'. Only primitive types or enumeration types are supported in this context.

If I set the `Nullable` to `False`, everything is fine.

**Comment by xuzhg** [comment]
Fixed. Thanks.
