### ISSUE TITLE
$count for actions/functions returning collections of complex types

### ISSUE THREAD

**Issue by gordon-matt** [OData/WebApi#484]
$count does not work for actions/functions returning collections of complex types. See details here:
http://stackoverflow.com/questions/31822755/passing-parameters-to-an-odata-get-method-which-returns-a-collection/31823976?noredirect=1#comment51621266_31823976

This is a big problem for me, as I need really @odata.count to be returned. Is there a workaround for now? Maybe I can get the source code, change a few lines of code and use that custom build for the moment?

**Comment by VikingsFan** [comment]
@gordon-matt This is working in 5.7, please check PR #546, I add a test case to test $count work for functions returning collections of complex types.

**Comment by gordon-matt** [comment]
It's working beautifully! Thanks!
