### ISSUE TITLE
Exceptions in RoutingConventions and PathHandler are not serialized in ODataV4 protocol compliant format

### ISSUE THREAD

**Issue by gkasturi** [OData/WebApi#485]
Exceptions occurring during routing are not serialized in the format specified here (http://docs.oasis-open.org/odata/odata-json-format/v4.0/errata02/os/odata-json-format-v4.0-errata02-os-complete.html#_Toc403940655). Instead a 404 is thrown.

**Comment by congysu** [comment]
Customize routing conventions, and add a catch all ODataController, in that controller, add a method: HandleUnmappedRequest
https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Routing/Conventions/UnmappedRequestRoutingConvention.cs

**Comment by xuzhg** [comment]
Close it please file a new issue if you have further concern.Thanks.
