### ISSUE TITLE
It's better to support automatically adding actions and functions in ODataConventionModelBuilder.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#49]
Now it is need to add actions and functions in this way:  

    
    
            var actionConfiguration = employee.Action("AddSkill");
            actionConfiguration.Parameter<Skill>("skill");
            actionConfiguration.ReturnsCollection<Skill>();
    

It will be more convenient If it is generated with reflection.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1587](http://aspnetwebstack.codeplex.com/workitem/1587)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Dec 25, 2013 at 12:25 PM
**Reported by:**	jinfutan
**Updated on:**	Jan 28, 2014 at 6:44 AM
**Updated by:**	xuzhg

**Comment by LianwMS** [comment]
On *2014-01-28 14:44:16 UTC*, **xuzhg** commented:

Postpone to vNext release.

**Comment by xuzhg** [comment]
Resolved it as won't fix. Thanks.
