### ISSUE TITLE
Versioning / Naming of OData Packages sucks

### ISSUE THREAD

**Issue by pascalberger** [OData/WebApi#491]
As already mentioned in #415 the naming and versioning of the OData Packages is really confusing. Are the v3 and v4 vesions in any way related? For example you fixed #216 for OData v4 v5.6. In the meantime you now also have released OData v3 v5.7 which [doesn't include this issue](http://odata.github.io/WebApi/5.7/). On the other hand the versions between v3 and v4 seem to be related in some way, because you have skipped OData v3 v5.6.

Why not just version the assemblies completely independently? Or what are you trying to achieve with the current versioning / naming schema?

It seems like you're aware of the problems in the naming since you've raised OData/odata.github.io#6. But there was no progress or replies over there...

**Comment by eloekset** [comment]
I'm also confused about this, but here's a blog post from one of the members of the ASP.NET team that may clear things up a bit: http://blogs.msdn.com/b/webdev/archive/2014/03/13/getting-started-with-asp-net-web-api-2-2-for-odata-v4-0.aspx

Read the section below **Important changes in this version**.

**Comment by pascalberger** [comment]
Thanks. The naming/namespacing, which is also confiusing, is one thing, but I really don't get what the version numbers try to explain, and if or how they are related between OData versions.

**Comment by mikepizzo** [comment]
OData V1-V4 refer to the versions of the OData protocol. OData protocol versions V1-V3 were Microsoft versions of the protocol, developed through an open process.  OData V4 is an OASIS, and now ISO, standard protocol.  There were some breaking changes between V1-V3 and V4, and we decided to have a new set of libraries for supporting the OData V4 standard so that we didn't carry forward excess code from the OData V1-V3 libraries.

Hope that helps.

**Comment by pascalberger** [comment]
@mikepizzo The difference between OData V1-V3 and V4 and its breaking changes are clear to me. This issue was about that I didn't get the idea behind the version numbers you are/were using. Eg. why didn't you start with 1.0 for the OData V4 package? Why isn't there a version 5.6 of the OData V3 library?

Probably not that much of an issue nowadays since 5.7 seemes to be the last version of the OData V3 library.
