### ISSUE TITLE
Odata Web API v4 - Open entity type and Unqualified Name call is not working.

### ISSUE THREAD

**Issue by ksureshhpk** [OData/WebApi#492]
Hi 
We are migrating the odata web api from v3 and v4, as there is new feature to add the dynamic properties at run time in v4. ie open type entity. so we created one of the entity as open type entity and we have few actions bounded to this entity.

Users are started using the v3 service without namespace , so we wanted to have v4 also without namespace, odata v4 supports it when we make a call to the config.EnableUnqualifiedNameCall(true);
we are able to call the odata urls without namespace after we added it. but open type entity alone this unqualifiednamecall is not working for the actions what we have. so we have added attribute routing to make it work. after adding the attribute routing, we could realize that its calling the POST method in the odata service but the parameter value is null in the odataactionparameters property. so when we call this with namespace am able to get the value in the odataactionparameters propert. so it seems unqualified name call is not working with open type entity. Below are my example.

Webapiconfig file :

ActionConfiguration actionAddCategory = builder.EntityType<A>().Action("AddCategory");
            actionAddCategory.Parameter<string>("CatID");
            actionAddCategory.ReturnsFromEntitySet<A>("A");

A Controller :

[ODataRoute("A({key})/AddCategory")]
        [HttpPost]             
        public A AddCategory([FromODataUri] string key, ODataActionParameters parameters)
        {
// when I call with namespace - working fine.
// when I call without namespace - its calling but the parameters argument is null and not having the value what am passing from client side.
}

Could you please check this and let me know if something wrong from my end.

Thanks
Suresh.

**Comment by congysu** [comment]
Related issue: https://github.com/OData/odata.net/issues/200

**Comment by VikingsFan** [comment]
This should work as the Issue in ODL 6.14 is fixed, @ksureshhpk please try WebAPI 5.8 rc.
