### ISSUE TITLE
OData Web API (v 5.6) - routing returns 404 (NOT FOUND) when calling a function with enumerated parameter(s)

### ISSUE THREAD

**Issue by korygin** [OData/WebApi#499]
Hi,

There seems to be a routing problem with calling OData 4 functions that have enumerated parameters. A work around is to use parameter aliasing, i.e.: http://localhost:4298/management/v1/AggregationBuckets(start=2015-08-26T20:00:00-05:00,end=2015-08-26T23:59:59-05:00,timeZone='US-Eastern',timeUnit=@p1,resolution=1,serviceId=null,clientId=null,userId=null)?@p1=Com.Ingr.ApiManagement.V1.TimeUnit%27Minute%27

However, specifying enumerated parameter value directly doesn't seem to work. This also prevents tools like Excel Power Query from invoking such functions.

Thanks,

Alex

**Comment by xuzhg** [comment]
@korygin Would you please try your scenario in 5.7? Or Would you please share us more your codes? As I know, Enum is supported in Uri. For example:

https://github.com/OData/WebApi/blob/master/OData/test/UnitTest/System.Web.OData.Test/OData/Formatter/ODataFunctionTests.cs#L32-L33

**Comment by korygin** [comment]
Hi,
It doesn't seem to work in 5.7 either. I am attaching a very simple test project to illustrate the problem. The first URL returns HTTP 404, while the second one with parameter aliasing gets the result back.
http://localhost:1622/odata/GetCountByCategory(category=ODataTest.Models.ProductCategories'Groceries')

http://localhost:1622/odata/GetCountByCategory(category=@p1)?@p1=ODataTest.Models.ProductCategories'Groceries'

Thanks,
Alex
Date: Sat, 5 Sep 2015 19:20:26 -0700

**Comment by xuzhg** [comment]
@korygin 

I wrote a test project to test. It works fine at my test project both for inline parameter or parameter alias for enum.  https://github.com/xuzhg/WebApiSample/tree/master/EnumParameterTest  is my project, it's a simple console application that you can run and debug it. and it refers to 5.6.  Please compare with your function definition and let us know any problem. Thanks.

**Comment by xuzhg** [comment]
@korygin Please re-open it if you find any problem. Thanks your feedback.
