### ISSUE TITLE
[vNext] GET /Customers(1)/Products returns a customer (vNext Navigation Properties)

### ISSUE THREAD

**Issue by julrichkieffer** [OData/WebApi#503]
Using the vNext branch, and running ODataSample.Web from source (commit 3b774a) on dnxcore50 beta6...

Calling `GET http://localhost:9091/odata/Customers(1)/Products` returns

``` javascript
{
  "@odata.context":"http://service-root/$metadata#Products/$entity",
  "@odata.type":"#ODataSample.Web.Models.Customer",
  "CustomerId":1,
  "FirstName":"Var1",
  "LastName":"Var2"
}
```

**instead of**

``` javascript
{
  "@odata.context":"http://service-root/$metadata#Products","value":[
    {
      "ProductId":1,"Name":"Apple","Price":10.0
    },{
      "ProductId":2,"Name":"Orange","Price":20.0
    }
  ]
}
```

**Comment by mikepizzo** [comment]
Thanks for your feedback.

The VNext branch was an experimental branch for exploring a way to support .NET Core.  Our direction for .NET Core support for WebAPI has gone a different direction, so we are no longer investing in the VNext branch.
