### ISSUE TITLE
[vNext] OData urls are case sensitive

### ISSUE THREAD

**Issue by julrichkieffer** [OData/WebApi#504]
Using the vNext branch, and running ODataSample.Web from source (commit 3b774a) on dnxcore50 beta6...

`http://localhost:9091/odata/customers(1)/firstName` returns _500 Internal Server Error_ where
`http://localhost:9091/odata/Customers(1)/FirstName` does not.

Why is the C# class definition _bleeding into_ the public api exposed by OData, which should be platform / language agnostic to the caller? Is there a centralised way -- i.e. without attributes on every class -- I can gain case insensitivity -- i.e. a convention for camel casing, or api-wide case insensitivity?

**Comment by congysu** [comment]
vCurrent support case insensitive Uri.  Welcome any contribution to port the change to vNext, or re-design.

**Comment by mikepizzo** [comment]
Thanks for your feedback.

The VNext branch was an experimental branch for exploring a way to support .NET Core.  Our direction for .NET Core support for WebAPI has gone a different direction, so we are no longer investing in the VNext branch.
