### ISSUE TITLE
[vNext] 404 Not Found should shortcircuit $expand etc

### ISSUE THREAD

**Issue by julrichkieffer** [OData/WebApi#505]
Using the vNext branch, and running ODataSample.Web from source (commit 3b774a) on dnxcore50  beta6...

`GET http://localhost:9091/odata/Customers(2)` **correctly** returns *404 Not Found*. However `GET http://localhost:9091/odata/Customers(2)?$expand=Products` returns *500 Internal Server Error* **instead of** the expected *404 Not Found*.

That is, when an entity is not found (i.e. a known request outcome), **further operations should be short-circuited** rather than these giving rise to runtime errors that occlude the underlying known state.

**Comment by congysu** [comment]
$expand support is newly added.

**Comment by VikingsFan** [comment]
reason is 

    context.HttpContext.Response's status code is always 200, even if controller return NotFound

at \src\Microsoft.AspNet.OData\EnableQueryAttribute.cs
consider change:

    if (!response.IsSuccessStatusCode())
    {
        return;
    }

to

    if (!response.IsSuccessStatusCode() || (context.Result as HttpStatusCodeResult != null))
    {
        return;
    }

**Comment by VikingsFan** [comment]
Merged af996ba17dd6e301088dabd2e8adcdf60a1f8cb5

**Comment by lazyWombat** [comment]
this fix causes a failure when the result cannot be casted to HttpStatusCodeResult. Run ODataSample.Web and use "odata/Products?$top=1" query. The full product list is returned.
context.Result is Microsoft.AspNet.Mvc.ObjectResult and it cannot be casted to HttpStatusCodeResult.

**Comment by VikingsFan** [comment]
Thanks, fixed as b0a0a74
