### ISSUE TITLE
Exception when using $select within $expand

### ISSUE THREAD

**Issue by klac503** [OData/WebApi#506]
The v5.7 release has broken the ability to use $select within $expand e.g. http://server/service/controller?$expand=NavProperty($select=Id). This has worked in prior versions including v5.6.

**Comment by congysu** [comment]
@klac503 Can you provide a repro?  Thanks.

**Comment by klac503** [comment]
I should be able to add a sample project in the next day or two.

**Comment by skarpovru** [comment]
Hi, same problem after upgrade on 5.7

**Comment by klac503** [comment]
In order to reproduce the problem you need to have a query filter, a base class on your entity class, and use the Entity Framework.

I've attached a sample project that duplicates the issue. There is a sql script included that creates a SQL Server database that is required to duplicate the issue. There's also a web application that hosts the 
service in IIS Express and a console application that makes the call to the service. You can also use Postman with the url http://localhost:42845/EntityRelations?$expand=NavEntity2($select=Id) to duplicate the issue.

Sample project:
![webapplication2 zip](https://cloud.githubusercontent.com/assets/14183720/9828374/34fddc74-58a1-11e5-8c59-e09a350a2f73.jpg)

Thanks

**Comment by congysu** [comment]
@klac503 the download link seems broken: https://cloud.githubusercontent.com/assets/14183720/9828374/34fddc74-58a1-11e5-8c59-e09a350a2f73.jpg

**Comment by klac503** [comment]
The link works for me. Opens in directly IE 11. For Chrome I have to right-click and select Save link as. Is there another way to upload a zip file?

**Comment by klac503** [comment]
Looks like this issue may be resolved with #522

**Comment by VikingsFan** [comment]
Closed as #522
