### ISSUE TITLE
Search engine cannot find any content in odata.github.io/WebApi

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#509]
Search for `release notes site:odata.github.io` returns no pages.

**Comment by VikingsFan** [comment]
Bing: can get the search result perfectly.
Google: use https://www.google.com/webmasters/tools/submit-url?continue=/addurl to add url, now we can search odata.github.io/webapi, but didn't get expected result when search content.
Baidu: use http://zhanzhang.baidu.com/linksubmit/url?sitename=http%3A%2F%2Fodata.github.io%2Fwebapi to add url, waiting for the result.
