### ISSUE TITLE
Remove MERGE http method

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#51]
Web API OData still supports MERGE. This is no longer part of the OData v4
specification.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1603](http://aspnetwebstack.codeplex.com/workitem/1603)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jan 6, 2014 at 7:36 AM
**Reported by:**	cysu
**Updated on:**	Jan 27, 2014 at 6:35 AM
**Updated by:**	zjufish

**Comment by LianwMS** [comment]
On *2014-01-27 14:35:37 UTC*, **zjufish** commented:

should we keep it for backward compatibility? or obsolete that method?

**Comment by xuzhg** [comment]
It's already merged. For example:

```
case "PATCH":
case "MERGE":
         actionNamePrefix = "Patch";
          break;
```
 Thanks.
