### ISSUE TITLE
Bug: case insensitivity does not work for collections sometimes

### ISSUE THREAD

**Issue by jayongg** [OData/WebApi#511]
This path is failing in DefaultODataPathHandler.Parse:
me/notes/noTeBooks/12345

"me" is a User
"notes" is a navigationproperty
notebooks is a collection of notebooks

I get the ODataException:
The request URI is not valid. Since the segment 'notebooks' refers to a collection, this must be the last segment in the request URI or it must be followed by an function or action that can be bound to it otherwise all intermediate segments must refer to a single resource.

However, this works with the (properly cased) path: me/notes/notebooks/12345

our metadata document is at https://www.onenote.com/api/beta/$metadata

I have a similar issue with this path:
mYOrgAniZation/SiteCollections?$expand=sites  Except it throws an ODataUnrecognizedPathException

**Comment by congysu** [comment]
Need to support key-as-segment with case insensitive url: https://github.com/OData/WebApi/issues/105
Issue can be in ODataLib: https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/UriParser/Metadata/ODataUriResolver.cs#L22

**Comment by VikingsFan** [comment]
@jayongg Hi, you say : "However, this works with the (properly cased) path: me/notes/notebooks/12345"

How do you turn on key as segment in WebApi?

I add test case in ODL's [PathTest](https://github.com/OData/odata.net/blob/master/test/FunctionalTests/Tests/DataOData/Tests/OData.Scenario.Tests/UriParser/Path/PathTests.cs), the exception you mentioned was occurred when key as segment    was not enabled:
working:

    ODataUriParser parser = new ODataUriParser(model, new Uri("http://www.potato.com/"), new Uri("http://www.potato.com/Schools/1/TEaCher/ORDERS/12345")) { UrlConventions = ODataUrlConventions.KeyAsSegment };
    parser.Resolver.EnableCaseInsensitive = true;
    var result = parser.ParsePath();

not working:

    ODataUriParser parser = new ODataUriParser(model, new Uri("http://www.potato.com/"), new Uri("http://www.potato.com/Schools/1/TEaCher/ORDERS/12345"));
    parser.Resolver.EnableCaseInsensitive = true;
    var result = parser.ParsePath();
