### ISSUE TITLE
Client issue deserializing when API returns Abstract Complex Type

### ISSUE THREAD

**Issue by lensgrinder** [OData/WebApi#513]
Hello,
I have an OData v4 service running on WebApi and have defined a function like this:
Function Name="GetRevisionAggregates" IsBound="true"
  Parameter Name="bindingParameter" Type="ScenarioPortal.V1.Model.Measure"  
  Parameter Name="pivotType" Type="ScenarioPortal.V1.Model.PivotType" Nullable="false" 
  ReturnType Type="Collection(ScenarioPortal.V1.Model.MeasureWithRevisionAggregate)" 
Function

Where MeasureWithRevisionAggregate is an abstract complex type:
Depending on the payload of the return set, a collection of different sub types will be returned where all the instances are of the same subtype, say DescriptiveStatisticsAggregate.
The Json returned by WebApi, however, doesn’t seem to make much sense to the V4 Generated Client who complains that the return type is not correct since DescriptiveStatisticsAggregate doesn’t match MeasureWithRevisionAggregate type.
When I look at the raw json returned by the service and try to load it using JsonConvert.DeserializeObject, it doesn’t produce any error, but doesn’t deserialize any of the data into the instance.
{ "@odata.context":"http://missioncontrolppe-data/ScenarioPortalOdataService/DataAccess/V1/$metadata#Collection(ScenarioPortal.V1.Model.DescriptiveStatisticsRevisionAggregate)","value":[ { "BuildRevision":0,"EventTime":"2015-04-27T00:00:00Z","MetricCardinality":1.0,"MetricMean":-88.0,"BuildNumber":10104,"BuildArchitecture":null,"MeasureId":900180 } ] }

Is there something wrong with the client or something wrong with trying to use abstract complex types in this way?

Thanks,
Michael

**Comment by VikingsFan** [comment]
Closed as open in ODL https://github.com/OData/odata.net/issues/439
