### ISSUE TITLE
Support now()

### ISSUE THREAD

**Issue by MaxWilson** [OData/WebApi#514]
Per oData v4 spec,

5.1.1.4.21 now
The now function has the following signature:
Edm.DateTimeOffset now()
The now function returns the current point in time (date and time with time zone) as a DateTimeOffset value. 

This doesn't seem to be supported in version 5.6 of oData.

_Example:_ http://Example.com/ProductPrices?$count=true&$filter=SKU+eq+%274F3-00015%27+and+FutureEndDate+gt+now()

_Result:_ 

``` javascript
    {
      error: {
        code: "",
        message: "The query specified in the URI is not valid. Unknown function 'now'."
      }
    }
```

**Comment by congysu** [comment]
Now() is not supported for now.

**Comment by robward-ms** [comment]
See #872
