### ISSUE TITLE
Manually using ODataQueryOptions.Validate and setting SelectExpandQueryOption.LevelsMaxLiteralExpansionDepth

### ISSUE THREAD

**Issue by MikalJ** [OData/WebApi#516]
When manually calling `ODataQueryOptions.Validate(...)`, with `MaxExpansionDepth` set to 1, for a request, with more than one expansion levels, will fail with the wrong exception being thrown (`InvalidExpansionDepthValue` rather than `MaxExpandDepthExceeded`) from line 44 in SelectExpandQueryValidator
```
if (selectExpandQueryOption.LevelsMaxLiteralExpansionDepth > validationSettings.MaxExpansionDepth)
{
    throw new ODataException(Error.Format(
        SRResources.InvalidExpansionDepthValue,
        "LevelsMaxLiteralExpansionDepth",
        "MaxExpansionDepth"));
}
```
The reason is that `SelectExpandQueryOption.LevelsMaxLiteralExpansionDepth` has not been correctly set.
This is usually handled in `EnableQueryAttribute` line 548
```
if (queryOptions.SelectExpand != null)
{
    queryOptions.SelectExpand.LevelsMaxLiteralExpansionDepth = _validationSettings.MaxExpansionDepth;
}
```
It looks like `SelectExpandQueryOption.LevelsMaxLiteralExpansionDepth` is mostly for internal use (despite being public). For that reason, and because the documentation suggests using `ODataQueryOptions.Validate()` and `ODataQueryOptions.ApplyTo()` as a valid alternative to `EnableQueryAttribute`, setting `SelectExpandQueryOption.LevelsMaxLiteralExpansionDepth` should be handled automatically (possible in the `ODataQueryOptions.Validate()` method) rather than manually having to set it on the ODataQueryOptions object.

**Comment by congysu** [comment]
update _levelsMaxLiteralExpansionDepth's default value to max expansion depth in validation setting:
https://github.com/OData/WebApi/blob/41b457a981b95545970b9ebf5a99bc517e66cff1/OData/src/System.Web.OData/OData/Query/SelectExpandQueryOption.cs#L264

**Comment by luoyan0517** [comment]
Committed as 618efe7 and 3a3ef57
