### ISSUE TITLE
No nightly packages anymore?

### ISSUE THREAD

**Issue by Casimodo72** [OData/WebApi#517]
Hi,
the last nightly package is two months old: v5.7.0-beta-150729-Nightly.
(see https://www.myget.org/gallery/aspnetwebstacknightly)
Why are there no newer nightly packages?

When instead installing the newer v5.7.0 from nuget.org which is dated Friday, August 21 2015, then NuGet insists on installing ODataLib 6.13.0 dated Wednesday, July 22 2015.

This means I'm not able to use the nightly ODataLib (currently v6.13.0-Nightly20150924).

How to solve this? 
Should I keep using OData/WepApi v5.7.0-beta-150729-Nightly if I want the newest ODataLib packages?

Regards,
Kasimier Buchcik

**Comment by Casimodo72** [comment]
What I did to circumvent this strange version constraint:

1) Install v5.7.0 from nuget.org. This will also install the old ODataLib release packages.

2) Manually remove the entries for "Microsoft.OData.Client", "Microsoft.OData.Core", "Microsoft.OData.Edm", "Microsoft.Spatial" from packages.config and assembly references.

3) Open package manager console and select your OData nightly packages source.

4) Try to install the latest ODataLib package. This will fail if we let NuGet try to apply version constraints:

PM> install-package Microsoft.OData.Client -IncludePrerelease -Version 6.13.0-Nightly20150927 
...
install-package : Unable to find a version of 'Microsoft.OData.Core' that is compatible with 'Microsoft.AspNet.OData 5.7.0 constraint: Microsoft.OData.Core (≥ 6.13.0 && < 
7.0.0)', 'Microsoft.OData.Client 6.13.0-Nightly20150927 constraint: Microsoft.OData.Core (= 6.13.0-Nightly20150927)'.

5) Using the "-DependencyVersion Ignore" worked for me. Maybe there's an easier way, but I added all four packages this way:

install-package Microsoft.OData.Client -IncludePrerelease -Version 6.13.0-Nightly20150927 -DependencyVersion Ignore
install-package Microsoft.OData.Core -IncludePrerelease -Version 6.13.0-Nightly20150927 -DependencyVersion Ignore
nstall-package Microsoft.OData.Edm -IncludePrerelease -Version 6.13.0-Nightly20150927 -DependencyVersion Ignore
install-package Microsoft.Spatial -IncludePrerelease -Version 6.13.0-Nightly20150927 -DependencyVersion Ignore

Regards,
Kasimier Buchcik

**Comment by LianwMS** [comment]
Hi Casimodo72,
Sorry for this issue.We have made the fix and the latest nuget package has been uploaded to myget. 
A little changes, the naming rule for WebAPI OData nuget package has been modified to align with ODatalib.... 
Please try to use and give the feedback.

Thanks,
Liang

**Comment by Casimodo72** [comment]
Hi @LianwMS,
thank you for working on this issue and giving us as fresh 5.7.0-Nightly150929 :-)

The machinery is still confused somehow.

1) When installing Microsoft.AspNet.OData 5.7.0-Nightly150929, NuGet still wants to uninstall the nightly ODataLib packages and install the non-nightly ODataLib packages:

![odatalib-nightly-00](https://cloud.githubusercontent.com/assets/10551738/10171341/fc69fb6c-66d9-11e5-89e0-2e9be5d8b27c.png)

2) When I then switch directly over to the OData nightly package source in the NuGet GUI, no nightly packages and no option to upgrade are available:

 ![odatalib-nightly-01](https://cloud.githubusercontent.com/assets/10551738/10171425/5ea298e8-66da-11e5-996f-72398eae62ac.png)

3) The command line shows the nightly packages though:

![odatalib-nightly-02](https://cloud.githubusercontent.com/assets/10551738/10171615/48bf5d26-66db-11e5-9788-547f8a5584b1.png)

4) Finally I still need to install the nightly packages over the non-nightly packages:

![odatalib-nightly-03](https://cloud.githubusercontent.com/assets/10551738/10171658/764ff6f6-66db-11e5-9825-e09b9268679a.png)

Regards,
Kasimier Buchcik

**Comment by Casimodo72** [comment]
Is it OK that the nightly packages try to uninstall the nightly ODataLib packages?

**Comment by xuzhg** [comment]
Hi, Casimodo72

-  ODL nightly is : https://www.myget.org/F/odlnightly

For example:
![odlnightlyall](https://cloud.githubusercontent.com/assets/9426627/12161373/fd95a71c-b52f-11e5-8752-578cdc1469ed.png)


-  Web API OData nightly is: https://www.myget.org/F/aspnetwebstacknightly/

For example:
![nightlyall](https://cloud.githubusercontent.com/assets/9426627/12161240/826b2018-b52e-11e5-81b5-db0e22b370b3.png)

-  I installed a ODL nightly package. Now, I install Web API OData nightly package. It gives me the following:
![updatenightlyall](https://cloud.githubusercontent.com/assets/9426627/12161592/5dfbf51e-b532-11e5-93d2-c764c128a607.png)

Thanks.
