### ISSUE TITLE
Convert webapi.odata's ODataPath to OData's ODataPath

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#52]
Now, webapi.odata has its own implementation of ODataPath and related
segments; however, some ODL APIs require passing an ODL ODataPath. 2 options:  
1. webapi.odata uses ODL's ODataPath 
2. Convert webapi.odata's ODataPath to ODL's ODataPath 
## Work Item Details

**Original CodePlex Issue:**    [Issue 1604](http://aspnetwebstack.codeplex.com/workitem/1604)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Jan 6, 2014 at 9:47 AM
**Reported by:**    cysu
**Updated on:** May 5, 2014 at 10:31 AM
**Updated by:** zjufish

**Comment by xuzhg** [comment]
See breaking change https://github.com/OData/WebApi/commit/505621465bdab9bb5e6784141092412bea2ccf49.
