### ISSUE TITLE
After update System.Web.OData to version 5.7.0.0 we get an "DbIsOfExpression requires ..." with $expand($select=...) OData query

### ISSUE THREAD

**Issue by waldrix** [OData/WebApi#522]
After update System.Web.OData to version 5.7.0.0 (from 5.6.0.0) we get a System.ArgumentException "DbIsOfExpression requires an expression argument with a polymorphic result type that is compatible with the type argument." when use expand options selecting only some field ex. $expand($select=...) 

Some query that fails:

http://localhost:56961/odata/Domini?$expand=ServerAutenticazione($select=Id)
http://localhost:56961/odata/Persone?$top=10&$expand=Residenze($select=Indirizzo)
http://localhost:56961/odata/Persone('0BLLHSNMA7Z249AG')?$expand=Residenze($select=Indirizzo)

These queries worked fine with version 5.6.0.0.

Investigating further we detect that the problem depends on [ConcurrencyCheck] marked property we have in our entities, if we comments ConcurrencyCheck Attribute both on parent and child the queries succeed without errors, if we comments on parent the queries succeed without errors when we include the concurrency check property in the $select inner the $expand query options.

Here the two entities related "http://localhost:56961/odata/Domini?$expand=ServerAutenticazione($select=Id)" query

	[Table("Domini")]
	public class Dominio : IRecVer, IDtAgg
	{
		[Key]
		[StringLength(50)]
		public string Id { get; set; }

		[StringLength(200)]
		public string Descrizione { get; set; }

		public string ServerAutenticazioneId { get; set; }

		[ForeignKey("ServerAutenticazioneId")]
		public virtual Server ServerAutenticazione { get; set; }

		public string ServerRicercheId { get; set; }

		[StringLength(50)]
		[ForeignKey("ServerRicercheId")]
		public virtual Server ServerRicerche { get; set; }

		[ConcurrencyCheck]
		public int? RECVER { get; set; }
		public DateTime? dtAgg { get; set; }
	}

	[Table("Servers")]
	public class Server : IRecVer, IDtAgg
	{
		[Key]
		[StringLength(50)]
		public string Id { get; set; }

		[StringLength(200)]
		public string Descrizione { get; set; }

		[StringLength(2000)]
		public string Url { get; set; }

		[ConcurrencyCheck]
		public int? RECVER { get; set; }
		public DateTime? dtAgg { get; set; }
	}

This is the detail of error with call stack

{
  "error":{
    "code":"","message":"An error has occurred.","innererror":{
      "message":"The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; odata.metadata=minimal'.","type":"System.InvalidOperationException","stacktrace":"","internalexception":{
        "message":"DbIsOfExpression requires an expression argument with a polymorphic result type that is compatible with the type argument.","type":"System.ArgumentException","stacktrace":"   at System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder.DbExpressionBuilder.ValidateIsOf(DbExpression argument, TypeUsage type)\r\n   at System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder.DbExpressionBuilder.IsOf(DbExpression argument, TypeUsage type)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.IsTranslator.TypedTranslate(ExpressionConverter parent, TypeBinaryExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.ConditionalTranslator.TypedTranslate(ExpressionConverter parent, ConditionalExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberInitTranslator.TypedTranslate(ExpressionConverter parent, MemberInitExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberInitTranslator.TypedTranslate(ExpressionConverter parent, MemberInitExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberInitTranslator.TypedTranslate(ExpressionConverter parent, MemberInitExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberInitTranslator.TypedTranslate(ExpressionConverter parent, MemberInitExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input, DbExpressionBinding& binding)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, DbExpression& source, DbExpressionBinding& sourceBinding, DbExpression& lambda)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SelectTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SequenceMethodTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, SequenceMethod sequenceMethod)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.Convert()\r\n   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()\r\n   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()\r\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()\r\n   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()\r\n   at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteFeed(IEnumerable enumerable, IEdmTypeReference feedType, ODataWriter writer, ODataSerializerContext writeContext)\r\n   at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)\r\n   at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)\r\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders)\r\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()"
      }
    }
  }
}

**Comment by congysu** [comment]
5.7 advertises concurrency annotation in $metadata.  Check if related.  Add test case with ConcurrencyCheck + Expand with Select + EF in e2e.

**Comment by waldrix** [comment]
I've read release notes for 5.7 (http://odata.github.io/WebApi/5.7/) and this issue https://github.com/OData/WebApi/issues/459 but I don't found any related information.

Now i've added a specific test to our e2e test suite to reproduce the problems, simple query like "http://localhost:9876/odata/Persone?$filter=CFPersona%20eq%20%27DCPRCR75B06H501E%27&$expand=Residenze($select=CFPersona,Indirizzo)" generate the error "DbIsOfExpression requires an expression argument with a polymorphic result type that is compatible with the type argument." when both parent and child entity contains a ConcurrencyCheck marked field (in this case [ConcurrencyCheck] public int? RECVER { get; set; }... 

The errors happens also with declaring RECVER not nullable, and including RECVER in select options. 

Can you help me? Thanks!

**Comment by xuzhg** [comment]
Fixed. Thanks.
