### ISSUE TITLE
Make members of ODataSegmentKinds const string

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/WebApi#523]
https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Routing/ODataSegmentKinds.cs

Users cannot use these constants in switch statement now.

**Comment by congysu** [comment]
Change from static readonly to const?

**Comment by lewischeng-ms** [comment]
@congysu Yes, directly declare some string const(s) and remove the static readonly fileds.
