### ISSUE TITLE
Support IEEE754Compatible=true/false

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#53]
ODL V4 support IEEE754Compatible=true/false in media type.  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1631](http://aspnetwebstack.codeplex.com/workitem/1631)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Jan 17, 2014 at 6:23 AM
**Reported by:**    xuzhg
**Updated on:** Jan 17, 2014 at 6:23 AM
**Updated by:** xuzhg

**Comment by karataliu** [comment]
Related stackoverflow question(with workaround):
http://stackoverflow.com/questions/30101625/webapi-odata-serialize-long-as-string

**Comment by mikepizzo** [comment]
Note: the suggested workaround in http://stackoverflow.com/questions/30101625/webapi-odata-serialize-long-as-string copies the type parameter from the input content type, while the Accept header should be used for the output content type.  If the IEEE754Compatible is specified in the Accept header, we should always honor that.

**Comment by wmalgadey** [comment]
@mikepizzo is there a reason why you closed this issue? It is still present, and there is no possibility to transfer "long" (Edm.Int64) values with `IEEE754Compatible=true`, isn't it?
