### ISSUE TITLE
The type 'FromBodyAttribute' exists in both Microsoft.AspNet.Mvc.Core and Microsoft.AspNet.Mvc.ModelBinding (Error CS0433)

### ISSUE THREAD

**Issue by encounter12** [OData/WebApi#537]
#### Short Description:
After adding Microsoft.AspNet.OData package (<a href="https://www.myget.org/gallery/odatavnext" target="_blank">https://www.myget.org/gallery/odatavnext</a>, currently: 6.0.0-alpha1) to project an error message appears on Build. 

#### Full Error Details:
D:\TestSystem\server\TestSystem.WebAPI\Controllers\TestsController.cs(38,27): DNXCore,Version=v5.0 error CS0433: The type 'FromBodyAttribute' exists in both 'Microsoft.AspNet.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.AspNet.Mvc.ModelBinding, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'

#### Troubleshooting performed: 
After removing the entry: "Microsoft.AspNet.OData": "6.0.0-*" from project.json, deleting the package folders and running "dnu restore" the issue gets solved. When re-adding the entry "Microsoft.AspNet.OData": "6.0.0-*" to project.json and restoring the packages the problem re-appears. 

In project.lock.json Microsoft.AspNet.OData/6.0.0-alpha1 depends on Microsoft.AspNet.Mvc.WebApiCompatShim 6.0.0-beta4 which has its own dependency: "Microsoft.AspNet.Mvc.ModelBinding": "6.0.0-beta4" (see source code below). In ASP.NET 5 Beta 4, FromBodyAttribute was located in: Microsoft.AspNet.Mvc.ModelBinding/BinderMetadata/ and I consider in a later release it was moved to: Microsoft.AspNet.Mvc.Core and Microsoft.AspNet.Mvc.ModelBinding was deleted. 

#### Possible Solution (steps): 

1. Updating OData vNext dependency package version from Microsoft.AspNet.Mvc.WebApiCompatShim v6.0.0-beta4 to the latest one specified on: <a href="https://www.myget.org/gallery/aspnetvnext" target="_blank">https://www.myget.org/gallery/aspnetvnext</a> (currently: Microsoft.AspNet.Mvc.WebApiCompatShim v6.0.0-rc1-16028)

2. Removing Dependency: 

Microsoft.AspNet.Mvc.ModelBinding v6.0.0-beta4

P.S. Please, let me know if some additional information is needed or if the issue is related to some specifics in my code. My solution full source code could be downloaded from <a href="https://drive.google.com/file/d/0B7HDR8W21lAid1hDY3ZkZlFnUDQ/view?usp=sharing" target="_blank">here</a>.

---

ASP.NET 5 "dev" nightly builds (<a href="https://www.myget.org/gallery/aspnetvnext" target="_blank">https://www.myget.org/gallery/aspnetvnext</a>) problem packages Depdendency versions:

* Microsoft.AspNet.Mvc.WebApiCompatShim v6.0.0-rc1-16028 (does not depend on Microsoft.AspNet.Mvc.ModelBinding)
* Microsoft.AspNet.Mvc.ModelBinding v6.0.0-beta5-13645

OData v4 web api 6.0 preview (6.0.0-alpha1) (<a href="https://www.myget.org/gallery/odatavnext" target="_blank">https://www.myget.org/gallery/odatavnext</a>) problem packages Depdendency versions: 

* Microsoft.AspNet.Mvc.WebApiCompatShim v6.0.0-beta4 (depends on: Microsoft.AspNet.Mvc.ModelBinding v6.0.0-beta4)
* Microsoft.AspNet.Mvc.ModelBinding v6.0.0-beta4

--------------------

##### ASP.NET 5 Beta 4 Release (FromBodyAttribute location) 
* Branch: beta
<a href="https://github.com/aspnet/Mvc/blob/beta/src/Microsoft.AspNet.Mvc.ModelBinding/BinderMetadata/FromBodyAttribute.cs" target="_blank">https://github.com/aspnet/Mvc/blob/beta/src/Microsoft.AspNet.Mvc.ModelBinding/BinderMetadata/FromBodyAttribute.cs</a>

* Branch: beta4-pinned
<a href="https://github.com/aspnet/Mvc/blob/beta4-pinned/src/Microsoft.AspNet.Mvc.ModelBinding/BinderMetadata/FromBodyAttribute.cs" target="_blank">https://github.com/aspnet/Mvc/blob/beta4-pinned/src/Microsoft.AspNet.Mvc.ModelBinding/BinderMetadata/FromBodyAttribute.cs</a>

##### ASP.NET 5 Beta 8 Release (FromBodyAttribute location) 
* Branch: dev
<a href="https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/FromBodyAttribute.cs" target="_blank">https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/FromBodyAttribute.cs</a>

--------------------
##### .NET Execution environment (DNX)
Version: 1.0.0-rc1-15838
Type: Clr
Architecture: x86
OS Name: Windows
OS Version: 8.0
Runtime Id: win8-x86

--------------------

##### FromBody attribute usage in TestController.cs:

```csharp
[HttpPost]
public void Post([FromBody]string value)
{
}
```
----------------------------

##### Project.json

```json
{
  "webroot": "wwwroot",
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.AspNet.Cors": "6.0.0-*",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
    "Microsoft.AspNet.Diagnostics": "1.0.0-*",
    "Microsoft.AspNet.Server.IIS": "1.0.0-*",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
    "Microsoft.AspNet.StaticFiles": "1.0.0-*",
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.AspNet.OData": "6.0.0-*"
  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000",
    "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5004",
    "run": "run server.urls=http://localhost:5003"
  },

  "frameworks": {
    "dnx451": {
      "dependencies": {
      }
    },
    "dnxcore50": {
    }
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ]
}
```
##### Nuget.Config (Solution level):
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="aspnetvnext" value="https://www.myget.org/F/aspnetvnext/api/v3/index.json" />
    <add key="aspnetvnext" value="https://www.myget.org/F/aspnetvnext/" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="aspnetwebstacknightly" value="https://www.myget.org/F/aspnetwebstacknightly/api/v3/index.json" />
    <add key="aspnetwebstacknightly" value="https://www.myget.org/F/aspnetwebstacknightly/" />
    <add key="odatavnext" value="https://www.myget.org/F/odatavnext/api/v3/index.json" />
    <add key="odatavnext" value="https://www.myget.org/F/odatavnext/" />
  </packageSources>
</configuration>
```
##### Global.json
```json
{
  "sdk": {
    "version": "1.0.0-*"
  }
}
```
##### Project.lock.json (extract):
```json
"Microsoft.AspNet.OData/6.0.0-alpha1": {
  "type": "package",
  "dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-beta4",
    "Microsoft.AspNet.Mvc.WebApiCompatShim": "6.0.0-beta4",
    "Microsoft.CSharp": "4.0.0-beta-22816",
    "Microsoft.Framework.OptionsModel": "1.0.0-beta4",
    "Microsoft.OData.Core": "6.12.0",
    "Microsoft.OData.Edm": "6.12.0",
    "Microsoft.Spatial": "6.12.0",
    "System.Collections": "4.0.10-beta-22816",
    "System.Diagnostics.Debug": "4.0.10-beta-22913",
    "System.Diagnostics.Tools": "4.0.0-beta-22913",
    "System.Globalization": "4.0.10-beta-22913",
    "System.Linq": "4.0.0-beta-22816",
    "System.Linq.Queryable": "4.0.0-beta-22913",
    "System.Reflection": "4.0.10-beta-22913",
    "System.Resources.ResourceManager": "4.0.0-beta-22913",
    "System.Runtime": "4.0.20-beta-22913",
    "System.Threading": "4.0.10-beta-22816"
}

"Microsoft.AspNet.Mvc.WebApiCompatShim/6.0.0-beta4": {
  "type": "package",
  "dependencies": {
    "Microsoft.AspNet.Mvc.Core": "6.0.0-beta4",
    "Microsoft.AspNet.Mvc.ModelBinding": "6.0.0-beta4",
    "Microsoft.AspNet.WebApi.Client": "5.2.2"
  }
```

**Comment by VikingsFan** [comment]
@encounter12 our project in myget is not updated for a long time, that version is for beta4, the newest version you can see in [here](https://github.com/OData/WebApi/tree/master/vNext), it's for newest version beta8, we didn't have plan to upload to myget recently, you can try that one with private build, any pull request is very welcome :)

**Comment by encounter12** [comment]
@VikingsFan I have cloned the OData WebApi vNext repository and tried to update its dependencies to the <a href="https://www.myget.org/gallery/aspnetvnext" target="_blank">latest nightly builds</a>, but there are many recent changes in AspNet vNext that break the OData code and I am not able to fix it for now. That is why, I will try to find a workaround. Thank you again very much for your reply and have a wonderful day!
