### ISSUE TITLE
AddEnumType only adds values not names

### ISSUE THREAD

**Issue by ghost** [OData/WebApi#538]
Given this enum
```csharp
public enum Color
{
	Red, Yellow, Green
}
```
And this model builder
```csharp
var builder = new ODataModelBuilder();
var colors = builder.AddEnumType(typeof(Color));
```
The following isn't valid
```url
...?$filter=ChosenColor eq Namespace.Color'Red'
```
However this is
```url
...?$filter=ChosenColor eq Namespace.Color'0'
```
In order to make queries by name work I have to do
```csharp
var builder = new ODataModelBuilder();
var colors = builder.AddEnumType(typeof(Color));
colors.AddMember(Color.Red).Name = "Red";
colors.AddMember(Color.Yellow).Name = "Yellow";
colors.AddMember(Color.Green).Name = "Green";
```
Perhaps it's a deliberate design decision. But I was expecting the names to work "out of the box" when using `AddEnumType`. Can that be done?

**Comment by congysu** [comment]
@esditm Can you use ODataConventionModelBuilder?

**Comment by esditm** [comment]
I have plans to switch to ODataConventionModelBuilder. But can't use it as this time :(

**Comment by xuzhg** [comment]
@ghost

If you use `var builder = new ODataModelBuilder();`, it's your responsibility to add the members of enum.
While, `ODataConventionModelBuilder` will take all the things automatically.

However, in non-convention model builder, you needn't to set the `Name` property.

That is:
```
colors.AddMember(Color.Red);
```
will set the name by call Enum.GetName(..) function.  See [here](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Builder/EnumMemberConfiguration.cs#L38)

Please re-open it if you have any further questions. Thanks.
