### ISSUE TITLE
There should be an API to control whether a unbound function/action is added as a FunctionImport/ActionImport.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#54]
There should be an API to control whether a unbound function/action is added
as a FunctionImport/ActionImport. And there should be an API to set the
FunctionImport/ActionImport name, because it may be not the same as the
function/action name.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1633](http://aspnetwebstack.codeplex.com/workitem/1633)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Jan 19, 2014 at 11:45 PM
**Reported by:**	jinfutan
**Updated on:**	Feb 24, 2014 at 2:35 AM
**Updated by:**	xuzhg

**Comment by LianwMS** [comment]
On *2014-02-13 12:16:07 UTC*, **xuzhg** commented:


There should be an API to control whether a function/action is added as a FunctionImport/FunctionImport.
it's already supported (or fixed). The bound action/function is created on entity type, such as the following sample codes:
ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
builder.Entity<Customer>().Function(...);
builder.Entity<Customer>().Action(...)
For this scenario, only function/action is created in Edm Model. No FunctionImport/ActionImport is added.
And there should be an API to set the FunctionImport/ActionImport name, because it may be not the same as the function/action name.
It's not necessary. The unbound action/function is created using the following sample codes:
ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
builder.Function(...);
builder.Action(...)
Here, users only care about the FunctionImport/ActionImport name, not the function/action name. Besides, unbound is only supported in attribute routing. The actual action name in controller can be any name what you want, even if the ODataRouteAttribute setting
 is correct. 

So, resolve it as won't fix.

**Comment by LianwMS** [comment]
On *2014-02-21 21:10:36 UTC*, **jinfutan** commented:

To be clear, change to a unbound function/action.

**Comment by LianwMS** [comment]
On *2014-02-21 21:17:17 UTC*, **jinfutan** commented:

and I'm ok to implement this in future release.

**Comment by LianwMS** [comment]
On *2014-02-24 10:35:18 UTC*, **xuzhg** commented:

For unbound function/action, I DONOT think so. Let's Postpone to vNext.

**Comment by xuzhg** [comment]
Resolved it as won't fix. Thanks.
