### ISSUE TITLE
Properties of type Entity not returning when calling Action / Post

### ISSUE THREAD

**Issue by ImGonaRot** [OData/WebApi#540]
Let's say there is a class called "Person" and there is another class called "Address".
Both of these are Entity Framework Entities (or even LINQ to SQL Entities).
Person has a Property called Address. It does not have to be a navigation property.
If I call the default GET on the Person controller and set the Address right before the return then I will notice that the JSON has the "Address" sent back to the user.
BUT if I create a custom Action Function and call the POST on the controller and set the Address right before the return, the JSON will not have "Address".

YET if I create a simple "Address" class the is not an Entity Framework Entity or even LINQ to SQL Entity, then the "POST" will return the "Address" in the JSON.

**Comment by xuzhg** [comment]
@ImGonaRot 

I can't understand that you create a custom Action Function and call the POST on  the controller.

Would you please share us your codes? about the models, edm model builder, controller, etc. That would be very help for us to dig the problem. Thanks a lot.

**Comment by xuzhg** [comment]
Close it. Please feel free to re-open it if you have further concern.
