### ISSUE TITLE
OData Query needs to error out based on ADO CommandTimeout Property

### ISSUE THREAD

**Issue by cwoodruff** [OData/WebApi#548]
We have a solution that is having issues when our OData queries are not adhering to the ADO CommandTimeout Property (which is the default 30 value). Is there a workaround or is this a really defect?

**Comment by TomDu** [comment]
Hi @cwoodruff , can you present some more detailed scenarios for your needs so we can check if we already have a solution add one, thanks.

**Comment by xuzhg** [comment]
Close it. Please re-open it if you have further concern.
