### ISSUE TITLE
ODataQueryOptions not working when trying to alter $filter

### ISSUE THREAD

**Issue by ImGonaRot** [OData/WebApi#555]
When a user passes the $filter on the URL to the controller and then at runtime we try to alter the $filter on the ODataQueryOptions, it does not work correctly.  
I have posted the issue here http://stackoverflow.com/questions/33660648/odata-v4-modify-filter-on-server-side

But here is some of the details.  

``` c#
[EnableQuery]
[HttpGet]
public IQueryable<Product> GetProducts(ODataQueryOptions<Product> queryOptions)
{
    if (queryOptions.Filter != null)
    {
        var url = queryOptions.Request.RequestUri.AbsoluteUri;
        string filter = queryOptions.Filter.RawValue;

        url = url.Replace("$filter=ID%20eq%201", "$filter=ID%20eq%202");
        var req = new HttpRequestMessage(HttpMethod.Get, url);

        queryOptions = new ODataQueryOptions<Product>(queryOptions.Context, req);
    }

    IQueryable query = queryOptions.ApplyTo(db.Products.AsQueryable());
    return query as IQueryable<Product>;
} 
```

Running this code will not return any product this is because the original query in the URL wanted product 1 and I swapped the ID filter of product 1 with product 2.
Now if I run SQL Profiler, I can see that it added something like "Select \* from Product WHERE ID = 1 AND ID = 2".

**BUT** if I try the same thing by replacing the $top then it works fine.

``` c#
[EnableQuery]
[HttpGet]
public IQueryable<Product> GetProducts(ODataQueryOptions<Product> queryOptions)
{
    if (queryOptions.Top != null)
    {
        var url = queryOptions.Request.RequestUri.AbsoluteUri;
        string filter = queryOptions.Top.RawValue;

        url = url.Replace("$top=2", "$top=1");
        var req = new HttpRequestMessage(HttpMethod.Get, url);

        queryOptions = new ODataQueryOptions<Product>(queryOptions.Context, req);
    }

    IQueryable query = queryOptions.ApplyTo(db.Products.AsQueryable());
    return query as IQueryable<Product>;
}
```

**Comment by VikingsFan** [comment]
Remove [EnableQuery] attribute, your scenario should work, because after using this attribute, OData/WebApi will apply your original query option after you return data in controller, if you already apply in your controller method, then you shouldn't use that attribute.

But if your query option contains $select, those code are not working because the result's type is not Product, we use a wrapper to represent the result of $select, so I suggest you use try this:

**Make a customized EnableQueryAttribute**

    public class MyEnableQueryAttribute : EnableQueryAttribute
    {
        public override IQueryable ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
        {
            // Don't apply Skip and Top.
            if (queryOptions.Filter != null)
            {
                var url = queryOptions.Request.RequestUri.AbsoluteUri;

                url = url.Replace("$filter=Id%20eq%201", "$filter=Id%20eq%202");
                var req = new HttpRequestMessage(HttpMethod.Get, url);

                queryOptions = new ODataQueryOptions(queryOptions.Context, req);
            }

            return queryOptions.ApplyTo(queryable);
        }
    }

**Use this attribute in your controller method**

    [MyEnableQueryAttribute]
    public IHttpActionResult Get()
    {
        return Ok(_products);
    }

Hope this can solve your problem, thanks!
Fan.

**Comment by ImGonaRot** [comment]
That almost worked. 
It did indeed alter the $filter command on the server but then it also broke the $select command. 
I can not longer use $select when a filter is applied. I get error "The EDM instance of type 'Product Nullable=True' is missing the property 'X'" Where 'X' is the property name I was trying to select. 
If I include all the properties in the $select then it seems to be working fine.

Seems that "new ODataQueryOptions<Product>(queryOptions.Context, req);" causes the issue.

The Product class has 3 properties. ID, Name, Description.
ID is Int64, Name is String, and Description is String.
If I do "$select=ID&$filter=ID eq 1" then it throws error "The EDM instance of type 'Product Nullable=True' is missing the property 'Name'".
*BUT* if I use "$select=ID,Name,Description&$filter=ID eq 1" then it works fine.

**Comment by VikingsFan** [comment]
@ImGonaRot I modified my code, add 
    
    queryOptions.Request.ODataProperties().SelectExpandClause = queryOptions.SelectExpand.ProcessLevels();

before modify the queryOptions, because we need Request's SelectExpandClause which will lose in my code.

**Comment by ImGonaRot** [comment]
The "ProcessLevels" method is marked "internal / private". 
https://github.com/OData/WebApi/blob/3a3ef57fc7f9c36445f3ea2929269b15ff3f32f1/OData/src/System.Web.OData/OData/Query/SelectExpandQueryOption.cs

**Comment by ImGonaRot** [comment]
Even when I copied all the "ProcessLevels" into my class this still throws the "The EDM instance of type 'Product Nullable=True' is missing the property 'X'" error.

I copied all the "ProcessLevels" and added this code.
```C#
public override IQueryable ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
{
    // Don't apply Skip and Top.
    if (queryOptions.Filter != null)
    {
        var url = queryOptions.Request.RequestUri.AbsoluteUri;

        url = url.Replace("$filter=ID%20eq%201", "$filter=ID%20eq%202");
        var req = new HttpRequestMessage(HttpMethod.Get, url);

        var currentSelect = queryOptions.SelectExpand.SelectExpandClause;
        queryOptions = new ODataQueryOptions(queryOptions.Context, req);

        queryOptions.Request.ODataProperties().SelectExpandClause = ProcessLevels(currentSelect);
    }

    return queryOptions.ApplyTo(queryable);
}

// NOTE: This was copied from System.Web.OData.Query.SelectExpandQueryOption class 
// since it was marked internal.  
// I also copied all the other "ProcessLevels" methods to get this to run.
internal SelectExpandClause ProcessLevels(SelectExpandClause selectExpandClause)
{
    bool levelsEncountered;
    bool isMaxLevel;
    return ProcessLevels(selectExpandClause,
        10, // TEST number since the variables are also internal
        out levelsEncountered,
        out isMaxLevel);
}
```

As a side note:
```C#
// The following will return NULL even before calling the ApplyQuery method.
queryOptions.Request.ODataProperties().SelectExpandClause

// But the following will return a SelectExpandClause before calling the ApplyQuery method.
queryOptions.SelectExpand.SelectExpandClause
```

**Comment by VikingsFan** [comment]
@ImGonaRot you modified the new queryOptions.Request(create by your code and scope is in queryOption), what I mean is modify the original queryOptions.Request(scope is global). 
Please see my code carefully, or you can just apply the origin query option first, then the global Request get SelectExpandClause, everything is working.

    if (queryOptions.Filter != null)
    {
          queryOptions.ApplyTo(queryable);   //apply first
          var url = queryOptions.Request.RequestUri.AbsoluteUri;

          url = url.Replace("$filter=Id%20eq%202", "$filter=Id%20eq%201");
          var req = new HttpRequestMessage(HttpMethod.Get, url);

          queryOptions = new ODataQueryOptions(queryOptions.Context, req);
    }
    return queryOptions.ApplyTo(queryable);

**Comment by ImGonaRot** [comment]
@VikingsFan That worked. Thanks.

**Comment by ImGonaRot** [comment]
After trying the solution listed above I noticed that $count=true does not work correctly.

If I apply ODataQuerySettings with PageSize = 10 right before the "return queryOptions.ApplyTo(queryable, ODataQuerySettings)", I get a result set but the odata has "@odata.count": 0

Any idea how to get PageSize with count to work when using the above solution?

**Comment by VikingsFan** [comment]
Can you show your customize EnableQueryAttribute? I tried added pagesize in previous code and odata.count is working correctly.

    queryOptions.ApplyTo(queryable, new ODataQuerySettings{PageSize = 10})

**Comment by ImGonaRot** [comment]
My EnableQueryAttribute is the exact same as the one posted
```
/// <summary>
/// Used to create custom filters, selects, groupings, ordering, etc...
/// </summary>
public class MyEnableQueryAttribute : EnableQueryAttribute
{
	public override IQueryable ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
	{
		if (queryOptions.Filter != null || queryOptions.Top == null) {
			// apply the query options before they get reset
			queryOptions.ApplyTo(queryable);

			// get the current URL
			dynamic url = queryOptions.Request.RequestUri.AbsoluteUri;

			// rebuild the URL if it contains a specific filter
			if (queryOptions.Filter != null) {
				url = url.Replace("$filter=ID%20eq%200", "$filter=ID%20ne%200");
			}

			dynamic req = new HttpRequestMessage(HttpMethod.Get, url);

			// reset the query options with the new request
			queryOptions = new ODataQueryOptions(queryOptions.Context, req);
		}

		// apply the query options
		return queryOptions.ApplyTo(queryable, new ODataQuerySettings { PageSize = 10 });
	}
}
```
And then on the URL I call it like this.
?$filter=ID%20eq%20%270%27&$count=true

This should select all records where ID != 0
If I comment out the url.Replace then the count does work assuming I had a lot of records where ID == 0...

**Comment by VikingsFan** [comment]
@ImGonaRot that's because $count result is also bound to Original request, I updated your code inline, please have a try.

**Comment by ImGonaRot** [comment]
Wow that was almost perfect. It does indeed return the count now but it does not act like a normal method that is decorated with "EnableQuery".
A normal method with the "EnableQuery(PageSize=10)" will also return "@odata.nextLink". 
Not that I am complaining.
But do you know if it is possible to get the "nextLink" to work?

I tried something like this in the controller.
```
[MyEnableQueryAttribute()]
[HttpGet()]
public PageResult<Product> GetProducts(ODataQueryOptions<Product> queryOptions)
{
	return new PageResult<Product>(db.Products as IEnumerable<Product>, Request.ODataProperties().NextLink, Request.ODataProperties().TotalCount);
}
```
but that return no results.
I have a feeling the will require a lot more code.
Let me know if it is not possible or if it is to much effort.

**Comment by VikingsFan** [comment]
it's also need to set into original request, Request.ODataProperties().NextLink, do this the same as count

**Comment by ImGonaRot** [comment]
Worked great.
Thanks for the help.

**Comment by ImGonaRot** [comment]
Here is my final solution.
```c#
using System.Net.Http;
using System.Web.OData;
using System.Web.OData.Extensions;
using System.Web.OData.Query;

/// <summary>
/// Used to create custom filters, selects, groupings, ordering, etc...
/// </summary>
public class CustomEnableQueryAttribute : EnableQueryAttribute
{
	public override IQueryable ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
	{
		IQueryable result = default(IQueryable);

		// get the original request before the alterations
		HttpRequestMessage originalRequest = queryOptions.Request;

		// get the original URL before the alterations
		string url = originalRequest.RequestUri.AbsoluteUri;

		// rebuild the URL if it contains a specific filter for "ID = 0" to select all records
		if (queryOptions.Filter != null && url.Contains("$filter=ID%20eq%200")) 
        {
			// apply the new filter
			url = url.Replace("$filter=ID%20eq%200", "$filter=ID%20ne%200");

			// build a new request for the filter
			HttpRequestMessage req = new HttpRequestMessage(HttpMethod.Get, url);

			// reset the query options with the new request
			queryOptions = new ODataQueryOptions(queryOptions.Context, req);
		}

		// set a top filter if one was not supplied
		if (queryOptions.Top == null) 
        {
			// apply the query options with the new top filter
			result = queryOptions.ApplyTo(queryable, new ODataQuerySettings { PageSize = 100 });
		} 
        else 
        {
			// apply any pending information that was not previously applied
			result = queryOptions.ApplyTo(queryable);
		}

		// add the NextLink if one exists
		if (queryOptions.Request.ODataProperties().NextLink != null) 
        {
			originalRequest.ODataProperties().NextLink = queryOptions.Request.ODataProperties().NextLink;
		}
		// add the TotalCount if one exists
		if (queryOptions.Request.ODataProperties().TotalCount != null) 
        {
			originalRequest.ODataProperties().TotalCount = queryOptions.Request.ODataProperties().TotalCount;
		}

		// return all results
		return result;
	}
}
```

**Comment by ImGonaRot** [comment]
I'm sorry to bother you again but ...
How do you force the CustomEnableQueryAttribute to always be called?

Basically I added code in the CustomEnableQueryAttribute that checks to see if there was a "Top" in the query and if not, I set a default page size to 100 records. (see code above)
What I didn't realize was that the CustomEnableQueryAttribute is only called if there is an odata parameter on the the URL.

Example:
http://test.com/Products() does not cause the CustomEnableQueryAttribute to fire
http://test.com/Products()?count=true does cause the CustomEnableQueryAttribute  to fire

**Comment by VikingsFan** [comment]
EnableQuery Attribute can only be fired when there is a query option, you can use [MyEnableQueryAttribute(PageSize=100)] for non query option situation

**Comment by ImGonaRot** [comment]
[MyEnableQueryAttribute(PageSize=100)] doesn't seem to do anything.
When I set PageSize on a normal controller then it seems to work but when I and this to my custom attribute, it does not seem to do anything.
In the "MyEnableQueryAttribute" method, I look at the "queryOptions.Top" but it is "null"

**Comment by VikingsFan** [comment]
[MyEnableQueryAttribute(PageSize=100)] won't set queryOptions.Top, it set the querySetting's pageSize, it will truncate the as the code: https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Query/ODataQueryOptions.cs#L357-L366

**Comment by ImGonaRot** [comment]
Thanks for the information but [MyEnableQueryAttribute(PageSize=100)] is not setting a pagesize on the return results. 
I set the following [MyEnableQueryAttribute(PageSize=1)] and hoped to get "1" result yet the result set was not one.
It is almost like the MyEnableQueryAttribute method needs to somehow reapply the pagesize before the return.

In MyEnableQueryAttribute if the last line is "return queryOptions.ApplyTo(queryable, new ODataQuerySettings() { PageSize = 1 })" then it does work.

When I am in the MyEnableQueryAttribute method, how can I grab the original QuerySettings?

**Comment by VikingsFan** [comment]
there seems no interface for Get querySetting in EnableQueryAttribute it's private, but you can get the pageSize through https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/EnableQueryAttribute.cs#L151-L161

**Comment by rootn3rd** [comment]
I am using the above class to modify some aspect of the incoming request parameter. However, the query.ApplyTo(....);  doesn't handle the $select and other odata operators.

Has anyone faced a similar issue before?

**Comment by VikingsFan** [comment]
@rootn3rd can you open another issue and show your code and detail information?

**Comment by rootn3rd** [comment]
@VikingsFan sure thing! Thanks.

**Comment by 9Rune5** [comment]
Having been misled by the code presented in this discussion, I have to ask: Why not (after modifying the requesturi as needed) simply call the overriden base method? The base method is the only code that can access the querysettings object...

**Comment by ImGonaRot** [comment]
This is no longer working in OData. 
When I use this code 
`queryOptions = new ODataQueryOptions(queryOptions.Context, req);`
NOTE: req is System.Net.Http.HttpRequestMessage

I get this error:

> An exception of type 'System.ArgumentException' occurred in System.Web.OData.dll but was not handled in user code. Additional information: Request message does not contain an HttpConfiguration object.

**Comment by xuzhg** [comment]
Close it because the origin problems resolved. Please file a new issue if you have further concern. Thanks.
