### ISSUE TITLE
[ODataAttrRouting] $value support requires adding a route for it

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#56]
_ Scenario _ : I am using OData Attribute routing on a property of an entity  
  
Currently I need to have 2 routes for support regular request and $value based
one, otherwise I get a 404 when i make a request for $value  

    
    
            [ODataRoute("Customers({key})/Name")]
            [ODataRoute("Customers({key})/Name/$value")]
            public async Task<IHttpActionResult> GetCustomerName(int key)
            {
                Customer customer = await context.Customers.FindAsync(key);

Ideally I would expect that specifying only the following route should be
sufficient.  

    
    
            [ODataRoute("Customers({key})/Name")]
            public async Task<IHttpActionResult> GetCustomerName(int key)
            {
                Customer customer = await context.Customers.FindAsync(key);

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1647](http://aspnetwebstack.codeplex.com/workitem/1647)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jan 25, 2014 at 12:01 AM
**Reported by:**	kichalla
**Updated on:**	Jan 27, 2014 at 6:06 AM
**Updated by:**	zjufish

**Comment by LianwMS** [comment]
On *2014-01-25 08:29:28 UTC*, **dougbu** commented:

Agree usability could be improved here. But the current situation is better than implicitly supporting …/Customers(23)/Name/$value or …/Customers(23)/Name/$ref when the user only specified “…/Customers/({key})/Name” in their template. We should not enable
 options the user hasn’t explicitly requested.

That said it’s worth talking about a feature to add something like a "next segment" bitmask property to the
[ODataRoute] attribute.

**Comment by xuzhg** [comment]
Close it. Please file a new issue if you have any concern.
