### ISSUE TITLE
ETag support requires having at least one structural versioned property.

### ISSUE THREAD

**Issue by TarkanSevilmis** [OData/WebApi#561]
ETag is used for all versioning purposes, however, existing eTag mechanics through etag handler and ConcurrencyCheck  attributes require exposing a structural property which is used to create the eTag value. This model would work fine when the versioning is entirely based on the data, since the data is the version, however it does not work well when the service keeps track of a version number separate from the data. In the latter case, services are required to expose the internal version field, despite the field being unusable by the clients of the service.

**Comment by congysu** [comment]
You can override how an ETag is created in the serializer:
https://github.com/OData/WebApi/blob/f4573605bd88dabe882c4dc45e4a4ed0e55b32e0/OData/src/System.Web.OData/OData/Formatter/Serialization/ODataEntityTypeSerializer.cs#L279

Default implementation is based on the vocabulary annotation:
```xml
<Term Name="OptimisticConcurrency" Type="Collection(Edm.PropertyPath)" AppliesTo="EntitySet">
<Annotation Term="Core.Description" String="Data modification requires the use of Etags. A non-empty collection contains the set of properties that are used to compute the ETag"/>
</Term>
```

**Comment by xuzhg** [comment]
Close it because workaround provided. Please re-open it if you have further concern. Thanks.
