### ISSUE TITLE
Base.AddEntityType()/AddComplexType() calls in ODataConventionModelBuilder do not return typeconfiguration with exposed properties.

### ISSUE THREAD

**Issue by chinese007** [OData/WebApi#564]
I'm trying to extend the ODataConvertionModelBuilder.cs to allow customized property attribute to be honored when generating OData data model.

My sample code looks like:

   public override EntityTypeConfiguration AddEntityType(Type type)
        {
            var entityTypeConfig = base.AddEntityType(type);
            foreach (var propertyConfig in entityTypeConfig.Properties.Where(p => p is PrimitivePropertyConfiguration))
            {
                if (IsKeyProperty(type, propertyConfig as PrimitivePropertyConfiguration))
                {
                    entityTypeConfig.HasKey(propertyConfig.PropertyInfo);
                }

                SetPrimitivePropertyAsOptionalOrRequired(type, propertyConfig as PrimitivePropertyConfiguration);
            }

            return entityTypeConfig;
        }

However, I found the returned "entityTypeConfig.Properties" from base.AddEntityType(type) call is always empty. This would make customization scenario to be broken. Hopefully, this can be addressed ASAP.

Thanks,
James

**Comment by xuzhg** [comment]
@chinese007 

When you call AddEntityType() or EntityType<T>() while will call AddEntityType(), it only register an entity type in the model builder. This time, no property is discovered until you call builder.GetEdmModel();

So, the it's correct that entityTypeConfig.Properties is empty. You can follow up the similar codes in https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Builder/ODataConventionModelBuilder.cs#L593-L637 to fetch the properties by yourself.

Hope it can help.
