### ISSUE TITLE
Issue with deepexpand when i have set MaxExpansionDepth

### ISSUE THREAD

**Issue by NicoJuicy** [OData/WebApi#567]
I have the following url with odata v4 WebApi 2.2

    http://my-url/odata/Routes(9cbaab82-1245-4015-a106-66c440a751fa)?$expand=Trajects($expand=FromPoi($expand=Tag))

This is my routeController

    [EnableQuery(MaxExpansionDepth =4)]
    public IQueryable<Route> GetRoutes()
    {
        return db.Routes;
    }

But why does it return:

    {
    "error":{
    "code":"","message":"The query specified in the URI is not valid. The request includes a $expand path which is too deep. The maximum depth allowed is 2. To increase the limit, set the 'MaxExpansionDepth' property on EnableQueryAttribute or ODataValidationSettings.","innererror":{
      "message":"The request includes a $expand path which is too deep. The maximum depth allowed is 2. To increase the limit, set the 'MaxExpansionDepth' property on EnableQueryAttribute or ODataValidationSettings.","type":"Microsoft.OData.Core.ODataException","stacktrace":"   at System.Web.OData.Query.Validators.SelectExpandQueryValidator.ValidateDepth(SelectExpandClause selectExpand, Int32 maxDepth)\r\n   at System.Web.OData.Query.Validators.SelectExpandQueryValidator.Validate(SelectExpandQueryOption selectExpandQueryOption, ODataValidationSettings validationSettings)\r\n   at System.Web.OData.Query.SelectExpandQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at System.Web.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at System.Web.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at System.Web.OData.EnableQueryAttribute.ValidateQuery(HttpRequestMessage request, ODataQueryOptions queryOptions)\r\n   at System.Web.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor)\r\n   at System.Web.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)"
    }
    }
    }

Could this be a bug of some sort?

I have the following in my WebApiConfig:

    
        public static void Register(HttpConfiguration config)
        {
            // Web API configuration and services
            // Configure Web API to use only bearer token authentication.

            config.EnableCors();

            // Web API routes
            config.MapHttpAttributeRoutes();

            config.SuppressDefaultHostAuthentication();
            config.Filters.Add(new HostAuthenticationFilter(OAuthDefaults.AuthenticationType));

            ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
            builder.EntitySet<Traject>("Trajects");
            builder.EntitySet<POI>("Pois");
            builder.EntitySet<Route>("Routes");
            builder.EntitySet<Device>("Devices");
            builder.EntitySet<Tag>("Tags");

            /*builder.EntityType<Route>().ContainsMany<Traject>(el => el.Trajects);
            builder.EntityType<Traject>().HasRequired<POI>(el => el.FromPoi);
            builder.EntityType<Traject>().HasRequired<POI>(el => el.ToPoi);
            builder.EntityType<POI>().HasOptional<Tag>(el => el.Tag);
            */
            config.MapODataServiceRoute("odata", "odata", builder.GetEdmModel());

            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
        }

**Comment by VikingsFan** [comment]
Hi @NicoJuicy With version of OData/WebApi are you using(latest is v5.8-beta)? we do have [case](https://github.com/OData/WebApi/blob/master/OData/test/E2ETest/WebStack.QA.Test.OData/DollarLevels/DollarLevelsTest.cs#L154-L179) to cover this scenario.

**Comment by Josephdias92** [comment]
i tried updating odata to v5.8 beta but its still not working.
its not serializing the data after 2 levels.

**Comment by VikingsFan** [comment]
your url is ....Routes(9cbaab82-1245-4015-a106-66c440a751fa)  it's like you should add the attribute in the controller method:

    [EnableQuery(MaxExpansionDepth =4)]
    public Route Get(Guid key)

**Comment by xuzhg** [comment]
@NicoJuicy @Josephdias92 

As Fan said, Your request is query single entity, Web API OData will route to "Get" method with key. So, please check your MaxExpansionDepth setting is put on the correct method. Thanks.

Please reopen it if you find any more concern. Thanks.

**Comment by NicoJuicy** [comment]
@xuzhg @VikingsFan sorry for not following up. I only saw the notification today.

I worked arround it by splitting it up in a  different API call.
