### ISSUE TITLE
Make KeyValueParser.ParseKeys support more format in OData Uri BNF

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#57]
Make the method ` KeyValueParser.ParseKeys ` support more format in OData Uri
BNF.  
  
For example, this parser won't handle the "JSON format for function
parameters" (section 5 of [ http://docs.oasis-
open.org/odata/odata/v4.0/cos01/abnf/odata-abnf-construction-rules.txt
](http://docs.oasis-open.org/odata/odata/v4.0/cos01/abnf/odata-abnf-
construction-rules.txt) ) correctly. Treats commas within an array as key
separators, can't parse a double-quoted string, et cetera.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1656](http://aspnetwebstack.codeplex.com/workitem/1656)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jan 28, 2014 at 3:03 AM
**Reported by:**	fenzhao
**Updated on:**	Feb 11, 2014 at 2:06 AM
**Updated by:**	zjufish

**Comment by LianwMS** [comment]
On *2014-01-31 09:15:12 UTC*, **fenzhao** commented:

This parser can not support parameter alias
for example: @argument=['hello','world']

**Comment by sanderej** [comment]
The OData client code generator (http://www.asp.net/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/create-an-odata-v4-client-app) sends objects in the URLs through this alias method. Because of this bug, we can't accept any objects as parameters in our GET functions because Web API can't parse the request.

**Comment by xuzhg** [comment]
Function parameter is not using "KeyValueParser.ParseKeys".

@sanderej would you please share us more information about your problem?

**Comment by xuzhg** [comment]
Close it. Please file a new issue if you have further concern. Thanks.
