### ISSUE TITLE
Clarify the situation for streams.

### ISSUE THREAD

**Issue by OnurGumus** [OData/WebApi#574]
Despite reading all the docs and samples, I still am not sure answer. Are entities with Stream properties supported ? If so any documentation or samples?

**Comment by VikingsFan** [comment]
Now we just support declare a entity as stream, Issue: https://github.com/OData/WebApi/issues/149 Doc:http://odata.github.io/WebApi/#06-04-streamEntity

**Comment by ReverseBlade** [comment]
Is there any working sample anywhere  ?, I can't figure how do I make use of this from the link you suggested. In that example does Vehicle has a property like stream or byte array ?  Is there any difference in controller ? How does Vehicle's controller look like? do I have to make use of a MediaTypeFormatter ?

**Comment by VikingsFan** [comment]
About working sample, related issue：https://github.com/OData/WebApi/issues/328

**Comment by ReverseBlade** [comment]
Thanks, though I have already reviewed all of these, including the blog post from 2013 and that new FileServer code. Unfortunately non of them makes use of that MediaType() method call.

**Comment by ivanko2000** [comment]
I second that request. I too need to implement support for media resources and although there are indications that this is now supported, I just can't seem to figure it out, even though I also did review all available relevant content, including the code in https://github.com/vojtechvit/ODataFileServer

I would appreciate any pointers into the minimal viable use of the feature described in http://odata.github.io/WebApi/#06-04-streamEntity

**Comment by ivanko2000** [comment]
Pinging this as 'still relevant' in case anyone is listening... :)

**Comment by agrabhi** [comment]
Totally confused how to use a stream entity

**Comment by NetTecture** [comment]
Cna someone pick this up and at least add some basic documentation?

Note that the links http://odata.github.io/WebApi/#06-04-streamEntity which was given on April 23rd 2016 is no longe rworking at all because of the new documentation. Which is significantly improoved, EXCEPT it removed all but the most basic information - there is now NO mention of streams like at all anymore.

**Comment by julealgon** [comment]
Any news here? I'm also interested in having a stream property in one of our entities.
