### ISSUE TITLE
the $skip and $top query options allow arithmetic overflows

### ISSUE THREAD

**Issue by m7milan** [OData/WebApi#578]
example: a get request to a collection with the following query option will cause an overflow:
$top=55555555555

Looking at TopQueryOption.cs and SkipQueryOption.cs
I see that the issue is due to how the Value property is calculated. A try parse should be used, or maybe a checked block.

**Comment by xuzhg** [comment]
@m7milan 

There is an assert code as: 

`Contract.Assert(topValue.Value <= Int32.MaxValue);`

Does the `$top=55555555555` make sense?

I know the issue happens at `_value = (int?)topValue;`, but what result should be return after try parse?

**Comment by m7milan** [comment]
@xuzhg 
Greetings, I am looking at [this SkipQueryOption.cs](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.Http.OData/OData/Query/SkipQueryOption.cs)

Specifically the get of the Value property:
`
 
                    try
                    {
                        _value = Convert.ToInt32(RawValue, CultureInfo.InvariantCulture);
                    }
    
`
take a looka at the RawValue and Value in this  [screenshot](http://prntscr.com/9yec4z)

From what I can see, that should be in a `checked` block, or a try parse.

I refer you to section 7.6.12 of the C# specification, a portion of which I reproduce here for your convenience:

> For non-constant expressions (expressions that are evaluated at run-time) that are not enclosed by any checked or unchecked operators or statements, the default overflow checking context is unchecked unless external factors (such as compiler switches and execution environment configuration) call for checked evaluation.

**Comment by xuzhg** [comment]
1. Throw as early as fast
2. use MaxValue.

**Comment by VikingsFan** [comment]
368278e
