### ISSUE TITLE
AllowedOrderByProperties should support paths

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#58]
AllowedOrderByProperties doesn't make sense when the $orderby clause is
something like Entity/NavigationProperty/ComplexType/Field which is a clause
we support.  

Change the attribute name to allow explicitly supporting paths, for example  
AllowedOrderByPaths= "$it/NavigationProperty/ComplexType/Field,
$it/OtherProperty" would allow the user to Orderby those two paths only.  

Another option would be to define the max orderby/filter path depth if there
is none (which I couldn't find)  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1677](http://aspnetwebstack.codeplex.com/workitem/1677)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Feb 11, 2014 at 12:54 AM
**Reported by:**    jacalvar
**Updated on:** May 12, 2014 at 9:19 AM
**Updated by:** azhou

**Comment by ArturAdam** [comment]
has this been resolved?
