### ISSUE TITLE
Array of enum doesn't work for convention model builder

### ISSUE THREAD

**Issue by xuzhg** [OData/WebApi#581]
If a model only includes array of enum property, the convention model builder will be failed.
For example:
```C#
public enum Color
{
  Red,
  Green
}
public class Customer
{
  public int Id {get;set;}
  public Color[] Colors {get;set;}
}

var builder = new ODataConventionModelBuilder()
builder.EntityType<Customer>();
IEdmModel model = builder.GetEdmModel();
```

`GetEdmModel()` will throw "The enum type 'Color' does not exist."

However, if we change `Color[]` as `IList<Color>`, it works fine. Please investigate and fix.

**Comment by VikingsFan** [comment]
PR #582  Merged 8b99db1a012c7931bba3e668f271d8aed61c215c
