### ISSUE TITLE
Make ApiDescription.ResponseDescription setter public

### ISSUE THREAD

**Issue by rustd** [OData/WebApi#587]
This was opened on the ASP.NET UserVoice site. https://aspnet.uservoice.com/forums/147201-asp-net-web-api/suggestions/9277539-make-apidescription-responsedescription-setter-pub

I am copying the details on the OData project. Please triage as appropiate.

It is impossible to provide a custom implementation of IApiExplorer because the setter for ApiDescription.ResponseDescription is internal. Please either make the setter public (or make the interface internal).

**Comment by xuzhg** [comment]
@rustd Are you sure it is related to Web API OData?

**Comment by xuzhg** [comment]
Close it. Please re-open it if you have further concern. Thanks.
