### ISSUE TITLE
Provide a built-in parameter binding for Key-value pairs

### ISSUE THREAD

**Issue by rustd** [OData/WebApi#588]
This was opened on the ASP.NET UserVoice site. https://aspnet.uservoice.com/forums/147201-asp-net-web-api/suggestions/3227380-provide-a-built-in-parameter-binding-for-key-value

I am copying the details on the OData project. Please triage as appropiate.

Right now to support OData URIs with multiple parameters, you need to parse the string yourself and extract the key/value pairs. This can be consolidated with a custom parameter binding, but given that this is part of the OData standard it would be helpful to offer this capability as part of the platform rather than having all of us author our own.

**Comment by xuzhg** [comment]
@rustd  

There is built-in parameter binding in Web API for function parameter.  For example:

`~/odata/Customers(1)/Default.GetName(name='abc')`

It will bind the 'abc' to the function parameter in the controller. So, the `name` parameter in the following function will have the 'abc' value.
```C#
public IHttpActionResult GetName([FromODataUri]string name)
{
   ...
}
```
For action parameter, it's same as function parameter, however, all parameters are saved into a Dictionary named [ODataActionParameters](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/ODataActionParameters.cs#L16).

Can you help us understand what's the multiple parameters in your question?

**Comment by xuzhg** [comment]
Close it. Please reopen it if you have further concern.
