### ISSUE TITLE
Remove ambiguity from the interface of ODataQueryOptions

### ISSUE THREAD

**Issue by rustd** [OData/WebApi#589]
This was opened on the ASP.NET UserVoice site. https://aspnet.uservoice.com/forums/147201-asp-net-web-api/suggestions/5894868-remove-ambiguity-from-the-interface-of-odataqueryo

I am copying the details on the OData project. Please triage as appropiate.
Most of the interface exposed via ODataQueryOptions presents only get accessors and appears to be immutable.

However, the OrderByQueryOption presents a mutable collection of OrderByNode that can be changed.

See here, 
http://stackoverflow.com/questions/23512076/can-i-change-the-odataqueryoptions-used-for-my-odatacontrollers-request

Changes to the collection appear to have no effect on the processing of the ODataController.

Please could you either,

Make the collection read-only.

or preferabley,

make it obvious how to use the interface to affect changes to processing later in the pipeline.

**Comment by VikingsFan** [comment]
Current we are not recommended to use [EnableQuery] and pass ODataQueryOptions in controller method together, use one of them can solve this issue, answer is already in your stackoverflow link and  also this is another approach http://stackoverflow.com/questions/33660648/odata-v4-modify-filter-on-server-side/33684667#33684667 .
