### ISSUE TITLE
Provide support for referential constraints in the ModelBuilder and when using ForeignKeyAttribute and InversePropertyAttribute

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#59]
This workitem tracks the remaining work of [
https://aspnetwebstack.codeplex.com/workitem/1423
](https://aspnetwebstack.codeplex.com/workitem/1423) as the changes in the
model builder required to support referential constraints, ForeignKeyAttribute
and InversePropertyAttribute are out of scope of the bug.  

Basically we currently build the model in the following way:  

We build the type headers.  
We build the properties (navigation and structural at the same time)  

In order to support adding referential constraints we should build the model
the following way:  

Build the type headers.  
Build the structural properties for all types.  
Build the navigation properties for all types.  

It will require extending the default ODataModelBuilder to allow specifying
principal and dependent properties of the relationship, and a convention on
the ODataConventionModelBuilder to support ForeignKeyAttribute and
InversePropertyAttribute, for example  

```
public class Customer
{
    public int Id { get; set; }
    public ICollection<Order> { get; set;}
}

public class Order
{
    public int Id { get; set; }
    public int CustomerId { get; set; }
    [Association(IsForeignKey=true, ThisKey="CustomerId", OtherKey="Id")]
    public Customer { get; set; }
}
```

Would result in a navigation property being created for the given entity that
specifies the referential constraint in the $metadata  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1684](http://aspnetwebstack.codeplex.com/workitem/1684)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Feb 14, 2014 at 12:02 AM
**Reported by:**    jacalvar
**Updated on:** Aug 11, 2014 at 11:05 PM
**Updated by:** jtraband

**Comment by LianwMS** [comment]
On *2014-05-01 00:06:24 UTC*, **lybax** commented:

Referential constraints are essential in a model!
This workitem could be linked to 
https://aspnetwebstack.codeplex.com/workitem/1094

**Comment by joshbooker** [comment]
Would also fix the following issue?

https://aspnetwebstack.codeplex.com/workitem/623

Is there a workaround to create bi-directional nav props in ODataV3 in the meantime?
