### ISSUE TITLE
[vNext] 'Microsoft.OData.Core.ODataContentTypeException' - when targeting aspnet-5-rc1-update1

### ISSUE THREAD

**Issue by grahamehorner** [OData/WebApi#597]
An exception of type 'Microsoft.OData.Core.ODataContentTypeException' occurred in Microsoft.OData.Core.dll but was not handled in user code

Additional information: A supported MIME type could not be found that matches the content type of the response. None of the supported type(s) 'application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false, application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true, application/json;odata.metadata=minimal;odata.streaming=true, application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false, application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true, application/json;odata.metadata=minimal;odata.streaming=false, application/json;odata.metadata=minimal;IEEE754Compatible=false, application/json;odata.metadata=minimal;IEEE754Compatible=true, application/json;odata.metadata=minimal, application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false, application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true, application/json;odata.metadata=full;odata.streaming=true, application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false, application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatib...' matches the content type 'application/xml; charset=utf-8'.

**Comment by PinpointTownes** [comment]
This exception is due to a breaking change in ASP.NET 5, that causes an incorrect formatters ordering. `ODataServiceCollectionExtensions.AddOData` must be fixed to react to this change.

You can replace...

```
foreach (var outputFormatter in ODataOutputFormatters.Create())
{
    options.OutputFormatters.Insert(0, outputFormatter);
}
```
... by:

```
var formatters = ODataMediaTypeFormatters.CreateOutputFormatters();
for (var index = 0; index < formatters.Count; index++)
{
    options.OutputFormatters.Insert(0 + index, formatters[index]);
}
```

https://github.com/OData/WebApi/blob/vNext/vNext/src/Microsoft.AspNet.OData/Extensions/ODataServiceCollectionExtensions.cs#L23-L26

**Comment by grahamehorner** [comment]
The above fix breaks the $metadata controller ?

**Comment by onionhammer** [comment]
I see a workaround here, not a fix
