### ISSUE TITLE
ODataRoute should accept an interface instead of ODataPathRouteConstraint

### ISSUE THREAD

**Issue by karunasagark** [OData/WebApi#601]
The constructor of ODataRoute() accepts an object of type ODataPathRouteConstraint. However, this causes tight coupling.
Consider a multi-model typeless routing system. In this case, we would want to customize the routeConstraint to select the appropriate model. This is hard because ODataRoute() accepts ODataPathRouteConstriant, which forces us to create a subclass and duplicate the private logic internal to ODataPathRouteConstraint.
If ODataRoute() accepted an interface, say IHttpRouteConstraint, it would cause a cleaner design using composition.

**Comment by xuzhg** [comment]
Hi, @karunasagark 
Would you please take a look the PR: #604? And Let me know any concern. 

Thanks.
Sam

**Comment by xuzhg** [comment]
Fixed at 5ebfb93f7b8e0a524426104a15f96f10024bb754
