### ISSUE TITLE
Globally registered OData Formatters prevent succeeding OWIN middleware from running properly

### ISSUE THREAD

**Issue by vojtechvit** [OData/WebApi#603]
If you register Web API OData v4 Formatters globally in an OWIN web application when creating WebApi `HttpConfiguration` object to set-up Web API OWIN middleware like this:

    // Note: removing default Json an Xml formatters is enough
    httpConfiguration.Formatters.Clear();
    httpConfiguration.Formatters.AddRange(ODataMediaTypeFormatters.Create());

The Web API middleware will return response (`406 Not Acceptable`) even if the URL does not match any Web API controller/action, which effectively prevents any succeeding OWIN middleware from running and serving the request.

**Comment by xuzhg** [comment]
Hi, @vojtechvit 

Does the workaround in https://github.com/xuzhg/WebApiSample/commit/ab100f23668dfd9262fd539316ceaeae95be967a can help you?

**Comment by vojtechvit** [comment]
Hi @xuzhg, yes, the workaround works well :-)

**Comment by xuzhg** [comment]
@vojtechvit

You are welcome. I closed this issue. please re-open it or file a new one if you have any further concern.
