### ISSUE TITLE
Single quote is sent to the parameter in unbound function

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#61]
Function define:  

    
    
    [HttpGet]
    [ODataRoute("GetSalesTaxRate(state={state})")]
    public IHttpActionResult GetSalesTaxRate(string state)
    {
        return Ok(GetRate(state));
    }

Model define:  

    
    
    // Unbound Function
    builder.Function("GetSalesTaxRate").Returns<double>().Parameter<string>("state");

Send request:  

    
    
    GET http://<siteurl>/odata/GetSalesTaxRate(state='CA')

The actual value send to parameter state is  

    
    
    'CA'

What expected is  

    
    
    CA

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1734](http://aspnetwebstack.codeplex.com/workitem/1734)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	xuzhg
**Reported on:**	Feb 28, 2014 at 7:47 PM
**Reported by:**	trdai
**Updated on:**	Jul 3, 2014 at 5:18 AM
**Updated by:**	azhou

**Comment by LianwMS** [comment]
On *2014-03-03 13:27:07 UTC*, **xuzhg** commented:

Try to add the [FromODataUri] before the parameter as: 

public IHttpActionResult FunctionName([FromODataUri]string state) 
{ 
... 
}

**Comment by LianwMS** [comment]
On *2014-03-03 14:56:31 UTC*, **azhou** commented:

The workaround for now is to add [FromODataUri] attribute in the key parameter. Move it to 5.2 RTM.


public IHttpActionResult GetSalesTaxRate([FromODataUri]string state)

**Comment by LianwMS** [comment]
On *2014-05-05 15:09:34 UTC*, **xuzhg** commented:

ODL expects the string value with the single quote around. 

For example, The function 
ODataUriUtils.ConvertFromUriLiteral(...) 
is used to convert the value from Uri literal. If the input value is a string, it must have a single quote around. Otherwise, it will throw exception.

Synced with test, PM, postpone it to vNext.

**Comment by LianwMS** [comment]
On *2014-07-03 12:18:21 UTC*, **azhou** commented:

For now, [FromODataUri] in the function parameter can be added by customer.

**Comment by xuzhg** [comment]
It's clear. close it.
