### ISSUE TITLE
Bound custom UriFunctions to CLR methods.

### ISSUE THREAD

**Issue by YogiBear52** [OData/WebApi#612]
After issue OData/odata.net#430 is solved at OData.Lib level, we must support it at OData.WebApi level.

Now, after adding the custom function signature in OData.Libs and run the WebApi we get the following exception as expected: 
"message": "Unknown function '[MyCustomFunctionName]'.",
"type": "System.NotImplementedException",
"stacktrace": "   at System.Web.OData.Query.Expressions.FilterBinder.BindSingleValueFunctionCallNode(SingleValueFunctionCallNode node)

It means that there is no CLR bounded method to this specific signature.

Now we have to make it possible for clients to register their EdmFunctionSignature to a CLR MethodInfo so we could create an Expression out of it.

**Comment by VikingsFan** [comment]
Thanks, Merged 56c61a1b957054e02ada5c35aed9735a83bd11a2

**Comment by YogiBear52** [comment]
Thanks for merging the code!
Will it be included in the full 5.9 release?

Yogev.
בתאריך 22 במרץ 2016 4:43 לפנה״צ,‏ "Fan Ouyang" <notifications@github.com>
כתב:

**Comment by VikingsFan** [comment]
Sure, Thanks for your PR, if there is a end to end using scenario for our github.io will be perfect.

**Comment by YogiBear52** [comment]
I am not near a computer and won't be for the next two weeks, so I can't
write any ,but there are few unit tests which pretty much covers all the
future.
Tell me if they are fine with you
בתאריך 22 במרץ 2016 4:53 לפנה״צ,‏ "Fan Ouyang" <notifications@github.com>
כתב:

**Comment by VikingsFan** [comment]
Okay, we'll try to add for you

**Comment by YogiBear52** [comment]
Thanks, feel free to ask me if you have any questions
בתאריך 22 במרץ 2016 5:10 לפנה״צ,‏ "Fan Ouyang" <notifications@github.com>
כתב:

**Comment by YogiBear52** [comment]
Hey!

Have you already done it?
בתאריך 22 במרץ 2016 5:18 לפנה״צ,‏ "יוגב מזרחי" <yogev0mz@gmail.com> כתב:

**Comment by VikingsFan** [comment]
I'm now a little busy about the releasing, PR is already merged, I'll have time to write the doc next week.

**Comment by VikingsFan** [comment]
Doc d76b3142e016507d5987aa48c7027e891a2d9c82
