### ISSUE TITLE
how do I define ODataModelBuilder multiple times for multiple domain model classes?

### ISSUE THREAD

**Issue by ashuthinks** [OData/WebApi#615]
I have one Odata Service which is having two separate models

ModelVer1.Customer.cs

int ID;
string Name;
ModelVer2.Customer.cs

int ID;
string Name;
string Address;
webapiconfig.cs

  public static void Register(HttpConfiguration config)
        {
            config.MapHttpAttributeRoutes();
            ODataModelBuilder builder = new ODataConventionModelBuilder();
            builder.EntitySet< ModelVer1.Customer >("Customers");
          // If I use below get error:
          // The entity set 'Customers' was already configured with a different EntityType ('Customer'). Parameter name: entityType
            builder.EntitySet< ModelVer2.Customer >("Customers");

            config.MapODataServiceRoute(
                routeName: "ODataRoute",
                routePrefix: "demo/api",
                model: builder.GetEdmModel());

            config.Services.Replace(typeof(IHttpControllerSelector), new CustomControllerSelector(config));

        }
But getting error :

The entity set 'Customers' was already configured with a different EntityType ('Customer'). Parameter name: entityType
What should be done?

**Comment by xuzhg** [comment]
@ashuthinks 

[OData V4 spec ](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part3-csdl/odata-v4.0-errata02-os-part3-csdl-complete.html#_Toc406398024) says:

_Each metadata document used to describe an OData service MUST define exactly <strong>one</strong> entity container. Entity containers define the entity sets, singletons, function and action imports exposed by the service._

<h4>That's, for one Edm model, there's one, and only one entity container.</h4>

[OData V4 spec](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part3-csdl/odata-v4.0-errata02-os-part3-csdl-complete.html#_Toc406398025) says: 

_The edm:EntityContainer element represents an entity container in an entity model.  .... Entity set, singleton, action import, and function import names <strong>MUST be unique</strong> within an entity container_

<h4>That's, for one entity container, each entity sets must have unique name.</h4>

---

So, for your scenario, you can't create two entity sets with the same name as "Customers", even though the corresponding CLR type has the different namespace.

There's two workarounds:
1. use the different name for different entity set.
2. use the model reference. for model reference, you can refer to this [blog](http://blogs.msdn.com/b/odatateam/archive/2014/06/30/refer-other-models-when-constructing-edm-model.aspx).

Thanks.
Sam
