### ISSUE TITLE
Support Pass Null to EntitySet during Feed Serialization

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#617]
The issue is about https://github.com/OData/odata.net/issues/69.
ODL has support pass null to entity set, but WebAPI OData does not support, now

**Comment by LianwMS** [comment]
https://github.com/OData/odata.net/pull/421 is for OData/odata.net#69.

**Comment by VikingsFan** [comment]
Merged dd7aecebf77121d118bf4231c46328b5ee3a893d
