### ISSUE TITLE
Fix PoliCheck Issues

### ISSUE THREAD

**Issue by LaylaLiu** [OData/WebApi#619]
http://som/ScanOutputManager/ScanOutputMgr.application?workspace=9f1a8b62-93cb-4d12-b147-e735dae5964f

**Comment by xuzhg** [comment]
Steps:

1. Use Policheck tool to run the clean clone.
2. Resolve the Policheck results
3. Re-un Policheck tool to generate the policheck result excel file.
4. Open the http://som/ScanOutputManager/ScanOutputMgr.application?workspace=9f1a8b62-93cb-4d12-b147-e735dae5964f
5. Upload the result excel file
6. Triage all items, for example select false positive.

**Comment by xuzhg** [comment]
Close it.
