### ISSUE TITLE
Delete TransientAction/Funcition. 

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#62]
Now action/function can be bound or unbound in odata v4. so there is no need
to keep these 2 APIs.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1744](http://aspnetwebstack.codeplex.com/workitem/1744)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 6, 2014 at 3:17 AM
**Reported by:**	jinfutan
**Updated on:**	Apr 17, 2014 at 10:53 AM
**Updated by:**	zjufish

**Comment by xuzhg** [comment]
already removed. Thanks.
