### ISSUE TITLE
swagger generation does not support navigation properties

### ISSUE THREAD

**Issue by nkbond** [OData/WebApi#626]
swagger document generated with ODataSwaggerConverter does not contain navigation properties in the entity, properties collection.

**Comment by madansr7** [comment]
@nkbond , Until OpenAPI 3.0, there wasn't a good way to represent navigation properties during the conversion. We've recently published a new library [https://github.com/Microsoft/OpenAPI.NET.OData](https://github.com/OData/lab/tree/master/OpenApi) that takes a CSDL and converts to OpenAPI 3.0. 
NuGet Package for the lib is available at [https://www.nuget.org/packages/Microsoft.OpenApi.OData/1.0.0-beta7](https://www.nuget.org/packages/Microsoft.OpenApi.OData/1.0.0-beta7).

There is a sample available under the OData lab that demonstrates the use of the library. [https://github.com/OData/lab/tree/master/OpenApi](https://github.com/OData/lab/tree/master/OpenApi)

Hope this helps.
