### ISSUE TITLE
Navigation Source Abstract Entity without a key

### ISSUE THREAD

**Issue by HefloRicardo** [OData/WebApi#627]
You already implemented at #4 abstract types that does not have a key, but if you have an navigation source of another element, an invalid operation is thrown:

at OData/src/System.Web.OData/OData/Builder/ODataModelBuilder.cs 

this part of the code:
`

```
    foreach (IEdmNavigationSource navigationSource in model.EntityContainer.Elements.OfType<IEdmNavigationSource>()) 
         { 

             if (!navigationSource.EntityType().Key().Any()) 
             { 
                 throw Error.InvalidOperation(SRResources.NavigationSourceTypeHasNoKeys, navigationSource.Name, 
                     navigationSource.EntityType().FullName()); 
             } 
         } 
```

`

does not check if the navicationSource.EntityType() is abstract.

Regards.

**Comment by xuzhg** [comment]
@Venki-Ricardo 

Would you please tell us more detail about " an navigation source of another element"?

And What error message do you get? 

Thanks.

**Comment by xuzhg** [comment]
Close it. Please feel free to re-open or file a new issue.
