### ISSUE TITLE
OData V4 needs better supports for $ref (formally $links)

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#63]
There is no easy way to support $ref(previously called $links) with the Web
API OData V4, we should provide a better story for this. I think $ref or
$links should be a very common scenario for customers.  
  
// Captured from [ http://msdn.microsoft.com/en-
us/library/dd728283(v=vs.110).aspx ](http://msdn.microsoft.com/en-
us/library/dd728283\(v=vs.110\).aspx)  
In addition to addressing entity sets and entity instances, OData also enables
you to address the associations that represent relationships between entities.
This functionality is required to be able to create or change a relationship
between two entity instances, such as the shipper that is related to a given
order in the Northwind sample database. OData supports a $link operator to
specifically address the associations between entities. For example, the
following URI is specified in an HTTP PUT request message to change the
shipper for the specified order to a new shipper.  
  
[
http://services.odata.org/Northwind/Northwind.svc/Orders(10643)/$links/Shipper
](http://services.odata.org/Northwind/Northwind.svc/Orders\(10643\)/$links/Shi
pper)  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1754](http://aspnetwebstack.codeplex.com/workitem/1754)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 7, 2014 at 10:09 PM
**Reported by:**	yjhong
**Updated on:**	Apr 27, 2014 at 6:38 PM
**Updated by:**	corydeppen

**Comment by LianwMS** [comment]
On *2014-04-12 01:29:31 UTC*, **yjhong** commented:

We do support $ref, but when implementing the $ref actions, users need to retrieve the ID of the related item in the request body. And, it requires users to write the following type of helper method to implement that $ref.

I think this is common enough and it could be error prone for users to implement it. I think it will be helpful if we can provide a helper method for this scenario.

    /// <summary>
    /// Helper method to get the key value from a uri.
    /// Usually used by $ref action to extract the key value from the url in body.
    /// </summary>
    /// <typeparam name="TKey">The type of the key</typeparam>
    /// <param name="request">The request instance in current context</param>
    /// <param name="uri">OData uri that contains the key value</param>
    /// <returns>The key value</returns>
    public static TKey GetKeyValue<TKey>(this HttpRequestMessage request, Uri uri)
    {
        if (uri == null)
        {
            throw new ArgumentNullException("uri");
        }

        //get the odata path Ex: ~/prefix/entityset/key/navigation/$ref
        var odataRoute = request.GetRouteData().Route as ODataRoute;

        var odataLocalPath = string.IsNullOrEmpty(odataRoute.RoutePrefix) ? uri.LocalPath
            : uri.LocalPath.Substring(uri.LocalPath.IndexOf(odataRoute.RoutePrefix, StringComparison.InvariantCulture) + odataRoute.RoutePrefix.Length);

        var odataPath = request.ODataProperties().PathHandler.Parse(request.ODataProperties().Model, odataLocalPath);
        var keySegment = odataPath.Segments.OfType<KeyValuePathSegment>().FirstOrDefault();
        if (keySegment == null)
        {
            throw new InvalidOperationException("The link does not contain a key.");
        }

        var value = ODataUriUtils.ConvertFromUriLiteral(keySegment.Value, ODataVersion.V4);
        return (TKey)value;
    }
}

**Comment by xuzhg** [comment]
We support $ref already. 

Close it. Please file a new issue if you have any concern. Thanks.
