### ISSUE TITLE
Issues with aggregates using V5.9.0-beta

### ISSUE THREAD

**Issue by Rosefield** [OData/WebApi#632]
Hello,

I have been working on a project that is utilizing OData as part of a reporting framework, and was excited to see that the basic aggregation extensions had been merged in. Obviously I realize this is still the beta release and didn't expect everything to work perfectly as described.

Below are some issues I had ran into while testing the new capabilities.

Given the simplified domain model of
```
public class Contribution {
  [PrimaryKey]
  public int ContributionID;
  public decimal Amount;
  public Contact Contact;
}

public class Contact {
  [PrimaryKey]
  public int ContactID;
  public string FirstName;
  public string LastName;
  public ICollection<Contribution> Contributions;
}
```
I have experienced the following issues:
- Attempting to name an aggregate that does not match an existing object property
`https://localhost/v5/odata/contributions?$apply=aggregate(Amount with sum as Total)`
This gives the exception
`Microsoft.OData.Core.ODataException: Could not find a property named 'Total' on type 'Contribution'. `

This matches Example 5 under the aggregations extensions (http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs01/odata-data-aggregation-ext-v4.0-cs01.html#_Toc378326291)

- Attempting to group by a property on the aggregate adds an implicit orderby the primary key throwing an exception if not added
`https://localhost/v5/odata/contributions?$apply=groupby((Contact/FirstName, Contact/LastName), aggregate(Amount with sum as Amount))&$orderby=Amount`
gives the exception ` Instance property 'ContributionID' is not defined for type 'DynamicTypeWrapper'. `

This matches the statement `If the result is a collection, $filter, $orderby, $expand and $select work as usual on properties that are defined on the output set after evaluating $apply. ` (http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs01/odata-data-aggregation-ext-v4.0-cs01.html#_Toc378326311)

- Attempting an aggregate on a referenced collection
`https://localhost/v5/odata/contacts?$apply=groupby((FirstName,LastName), aggregate(Contributions/Amount with sum as Amount))`
throws the exception
` Microsoft.OData.Core.ODataException: The parent value for a property access of a property 'Amount' is not a single value. Property access can only be applied to a single value. `

This matches example 50 under the aggregation extensions (http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs01/odata-data-aggregation-ext-v4.0-cs01.html#_Toc378326330)

Thank you,
Schuyler Rosefield

**Comment by VikingsFan** [comment]
Hi Rosefield, Thanks for your verify to our Aggregation feature! 
The first url `https://localhost/v5/odata/contributions?$apply=aggregate(Amount with sum as Total)` should working, you can check your package version, I also upload a [sample project](https://github.com/VikingsFan/SampleForOData/tree/master/AggregationSample) with same model.

The second url is not valid $groupby is not acceptable, `https://localhost/v5/odata/contributions?$apply=groupby((Contact/FirstName, Contact/LastName), aggregate(Amount with sum as Amount))&$groupby=Amount`, as the statement you copy from spec is `$filter, $orderby, $expand and $select`, I opened an [issue](https://github.com/OData/WebApi/issues/633) to track filter and orderby, this is already fixed, but need odata lib release a new version like beta2 or rc.

The third should fix in odata lib and WebApi. I opened an [issue](https://github.com/OData/WebApi/issues/634).

**Comment by Rosefield** [comment]
Hello VikingsFan,

For the first item, it is hard to tell which version exactly is needed, so of all the odata packages, I have 
- Microsoft.Data.OData V5.7.0 (no pre release version available)
- Microsoft.AspNet.OData V5.9.0-beta (pre release)
- Microsoft.OData.Core V6.15.0-beta (pre release)

For the second item I managed to mistype "group by" instead of "order by" many times, I have edited the original post to reflect that.

Overall, thank you for creating the tracking items and responding so quickly!

Thanks,
Schuyler Rosefield

**Comment by VikingsFan** [comment]
Microsoft.Data.OData V5.7.0 (no pre release version available) this is for V1-3. remove this maybe we can get the first url working, check my sample project maybe helpful too.

**Comment by VikingsFan** [comment]
Close as sub issues are created
