### ISSUE TITLE
OData EnableAlternateKeys can't use while EnableEnumPrefixFree/EnableUnqualifiedNameCall

### ISSUE THREAD

**Issue by VikingsFan** [OData/WebApi#636]
Related code: https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/ODataUriResolverSetttings.cs#L30-L50

it's confuse to customer that those settings can't enable together, we need change the implementation and maybe provide a api for customer to set the UriResolver directly.

**Comment by mikepizzo** [comment]
I'm assuming this has been fixed with the refactoring of simplified options in the 6.x branch. I suspect a number of customers will use these options together, especially now that they are being added to OData V4.01.
