### ISSUE TITLE
ODataQueryOptions should support $id.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#64]
The supported query options are:  

    
    
    public static bool IsSystemQueryOption(string queryOptionName)
    {
        return queryOptionName == "$orderby" ||
             queryOptionName == "$filter" ||
             queryOptionName == "$top" ||
             queryOptionName == "$skip" ||
             queryOptionName == "$count" ||
             queryOptionName == "$expand" ||
             queryOptionName == "$select" ||
             queryOptionName == "$format" ||
             queryOptionName == "$skiptoken";
    }
    

There is no $id, so some scenarios can't be implemented, such as:  

  1. Resolving an entity by id:   
http://host/service/$entity?$id=Products(0)

  2. Delete reference between entities:   
DELETE [ http://host/service/Categories(1)/Products/$ref?$id=../../Products(0
](http://host/service/Categories\(1\)/Products/$ref?$id=../../Products\(0) )

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1761](http://aspnetwebstack.codeplex.com/workitem/1761)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 13, 2014 at 9:05 AM
**Reported by:**	jinfutan
**Updated on:**	Apr 17, 2014 at 10:54 AM
**Updated by:**	zjufish

**Comment by xuzhg** [comment]
It's already resolved. See the test case: https://github.com/OData/WebApi/blob/master/OData/test/UnitTest/System.Web.OData.Test/OData/Routing/DefaultODataPathHandlerTest.cs#L649-L662
