### ISSUE TITLE
Overriding OData URLs by Request.RequestUri doesn't work for @odata.context URL

### ISSUE THREAD

**Issue by eloekset** [OData/WebApi#643]
As explained in this question at StackOverflow (http://stackoverflow.com/questions/35628422/override-host-of-webapi-odata-links) I'm hosting an OData WebAPI on a server that is not publicly exposed. I access the API from client side JavaScript using a URL rewrite on the web server, passing the request over to the local app server. Because of this, all OData URLs are generated based on the internal IP address of the app server, so links like @odata.context and @odata.nextLink are invalid from the client side.

I try to fix this by overriding the Request.RequestUri in a BaseODataController.Initialize() method as follows:
```
	protected override void Initialize(HttpControllerContext controllerContext)
	{
		base.Initialize(controllerContext);
		if (Request.RequestUri.Host.StartsWith("192.168"))
		{
			var externalAddress = "https://accountname.domain.com";
			var account = "AccountName";
			var uriToReplace = new Uri(new Uri("http://" + Request.RequestUri.Host), account);
			string originalUri = Request.RequestUri.AbsoluteUri;
			Request.RequestUri = new Uri(Request.RequestUri.AbsoluteUri.Replace(uriToReplace.AbsoluteUri, externalAddress));
			string newUri = Request.RequestUri.AbsoluteUri;
			this.GetPluginLogger().Info($"Request URI was rewritten from {originalUri} to {newUri}");
		}
    }
```
When this code runs on the app server, I get a valid @odata.nextLink URL, but the @odata.context URL still contains the /AccountName/ part of the URL like so: https://accountname.domain.com/AccountName/api/edi/odata/$metadata#DeliveryNotes
The original URL that is being rewritten is:
http://192.168.111.20/AccountName/api/edi/odata/$metadata#DeliveryNotes

Example of an @odata.nextLink that is correctly rewritten and valid: https://accountname.domain.com/api/edi/odata/DeliveryNotes?token=3f249df3-0546-...&$orderby=statusId%2CsystemTime%20desc&$top=1&$count=true&$skip=20

How come the @odata.context URL is not generated correctly when the @odata.nextLink URL is? I'm creating this issue since the links clearly aren't generated the exact same way.

I've tried stepping through some of the unit tests in MetaDataControllerTest.cs but I still got no clue why the $metadata link is only partially rewritten.

Is there a better way to override OData URL generation to get valid external URLs than overriding the ODataController.Initialize method?

I'm using WebAPI 2.2 and Microsoft.AspNet.OData 5.7.0.

**Comment by jackfree** [comment]
I had a similar issue with OData.Context url's and not having enough control to override them - See issue #644.  I created pull request #645 as a potential solution.

**Comment by VikingsFan** [comment]
Close as #645 is merged. Please reopen it if you have any concern.
