### ISSUE TITLE
[vNext] Task.Run

### ISSUE THREAD

**Issue by TheWyzard44** [OData/WebApi#647]
version 6.0.0-alpha1

ODataOutputFormatter line 49

If you could please replace `Task.Run` with `Task.Factory.StartNew` (unless you have a good reason?)

I have a particular implementation that needs a custom TaskScheduler and Task.Run thwarts what I'm trying to do.

**Comment by xuzhg** [comment]
It's out of date. We have vNext branch that you can target on. Please feel free open a new issue for us on the vNext branch.
