### ISSUE TITLE
Complex type cast segment

### ISSUE THREAD

**Issue by VikingsFan** [OData/WebApi#649]
Merge:

https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Routing/ComplexCastPathSegment.cs

and:

https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Routing/CastPathSegment.cs

**Comment by xuzhg** [comment]
Resolved with the ODataPathSegment change. Close it.
