### ISSUE TITLE
Un-supported primitive types

### ISSUE THREAD

**Issue by VikingsFan** [OData/WebApi#654]
Refactor:  

https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Formatter/Serialization/ODataPrimitiveSerializer.cs#L148-L238

Make a solution how to support the un-support primitive types.

**Comment by mikepizzo** [comment]
Not sure I understand the issue. Are there primitive types we don't support, or is this about supporting Edm.Primitive, or???
