### ISSUE TITLE
Support $search in OData v4.0

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#66]
The $search system query option restricts the result to include only those entities matching the specified search expression. The definition of what it means to match is dependent upon the implementation.

```
Example 53: return all Products that match the search term "bike"

http://host/service/Products?$search=bike

The search expression can contain phrases, enclosed in double-quotes. 

Example 54: return all Products that match the phrase "mountain bike"


http://host/service/Products?$search="mountain bike"

The upper case keyword NOT restricts the set of entities to those that do not match the specified term. 

Example 55: return all Products that do not match "clothing"


http://host/service/Products?$search=NOT clothing

Multiple terms within a search expression are separated by a space (implicit AND) or the upper-case keyword AND, indicating that all such terms must be matched. 

Example 56: return all Products that match both "mountain" and "bike"


http://host/service/Products?$search=mountain AND bike

The upper-case keyword OR is used to return entities that satisfy either the immediately preceding or subsequent expression. 

Example 57: return all Products that match either "mountain" or "bike"


http://host/service/Products?$search=mountain OR bike

Parentheses within the search expression group together multiple expressions. 

Example 58: return all Products that match either "mountain" or "bike" and do not match clothing


http://host/service/Products?$search=(mountain OR bike) AND NOT clothing 

The operations within a search expression MUST be evaluated in the following order: grouping operator, NOT operator, AND operator, OR operator

If both $search and $filter are specified in the same request, only those entities satisfying both criteria are returned.

The value of the $search option is a Boolean expression as defined in [OData-ABNF]. 
```
## Work Item Details

**Original CodePlex Issue:**    [Issue 1767](http://aspnetwebstack.codeplex.com/workitem/1767)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Mar 17, 2014 at 9:44 PM
**Reported by:**    jacalvar
**Updated on:** Apr 17, 2014 at 10:47 AM
**Updated by:** zjufish

**Comment by MolallaComm** [comment]
Making this work is simple - making it work in a way that suits the needs of everyone or what is written above and in the odata spec is probably impossible and/or not even advisable.  For my purposes, on the client side, I have my DTO entities bound to an ion-autocomplete and I just want to find matches based on whether any of the string columns contain the text that has been typed or if the entity key is a number/identity I also want to look up by that (i.e. say they type in the AccountID #).  To accomplish this, you can modify the code in the constructor for ODataQueryOptions to be something like this effectively munging $search into a bunch of ORed $filters:

           // Parse the query from request Uri
            RawValues = new ODataRawQueryOptions();
            IDictionary<string, string> queryParameters = 
                request.GetQueryNameValuePairs().ToDictionary(p => p.Key, p => p.Value);

            string search; Regex num = new Regex(@"^\d+$");

            if (queryParameters.TryGetValue("$search", out search))
            {
                queryParameters.Clear(); var type = (Microsoft.OData.Edm.Library.EdmEntityType)context.ElementType; List<string> cols = new List<string>();

                if (num.Match(search).Success && type.DeclaredKey.Count() == 1 && type.DeclaredKey.First().Type.ToString().Contains("Edm.Int32"))
                    cols.Add(string.Format("{0} eq {1}", type.DeclaredKey.First().Name, search));

                cols.AddRange(from p in type.DeclaredProperties where p.Type.ToString().Contains("Edm.String") select string.Format("contains({0},'{1}')", p.Name, search));

                queryParameters.Add("$filter", string.Join(" or ", cols));
            }

            _queryOptionParser = new ODataQueryOptionParser(
                context.Model,
                context.ElementType,
                context.NavigationSource,
                queryParameters);

This doesn't meet all the requirements in the spec, but seems to work well for my purposes, so I'm sharing it.  Regarding a generic solution, I think a lot of thought would be required and the linq expressions required would get gnarly in a hurry.

P.S.  You also need to add $search to the IsSystemQueryOption functionin that same file for it to be allowed.

**Comment by patrickmichalina** [comment]
Where does one add "$search" to "IsSystemQueryOption"? Web Api throw an error since it is not supported out of the box.

**Comment by patrickmichalina** [comment]
@xuzhg any update on this?
