### ISSUE TITLE
Improve Serialize/Deserialize

### ISSUE THREAD

**Issue by VikingsFan** [OData/WebApi#665]
Sync with Performance. @luoyan0517

**Comment by DickvdBrink** [comment]
Can you tell us what is going to be improved/changed?
Is it about performance? Is it for the full framework or also for vNext?

**Comment by xuzhg** [comment]
@DickvdBrink:  It's related the performance. and it's full vCurrent. not for vNext.

**Comment by VikingsFan** [comment]
close this as sub item are opened.
