### ISSUE TITLE
Upgrade Newtonsoft.Json to a newer version.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#67]
The package referenced is:  
<package id="Newtonsoft.Json" version="4.5.11" targetFramework="net45" />  
  
And the latest one is 6.0. If user chooses to use a newer one, assembly
loading redirection is needed.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1769](http://aspnetwebstack.codeplex.com/workitem/1769)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 18, 2014 at 6:53 AM
**Reported by:**	jinfutan
**Updated on:**	Apr 17, 2014 at 10:47 AM
**Updated by:**	zjufish

**Comment by xuzhg** [comment]
It's out of date. Now, Newtonsoft.Json is referenced to 6.0.4.
