### ISSUE TITLE
Order the return object properties according to the order they are provided in the $select url param

### ISSUE THREAD

**Issue by dontwork** [OData/WebApi#676]
Just looking to see if this is possible to achieve without having to write some ordering code

**Comment by VikingsFan** [comment]
@dontwork would you please tell us more about your scenario? It will be helpful for us to give a solution :)

**Comment by mikepizzo** [comment]
Properties in a JSON object are defined to be unordered.  The order of properties in the $select list is insignificant in OData. We do impose some ordering of annotation properties, but even these are only enforced if odata.streaming=true.
