### ISSUE TITLE
HttpConfiguration.MapODataServiceRoute with route prefix less than 3 charecters is not working

### ISSUE THREAD

**Issue by kotapatisiva** [OData/WebApi#679]
Hi All,
I tried to use HttpConfiguration.MapODataServiceRoute with routeprefix parameter less than 3 characters(for example SC) and the call to get the metadata failed, I increased to 3 characters(for example SCC) the  call to get metadata worked, So I think there is some issue in this with the length of the routeprefix string.

**Comment by VikingsFan** [comment]
@kotapatisiva you are using WebAPI/OData V4 or V3? Can you give more detail about your code? :) I have tried use a less than 3 charecters route prefix in test case and it can get Metadata successfully.
My sample code:

    ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
    builder.EntitySet<FormatterAccount>("Accounts");

    var config = new[] { typeof(MetadataController) }.GetHttpConfiguration();
    config.MapODataServiceRoute("odata", "ab", builder.GetEdmModel());

    HttpServer server = new HttpServer(config);
    HttpClient client = new HttpClient(server);

    var responseString = client.GetStringAsync("http://localhost/ab/$metadata").Result;

**Comment by VikingsFan** [comment]
Can't repro, close it.
