### ISSUE TITLE
Support singleton on query option

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#68]
Current, the WebAPI V4 is based on ODL V6.0 beta 1. It doesn't work if we put
singleton on query option. for example:  
  
~/Customers(1)?&expand=CEO  
  
where, CEO is the navigation property and binding to the singleton.  
  
Therefore, once we migrate to ODL V6.2 (it's undergoing), please add singleton
support on query option.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1770](http://aspnetwebstack.codeplex.com/workitem/1770)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 18, 2014 at 9:13 AM
**Reported by:**	xuzhg
**Updated on:**	Mar 18, 2014 at 9:13 AM
**Updated by:**	xuzhg

**Comment by VikingsFan** [comment]
This is supported now.
