### ISSUE TITLE
OData for Web Api throws error with latest version of OData.Core Lib (6.15.0.0)

### ISSUE THREAD

**Issue by oliroy** [OData/WebApi#687]
Hi

When trying to access a OData endpoint this error is now thrown:

Could not load type 'Microsoft.OData.Core.UriParser.Extensions.Semantic.ApplyClause' from assembly 'Microsoft.OData.Core, Version=6.15.0.0

Details:

> 
> System.TypeLoadException: Could not load type 'Microsoft.OData.Core.UriParser.Extensions.Semantic.ApplyClause' from assembly 'Microsoft.OData.Core, Version=6.15.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
>    at System.Web.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
>    at System.Web.OData.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
>    at System.Web.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor)
>    at System.Web.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)
>    at 

The OData.Core lib was upgraded through nuget from 6.14.0.0 to 6.15.0.0.  Going back to older version resolves this issue.

Please advise.

**Comment by VikingsFan** [comment]
@oliroy We have some public API change from OData Lib 6.15 beta to 6.15, WebAPI 5.9's release will fix this problem, thanks!

**Comment by oliroy** [comment]
Thanks for letting me know!

Cheers,
