### ISSUE TITLE
OData Expand overrides Entity Framework includes

### ISSUE THREAD

**Issue by xuzhg** [OData/WebApi#689]
Transfered from https://github.com/OData/odata.net/issues/356

Customer @HenkHui said:

I have posted a question on Stackoverflow regarding OData expands:

http://stackoverflow.com/questions/33164537/odata-expand-override-entity-framework-includes

Any suggestions?

**Comment by VikingsFan** [comment]
@HenkHui we use element type like Employee when select all properties, so we lose Address when composing the Linq expression, but if you select Address, it will come in result because it's not select all, so a work around maybe request like: $expand=Messages&$select=Address,Id,Name

**Comment by xuzhg** [comment]
Close it.
