### ISSUE TITLE
support $search for OData

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#69]
[ http://docs.oasis-open.org/odata/odata/v4.0/os/part1-protocol/odata-v4.0-os-
part1-protocol.html#_Toc372793700 ](http://docs.oasis-
open.org/odata/odata/v4.0/os/part1-protocol/odata-v4.0-os-
part1-protocol.html#_Toc372793700)  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1785](http://aspnetwebstack.codeplex.com/workitem/1785)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 21, 2014 at 8:05 AM
**Reported by:**	zjufish
**Updated on:**	Jan 3 at 9:18 PM
**Updated by:**	rbuergi

**Comment by xuzhg** [comment]
Close as duplicated #66.
