### ISSUE TITLE
ForeignKey properrty nullable=false not set

### ISSUE THREAD

**Issue by xuzhg** [OData/WebApi#690]
Transferred from: https://github.com/OData/odata.net/issues/337

**Comment by pysco68** [comment]
(just subscribing notifications as I was the one opening https://github.com/OData/odata.net/issues/337)

**Comment by xuzhg** [comment]
@pysco68 

I don't think it's a bug. The nullable  of foreign key is along with the nullable  of its corresponding navigation property.

So, If you mark the navigation property with [Required] attribute as follows:

```
public class Entity2
{
    public int Id { get; set; } 

    [Required]
    [ForeignKey("EntityOneId")]
    public virtual Entity1 EntityOne { get; set; }
    public int EntityOneId { get; set; }
}
```

you will get the following metadata:

![image](https://cloud.githubusercontent.com/assets/9426627/14373182/e838fe04-fd79-11e5-9e1b-7bae06f606fc.png)

Thanks.
