### ISSUE TITLE
Support for "contains" function in $filter

### ISSUE THREAD

**Issue by superstrom** [OData/WebApi#696]
OData V4 added a "contains" function that essentially switches the parameters of substringof (making them more consistent with other string functions)
http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part2-url-conventions.html#_Toc371341773

Is there any plan to add support for that function?

**Comment by MaxWilson** [comment]
It's already there.

**Comment by VikingsFan** [comment]
Close as it's already supported.

**Comment by superstrom** [comment]
Perhaps I am missing something, but there is nothing for enabling contains in AllowedFunctions, and every request that uses contains fails validation with an ODataException "An unknown function with name 'contains' was found. This may also be a key lookup on a navigation property, which is not allowed."

**Comment by VikingsFan** [comment]
for now, `contains` is `AllowedFunctions.SubstringOf`, IMO it should be `AllowedFunctions.Contains`, open issue https://github.com/OData/WebApi/issues/706 to track.

**Comment by xuzhg** [comment]
Close it.
