### ISSUE TITLE
EnumMember Attribute without value 

### ISSUE THREAD

**Issue by NicosNet** [OData/WebApi#697]
Hello, I was used to declare my enums like this:

[DataContract]
public enum SalesmanKind
{

    [EnumMember]
    None,
    [EnumMember]
    Multiple,
    [EnumMember]
    Exclusive
And since my last OData package upgrade EnumMembers disapears from my metadatas.

I think it's due to [this](https://github.com/OData/WebApi/issues/640) issue correction and sepecificly this condition
**!String.IsNullOrWhiteSpace(enumMemberAttribute.Value)**

I dont want to specify a value to Every EnumMember decoration.

**Comment by VikingsFan** [comment]
@NicosNet Thanks for your PR! before next version you can work around as 

    builder.EnumTypes.Single(e => e.Name == "SalesmanKind").AddMember(SalesmanKind.None);

**Comment by VikingsFan** [comment]
Merged  660f3ab
