### ISSUE TITLE
V5.5: Complex types,Entity reference, Entity and a collection of them as function parameters

### ISSUE THREAD

**Issue by xuzhg** [OData/WebApi#7]
Currently, Web API only support primitive type and enum type as function parameters.
Now, ODL supports
   .Complex types
   .Entity reference
   .Entity
   .A collection of them
as function parameters.

Web API should support all of them.

**Comment by xuzhg** [comment]
Checked in. Thanks.

**Comment by xuzhg** [comment]
Please refer the [simple tutorial](http://odata.github.io/WebApi/Complex-Entity-As-Function-Parameter/) for sample.

**Comment by baselsalam** [comment]
The link to the tutorial is broken :(: http://odata.github.io/WebApi/Complex-Entity-As-Function-Parameter/

**Comment by xuzhg** [comment]
@baselsalam  Thanks. Can you refer to: http://odata.github.io/WebApi/#04-06-function-parameter-support
