### ISSUE TITLE
Support aggregation for OData

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#70]
[ http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs01/odata-
data-aggregation-ext-v4.0-cs01.html ](http://docs.oasis-open.org/odata/odata-
data-aggregation-ext/v4.0/cs01/odata-data-aggregation-ext-v4.0-cs01.html)  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1786](http://aspnetwebstack.codeplex.com/workitem/1786)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 21, 2014 at 8:08 AM
**Reported by:**	zjufish
**Updated on:**	Dec 8, 2014 at 1:55 PM
**Updated by:**	doggy8088

**Comment by LianwMS** [comment]
On *2014-10-12 20:16:04 UTC*, **nlips** commented:

An alternative to some OData aggregation scenarios is to use the server-side extension method QueryByCube provided by my product
AdaptiveLINQ.
This function is based on the notion of cube defined as C# expressions.
Grouping and aggregation is performed according to the selection expressed via the $select operator.

For example, the following query provides the total sales per customer:
.../myService?$select=Customer, Sales
The request is processed by AdaptiveLINQ as a query using the GroupBy operator on a (potentially) complex entity model.
The advantage vs a grouping expression expressed client side, is that the developer of the service, control the dimensions of aggregation can therefore optimize his data system (index on some data table fields...). Moreover, the client does not have to know
 the complexity of calculating aggregations.

**Comment by dotnetwise** [comment]
+1

**Comment by apathytomorrow** [comment]
Please support this! +1

**Comment by D-Bush** [comment]
+1 This would significantly decrease the payload if aggregation were to be handled by the end point rather than the client.

**Comment by bj00rn** [comment]
+1 Any roadmap if/when this is to be implemented?

**Comment by thebothead** [comment]
+1

**Comment by ronnyek** [comment]
I'm really interested in this, where do things stand with this? As a whole, the extension is not present? Or is it just the ODataUriParser that is lacking?

**Comment by VikingsFan** [comment]
basic support is checked in at ff46c7921e8c67a1b2ce90acb7c9299429124f54, you can try nightly at https://www.myget.org/F/aspnetwebstacknightly/ further PR for make Aggregation more powerful is very welcome!

**Comment by karldodd** [comment]
+1

**Comment by nlips** [comment]
Try [AdaptiveLINQ](http://www.adaptivelinq.com/)

**Comment by VikingsFan** [comment]
@karldodd now it's support basic aggregate and groupby, can you try 5.9?

**Comment by VikingsFan** [comment]
Close this issue, please open a new issue if you have any concern.
