### ISSUE TITLE
Support case-insensitive on ODataEnumSerializer and ODataEnumDeserializer

### ISSUE THREAD

**Issue by chuanboz** [OData/WebApi#700]
Currently there is no easy way to turn on case-insensitive for enum serialization and deserialization, it would be great to have some flag like NameResolverOptions.ProcessEnumProperty to turn on case-insensitive and camel case support.

**Comment by markdstafford** [comment]
This sounds like a great feature, but unfortunately it's more complicated than it sounds. E.G., .NET's native handling of enum values is case sensitive and things like the following are legitimate (though nonsensical):

```
public enum Color
{
  Red,
  red
}
```

For now we recommend working around this by implementing your own ODataEnumSerializer/ODataEnumDeserializer. If you come up with a good solution that will work generically across services, we'd love to look at a PR.

**Comment by jholovacs** [comment]
I think that should be an option, even if someone could do something incredibly silly like have 2 enum values as "red" and "Red".  ASP.NET Core 2.x+ supports this for webapi; OData is now inconsistent with the MVC configuration.
