### ISSUE TITLE
GetPerRequestFormatterInstance needlessly creates two formatters per request

### ISSUE THREAD

**Issue by jackfree** [OData/WebApi#703]
GetPerRequestFormatterInstance wastes time and memory creating another formatter object just for the sake of validating parameters; this seems excessive; we should be able to borrow/copy/mimic the minimal validation code we need for these 3 parameters.

        /// <inheritdoc/>
        public override MediaTypeFormatter GetPerRequestFormatterInstance(Type type, HttpRequestMessage request, MediaTypeHeaderValue mediaType)
        {
            // call base to validate parameters
            base.GetPerRequestFormatterInstance(type, request, mediaType);

**Comment by xuzhg** [comment]
@jackfree Thanks your input.

Below is the source codes of the `MediaTypeFormatter` class that the WAO is referencing:

```C#
public virtual MediaTypeFormatter GetPerRequestFormatterInstance(Type type, HttpRequestMessage request, MediaTypeHeaderValue mediaType)
{
    if (type == null)
     {
            throw Error.ArgumentNull("type");
     }
     if (request == null)
     {
           throw Error.ArgumentNull("request");
      }

      return this;
}

```

You see, it's simple. So I don't think it's time consuming. Please reopen it if you have further concern.
