### ISSUE TITLE
BaseAddressFactory does not work - custom delegate methods are never invoked.

### ISSUE THREAD

**Issue by jackfree** [OData/WebApi#704]
The copy constructor for ODataMediaTypeFormatter does not copy over the value of the BaseAddressFactory.  Since a new ODataMediaTypeFormatter is created for every single request, the value of the property is lost, and custom implementations are never invoked.

Related to Issue #160 -- It seems like a fragile approach to have to copy over ODataMediaTypeFormatter members and create a new one for every single request.  Why is this necessary?

**Comment by xuzhg** [comment]
Merged the PR, Thanks your contribution.
