### ISSUE TITLE
V5.9 causes Object Reference Not Set errors on endpoints that 5.8 worked fine on

### ISSUE THREAD

**Issue by JohnGalt1717** [OData/WebApi#709]
And the endpoints aren't even being called with oData parameters. As a result we haven't been able to upgrade. Changing the return type from IQueryable to IEnumerable solves the issue for obvious reasons but then we lose oData.

**Comment by VikingsFan** [comment]
@JohnGalt1717 is there more detail about the error, or a repro is very important for us to investigate

**Comment by VikingsFan** [comment]
Close as two weeks no response, pls reopen this if you have detail info.

**Comment by JohnGalt1717** [comment]
I'm trying to figure out how I can create a repro for you given that it's IQueryable against an Entity Framework database with proprietary DTOs with a custom Json formatter. I'd have to give you a database that it could query against, the dtos that it's mapping to, and the json formatter which is problematic.

**Comment by VikingsFan** [comment]
@JohnGalt1717 maybe you can refer to our E2E test to create a small repro. https://github.com/OData/WebApi/tree/master/OData/test/E2ETest/WebStack.QA.Test.OData

**Comment by VikingsFan** [comment]
Close this issue as no-repro details, please open a new issue with detail information.
