### ISSUE TITLE
Support delta for webapi

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#71]
Support incremental maintenance of local results through "Delta Queries".  

[ https://www.google.com/url?q=https://www.oasis-open.org/committees/download.
php/46575/OData%2520Deltas.pptx&sa;=U&ei;=0uYrU9a1JITmoAS_4oD4CQ&ved;=0CAYQFjA
A&client;=internal-uds-cse&usg;=AFQjCNFuY79yA6cWOGGqE_KW-m4WPZAQuA
](https://www.google.com/url?q=https://www.oasis-open.org/committees/download.
php/46575/OData%2520Deltas.pptx&sa=U&ei=0uYrU9a1JITmoAS_4oD4CQ&ved=0CAYQFjAA&c
lient=internal-uds-cse&usg=AFQjCNFuY79yA6cWOGGqE_KW-m4WPZAQuA)  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1788](http://aspnetwebstack.codeplex.com/workitem/1788)
**Status:** Active
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Mar 21, 2014 at 8:15 AM
**Reported by:**    zjufish
**Updated on:** Apr 17, 2014 at 10:35 AM
**Updated by:** zjufish

**Comment by mikepizzo** [comment]
Delta responses can be read/written in WebAPI 6.x by adding EdmDeltaEntity, EdmDeltaDeletedEntity, EdmDeltaLink, and EdmDeltaDeletedLink objects to an EdmChangedObject collection.
