### ISSUE TITLE
ETag parsing: protocol states opaque quoted string (on OData oasis spec), but current implementation is base64 encoding

### ISSUE THREAD

**Issue by rjjkathy** [OData/WebApi#710]
Here is the protocol reference:
http://www.ietf.org/rfc/rfc7232.txt 
http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#HTTPConditional> 

Currently ETag parsing implementation requires base64 string

1. if using base64 unquoted string
The client header will be If-Match: IjEzMGExODc0LTI3YzgtNDI4Mi1iZDMzLWEzODA0MzFlODUzNSI=
which during parsing ETag, this line will return null and causing etag not populated in ODataQueryOptions: options.Request.Headers.IfMatch.SingleOrDefault();

2. if using protocol specified in spec, non-base 64 quoted string
Exception: base64 string required

3. if using base64 quoted string
Client header looks like: If-Match: "IjEzMGExODc0LTI3YzgtNDI4Mi1iZDMzLWEzODA0MzFlODUzNSI="
Value picked up in ODataQueryOptions: Tag: "\"IjEzMGExODc0LTI3YzgtNDI4Mi1iZDMzLWEzODA0MzFlODUzNSI=\""
That will cause the "\" unrecognized exception.

Overall, the implementation should follow the public protocol stated in the specs, ie. quoted opaque string.

**Comment by xuzhg** [comment]
[HTTP specification section 3.11]( http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.11) says:

_...An entity tag consists of an opaque **quoted** string, possibly prefixed by a weakness indicator._ 

So,  

* In Item 1, you provide an invalid entity tag.

* In Item 2, Web API OData provides the default odata.etag wrapper format, it's the base64. If you don't override the default behavior, you must obey this rule. Of course, it's easy to override the default behavior, please see [here](https://github.com/xuzhg/WebApiSample/tree/master/Microsoft.AspNet.OData.Test/ETag) . 

* In Item3, decord base64 from **IjEzMGExODc0LTI3YzgtNDI4Mi1iZDMzLWEzODA0MzFlODUzNSI=**, it's a guid string with double quoted as "\"130a1874-27c8-4282-bd33-a380431e8535\"". It's not valid odata guid uri literal. 
    if you use the `DefaultODataETagHandler`, 
  the `EntityTagHeaderValue` for object `new Guid("130A1874-27C8-4282-BD33-A380431E8535")` is 
**"\"MTMwYTE4NzQtMjdjOC00MjgyLWJkMzMtYTM4MDQzMWU4NTM1\""**

please verify your scenario. Thanks.
