### ISSUE TITLE
Using same enum twice in a model causes null reference exception

### ISSUE THREAD

**Issue by VitaliyKurokhtin** [OData/WebApi#711]
Following model breaks EDM model build:

```
[DataContract(Name = "foo")]
public class Foo {
    [DataMember(Name = "bar1")]
    public Bar Bar1 { get; set; }

    [DataMember(Name = "bar2")]
    public Bar Bar2 { get; set; }
}

[DataContract(Name = "bar")]
public enum Bar {
    [EnumMember(Value = "bar-value-1")]
    Value1,
    [EnumMember(Value = "bar-value-2")]
    Value2
}
```

Code to build mode:

```
var builder = new ODataConventionModelBuilder();
builder.EntitySet<Foo>("foos");
var model = builder.GetEdmModel();
```

### Assemblies affected
System.Web.OData, at least since 5.9.  

### Reproduce steps
Just copy paste code from above and run it.  

### Expected result
Normal model should be built, taking into account DataContract and EnumMember settings.

### Actual result
NullReferenceException is thrown.

### Additional details
This happens because of logic in ODataConventionModelBuilder.AddEnumType. When it's called for first time

**Comment by VikingsFan** [comment]
Merged 529d3453b97a44911148a558b9857b8a99546a85
