### ISSUE TITLE
Moving to 5.9.0 from 5.8.0 broke AutoExpand property functioning

### ISSUE THREAD

**Issue by atrumas** [OData/WebApi#713]
The problem is pretty simple, after updating to 5.9.0 I can no longer use the [AutoExpand] attribute to make oData automatically expand data structures without using the [EnableQuery] and $expand, it simply doesn't return the objects at all on client side, which it did without any problems in 5.8.0

**Comment by VikingsFan** [comment]
@atrumas can you try with [EnableQuery] attribute, it's by design that [AutoExpand] attribute work with [EnableQuery] attribute, we make this change for better support both EF and in-memory data source.

**Comment by atrumas** [comment]
I've just tried out using it with [EnableQuery] and it does indeed work, however that brings a few problems, main being the fact that I'm using count to return full result count from the server, with only top=20 selected for paging and I can't do that with [EnableQuery] attribute since it automatically lowers the count results down to what ever the top is set. Is there any way to use [AutoExpand] without using [EnableQuery] like you could in 5.8.0 then?

**Comment by VikingsFan** [comment]
@atrumas you can have a customized EnableQueryAttribute and choose which queryOption not to apply, or just return the original queryable:


        public class MyEnableQueryAttribute : EnableQueryAttribute
        {
            public override IQueryable ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
            {
                // won't apply the $top
                return queryOptions.ApplyTo(queryable, AllowedQueryOptions.Top);
            }
        }

**Comment by atrumas** [comment]
That's not the key problem I'm having with [EnableQuery], guess I should have tried explaining better.

Thing is, I want to apply the $top filter, problem with it is, it's not returning the value it's supposed to.

Say I'm returning results as PageResult:
`        public static PageResult<T> ToPageResult<T>(this ListQueryResult<T> res)
        {
            return new PageResult<T>(res.Items, null, res.TotalCount);
        }`

The problem I have with [EnableQuery] is that it ruins the result data. If my res.TotalCount here is set to say value 47, somewhere under the hood the [EnableQuery] attribute changes that returned res.TotalCount and it return the count shrinks to what ever the $top is set to, like here in my query I have $top=20, the result returned is 
`@odata.context:"http://localhost:2028/api/$metadata#MessagesOData"
@odata.count:20
value:[{Id: 177, PersonalMessageId: 283,…},…]`
With the count being reset to 20, despite the fact that I'm returning 47 server side.

And according to OData specification, what it should do, is return the count 47, but trim the value results to 20.

**Comment by VikingsFan** [comment]
Can you show your controller's code?

**Comment by atrumas** [comment]
It's probably not going to help you out on it's own so I'm adding all the functions that it's calling:

```
        public PageResult<TListItem> Get(ODataQueryOptions<TListItem> options, string extendedFilter, string mainFilter, string fullTextFilter = null)
        {
            return messageBll
                .GetPageDataForBrowser<TListItem>(
                    options.ToSimplified(FormatExtendedFilter(extendedFilter), mainFilter, fullTextFilter))
                .ToPageResult();
        }
```

The functions are as follows:
```
 public ListQueryResult<TListEntity> GetPageDataForBrowser<TListEntity>(QueryOptions options)
             where TListEntity : class
        {
            var criteria = GetODataCriteria<TListEntity>(options);

            if (!String.IsNullOrEmpty(options.ExtendedFilter))
                ApplyExtendedFilter(criteria, options.ExtendedFilter);

            if (!String.IsNullOrEmpty(options.MainFilter))
                ApplyMainFilters(criteria, options.MainFilter);

            if (!String.IsNullOrEmpty(options.FullTextFilter))
                ApplyFullTextFilter<TListEntity>(criteria, options.FullTextFilter);

            int count = GetTotalCount(criteria);

            criteria.SetFirstResult(options.Skip).SetMaxResults(options.PageSize);

            SetOrder(criteria, options);

            return new ListQueryResult<TListEntity>
                {
                    Items = criteria.List<TListEntity>(),
                    TotalCount = count
                };
        }
```


```
        public static QueryOptions ToSimplified(
            this ODataQueryOptions options,
            string extendedFilter = null,
            string mainFilter = null,
            string fullTextFilter = null)
        {
            return new QueryOptions
                {
                    Filter = options.Filter != null ? options.Filter.RawValue : String.Empty,
                    Skip = options.Skip != null ? options.Skip.Value : 0,
                    PageSize = options.Top.Value,
                    Order = options.OrderBy != null ? options.OrderBy.RawValue : String.Empty,
                    ExtendedFilter = extendedFilter,
                    MainFilter = mainFilter,
                    FullTextFilter = fullTextFilter
            };
        }
```

```
        public static PageResult<T> ToPageResult<T>(this ListQueryResult<T> res)
        {
            return new PageResult<T>(res.Items, null, res.TotalCount);
        }
```

**Comment by VikingsFan** [comment]
can you try these code? 

    public class MyEnableQueryAttribute : EnableQueryAttribute
        {
            public override IQueryable ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
            {
                // won't apply anything.
                return queryable;
            }
        }

**Comment by VikingsFan** [comment]
It seems that you have already apply top and if you use EnableQuery attribute, it will apply the query option again, so the result count is not right, so can you try my suggested customized attribute and put the query option you have already applied to the second parameter, so EnableQuery won't apply again.

**Comment by atrumas** [comment]
If I'm using it as [EnableQuery, MyEnableQuery] now, nothing changes, the count still gets reduced to whatever top is.

I've tried replacing [EnableQuery] with just [MyEnableQuery] and the result was really odd as it only returned the result that didn't contain count at all and it also didn't return the [AutoExpand] properties.

**Comment by VikingsFan** [comment]
sorry for the late reply:

        public class MyEnableQueryAttribute : EnableQueryAttribute
        {
            public override IQueryable ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
            {
                // won't apply the $top & $count & ...
                return queryOptions.ApplyTo(queryable, AllowedQueryOptions.Top | AllowedQueryOptions.Count);
            }
        }

            [MyEnableQueryAttribute]
            public IQueryable<AutoExpandedCustomer> Get()
            {
                // your code to get a result that already applied top and orderby and so on.
                // set the totalcount
                queryOptions.Request.ODataProperties().TotalCount = 10;
                return _autoCustomers;
            }


url: http://localhost/odata/AutoExpandedCustomers?$top=5&$count=true

response: 
`{ "@odata.context":"http://localhost/odata/$metadata#AutoExpandedCustomers","@odata.count":10,"       value":[{"Id":1,"Category":"@odata.type":"#System.Web.OData.Test.PremiumEnableQueryCategory","Id":1234,"PremiumLevel":5678}}]}`

we can see there is a `odata.count` set by myself and expanded `Category`.

**Comment by atrumas** [comment]
Guess I'm pretty much stuck with using a custom serializer to return OData results since AutoExpand only works with EnableQuery attribute and I'd have to return IQueryable instead of PageResult otherwise.

Okay, thanks for helping out.
