### ISSUE TITLE
oDataQueryOptions not apply with select statement

### ISSUE THREAD

**Issue by biren-patel** [OData/WebApi#717]
I am newbee in oData. I have integrate oData with WebAPI.
Its worked fine with all operations listed below :

localhost/Default?$top=1
localhost/Default?$filter=ProductName eq %27MOBILE%27

as well other option also but when i apply to select particular columns from all then it will throw error.
localhost/Default?$select=ProductName,ProductSKU

[EnableQuery]
public IEnumerable<Product> Get(ODataQueryOptions<Product> queryOptions)
{
            IQueryable result = queryOptions.ApplyTo(_oEntity.Products.AsQueryable());
            return result as IEnumerable<Product>;
 }

Product class have also other attribute
  public class Product
    {
        public Product();

        public virtual Category Category { get; set; }
        public int? CategoryId { get; set; }
        public string Features { get; set; }
        public double? Price { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductSKU { get; set; }
        public virtual Supplier Supplier { get; set; }
        public int? SupplierId { get; set; }
    }

**Comment by VikingsFan** [comment]
EnableQuery attribute will apply the query option for you, change your code to:

[EnableQuery]
public IEnumerable Get()
{
    return _oEntity.Products;
}

**Comment by biren-patel** [comment]
Hi VikingsFan

Thanks but I need to pass that oDataQueryOptions to other function not same function. 
If i want to do that using oDataQueryOptions.

**Comment by VikingsFan** [comment]
then you can do with :
 public class MyEnableQueryAttribute : EnableQueryAttribute
    {
        public override IQueryable ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
        {
            // do something here
            return base.ApplyTo(queryable, queryOptions);
        }
    }

then use MyEnableQuery in your controller method.

**Comment by biren-patel** [comment]
It still not working.

**Comment by xuzhg** [comment]
@biren-patel Can you give us a repo or a detail information?
