### ISSUE TITLE
ODataSwaggerConverter throws exception on composite keys

### ISSUE THREAD

**Issue by jasontho-ms** [OData/WebApi#719]
ODataSwaggerConverter throws exception on composite keys due to bug in ODataSwaggerUtilities.cs

### Assemblies affected
System.Web.OData.dll

### Reproduce steps
Create a model containing an entity with a composite key and attempt to generate swagger metadata with ODataSwaggerConverter

### Expected result
The metadata is generated successfully

### Actual result
Exception is thrown (see text below)

### Additional details
ExceptionMessage":"Can not add property format to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.","ExceptionType":"System.ArgumentException","StackTrace":" at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)\r\n at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)\r\n at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)\r\n at System.Web.OData.ODataSwaggerUtilities.Parameter(JArray parameters, String name, String kind, String description, String type, String format)\r\n at System.Web.OData.ODataSwaggerUtilities.CreateSwaggerPathForEntity(IEdmNavigationSource navigationSource)\r\n at System.Web.OData.ODataSwaggerConverter.InitializeContainer()\r\n at System.Web.OData.ODataSwaggerConverter.GetSwaggerModel()

**Comment by jasontho-ms** [comment]
Add pull request https://github.com/OData/WebApi/pull/720

**Comment by VikingsFan** [comment]
Merged  80c718f
