### ISSUE TITLE
The Int64 and Decimal type property value should be serialized as string if IEEE754Compatible is set to true. 

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#72]
The Int64 and Decimal type property value should be serialized as string if
IEEE754Compatible is set to true.  
But currently it is not.  

Sample Request:  

```
GET http://jinfutanwebapi2:9123/convention/Employees?$format=application/json;odata.metadata=none;IEEE754Compatible=true HTTP/1.1
Host: jinfutanwebapi2:9123
```

Sample Response:  

```
HTTP/1.1 200 OK
Content-Length: 1000
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
OData-Version: 4.0
Date: Mon, 24 Mar 2014 02:12:45 GMT

{
  "@odata.context":"http://jinfutanwebapi2:9123/convention/$metadata#Employees","value":[
    {
      "#WebStack.QA.Test.OData.Enums.AddSkill1":{

      },"ID":1,"Name":"Name1","SkillSet":[
        "CSharp","Sql"
      ],"Gender":"Female","AccessLevel":"Execute","FavoriteSports":{
        "LikeMost":"Pingpong","Like":[
          "Pingpong","Basketball"
        ]
      }
    },{
      "#WebStack.QA.Test.OData.Enums.AddSkill1":{

      },"ID":2,"Name":"Name2","SkillSet":[

      ],"Gender":"Female","AccessLevel":"Read","FavoriteSports":{
        "LikeMost":"Pingpong","Like":[
          "Pingpong","Basketball"
        ]
      }
    },{
      "#WebStack.QA.Test.OData.Enums.AddSkill1":{

      },"ID":3,"Name":"Name3","SkillSet":[
        "Web","Sql"
      ],"Gender":"Female","AccessLevel":"Read, Write","FavoriteSports":{
        "LikeMost":"Basketball","Like":[
          "Pingpong","Basketball"
        ]
      }
    }
  ]
}
```

Where ID is of type int64.  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1793](http://aspnetwebstack.codeplex.com/workitem/1793)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Mar 24, 2014 at 3:29 AM
**Reported by:**    jinfutan
**Updated on:** Oct 22, 2014 at 1:16 PM
**Updated by:** greggbjensen

**Comment by LianwMS** [comment]
On *2014-10-22 20:16:36 UTC*, **greggbjensen** commented:

This would seem to be a major problem with using Int64 and Decimal within JavaScript using JSON.parse(). Shouldn't this be a higher priority?

**Comment by mnahkies** [comment]
As far as I understand this can be fixed / implemented by simply adding the appropriate media types to the Odata JSON formatter.

Ref: https://github.com/OData/WebApi/blob/326d9a497f9de8f48b9fe483846dc7387c789532/src/System.Web.OData/OData/Formatter/ODataMediaTypeFormatters.cs#L90-L101
