### ISSUE TITLE
ODataUriParser broken with Enum key templates

### ISSUE THREAD

**Issue by grant77** [OData/WebApi#723]
If the Entity has an enum key defined as the single key or within a composite key and you try to parse a template such as "media(id={id},type={type})" it will fail.  If I redefine type as a string instead of an enum, it works.

### Assemblies affected
Microsoft.OData.Core.dll version 6.15.0.0

### Reproduce steps
namespace Test
{
    public enum MediaType
    {
        ClubLogo = 1,
        MemberPhoto = 2
    }

    public class MediaDto
    {
        [Key]
        public int Id { get; set; }

        [Key]
        public MediaType Type { get; set; }
    }

    public class Global : HttpApplication
    {
        protected void Application_Start(object sender, EventArgs e)
        {
            IEdmModel model = null;
            GlobalConfiguration.Configure(config =>
            {
                config.EnableEnumPrefixFree(true);

                var builder = new ODataConventionModelBuilder();
                builder.EnableLowerCamelCase();
                builder.EntitySet<MediaDto>("media");
                model = builder.GetEdmModel();

                config.MapODataServiceRoute("odata", "odata", model);
            });

            var parser = new ODataUriParser(model, new Uri("media(id={id},type={type})", UriKind.Relative));
            parser.Resolver = new StringAsEnumResolver();
            parser.EnableUriTemplateParsing = true;
            try
            {
                // Note: this will work if MediaDto.Type is declared as a string instead of enum.
                var path = parser.ParsePath();
            }
            catch (Exception ex)
            {
                // Bad Request - Error in query syntax.
                throw;
            }
        }
    }
}
### Expected result
No exception thrown

### Actual result
Exception is thrown

### Additional details
The problem code is located here: Microsoft.OData.Core.UriParser.Parsers.SegmentArgumentParser.TryConvertValue

It should call UriTemplateParser.TryParseLiteral if it is an enum as well.

**Comment by xuzhg** [comment]
@grant77 It's the same issue as https://github.com/OData/WebApi/issues/722

I will resolve it as duplicated. Does it work for you?  Thanks.

**Comment by grant77** [comment]
Yes.

**Comment by xuzhg** [comment]
Resolved as duplicated as #722; Thanks your input.
