### ISSUE TITLE
Model Binding broken with Enum Keys

### ISSUE THREAD

**Issue by grant77** [OData/WebApi#724]
Model binding does not work with enum keys because the RouteData for the enum key contains the UriEnumLiteral.  (ie, Test.MediaType'1' ).  Had it just been "1" or "ClubLogo" it would work.

### Assemblies affected
Microsoft.OData.Core.dll version 6.15.0

### Reproduce steps

namespace Test
{
    public enum MediaType { ClubLogo = 1, MemberPhoto = 2 }

    public class MediaDto
    {
        [Key]
        public MediaType Id { get; set; }
        public string Name { get; set; }
    }

    public class MediaController : ODataController
    {
        // Made nullable for display purposes
        public MediaDto Get(MediaType? key)
        {
            if (!ModelState.IsValid)
            {
                var message = string.Format(@"Model binding failed because RequestContext.RouteData.Values[""key""] = '{0}'", RequestContext.RouteData.Values["key"]);
                throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.InternalServerError, new HttpError(message)));
            }
            return new MediaDto { Id = key.Value, Name = "Dummy" };
        }
    }

    public class Global : HttpApplication
    {
        protected void Application_Start(object sender, EventArgs e)
        {
            IEdmModel model = null;
            GlobalConfiguration.Configure(x =>
            {
                var builder = new ODataConventionModelBuilder();
                builder.EnableLowerCamelCase();
                builder.EntitySet<MediaDto>("media");
                model = builder.GetEdmModel();
                x.EnableEnumPrefixFree(true);
                x.MapODataServiceRoute("odata", "odata", model);
            });

            var client = new HttpClient();
            client.GetAsync("http://localhost:60667/odata/media('ClubLogo')").ContinueWith(async x =>
            {
                var content = await x.Result.Content.ReadAsStringAsync();
                /*
                    {
                      "error":{
                        "code":"","message":"Model binding failed because RequestContext.RouteData.Values[\"key\"] = 'Test.MediaType'1''"
                      }
                    }
                */
            });
        }
    }
}

### Expected result
{
  "@odata.context":"http://localhost:60667/odata/$metadata#media/$entity","id":"ClubLogo","name":"Dummy"
}

### Actual result
{
    "error":{
    "code":"","message":"Model binding failed because RequestContext.RouteData.Values[\"key\"] = 'Test.MediaType'1''"
    }
}

### Additional details
The problem occurs inside DefaultODataPathHandler when it calls ODataPathSegmentTranslator.TranslateODataLibPathToWebApiPath.  The KeyValuePathSegment value is Test.MediaType'1' which cannot be bound to an enum unless you create a custom model binder.  Somewhat related to the other bug I reported: https://github.com/OData/WebApi/issues/723

**Comment by xuzhg** [comment]
@grant77 

It should work to add [FromODataUri], for example:
```
Get([FromODataUri] MediaType? key)
```

**Comment by xuzhg** [comment]
of course,  would you please take a look the PR #724?

**Comment by grant77** [comment]
Adding FromODataUriAttribute does work, but it should not be required (in my opinion).  Shouldn't the default rules that apply to basic Web API also apply to OData?  In basic Web API, the FromUriAttribute is implied since it is a "simple" type and the binding works without the attribute.  The default rules I am referring to come from here:  http://www.asp.net/web-api/overview/formats-and-model-binding/parameter-binding-in-aspnet-web-api

Note:  If the enum key were added to the route data as "1" or "ClubLogo", the binding would work without FromODataUriAttribute .

**Comment by grahamehorner** [comment]
I believe that binding of models and parameters changed in aspnetcore you need to explicitly state the bindings as the default pre aspnetcore is considered a security risk.

**Comment by xuzhg** [comment]
From OData, the enum type is not a "simple" type, it's similar as entity/complex type. Besides, the enum value in request Uri is an OData enum value (EdmEnumValue), it must obey the enum literal rule no matter whether it's enum prefix free or not. So, the enum parameter should be prefix with [FromODataUri]

However, it's better if the enum parameter can work without [FromODataUri]. So, 
My PR #724 tries to make the enum key working with/without the [FromODataUri]. Would you please give me some feedback?

**Comment by grant77** [comment]
Yes.  Please make the enum key work without the [FromODataUri].

**Comment by xuzhg** [comment]
@grant77 Would you please try the commit? Any feedback is welcome. Thanks.

**Comment by grant77** [comment]
I tried the commit with the code sample at beginning of this thread.  It worked.  Thank you.  There are a lot more code changes then I anticipated.  Wow!  The class, "ODataPathSegmentExtenstions", is spelled incorrectly.  Please rename to "ODataPathSegmentExtensions".

**Comment by xuzhg** [comment]
Yes. I changed it. See 1846c0c1d4424685abbe59d0928ef0ad146f5ce4 Thanks
