### ISSUE TITLE
OData Parser leaves extra single quotes around string tokens

### ISSUE THREAD

**Issue by CzPete** [OData/WebApi#725]
When using attribute parsing, parsed tokens are often enclosed in extra single quotes.

### Assemblies affected
Namespace: System.Web.OData.Routing
Assembly: Microsoft.AspNet.OData.5.9.0-beta\System.Web.OData.dll

### Reproduce steps
In controller, have a GET method, say GetTableDefinition(), with
[ODataRoute("TableDefinitions({tableId})")].

Call GET on serviceRoot/tableDefinitions/T34567

### Expected result
The parameter tableId in the GetTableDefinition has a value of "T34567".

### Actual result
The parameter tableId in the GetTableDefinition has a value of "'T34567'".
(note the extra single quotes)

### Additional details
This is happening for pretty much all string tokens. Integer tokens seem to be fine.
This issue was also present in earlier versions of WebApi.OData.

**Comment by chinadragon0515** [comment]
You can add‘[FromODataUri] for your parameter.This will remove the single quotes.
And copied from document, http://odata.github.io/WebApi/
‘[FromODataUri]’ is mandatory for complex, entity and all collection. However, it is optional for Primitive & Enum. But for string primitive type, the value will contain single quotes without ‘[FromODataUri]’.

**Comment by CzPete** [comment]
Thanks ☺ I noticed your response already.

Petr

**Comment by CzPete** [comment]
Yes, that worked. Thank you!
