### ISSUE TITLE
Support for JSON PATCH

### ISSUE THREAD

**Issue by Gebov** [OData/WebApi#728]
In addition to the $ref endpoints for managing relations to entities, it would be more convenient to support the JSON patch format described [here](https://tools.ietf.org/html/rfc6902)

**Comment by xuzhg** [comment]
@Gebov Thanks your input and the JSON patch format looks interesting. However, most of the operational can be finished with the OData CRUD request. Would you please let us know your scenarios with the JSON patch format in Web API OData? 
And, Welcome your contribution by sending us an implementation through pull request. Thanks.

**Comment by xuzhg** [comment]
Close it. Please reopen it if you have further concern.

**Comment by HappyNomad** [comment]
I am in the process of learning OData to create a Web API for miscellaneous partial updates of a large object graph.  I came across this issue and read the RFC.  It describes with succinct clarity how to fulfill my exact requirement.  I'm just getting started with OData, but so far it seems unnecessarily complex in comparison.

**Comment by HappyNomad** [comment]
I came across [this post](https://blogs.realdolmen.com/experts/2015/05/05/partial-updates-for-your-restful-api-with-jsonpatch-in-the-new-asp-net-5/) saying that ASP.NET Core will support Json Patch.  And Google reveals a lot of activity around this.

**Comment by xuzhg** [comment]
@HappyNomad 
Thanks your information. We hope Web API OData vNext can involve to Asp.NET Core. At that time, maybe we can consider to add the Json patch support and welcome your contribution. Thanks.
