### ISSUE TITLE
support cast for complex type and collections

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#73]
[ http://docs.oasis-open.org/odata/odata/v4.0/os/part2-url-
conventions/odata-v4.0-os-part2-url-conventions.html#_Toc372793843
](http://docs.oasis-open.org/odata/odata/v4.0/os/part2-url-
conventions/odata-v4.0-os-part2-url-conventions.html#_Toc372793843)  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1804](http://aspnetwebstack.codeplex.com/workitem/1804)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 27, 2014 at 5:12 AM
**Reported by:**	zjufish
**Updated on:**	Dec 10, 2014 at 12:31 AM
**Updated by:**	yishaigalatzer

**Comment by xuzhg** [comment]
already supported about the complex type cast. Close it.
