### ISSUE TITLE
[vNext] Complex types through API context type

### ISSUE THREAD

**Issue by Asido** [OData/WebApi#730]
### Assemblies affected

vNext branch (168b18e)
### Reproduce steps

``` C#
public class ActionModel
{
    public int SomeInt { get; set; }
    public string SomeString { get; set; }
}

public interface IDataContext
{
    [ODataAction(IsBound = false)]
    string SomeAction(ActionModel model);
}

public void Configure(IApplicationBuilder app)
{
    app.UseOData<IDataContext>("OData");
}
```
### Expected result

`ActionModel` is registered as ComplexType.
### Actual result

`System.InvalidOperationException: The entity 'ActionModel' does not have a key defined.`
Or gets registered as EntityType if I add `ActionModel.Id` property.
### Additional details

Looking at `DefaultODataModelProvider.BuildEdmModel()` implementation I don't see that it is able to register complex types.
### Proposal
1. There are `ODataActionAttribute`, `ODataFunctionAttribute`, `ContainedAttribute` ... Wouldn't it make sense to have `ComplexTypeAttribute` for classes?
2. Somewhat silly, but implicitly register structs as ComplexType?
3. Allow to flatten model properties into action args:

``` C#
public interface IDataContext
{
    [ODataAction(IsBound = false)]
    string SomeAction(int someInt, string someString);
}
```

Is there already a way to achieve what I want?
If not, is this open for contribution?

**Comment by xuzhg** [comment]
@Asido  We are looking for your contribution. Thanks.

**Comment by Asido** [comment]
I was looking for your feedback first.
