### ISSUE TITLE
ODataMediaTypeFormatter and virtual members

### ISSUE THREAD

**Issue by wasphub** [OData/WebApi#737]
I would like to understand how one would be supposed to derive properly a new formatter from [ODataMediaTypeFormatter](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.Http.OData/OData/Formatter/ODataMediaTypeFormatter.cs), given that it exposes virtual methods and therefore subclassing should be accepted practice.

In my case I wanted to add some orthogonal logic inside methods like `WriteToStreamAsync`, and then let the base implementation do the actual job, but if I do that the base implementation complains that the **internal** `Request `member is not properly initialized. I was able to work around this assigning the property inside my override of `GetPerRequestFormatterInstance` through reflection (o_O), but either I'm missing a proper way to setup and initialize a derived class, or I do not see the point of having virtual methods like that if then the base implementation cannot be called without dirty tricks.

Would it be such a big concern to have the `Request `property _at least_ protected?

**Comment by VikingsFan** [comment]
@wasphub it would be very appreciate to send us a PR about this issue and show your scenario in test case :)

**Comment by wasphub** [comment]
I'm not sure it really makes sense. I do not have any particular bug to describe and test case to reproduce, it's more the logic around having the `Request `member as internal in a class that exposes virtual methods but disallows calling the corresponding overridden base members because the `Request `member is not set. The way those members refuse to execute is through an exception, so yes I could build a repro, but maybe the issue could be reasoned about staying on a logical level by looking at [the source code](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.Http.OData/OData/Formatter/ODataMediaTypeFormatter.cs), couldn't it? :)

In practice:


* `WriteToStreamAsync `[is not sealed](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.Http.OData/OData/Formatter/ODataMediaTypeFormatter.cs#L384), therefore it allows derived types to override it
* During execution [it throws an exception if the `Request `member is not assigned](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.Http.OData/OData/Formatter/ODataMediaTypeFormatter.cs#L395)
* the `Request` member [is internal](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.Http.OData/OData/Formatter/ODataMediaTypeFormatter.cs#L189), and the only costructor which assigns it [is internal too](url) (meant to be used from `GetPerRequestFormatterInstance `only)
* hence, there is no way to override a method in a derived type and call the base implementation where suited (unless Reflection is used)

If you still think a PR is needed I'll try to prepare it but it might take me a while...

**Comment by VikingsFan** [comment]
@wasphub if current implementation with protected Request is enough, PR is not needed :) Thanks

**Comment by wasphub** [comment]
It would be indeed :) Thx!

**Comment by wasphub** [comment]
The specific logic I need to implement might be misleading (it's more a hack than anything else, and for very specific reasons), but the general reasoning could be applied to other aspects (logging for example). In any case, what I'm trying to do it this (simplified):

```
public override Task WriteToStreamAsync(Type type, object value, Stream writeStream, HttpContent content,
	TransportContext transportContext, CancellationToken cancellationToken)
{
	var entityType = type.GetDeepestType();

	try
	{
		base.WriteToStreamAsync(type, value, writeStream, content, transportContext, cancellationToken)
			.Wait(cancellationToken);
	}
	catch (Exception ex)
	{
		Log.ForContext("Type", entityType)
		   .Error(ex, $"Error while streaming entities of type {{Type}} as {string.Join(",", SupportedMediaTypes.Select(v => v.MediaType))}");
		throw;
	}
	return Task.FromResult((object)null);
}
```

The whole point is, the normal behaviour of `WriteToStreamAsync` in `ODataMediaTypeFormatter` is done in a way that, if coupled with other pieces of logic to do, for example, compression of the output stream, any error happening during the streaming is not intercepted by the right thread and therefore the client gets a 200 OK even if the response is corrupted. By doing a forced `.Wait()` on the base `WriteToStreamAsync` call I manage to keep it on the streaming thread, therefore any error from there causes a 504, which is the best I can do to signal an error once the headers are already written, preventing the client from consuming a corrupted response while still being able to stream and compress it (some responses could be huge).

The whole thing is pretty complicated and a bit hacky, but this simple workaround does the job and, although not ideal at all (it might hinder scalability), at the moment it's good enough for me.

This works _only because_ the `GetPerRequestFormatterInstance` override I wrote sets the internal `Request` member by using Reflection.
