### ISSUE TITLE
There is no way to set OData reference in metadata.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#74]
If you are composing several metadata documents and want to reference them the
specification states to use "edmx:Reference". This has no support in the web
stack or EDM libs.  
  
[ http://docs.oasis-open.org/odata/odata/v4.0/os/part3-csdl/odata-v4.0-os-
part3-csdl.html#_Toc372793886 ](http://docs.oasis-
open.org/odata/odata/v4.0/os/part3-csdl/odata-v4.0-os-
part3-csdl.html#_Toc372793886)  
  
Please provide support for this. There is support for adding annotations, but
without adding the external reference to the core annotations document (i.e. [
http://docs.oasis-
open.org/odata/odata/v4.0/csprd02/vocabularies/Org.OData.Core.V1.xml
](http://docs.oasis-
open.org/odata/odata/v4.0/csprd02/vocabularies/Org.OData.Core.V1.xml) ) or any
of the other vocabulary documents these annotations/terms are not recognized.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1808](http://aspnetwebstack.codeplex.com/workitem/1808)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 28, 2014 at 4:44 PM
**Reported by:**	thebothead
**Updated on:**	Apr 17, 2014 at 10:37 AM
**Updated by:**	zjufish

**Comment by LianwMS** [comment]
On *2014-04-17 17:36:42 UTC*, **zjufish** commented:

we has this feature in new odl lib already. will integreate with webapi after RTM

**Comment by xuzhg** [comment]
You can call the following API to add reference model.

```
EdmModel model = ...
model.AddReferencedModel(referenceModel);
```

Thanks.
