### ISSUE TITLE
String parameter handling breaks with . ?

### ISSUE THREAD

**Issue by TehWardy** [OData/WebApi#740]
String parameter handling breaks with "." (dot) in them ...
### Assemblies affected

System.Web.OData 5.7
### Reproduce steps

Define this function on an endpoint ...

```
var getResource = Builder.EntityType<ResourceString>().Collection.Function("GetResource");
getResource.Parameter<string>("path");
getResource.Parameter<string>("culture");
getResource.Returns<Resource>();
```

With this method in the controller ...

```
[HttpGet]
[ODataRoute("GetResource(path={path},culture={culture})")]
public async Task<IHttpActionResult> GetResource([FromODataUri]string path, [FromODataUri]string culture)
{
    try
    {
        //TODO: resourcePath.Replace("_", ".") <-- figure out why this breaks the routing
        return Ok(service.GetResource(path.Replace("_", "."), culture));
    }
    catch (Exception ex)
    {
        return await Failed(ex);
    }
}
```
### Expected result

Issue http GET request with url ~/OData/ControllerName/GetResource(path='foo.bar', culture='en-gb')
### Actual result

The presence of the "." in the path string causes the server to return a 404 for some reason, removing the "." removes the exception and everything works normally
### Additional details

I tried the same without OData, simply using a WebAPI controller and it didn't present the same behaviour.

**Comment by xuzhg** [comment]
@TehWardy 

In a typical IIS configuration, the dot in the URL will cause IIS to return error 404. 
you can change `path` attribute config in **Web.config**:

```xml
<add name="ExtensionlessUrlHandler-Integrated-4.0" path="*" verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
```
Please try it out and let us know the result? Thanks.

**Comment by TehWardy** [comment]
That's already in my config, I have dots in other URL's but for some reason this particular function seems to not like it.

**Comment by xuzhg** [comment]
@TehWardy  My path has value "*", your path has value "*.". Can you change it and see what happen?

**Comment by TehWardy** [comment]
Didn't help my situation ... 
I've also been having trouble with binding scenarios ... why does normal WebAPI type binding not work in OData and what's with these ODataActionParameter types that often don't parse json packets right at all?

I noticed that when I do something like this it all goes majorly wrong ...
```
public class Foo { ... }
public class Bar : Foo { ... }

public class SomeBaseDto {
      public Foo AThing { get;set; }
} 

public class SomeDto : SomeBaseDto {
    public new Bar AThing { get;set; }
}


public class SomeController : ODataController<SomeDto > {
         [HttpPost]
         public IHttpActionResult CustomAction(SomeDto data) { 
              //?!?!?!?!?! 
              // Why is data always null or partially parsed?
        }
}

```
At this point I have to resort to manually reading my post bodies and manually parsing the json as WebAPI / Odata just can't get their head round what's going on.


I'm thinking this model stuff could pretty much entirely go with some well defined attributes then the OData behaviour would be more like standard WebAPI.

**Comment by TehWardy** [comment]
Uh, sorry I took so long, been ableto work around this on 90% of cases.
@xuzhg removing that "." from the handler configuration fixes it.

Thanks :)
