### ISSUE TITLE
ends with starts with and contains do not work on version 5.9.0

### ISSUE THREAD

**Issue by marlongrech** [OData/WebApi#741]
Hi all 

Whenever you try to do something like 

http://localhost:5051/Accounts?$filter=startswith(comments,'te')

you get the following error 
![odata-bug](https://cloud.githubusercontent.com/assets/19221937/15495356/93f35026-218f-11e6-99a8-5d6ccc71ed34.PNG)

To resolve this I downgraded from 5.9.0 to 5.5.1

Regards

**Comment by VikingsFan** [comment]
@marlongrech Thanks for reporting this bug, I've tried with 5.9 with EF and didn't repro, can you share more detail or a minimal repro will be very helpful!

**Comment by marlongrech** [comment]
Apologies .. I finally found the issue. I was messing around and installed EF 7 beta 8. This was the issue. I remove this and now all working fine. 

Thanks

**Comment by VikingsFan** [comment]
Glad to see it works! Thanks
