### ISSUE TITLE
[vNext] Roadmap for ASP.NET Core 1.0 RC2?

### ISSUE THREAD

**Issue by alvachien** [OData/WebApi#744]
Is there a roadmap for ASP.NET Core 1.0 RC2?

The branch vNext got a latest checkin four month ago.

**Comment by xuzhg** [comment]
vNext is the key parts of Web API OData in the next several month.

**Comment by SamiMajed** [comment]
We just started working on a design that will provide an OData Web API and we would prefer to develop it using .NET Core. Unfortunately we learned that .NET Core does not support the ODataController which is necessary for OData v4. 
Could you please provide us with a timeline in regards to when the ODataController may be supported?

**Comment by DickvdBrink** [comment]
You can find a statement here: https://github.com/OData/WebApi/issues/229#issuecomment-194632766

It is pretty said, I'm really waiting for this to... I tried to update the vnext branch to rc2 with the new MVC and stuff but I had some problems with some stuff in the model builders.

**Comment by xuzhg** [comment]
@alvachien @SamiMajed @DickvdBrink vNext branch is updated to ASP.NET Core 1.0 RC2 final. See detail at 2b032b1dab87866cad3319a46d648f7252f5556d. Thanks your contribution.

**Comment by DickvdBrink** [comment]
Thanks This is pretty neat! :)

**Comment by alvachien** [comment]
Thanks to xuzhg.

One day before you update the vNext branch, that's June 27, the ASP.NET team [announce](https://blogs.msdn.microsoft.com/webdev/2016/06/27/announcing-asp-net-core-1-0/) the official release of ASP.NET Core 1.0. 

When will be the official release of OData Web API run on ASP.NET Core 1.0 then, thanks!

**Comment by jondavis-ineight** [comment]
It's not on their roadmap. They officially said it's not in their roadmap, and they still haven't declared that it has been put on their roadmap.

**Comment by candidodmv** [comment]
I'm excited to see this avaiable on vNext.
