### ISSUE TITLE
406 Error when using $apply aggregate function

### ISSUE THREAD

**Issue by kkopczyk** [OData/WebApi#759]
In my project, I have attempted to *not* use the [EnableQuery] attribute, but instead, call publicly available methods of System.Web.OData (queryOptions.ApplyTo()) so that I could have a little bit more control over the querying from within the controller (as opposed to relying on the OnExecuted event of EnableQueryAttribute).  I have done this for the following reasons:
- To support a theoretical problem of having a domain object stored across multiple entities.  If I need to query multiple entities in order to build a single domain object, I could (in theory) split apart the OData query, apply it to the multiple entities, build out a single domain object result set from the multiple entities, and pass this new results set as the result of the controller.
- To make it easier to unit test OData query results without using an ODataController.

Here is a code sample of an ODataController demonstrating this idea:
<pre>public class PricesController : ODataController
{
  public IHttpActionResult GetPrices(ODataQuery<Price> queryOptions)
  {
    MyDbContext dbContext = new MyDbContext();
    IQueryable<Price> basicQuery = dbContext.Prices;
    object advancedQuery = queryOptions.ApplyTo(basicQuery);
    
    // http://stackoverflow.com/questions/18879779/select-and-expand-break-odataqueryoptions-how-to-fix
    Type type = advancedQuery.GetType();
    Type resultType = typeof(OkNegotiatedContentResult<>).MakeGenericType(type);
    return Activator.CreateInstance(resultType, advancedQuery, this) as IHttpActionResult;
  }
}</pre>
In this code, I create the fully baked IQueryable prior to leaving the ODataController.  This seems to work great when using $filter or $select and I get the expected OData resultset in the browser.  However, it falls flat when using $apply/aggregate and I get a 406 error instead.  After digging into the source code, it looks like the reason is related to System.Web.OData not knowing how to serialize objects of type DynamicTypeWrapper (which gets used for aggregation specifically).  While I'm not sure if this is actually a bug or not, it does strike me as unexpected behavior and breaks the pattern I have developed.  Any advice/fix on how to proceed is appreciated.

### Assemblies affected
System.Web.OData 5.9.0

### Reproduce steps
I'm hoping my code sample above is enough to go on.  If not, I can upload a full VS solution to reproduce the behavior.

### Expected result
An OData result set when using $apply/aggregate.
`$apply=aggregate(Price with sum as Total)` (for example)

### Actual result
406 error from System.Web.OData

### Additional details
It looks like the reason is related to System.Web.OData not knowing how to serialize objects of type DynamicTypeWrapper.

**Comment by VikingsFan** [comment]
@kkopczyk will the customized EnableQuery Attribute be a work around for you? Code sample is in https://github.com/OData/WebApi/issues/521

**Comment by kkopczyk** [comment]
@VikingsFan Thank you for the response.  I was on vacation, and I will look at this very soon.

**Comment by kkopczyk** [comment]
@VikingsFan This works.  Thank you.
