### ISSUE TITLE
Add http header Prefer: odata.maxpagesize.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#76]
Download [
https://aspnet.codeplex.com/SourceControl/latest#Samples/WebApi/OData/v4/
](https://aspnet.codeplex.com/SourceControl/latest#Samples/WebApi/OData/v4/)
actions sample,  
1. Add[EnableQuery] to MoviesController.get() method 
2. request   
   
   ```
   GET http://localhost:44221/odata/Movies 
   ```
   
   Prefer: odata.maxpagesize=2

Expected: Only 2 movies are returned and with a continuous token  
Actual: All the movies are returned.  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1818](http://aspnetwebstack.codeplex.com/workitem/1818)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Apr 2, 2014 at 4:34 AM
**Reported by:**    jinfutan
**Updated on:** Apr 17, 2014 at 10:37 AM
**Updated by:** zjufish

**Comment by xuzhg** [comment]
Related to #693

**Comment by mikepizzo** [comment]
Closing due to lack of customer activity. Will re-visit based on any user feedback.
