### ISSUE TITLE
Release Notes Error

### ISSUE THREAD

**Issue by Vaccano** [OData/WebApi#760]
The release notes for the latest web API Osama release, the optimistic concurrency model and the Store generated pattern sections are identical. 

I imagine it is a copy paste error error.

**Comment by xuzhg** [comment]
@Vaccano Would you please give us the link of latest Web API Osama release?

**Comment by Vaccano** [comment]
This [Post](https://blogs.msdn.microsoft.com/odatateam/2016/05/13/announcement-web-api-odata-v5-9-release/) has a link to this [site](http://odata.github.io/WebApi/#07-15-5-9) where if you scroll down just a bit you will see the header: "8.1 ConcurrencyMode and ETag".

The content for that section is exactly the same as the next section: "8.2 StoreGeneratedPattern annotation"

(I realize now that this document is not really just "release notes", but the post said it was.)

**Comment by xuzhg** [comment]
Ok. Thanks your input. It was reported at #746. So, Close it as duplicated.
