### ISSUE TITLE
OData creating incorrect IQueryable on Expand

### ISSUE THREAD

**Issue by NathanNZ** [OData/WebApi#763]
I'm having an issue with OData throwing up the following exception - I'm at a loss what is causing it, and seeing that this is my second day implementing a OData endpoint I am not familiar enough with the code to debug this issue any further.

> Cannot compare 'member 'Elephants' of type 'Test.WebApi.OData.v1.ViewModels.ChildObjects.SessionChild''. Only primitive types, enumeration types and entity types are supported.

When I provide the following URL to the OData endpoint

> ElephantKids?$top=1&$expand=ElephantKidSessions($expand=Session)

The following query is what it seems to be evaluating to before it throws the exception upon evaluation. (no comparisons for the member Elephants as far as I can tell?)
http://pastie.org/private/wjdkfhlvs4agkglju7baag

It looks like the issue only occurs after OData merges the queryable (line 87 in SelectExpandBinder.cs) that has been processed by EF and Automapper with the following projectionLambda. Everything up to that projection lambda seems to be working fine and returning the populated DTO's as expected. (the contents of the projection lambda is below)
http://pastie.org/private/7aqvhhibtdktpqxqup2vlw

### Assemblies affected
OData 5.9.0

### Reproduce steps
Create a object that has a collection of child objects that also have their own collection of objects. This is different from the above example for simplicity sake.

Map them as so with the ConventionModuleBuilder
```
            v1builder.EntitySet<Elephant>("Elephants");
            v1builder.EntitySet<ElephantChild>("ElephantChildren");
            v1builder.EntitySet<ElephantOwner>("ElephantOwners");
            v1builder.EntitySet<Owner>("Owners");

```

> Elephant -> ElephantOwners -> Owner -> ElephantChildren

> Elephant{
> int Id
> string Name
> List<ElephantOwner> ElephantOwners
> }
> 
> ElephantOwner{
> ElephantChild Elephant
> Owner Owner
> DateTimeOffset OwnedDate
> }
> 
> Owner{
> int Id
> string Name
> List<ElephantChild> Elephants
> }
> 
> ElephantChild{
> int Id
> string Name
> }

-Try to query it with any query in OData with the expand query string.
> Elephants?$top=1&$expand=ElephantOwners($expand=Owner)
or
> Elephants?$top=1&$expand=ElephantOwners($expand=Owner($expand=Elephants))

### Expected result
The Elephants would successfully return with their respective owners, who would contain the elephants that they own.

### Actual result
OData errors with the exception
> 'Test.WebApi.OData.v1.ViewModels.ChildObjects.ElephantChild''. Only primitive types, enumeration types and entity types are supported.

**Comment by NathanNZ** [comment]
Let me know if you need any further information :+1:

**Comment by VikingsFan** [comment]
@NathanNZ I have tried your code and everything works fine, problems maybe in your data source, try with in-memory data, to see it's working or not, and another question, where do you use the type ElephantChild?

**Comment by NathanNZ** [comment]
ElephantChild is used in a linking table off ElephantOwner (I've updated the question) - however thanks for your suggestion to try it in memory as it looks like it's working if I run a ToList().AsQueryable() on the projected queryable.

Must be an edge case causing the  EF => Automapper  => OData query not to work as expected. Looks like I'll have to figure out the difference in the queries and see what seems to be different between the two of them that's causing it to fail!

Feel free to close this issue if you do not support any queriables apart from the one supplied by EF as it well may be Automapper doing something strange with the IQueryable rather than the way OData processes it 👍

**Comment by Venom16** [comment]
It may be a bug here
 ModelID = "5fa72dc4-c2ee-4e20-ba7d-3945fcf6e23f" type TestWebApi.OData.v1.ViewModels.ElephantKidSession $ var2
and
ModelID = "5fa72dc4-c2ee-4e20-ba7d-3945fcf6e23f" type TestWebApi.OData.v1.ViewModels.ChildObjects.SessionChild
For all types of one ModelID.
