### ISSUE TITLE
OData 4 $expand does not seem to work with custom function

### ISSUE THREAD

**Issue by rafeeqg** [OData/WebApi#766]
I have a controller which returns a collection of Items in its default GET action, I then created a function to return Items based on a parameter value. The function works well however, when I call the $expand on a child collection it doesn't seem to work. Although it expanded the EF query to get child items but end results doesn't show children. $select seems to be working though

**Not Working:**
Things/ThingsNamespace.GetByLocation(LocationID=1)?$expand=RelatedToThings

**Working:**
Things?$expand=RelatedToThings
Things/ThingsNamespace.GetByLocation(LocationID=1)?$select=Name

### Assemblies affected
Microsoft.AspNet.OData v5.9.0

### Reproduce steps
See bug description

### Expected result
It should expand the child collection of function restricted results

### Actual result
Doesn't expand the child collection

### Additional details
*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by VikingsFan** [comment]
@rafeeqg I can't repro it, could you share more code detail? Here are mine

model builder:

    builder.EntityType<Customer>().Collection.Function("Test")
    .ReturnsCollectionFromEntitySet<Customer>("Customers").Namespace = "Default";

controller:

    [HttpGet]
    [EnableQuery]
    public IQueryable<Customer> Test()
    {
        var db = new DbContext();
        return db.Customers;
    }

query:

`Customers/Default.Test()?$expand=Order`

**Comment by rafeeqg** [comment]
Thanks @VikingsFan, I replaced IQueryable<Things> with ReturnsCollectionFromEntitySet<Things> below and it worked. Not sure why it didn't work with IQueryable. 

**Model Builder:**
            configuration.EntityType.Collection.Function("GetByLocation")
                .Returns<IQueryable<Thing>>()
                .Parameter<int>("LocationID");

**Controller**

        [EnableQuery(MaxExpansionDepth = 100)]
        [ODataRoute]
        public IHttpActionResult GetByLocation(int LocationID)
        {
             var db = new DbContext();
             var things = from thing in db.things
                                       where db.LocationDescendants(LocationID, true).Contains(thing.LocationID)
                                       select thing;
          }

**Query**
Things/ThingsNamespace.GetByLocation(LocationID=1)?$expand=RelatedToThings

**Comment by VikingsFan** [comment]
For now we only support expand navigation property in entity type, so in function definition, you need specify it's collection from entityset.

**Comment by engbryan** [comment]
Hi guys. We are facing the same issue here. Aparently the function works very well with other clauses as filter, select, top... However the expand does not provoke effects on the results.

We have already tried to change namespaces and did some other simple tests on returning types and function properties. But nothing was able to solve the issue.

Could someone give a light on it?

Builder:
```
            var hotelsGetPrices = builder.EntityType<Hotel>().Collection
                .Function("CalculatePrices")
                .ReturnsCollectionFromEntitySet<Hotel>(HotelMap.Table.Name);
```

Function:
```
[HttpGet]
        [EnableQuery(
            MaxAnyAllExpressionDepth = 5,
            MaxExpansionDepth = 5,
            AllowedQueryOptions = AllowedQueryOptions.All
            )]
        public object CalculatePrices(ODataQueryOptions<Hotel> queryOptions)
        {
            var hotelHandler = roleBasedContext.GetHandlerFor<Hotel>() as HotelHandler;
            var source = hotelHandler.AsQueryable();

            queryOptions.ApplyTo(source);

            return source;
        }
```

Url:
`/Hotel/Default.CalculatePrices()?$filter=Id eq 1` OK
`/Hotel/Default.CalculatePrices()?$select=Title` OK
`/Hotel/Default.CalculatePrices()?$expand=Room` NOT OK

**Comment by mishraabhinn** [comment]
> Hi guys. We are facing the same issue here. Aparently the function works very well with other clauses as filter, select, top... However the expand does not provoke effects on the results.
> 
> We have already tried to change namespaces and did some other simple tests on returning types and function properties. But nothing was able to solve the issue.
> 
> On the SQL Profiler I can see the join from the expand, but it's data are not appended on the json result.
> 
> Could someone give a light on it?
> 
> Builder:
> 
> ```
>             var hotelsGetPrices = builder.EntityType<Hotel>().Collection
>                 .Function("CalculatePrices")
>                 .ReturnsCollectionFromEntitySet<Hotel>(HotelMap.Table.Name);
> ```
> 
> Function:
> 
> ```
> [HttpGet]
>         [EnableQuery(
>             MaxAnyAllExpressionDepth = 5,
>             MaxExpansionDepth = 5,
>             AllowedQueryOptions = AllowedQueryOptions.All
>             )]
>         public object CalculatePrices(ODataQueryOptions<Hotel> queryOptions)
>         {
>             var hotelHandler = roleBasedContext.GetHandlerFor<Hotel>() as HotelHandler;
>             var source = hotelHandler.AsQueryable();
> 
>             queryOptions.ApplyTo(source);
> 
>             return source;
>         }
> ```
> 
> Url: `/Hotel/Default.CalculatePrices()?$filter=Id eq 1` OK `/Hotel/Default.CalculatePrices()?$select=Title` OK `/Hotel/Default.CalculatePrices()?$expand=Room` NOT OK
> 
> Versions: ![image](https://user-images.githubusercontent.com/19389281/105647181-8c726a00-5e82-11eb-9fc4-b8112e80f7cf.png)

I think it too late for answers but you should change the path  in builder ReturnsCollectionFromEntitySet<Hotel>(nameoff(Hotel));
