### ISSUE TITLE
CORS options don't work when custom formatters are used

### ISSUE THREAD

**Issue by matjanos** [OData/WebApi#767]
When you add custom formatters to configuration, CORS configurations are ignored when you request metadata.

It was discovered, when applying workaround for empty single result (http://odata.github.io/WebApi/#10-02-work-around-for-singleresult-create). 

This snippet was used:

```
var odataFormatters = ODataMediaTypeFormatters.Create(
                                                 new NullSerializerProvider(), 
                                                 new DefaultODataDeserializerProvider());
config.Formatters.AddRange(odataFormatters);
```

And then, GET request for http://localhost:8888/odata/$metadata fails, because of: 

> No 'Access-Control-Allow-Origin' header is present on the requested resource.

Without adding new formatters, everything works fine.

**Comment by VikingsFan** [comment]
@matjanos  can you show more detail about your CORS configurations for me to investigate this issue?

**Comment by canibanoglu** [comment]
I have a similar problem. 

I have enabled CORS as suggested with:
```
var cors = new EnableCorsAttribute("*", "*", "*");
            config.EnableCors(cors);
```

Now, when I try to access the metadata at the URL `odata/$metadata` the preflight `OPTIONS` request works as expected but the subsequent get request fails with

> No 'Access-Control-Allow-Origin' header is present on the requested resource.

Sure enough, there is no `Access-Control-Allow-Origin` header set in the response.

The thing is, this just doesn't work, I'm only using `ODataConventionModelBuilder` to generate EDMs.

I would very much appreciate your help on this as it is going to drive me crazy.

**Comment by VikingsFan** [comment]
@canibanoglu I have enable the CORS in sample project like : https://github.com/OData/ODataSamples/blob/master/WebApi/v4/ODataFunctionSample/FunctionSample/Startup.cs

but things are working, any thing I miss to repro your issue?

**Comment by xuzhg** [comment]
@canibanoglu @matjanos Please re-open it if you have further concerns.

**Comment by ysmoradi** [comment]
It's a good idea to apply CORS at Owin pipeline level.

        public virtual void Configuration(IAppBuilder owinApp)
        {
            owinApp.UseCors(CorsOptions.AllowAll);

            owinApp.UseWebApi(new HttpConfiguration());

            // or if you want to apply CORS on Web API only, you've two options.
            // 1- Customize CorsOptions and use customized options instead of CorsOptions.AllowAll
            // 2- Use owin branching as below:

            owinApp.Map("/odata", owinAppForOData =>
            {
                owinAppForOData.UseCors(CorsOptions.AllowAll);

                owinAppForOData.UseWebApi(new HttpConfiguration());
            });
        }
