### ISSUE TITLE
Should not throw exception for invalid enum cast in query option

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#77]
Now the ODataQueryOptionParser and ODataUriParser will throw ODataException
for invalid enum cast in query option, which is not expected.  
According OData V4 spec, invalid cast should return null.  
So the parser should let the invalid cast pass or return null rather than
throw exception.  
  
Invalid enum cast includes all possible cast except cast enum to string and
cast string to enum,  
such as:  
cast null to enum,  
cast enum to non-string type(such as primitive/complex/entity/collection/enum
type)  
cast non-string type to enum.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1824](http://aspnetwebstack.codeplex.com/workitem/1824)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Apr 5, 2014 at 4:57 PM
**Reported by:**	fenzhao
**Updated on:**	Dec 10, 2014 at 12:31 AM
**Updated by:**	yishaigalatzer

**Comment by LianwMS** [comment]
On *2014-05-07 15:58:47 UTC*, **fenzhao** commented:

cast null to enum is fixed after migration to ODL 6.3.

**Comment by xuzhg** [comment]
Close it. Please file a new issue if you have further concern. Thanks.
