### ISSUE TITLE
Can't Filter on Dynamic properties which is collection

### ISSUE THREAD

**Issue by VikingsFan** [OData/WebApi#770]
http://localhost/API/odata/GetItems(id=30045)?$count=true&$filter=Context%2Fany(c:+c+eq+%27Context1%27)&$format=json&$top=5

Get error:
`Validating OData QueryNode of kind CollectionOpenPropertyAccess is not supported by FilterQueryValidator.`

**Comment by ersandgamp** [comment]
Will this be fixed anytime near in the future?
I'm facing the same issue.

**Comment by mtroth-microsoft** [comment]
This is not a bug, the WebApi layer is intentionally blocking this. We have, however, recently added support to ODL that enables parsing of urls like this one (note the slight modification to expression inside the any container): 

http://localhost/API/odata/GetItems(id=30045)?$count=true&$filter=Context%2Fany(c:+c/Edm.String+eq+%27Context1%27)&$format=json&$top=5.

Community contributions to expose this feature in WebApi are welcome.
