### ISSUE TITLE
[vNext] NuGet Feeds for OData Web API vNext

### ISSUE THREAD

**Issue by christiannagel** [OData/WebApi#771]
Where are the NuGet feeds for vNext?

The packages seem not to be on the nightly build feed described in [README](https://github.com/OData/WebApi/blob/vNext/README.md)

Thanks,
Christian

**Comment by alvachien** [comment]
Met the same issue.

**Comment by ryanhall27** [comment]
I ran into the same issue so I tried downloading the project and adding it as an existing project.  I can't even get it to compile.  Doesn't look to me like this is anywhere even close to alpha. 

I am really hoping we can get the OData team to give us an update on the status of OData in .NET core.

**Comment by xiaoxin1983** [comment]
+1

**Comment by xuzhg** [comment]
It's related to Asp.NET Core support. It's not released yet. So you can't find it in the Nuget.org 

Closed it because it's related to a lot of similar issues, for example: https://github.com/OData/WebApi/issues/772
