### ISSUE TITLE
aggregate($count as total) doesn't work

### ISSUE THREAD

**Issue by olsh** [OData/WebApi#773]
I'm trying to use the aggregation function with the virtual property $count as described [here](https://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/csprd02/odata-data-aggregation-ext-v4.0-csprd02.html#_Keyword_with_1)
Here is my query:
`?$apply=groupby((name, version), aggregate($count as total))`
### Assemblies affected

Microsoft.AspNet.OData 5.9.1
Microsoft.OData.Core 6.15.0
Microsoft.OData.Edm 6.15.0
### Reproduce steps

Execute aggregate function with $count
`$apply=aggregate($count as total)`
### Expected result

Total amount of rows in the set.
### Actual result

`The query specified in the URI is not valid. 'with' expected at position 17 in 'aggregate($count as total)'.`

**Comment by VikingsFan** [comment]
@olsh yes, this is not supported for now, need do it in ODL and WebAPI/OData

**Comment by olsh** [comment]
@VikingsFan thanks. 
Is there any other way to count entities in a set?

**Comment by VikingsFan** [comment]
can you add &$count=true to get the count as a workaround ?

**Comment by olsh** [comment]
I need something like this.
```
  "value": [
    { "name" : "bob", "version" 2: , "total": 5 },
    { "name" : "alice", "version" 1: , "total": 8 },
    { "name" : "alice", "version" 2: , "total": 2 },
  ]
```
I thought `&$count=true` returns count for all records for the entire query.

**Comment by VikingsFan** [comment]
@olsh For now we only support filter and aggregate in groupby, or there need a property and use  `aggregate PropertyName with sum as total` to get total count.

**Comment by olsh** [comment]
@VikingsFan thank you for the quick reply.
> need do it in ODL and WebAPI/OData

What is ODL?
I'll try to add the feature if I have some spare time.

**Comment by VikingsFan** [comment]
You are very welcome to contribute to us, ODL odata lib, is https://github.com/OData/odata.net , our master is reference on their ODataV4-6.x

**Comment by xuzhg** [comment]
We have a PR request merged at https://github.com/OData/WebApi/commit/6c18a49921f257e20ca157da6b755886f0da6c57. Please test at your side and let us know any further problem. Thanks.
