### ISSUE TITLE
Aliases created in $apply aren't available in further clauses

### ISSUE THREAD

**Issue by kosinsky** [OData/WebApi#776]
I aggregate statement in side $apply clause user could create aliases and spec says that user could use them in further clauses:
3.16 Evaluating $apply
The new system query option $apply is evaluated first, then the other system query options are evaluated, if applicable, on the result of $apply in their normal order (see [OData-Protocol, section 11.2.1]). If the result is a collection, $filter, $orderby, $expand and $select work as usual on properties that are defined on the output set after evaluating $apply. 

However, when I'm using query like that Order_Details?$apply=groupby((Product/ProductName), ggregate(Quantity with average as AvqQty))&$orderby=AvgQty

The query specified in the URI is not valid. Could not find a property named 'AvgQty'

**Comment by VikingsFan** [comment]
@kosinsky can you try 5.9.1, I think this is working.

**Comment by kosinsky** [comment]
@VikingsFan Thank you. It works for me.
