### ISSUE TITLE
Should not throw when the target type of cast is not primitive or enumeration type

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#78]
Should not throw when the target type of cast is not primitive or enumeration
type.  
such as:  
cast(null,NS.ComplexType)  
cast(null,NS.EntityType)  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1827](http://aspnetwebstack.codeplex.com/workitem/1827)
**Status:** Active
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Apr 8, 2014 at 7:03 AM
**Reported by:**    fenzhao
**Updated on:** Dec 10, 2014 at 12:31 AM
**Updated by:** yishaigalatzer

**Comment by mikepizzo** [comment]
Closing due to lack of customer activity. Will re-visit based on any user feedback.
