### ISSUE TITLE
More control on Expand and Select attribute

### ISSUE THREAD

**Issue by chinadragon0515** [OData/WebApi#783]
Three more controls
1.	For the class Expand attribute, it will have a flag to indicate whether search auto-expand navigation properties of derived type when user query base type and result is derived type, the default value is false (means by default, derive type is not searched for auto-expand properties).
2.	For the class Expand attribute, it will have a flag to indicate whether to ignore auto-expand property when there is a select clause and default value is false (mean by default auto-expand will always work even there is a select).
3.	For the class Select attribute, it will have a flag to indicate whether to ignore auto-select property list when there is a select clause and default value is false (mean by default we will merge user passed in list property with auto-select property list).

**Comment by chinadragon0515** [comment]
From Mike,

1)	I would expect that any auto-expand properties of a derived type would also be expanded by default (otherwise there's much less value in making them autoexpand)
2)	This looks fine
3)	I would expect that, by default, a $select clause would only include the specified properties (and not autoselect columns) – I would expect that, by default, $select would take precedence -- otherwise there's no way to restrict the set of autoselect properties.

**Comment by VikingsFan** [comment]
98e65958794f8f7e6965693548e26004fc1885aa
