### ISSUE TITLE
OData query with many fields produces StackOverflowException 

### ISSUE THREAD

**Issue by Casimodo72** [OData/WebApi#784]
Hi,

a javascript client odata query produces a StackOverflowException on the server in EntityFramework when the query has lots of fields.
In my scenario the query succeeds with 94 fields (main and 13 $expanded tables), but not with 96 fields (i.e. 2 fields added to query over main table). Note that I do not select all fields of any of those tables.

The exception is thrown for me in EntityFramework's Coordinator<T>.ReadNextElement in the line:
element = TypedCoordinatorFactory.Element(shaper);
I'm not able (as in dunno how) to debug further down into the TypedCoordinatorFactory.Element method.

This issue is probably related to the bug described here: https://github.com/dotnet/corefx/issues/7953. In this scenario the OP seems to have a query over a single table. Also his stack trace does not include the Coordinator<T>.ReadNextElement method.
The folks over at corefx are asking for a LINQ-expression-only repro. Is someone able to produce such an expression, reflecting the shape of expression as produced by WebApi OData and EF? This should also include the $top and $count query options.

I'm not sure where to put this bug, because it might be a bug in the Lambda compilation, but I can only reproduced this using WebApi OData + EntityFramework.

Is someone already aware of this issue?

I'm using .NET 4.6, ASP.NET 4, MVC 5, OData v4 (6.15.0).

Regards,
Kasimier Buchcik

**Comment by VikingsFan** [comment]
if there in no issue when you turn the data source into in-memory, then this should be EF's problem, since the exception is throwing in EF, waiting the repro on reference EF issue.

**Comment by mikepizzo** [comment]
This appears to be an issue in .NET (see https://github.com/dotnet/corefx/issues/7953) fixed by https://github.com/dotnet/corefx/pull/11091. There is an open question as to whether OData may be building queries that exacerbate the issue.  This appears to affect a number of folks; @kosinsky has been involved in the discussion and may have more context.

**Comment by kosinsky** [comment]
@mikepizzo @robward-ms Should issue be closed? Fix was merged

**Comment by kevinayers** [comment]
Did this issue get ported over to .NET core?  I am having a very similar issue in .NET core v2.2 and I don't see the presence of the System.Linq.Expressions.StackGuard class.

**Comment by Kevat** [comment]
We are seeing a similar issue when using OData with Entity Framework Core 2.2. It even weirder that we only run into this issue when we specify a "select" for a given expand. Expanding 4 other tables does not cause an error. However, selecting a specific column for each of those expands somehow causes an overflow. Is that the same or similar to the issue you are facing @kevinayers?

**Comment by kevinayers** [comment]
Yes, seems very similar.  Short term, we found turning change tracking off on entity framework prevents the issue - if you don't need to worry about updates
