### ISSUE TITLE
OData query force select specified some property

### ISSUE THREAD

**Issue by CarefreeXT** [OData/WebApi#785]
I hope control query result field,
some user can't query some property

**Comment by VikingsFan** [comment]
@CarefreeXT I'm very excited to tell you we have a new feature to handle this scenario in the 6.0.0, night package are ready and document is [here](http://odata.github.io/WebApi/#04-26-modelbound-attribute), please have a try, any feedback is very appreciate.

**Comment by CarefreeXT** [comment]
Thank you!
Can you tell me the release date?

**Comment by VikingsFan** [comment]
If you wan to achieve diffident user select diffident property then sill need to do like [this](https://github.com/OData/WebApi/issues/555#issuecomment-165157537), this feature is for server side security setting, you can try the nightly package, release will be in Spe.
