### ISSUE TITLE
Nested filter not working properly

### ISSUE THREAD

**Issue by sproulx100** [OData/WebApi#787]
Nested filters are not working (ignored) by OData when doing an expand on single Entity with EntityFramework.

### Assemblies affected
OData 5.9.0 and 5.9.1 (didn't test with previous)

### Reproduce steps
Simple model:
```
public class Parent {
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual List<Child> Childs { get; set; }
}

public class Child {
    [Key]
    public int Id { get; set; }

    public string ChildName { get; set; }

    public int ParentId { get; set; }
    public virtual Parent Parent { get; set; }
}
```

OData URL:
**http://www.example.com/odata/Childs?$expand=Parent($filter=Name%20eq%20'something')**

### Expected result
Should list every child that has a Parent named "something" and list parent's properties:
```
value: [
    {
        "Id": ...
        "ChildName": '...',
        "Parent": {
            "Id": ...
            "Name": "something"
        }
    }
]
```

### Actual result
List every child. $filter is not taken into account.
```
value: [
    {
        "Id": ...
        "ChildName": '...',
        "Parent": {
            "Id": ...
            "Name": "notSomethingAndStillHere"
        }
    }
]
```

### Additional details
First level $filter is working properly in this situation:
**http://www.example.com/odata/Childs?$expand=Parent&$filter=Parent/Name%20eq%20'something'**

Filters are working properly if we reverse the query to filter on a list and not only on an entity:
**http://www.example.com/odata/Parents?expand=Childs($filter=ChildName%20eq%20'something')**

(I know this last example is not giving the same result. It's just to show that nested filter works properly when filtering on a collection)

**Comment by VikingsFan** [comment]
@sproulx100 $filter should apply to a collection, your query `$expand=Parent($filter=,,)` are apply filter to Parent which is not a collection, so it's not working, the last two samples are working property because the you apply filter to Childs which is a collection.

**Comment by sproulx100** [comment]
You are right. OData V4 documentation specifies that filter works on collection and does not specify it must works on navigation property that are not collection, implicitly means that we have to start filter query on parent node down to what we want.
