### ISSUE TITLE
Formatters are not found for entities exposed as interfaces

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#79]
This scenario is using oData v4.  
I exposed a model as interfaces by mapping both concrete and interface types
in the model.  
(next step will be to strip the concrete types from the $metadata)  
  
When the controller retrieve the entities (by mean of an helper who knows the
real concrete type) and return the requested IQueryable<IMyType> the browser
receive a NotAcceptable (406).  
  
The problem is inside the Execute method (NegotiatedContentResult.cs). In
particular this call returns null:  
ContentNegotiationResult result = contentNegotiator.Negotiate(typeof(T),
request, formatters);  
  
The real cause is inside the ODataMediaTypeFormatter.CanWriteType where the
following function returns null for all the seven default formatters:  
IEdmModel model = Request.ODataProperties().Model;  
  
Workaround.  
I applied a custom attribute to my controller which shift the position of the
json formatter in the list of the formatters:  

    
    
        public class JsonLastAttribute : Attribute, IControllerConfiguration
        {
            public void Initialize(HttpControllerSettings controllerSettings, HttpControllerDescriptor controllerDescriptor)
            {
                IList<ODataMediaTypeFormatter> odataFormatters = ODataMediaTypeFormatters.Create();
                var jsonFormatter = odataFormatters.First(f => f.SupportedMediaTypes.Contains(MediaTypeHeaderValue.Parse("application/json")));
                odataFormatters.Remove(jsonFormatter);
                odataFormatters.Add(jsonFormatter);
                foreach(var formatter in odataFormatters)
                    controllerDescriptor.Configuration.Formatters.Insert(0, formatter);
            }
        }

The nightly build package used for this test was the 140409.  
  
I suspect there is some collision between the old and new v4 namespaces as the
ODataMediaTypeFormatter.cs was in the System.Web.Http.OData namespace instead
of the System.Web.OData as I would expect.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1833](http://aspnetwebstack.codeplex.com/workitem/1833)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	cysu
**Reported on:**	Apr 11, 2014 at 12:11 PM
**Reported by:**	raffaeler
**Updated on:**	May 12, 2014 at 7:42 AM
**Updated by:**	azhou

**Comment by LianwMS** [comment]
On *2014-05-09 22:36:29 UTC*, **cysu** commented:

Seem able to make it work using:
            var builder = new ODataConventionModelBuilder(_configuration);
            builder.EntityType<Sales>().DerivesFrom<ISales>();
            builder.EntitySet<ISales>("Sales");
            var model = builder.GetEdmModel();

        public class SalesController : ODataController
        {
            private static Sales[] sales = { new Sales { Id = 1, Name = "abc" } };

            [EnableQuery]
            [ODataRoute("Sales")]
            public IQueryable<ISales> Get()
            {
                return sales.AsQueryable();
            }


        public interface ISales
        {
            int Id { get; set; }
        }

        public class Sales : ISales
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }

**Comment by LianwMS** [comment]
On *2014-05-09 23:01:26 UTC*, **raffaeler** commented:

Hi cysu,
I suspect your sample works because Sales is a class and not an interface.

So, if you create :

IEntityBase containing Id ISales deriving IEntityBase and adding Name create a concrete Sales deriving implementing ISales expose via oData ISales (not Sales as in your code)
in my case it doesn't work just because the Id is in a base interface IEntityBase instead of being inside ISales.

The problem is that the reflection helpers do not deep traverse the hierarchy in case of interfaces.

**Comment by LianwMS** [comment]
On *2014-05-10 13:53:29 UTC*, **cysu** commented:

A possible workaround is changing the interface to abstract class. Existing code does not seem treat an interface as BaseType. Actually, interface is not base type as per existing code using Clr: Sales' base Clr type is object, instead of ISales.
baseClrType = baseClrType.BaseType;

**Comment by LianwMS** [comment]
On *2014-05-11 09:56:29 UTC*, **cysu** commented:

Link similar requests:
https://aspnetwebstack.codeplex.com/workitem/514
https://aspnetwebstack.codeplex.com/workitem/1887

**Comment by LianwMS** [comment]
On *2014-05-12 05:03:00 UTC*, **raffaeler** commented:

I appreciate the effort to find a workaround but honestly interfaces cannot be replaced easily with abstract classes. The examples I provided here and in other feedbacks are only samples but obviously the real model is far more complex and there are good
 reasons to avoid messing up with concrete classes in a large project.

If it is a problem providing the mechanism to traverse the hierarchy for interfaces, an alternative solution may be to make this code pluggable so that I can write by myself the parts which will allow us to expose the model using the interfaces.
But please don't ask me to fork the sources ...

**Comment by LianwMS** [comment]
On *2014-05-12 14:42:03 UTC*, **azhou** commented:

Move it to vNext as both 
https://aspnetwbstack.codeplex.com/workitem/514 and 
https://aspnetwebstack.codeplex.com/workitem/1887.

**Comment by xuzhg** [comment]
Interface is not considered in the Model builder. 

Close it. Please file a new issue if you have further concern.
