### ISSUE TITLE
Restier in a self-hosted environment

### ISSUE THREAD

**Issue by henning-krause** [OData/WebApi#794]
I'm trying to get Restier running in a self-hosted environment.

I'm trying to register the ODATA router using

``` cs
await config.MapRestierRoute<EntityFrameworkApi<AdventureWorksLT>>(
				"AdventureWorksLT",
				"api/AdventureWorksLT",
				new RestierBatchHandler(GlobalConfiguration.DefaultServer));
```

But I don't have the GlobalConfiguration class in my environment. 

Any ideas on how to bootstrap Restier in a self hosted environment?

**Comment by VikingsFan** [comment]
You should open this issue in [here](https://github.com/OData/RESTier/issues), what framework you are using that don't have global configuration? for example, you can config in OWIN self host like: 
https://github.com/OData/ODataSamples/blob/master/WebApi/v4/CustomODataFormatter/CustomODataFormatter/Program.cs#L36-L51

**Comment by henning-krause** [comment]
Thanks.
