### ISSUE TITLE
ODataEntityTypeSerializer.CreateEntry is incorrectly setting the host for the self links if the path segment right after the host start with an underscore

### ISSUE THREAD

**Issue by emanuelquintero** [OData/WebApi#796]
ODataEntityTypeSerializer.CreateEntry is incorrectly setting the host for the self links if the path segment right after the host start with an underscore.
### Assemblies affected

Don't really know, how can I know?
### Reproduce steps

Create an EntityInstanceContext with the following requestUri: https://host.com:333/_pathSegment/moreSegments
Call ODataEntityTypeSerializer.CreateEntry(SelectExpandNode, EntityInstanceContext)
See the self links in the ODataEntry returned
### Expected result

See the self links e.g. ReadLink
It should be similar to https://host.com:333/_pathSegment/moreSegments
### Actual result

It actually is https://**_pathSegment**/moreSegments

**Comment by VikingsFan** [comment]
@emanuelquintero just check the version of your project referenced System.Web.OData.dll, that's the version number we want.

about the link, firstly, by default we won't set readLink in CreateEntry method, so I'm not sure why you can have ReadLink in your result, have you set your own LinkBuilder by calling this?

    builder.EntitySet<Customer>("_Customers").HasReadLink ... 

And I also tried with uri like `localhost/_odata/_Customers(1)` the self link in the response seems right with System.Web.OData version 5.9.1.

More detail to reproduce your issue will be very helpful.

**Comment by emanuelquintero** [comment]
Thanks for the reply @VikingsFan 

###Assemblies affected
Assembly version: 5.3.21007.0
[NuGet package](http://www.nuget.org/packages/Microsoft.AspNet.WebApi.OData/5.3.1)

### More info
We are calling [createEntry](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.Http.OData/OData/Formatter/Serialization/ODataEntityTypeSerializer.cs#L136) which in turn calls
[linkBuilder.BuildEntitySelfLinks](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.Http.OData/OData/Formatter/Serialization/ODataEntityTypeSerializer.cs#L163) and I believe that's where it's failing.

**Comment by emanuelquintero** [comment]
Thanks for the reply @VikingsFan 

### Assemblies affected
Assembly version: 5.3.21007.0
[NuGet package](http://www.nuget.org/packages/Microsoft.AspNet.WebApi.OData/5.3.1)

### More info
We are calling [createEntry](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.Http.OData/OData/Formatter/Serialization/ODataEntityTypeSerializer.cs#L136) which in turn calls [linkBuilder.BuildEntitySelfLinks](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.Http.OData/OData/Formatter/Serialization/ODataEntityTypeSerializer.cs#L163) and I believe that's where it's failing.

```
entityInstanceContext.SerializerContext.Model.GetEntitySetLinkBuilder(entityInstanceContext.EntitySet).GetType()
{Name = "EntitySetLinkBuilderAnnotation" FullName = "System.Web.Http.OData.Builder.EntitySetLinkBuilderAnnotation"}
    Assembly: {System.Web.Http.OData, Version=5.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35}
    AssemblyQualifiedName: "System.Web.Http.OData.Builder.EntitySetLinkBuilderAnnotation, System.Web.Http.OData, Version=5.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
    Attributes: Public | BeforeFieldInit
    BaseType: {Name = "Object" FullName = "System.Object"}
    ContainsGenericParameters: false
    CustomAttributes: Count = 0
    DeclaredConstructors: {System.Reflection.ConstructorInfo[4]}
    DeclaredEvents: {System.Reflection.EventInfo[0]}
    DeclaredFields: {System.Reflection.FieldInfo[9]}
    DeclaredMembers: {System.Reflection.MemberInfo[26]}
    DeclaredMethods: {System.Reflection.MethodInfo[12]}
    DeclaredNestedTypes: {System.Reflection.TypeInfo.<get_DeclaredNestedTypes>d__23}
    DeclaredProperties: {System.Reflection.PropertyInfo[0]}
    DeclaringMethod: '((System.RuntimeType)(entityInstanceContext.SerializerContext.Model.GetEntitySetLinkBuilder(entityInstanceContext.EntitySet).GetType())).DeclaringMethod' threw an exception of type 'System.InvalidOperationException'
    DeclaringType: null
    FullName: "System.Web.Http.OData.Builder.EntitySetLinkBuilderAnnotation"
    GUID: {fb95d8ed-d3cd-3b4e-bb0e-02ab02d2dd92}
    GenericParameterAttributes: '((System.RuntimeType)(entityInstanceContext.SerializerContext.Model.GetEntitySetLinkBuilder(entityInstanceContext.EntitySet).GetType())).GenericParameterAttributes' threw an exception of type 'System.InvalidOperationException'
    GenericParameterPosition: '((System.RuntimeType)(entityInstanceContext.SerializerContext.Model.GetEntitySetLinkBuilder(entityInstanceContext.EntitySet).GetType())).GenericParameterPosition' threw an exception of type 'System.InvalidOperationException'
    GenericTypeArguments: {System.Type[0]}
    GenericTypeParameters: {System.Type[0]}
    HasElementType: false
    ImplementedInterfaces: {System.Type[0]}
    IsAbstract: false
    IsAnsiClass: true
    IsArray: false
    IsAutoClass: false
    IsAutoLayout: true
    IsByRef: false
    IsCOMObject: false
    IsClass: true
    IsConstructedGenericType: false
    IsContextful: false
    IsEnum: false
    IsExplicitLayout: false
    IsGenericParameter: false
    IsGenericType: false
    IsGenericTypeDefinition: false
    IsImport: false
    IsInterface: false
    IsLayoutSequential: false
    IsMarshalByRef: false
    IsNested: false
    IsNestedAssembly: false
    IsNestedFamANDAssem: false
    IsNestedFamORAssem: false
    IsNestedFamily: false
    IsNestedPrivate: false
    IsNestedPublic: false
    IsNotPublic: false
    IsPointer: false
    IsPrimitive: false
    IsPublic: true
    IsSealed: false
    IsSecurityCritical: true
    IsSecuritySafeCritical: false
    IsSecurityTransparent: false
    IsSerializable: false
    IsSpecialName: false
    IsUnicodeClass: false
    IsValueType: false
    IsVisible: true
    MemberType: TypeInfo
    MetadataToken: 33554703
    Module (System.Reflection.MemberInfo): {System.Web.Http.OData.dll}
    Module: {System.Web.Http.OData.dll}
    Name: "EntitySetLinkBuilderAnnotation"
    Namespace: "System.Web.Http.OData.Builder"
    ReflectedType: null
    StructLayoutAttribute: {System.Runtime.InteropServices.StructLayoutAttribute}
    TypeHandle: {System.RuntimeTypeHandle}
    TypeInitializer: null
    UnderlyingSystemType: {Name = "EntitySetLinkBuilderAnnotation" FullName = "System.Web.Http.OData.Builder.EntitySetLinkBuilderAnnotation"}
```

**Comment by emanuelquintero** [comment]
### More info
And then BuildEntitySelfLinks calls [entityInstanceContext.GenerateSelfLink](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.Http.OData/OData/Builder/EntitySetLinkBuilderAnnotation.cs#L82) which in turn calls [GenerateSelfLink](https://github.com/OData/WebApi/blob/c44ce5547b1b44474bfa2d1208c68b90fa401556/OData/src/System.Web.Http.OData/OData/Builder/LinkGenerationHelpers.cs#L27).
And that's where I think it's broken somewhere.

**Comment by VikingsFan** [comment]
@emanuelquintero I can see you are using WebAPI/OData V3, it's under maintenance and we won't do any feature on it anymore, can you try V4? https://www.nuget.org/packages/Microsoft.AspNet.OData/

**Comment by emanuelquintero** [comment]
Will try v4 and update.

**Comment by mikepizzo** [comment]
Did V4 address your issue?
