### ISSUE TITLE
Having ODataMetadataController in the OData assembly causes issues

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#80]
When a user wants to use something from OData, like EnableQuery or Delta<T>
outside of the context of OData, they are forced to deal with the fact that
ODataMetadataController gets included on their app as part of the loaded
assembly whether they like it or not. At that point, ODataMetadata is a
controller that can be routed as any other Controller on your app, which might
cause unexpected behaviors.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1847](http://aspnetwebstack.codeplex.com/workitem/1847)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Apr 18, 2014 at 7:15 PM
**Reported by:**	jacalvar
**Updated on:**	May 5, 2014 at 10:30 AM
**Updated by:**	zjufish

**Comment by xuzhg** [comment]
So far, there's no exception reported about the MetadataController. Please reopen it if you find any concern. Thanks.
