### ISSUE TITLE
$filter primitive type collection contains

### ISSUE THREAD

**Issue by CarefreeXT** [OData/WebApi#802]
I hope one entity property value $filter in operation one primitive type collection.

for example
http://localhost:54504/UserInfoes?$filter=in(Age,@c)&@c=[27,29]
TO LINQ
var query = from a in db.UserInfoes
                        where new int[] { 27, 29 }.Contains(a.Age)
                        select a;

**Comment by mikepizzo** [comment]
The OData 4.01 protocol adds the "in" operator. Simple usage: http://localhost:54504/UserInfoes?$filter=Age in (27,29)

**Comment by mikepizzo** [comment]
Marking as P2 because it is a common ask.

**Comment by biaol-odata** [comment]
@jlbrumfield ODL's "in" operator support is currently in progress. Subsequently we will bring that up to the WebAPI layer.

**Comment by xuzhg** [comment]
See #1497

**Comment by AlanWong-MS** [comment]
Addressed with #1497 and the feature will be available in our incoming release. Thanks for the ongoing interest!
