### ISSUE TITLE
ODataEntityDeserializer is missing 6.0.0-beta2

### ISSUE THREAD

**Issue by azyl-scnsoft** [OData/WebApi#805]
I'm moving my project to Asp.Net core, 
I have custom entity deserializer that is inherited from ODataEntityDeserializer. But in 6.0.0-beta2 there is no such anymore. 
I also haven't found any mention about it in release notes. 

Is this deserialzed had been completely removed?

**Comment by VikingsFan** [comment]
in 6.0.0-beta2 breaking change release: Rename ODataEntityDeserializer to ODataResourceDeserializer, but this release is not based on Asp.Net core, it's based on breaking change release of OData Lib 7.0, we have a lot of improvements and features.

**Comment by xuzhg** [comment]
It's mentioned in the release note: https://github.com/OData/WebApi/releases/tag/v6.0.0-beta

* Rename ODataEntityDeserializer to ODataResourceDeserializer

**Comment by mikepizzo** [comment]
Closing as resolved.
