### ISSUE TITLE
Aggregate function threw exception with message: The parent value for a property access of a property 'ProductId' is not a single value. Property access can only be applied to a single value.

### ISSUE THREAD

**Issue by thoangphuoc123** [OData/WebApi#807]
I am trying with aggregate function with countdistinct as described [here](http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs01/odata-data-aggregation-ext-v4.0-cs01.html#_Toc378326305).
Here is my query : 
Categories?$apply=groupby((CategorieName),aggregate(Products/ProductId with countdistinct as ProductsCount)). -> Error 

### Assemblies affected
System.Web.OData: 5.9.1.0
Microsoft.OData.Core: 6.15.0.0
Microsoft.OData.Edm: 6.15.0.0

### Reproduce steps
Categories?$apply=groupby((CategorieName),aggregate(Products/ProductId with countdistinct as ProductsCount)). -> Error  

### Expected result
Return the number of Products based on Categories.
eg:  CategorieName:Beverages, ProductsCount: 10
      CategorieName:Condiments, ProductsCount: 12

### Actual result
Threw Exception with Odata Core message: ***The parent value for a property access of a property 'ProductId' is not a single value. Property access can only be applied to a single value.***

### Additional details
Products?$apply=groupby((ProductName ),aggregate(Categories/CategorieId with countdistinct as CategoriesCount)). -> working Ok

Here is my db for example: 
![capture](https://cloud.githubusercontent.com/assets/22023445/18268435/ed4d53cc-744d-11e6-8b3b-cbb8a6623c8f.PNG)

**Comment by VikingsFan** [comment]
@thoangphuoc123 this is duplicate with #634
