### ISSUE TITLE
Deficient error reporting from ReorderDependentProperties

### ISSUE THREAD

**Issue by escape-llc** [OData/WebApi#808]
This code has deficient error reporting.

```
private IEnumerable<IEdmStructuralProperty> ReorderDependentProperties(
            NavigationPropertyConfiguration navProperty)
        {
            EntityTypeConfiguration principalEntity = _configurations.OfType<EntityTypeConfiguration>()
                .FirstOrDefault(e => e.ClrType == navProperty.RelatedClrType);
            Contract.Assert(principalEntity != null);

            int keyCount = principalEntity.Keys().Count();
            if (keyCount != navProperty.PrincipalProperties.Count())
            {
                throw Error.InvalidOperation(SRResources.DependentPropertiesNotMatchWithPrincipalKeys,
                    String.Join(",", navProperty.DependentProperties.Select(e => e.PropertyType.FullName)),
                    String.Join(",", principalEntity.Keys.Select(e => e.PropertyInfo.PropertyType.FullName)));
            }
...
}
```
### Assemblies affected

System.Web.Http.OData.Builder
### Reproduce steps

Create an entity class that has an `Int32` ID column but no `KeyAttribute`, and has any column (e.g. Status1) of type `String` that is `KeyAttribute`.  Link this class to any other entity that uses the FK column.  See two classes below.

```
    public partial class Status {
        public Status() {
            this.Jobs = new HashSet<Jobs2>();
        }
        // no attributes detected
        public virtual ICollection<Jobs2> Jobs { get; set; }
        [Required, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Int32 ID { get; set; }
        [Key, Required, MaxLength(32), StringLength(32)]
        public String Status1 { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public String Name { get; set; }
    }
    public partial class Jobs2 {
        public Jobs2() {
        }
        [ForeignKey("Status")]
        public virtual Status Status1 { get; set; }
        [Key, Required, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Int32 ID { get; set; }
        [Required, MaxLength(32), StringLength(32)]
        public String Status { get; set; }
    }

```

 This code sequence blows up with the given message in **Actual Result** section.

```
    var builder = new ODataConventionModelBuilder();
    builder.DataServiceVersion = new Version(2, 0);
    builder.MaxDataServiceVersion = new Version(4, 0);
    foreach (var es in new Type[] { typeof(Jobs2), typeof(Status) }) {
        var esconfig = builder.AddEntity(es);
        builder.AddEntitySet(es.Name, esconfig);
    }
    var edm = builder.GetEdmModel();

```

Remove the `Status.ID` property completely, and the example works correctly.  Rename that property to any other name (not picked up by a convention), and the example works correctly.  The other attributes do not affect the error.
### Expected result

To see the **NAME OF THE CLASS/PROPERTY** affected by this mismatch.

"Status.Status1->Jobs2.Status1": The dependent property types 'System.String' are not same as the principal key types 'System.Int32,System.String'. The dependent and principal must each contain the same number of elements and must have the same types.

Most critically, when the KeyAttribute is already in use on an entity, is it not acceptable to blindly include any other columns selected by conventions.  "Key conventions" should only apply when there are no other KeyAttribute in effect.
### Actual result

Gets the list of types, without mentioning the offending navigation property, entities etc.  

The dependent property types 'System.String' are not same as the principal key types 'System.Int32,System.String'. The dependent and principal must each contain the same number of elements and must have the same types.
### Additional details

How can we troubleshoot errors without providing reference information?  The model has 500 nav properties in it, thanks a bunch, and p.s. they all look "correct" it took hours to figure out the key convention was the culprit!  In other words, the model contains NO SUCH navigation property associations, so where can one look without the NAME of the THING builder thinks is in error?

Even examining the source code did not help determine what SOURCE OBJECTS were making it fail.

Generally Important Advice:  **ALL MESSAGES MUST include complete reference information**, so someone without the source code and a debugger in the field, can pinpoint EXACTLY WHICH OBJECT is causing the EDM model breakdown, e.g. to trace it back to an SSDL/CSDL file or other asset.

**Comment by mikepizzo** [comment]
We should fix the related issue and, in general, look for ways to improve 500 responses from the server (which, I agree, are not very helpful).

**Comment by lneninger** [comment]
I ran in a similar exception. I have not clue which relationship is causing the error.

The exception:
System.InvalidOperationException
The dependent property types 'System.Guid' are not same as the principal key types ''. The dependent and principal must each contain the same number of elements and must have the same types.

I'm using EF CodeFirst to generate DB schema. I generated a DbContext diagram and double checked the DB tables's primary keys as well. So far, the is no signal where the problem is.

Any help will be appreciated.

Thanks!

**Comment by escape-llc** [comment]
My general advice is always use INT IDENTITY for PK in Entity Framework/OData, and use UNIQUE for your "real" key column(s).  Do not use any other type of PK, or a composite PK; it just cannot deal with it properly.  We've been working around it for years now, it's really frustrating.
Based on your meager facts, it sounds like a `KeyAttribute` or `ForeignKeyAttribute` is missing somewhere, or you are naming fields outside the "conventions" that usually pick that stuff up.

**Comment by lneninger** [comment]
My question is about why not show the Types involved into the relationship issue?

**Comment by escape-llc** [comment]
I'm not on the project, so i cannot answer that.  My original point is without any entity/property names in the error, how are we to track them down?

**Comment by lneninger** [comment]
I understand. I realized that the issue was because a bad entity mapping with an abstract parent. We are implementing a distributed-multidb system, so as far I know, numeric keys is not an option. Do you have any suggestion about this?

**Comment by samunro** [comment]
Note that this issue is also reproducible with the following.

```
<type name>Id
[Key]
OtherProperty
```

Note that the non-key property does not need to be named Id as the [convention](https://learn.microsoft.com/en-us/ef/core/modeling/keys?tabs=data-annotations) is as follows.

> By convention, a property named Id or `<type name>Id` will be configured as the primary key of an entity.

@mikepizzo I am still seeing this with version 5.7.0 of the [NuGet package](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.OData) which is currently the latest one. Should this issue be reopened?

I see that the Microsoft.Data.OData dependency has been [deprecated](https://www.nuget.org/packages/Microsoft.Data.OData/). Are there plans to remove the dependency?

Should [Microsoft.AspNet.WebApi.OData](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.OData) be deprecated too?
