### ISSUE TITLE
Odata threw exception with the sum, min, max, countdistinct, average functions with message: "The parent value for a property access of a property '{0}' is not a single value. Property access can only be applied to a single value."

### ISSUE THREAD

**Issue by thoangphuoc123** [OData/WebApi#810]
As the previous issue at: https://github.com/OData/WebApi/issues/807.
I am trying with max function as below
Here is my query :
Categories?$apply=groupby((CategorieName),aggregate(Products/UnitPrice with max as ProductsMaxPrice)). -> Error

**Assemblies affected**
System.Web.OData: 5.9.1.0
Microsoft.OData.Core: 6.15.0.0
Microsoft.OData.Edm: 6.15.0.0

**Reproduce steps**
Categories?$apply=groupby((CategorieName),aggregate(Products/UnitPrice with max as ProductsMaxPrice)). -> Error

**Expected result**
Return the number of Products based on Categories.
eg: CategorieName:Beverages, ProductsMaxPrice: 10

**Actual result**
Threw Exception with Odata Core message: The parent value for a property access of a property 'UnitPrice' is not a single value. Property access can only be applied to a single value.

**Additional details**
Products?$apply=groupby((ProductName ),aggregate(Categories/CategorieId with max as CategoriesMax)). -> working Ok

Here is my db for example: 
![capture](https://cloud.githubusercontent.com/assets/22023445/18305911/ce08bdc8-7513-11e6-9a63-b3d5c8242897.PNG)

**Comment by VikingsFan** [comment]
@thoangphuoc123  this is duplicate with https://github.com/OData/WebApi/issues/634
