### ISSUE TITLE
EnableCaseInsensitive method is gone

### ISSUE THREAD

**Issue by ymoradi** [OData/WebApi#812]
After upgrading to Microsoft.OData 7 & Microsoft.AspNet.OData 6, There is no Extension method "EnableCaseInsensitive" on "HttpConfigurationExtensions" class any more.

**Comment by VikingsFan** [comment]
Now we are using DI to set this configuration, you can do this like:

    configuration.MapODataServiceRoute("odata", "odata",
                builder =>
                    builder.AddService(ServiceLifetime.Singleton, sp => edmModel)
                        .AddService<IEnumerable<IODataRoutingConvention>>(ServiceLifetime.Singleton, sp =>
                            ODataRoutingConventions.CreateDefaultWithAttributeRouting("odata", configuration))
                        .AddService<ODataUriResolver>(ServiceLifetime.Singleton, sp => new CaseInsensitiveResolver()));

     public class CaseInsensitiveResolver : ODataUriResolver
     {
        private bool _enableCaseInsensitive;

        public override bool EnableCaseInsensitive
        {
            get { return true; }
            set { _enableCaseInsensitive = value; }
        }
     }

for other service in DI : http://odata.github.io/WebApi/#13-04-DependencyInjection

**Comment by ymoradi** [comment]
Thanks, I like DI (-: and it worked, but I was able to call MapODataServiceRoute several times on the same shared http configuration instance before, but After these changes (specially custom container builder) I've to create several instances of http configuration for every of my edm models, am I right?

**Comment by VikingsFan** [comment]
@ymoradi I think you can share the instance if they are same.

**Comment by ymoradi** [comment]
Yeah, you are right. Sorry )-: and Thanks for your helps (-:

**Comment by pHr34kY** [comment]
Quick question: Is it necessary to create the CaseInsensitiveResolver class when one could just do this?
`sp => new ODataUriResolver { EnableCaseInsensitive = true }`

**Comment by ysmoradi** [comment]
@pHr34kY Short Answer: I've not tested that, but it should work fine. But Take a look at following code:

```
public class DefaultODataUriResolver : UnqualifiedODataUriResolver
    {
        private readonly StringAsEnumResolver _stringAsEnumResolver = new StringAsEnumResolver
        {
            EnableCaseInsensitive = true
        };

        public override bool EnableCaseInsensitive
        {
            get { return true; }
            set { }
        }

        public override void PromoteBinaryOperandTypes(BinaryOperatorKind binaryOperatorKind,
            ref SingleValueNode leftNode, ref SingleValueNode rightNode, out IEdmTypeReference typeReference)
        {
            _stringAsEnumResolver.PromoteBinaryOperandTypes(binaryOperatorKind, ref leftNode, ref rightNode, out typeReference);
        }

        public override IEnumerable<KeyValuePair<string, object>> ResolveKeys(IEdmEntityType type,
            IDictionary<string, string> namedValues, Func<IEdmTypeReference, string, object> convertFunc)
        {
            return _stringAsEnumResolver.ResolveKeys(type, namedValues, convertFunc);
        }

        public override IEnumerable<KeyValuePair<string, object>> ResolveKeys(IEdmEntityType type,
            IList<string> positionalValues, Func<IEdmTypeReference, string, object> convertFunc)
        {
            return _stringAsEnumResolver.ResolveKeys(type, positionalValues, convertFunc);
        }

        public override IDictionary<IEdmOperationParameter, SingleValueNode> ResolveOperationParameters(
            IEdmOperation operation, IDictionary<string, SingleValueNode> input)
        {
            return _stringAsEnumResolver.ResolveOperationParameters(operation, input);
        }
    }
```
You can achieve a lot if you extend that. For example I've added support for unqualified Uri(s), being case insensitive, and have a support for Enum values.

**Comment by Rummskull** [comment]
@pHr34kY Tried your approach and it does not work. Maybe `EnableCaseInsensitive` is set a bit later... by whatever...

The only workaround I know is a derived class with "readonly" `EnableCaseInsensitive` property.

**Comment by commonsensesoftware** [comment]
Although this issue is closed, the problem remains. As @pHr34kY pointed out, it _should_ just work.  The reason it doesn't work is due to a bug in the OData Lib itself (Issue OData/odata.net#695). The internal **ODataUriParseConfiguration** paves over the setting associated with the injected **ODataUriParser**.

**Comment by mikepizzo** [comment]
Tracking the issue with ODataUriParseConfiguration paving over EnableCaseInsensitive as part of issue https://github.com/OData/odata.net/issues/695.

**Comment by t03apt** [comment]
> @pHr34kY 
Quick question: Is it necessary to create the CaseInsensitiveResolver class when one could just do this?
sp => new ODataUriResolver { EnableCaseInsensitive = true }

This works fine using Microsoft.OData.Core@7.3.1.

**Comment by mikuam** [comment]
Hi, I'm trying to achieve the same thing in vb.net, but somehow it doesn't work. Do you know what might be a problem?

    Imports System.Web.Http
    Imports Guestline.RezLynx.Persistence
    Imports Microsoft.AspNet.OData.Builder
    Imports Microsoft.AspNet.OData.Extensions
    Imports Microsoft.OData
    Imports Microsoft.OData.UriParser

    Public Class WebApiConfig

        Private Shared Property builder() As ODataModelBuilder

        Public Shared Sub Register(ByVal config As HttpConfiguration)
            builder = New ODataConventionModelBuilder()
            builder.EntitySet(Of vw_CompanyPerson)("profiles")

            config.MapODataServiceRoute(
                "odata",
                "odata",
                New Action(Of IContainerBuilder)(AddressOf ModifyContainer))

            config.Select().Expand().Filter().OrderBy().MaxTop(Nothing).Count()
        End Sub

        Private Shared Sub ModifyContainer(obj As IContainerBuilder)
            obj.AddService(ServiceLifetime.Singleton, New Func(Of IServiceProvider, ODataUriResolver)(AddressOf CreateUriResolver))
            obj.AddService(ServiceLifetime.Singleton, New Func(Of IServiceProvider, Edm.IEdmModel)(AddressOf GetEdmModel))
        End Sub

        Private Shared Function GetEdmModel(arg As IServiceProvider) As Edm.IEdmModel
            Return builder.GetEdmModel()
        End Function

        Private Shared Function CreateUriResolver(arg As IServiceProvider) As ODataUriResolver
            Return New CaseInsensitiveUriResolver()
        End Function

    End Class

And


    Imports Microsoft.OData.UriParser

    Public Class CaseInsensitiveUriResolver
        Inherits ODataUriResolver

        Public Overrides Property EnableCaseInsensitive As Boolean
            Get
                Return True
            End Get
            Set(value As Boolean)

            End Set
        End Property

    End Class
