### ISSUE TITLE
Can't make queries with controllers after update to Microsoft.AspNet.OData v6

### ISSUE THREAD

**Issue by PaulTodd** [OData/WebApi#814]
After upgrading to the latest version of OData I can no longer use my controllers to query data.  it seems my unbound functions work fine though.  This works fine when using the last stable version.

Microsoft.AspNet.OData v6.0.0
Microsoft.OData.Core v7.0.0
### Reproduce steps

Create a controller with get function and query it.       

```
    <EnableQuery(AllowedQueryOptions:=AllowedQueryOptions.All)>
    Public Function [Get]() As IHttpActionResult
        Dim db As Model.Context = New Model.Context()
        db.Configuration.AutoDetectChangesEnabled = False
        Return Ok(db.PROJECTS.AsQueryable())
    End Function
```
### Expected result

I should be getting a json result of my table
### Actual result

{"error": {
    "code": "",
    "message": "The query specified in the URI is not valid. The limit of '0' for Top query has been exceeded. The value from the incoming request is '20'.",
    "innererror": {
        "message": "The limit of '0' for Top query has been exceeded. The value from the incoming request is '20'.",
        "type": "Microsoft.OData.ODataException",
        "stacktrace": "   at System.Web.OData.Query.Validators.TopQueryValidator.Validate(TopQueryOption topQueryOption, ODataValidationSettings validationSettings)
   at System.Web.OData.Query.TopQueryOption.Validate(ODataValidationSettings validationSettings)
   at System.Web.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)
   at System.Web.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)
   at System.Web.OData.EnableQueryAttribute.ValidateQuery(HttpRequestMessage request, ODataQueryOptions queryOptions)
   at System.Web.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor, ODataQueryContext queryContext)
   at System.Web.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)"
    }
}}

**Comment by VikingsFan** [comment]
Now the default setting for WebAPI OData is : client can’t apply $count, $orderby, $select, $top, $expand, $filter in the query, query like localhost\odata\Customers?$orderby=Name will failed as BadRequest, because all properties are not sort-able by default, this is a breaking change in 6.0.0, if we want to use the default behavior that all query option are enabled in 5.x version, we can configure the HttpConfigration to enable the query option we want like this:

    configuration.Count().Filter().OrderBy().Expand().Select().MaxTop(null);
    configuration.MapODataServiceRoute("odata", "odata", edmModel);

document: http://odata.github.io/WebApi/#13-01-modelbound-attribute

**Comment by rwmcdonald** [comment]
The above didn't work for me, I had to do this:

config.Filter( QueryOptionSetting.Allowed ).Count( QueryOptionSetting.Allowed )

**Comment by ImGonaRot** [comment]
In the 6.0 you could add the attributes to specific controllers.
Are you saying that now you have to add it to the entire odata configuration?

**Comment by VikingsFan** [comment]
Pls read through the document, by default the queryoption is disabled, but you can enable it from global configuration or add model bound attribute.

**Comment by ImGonaRot** [comment]
Sorry. You are correct. Reading the documentation helps. ;)

**Comment by mikepizzo** [comment]
Closing issue as resolved.
