### ISSUE TITLE
odata nightly package

### ISSUE THREAD

**Issue by developermj** [OData/WebApi#815]
I apologize in advance if I'm posting this in the wrong place. I'm not familiar was the practices of this repository. I'm looking for a nightly of the vNext branch if one exists. Please assist. Thanks in advance.

**Comment by mikepizzo** [comment]
Thanks for your interest! 
The vNext branch was an experimental branch for supporting WebAPI over .NET Core.  We are planning instead to support .NET Core through common code in the master branch, so the vNext branch is no longer being maintained or published.
