### ISSUE TITLE
Public UnqualifiedCallAndEnumPrefixFreeResolver?

### ISSUE THREAD

**Issue by akamyshanov** [OData/WebApi#817]
Hi,

Before v6 we were able to write something like this:
```C#
httpCfg.EnableCaseInsensitive(odataCfg.EnableCaseInsensitive);
httpCfg.EnableEnumPrefixFree(odataCfg.EnableEnumPrefixFree);
httpCfg.EnableUnqualifiedNameCall(odataCfg.EnableUnqualifiedNameCall);
```
As of v6, we need to use DI but there is no ready-made public class that has the same effect. I noticed an implementation of what we need [here](https://github.com/OData/WebApi/blob/c44ce5547b1b44474bfa2d1208c68b90fa401556/OData/src/System.Web.OData/OData/UnqualifiedCallAndEnumPrefixFreeResolver.cs), but this class is internal. As a workaround we just copy-pasted this class into the project.

Suggestion: why not make it public?

**Comment by VikingsFan** [comment]
@akamyshanov before V6, we've got a lot of requests about how to enable A (some kind of resolver) & B, B & C, C & A...different combination of those resolver, it's hard to public and implement all the resolver, so we'd like open a entry in V6, and you can inject all kinds of resolver you want.

**Comment by Luiggi370z** [comment]
@akamyshanov 
Hi
I have the same issue, did you just copy and paste the class? for me is not working...
