### ISSUE TITLE
ODataEnumDeserializer.Read override not being called

### ISSUE THREAD

**Issue by rob-williams** [OData/WebApi#818]
I'm trying to override ODataEnumDeserializer.Read to deserialize some enum values in an edge case bug in our OData service where the actual enum type is empty and the enum values are stored elsewhere. However, my override isn't being called. Our code already has a provider inheriting from DefaultODataEntityDeserializerProvider, and an override of GetEdmTypeDeserializer that returns a custom ODataEntityDeserializer (with method overrides that _are_ being called), so our provider architecture is set up correctly.

I cloned this repo and it looks like ReadInline is being called directly instead of Read for ODataEnumDeserializers. I can't override ReadInline because it's a sealed method. Is there another way to customize enum deserialization? I feel as if Read should be called instead of ReadInline, as ReadInline is called by Read's default implementation.

I should note that my situation revolves around action parameters. Reading a payload of entity data in CRUD operations is working fine.
### Assemblies affected

System.Web.OData
### Reproduce steps

Create a type inheriting from ODataEnumDeserializer and override the Read method.
### Expected result

Read would be called when returned from a deserialization provider.
### Actual result

Read is not called. From my interpretation of the code ReadInline is called instead, which cannot be overridden.

**Comment by VikingsFan** [comment]
@rob-williams can you try V6.0, the method is public

**Comment by mikepizzo** [comment]
It looks like there is a solution in V6; ReadInline is now a public method. Please let us know if this does not address the issue.
