### ISSUE TITLE
support updating a property

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#82]
Looks like our implementation might not support updating a property for now.  
  
The url for updating a property would be the property name appended to the
edit url of the entity being updated, as per below. Although a similar result
can be achieved from PATCH, note that their payloads are slightly different;
for the PUT to the property url the body is just the primitive value (same as
would be retrieved with a GET); in JSON that looks like:  

    
    
    {
                    value : "Alfreds Futterkiste"
    }

where-as for the PATCH it is the object with only one property:  

    
    
    {
                    CompanyName : "Alfreds Futterkiste" 
    }

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1857](http://aspnetwebstack.codeplex.com/workitem/1857)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Apr 22, 2014 at 2:10 AM
**Reported by:**	cysu
**Updated on:**	May 5, 2014 at 10:23 AM
**Updated by:**	zjufish

**Comment by xuzhg** [comment]
Now, it's support to update:

1. Primitive
2. Complex 
3. Collection of them

Enum and Collection of enum, please refer to: #742, #743.

**Comment by xuzhg** [comment]
The related test cases, please refer to: https://github.com/xuzhg/WebApiSample/blob/master/Microsoft.AspNet.OData.Test/CRUD/UpdatePropertyTest.cs
