### ISSUE TITLE
There is no way to install Microsoft.OData.Client in a project that has OData 6.0 installed

### ISSUE THREAD

**Issue by ghost** [OData/WebApi#825]
If you have a solution that requires the latest version of "Microsoft.AspNet.OData" (Version 6.0) then you will not be able to install any version of "Microsoft.OData.Client" Nuget package in the same project, since you will have a conflict in dependency package versions.

The package dependencies for these NuGets are as follows:

Microsoft.AspNet.OData 6.0.0 -> Microsoft.OData.Core (>= 7.0.0 && < 8.0.0) 
Microsoft.OData.Client 6.15.0 -> Microsoft.OData.Core (= 6.15.0) 

If you install Microsoft.AspNet.OData 6.0 to a project, then you will be unable to install any available version of the Microsoft.OData.Client since you will get this error:

Microsoft.OData.Core 7.0.0 is not compatible with Microsoft.OData.Client 6.15.0

Is there an update to Microsoft.OData.Client to be expected soon that has updated dependencies?

**Comment by adrianm64** [comment]
Had the same problem.
Downloaded the nightly (Package source https://www.myget.org/F/odlnightly/api/v3/index.json) and it works for me.

Microsoft.OData.Client.7.0.0-Nightly20160905

**Comment by kbarkhausen-campusmgmt** [comment]
Any idea when the official Nuget Microsoft.OData.Client v7.0.0 will be available? We cannot add a nightly build package into our solution. We would need an official release version in order to incorporate it into our production version.

**Comment by mleyb** [comment]
Any news on this one?

**Comment by kbarkhausen-campusmgmt** [comment]
Nuget Microsoft.OData.Client v7.0.0 has not been released yet.

**Comment by berndesj** [comment]
is there someone in Microsoft reading these issues?
if so, a politically correct response, at least ,would be appreciated  on a time frame of new release.

thank you

**Comment by tan00001** [comment]
Google cannot seem to find anything on Nuget Microsoft.OData.Client v7.0.0 release schedule. Is Microsoft not getting any request for it? What is going on?

**Comment by NetTecture** [comment]
And now it is end August and still - nothing. Anyone working on this? Right now the Microsoft OData Stack is a wonderfull mess - half does not work with a modern environment. What are we supposed to do? Split our projects?

**Comment by robertmclaws** [comment]
I have been telling people for a while now that you should be building your OData APIs in separate projects built on .NET 4.X, and then have a separate web project for .NET Core apps.

This makes sense anyways because you should be scaling your back- and front-ends independently.

I don't think you guys appreciate how complicated the OData stack is. The refactor they're doing is *massive*, and they have to support TWO target runtimes. Subscribe to all of the notifications from this repo, and you'll see how hard they are working. They're getting to it. You're just going to have to be patient.

**Comment by NetTecture** [comment]
Well, is there any word when something will go up nn newget even in alpha state?

**Comment by ysmoradi** [comment]
@robertmclaws Consider following examples:

1- You've a server side app based on OData. And at server side, there is a requirement to retrieve data from dynamic crm (as an example). Dynamic CRM itself is an OData server, so you need to retrieve data from it in your server side code using odata client. So you add OData client nuget packages to your OData server, and it does not work. Yeah, you can use separate app domain or even separate app, but it has its own costs. Or maybe you'd recommend us to use its awful SOAP based SDK.

2- You need new odata core features at client side, such as $apply.

**Comment by alexandergorban** [comment]
In my case works
Microsoft.AspNet.OData v.5.10.0
Microsoft.Data.OData v5.8.3
Microsoft.OData.Core v7.4.0-beta3
and 
Microsoft.AspNet.OData v.5.10.0
Microsoft.Data.OData v5.6.0
Microsoft.OData.Core v6.15.0

**Comment by mikepizzo** [comment]
We have released OData Client support for 7.x which is compatible with the latest OData WebAPI 6.x.
