### ISSUE TITLE
$expand does not seem to work with PageSize EnableQuery Attribute

### ISSUE THREAD

**Issue by borisqbf** [OData/WebApi#827]
Attempting to issue query that returns all entities 10 per page. It works. Adding $expand query options - getting a fatal error. Removing PageSize parameter from EnableQuery makes it work again.
### Assemblies affected

Microsoft.OData.Core 6.15,Microsoft.OData.Edm 6.15, Microsoft.AspNet.OData 5.9.1
### Reproduce steps

I have Student entity with navigation property StudenPhones - a collection of StudenPhone entities. My Get() method in StudentController::

```
    [EnableQuery(PageSize = 10)]
    public IQueryable<Student> Get()
    {
        return db.Students;
    }
```

Issuing **GET localhost/StudentService/Students** returns all Students 10 per page.
Issuing **GET localhost/StudentService/Students/?$expand=StudentPhones** causes Get() to crash.
Removing  **[EnableQuery(PageSize = 10]** attribute from Get() method and issuing **GET localhost/StudentoneService/Students/?$expand=StudentPhones** again returns all Student Entities with StudentPhones expanded as expected but not in paginated form.
### Expected result

GET localhost/StudentService/Students/?$expand=StudentPhones should return 10 Student Entities per page with StudentPhones property expanded if Get() method is decorated with  [EnableQuery(PageSize = 10)] attribute
### Actual result

Exception is thrown:
{
  "error":{
    "code":"","message":"An error has occurred.","innererror":{
      "message":"Exception has been thrown by the target of an invocation.","type":"System.Reflection.TargetInvocationException","stacktrace":"   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Web.OData.Query.ODataQueryOptions.LimitResults(IQueryable queryable, Int32 limit, Boolean& resultsLimited)\r\n   at System.Web.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\r\n   at System.Web.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor)\r\n   at System.Web.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutedAsync(HttpActionExecutedContext actionExecutedContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()","internalexception":{
        "message":"An error occurred while executing the command definition. See the inner exception for details.","type":"System.Data.Entity.Core.EntityCommandExecutionException","stacktrace":"   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)\r\n   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)\r\n   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()\r\n   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Web.OData.Query.TruncatedCollection`1..ctor(IQueryable`1 source, Int32 pageSize)\r\n   at System.Web.OData.Query.ODataQueryOptions.LimitResults[T](IQueryable`1 queryable, Int32 limit, Boolean& resultsLimited)","internalexception":{
          "message":"Oracle 11.2.0.3.0 does not support APPLY","type":"System.Exception","stacktrace":"   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)\r\n   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)\r\n   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)\r\n   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)\r\n   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)"
        }
      }
    }
  }
}

**Comment by VikingsFan** [comment]
@borisqbf this seems is EF related issue, pls try with in-memory data to see the issue is repro or not.

**Comment by borisqbf** [comment]
Investigated further - the problem occurs only if expanding one-to-many relations and only if the database is ORACLE 11.2 and older. 
The problem is caused by EF6 generating SQL that contains OUTER APPLY which Oracle supports from v12c only. 
Having said that it looks like a combination of $extend and PageSize parameter is forcing EF6 to use OUTER APPLY. If I implement "poor man's" paging in my code:
            return db.Students.OrderBy(p=>p.StudentId).Skip(10).Take(10);
EF6 generates SQL based on LEFT OUTER JOIN which is semantically equivalent to OUTER APPLY and everything works...
 Any suggestions? workarounds?

**Comment by xuzhg** [comment]
@borisqbf Please re-open it or file a new issue for us if you have further questions/issues. We'd love to hear your feedback. Thanks a lot.
