### ISSUE TITLE
OData webAPI with ASP.NET Core: 500 when trying to get metadata

### ISSUE THREAD

**Issue by SuneLindhard** [OData/WebApi#828]
I've been struggling with setting up OData with ASP.NET Core. The samples I can find here on GitHub are either 6 months old or targetet .NET Core. What I'm trying is to create a ASP.NET Core project (with full .Net Framework).

I'm using the newest NuGet package I could find: Microsoft.AspNetCore.OData": "1.0.0-rtm-00015". I don't see any samples using this. I'm using the newest AspNetCore and the .net 4.6.1 framework

I've set up a very simple OData controller and I am able to get data from it and even using $filter. When I try to $expand or get /odata/$metadata I get a 500 error with no further information.

In my startup file I try to register like this:
`services.AddOData<IDataService>(builder =>`
Like a saw in the samples. However it seems to ignore whatever I do in here (removing properties and stuff)

**Comment by robertmclaws** [comment]
As far as I know, OData does not work with ASP.NET Core yet, even if you're running on the full .NET Framework. They are a very small team and still working on getting that support in place.

**Comment by ymoradi** [comment]
@robertmclaws Sample of ASP.NET Core app with ASP.NET Web API OData on Full .NET Framework:
https://github.com/ymoradi/OwinAspNetCore
Just configure owin pipeline on top of asp.net core pipeline (-;

**Comment by robertmclaws** [comment]
@ymoradi This looks really cool. Would be nice if it had some XML code docs and followed the 1 class per file convention. If you could add some unit tests and what-not I'd be interested in trying it in a production app.

**Comment by SuneLindhard** [comment]
@ymoradi Wow that seems to be just what I'm looking for. I'm going to see if I can use that for my current project tomorrow.

**Comment by robward-ms** [comment]
#975 is being used to track the release of a Nuget package for ASP.Net Core. Since this issue appears to be resolved for @SuneLindhard using @ysmoradi code, I'm closing this issue. Please re-activate if I'm missing an ask here not already covered by #975.
