### ISSUE TITLE
Web Api Odata v4 -Stackoverflow Exception - AppPool Crash

### ISSUE THREAD

**Issue by compmks** [OData/WebApi#829]
_I have 3 models classes as attached, two of the are referenced in 1 one model class as foreignkey and navigation property[total 4 properties]. When I Query  all four Properties using OData at server side my IIS AppPool Crash and through StackOverFlow Exception but if I don't query 1 of the all works good but again when I try to query all four of them again system will through StackOverflow Exception_  
### Assemblies using

_"EntityFramework" version="6.1.3"_
_Microsoft.AspNet.OData" version="5.9.0" *
*"Microsoft.AspNet.Razor" version="3.2.3"_
_"Microsoft.AspNet.WebApi" version="5.2.3"_
_"Microsoft.AspNet.WebApi.Client" version="5.2.3"_
_"Microsoft.AspNet.WebApi.Core" version="5.2.3"_
_"Microsoft.AspNet.WebApi.Owin" version="5.2.3"_
_"Microsoft.AspNet.WebApi.WebHost" version="5.2.3"_
_"Microsoft.AspNet.WebPages" version="3.2.3"_
_"Microsoft.OData.Core" version="6.15.0"_
_"Microsoft.OData.Edm" version="6.15.0"_
_"Microsoft.Owin" version="3.0.1"_
_"Microsoft.Owin.Cors" version="3.0.1"_
_"Microsoft.Owin.Host.SystemWeb" version="3.0.1"_
_"Microsoft.Spatial" version="6.15.0"_
_"Newtonsoft.Json" version="9.0.1"_
_"Owin" version="1.0"_
### Reproduce steps

_See the Text file attached with name testurls.txt_  
### Expected result

_I must receive the value for all the Fields for which i sent the query._  
### Actual result

_An StackOverFlow Exception._  
### Additional details

_The Data is queried from Database and I think the issue is somewhen in parsing/Materialization_
_I am attaching debbug reports
[w3wp.exe__DefaultAppPool__PID__2132__Date__10_06_2016__Time_08_04_12PM__535__Manual Dump_MultipleRules.zip](https://github.com/OData/WebApi/files/514630/w3wp.exe__DefaultAppPool__PID__2132__Date__10_06_2016__Time_08_04_12PM__535__Manual.Dump_MultipleRules.zip)
[queryurls.txt](https://github.com/OData/WebApi/files/514644/queryurls.txt)
._

**Comment by compmks** [comment]
Does it have something related to $expand, as I have 16 navigation properties under $expand node of query?

**Comment by xuzhg** [comment]
Thanks your information. Please re-open it or file a new issue if you have further questions/issues.
