### ISSUE TITLE
"'ODataFeedDeserializer' does not support Read" exception when passing collection of Entities to Action

### ISSUE THREAD

**Issue by kseniya-terekhova** [OData/WebApi#831]
ODataFeedDeserializer doesn't override Read method. So, then collection of Entities is passed  to Action, base deserilizer method is called. The later throws the exception and collection fails to be deserialized. At the same time, then the ODataFeedDeserializer is called from other deserializer, e.g. ODataActionPayloadDeserializer, exactly the same collection is parsed without problems. So, passing the collection as ODataActionParameters into Action method helps, but it isn't so convinient.
### Assemblies affected

System.Web.OData, Version=5.7.0.0 
### Reproduce steps

**Action method**

``` C#
[HttpPost]
[ODataRoute("AddSettings")]
public async Task<IHttpActionResult> AddSettings(
    [FromUri] string scope,
    [FromUri] Guid userId,
    [FromUri] string childId,
    [FromUri] string deviceId,
    IEnumerable<SettingsBase> settings)
    //ODataActionParameters parameters)
    {
        //var settings = parameters["settings"] as IEnumerable<SettingsBase>;           
        ...
```

**Action registration**

``` C#
builder.EntitySet<SettingsBase>("Settings");
builder.Action("AddSettings")
    .CollectionEntityParameter<SettingsBase>("settings");
```

**Request Payload**

``` json
[{
    "@odata.type": "#EkaEntityMapping.ApplicationUsageProtectionSwitch",
    "EkaTypeUniqueId": 1317793492,
    "Key": null,
    "IsDeleted": false,
    "ValidTill": "0001-01-01T00:00:00Z",
    "ID": "1317793492",
    "SyncVersion": "2-1",
    "IsOn": true
}, {
    "@odata.type": "#EkaEntityMapping.SmsControlSwitch",
    "EkaTypeUniqueId": 1900094280,
    "Key": null,
    "IsDeleted": false,
    "ValidTill": "0001-01-01T00:00:00Z",
    "ID": "1900094280",
    "SyncVersion": "7-1",
    "IsOn": false
}, {
    "@odata.type": "#EkaEntityMapping.PermissionRequestQueueLength",
    "EkaTypeUniqueId": 2204011929,
    "Key": "setting_app_request_status",
    "IsDeleted": false,
    "ValidTill": "0001-01-01T00:00:00Z",
    "ID": "2204011929-c2V0dGluZ19hcHBfcmVxdWVzdF9zdGF0dXM=",
    "SyncVersion": "2-12",
    "Length": 25
}]
```
### Expected result

`IEnumerable<SettingsBase> settings` contain passed entities collection. 
### Actual result

`IEnumerable<SettingsBase> settings` is null. _"ODataFeedDeserializer does not support Read"_ exception is thrown during deserialization process. When switching `ODataActionParameters` and passing the array under "settings" key, it is deserialized normaly.
### Additional details

It is stated in the Issue #180, that entities feed should be passed to Action normally from 5.5 version, but we have the problem reproduced in 5.7.0.

**Comment by xuzhg** [comment]
Please use 
`ODataActionParameters parameters` not `IEnumerable<SettingsBase>` as the parameter.

tutorial can be found [here](http://odata.github.io/WebApi/#04-07-action-parameter-support)

Thanks!
