### ISSUE TITLE
can't call FindCustomersWithProductAny and misc.

### ISSUE THREAD

**Issue by mowali** [OData/WebApi#832]
I cloned the project into VS 2015. I didn't download or installed any other packages because I should have everything I need according to what I  understood from project description. I was able to build it and run its tests successfully. I launched the ODataSample.Web sample, which launched the Kestrel webserver. Here are the issues I faced:
1. At first, I setup a break point at this method and tried to call it
   
   public IEnumerable<Customer> Get()
   {
        return _sampleContext.Customers;
   }
   from fiddler. While it was hitting the breakpoint, finding the customers, but nothing was showing up in browser or fiddler. 
   To fix it, I went to Extensions
   
   ODataServiceCollectionExtensions.cs
   and after the addMVCCore, I did:
   
   .AddJsonFormatters();
   which fixed the issue and results are returned
2. The suggested way to execute the public IActionResult Get(int customerId) per the comment above it is to use
   
   // GET odata/Customers(5)
   but I tried that and it didn't work. Doing this notation worked for me:
   
   // GET odata/Customers/1
   so forward slash instead of parens
3. I'm stuck at the FindCustomersWithProductAny method and how to call it. I've tried (I set breakpoints at both gets):
   http://localhost:5000/odata/FindCustomersWithProduct(productId=1) I got 404
   http://localhost:5000/odata/FindCustomersWithProduct(ProductId=1) I got 404
   http://localhost:5000/odata/Customers/Default.FindCustomersWithProductId(productId=1) took me to
   
   ```
   public IActionResult Get(int customerId)
   ```
   
   http://localhost:5000/odata/Customers(1)/Default.FindCustomersWithProductId(productId=1) gave me this popup error: Description: Assertion failed. with Abort/Retry/Ignore options

what am I missing?

**Comment by xuzhg** [comment]
@mowali 

Very glad to hear you trying our vNext branch. However, the codes in this branch are not stable and it's not finished yet (It's a long journey). And I am sorry that I am block by other new area development in the past several months and can't update the codes frequently. 

In fact, the codes can work for some scenarios if you are using the lastest vNext branch codes, I think you may noticed that I added several router for the OData in the Startup.cs. So, if you issue request (for example):

```C#
http://localhost:5000/odata1/Customers
```
you can get:
```json
{
  "@odata.context": "http://localhost:5000/odata1/$metadata#Customers",
  "value": [
    {
      "CustomerId": 1,
      "FirstName": "Mark",
      "LastName": "Stand"
    },
    {
      "CustomerId": 2,
      "FirstName": "Peter",
      "LastName": "Huward"
    },
    {
      "CustomerId": 3,
      "FirstName": "Sam",
      "LastName": "Xu"
    }
  ]
}
```

Thanks!
