### ISSUE TITLE
How to do composite key routing in oData 6.0.0

### ISSUE THREAD

**Issue by PaulTodd** [OData/WebApi#833]
I am using the new version of oData and it seems that my Routing has broken.

Microsoft.AspNet.OData v6.0.0
Microsoft.OData.Core v7.0.0

```
    <ODataRoute("myTable(first_id={f_id}, second_id={s_id})")>
    Public Function [Get](<FromODataUri> f_id As Long, <FromODataUri> s_id As Long) As IHttpActionResult
        db.Configuration.AutoDetectChangesEnabled = False
        Return Ok((From i In db.MY_TABLE Where i.FIRST_ID = f_id AndAlso i.SECOND_ID = s_id))
    End Function
```

http://domain/odata/myTable(first_id=1, second_id=2)

I should get 1 result, but when I call it, it gives me invalid route path.  I downgraded to Microsoft.AspNet.OData 5.9.1 and Microsoft.OData.Core 6.1.5 and it works fine.  Is there an example of what I should do for this type of routing?

Thanks

**Comment by jemerald** [comment]
The following signature works:
`public Person Get([FromODataUri] string keyFirstName, [FromODataUri] string keyLastName)`

request URL
`/people(firstName='Kate',lastName='Jones')`

**Comment by xuzhg** [comment]
@jemerald Thanks!

@PaulTodd  Yes! for convention routing,  please add "key" prefix for the composite keys' property name as the function parameter. for routing convection, please keep the original logic unchanged.
