### ISSUE TITLE
OData 6.0 How to enable Unqualified function/action call?

### ISSUE THREAD

**Issue by flibustier7seas** [OData/WebApi#835]
### Assemblies affected

Microsoft.AspNet.OData version=6.0.0

This package is missing EnableUnqualifiedNameCall method.

It works for me:

```
httpServer.Configuration.MapODataServiceRoute(
                routeName: routeName,
                routePrefix: routePrefix,
                model: model,
                batchHandler: new DefaultODataBatchHandler(httpServer),
                uriResolver: new UnqualifiedODataUriResolver());


private static void MapODataServiceRoute(this HttpConfiguration configuration, string routeName,
            string routePrefix, IEdmModel model, ODataBatchHandler batchHandler, ODataUriResolver uriResolver)
        {
            configuration.MapODataServiceRoute(routeName, routePrefix, builder =>
                builder
                    .AddService(ServiceLifetime.Singleton, sp => model)
                    .AddService(ServiceLifetime.Singleton, sp => batchHandler)
                    .AddService(ServiceLifetime.Singleton, sp => uriResolver)
                    .AddService<IEnumerable<IODataRoutingConvention>>(ServiceLifetime.Singleton, sp =>
                        ODataRoutingConventions.CreateDefaultWithAttributeRouting(routeName, configuration)));
        }
```

Thanks

**Comment by VikingsFan** [comment]
see https://github.com/OData/WebApi/issues/812

**Comment by VikingsFan** [comment]
please refer to this test: https://github.com/OData/WebApi/blob/OData60/OData/test/E2ETest/WebStack.QA.Test.OData/UriParserExtension/UnqualifiedCallTest.cs

**Comment by pomadin** [comment]
I also have some confusion. The main [docs](http://odata.github.io/WebApi/#unqualified-functionaction-call) says there is the extension **EnableUnqualifiedNameCall**. But it's not available in OData WebApi v6. How could I use it or what API version should be used?

**Comment by jemerald** [comment]
@pomadin see the OP's solution, you need to use the `IContainerBuilder` and configure it with UnqualifiedODataUriResolver

**Comment by xuzhg** [comment]
Close it. Please re-open or file an new issue if you have further concern.

**Comment by robertmclaws** [comment]
Am I the only one that thinks it's ridiculous that it takes 700+ characters to enable that feature, and that there's no documentation on how to use it?
