### ISSUE TITLE
Functions/Actions bound to a collection of entity should be advertised.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#84]
Say entity types:  

    
    
    Account,
    PremiumAccount, which derives from Account
    PaymentInstrument
    

Containment navigation properties:  

    
    
    Account.PayinPIs, which is of collection PaymentInstrument type
    

Actions bound to Collection of PaymentInstrument:  

    
    
    Clear
    

If the request is GET
~/Accounts?$expand=PayoutPI&$format=application/json;odata.metadata=full  
  
Then the advertised action of Clear should be in the response payload.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1862](http://aspnetwebstack.codeplex.com/workitem/1862)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Apr 22, 2014 at 8:40 AM
**Reported by:**	jinfutan
**Updated on:**	May 5, 2014 at 10:16 AM
**Updated by:**	zjufish

**Comment by LianwMS** [comment]
On *2014-05-05 17:16:26 UTC*, **zjufish** commented:

pending odl to fix

**Comment by xuzhg** [comment]
Resolved.
See PR: https://github.com/OData/WebApi/pull/642.
