### ISSUE TITLE
Should GetODataRootContainer be public instead of internal?

### ISSUE THREAD

**Issue by 0xced** [OData/WebApi#840]
In order to support OData WebApi 6.0.0 in [Swashbuckle.OData](https://github.com/rbeauchamp/Swashbuckle.OData), we have to use `httpConfig.GetODataRootContainer(oDataRoute)` in [several](https://github.com/rbeauchamp/Swashbuckle.OData/blob/0e32447a01598116bb651f7bf7f7149a8df29a7b/Swashbuckle.OData/Descriptions/AttributeRouteStrategy.cs#L33) [places](https://github.com/rbeauchamp/Swashbuckle.OData/blob/0e32447a01598116bb651f7bf7f7149a8df29a7b/Swashbuckle.OData/Descriptions/SwaggerRouteStrategy.cs#L94).

I had to [use reflection](https://github.com/rbeauchamp/Swashbuckle.OData/blob/0e32447a01598116bb651f7bf7f7149a8df29a7b/Swashbuckle.OData/HttpConfigurationExtensions.cs#L56-L64) in order to access `GetODataRootContainer`. Should `GetODataRootContainer` be made public instead of internal or am I missing another way than using reflection to fulfill Swashbuckle.OData goals?

**Comment by gathogojr** [comment]
The `GetODataRootContainer` method is now declared in a public interface `IPerRouteContainer` and defined in a public class `PerRouteContainerBase` class and its derived types
