### ISSUE TITLE
How to make the odata version 7.0 case insensitive 

### ISSUE THREAD

**Issue by spuc** [OData/WebApi#843]
*Short summary (3-5 sentences) describing the issue.*  

### Assemblies affected
*Which assemblies and versions are known to be affected e.g. OData .Net lib 6.15-beta.*  

After upgrading to odata version 7, the config.EnableCaseInsensitive does not work any more
I tried several work arounds, such as ..
-1.	Added a class with CaseInsensitiveResolver specification to the ODataUriResolver singleton
-add a ODataUriHelper class to rewrite the filter
nothing worked

are there any working solutions to making odata version 7 work with case insensitivity?

thanks!

If known, describe the steps to reproduce the issue:

upgrade odata to latest version (version 7)
keep case insensitivity configuration or make a case insensitive query

**Comment by VikingsFan** [comment]
please refer to https://github.com/OData/WebApi/issues/812

**Comment by spuc** [comment]
Thanks, I tried implementing this CaseInsensitiveResolver  on the webapiconfig.cs but it didn't make any difference
would you have any sample basic repo of this working for the case insensitive?
I am not sure why it did not work
should it be compatible with odata version 7?
thanks!

**Comment by freeranger** [comment]
@spuc - works for me.  Perhaps you should post a basic repo showing it NOT working and people can look and see what's wrong with it?
