### ISSUE TITLE
Wrong IEdmModel used by EnableQueryAttribute in vNext branch

### ISSUE THREAD

**Issue by IgorWolbers** [OData/WebApi#848]
`EnableQueryAttribute` is not finding the defined `IEdmModel` model in the `ODataSample.Web` project. The found model has an empty `ReferencedModels` property where the instance defined in the `Startup` class has 4 types associated with it.

* Branch: `vNext`
* Updated `global.json` to use sdk `"version": "1.0.0-preview2-003131"`
* Added `services.AddMvc();` to `ConfigureServices(IServiceCollection services)` method so that json could be included as output.

### Assemblies affected
`Microsoft.AspNetCore.OData`

### Reproduce steps
Use the included `ODataSample.Web` as the test application. Query the `odata/Products` feed with any valid OData filter query string. The first url below will output the products found in the service, the second one triggers the `EnableQueryAttribute` to apply the filter and will throw an Exception.

    /odata/products/
    /odata/products/?$filter=ProductId%20eq%201

### Expected result
The `EnableQueryAttribute` should find the same `IEdmModel` model as defined in the `Startup` class and use it to apply the filter.

### Actual result
An empty `IEdmModel` model is found and the ClrType cannot be resolved to an Odata model so an Exception is thrown.

**Comment by IgorWolbers** [comment]
Fixed under the following conditions.

1. ProductsController - removed the `RouteAttribute`
2. The URL entity/controller name is case sensitive. `Products` should be used and not any other casing of this name.

Under those conditions the `ODataRouteConstraint` can find the associated `IEdmModel` based on the route constraint and set it on a new `IODataFeature` that is then associated with that request.

The only fix/bug IMO should be that the controller used in the URL should not be case sensitive. Maybe this is an option somewhere on the constraint?

**Comment by IgorWolbers** [comment]
There is 1 other bug as well in type `Microsoft.AspNetCore.OData.Routing.ODataRouteConstraint::Match` from the vNext branch.

```
// Leave an escaped '/' out of the service route because DefaultODataPathHandler will add a
// literal '/' to the end of this string if not already present. That would double the slash
// in response links and potentially lead to later 404s.
if (serviceRoot.EndsWith(_escapedSlash, StringComparison.OrdinalIgnoreCase))
{
    serviceRoot = serviceRoot.Substring(0, serviceRoot.Length - 3);
}
```

That 3 should be a 1 as you only want to remove the last single trailing character in the event of a trailing `/` and not the last 3.

**Comment by grahamehorner** [comment]
@IgorWolbers are you seeing an issue with the 

```
> // Leave an escaped '/' out of the service route because DefaultODataPathHandler will add a
> // literal '/' to the end of this string if not already present. That would double the slash
> // in response links and potentially lead to later 404s.
> if (serviceRoot.EndsWith(_escapedSlash, StringComparison.OrdinalIgnoreCase))
> {
>     serviceRoot = serviceRoot.Substring(0, serviceRoot.Length - 3);
> }
```
or are you making an assumption? I read this to be correct as the length of an escaped '/' is 3 characters not 1 ?
