### ISSUE TITLE
Is the .NET Core initiative of OData dead?

### ISSUE THREAD

**Issue by dozer75** [OData/WebApi#851]
Hi,

I am in need of OData services in a .NET Core project, but the source for this doesn't support the latest release of .NET Core only an early beta release of it. I see that this pull request (https://github.com/OData/WebApi/pull/768) exists, but isn't applied to the parent branch.

So, is the .NET Core part dead? Is there any alternative I have missed here?

--Rune

**Comment by xuzhg** [comment]
@dozer75 

I am sorry that the rate to updating our codes slows down recently because most of our resources are focus on other areas. However, I do think the OData for Asp.Net Core will continue once the new resources are founded. Thanks.
