### ISSUE TITLE
ODataQuerySettings should be made more prominent

### ISSUE THREAD

**Issue by 9Rune5** [OData/WebApi#852]
I have spent most of today looking at issues similar to what is discussed in #555 and afaict a major short-coming of how queries are applied is that ODataQuerySettings is hidden.

EnableQueryAttribute keeps it around as a private field, so inheriting from EnableQueryAttribute leads down a blind alley as far as paging is concerned (unless I hard code some limit).

Given 
```
        [mmEnableQuery(PageSize = 20)]
        public async Task<IHttpActionResult> Get(ODataQueryOptions<BorrowerBarcode> options)
        {
```
There is no obvious way to figure out that page size has been set to 20 (or set at all). I need to pass a custom request to my DAL (using WCF) and PageSize is a deal breaker.

And of course, at the end my mmEnableQueryAttribute.ApplyTo() needs to make sure the paging links are applied. Again: The ODataQuerySettings object is missing in action!

**Comment by ImGonaRot** [comment]
Admittedly it would be nice to see the original / base ODataQueryOptions but there is a workaround for pagesize.
Your "mmEnableQuery" class should have inherited from "EnableQueryAttribute" and in doing so you will have "this.PageSize" that will show you the current page size being requested.

I have something like this.
In the case below, if the user does not specify page size then it defaults to 100.

```c#
public override IQueryable ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
{
	IQueryable result = default(IQueryable);

	// get the original request before the alterations
	HttpRequestMessage originalRequest = queryOptions.Request;

	// get the original URL before the alterations
	string url = originalRequest.RequestUri.AbsoluteUri;

	// rebuild the URL if it contains a specific filter
	if (queryOptions.Filter != null && url.Contains("$filter=???"))
	{
		// apply the new filter
		url = url.Replace("$filter=???", "$filter=???");

		// build a new request for the filter
		HttpRequestMessage req = new HttpRequestMessage(HttpMethod.Get, url);

		// reset the query options with the new request
		queryOptions = new ODataQueryOptions(queryOptions.Context, req);
	}

	// top should override page size if used
	if (queryOptions.Top != null)
	{
		// apply any pending information that was not previously applied
		result = queryOptions.ApplyTo(queryable);
	}
	else
	{
		if (this.PageSize == 0)
		{
			this.PageSize = 100;
		}
		// apply the query options with the new page size
		result = queryOptions.ApplyTo(queryable, new ODataQuerySettings { PageSize = this.PageSize });
	}

	// add the NextLink if one exists
	if (queryOptions.Request.ODataProperties().NextLink != null)
	{
		originalRequest.ODataProperties().NextLink = queryOptions.Request.ODataProperties().NextLink;
	}
	// add the TotalCount if one exists
	if (queryOptions.Request.ODataProperties().TotalCount != null)
	{
		originalRequest.ODataProperties().TotalCount = queryOptions.Request.ODataProperties().TotalCount;
	}

	// return all results
	return result;
}
```

**Comment by 9Rune5** [comment]
Yes, that looks like the sample code posted in other threads.

Do the NextLink code actually work? 

AFAICT, it is EnableQueryAttribute.ApplyQuery() that pushes the result into a "TruncatedCollection". Then, and only then, is the need for a "next page" link determined. 

Not invoking base.ApplyQuery() should cause quite a few headaches IMO. And those are not easily solved without access to the private ODataQuerySettings object.

My other complaint was the lack of PageSize information when invoking my Get-handler. It needs this because I cannot transfer an IQueryable result using WCF from my DAL. The page cropping is done someplace else.

What I settled for in the end was to keep a global PageSize for my project. Not a very attractive solution, but I see no other option.

**Comment by ImGonaRot** [comment]
On my system the NextLink != null is working so that I only apply the next link if there is a need for the next link.

So far I have able to use Filter, OrderBy, Top, Skip, Count, Expand, and Select with the code listed above.
The source code for base.ApplyQuery calls queryOptions.ApplyTo which I am already calling in my If Else page size statement but the base.ApplyQuery has _querySettings which will not work because I am using a new ODataQuerySettings in the page size If Else.
https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/EnableQueryAttribute.cs
