### ISSUE TITLE
Delta feed entries contain all properties and not just changed properties.

### ISSUE THREAD

**Issue by ll-sc** [OData/WebApi#857]
I'm trying to use WebApi + ODataLib to create a Delta Sync feed.  I see that the changes to my objects are being tracked correctly, but serialization results in all properties of the object being emitted, not just the properties that were changed.

### Assemblies affected

WebApi 6.15.0.0

### Reproduce steps
Please see https://github.com/ll-sc/WebApi/commit/4424a1d04ec55bc045d0f56e5b9d537df2021315.  I've hijacked the UntypedDeltaWorksInAllFormats testcase.  

### Expected result
There should be 4 properties on the first object, and 3 properties on subsequent objects.  The first delta object is the only one that should have the FavoriteNumbers property in the new test case.  The rest should be missing FavoriteNumbers, since FavoriteNumbers is not being set.

### Actual result
All delta objects in the test case have all 4 properties (including FavoriteNumbers).

**Comment by mikepizzo** [comment]
Should be fixed by PR #901 (for OData WebAPI 5.x) and PR #903 (for OData WebAPI 6.x)
