### ISSUE TITLE
DateTime JSON with time zone is converted to DateTimeKind.Unspecified.

### ISSUE THREAD

**Issue by Shachar1** [OData/WebApi#867]
When posting an object to OData controller with DateTime property, the DateTime is serialized to DateTimeKind.Unspecified although the JSON includes TimeZone property according ISO8601 standard.

for example - "2016-03-21T09:55:22.638Z" , is getting DateTimeKind.Unspecified
### Assemblies affected
I'm using Asp.Net.Odata 5.9 
### Expected result
* I would expect DateTimeKind.UTC in the example above

**Comment by biaol-odata** [comment]
Close as duplicated of [#804](https://github.com/OData/WebApi/issues/804)
