### ISSUE TITLE
ODataUriParser can not parse key segment after function segment

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#87]
ODataUriParser can not parse key segment after function segment  
such as:  
"~/Customers(42)/NS.BoundToEntityReturnsEntityCollectionNoParams()(42)"  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1872](http://aspnetwebstack.codeplex.com/workitem/1872)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Apr 23, 2014 at 12:47 PM
**Reported by:**	fenzhao
**Updated on:**	May 5, 2014 at 10:07 AM
**Updated by:**	zjufish

**Comment by VikingsFan** [comment]
now in 5.7 can use Key-as-segment convention as a work around https://github.com/OData/WebApi/commit/33c370b79fe055a57fbd6e3767a007437f2f8c41#diff-29d49a3aa2314e069f5548d433c0deddR296
