### ISSUE TITLE
$apply used with Entity Framework causes memory leaks

### ISSUE THREAD

**Issue by kosinsky** [OData/WebApi#874]
Dynamic CLR types generated to represent shape in groupby/aggregate clauses are aggressively cached by Entity Framework 6 in many places and as result never garbage collected. Entity Framework caches whole Query plan and parts of lambda expression used to represent a query. As a result, each next call make system a bit slower.

**Comment by markdstafford** [comment]
Hi Konstantin, thanks for creating the issue. Can you please clarify whether this is an issue with WAO or whether it's an issue with EF? If it is our issue, are you planning to send a PR or is this something you would like us to look at?

**Comment by kosinsky** [comment]
Issues is on the edge. EF caches types used in queries for performance reasons and current implementation generates at least 2 dynamic types (in two dynamic assemblies) per query and EF caches them. Original implementation with emitting dynamic types was based on assumption that generated types will be thrown away in all cases.

**Comment by xuzhg** [comment]
@kosinsky Please verify the fix and close it.

**Comment by kosinsky** [comment]
@xuzhg Didn't notice right away. Looks good now. Closing.
