### ISSUE TITLE
Can/should I indicate that an entity is not a "top-level" entity?

### ISSUE THREAD

**Issue by silkroadscott** [OData/WebApi#877]
We're building an OData API and have a couple of cases where Entity B is contained by Entity A. So, for instance, requesting a particular record of type Entity B would look like this:
`GET ~/entitya(aid)/entityb(bid)`

However, it is NOT possible to access a record of type Entity B directly, such as this:
`GET ~/entityb(bid)`

Functionally this works great, but the question is around the generated metadata. It includes both Entity A and Entity B:
>       <EntityType Name="entitya">
>        <Key>
>          <PropertyRef Name="aid" />
>        </Key>
>        ...properties...
>        <NavigationProperty Name="entityb" Type="Collection(Myapi.Graph.Models.EntityB)" ContainsTarget="true" />
>      </EntityType>
>      <EntityType Name="entityb">
>        <Key>
>          <PropertyRef Name="bid" />
>        </Key>
>        ...properties...
>      </EntityType>

Is this "okay"? Is it permissible to have an entity appear in the metadata that can't be accessed directly? Or does the above metadata structure imply to a consumer that they should be able to access Entity B directly?

### Assemblies affected
Microsoft.OData.Edm 6.15.0

**Comment by xuzhg** [comment]
That's the scenario of Containment. If a navigation property of Entity B is contained by Entity A, that means you should only access such property from entity A. 

The generated metadata includes both Entity A and Entity B, it's totally correct. Otherwise, OData can't know how to serialize/desterilize the entity of B. The difference I think is that Entity A has an entity set while Entity B doesn't have a corresponding entity set.

**Comment by silkroadscott** [comment]
Thank you for confirming that both entities should be listed in the metadata. Your comment about the entitysets makes sense, although in my case I still see entityset entries even for the contained entities. Does that indicate that I need to do something else to those entities to prevent their entitysets from appearing in the metadata?

**Comment by silkroadscott** [comment]
@markdstafford Hi Mark, was the addition of the in-progress label an indication that the generated metadata isn't handling contained entities correctly? (I.e. is it incorrect that fully contained entities still get an <EntitySet> entry in the metadata?)

**Comment by mikepizzo** [comment]
If you set the [Contained] attribute on your navigation property in your model, and only define the entity set for entitya you should not see the entity set for the contained entity.

i.e.;
~~~c#
    public class entitya
    {
       // properties...
        [Contained]
        public IList<entityb> entityb { get; set; }
    }

   public IEdmModel GetModel()
   {
         ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
         builder.EntitySet<entitya>("EntityAs");
         return builder.GetEdmModel();
    }
~~~

I'm not sure how you are creating your model, but I validated that the above code works (for reference, see https://github.com/OData/ODataSamples/tree/master/WebApi/v4/ODataContainmentSample).

Please re-activate if you are still having problems.

**Comment by NetTecture** [comment]
How do you do that without the Contained attribuite, i.e. in code? There is no documentation and i seem t obe unable to suppress the entity set creation.
