### ISSUE TITLE
5.9.1 not calling correct GET action overload with key argument when uri is composite key.

### ISSUE THREAD

**Issue by AdamCaviness** [OData/WebApi#884]
Upgrading to 5.9.1 causes the URIs with muli-key to fail. This problem does not occur in 5.9.0. For example, imagine a composite keyed entity named AddressZone. Calling a controller named AddressZones like so:
https://{{server}}:{{port}}/DataApi/AddressZones(AddressID=7D2AD7D6-6ED6-20CF-76F5-01418D2886AE,MemberID=A8FDC2CB-1857-4F13-808C-9360B26A9A0B) will return all AddressZones as the parameterless Get() action method is called instead of Get(string key).

### Assemblies affected
System.Web.OData.dll (va nuget package Microsoft.AspNet.OData 5.9.1)

### Reproduce steps
Create a composite keyed entity and try to get just one in v5.9.1.

### Expected result
The correct overload Get(string key) would be called and you'd get just one AddressZone back instead of all of them.

### Actual result
Get() is called and you get all AddressZones.

### Additional details
Take [your composite key sample](https://github.com/OData/ODataSamples/tree/master/WebApi/v4/ODataCompositeKeySample) and upgrade it to 5.9.1 and query /People(FirstName='Kate',LastName='Jones') via Postman.  You'll get all the people, not just Kate Jones.  Lastly, why did your unit tests not catch this?  Thanks!

**Comment by xuzhg** [comment]
In Web API OData V6.0 and v5.9.1, we use the following convention for the composite key parameter name, but leave the key for single key parameter.
`"key" + {CompositeKeyPropertyName}`

So, if we have the following entity type `Customer` with three keys
`
public class Customer
{
    public string StringProp { get; set; }
    public Date DateProp { get; set; }
    public Guid GuidProp { get; set; }
}
`
Therefore, for `StringProp` key property, the action parameter name should be `keyStringProp`.
Below is the contoller action looks like:
`
public class CustomersController : ODataController
{
    public IHttpActionResult Get([FromODataUri]string keyStringProp, [FromODataUri]Date keyDateProp, [FromODataUri]Guid keyGuidProp)
    {
    }
}
`
Now, you can issue a request:
`
GET http://~/odata/Customers(StringKey='my',DateKey=2016-05-11,GuidKey=46538EC2-E497-4DFE-A039-1C22F0999D6C)
`
The value of each parameter is:
1. keyStringProp == "my";
2. keyDataProp == new Date(2016, 5, 11);
3. keyGuidProp == new Guid("46538EC2-E497-4DFE-A039-1C22F0999D6C")

**Comment by AdamCaviness** [comment]
@xuzhg  This is a breaking change in a minor release, no?  We have a base controller that parses the composite keys from the single key parameter overload Get(string key). I would not have expect a minor release to stop calling our action by design.  We have hundreds of controllers so DRY is important.

**Comment by AdamCaviness** [comment]
@xuzhg Why do you call the parameterless Get() action instead of the Get(string key) action when no `"key" + {CompositeKeyPropertyName}` action exists?  It would seem semantically correct to call Get(string key) action **when no other more suitable action exists**. Choosing the Get() action will return all records and without question a uri with a composite key does not intend to get all records.  Thank you.

**Comment by vrkrishn** [comment]
Unfortunately, we have dynamic types in our application that are forwarded to the same controller. Previously (in 5.7.0) we also use the method that parses the composite keys from the single key parameter overload Get(string key).

What would be the easiest way of replicating this functionality in 5.9.1?

**Comment by vrkrishn** [comment]
Just a follow up incase anyone else runs into this issue...

In the SelectActionMethod() in RuntimeOdataConventions:
    We add the fol

```
if ((controllerContext.Request.Method == HttpMethod.Get) && (odataPath.PathTemplate == "~/entityset/key"))
            {
                //Get key segment
                var keyValueSegment = odataPath.Segments[1] as KeyValuePathSegment;
                controllerContext.RouteData.Values[ODataRouteConstants.Key] = keyValueSegment.Value;
```
