### ISSUE TITLE
DefaultODataBatchHandler headers incompatible with HttpClient

### ISSUE THREAD

**Issue by BellaCode** [OData/WebApi#885]
*The default batch handler exact string compares the Content-Type header for the request, and doesn't send a compatible Content-Type response when using HttpClient*

### Assemblies affected
OData Web API master branch

### Reproduce steps
use HttpClient to formulate a request using OData batching, use HttpClient to deserialize the response.
The Content-Type in the request will include msg-type:request which will break OData batching
The Content-Type in the response will be missing msg-type:response which will break HttpClient deserialization.

### Expected result
Batch call would succeed.  

### Actual result
OData batch request fails with 500.
Response deserialization failed with exception.  

### Additional details
For the request: ODataBatchHttpRequestMessageExtensions.ValidateODataBatchRequest does an exact string compare for the ContentType property.  It should parse out the parts by semi-colon, or do a IndexOf (case-insensitive).

For the response: ODataBatchContent ctor uses MediaTypeHeaderValue.Parse and passes a string that does not contain msg-type:response.   If the request has a msg-type:request, then msg-type:response should be included in the Content-Type header of the response.

**Comment by BellaCode** [comment]
Example of fixing up the request headers:

            var client = new HttpClient();
            client.Timeout = TimeSpan.FromSeconds(300);
            client.DefaultRequestHeaders.Add("Authorization", $"Basic {_config.EncodedPAT}");
            MultipartContent content = new MultipartContent("mixed", $"batch_{batchIdString}");
            var contentId = 1;
            foreach (var url in urls)
            {
                var message = new HttpRequestMessage(HttpMethod.Get, url);
                var messageContent = new HttpMessageContent(message);

                if (fixupHeaders)
                {
                    // HttpMessageContent Content-Type will have "application/http; msgtype=request;"
                    // This breaks OData (probably a bug in their media type checking)
                    // I fix it by setting the Content-Type manually.
                    if (messageContent.Headers.Contains("Content-Type"))
                    {
                        messageContent.Headers.Remove("Content-Type");
                    }
                    messageContent.Headers.Add("Content-Type", "application/http");

                    // OData requires these headers to batch
                    messageContent.Headers.Add("Content-Transfer-Encoding", "binary");
                    messageContent.Headers.Add("Content-ID", contentId.ToString());
                }

                content.Add(messageContent);

                contentId++;
            }

Example of fixing up the response:

            HttpResponseMessage response = client.SendAsync(batchRequest).Result;
            if (response.StatusCode != HttpStatusCode.OK)
            {
                Console.WriteLine($"Err: {response.StatusCode.ToString()} {response.ReasonPhrase}");
            }
            else
            {
                //Reads the individual parts in the content and loads them in memory
                MultipartMemoryStreamProvider multipartresponse = response.Content.ReadAsMultipartAsync().Result;

                foreach (var responseContent in multipartresponse.Contents)
                {
                    if (fixupHeaders)
                    {
                        // ReadAsHttpResponseMessageAsync requires the Content-Type is "application/http; msgtype=response"
                        // OData does not send this msgtype, so I add it manually.
                        if (responseContent.Headers.Contains("Content-Type"))
                        {
                            responseContent.Headers.Remove("Content-Type");
                        }
                        responseContent.Headers.Add("Content-Type", "application/http; msgtype=response");
                    }
                    var responseMessage = responseContent.ReadAsHttpResponseMessageAsync().Result;
                    var responseText = responseMessage.Content.ReadAsStringAsync().Result;
                    Console.WriteLine("----- Batched Response -----");
                    Console.WriteLine(responseText);
                }
            }

**Comment by biaol-odata** [comment]
Hi BellaCode, thanks for your question. Not sure why you need to use HttpClient to handle the batch request and response. Actually OData libraries provide libraries for that purpose. One tutorial is available here: http://www.odata.org/blog/advanced-odata-tutorial-with-simple-odata-client/ (see section "Executing OData batch operations").

**Comment by biaol-odata** [comment]
If you find the answer helpful, please consider using the stackoverflow.com for sharing solutions for OData knowledge.

**Comment by biaol-odata** [comment]
I am closing this for now since this doesn't appear to be an OData issue. Feel free to re-open.
