### ISSUE TITLE
Odata V4 Actions net 452

### ISSUE THREAD

**Issue by apazureck** [OData/WebApi#887]
Hello,

I have the problem that my OData Actions are not executed. [I followed the examples](https://www.asp.net/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/odata-actions-and-functions), but I always get "Not found" response.
I tried to build your [OData Actions Example](http://aspnet.codeplex.com/SourceControl/latest#Samples/WebApi/OData/v4/ODataActionsSample/), but if I update to target net452/461 and update all nuget packages, I do not get the movie list displayed in my browser at all.

### Assemblies affected
Web API 2.2 (Microsoft.AspNet.WebApi V5.2.3) / Microsoft.AspNet.Odata V6.0.0

### Reproduce steps
1. Checkout the ODataActionsSample
2. Set Target to .NET 4.5.2
3. Update Nuget Packages

### Expected result
Should do the same as the mint condition.

### Actual result
No List is displayed

Please let me know if you need further information.

### Additional Questions
1. Which version/combination would you recommend to use?
2. Is there any tutorial on ASP.NET core web api with odata? [See also this question on SO](http://stackoverflow.com/questions/39871420/how-to-properly-integrate-odata-with-asp-net-core)
3. What would I have to do to figure out why my action is not found? I do not get any information there.

Thank you in advance.

**Comment by biaol-odata** [comment]
Hi apazureck, per my understanding OData is only supported for application targeting .NET target 4.0 or 4.5. I would recommend you don't update the target beyond .NET 4.5, which the tutorial specifies. If you are using browser and really want to figure out why it doesn't work, I would try using browser dev tools (such as [Fiddler](http://www.telerik.com/fiddler) or [Firebug](https://getfirebug.com/) to see whether further information is available.

**Comment by biaol-odata** [comment]
I am closing this issue for now because this is not necessary an OData issue. Feel free to re-open it any time.

**Comment by robertmclaws** [comment]
Um, @biaol-OData, that isn't now .NET works. Code built on .NET 4.5 runs on .NET 4.6.2. In fact, WebApi OData *targets* .NET 4.5.2 and that tutorial is dramatically out of date.. I think maybe you are misunderstanding the problem, and I would recommend that you re-open the issue

**Comment by robertmclaws** [comment]
Code built on .NET 4.5 runs on every version of NET, up to and including .NET 4.7.*

**Comment by apazureck** [comment]
Hi @robertmclaws and @biaol-odata,

Thank you for your replies and help. I filed this issue is some time ago, so I am not pretty sure what problem I had back then in particular. I guess the example is pretty outdated, but I got odata functions and actions to run on my asp.net service by now. I guess I used some other sources to get it running.

I don't think I will have the time to reproduce the problem, so please close this issue, if your example is updated.

Regards,

Andreas

**Comment by mikepizzo** [comment]
Closing, as per @apazureck. Please reactivate if you discover this is still an issue.
