### ISSUE TITLE
Complex types in delta payload seem to be broken in 6.0

### ISSUE THREAD

**Issue by mikepizzo** [OData/WebApi#891]
Complex types do not appear to be written in WebAPI 6.0 delta payloads.

### Assemblies affected
*WebAPI OData 6.0 

### Reproduce steps
Implement the following method to return a delta feed:

        public EdmChangedObjectCollection Get()
        {
            List<IEdmChangedObject> changedObjects = new List<IEdmChangedObject>();
            Microsoft.OData.Edm.IEdmEntityType entityType = ModelBuilder.GetEdmModel().FindDeclaredType("ODataService.Models.Supplier") as Microsoft.OData.Edm.IEdmEntityType;
            Microsoft.OData.Edm.IEdmComplexType addressType = ModelBuilder.GetEdmModel().FindDeclaredType("ODataService.Models.Address") as Microsoft.OData.Edm.IEdmComplexType;

                EdmDeltaEntityObject changedEntity = new EdmDeltaEntityObject(entityType);
                changedEntity.TrySetPropertyValue("Name", "Name");

                EdmComplexObject a = new EdmComplexObject(addressType);
                a.TrySetPropertyValue("City", "Redmond");
                a.TrySetPropertyValue("State", "WA");
                a.TrySetPropertyValue("ZipCode", "98053");
                a.TrySetPropertyValue("Street", "One Microsoft Way");

                changedEntity.TrySetPropertyValue("Address", a);
                changedObjects.Add(changedEntity);

            return new EdmChangedObjectCollection(entityType, changedObjects);
        }

### Expected result
*Address property should be included in payload*  

### Actual result
*Supplier is written without an address*  

### Additional details
*In 6.0, the SelectExpandNode separates complex types from other structural properties. ODataResourceSerializer.WriteResource calls new routines to serialize complex properties, but WriteDeltaResource does not.*

**Comment by xuzhg** [comment]
Yes. It's not supported in 6.0.

**Comment by mikepizzo** [comment]
This should be fixed with PR #903.
