### ISSUE TITLE
Bug in AssociationSetDiscoveryConvention for 6.0

### ISSUE THREAD

**Issue by lensgrinder** [OData/WebApi#892]
I discovered an issue while upgrading from 5.9.1 to 6.0.
Please see issue logged here for details:
https://github.com/OData/odata.net/issues/753

Likely that issue was opened in the wrong place as I hadn't yet debugged to discover the root cause in the System.Web.OData binary. The fix I provide in my post works for my case but it is quick and dirty.

**Comment by mtroth-microsoft** [comment]
This issue has been fixed.
