### ISSUE TITLE
Problem with odatacontroller inheritance above 5.7.0 version

### ISSUE THREAD

**Issue by bzuidgeest** [OData/WebApi#896]
Upon until now I have been happily working with Microsoft.AspNet.OData package version 5.7.0, but then I decided to upgrade to 5.8.0 or higher and noticed that none of my odatacontroller worked anymore. All gave a big 404 error. After reading the 404 message that no suitable controller could be found I discovered the following:

My controllers do not directly inherit from ODataController. There is an class "in between" to do some extra initialization that is shared between all ODataControllers. For example:
AccountMessagesController --> ISSODataController --> ODataController
As soon as I remove ISSODataController from the chain (AccountMessagesController --> ODataController), everything starts working again.

I could not find anything in the different release notes for 5.8.0 and above (did not test rc's between 5.7 and 5.8) that would explain this change in behavior. Hopefully someone here could explain how I can fix this.... I would hate to have to maintain the init code on a per class basis or something.

**Comment by mikepizzo** [comment]
Can you provide a simple Repo?  I am not able to reproduce against 5.9.1 or 6.0.  When I derive from a trivial derived controller.  i.e.;

~~~c#
     public class BaseController : ODataController { }
     public class ProductsController : BaseController 
     {
         // Controller Logic here
     }

~~~

ProductsController is found and used for the Products entity set.

**Comment by bzuidgeest** [comment]
While making you a simple test case I figured it out. The derived controllers are coming from a separate class library. That library was still linked to version 5.7 while the main project was upgraded to 6. It builds fine without the matching version numbers, but it will not find any controllers anymore when running....

Obvious in hindsight, but quite frustrating in the moment.

Thank you for time, I will quickly close this now
