### ISSUE TITLE
ODATA v4 - Modifying Model to have custom metadata namespace prefix defect

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#9]
I followed this example:  
  
[adding-arbitrary-data-to-odata-metadata-in-webapi](http://stackoverflow.com/questions/22207249/adding-arbitrary-data-to-odata-metadata-in-webapi)  

  
I had the exact same case. Basically the namespace prefix mapping to a
namespace does not work.  
Instead of using a prefix the $metatdata returns with an autogenerated prefix
like "p5". As I add namespaces the numeric portion increases, but, never does
my mapped prefix get used.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2167](http://aspnetwebstack.codeplex.com/workitem/2167)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	lianw
**Reported on:**	Oct 24, 2014 at 12:57 AM
**Reported by:**	williamwsmith
**Updated on:**	Tue at 8:56 AM
**Updated by:**	cysu

**Comment by LianwMS** [comment]
On *2015-01-06 16:56:09 UTC*, **cysu** commented:

Follow up.

**Comment by xuzhg** [comment]
SetNamespacePrefixMappings() function can map the namespace with a prefix. 

See [adding-arbitrary-data-to-odata-metadata-in-webapi](http://stackoverflow.com/questions/22207249/adding-arbitrary-data-to-odata-metadata-in-webapi)
