### ISSUE TITLE
$orderby with duplicate property in odata v4 failed.

### ISSUE THREAD

**Issue by thelongshot** [OData/WebApi#907]
This issue was reportedly fixed in #630, but as of 6.0.0, it is still broken.

I have a table with two links to the Node table, which has a Alias field.

Parent > ReceiveNode > Alias
Parent > SentNode > Alias

When I try to orderby on both properties ($orderby=SentNode/Alias asc, ReceiveNode/Alias asc), I get the duplicate property error.

**Comment by Malyngo** [comment]
I ran into the same issue.
I created a repository with some test code to illustrate the issue:
https://github.com/Malyngo/ODataWebapiTest

**Comment by thelongshot** [comment]
I saw your StackOverflow post, but couldn't respond.  I'm currently working around it by adding a second field to the database and setting them both to the same value.  Not the solution I want.

**Comment by mikepizzo** [comment]
@robward-ms: Any chance this is addressed by your fix in https://github.com/OData/odata.net/pull/756?

**Comment by robward-ms** [comment]
#756 fixes an issue in a different cache; a fix is still needed.

**Comment by mikepizzo** [comment]
Closing as dupe of Issue #630
