### ISSUE TITLE
Add support for functions that return heterogeneous collections of entity types

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#91]
I have three entity sets and would like to expose a function that returns a
collection whose contents are any number of objects from each of these three
sets.  

According to the CSDL specification I should be able to do this.  

[ http://docs.oasis-open.org/odata/odata/v4.0/os/part3-csdl/odata-v4.0-os-
part3-csdl.html#_Toc372793900 ](http://docs.oasis-
open.org/odata/odata/v4.0/os/part3-csdl/odata-v4.0-os-
part3-csdl.html#_Toc372793900)  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1884](http://aspnetwebstack.codeplex.com/workitem/1884)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Apr 25, 2014 at 6:25 PM
**Reported by:**    tyrius
**Updated on:** Aug 6, 2014 at 6:55 AM
**Updated by:** royoung

**Comment by mikepizzo** [comment]
This should be easy to do now with our untyped support.

**Comment by mikepizzo** [comment]
Closing due to lack of customer activity. Will re-visit based on any user feedback.
