### ISSUE TITLE
Microsoft.AspNet.WebApi.OData v5.7.0: "$orderby" not working with GUID type

### ISSUE THREAD

**Issue by vcrobe** [OData/WebApi#921]
I'm creating an ASP.NET Web API 2 project and I'm exposing an OData endpoint using the package Microsoft.AspNet.WebApi.OData v5.7.0.

When I issue an _orderby_ by a _GUID_ column it returns the data in the same way I entered it in the database (not ordered) but issuing an _orderby_ by another column of type _string_ or _int_ it works as expected.

### Assemblies affected
Microsoft.AspNet.WebApi.OData v5.7.0  

### Reproduce steps
http://localhost:21157/odata/C_Employees?$orderby=ID

The type of _ID_ is _GUID_

### Expected result
```
588e4b3c-9ad9-40a1-89da-fe39765e4d03
70c63a41-a1a8-4cd0-be9e-685aa6a1df1e
90bc0ba7-9dc3-411c-abe4-845ace740b32
```

### Actual result
```
70c63a41-a1a8-4cd0-be9e-685aa6a1df1e
90bc0ba7-9dc3-411c-abe4-845ace740b32
588e4b3c-9ad9-40a1-89da-fe39765e4d03
```

**Comment by xuzhg** [comment]
Hi, 
I have a test using the v5.7.0. It works fine at my side.
I use the following to add the reference to v5.7.0 as:
```C#
Install-Package Microsoft.AspNet.OData -version 5.7.0
```
Below is my sample codes. You can create a console application and copy the codes to execute it.
```C#
class Program
{
        static void Main(string[] args)
        {
            HttpClient client = GetClient();

            Query(client, "Customers");
            Query(client, "Customers?$orderby=Id");
        }

        public static void Query(HttpClient client, string uri)
        {
            Console.WriteLine();
            Console.WriteLine("[Request URI]: " + uri);
            string requestUir = "http://localhost/odata/" + uri;

            HttpResponseMessage response = client.GetAsync(requestUir).Result;

            if (response.Content != null)
            {
                JObject obj = JObject.Parse(response.Content.ReadAsStringAsync().Result);
                Console.WriteLine(obj);
            }
        }
        public static HttpClient GetClient()
        {
            var config = new HttpConfiguration();
            config.MapODataServiceRoute("odata", "odata", GetEdmModel());
            return new HttpClient(new HttpServer(config));
        }

        public static IEdmModel GetEdmModel()
        {
            var builder = new ODataConventionModelBuilder();
            builder.EntitySet<Customer>("Customers");
            return builder.GetEdmModel();
        }
    }

    public class Customer
    {
        public Guid Id { get; set; }
    }

    public class CustomersController : ODataController
    {
        private static IList<Customer> Customers;

        static CustomersController()
        {
            Customers = new List<Customer>();

            Customer cus = new Customer
            {
                Id = new Guid("70c63a41-a1a8-4cd0-be9e-685aa6a1df1e")
            };
            Customers.Add(cus);

            cus = new Customer
            {
                Id = new Guid("90bc0ba7-9dc3-411c-abe4-845ace740b32")
            };
            Customers.Add(cus);
            cus = new Customer
            {
                Id = new Guid("588e4b3c-9ad9-40a1-89da-fe39765e4d03")
            };
            Customers.Add(cus);
        }

        [EnableQuery]
        public IHttpActionResult Get()
        {
            return Ok(Customers);
        }
    }
```
Below is the output of my sample code. You can find it works as expect.
![image](https://cloud.githubusercontent.com/assets/9426627/23365403/f840a378-fd3d-11e6-9bc0-a7aec37cf3b0.png)

**Comment by vcrobe** [comment]
Hi @xuzhg,

I tried your example and it works then I did some transformations to your example and all transformations worked.

One of the transformations I did to your code was this

```
[EnableQuery]
public IQueryable<Customer> Get()
{
	return Customers.AsQueryable();
}
```

that is the way I'm creating my Get method.

What I realized is that my items are stored in a `DbSet<T>` instead of `List<T>`.

Here's my Get method

```
public class C_DireccionController : ODataController
{
	private readonly EntitiesContext db = new EntitiesContext();

	// GET: odata/C_Direccion
	[EnableQuery]
	public IQueryable<C_Direccion> GetC_Direccion()
	{
		return db.C_Direccion;
	}
}
```

where _EntitiesContext_ inherits from _DbContext_

Would you please try to reproduce the same example you sent me using `DbSet<T>` instead `List<T>`?

Thank you.

**Comment by xuzhg** [comment]
@vcrobe Yes. It **doesn't** work at my side if I change to use `DbContext` as below.

![image](https://cloud.githubusercontent.com/assets/9426627/23603992/29ee5d62-0292-11e7-8acf-c722641b8286.png)

It needs time to do more investigation. Is it urgency at your side?

**Comment by vcrobe** [comment]
@xuzhg it isn't urgent.

I'm using this workaround until you fix it.

```
var result = webApiService.C_Employees
	.OrderBy(x => x.ID)
	.ToList()
	// todo: Remove this when OData team fix the bug
	.OrderBy(x => x.ID)
	.ToList();
```

Thank you for your time.

**Comment by joshross4** [comment]
I just have to ask, did you find this bug because you needed to sort some collection by a unique identifier or it just happened that you noticed that your collection wasn't sorting by the unique identifier?

**Comment by vcrobe** [comment]
Yes, I found this bug because I need to query a DB and I need the result ordered by a GUID that's the key of the table.

**Comment by joshross4** [comment]
If you query the DB directly, are the GUIDs sorted as if they were casted to varchars first?

**Comment by vcrobe** [comment]
I did a few tests unsing the SQL Server Management Studio and I've realized that SQL Server is returning the rows in the same order when using _order by_  and without using _order by_

Here are the tests I did

`select * from xxx` 

and

`select * from xxx order by ID` 

return the rows in the same order

_ID_'s type is _uniqueidentifier_

what's happening?

**Comment by joshross4** [comment]
It helps to have a lot of GUIDs to see the pattern.

I wrote this to emphasize what is happening...

DECLARE @min UNIQUEIDENTIFIER = NEWID();

WHILE 1 = 1
    BEGIN

        DECLARE @test UNIQUEIDENTIFIER = NEWID();

        IF @test < @min
            BEGIN
                SET @min = @test;
                PRINT 'min is now ' + CAST(@min AS VARCHAR(36));
            END;

    END;

PRINT @min;

That will yield something like this:

min is now 6679BDFB-B10B-4F5B-8C79-14BAEF5EA729
min is now 699AF164-174C-45C1-8EED-138B6095E0E8
min is now 51903A43-50AA-4ABA-9758-0ED3A77BEFBC
min is now D09E1CB3-162B-4B20-AB79-0AC744788AC1
min is now C6E42FA8-637B-4D80-B28C-01FED7E9F1B0
min is now 44E1FA44-04F1-43E9-A1FD-00D9B92CEC75
min is now 8923ECC2-C214-437E-9EE1-00AE60926E4F
min is now F2F327B9-1CDE-4FB8-BA80-00306B6AFCC6
min is now 276B6C03-0DD9-4B38-8A39-0000381A92F9
min is now 0ADE533C-1F3A-4216-A4D5-0000350C7F45
min is now BF1E03F3-C070-440F-8F76-000033384742
min is now 9D434B54-4C74-4EF7-9EEE-000005669990
min is now 4CE02311-6211-4BE9-A411-000004D5C750
min is now 24AF8E58-CF06-45B9-BFD2-000003B70DC2
min is now 536AF466-2010-4D37-8C0E-0000024D89A6
min is now 91436B3C-9BCC-4110-83FA-000000D2499F

Can you see the pattern? It doesn’t sort from the beginning,
it sorts from the last group (in hex) first.

**Comment by vcrobe** [comment]
Thak you for your help.

Here's the explanation about how SQL Server sort a uniqueidentifier column.

So this is not a bug nor an error in the Microsoft.AspNet.WebApi.OData package

**Comment by xuzhg** [comment]
Thanks your help, @joshross4.

@vcrobe, As you said, it's not a bug in WAO. But, it's inconsistent behavior between in-memory and EntityFramework. Can we keep this issue open and let OData Team to triage more?

**Comment by vcrobe** [comment]
> it's inconsistent behavior between in-memory and EntityFramework

The inconsistency is in the way SQL Server sort the _GUID_ data type. Using _SqlGuid_ data type in .NET should solve the problem. I've not tested it yet but that's what the documentation said in the link I posted above.

> Can we keep this issue open and let OData Team to triage more?

Sure!

**Comment by gathogojr** [comment]
But not in OData WebApi but rather in how SQL Server sorts Guid data type
