### ISSUE TITLE
Enum values missing in $metadata

### ISSUE THREAD

**Issue by ll-sc** [OData/WebApi#925]
I'm using a ODataController and an ODataConventionModelBuilder; enum values are not appearing in the metadata for the service.

### Assemblies affected
WebApi 5.9.1 exhibits the behavior with missing values; WebApi 5.7 produces the expected results.

### Reproduce steps

Model looks like this:

            string ModelNamespace = "example.namespace";
            ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
            builder.ContainerName = "container";
            builder.Namespace = ModelNamespace;
            builder.OnModelCreating += ApplyLowerCamelCase;
            
            builder.EntitySet<User>(UsersEntitySetName);
            
            builder.EnumType<BitFlags>().Namespace = ModelNamespace;
            builder.EnumType<Modes>().Namespace = ModelNamespace;
            
            IEdmModel model = builder.GetEdmModel();
            
            return model;

BitFlags looks like:

    [Flags]
    [DataContract(Namespace = "example.namespace")]
    public enum BitFlags
    {
        none = 0x0,
        cream = 0x1,
        sugar = 0x2,
    }

And Modes:

    [DataContract(Namespace = ServiceModelBuilder.ModelNamespace)]
    public enum Modes
    {
        bar = 0,
        line = 1,
        graph = 2,
    }

### Expected result
$metadata contains the names of values in the enum.

### Actual result
$metadata does not contain the values for enums.

**Comment by xuzhg** [comment]
please remember to add `[EnumMember]` to the enum member if you decorate the enum type using `[DataContract]`.

for example:
```C#
[DataContract(Namespace = ServiceModelBuilder.ModelNamespace)]
public enum Modes
{
    [EnumMember]
    bar = 0,
    [EnumMember]
    line = 1,
    [EnumMember]
    graph = 2,
}
```
