### ISSUE TITLE
Can't use IHttpActionResult with dynamic entity

### ISSUE THREAD

**Issue by adrianm64** [OData/WebApi#934]
I have an action returning a dynamic entity. Returning the collection directly works fine
```
public EdmEntityObjectCollection DynamicGet() {
    ...
    return result;
}
```
but using action result just returns 406
```
public IHttpActionResult DynamicGet() {
    ...
    return this.Ok(result);
}
```

### Assemblies affected
Microsoft.OData.Core 7.0.0
Microsoft.AspNet.OData 6.0.0
Microsoft.AspNet.WebApi 5.2.3

### Expected result
< HTTP/1.1 200 OK                                                                         
< Content-Type: application/json; odata.metadata=minimal                                  
< Server: Microsoft-IIS/10.0                                                              
< OData-Version: 4.0                                                                      
< X-Powered-By: ASP.NET                                                                   
< Date: Thu, 09 Mar 2017 22:01:53 GMT                                                     
< Content-Length: 1847                                                                    
<                                                                                         
{"@odata.context":"http://localhost:53728/$metadata#Test","value":[...

### Actual result
< HTTP/1.1 406 Not Acceptable                                                             
< Server: Microsoft-IIS/10.0                                                              
< X-Powered-By: ASP.NET                                                                   
< Date: Thu, 09 Mar 2017 22:03:29 GMT                                                     
< Content-Length: 0                                                                       

### Trace

> ExecuteAsync;Invoking action 'DynamicGet()'
> ExecuteAsync;Action returned 'System.Web.Http.Results.OkNegotiatedContentResult`1[System.Object]'
> System.Net.Http.Formatting/FormUrlEncodedMediaTypeFormatter/GetPerRequestFormatterInstance;Obtaining formatter of type 'FormUrlEncodedMediaTypeFormatter' for type='Object', mediaType=''
> System.Net.Http.Formatting/FormUrlEncodedMediaTypeFormatter/GetPerRequestFormatterInstance;Will use same 'FormUrlEncodedMediaTypeFormatter' formatter
> System.Net.Http.Formatting/JQueryMvcFormUrlEncodedFormatter/GetPerRequestFormatterInstance;Obtaining formatter of type 'JQueryMvcFormUrlEncodedFormatter' for type='Object', mediaType=''
> System.Net.Http.Formatting/JQueryMvcFormUrlEncodedFormatter/GetPerRequestFormatterInstance;Will use same 'JQueryMvcFormUrlEncodedFormatter' formatter
> System.Net.Http.Formatting/DefaultContentNegotiator/Negotiate;Type='Object', formatters=[ODataMediaTypeFormatter, ODataMediaTypeFormatter, ODataMediaTypeFormatter, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, MediaTypeFormatterTracer]
> System.Net.Http.Formatting/DefaultContentNegotiator/Negotiate;Selected formatter='none', content-type='none'
> System.Web.Http.Action/ApiControllerActionInvoker/InvokeActionAsync;
> System.Web.Http.Controllers/DynamicEntitiesController/ExecuteAsync;
> Response: 406 (NotAcceptable);Content-type='none', content-length=unknown
>

**Comment by adrianm64** [comment]
Solved this myself.

Learned that the formatter is selected from the **compile** time type of the result (not the runtime type)

**Comment by xiaoxin1983** [comment]
if i need to return a dynamic object , how i do ?

```
public class UserController: ODataController
{
    public IHttpActionResult Get()
    {
        return Ok(_users.AsQueryable<dynamic>());
    }
}
```
error 406

PerRequestContentNegotiator  
public ContentNegotiationResult Negotiate(Type type, HttpRequestMessage request, IEnumerable<MediaTypeFormatter> formatters)

the parameter type is IQueryable<object> not IQueryable<User> , so can't find EdmType

how can i do if i must return a dynamic type ? i think it's working good at V5.9.0
