### ISSUE TITLE
$expand with filter does not apply filter.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#95]
As per v4 specification I should be able to add a filter to an expanded
property:  

    
    
    http://host/service/Categories?$expand=Products($filter=DiscontinuedDate eq null)

Currently the filter does not seem to be applied to the queryable source, such
that you always get back the full set of products and not a filtered list of
products.  
  
I am using version 5.2.0-alpha1-140420  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1893](http://aspnetwebstack.codeplex.com/workitem/1893)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Apr 29, 2014 at 9:31 PM
**Reported by:**	thebothead
**Updated on:**	Oct 23, 2014 at 7:56 PM
**Updated by:**	thebothead

**Comment by congysu** [comment]
This should be the same issue as #127
