### ISSUE TITLE
ef7 navigation $expand error

### ISSUE THREAD

**Issue by xiaoxin1983** [OData/WebApi#954]
hi,

Edm Entity define :

```
public class User { 
    public Guid Id {get;set;}
    public Department Department {get;set;}
}

public class Department{
    public Guid Id {get;set;}
    public ICollection<User> Users {get;set;}
}

```
http://serverhost/odata/Department/?$expand=Users
throw 406 "Argument type is not match"  exception from EF when execute query
it's working at EF6 with same code.

but http://serverhost/odata/User/?$expand=Department is OK

may you fix the bug , to support ef7 ? or it's anything wrong?

thank you !

xiaoxin

EntityFramework Version:   EF Core 1.1.0
OData Version : webapi 5.3.2 + V5.9.1, V5.10, V6.0;    aspnetcore +odata vnext
VS Version:  VS 2017

**Comment by mikepizzo** [comment]
Thanks for your feedback.

The VNext branch was an experimental branch for exploring a way to support .NET Core.  Our direction for .NET Core support for WebAPI has gone a different direction, so we are no longer investing in the VNext branch.

We are actively investing in adding support for .NET Core to the WebAPI master branch.
