### ISSUE TITLE
MissingManifestResourceException being thrown when using query string

### ISSUE THREAD

**Issue by michaelbowman1024** [OData/WebApi#955]
Please see the following StackOverflow post for full information. Essentially, a MissingManifestResourceException is thrown when trying to use OData.vNext with ASPNet Core for a Web API application.

http://stackoverflow.com/questions/43102465/missingmanifestresourceexception-thrown-when-using-odata-query-string

### Assemblies affected
I tried 6.0.1-alpha2-rtm and 6.0.2-alpha-rtm, and received the same results.

### Reproduce steps
Create an ASPNet Core Web API application in VS 2017. Utilize the AspNetCore.Odata.vNext Nuget package. Attempt to utilize a query string in the URL route for the controller decorated with the [EnableQuery] annotation.

### Expected result
The controller should return data with no errors.

### Actual result
The controller is not returning data, and is throwing a MissingManifestResourceException.

### Additional details
http://stackoverflow.com/questions/43102465/missingmanifestresourceexception-thrown-when-using-odata-query-string

**Comment by mbowman8** [comment]
It's been 2 days with no response. Would someone please respond with at least a 'we're taking a look into it', so I'm aware?

**Comment by LClauss** [comment]
this solved the issue for me when using 6.0.2-alpha-rtm

    using Microsoft.AspNetCore.OData.Query;
    [EnableQuery(Order = (int)AllowedQueryOptions.Supported)]
    [ODataRoute("Works")]
    public class WorksController : Controller
    [HttpGet]
        public IQueryable<Work> Get()
        {
           return _context.Work.AsQueryable();
        }

**Comment by ElCasagrande** [comment]
@LClauss This does not solved the issue for me.

Is there a solution?

**Comment by ElCasagrande** [comment]
I was having this issue too and to make it work I had to remove the [RouteAttribute] in my controller.

**Comment by mikepizzo** [comment]
Thanks for your feedback.

The VNext branch was an experimental branch for exploring a way to support .NET Core.  Our direction for .NET Core support for WebAPI has gone a different direction, so we are no longer investing in the VNext branch.

We are actively investing in adding support for .NET Core to the WebAPI master branch.
