### ISSUE TITLE
 Add more test cases to test ODL will compute the links if the service didn't set them

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#96]
Add more test cases to test ODL will compute the links if the service didn't
set them  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1897](http://aspnetwebstack.codeplex.com/workitem/1897)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Apr 30, 2014 at 4:32 AM
**Reported by:**    xuzhg
**Updated on:** May 5, 2014 at 9:47 AM
**Updated by:** zjufish

**Comment by xuzhg** [comment]
Close it.
