### ISSUE TITLE
No Microsoft.Data.Services 5.8.2 nuget package

### ISSUE THREAD

**Issue by pculver** [OData/WebApi#961]
Microsoft.Data.Edm, Microsoft.Data.OData, Microsoft.Data.Services.Client, and System.Spatial have all been upgraded to 5.8.2 on nuget.  The Microsoft.Data.Services package is still at 5.8.1.   This is preventing me from upgrading my project to 5.8.2 due to dependencies.

### Assemblies affected
Microsoft.Data.Services nuget

**Comment by rufio620** [comment]
+1

**Comment by identy** [comment]
+1 OData 4.0

**Comment by pculver** [comment]
This looks like it was resolved with a 5.8.3 release.
