### ISSUE TITLE
Action return type of IEnumerable<string> causes model to fail at runtime

### ISSUE THREAD

**Issue by egbertn** [OData/WebApi#966]
*Short summary (3-5 sentences) describing the issue.*  

### Assemblies affected
*Which assemblies and versions are known to be affected e.g. OData .Net lib 6.15-beta.*  
OData 6.0.0.0
EDm 7.0.0
### Reproduce steps
*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*  

var action = builder.Action("AddConnection");
    action.Parameter<MyModel>("connection");
     action.Returns<IEnumerable<string>>();

### Expected result
*What would happen if there wasn't a bug.*  
In $metadata
any property of IEnumerable<string>() is modelled as Collection(Edm.String)
### Actual result
any property of IEnumerable<string>() is modelled as 
Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="System.Collections.Generic">
<ComplexType Name="IEnumerable_1OfString" Abstract="true"/>
</Schema>

"ODataResourceSerializer cannot write an object of type 'Collection(Edm.String)'.","type":"System.Runtime.Serialization.SerializationException","stacktrace":"   at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.GetResourceType(Object graph, ODataSerializerContext writeContext)

### Additional details
*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

To FIX the behavior, change the return parameter into a string array instead of IEnumerable

action.Returns<string[]>();

**Comment by xuzhg** [comment]
Why don't you call [`ReturnsCollection<TReturnElementType>()`](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Builder/ActionConfiguration.cs#L213) method?

So, if you want your action to return a collection of string, you can call as:
```C#
ActionConfiguration action = ....
action.ReturnsCollection<string>();
```

**Comment by egbertn** [comment]
good idea :)

**Comment by xuzhg** [comment]
😄
