### ISSUE TITLE
function 'isof' validation does not work well.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#97]
[ http://host/svc/Orders?$filter=isof(%27Edm.String%27
](http://host/svc/Orders?$filter=isof\(%27Edm.String%27) )  
  
If user specify AllowedFunctions.None in ODataValidationSettings, 'isof'
function could still get passed when doing queryoption validation.  
  
In FilterQueryValidator.cs  

    
    
    private static AllowedFunctions ToODataFunction
    ...
    case "IsOf":
        result = AllowedFunctions.IsOf;
    ...

'IsOf' should be lower case according to odata spec.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1905](http://aspnetwebstack.codeplex.com/workitem/1905)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	May 4, 2014 at 4:19 AM
**Reported by:**	karata
**Updated on:**	Dec 10, 2014 at 12:31 AM
**Updated by:**	yishaigalatzer

**Comment by LianwMS** [comment]
On *2014-05-12 10:06:23 UTC*, **fenzhao** commented:

isof is not supported now and validataion will always throw for isof. 
Move it to vnext.

**Comment by VikingsFan** [comment]
It's fixed now https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Query/Validators/FilterQueryValidator.cs#L746-L748
