### ISSUE TITLE
String and Byte array values not handled properly in System.Web.OData

### ISSUE THREAD

**Issue by mtroth-microsoft** [OData/WebApi#970]
*Short summary (3-5 sentences) describing the issue.*  
When querying for a simple string such as /Suppliers(1)/CompanyName
the return value is interpreted as a collection as opposed to a simple property.
This also happens on byte array defined properties, but my repro model is not northwind.

### Assemblies affected
*Which assemblies and versions are known to be affected e.g. OData .Net lib 6.15-beta.*  
System.Web.OData for both 5.x and 6.x

### Reproduce steps
*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*  
Query /Suppliers(1)/CompanyName?randomqueryoption=foo

### Expected result
*What would happen if there wasn't a bug.*  
The company name would be return as so "Exotic Liquids"

### Actual result
*What is actually happening.*  
An array of chars is being returned "E","x","o","t","i","c"," ","L","i","q","u","i","d","s"

### Additional details
*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by xuzhg** [comment]
Both 5.x and 6.x PRs are merged. So, close it.
