### ISSUE TITLE
support non-updatable properties by core.computed or capabilities.nonupdatableproperties  annotations

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#98]
Web API work to able services to support non-updatable properties. This
implies that we need to add these annotations in the metadata document and
allow data services to set these properties.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1908](http://aspnetwebstack.codeplex.com/workitem/1908)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	May 5, 2014 at 9:15 AM
**Reported by:**	zjufish
**Updated on:**	Jun 10, 2014 at 4:33 AM
**Updated by:**	garethj

**Comment by xuzhg** [comment]
Checked in.
