### ISSUE TITLE
ODL parser should throw when there are single quotes on type name of cast

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#99]
According to V4 spec, there are no single quotes on type name of cast.  
such as: cast('Two, Four',NS.FlagsEnum)  

Now the odl parser is too lax and won't throw if there are single quotes and
support both usages  
cast('Two, Four',NS.FlagsEnum) and cast('Two, Four','NS.FlagsEnum')  

Should throw for the latter case.  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1927](http://aspnetwebstack.codeplex.com/workitem/1927)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    May 9, 2014 at 3:14 AM
**Reported by:**    fenzhao
**Updated on:** May 9, 2014 at 3:14 AM
**Updated by:** fenzhao

**Comment by xuzhg** [comment]
Related to: https://github.com/OData/odata.net/issues/575
