### ISSUE TITLE
406!406!406!

### ISSUE THREAD

**Issue by CN-jaycee** [OData/WebApi#993]
maintenance-aspnetcore
vNext=>samples/ODataSample.Web
F5
url: http://localhost:5000/odata/Products

Actual result
406 Not Acceptable.

@.@~

**Comment by xuzhg** [comment]
@CN-jaycee 

You can try:
`http://localhost:5000/a/Products`  or
`http://localhost:5000/odata1/Products` 

Both of them should work.

Thanks for your interesting in the ASP.NET Core supporting. 
`maintenance-aspnetcore` branch is still in development/maintenance status, So far, the codes in the sample project are just samples. I think we will make a plan for the ASP.NET Core supporting in the following months.  
Please let us know any further concern.
