### ISSUE TITLE
OData 6.0 is missing ODataEntityTypeSerializer

### ISSUE THREAD

**Issue by lequangnguyenqn** [OData/WebApi#995]
It have seen replaced by ODataResourceSerializer.
Anyone know how to skip serialize NULL value in OData 6.0?
Actually, I want to save the response size for client.

**Comment by xuzhg** [comment]
Before 6.0, how do you skip the null value?

**Comment by lequangnguyenqn** [comment]
Here is a example:
https://stackoverflow.com/questions/24863111/how-to-ignore-null-values-while-serializing-odata-response

**Comment by xuzhg** [comment]
@lequangnguyenqn So far, no.

Can you call this method to get the `IServiceProvider`: https://github.com/OData/WebApi/blob/master/src/System.Web.OData/Extensions/HttpRequestMessageExtensions.cs#L234

**Comment by lequangnguyenqn** [comment]
Thanks @xuzhg !
But it's seem i need to resolve it every-time i need serialize.
I need to make a custom IContentNegotiator.
Here is my code:
`public override ContentNegotiationResult Negotiate(Type type, HttpRequestMessage request, IEnumerable<MediaTypeFormatter> formatters)
        {
            var odataFormatters = ODataMediaTypeFormatters.Create(new CustomODataSerializerProvider(request.GetRequestContainer()), new DefaultODataDeserializerProvider(request.GetRequestContainer()));
            foreach (var item in odataFormatters)
            {
                item.Request = request;
            }
            return base.Negotiate(type, request, odataFormatters);
}`

Is this OK for performance to create ODataMediaTypeFormatters like that?
Before I can register OData formatters in Application_Start. Is there anyway to do like that for this version?

**Comment by gathogojr** [comment]
OData 6.0 is in maintenance mode
